import { describe, expect, test } from "vitest";
import {
  describeRetractionDetail,
  describeRetractionRefusal,
  findEmptySeparatedCharacters,
  parseRetractionOffers,
  planCharacterSeparation,
} from "../../../src/core/characterSeparate";
import { emptyCharacter, type Character } from "../../../src/models/character";

/**
 * 1つにまとめられた人物を、別人に分ける（設計書6.5.8）。
 *
 * 実データ（char_003 アジャン）を写して試す。
 */
function ajan(): Character {
  const character = emptyCharacter("char_003", "アジャン");
  character.aliases = ["アジャーノ", "アジャン様", "アジャーノさん"];
  character.summary = "村の長";
  character.role = "族長";
  character.personality = "温厚";
  character.appearedChapters = [1, 5, 6, 7, 8, 10, 15];
  character.changes = [
    {
      field: "role",
      value: "族長",
      chapters: [5],
      timepointId: null,
      evidence: null,
      note: null,
      source: "author",
    },
  ];
  character.authorNotes = "作者メモ";
  character.spoilerLevel = "staff_only";
  return character;
}

describe("別人に分ける", () => {
  test("選んだ別名が、新しい人物の名前になる", () => {
    const source = ajan();
    const plan = planCharacterSeparation(source, "アジャーノ", [source]);

    expect(plan.created.id).toBe("char_004");
    expect(plan.created.name).toBe("アジャーノ");
  });

  test("敬称違いの呼び方は一緒に移る", () => {
    const source = ajan();
    const plan = planCharacterSeparation(source, "アジャーノ", [source]);

    expect(plan.movedAliases).toEqual(["アジャーノ", "アジャーノさん"]);
    expect(plan.created.aliases).toEqual(["アジャーノさん"]);
  });

  test("関係のない別名は元に残る", () => {
    // 「アジャン様」は「アジャン」の呼び方であって、アジャーノではない
    const source = ajan();
    const plan = planCharacterSeparation(source, "アジャーノ", [source]);

    expect(plan.original.aliases).toEqual(["アジャン様"]);
  });

  test("中身は移さない。元にそのまま残る", () => {
    const source = ajan();
    const plan = planCharacterSeparation(source, "アジャーノ", [source]);

    expect(plan.original.summary).toBe("村の長");
    expect(plan.original.role).toBe("族長");
    expect(plan.original.personality).toBe("温厚");
    expect(plan.original.appearedChapters).toEqual([1, 5, 6, 7, 8, 10, 15]);
    expect(plan.original.changes).toHaveLength(1);
    expect(plan.original.authorNotes).toBe("作者メモ");

    expect(plan.created.summary).toBeNull();
    expect(plan.created.role).toBeNull();
    expect(plan.created.appearedChapters).toEqual([]);
    expect(plan.created.changes).toEqual([]);
    expect(plan.created.authorNotes).toBe("");
  });

  test("新しい人物は自動生成のまま（次の抽出で埋まるように）", () => {
    // false にすると、マージが登場話数しか足さなくなり、永久に空のままになる
    const source = ajan();
    const plan = planCharacterSeparation(source, "アジャーノ", [source]);

    expect(plan.created.autoGenerated).toBe(true);
  });

  test("公開範囲とモブ扱いは元から引き継ぐ", () => {
    // 既定（public）へ落とすと、隠していた人物が分けた拍子に資料へ出る
    const source = ajan();
    const plan = planCharacterSeparation(source, "アジャーノ", [source]);

    expect(plan.created.spoilerLevel).toBe("staff_only");
  });

  test("元の自動生成の印は、こちらでは変えない", () => {
    // 「AIに触らせない」は作者がその場で選ぶ（画面側の仕事）
    const source = ajan();
    const plan = planCharacterSeparation(source, "アジャーノ", [source]);

    expect(plan.original.autoGenerated).toBe(source.autoGenerated);
  });

  test("互いを別人として覚える", () => {
    const source = ajan();
    const plan = planCharacterSeparation(source, "アジャーノ", [source]);

    expect(plan.original.distinctFrom).toEqual([
      { name: "アジャーノ", id: "char_004" },
    ]);
    expect(plan.created.distinctFrom).toEqual([
      { name: "アジャン", id: "char_003" },
    ]);
  });

  test("読み仮名は機械で作る", () => {
    const source = ajan();
    const plan = planCharacterSeparation(source, "アジャーノ", [source]);

    expect(plan.created.reading).toBe("あじゃーの");
  });

  test("敬称を付けただけの呼び方は分けられない", () => {
    // 「アジャン様」は「アジャン」自身の呼び方であって、別人ではない。
    // ここを通すと、同じ人物が敬称の数だけ増えていく
    const source = ajan();
    expect(() =>
      planCharacterSeparation(source, "アジャン様", [source])
    ).toThrow(/自身の呼び名/);
  });

  test("2人目を分けても、1人目の記録が消えない", () => {
    const source = ajan();
    source.aliases = [...source.aliases, "ジャン"];
    const first = planCharacterSeparation(source, "アジャーノ", [source]);
    const second = planCharacterSeparation(first.original, "ジャン", [
      first.original,
      first.created,
    ]);

    expect(second.original.distinctFrom).toEqual([
      { name: "アジャーノ", id: "char_004" },
      { name: "ジャン", id: "char_005" },
    ]);
    expect(second.created.id).toBe("char_005");
  });

  test("別名に無い呼び方は分けられない", () => {
    const source = ajan();
    expect(() => planCharacterSeparation(source, "リナ", [source])).toThrow(
      /別名に/
    );
  });

  test("自分自身の名前は分けられない", () => {
    const source = ajan();
    expect(() => planCharacterSeparation(source, "アジャン", [source])).toThrow(
      /自身の呼び名/
    );
  });

  test("空の呼び名は分けられない", () => {
    const source = ajan();
    expect(() => planCharacterSeparation(source, "  ", [source])).toThrow();
  });

  test("同じ名前の人物が既にいるときは止める", () => {
    // 分けるのではなく、そちらへまとめるべき場面
    const source = ajan();
    const other = emptyCharacter("char_009", "アジャーノ");

    expect(() =>
      planCharacterSeparation(source, "アジャーノ", [source, other])
    ).toThrow(/既にいます/);
  });
});

/**
 * 分けたあとの抽出でも中身が見つからなかったら、取り下げを持ちかける
 * （作者の裁定、2026-10-03「取り下げを持ちかける」。設計書6.5.8）。
 *
 * 実機（2026-09-07）：「文佳」から「お嬢様」を分けたが、本文の「お嬢様」は
 * すべて文佳への呼びかけで、抽出のあとも空の記録が残り続けた。
 */
describe("中身の入らなかった、分けた記録", () => {
  function separated(): Character {
    const source = emptyCharacter("char_001", "密倉文佳");
    source.aliases = ["お嬢様", "文佳ちゃん"];
    source.summary = "社長令嬢";
    source.appearedChapters = [1, 2];
    return planCharacterSeparation(source, "お嬢様", [source]).created;
  }

  test("分けた直後の空の記録は、持ちかける相手になる", () => {
    const empty = separated();
    expect(
      findEmptySeparatedCharacters([empty], { updatedIds: new Set(), offered: [] })
        .map((entry) => entry.id)
    ).toEqual([empty.id]);
  });

  test("今回の抽出で更新案が出ていれば（中身が見つかった）、持ちかけない", () => {
    const empty = separated();
    expect(
      findEmptySeparatedCharacters([empty], {
        updatedIds: new Set([empty.id]),
        offered: [],
      })
    ).toEqual([]);
  });

  test("元の人物（中身がある）は相手にならない", () => {
    const source = emptyCharacter("char_001", "密倉文佳");
    source.aliases = ["お嬢様"];
    source.summary = "社長令嬢";
    const plan = planCharacterSeparation(source, "お嬢様", [source]);
    expect(
      findEmptySeparatedCharacters([plan.original], {
        updatedIds: new Set(),
        offered: [],
      })
    ).toEqual([]);
  });

  test("登場話だけ入っていても、中身が見つかったものとして持ちかけない", () => {
    const appeared = { ...separated(), appearedChapters: [3] };
    expect(
      findEmptySeparatedCharacters([appeared], { updatedIds: new Set(), offered: [] })
    ).toEqual([]);
  });

  /** 規則2：作者が書いた欄のある記録は、消す話を持ち出さない */
  test("作者メモ・資料用の補足・作者が足した項目があれば、相手にならない", () => {
    const withNotes = { ...separated(), authorNotes: "あとで考える" };
    const withExport = { ...separated(), exportNote: "補足" };
    const withCustom = { ...separated(), customFields: { 口癖: "はい" } };
    const touched = { ...separated(), autoGenerated: false };
    for (const record of [withNotes, withExport, withCustom, touched]) {
      expect(describeRetractionRefusal(record)).not.toBeUndefined();
      expect(
        findEmptySeparatedCharacters([record], { updatedIds: new Set(), offered: [] })
      ).toEqual([]);
    }
    expect(describeRetractionRefusal(separated())).toBeUndefined();
  });

  test("一度持ちかけた記録には、二度と持ちかけない（同じIDと名前）", () => {
    const empty = separated();
    expect(
      findEmptySeparatedCharacters([empty], {
        updatedIds: new Set(),
        offered: [{ id: empty.id, name: empty.name }],
      })
    ).toEqual([]);
    // IDが同じでも名前が違えば別の記録（取り下げたあとに番号が使い回された）
    expect(
      findEmptySeparatedCharacters([empty], {
        updatedIds: new Set(),
        offered: [{ id: empty.id, name: "別の人" }],
      })
    ).toHaveLength(1);
  });

  test("持ちかけた記録の覚書は、壊れていれば空として読む", () => {
    expect(parseRetractionOffers({ offered: [{ id: "char_002", name: "お嬢様" }] }))
      .toEqual([{ id: "char_002", name: "お嬢様" }]);
    expect(parseRetractionOffers({ offered: [{ id: 3 }] })).toEqual([]);
    expect(parseRetractionOffers("壊れた")).toEqual([]);
  });

  test("何を消すかを、取り下げる前に見せる", () => {
    const empty = separated();
    const detail = describeRetractionDetail(empty, "char_002_お嬢様.json");
    expect(detail).toContain("char_002_お嬢様.json");
    expect(detail).toContain("「密倉文佳」");
    expect(detail).toContain(".novelai-recovery");
  });
});
