import { describe, expect, test } from "vitest";
import {
  dropConflictValue,
  isRejectedValue,
  undoRejectedValue,
} from "../../../src/core/recordChanges";
import { mergeExtractedCharacters } from "../../../src/core/characterMerge";
import { unifyCharacters } from "../../../src/core/characterUnify";
import {
  emptyCharacter,
  parseCharacter,
  type Character,
} from "../../../src/models/character";

/**
 * 資料の食い違いを「誤り」として一度で落とす（作者の裁定、2026-09-26 深夜）。
 *
 * **再現**：これまでは設定資料パネルで［作中の変化として記録］を押してから、
 * 変化の行の［誤りを落とす］で選び直す2手が要った（0.89.5 の F4 の担当の報告）。
 * しかも昇格の途中で、誤りの値が「作者が認めた変化」として本体に入りうる。
 * 食い違いの値を直接「こちらは誤り」と落とせるようにする。
 *
 * 守ること（CLAUDE.md 規則2）：
 * - 落とすのは作者が押した値だけ。ほかの値・作者の欄には触らない
 * - 落とした値は黙って消さず、人物の記録（`rejectedValues`）へ残す
 * - 次の抽出で同じ値を食い違いへ立て直さない（キャッシュの答えは毎回マージされる）
 */

const AT = "2026-09-26T23:00:00.000Z";

/** 第1話で黒髪と読んだ本体に、第1話で銀髪が来た（同じ話の矛盾）人物 */
function conflicted(): Character {
  const character = emptyCharacter("char_001", "灯");
  character.appearance = "黒髪";
  character.authorNotes = "作者メモ";
  character.exportNote = "公開用注記";
  character.autoGenerated = false;
  character.changes = [
    {
      field: "appearance",
      value: "黒髪",
      chapters: [1],
      timepointId: null,
      note: null,
      evidence: "黒い髪を揺らして",
      source: "extracted",
    },
  ];
  character.conflicts = [
    {
      field: "appearance",
      values: ["黒髪", "銀髪"],
      chapters: [1],
      note: null,
      observations: [
        { value: "黒髪", chapters: [1], evidence: "黒い髪を揺らして" },
        { value: "銀髪", chapters: [1], evidence: "銀の髪の少女", resembles: "月島" },
      ],
    },
  ];
  return character;
}

describe("食い違いの値を誤りとして落とす", () => {
  test("後から来た値を落とす：食い違いが解け、本体はそのまま、落とした値は記録に残る", () => {
    const character = conflicted();
    const before = structuredClone(character);

    const outcome = dropConflictValue(character, "appearance", "銀髪", AT);

    expect(outcome).toBeDefined();
    // 元のレコードは書き換えない
    expect(character).toEqual(before);
    const updated = outcome!.character;
    expect(updated.conflicts).toEqual([]);
    expect(updated.appearance).toBe("黒髪");
    expect(outcome!.resolved).toBe(true);
    expect(outcome!.bodyReplaced).toBe(false);
    // **黙って消さない**：値・話数・根拠・時刻を残す
    expect(updated.rejectedValues).toEqual([
      {
        field: "appearance",
        value: "銀髪",
        chapters: [1],
        evidence: "銀の髪の少女",
        rejectedAt: AT,
      },
    ]);
    // 作者の欄には触らない
    expect(updated.authorNotes).toBe("作者メモ");
    expect(updated.exportNote).toBe("公開用注記");
    expect(updated.autoGenerated).toBe(false);
    // ほかの値の変化の記録は残る
    expect(updated.changes.map((change) => change.value)).toEqual(["黒髪"]);
  });

  test("本体の値を落とす：残った1つが本体に入る（作者がこちらを誤りと決めた）", () => {
    const outcome = dropConflictValue(conflicted(), "appearance", "黒髪", AT);

    const updated = outcome!.character;
    expect(updated.appearance).toBe("銀髪");
    expect(outcome!.bodyReplaced).toBe(true);
    expect(updated.conflicts).toEqual([]);
    // 誤りの値は変化の記録からも外す（残すと、あとで本体へ戻る道になる）
    expect(updated.changes.map((change) => change.value)).not.toContain("黒髪");
    expect(outcome!.droppedChanges).toBe(1);
    expect(updated.rejectedValues?.[0]).toMatchObject({
      field: "appearance",
      value: "黒髪",
      chapters: [1],
    });
  });

  test("値が3つあるなら、1つ落としても食い違いは残る（残りは作者がまだ決めていない）", () => {
    const character = conflicted();
    character.conflicts[0].values.push("赤髪");
    character.conflicts[0].observations!.push({ value: "赤髪", chapters: [1] });

    const outcome = dropConflictValue(character, "appearance", "銀髪", AT);

    expect(outcome!.resolved).toBe(false);
    expect(outcome!.character.conflicts).toHaveLength(1);
    expect(outcome!.character.conflicts[0].values).toEqual(["黒髪", "赤髪"]);
    expect(
      outcome!.character.conflicts[0].observations!.map((item) => item.value)
    ).toEqual(["黒髪", "赤髪"]);
  });

  test("値が3つあって本体を落としたときは、残りのどちらかを勝手に選ばない", () => {
    const character = conflicted();
    character.conflicts[0].values.push("赤髪");
    character.conflicts[0].observations!.push({ value: "赤髪", chapters: [1] });

    const outcome = dropConflictValue(character, "appearance", "黒髪", AT);

    expect(outcome!.character.appearance).toBe("黒髪");
    expect(outcome!.bodyReplaced).toBe(false);
    expect(outcome!.bodyStillDropped).toBe(true);
  });

  test("話数の記録が無い古いデータの値も落とせる", () => {
    const character = conflicted();
    character.conflicts[0].values = ["黒髪", "銀髪"];
    delete character.conflicts[0].observations;

    const outcome = dropConflictValue(character, "appearance", "銀髪", AT);

    expect(outcome!.character.conflicts).toEqual([]);
    expect(outcome!.character.rejectedValues?.[0]).toMatchObject({
      value: "銀髪",
      chapters: [],
    });
  });

  test("食い違いに無い値・無い項目なら何もしない（別の窓で先に処理された）", () => {
    expect(dropConflictValue(conflicted(), "appearance", "金髪", AT)).toBeUndefined();
    expect(dropConflictValue(conflicted(), "summary", "銀髪", AT)).toBeUndefined();
  });

  test("落とすと何も残らない食い違い（値が1つだけの壊れたデータ）は落とさない", () => {
    const character = conflicted();
    character.conflicts[0].values = ["銀髪"];
    character.conflicts[0].observations = [{ value: "銀髪", chapters: [1] }];

    expect(dropConflictValue(character, "appearance", "銀髪", AT)).toBeUndefined();
  });

  test("同じ値を2度落としても、記録は1件に畳む", () => {
    const first = dropConflictValue(conflicted(), "appearance", "銀髪", AT)!.character;
    first.conflicts = conflicted().conflicts;

    const second = dropConflictValue(first, "appearance", "銀髪", AT)!.character;

    expect(second.rejectedValues).toHaveLength(1);
  });

  test("落とした値かどうかは、項目ごとに見る", () => {
    const updated = dropConflictValue(conflicted(), "appearance", "銀髪", AT)!.character;
    expect(isRejectedValue(updated, "appearance", "銀髪")).toBe(true);
    expect(isRejectedValue(updated, "appearance", " 銀髪 ")).toBe(true);
    expect(isRejectedValue(updated, "summary", "銀髪")).toBe(false);
    expect(isRejectedValue(updated, "appearance", "黒髪")).toBe(false);
  });
});

describe("落とした値を、次の抽出で立て直さない", () => {
  test("同じ値が来ても食い違いに戻らない。違う値はこれまでどおり食い違いになる", () => {
    const dropped = dropConflictValue(conflicted(), "appearance", "銀髪", AT)!.character;
    dropped.autoGenerated = true;

    const again = mergeExtractedCharacters([dropped], [
      { data: { name: "灯", appearance: "銀髪" }, chapters: [1] },
    ]);
    expect(again.characters[0].conflicts).toEqual([]);
    expect(again.characters[0].appearance).toBe("黒髪");
    expect(again.conflicts).toEqual([]);

    const other = mergeExtractedCharacters([dropped], [
      { data: { name: "灯", appearance: "赤髪" }, chapters: [1] },
    ]);
    expect(other.characters[0].conflicts).toHaveLength(1);
  });

  test("空欄のときも、落とした値では埋めない", () => {
    const character = emptyCharacter("char_001", "灯");
    character.rejectedValues = [
      { field: "role", value: "リーダー格", chapters: [1], rejectedAt: AT },
    ];

    const result = mergeExtractedCharacters([character], [
      { data: { name: "灯", role: "リーダー格" }, chapters: [1] },
    ]);

    expect(result.characters[0].role).toBeNull();
  });
});

describe("落とした値の記録を失わない", () => {
  test("人物をまとめても、両方の記録を引き継ぐ", () => {
    const keep = emptyCharacter("char_001", "灯");
    keep.rejectedValues = [
      { field: "appearance", value: "銀髪", chapters: [1], rejectedAt: AT },
    ];
    const absorb = emptyCharacter("char_002", "あかり");
    absorb.rejectedValues = [
      { field: "role", value: "リーダー格", chapters: [2], rejectedAt: AT },
      { field: "appearance", value: "銀髪", chapters: [1], rejectedAt: AT },
    ];

    const { unified } = unifyCharacters(keep, absorb);

    expect(unified.rejectedValues?.map((entry) => entry.value).sort()).toEqual(
      ["リーダー格", "銀髪"].sort()
    );
  });

  test("読み込みで記録を保つ。壊れた形は読み込みエラーにする（黙って空にしない）", () => {
    const raw = {
      id: "char_001",
      name: "灯",
      rejectedValues: [
        { field: "appearance", value: "銀髪", chapters: [1], rejectedAt: AT },
      ],
    };
    expect(parseCharacter(raw).rejectedValues).toEqual([
      { field: "appearance", value: "銀髪", chapters: [1], rejectedAt: AT },
    ]);
    expect(() =>
      parseCharacter({ ...raw, rejectedValues: [{ field: "appearance" }] })
    ).toThrow();
    // 持っていない古い資料は、そのまま読める
    expect(parseCharacter({ id: "char_001", name: "灯" }).rejectedValues).toBeUndefined();
  });
});

/**
 * 誤りの印を外す（作者の裁定、2026-09-26）。
 *
 * 外すのは「次の抽出でまた出してよい」と許すことだけ。**食い違いの記録も
 * 本体の値も戻さない**——落としたときに本体が入れ替わっていても、それは作者が
 * 決めた結果である。
 */
describe("誤りの印を外す", () => {
  test("押した1件だけを外す。ほかの記録・本体・作者の欄は変えない", () => {
    const character = conflicted();
    character.rejectedValues = [
      { field: "appearance", value: "銀髪", chapters: [1], rejectedAt: AT },
      { field: "role", value: "リーダー格", chapters: [2], rejectedAt: AT },
    ];
    const before = structuredClone(character);

    const undone = undoRejectedValue(character, "appearance", "銀髪");

    expect(undone?.rejectedValues).toEqual([
      { field: "role", value: "リーダー格", chapters: [2], rejectedAt: AT },
    ]);
    expect(undone?.appearance).toBe("黒髪");
    expect(undone?.conflicts).toEqual(before.conflicts);
    expect(undone?.changes).toEqual(before.changes);
    expect(undone?.authorNotes).toBe("作者メモ");
    expect(undone?.exportNote).toBe("公開用注記");
    expect(undone?.autoGenerated).toBe(false);
    // 元のレコードは書き換えない
    expect(character).toEqual(before);
  });

  test("落としたときに本体が入れ替わっていても、外したあと元へ戻さない", () => {
    // 本体（黒髪）を誤りとして落とし、残った銀髪が本体に入った
    const dropped = dropConflictValue(conflicted(), "appearance", "黒髪", AT)!;
    expect(dropped.bodyReplaced).toBe(true);

    const undone = undoRejectedValue(dropped.character, "appearance", "黒髪")!;

    expect(undone.appearance).toBe("銀髪");
    expect(undone.conflicts).toEqual([]);
    expect(undone.changes).toEqual(dropped.character.changes);
    // 最後の1件を外したら、欄ごと消す（古い形の資料と同じ）
    expect(undone.rejectedValues).toBeUndefined();
    expect(isRejectedValue(undone, "appearance", "黒髪")).toBe(false);
  });

  test("外したあとの抽出では、その値がまた食い違いとして並ぶ", () => {
    const dropped = dropConflictValue(conflicted(), "appearance", "銀髪", AT)!.character;
    dropped.autoGenerated = true;
    const undone = undoRejectedValue(dropped, "appearance", "銀髪")!;

    const again = mergeExtractedCharacters([undone], [
      { data: { name: "灯", appearance: "銀髪" }, chapters: [1] },
    ]);
    expect(again.characters[0].conflicts).toHaveLength(1);
  });

  test("同じ項目に空白だけ違う記録があっても、押した記録だけを外す", () => {
    const character = emptyCharacter("char_001", "灯");
    character.rejectedValues = [
      { field: "role", value: "リーダー格", chapters: [1], rejectedAt: AT },
      { field: "role", value: "リーダー格 ", chapters: [2], rejectedAt: AT },
    ];
    const undone = undoRejectedValue(character, "role", "リーダー格 ");
    expect(undone?.rejectedValues?.map((entry) => entry.chapters)).toEqual([[1]]);
  });

  test("対象が無い（別の窓で先に外された）ときは undefined", () => {
    const character = emptyCharacter("char_001", "灯");
    expect(undoRejectedValue(character, "role", "リーダー格")).toBeUndefined();
    character.rejectedValues = [
      { field: "role", value: "リーダー格", chapters: [1], rejectedAt: AT },
    ];
    // 項目が違えば当てない
    expect(undoRejectedValue(character, "summary", "リーダー格")).toBeUndefined();
  });
});
