import { describe, expect, it } from "vitest";
import {
  initialAbilityTermOf,
  replayExtraction,
  selectChangedCharacters,
  type ExtractionBaseline,
  type ReplayChunk,
} from "../../../src/core/externalExtractMerge";
import { validateCharacterExtractResult } from "../../../src/core/characterExtractionValidation";
import { mergeExtractedCharacters } from "../../../src/core/characterMerge";
import {
  mergeExtractedAbilities,
  mergeExtractedLocations,
  mergeExtractedOrganizations,
  mergeExtractedWorldItems,
  organizationsFromAffiliations,
} from "../../../src/core/settingsMerge";
import { SettingsExtractionCollector } from "../../../src/core/settingsExtractionCollect";
import { buildKnownCharacterNames } from "../../../src/core/knownCharacterNames";
import { chunksOfSources, episodeBodySources } from "../../../src/core/episodeChunks";
import type { CharacterExtractResult } from "../../../src/prompts/characterExtract";
import { emptyCharacter, nextCharacterId } from "../../../src/models/character";
import { emptyLocation, nextLocationId } from "../../../src/models/location";
import { emptyAbilitySystem } from "../../../src/models/ability";
import type { Chunk } from "../../../src/core/chunker";

/**
 * 外部AIの抽出を、製品と同じ順で資料にする（`replayExtraction`。2026-10-02）。
 *
 * **見張るのはパリティ（同じ答えの列から、製品と同じ資料ができること）。**
 * 比べる相手は、切り出す前の `features/extractCharacters.ts` と
 * `features/extractSettings.ts` の `persist` が並べていた手順そのもの
 * （下の `productPath`）。片方だけ直ると、外部AIで抽出した作品だけ資料の
 * 中身が変わる。番号の採り方は並び順に依るので、ここが並びの検算にもなる。
 */

function chunkOf(filePath: string, chapter: number, text: string): Chunk {
  const sources = episodeBodySources(filePath, text, {
    chapterStart: chapter,
    chapterEnd: chapter,
  });
  return chunksOfSources(sources, { maxChars: 4000 })[0];
}

const CHUNK_1 = chunkOf(
  "本文/001_出会い.txt",
  1,
  "　港町に灯という娘がいた。\n　灯は毎晩、灯台に火をともした。\n" +
    "　灯は「灯守組」に入っていた。\n「わたしが守るの」と灯は言った。\n"
);
const CHUNK_2 = chunkOf(
  "本文/002_嵐.txt",
  2,
  "　嵐の夜、漁師の岩男が港町へ戻ってきた。\n　岩男は灯に礼を言った。\n" +
    "　岩男は網元組の者だった。\n"
);

const ANSWER_1: CharacterExtractResult = {
  characters: [
    {
      name: "灯",
      aliases: [],
      entityType: "person",
      summary: "毎晩、灯台に火をともす娘",
      affiliation: "灯守組",
      evidence: "灯は毎晩、灯台に火をともした",
    },
  ],
  locations: [
    { name: "港町", description: "灯の暮らす海辺の町", evidence: "港町に灯という娘がいた" },
    { name: "灯台", description: "灯が毎晩火をともす塔", evidence: "灯台に火をともした" },
  ],
};
const ANSWER_2: CharacterExtractResult = {
  characters: [
    {
      name: "岩男",
      aliases: [],
      entityType: "person",
      role: "漁師",
      affiliation: "網元組",
      evidence: "漁師の岩男が港町へ戻ってきた",
    },
    // 本文に根拠の無い人物（検算で落ちる）
    { name: "谷村修一", aliases: [], entityType: "person" },
  ],
};

function baseline(): ExtractionBaseline {
  return {
    characters: [emptyCharacter(nextCharacterId([]), "灯")],
    abilities: [],
    locations: [emptyLocation(nextLocationId([]), "港町")],
    organizations: [],
    world: [],
  };
}

/**
 * 切り出す前の製品の手順（`extractCharacters.ts` の輪と、そのあとのマージ、
 * `extractSettings.ts` の `persist`）。**比べるための参照で、写しを製品に戻さない。**
 */
function productPath(chunks: ReplayChunk[], base: ExtractionBaseline) {
  const existingCharacterNames = buildKnownCharacterNames(base.characters, []);
  const authorEditedNames = base.characters
    .filter((character) => character.autoGenerated === false)
    .map((character) => character.name);
  const existingSettingNames = {
    abilities: base.abilities.flatMap((item) => [item.name, ...item.aliases]),
    locations: base.locations.flatMap((item) => [item.name, ...item.aliases]),
    organizations: base.organizations.flatMap((item) => [item.name, ...item.aliases]),
  };
  const settings = new SettingsExtractionCollector(null);
  const extractedAll: Array<{ data: CharacterExtractResult["characters"][number]; chapters: number[] }> = [];
  for (const { chunk, parsed } of chunks) {
    const validated = validateCharacterExtractResult(parsed, chunk, {
      knownNames: existingCharacterNames,
      authorEditedNames,
      knownRecordNames: buildKnownCharacterNames(base.characters, extractedAll),
    });
    extractedAll.push(...validated.accepted);
    settings.collect(parsed, chunk, existingSettingNames);
  }
  const merged = mergeExtractedCharacters(base.characters, extractedAll);
  const changed = selectChangedCharacters(merged.characters, merged.changedIds);
  const ids = new Set(base.characters.map((character) => character.id));

  const collected = settings.candidates();
  const existingLocations = collected.locations.length > 0 ? base.locations : [];
  const existingOrganizations =
    collected.organizations.length > 0 || collected.affiliations.length > 0
      ? base.organizations
      : [];
  const abilityMerge = mergeExtractedAbilities([], [...collected.abilities]);
  const locationMerge = mergeExtractedLocations(existingLocations, [...collected.locations]);
  const organizationMerge = mergeExtractedOrganizations(existingOrganizations, [
    ...collected.organizations,
  ]);
  const fromAffiliations = organizationsFromAffiliations(
    organizationMerge.organizations,
    [...collected.affiliations],
    locationMerge.locations
  );
  const worldMerge = mergeExtractedWorldItems([], [...collected.worldItems]);
  const changedOrganizationIds = new Set([
    ...organizationMerge.changedIds,
    ...fromAffiliations.changedIds,
  ]);
  return {
    createdCharacters: changed.filter((character) => !ids.has(character.id)),
    updatedCharacters: changed.filter((character) => ids.has(character.id)),
    locations: locationMerge.locations.filter((item) =>
      locationMerge.changedIds.includes(item.id)
    ),
    organizations: fromAffiliations.organizations.filter((item) =>
      changedOrganizationIds.has(item.id)
    ),
    abilities: abilityMerge.abilities,
    world: worldMerge.items,
  };
}

/** 新規と変更を分けて返すので、並びはIDで揃えてから比べる */
function byId<T extends { id: string }>(records: T[]): T[] {
  return [...records].sort((a, b) => a.id.localeCompare(b.id));
}

describe("replayExtraction——製品の手順とのパリティ", () => {
  const chunks: ReplayChunk[] = [
    { chunk: CHUNK_1, parsed: ANSWER_1 },
    { chunk: CHUNK_2, parsed: ANSWER_2 },
  ];

  it("同じ答えの列から、製品と同じ新規レコード・同じ変更ができる", () => {
    const expected = productPath(chunks, baseline());
    const actual = replayExtraction({
      chunks,
      baseline: baseline(),
      initialAbilityTerm: null,
    });

    // 中身まで比べる（件数だけだと、番号や欄の取り違えを見逃す）
    expect(actual.characters.created).toEqual(expected.createdCharacters);
    expect(actual.characters.updated).toEqual(expected.updatedCharacters);
    expect(byId([...actual.locations.created, ...actual.locations.updated])).toEqual(
      byId(expected.locations)
    );
    expect(
      byId([...actual.organizations.created, ...actual.organizations.updated])
    ).toEqual(byId(expected.organizations));
    expect(actual.abilities.created).toEqual(expected.abilities);
    expect(actual.world.created).toEqual(expected.world);

    // 中身の当たりも見ておく（パリティだけだと、両方が空でも通る）
    expect(actual.characters.created.map((item) => item.name)).toEqual(["岩男"]);
    expect(actual.characters.updated.map((item) => item.name)).toEqual(["灯"]);
    expect(actual.locations.created.map((item) => item.name)).toEqual(["灯台"]);
    expect(actual.locations.updated.map((item) => item.name)).toEqual(["港町"]);
    expect(actual.organizations.created.map((item) => item.name).sort()).toEqual(
      ["灯守組", "網元組"].sort()
    );
    expect(actual.rejectedCharacters.map((item) => item.name)).toEqual(["谷村修一"]);
  });

  it("並びが変われば番号の採り方も変わる（並べるのは呼ぶ側の仕事）", () => {
    const forward = replayExtraction({ chunks, baseline: baseline(), initialAbilityTerm: null });
    const backward = replayExtraction({
      chunks: [...chunks].reverse(),
      baseline: baseline(),
      initialAbilityTerm: null,
    });
    const idsOf = (result: typeof forward) =>
      result.organizations.created.map((item) => `${item.id}:${item.name}`);
    expect(idsOf(forward)).not.toEqual(idsOf(backward));
  });
});

describe("initialAbilityTermOf", () => {
  it("作者が確定させた総称だけを引き継ぐ（製品と同じ）", () => {
    expect(initialAbilityTermOf(undefined)).toBeNull();
    expect(initialAbilityTermOf({ ...emptyAbilitySystem(), abilityTerm: "魔法" })).toBeNull();
    expect(
      initialAbilityTermOf({
        ...emptyAbilitySystem(),
        abilityTerm: "異能",
        autoGenerated: false,
      })
    ).toBe("異能");
  });
});
