import { describe, expect, test } from "vitest";
import {
  assembleCharacterReview,
  describeCharacterReviewItem,
  type PendingUpdate,
} from "../../../src/core/pendingReview";
import { settlePendingRejectedValues } from "../../../src/core/recordChanges";
import { emptyCharacter, type Character } from "../../../src/models/character";

/**
 * 承認の出口でも、作者が「誤り」として落とした値を並べない（精査の続き、2026-09-26）。
 *
 * **再現**：0.89.11 で外部AIの提案（`novel.propose`）は落とした値を取り下げる
 * ようにしたが、**作者が値を落とす前に**承認待ちへ置かれていた案は、
 * 積んだ時点の写しのまま「設定資料更新分反映」に並ぶ。承認すると、作者が
 * 誤りと決めた値が本体へ戻る。
 *
 * 退けた関係（`settlePendingRelations`）と同じ形で、組み立ての前に外す。
 * 外したことは黙らず、一行の説明に件数を出す。
 */

const AT = "2026-09-26T23:00:00.000Z";

/** 台帳の人物：外見は黒髪。作者が「銀髪」を誤りとして落としてある */
function ledger(): Character {
  const character = emptyCharacter("char_001", "灯");
  character.appearance = "黒髪";
  character.role = "見習い";
  character.rejectedValues = [
    {
      field: "appearance",
      value: "銀髪",
      chapters: [1],
      evidence: "銀の髪の少女",
      rejectedAt: AT,
    },
  ];
  return character;
}

/** 落とす前に積まれた外部AIの案：外見を銀髪に、役割を案内役に */
function staleProposal(current: Character): PendingUpdate {
  const { rejectedValues: _dropped, ...before } = current;
  return {
    character: { ...before, appearance: "銀髪", role: "案内役" },
    filePath: "pending-characters/char_001.json",
    source: "external",
    reason: "第3話の描写に合わせる",
  };
}

describe("承認待ちの案から、作者が落とした値を外す", () => {
  test("落とした値は差分に並ばず、ほかの欄の提案は残る", () => {
    const current = ledger();
    const { items, stale } = assembleCharacterReview(
      [staleProposal(current)],
      [current],
      []
    );

    expect(stale).toHaveLength(0);
    expect(items).toHaveLength(1);
    const item = items[0];
    const labels = item.diff.changes.map((change) => change.label);
    expect(labels).not.toContain("外見");
    expect(labels).toContain("役割");
    // 承認したときに書かれる形でも、本体の値はいまのまま
    expect(item.update.character.appearance).toBe("黒髪");
    expect(item.update.character.role).toBe("案内役");
    // **落とした記録は台帳の側が正**（写しの古い記録で巻き戻さない）
    expect(item.update.character.rejectedValues).toEqual(current.rejectedValues);
    expect(item.skippedRejectedValues).toEqual([
      { field: "appearance", value: "銀髪" },
    ]);
  });

  test("外したことを黙らない：一行の説明に件数を出す", () => {
    const current = ledger();
    const { items } = assembleCharacterReview([staleProposal(current)], [current], []);

    expect(describeCharacterReviewItem(items[0])).toContain(
      "作者が誤りとして落とした値なので除きました（1件）"
    );
  });

  test("前後の空白だけ違っても、落とした値として扱う（isRejectedValue と同じ判定）", () => {
    const current = ledger();
    const proposal = staleProposal(current);
    proposal.character = { ...proposal.character, appearance: " 銀髪　" };
    const { items } = assembleCharacterReview([proposal], [current], []);

    expect(items[0].update.character.appearance).toBe("黒髪");
    expect(items[0].skippedRejectedValues).toHaveLength(1);
  });

  test("案が落とした値だけなら、並べずに片付ける（理由は落とした値）", () => {
    const current = ledger();
    const proposal = staleProposal(current);
    proposal.character = { ...proposal.character, role: current.role };
    const { items, stale, staleReasons } = assembleCharacterReview(
      [proposal],
      [current],
      []
    );

    expect(items).toHaveLength(0);
    expect(stale).toHaveLength(1);
    expect(staleReasons.get(proposal.filePath)).toBe("rejectedValuesOnly");
  });

  test("落としていない値は、似ていても外さない", () => {
    const current = ledger();
    const proposal = staleProposal(current);
    proposal.character = { ...proposal.character, appearance: "銀髪の少女" };
    const { items } = assembleCharacterReview([proposal], [current], []);

    expect(items[0].update.character.appearance).toBe("銀髪の少女");
    expect(items[0].skippedRejectedValues).toEqual([]);
    expect(describeCharacterReviewItem(items[0])).not.toContain("誤りとして落とした");
  });
});

describe("承認待ちの案の食い違い・変化の記録からも、落とした値を外す", () => {
  /**
   * **再現**：案は積んだ時点の写しなので、作者が値を落とす前の食い違い
   * （黒髪／銀髪）と変化の記録（銀髪）をそのまま持っている。差分の画面には
   * 出ないまま、承認すると誤りの値を含んだ食い違いが台帳へ戻る。
   */
  function staleWithRecords(current: Character): PendingUpdate {
    const proposal = staleProposal(current);
    proposal.character = {
      ...proposal.character,
      appearance: current.appearance,
      authorNotes: "作者メモ",
      autoGenerated: false,
      conflicts: [
        {
          field: "appearance",
          values: ["黒髪", "銀髪"],
          chapters: [1],
          note: null,
          observations: [
            { value: "黒髪", chapters: [1], evidence: "黒い髪を揺らして" },
            { value: "銀髪", chapters: [1], evidence: "銀の髪の少女" },
          ],
        },
        {
          field: "affiliation",
          values: ["騎士団", "近衛", "銀髪"],
          chapters: [2],
          note: null,
        },
      ],
      changes: [
        {
          field: "appearance",
          value: " 銀髪",
          chapters: [3],
          timepointId: null,
          note: null,
          evidence: null,
          source: "extracted",
        },
        {
          field: "role",
          value: "案内役",
          chapters: [3],
          timepointId: null,
          note: null,
          evidence: null,
          source: "extracted",
        },
      ],
    };
    return proposal;
  }

  test("落とした値を外し、値が1つになった食い違いは記録ごと外す", () => {
    const current = { ...ledger(), authorNotes: "作者メモ", autoGenerated: false };
    const { items } = assembleCharacterReview([staleWithRecords(current)], [current], []);
    const approved = items[0].update.character;

    // 外見の食い違いは「黒髪」だけになったので解けた
    expect(approved.conflicts.map((entry) => entry.field)).toEqual(["affiliation"]);
    // 別の項目の同じ文字は、落とした値ではない（項目ごとに当てる）
    expect(approved.conflicts[0].values).toEqual(["騎士団", "近衛", "銀髪"]);
    // 変化の記録からも外す（前後の空白だけ違うものも同じ値）。ほかの記録は残す
    expect(approved.changes.map((change) => change.value)).toEqual(["案内役"]);
    // 本体の値は入れ替えない（件1で守っている）
    expect(approved.appearance).toBe("黒髪");
    // 作者の欄と autoGenerated には触らない
    expect(approved.authorNotes).toBe("作者メモ");
    expect(approved.autoGenerated).toBe(false);
  });

  test("値が2つ以上残る食い違いは、落とした値だけを外して残す", () => {
    const current = ledger();
    const proposal = staleWithRecords(current);
    proposal.character.conflicts[0] = {
      field: "appearance",
      values: ["黒髪", "銀髪", "茶髪"],
      chapters: [1],
      note: null,
      observations: [
        { value: "黒髪", chapters: [1] },
        { value: "銀髪", chapters: [1] },
        { value: "茶髪", chapters: [1] },
      ],
    };
    const settled = settlePendingRejectedValues(current, proposal.character);
    const appearance = settled.character.conflicts.find(
      (entry) => entry.field === "appearance"
    )!;

    expect(appearance.values).toEqual(["黒髪", "茶髪"]);
    expect(appearance.observations?.map((item) => item.value)).toEqual(["黒髪", "茶髪"]);
  });

  test("外した件数は「除きました（N件）」に合算する（同じ項目・同じ値は1件に数える）", () => {
    const current = ledger();
    const proposal = staleWithRecords(current);
    // 本体の欄にも誤りの値（件1の形）。食い違い・変化の記録と同じ値なので1件
    proposal.character = { ...proposal.character, appearance: "銀髪" };
    const { items } = assembleCharacterReview([proposal], [current], []);

    expect(items[0].skippedRejectedValues).toEqual([
      { field: "appearance", value: "銀髪" },
    ]);
    expect(describeCharacterReviewItem(items[0])).toContain(
      "——作者が誤りとして落とした値なので除きました（1件）"
    );
  });
});

describe("settlePendingRejectedValues", () => {
  test("いまの本体がその値なら、差分にならないので数えない", () => {
    // 食い違いが残っていて、本体に誤りの値が入ったまま（bodyStillDropped）の人物
    const current = { ...ledger(), appearance: "銀髪" };
    const settled = settlePendingRejectedValues(current, { ...current });

    expect(settled.character.appearance).toBe("銀髪");
    expect(settled.skipped).toEqual([]);
  });

  test("作者の欄には触らない", () => {
    const current = { ...ledger(), authorNotes: "作者メモ", exportNote: "注記" };
    const pending = { ...current, appearance: "銀髪", authorNotes: "作者メモ" };
    const settled = settlePendingRejectedValues(current, pending);

    expect(settled.character.authorNotes).toBe("作者メモ");
    expect(settled.character.exportNote).toBe("注記");
  });
});
