import { describe, expect, test } from "vitest";
import {
  buildPendingSettingsPayload,
  describePendingUpdateCounts,
  diffSettingsRecord,
  mergePendingSettingsRecord,
  parsePendingSettingsPayload,
} from "../../../src/core/pendingSettingsMerge";
import { emptyLocation, type Location } from "../../../src/models/location";
import { emptyOrganization } from "../../../src/models/organization";
import { emptyAbility } from "../../../src/models/ability";
import { SUMMARY_MAX_CHARS } from "../../../src/core/summaryLimit";

/**
 * 人物以外（能力・組織・場所・世界観）の更新案を、「更新分を反映」で
 * 反映するときの取り込み（作者の裁定、2026-09-23 問11 B）。
 *
 * **マージはコードが行う**（CLAUDE.md 規則3）。更新案はレコード丸ごとの
 * 写しだが、そのまま保存しない——積んでから承認までのあいだに作者が
 * 書いたものを、古い写しで巻き戻さないため。
 */

function location(overrides: Partial<Location> = {}): Location {
  return { ...emptyLocation("loc_001", "王都"), ...overrides };
}

describe("取り込み（規則2：作者のデータを上書きしない）", () => {
  test("作者メモと資料用の補足は、更新案が違っていても変えない", () => {
    const current = location({ authorNotes: "作者の覚え", exportNote: "補足" });
    const proposal = location({
      authorNotes: "AIが書いた覚え",
      exportNote: "AIの補足",
      description: "石造りの城壁に囲まれた都",
    });

    const merged = mergePendingSettingsRecord("location", current, proposal);

    expect(merged.authorNotes).toBe("作者の覚え");
    expect(merged.exportNote).toBe("補足");
    expect((merged as Location).description).toBe("石造りの城壁に囲まれた都");
  });

  test("作者が確定させた記録（autoGenerated: false）は、登場話数の追記だけ", () => {
    const current = location({
      autoGenerated: false,
      description: "作者が書いた説明",
      appearedChapters: [1, 3],
    });
    const proposal = location({
      description: "AIの説明",
      region: "北部",
      appearedChapters: [3, 5],
    });

    const merged = mergePendingSettingsRecord("location", current, proposal) as Location;

    expect(merged.description).toBe("作者が書いた説明");
    expect(merged.region).toBeNull();
    expect(merged.appearedChapters).toEqual([1, 3, 5]);
    expect(merged.autoGenerated).toBe(false);
  });

  test("更新案で空の項目は、今の値を消さない", () => {
    const current = location({ region: "北部", description: "城壁の都" });
    const proposal = location({ region: null, description: "" });

    const merged = mergePendingSettingsRecord("location", current, proposal) as Location;

    expect(merged.region).toBe("北部");
    expect(merged.description).toBe("城壁の都");
  });

  test("別名は足すだけで、今の別名を消さない", () => {
    const current = location({ aliases: ["都"] });
    const proposal = location({ aliases: ["王の都"] });

    const merged = mergePendingSettingsRecord("location", current, proposal);

    expect(merged.aliases).toEqual(["都", "王の都"]);
  });

  test("名前・IDは更新案で変えない（改名は作者の操作）", () => {
    const current = location();
    const proposal = { ...location(), name: "新王都" };

    const merged = mergePendingSettingsRecord("location", current, proposal);

    expect(merged.name).toBe("王都");
    expect(merged.id).toBe("loc_001");
  });

  test("紹介文の長さはコードで揃える", () => {
    const merged = mergePendingSettingsRecord(
      "location",
      location(),
      location({ summary: "あ".repeat(SUMMARY_MAX_CHARS + 20) })
    ) as Location;
    expect((merged.summary ?? "").length).toBeLessThanOrEqual(SUMMARY_MAX_CHARS);
  });

  test("食い違いの記録は足すだけで、同じものは二重にしない", () => {
    const conflict = {
      field: "region",
      values: ["北部", "南部"],
      chapters: [2, 5],
      note: null,
    };
    const current = location({ conflicts: [conflict] });
    const proposal = location({
      conflicts: [
        conflict,
        { field: "description", values: ["城", "砦"], chapters: [4], note: null },
      ],
    });

    const merged = mergePendingSettingsRecord("location", current, proposal);

    expect(merged.conflicts).toHaveLength(2);
  });

  test("追加項目の値は、入っているものだけ取り込み、今の値を消さない", () => {
    const current = location({ customFields: { field_001: "温暖", field_002: "十万" } });
    const proposal = location({ customFields: { field_001: "寒冷" } });

    const merged = mergePendingSettingsRecord("location", current, proposal);

    expect(merged.customFields).toEqual({ field_001: "寒冷", field_002: "十万" });
  });

  test("能力の使い手は足すだけ", () => {
    const current = { ...emptyAbility("abil_001", "神術"), userNames: ["灯"] };
    const proposal = { ...emptyAbility("abil_001", "神術"), userNames: ["湊"] };

    const merged = mergePendingSettingsRecord("ability", current, proposal);

    expect((merged as typeof current).userNames).toEqual(["灯", "湊"]);
  });
});

describe("差分（作者が見て決める材料）", () => {
  test("変わる項目を日本語の見出しで並べる", () => {
    const current = location({ region: "北部" });
    const merged = location({ region: "南部", description: "港の都" });

    const diff = diffSettingsRecord("location", current, merged, [
      { key: "field_001", label: "気候", hint: "", multiline: false },
    ]);

    expect(diff.name).toBe("王都");
    expect(diff.changes.map((change) => change.label)).toEqual(["地域", "説明"]);
    expect(diff.changes[0]).toMatchObject({ before: "北部", after: "南部" });
  });

  test("追加項目の変化も、定義の見出しで出す", () => {
    const diff = diffSettingsRecord(
      "location",
      location(),
      location({ customFields: { field_001: "温暖" } }),
      [{ key: "field_001", label: "気候", hint: "", multiline: false }]
    );
    expect(diff.changes).toEqual([{ label: "気候", before: "", after: "温暖" }]);
  });

  test("何も変わらなければ空", () => {
    expect(diffSettingsRecord("location", location(), location(), []).changes).toEqual([]);
  });

  test("組織は種別と上位組織を見る", () => {
    const diff = diffSettingsRecord(
      "organization",
      emptyOrganization("org_001", "ギルド"),
      { ...emptyOrganization("org_001", "ギルド"), parent: "王国", category: "商会" },
      []
    );
    expect(diff.changes.map((change) => change.label)).toEqual(["種別", "上位組織"]);
  });
});

describe("承認待ちのファイルの形", () => {
  test("作った形を読み直せる", () => {
    const record = location({ region: "北部" });
    const payload = buildPendingSettingsPayload("location", record, {
      source: "chat",
      reason: "相談で決めた",
    });
    const parsed = parsePendingSettingsPayload(JSON.parse(JSON.stringify(payload)));
    expect(parsed.recordKind).toBe("location");
    expect((parsed.record as Location).region).toBe("北部");
    expect(parsed.source).toBe("chat");
    expect(parsed.reason).toBe("相談で決めた");
  });

  test("種類の分からない案は読まない（どの台帳へ入れるか決められない）", () => {
    expect(() =>
      parsePendingSettingsPayload({ recordKind: "locaton", record: location() })
    ).toThrow();
    expect(() => parsePendingSettingsPayload(location())).toThrow();
  });

  test("種類とIDの形が食い違う案は読まない", () => {
    expect(() =>
      parsePendingSettingsPayload({
        recordKind: "organization",
        record: location(),
      })
    ).toThrow();
  });

  test("新しく作る案は、まだ扱わない（黙って更新として入れない）", () => {
    expect(() =>
      parsePendingSettingsPayload({
        recordKind: "location",
        kind: "creation",
        record: location(),
      })
    ).toThrow();
  });
});

describe("件数の知らせ", () => {
  test("種類ごとの内訳を添える", () => {
    expect(describePendingUpdateCounts({ character: 3, location: 1 })).toBe(
      "反映待ちの更新が 4 件あります（人物 3・場所 1）"
    );
  });

  test("0件なら何も出さない", () => {
    expect(describePendingUpdateCounts({})).toBe("");
    expect(describePendingUpdateCounts({ character: 0 })).toBe("");
  });
});
