import { describe, expect, it } from "vitest";
import {
  buildNewCharacterRecords,
  buildPlotCharacterUpdates,
  inheritPendingCreationFields,
  parsePlotCharacters,
  plotCharactersDigest,
  PENDING_CREATION_ID,
} from "../../../src/core/plotCharacterSync";
import { emptyCharacter, type Character } from "../../../src/models/character";
import { sha256Text } from "../../../src/core/hash";

/**
 * plot.md の「主要登場人物」から設定資料への差分反映（設計書6.4.9）。
 *
 * **プロットは自由に書けるMarkdownである**（6.4.3）ので、読めるのは
 * 箇条書きの決まった形だけになる。読めなかった行は黙って飛ばさず
 * `unparsed` に積み、件数を作者へ伝える。
 */

function character(
  id: string,
  name: string,
  overrides: Partial<Character> = {}
): Character {
  return { ...emptyCharacter(id, name), ...overrides };
}

describe("主要登場人物の節を読む", () => {
  it("コロン・ダッシュ・空白の3つの区切りを読む", () => {
    const parsed = parsePlotCharacters(
      ["- 月島灯：主人公。十七歳。", "- 白瀬澪——灯の親友", "- 三門太志 担任の教師"].join(
        "\n"
      )
    );

    expect(parsed.entries).toEqual([
      { name: "月島灯", summary: "主人公。十七歳。" },
      { name: "白瀬澪", summary: "灯の親友" },
      { name: "三門太志", summary: "担任の教師" },
    ]);
    expect(parsed.unparsed).toEqual([]);
  });

  it("半角コロンでも読む", () => {
    const parsed = parsePlotCharacters("- 灯: 主人公");
    expect(parsed.entries).toEqual([{ name: "灯", summary: "主人公" }]);
  });

  it("名前だけの行は、説明を空にして拾う", () => {
    const parsed = parsePlotCharacters("- 密倉文佳");
    expect(parsed.entries).toEqual([{ name: "密倉文佳", summary: "" }]);
    expect(parsed.unparsed).toEqual([]);
  });

  it("中黒と長音符は区切りにしない（カタカナの姓名が割れる）", () => {
    const parsed = parsePlotCharacters(
      ["- ヴォイド・コンストラクタ：父親", "- ギルドマスター 受付の主"].join("\n")
    );
    expect(parsed.entries).toEqual([
      { name: "ヴォイド・コンストラクタ", summary: "父親" },
      { name: "ギルドマスター", summary: "受付の主" },
    ]);
  });

  it("読めない行は unparsed に積む（黙って飛ばさない）", () => {
    const parsed = parsePlotCharacters(
      ["この節はあとで書き直す。", "- 灯：主人公"].join("\n")
    );
    expect(parsed.entries).toEqual([{ name: "灯", summary: "主人公" }]);
    expect(parsed.unparsed).toEqual(["この節はあとで書き直す。"]);
  });

  it("空の節では、何も拾わず何も報せない", () => {
    expect(parsePlotCharacters("")).toEqual({ entries: [], unparsed: [] });
    expect(parsePlotCharacters("\n\n- \n")).toEqual({
      entries: [],
      unparsed: [],
    });
    expect(parsePlotCharacters("<!-- ここに書きます -->")).toEqual({
      entries: [],
      unparsed: [],
    });
  });

  it("字下げした箇条書きは、直前の人物の説明の続きとして読む", () => {
    const parsed = parsePlotCharacters(
      ["- 灯：主人公", "  - 十七歳", "  - 幽霊が見える"].join("\n")
    );
    expect(parsed.entries).toEqual([
      { name: "灯", summary: "主人公 十七歳 幽霊が見える" },
    ]);
    expect(parsed.unparsed).toEqual([]);
  });
});

describe("節の内容ハッシュ", () => {
  const entries = [
    { name: "灯", summary: "主人公" },
    { name: "澪", summary: "親友" },
  ];

  it("同じ内容なら同じ", () => {
    expect(plotCharactersDigest(entries)).toBe(plotCharactersDigest([...entries]));
  });

  it("並べ替えただけでは変わらない（同じ提案を積み直さない）", () => {
    expect(plotCharactersDigest([...entries].reverse())).toBe(
      plotCharactersDigest(entries)
    );
  });

  it("説明が変われば変わる", () => {
    expect(
      plotCharactersDigest([{ name: "灯", summary: "主人公" }])
    ).not.toBe(plotCharactersDigest([{ name: "灯", summary: "主人公。十七歳" }]));
  });
});

describe("更新案の組み立て", () => {
  it("居ない名前は新規、同名で紹介文が違えば更新", () => {
    const existing = [character("char_001", "灯", { summary: "主人公" })];
    const plan = buildPlotCharacterUpdates(
      [
        { name: "灯", summary: "主人公。幽霊が見える。" },
        { name: "澪", summary: "灯の親友" },
      ],
      existing
    );

    expect(plan.updates).toHaveLength(1);
    expect(plan.updates[0].id).toBe("char_001");
    expect(plan.updates[0].summary).toBe("主人公。幽霊が見える。");
    expect(plan.creations).toEqual([{ name: "澪", summary: "灯の親友" }]);
    // 元のレコードは書き換えない
    expect(existing[0].summary).toBe("主人公");
  });

  it("紹介文が同じなら積まない", () => {
    const plan = buildPlotCharacterUpdates(
      [{ name: "灯", summary: "主人公" }],
      [character("char_001", "灯", { summary: "主人公" })]
    );
    expect(plan.updates).toEqual([]);
    expect(plan.creations).toEqual([]);
  });

  it("別名でも既存の人物に当てる", () => {
    const plan = buildPlotCharacterUpdates(
      [{ name: "月島灯", summary: "主人公" }],
      [character("char_001", "灯", { aliases: ["月島灯"] })]
    );
    expect(plan.updates).toHaveLength(1);
    expect(plan.updates[0].id).toBe("char_001");
    expect(plan.creations).toEqual([]);
  });

  it("名前だけの行は、既に居る人物には何も起こさない", () => {
    const plan = buildPlotCharacterUpdates(
      [{ name: "灯", summary: "" }],
      [character("char_001", "灯", { summary: "主人公" })]
    );
    expect(plan.updates).toEqual([]);
    expect(plan.creations).toEqual([]);
  });

  it("作者が確定させた人物（autoGenerated: false）は積まない", () => {
    const plan = buildPlotCharacterUpdates(
      [{ name: "灯", summary: "主人公。幽霊が見える。" }],
      [
        character("char_001", "灯", {
          summary: "主人公",
          autoGenerated: false,
        }),
      ]
    );
    expect(plan.updates).toEqual([]);
    expect(plan.skipped).toEqual([{ name: "灯", reason: "authorConfirmed" }]);
  });

  it("同じ名前の人物が複数居るときは、どれにも当てない", () => {
    const plan = buildPlotCharacterUpdates(
      [{ name: "お母さん", summary: "灯の母" }],
      [character("char_001", "お母さん"), character("char_002", "お母さん")]
    );
    expect(plan.updates).toEqual([]);
    expect(plan.creations).toEqual([]);
    expect(plan.skipped).toEqual([{ name: "お母さん", reason: "ambiguous" }]);
  });

  it("作者が「別人だ」と決めた呼び名では引き当てない（設計書6.5.8）", () => {
    const plan = buildPlotCharacterUpdates(
      [{ name: "アジャン", summary: "帝国の皇子" }],
      [
        character("char_001", "アジャーノ", {
          distinctFrom: [{ name: "アジャン", id: null }],
        }),
      ]
    );
    expect(plan.updates).toEqual([]);
    expect(plan.creations).toEqual([
      { name: "アジャン", summary: "帝国の皇子" },
    ]);
  });

  it("新規案は仮のIDで作り、抽出の新規と同じ初期値を持つ", () => {
    const [record] = buildNewCharacterRecords([
      { name: "澪", summary: "灯の親友" },
    ]);

    // 本当の番号は承認したときに採る（積んだ時点では決められない）
    expect(record.id).toBe(PENDING_CREATION_ID);
    expect(record.name).toBe("澪");
    expect(record.summary).toBe("灯の親友");
    expect(record.autoGenerated).toBe(true);
    expect(record.appearedChapters).toEqual([]);
    // 本文にはまだ出ていない（資料には「未登場（設定のみ）」と出る）
    expect(record.status).toBe("未登場");
    expect(record.authorNotes).toBe("");
  });

  it("名前だけの新規案は、紹介文を空のままにする", () => {
    const [record] = buildNewCharacterRecords([{ name: "密倉文佳", summary: "" }]);
    expect(record.summary).toBeNull();
  });

  it("長すぎる紹介文は、資料の上限まで切り詰めてから積む", () => {
    const long = "あ".repeat(200);
    const plan = buildPlotCharacterUpdates(
      [{ name: "灯", summary: long }],
      [character("char_001", "灯")]
    );
    expect(plan.updates).toHaveLength(1);
    expect([...(plan.updates[0].summary ?? "")].length).toBeLessThanOrEqual(80);
  });
});

/*
  名前の候補（設計書6.4.8）で書き足す「役名（名前）」の形。
  **「主人公（相馬 誠）」という名前の人物を作らない**
*/
describe("役名（名前）の行を読む", () => {
  it("外側が役名なら、名前と役名に分ける", () => {
    const parsed = parsePlotCharacters(
      ["- 主人公（相馬 誠）：新人", "- 向こうの業者（ガルド）——封印の業者"].join("\n")
    );
    expect(parsed.entries).toEqual([
      { name: "相馬 誠", summary: "新人", role: "主人公" },
      { name: "ガルド", summary: "封印の業者", role: "向こうの業者" },
    ]);
  });

  it("外側が名前なら分けない（読みを添えた書き方をそのまま読む）", () => {
    const parsed = parsePlotCharacters("- 灯（あかり）：主人公");
    expect(parsed.entries).toEqual([{ name: "灯（あかり）", summary: "主人公" }]);
  });

  it("役名を持たない行のダイジェストは、役名の欄を足す前と同じ綴じ方", () => {
    // 足す前の綴じ方（名前と説明の2つ）をここで組み直して比べる。
    // 変わると、反映済みの作品がすべて積み直しになる
    const entries = [{ name: "灯", summary: "主人公" }];
    expect(plotCharactersDigest(entries)).toBe(
      sha256Text(JSON.stringify(["灯", "主人公"]))
    );
    expect(plotCharactersDigest(entries)).not.toBe(
      plotCharactersDigest([{ name: "灯", summary: "主人公", role: "ヒロイン" }])
    );
  });

  it("新規案は役名を役割の欄へ入れ、別名にはしない", () => {
    const [record] = buildNewCharacterRecords([
      { name: "相馬 誠", summary: "新人", role: "主人公" },
    ]);
    expect(record.role).toBe("主人公");
    expect(record.aliases).toEqual([]);
  });

  it("積み直す新規案は、承認待ちの同じ名前の案から読みと役割だけを引き継ぐ", () => {
    const [fresh] = buildNewCharacterRecords([{ name: "相馬 誠", summary: "新しい説明" }]);
    const previous = {
      ...character("char_000", "相馬 誠"),
      reading: "そうま まこと",
      role: "主人公",
      summary: "古い説明",
    };

    const [inherited] = inheritPendingCreationFields([fresh], [previous]);

    expect(inherited.reading).toBe("そうま まこと");
    expect(inherited.role).toBe("主人公");
    // プロットに書いてある欄はプロットが正しい
    expect(inherited.summary).toBe("新しい説明");
  });
});

/*
  名前の候補で「主人公（相馬 誠）」と書き足したあと、**名前を直す案
  （主人公 → 相馬 誠）がまだ承認待ちのうちに** plot.md を保存したとき
  （作者の判断、2026-09-25「直す」）。資料にはまだ「主人公」しかいないので、
  名前だけで突き合わせると「相馬 誠」を新規として積み、先に承認すると
  2人になる。**役名でも、承認待ちでも突き合わせる**
*/
describe("役名（名前）の行を、役名と承認待ちでも突き合わせる", () => {
  const ledgerRole = character("char_002", "主人公", { summary: "冒険者試験に落ちた" });
  const rename = {
    kind: undefined,
    character: {
      ...ledgerRole,
      name: "相馬 誠",
      reading: "そうま まこと",
      role: "主人公",
    },
  };

  it("承認待ちに「役名 → 名前」の直す案があれば、新規には積まない", () => {
    const plan = buildPlotCharacterUpdates(
      [{ name: "相馬 誠", summary: "冒険者試験に落ちた", role: "主人公" }],
      [ledgerRole],
      [rename]
    );
    expect(plan.creations).toEqual([]);
    // 資料の「主人公」の紹介文を更新する案も積まない（直す案のファイルを消してしまう）
    expect(plan.updates).toEqual([]);
    expect(plan.pendingOverlays).toEqual([]);
  });

  it("紹介文が変わっていれば、直す案へ重ねる（読みは直す案のまま残す）", () => {
    const plan = buildPlotCharacterUpdates(
      [{ name: "相馬 誠", summary: "試験に落ちた新人", role: "主人公" }],
      [ledgerRole],
      [rename]
    );
    expect(plan.creations).toEqual([]);
    expect(plan.updates).toEqual([]);
    expect(plan.pendingOverlays).toHaveLength(1);
    const [overlay] = plan.pendingOverlays;
    expect(overlay.proposal).toBe(rename);
    expect(overlay.character.id).toBe("char_002");
    expect(overlay.character.name).toBe("相馬 誠");
    expect(overlay.character.reading).toBe("そうま まこと");
    expect(overlay.character.summary).toBe("試験に落ちた新人");
    // 承認待ちの案そのものは書き換えない
    expect(rename.character.summary).toBe("冒険者試験に落ちた");
  });

  it("作者が確定させた人物の直す案には、紹介文を重ねない", () => {
    const locked = {
      kind: undefined,
      character: { ...rename.character, autoGenerated: false },
    };
    const plan = buildPlotCharacterUpdates(
      [{ name: "相馬 誠", summary: "試験に落ちた新人", role: "主人公" }],
      [{ ...ledgerRole, autoGenerated: false }],
      [locked]
    );
    expect(plan.creations).toEqual([]);
    expect(plan.pendingOverlays).toEqual([]);
    expect(plan.skipped).toEqual([{ name: "相馬 誠", reason: "authorConfirmed" }]);
  });

  it("直す案が無くても、資料に役名の人物がいれば新規には積まない", () => {
    const plan = buildPlotCharacterUpdates(
      [{ name: "相馬 誠", summary: "試験に落ちた新人", role: "主人公" }],
      [ledgerRole],
      []
    );
    expect(plan.creations).toEqual([]);
    expect(plan.updates).toEqual([]);
    expect(plan.skipped).toEqual([
      { name: "相馬 誠", reason: "sameRole", role: "主人公" },
    ]);
  });

  it("承認待ちに役名の新規案があれば、新規には積まない", () => {
    const plan = buildPlotCharacterUpdates(
      [{ name: "相馬 誠", summary: "試験に落ちた新人", role: "主人公" }],
      [],
      [{ kind: "creation", character: character("char_000", "主人公") }]
    );
    expect(plan.creations).toEqual([]);
    expect(plan.skipped).toEqual([
      { name: "相馬 誠", reason: "sameRole", role: "主人公" },
    ]);
  });

  it("資料の役名が集団の呼び名（モブ）なら、その中の1人として新規に積む", () => {
    const plan = buildPlotCharacterUpdates(
      [{ name: "ガルド", summary: "封印の業者", role: "作業員" }],
      [character("char_003", "作業員", { isMob: true })],
      []
    );
    expect(plan.creations).toEqual([
      { name: "ガルド", summary: "封印の業者", role: "作業員" },
    ]);
  });

  it("役名も名前も資料と承認待ちに無ければ、今までどおり新規に積む", () => {
    const plan = buildPlotCharacterUpdates(
      [{ name: "相馬 誠", summary: "新人", role: "主人公" }],
      [character("char_001", "灯")],
      [{ kind: "creation", character: character("char_000", "澪") }]
    );
    expect(plan.creations).toEqual([
      { name: "相馬 誠", summary: "新人", role: "主人公" },
    ]);
    expect(plan.skipped).toEqual([]);
  });
});
