import { describe, expect, it } from "vitest";
import {
  buildNewCharacterRecords,
  buildPlotCharacterUpdates,
  parsePlotCharacters,
  plotCharactersDigest,
  PENDING_CREATION_ID,
} from "../../src/core/plotCharacterSync";
import { emptyCharacter, type Character } from "../../src/models/character";

/**
 * plot.md の「主要登場人物」から設定資料への差分反映（設計書6.4.9）。
 *
 * **プロットは自由に書けるMarkdownである**（6.4.3）ので、読めるのは
 * 箇条書きの決まった形だけになる。読めなかった行は黙って飛ばさず
 * `unparsed` に積み、件数を作者へ伝える。
 */

function character(
  id: string,
  name: string,
  overrides: Partial<Character> = {}
): Character {
  return { ...emptyCharacter(id, name), ...overrides };
}

describe("主要登場人物の節を読む", () => {
  it("コロン・ダッシュ・空白の3つの区切りを読む", () => {
    const parsed = parsePlotCharacters(
      ["- 月島灯：主人公。十七歳。", "- 白瀬澪——灯の親友", "- 三門太志 担任の教師"].join(
        "\n"
      )
    );

    expect(parsed.entries).toEqual([
      { name: "月島灯", summary: "主人公。十七歳。" },
      { name: "白瀬澪", summary: "灯の親友" },
      { name: "三門太志", summary: "担任の教師" },
    ]);
    expect(parsed.unparsed).toEqual([]);
  });

  it("半角コロンでも読む", () => {
    const parsed = parsePlotCharacters("- 灯: 主人公");
    expect(parsed.entries).toEqual([{ name: "灯", summary: "主人公" }]);
  });

  it("名前だけの行は、説明を空にして拾う", () => {
    const parsed = parsePlotCharacters("- 密倉文佳");
    expect(parsed.entries).toEqual([{ name: "密倉文佳", summary: "" }]);
    expect(parsed.unparsed).toEqual([]);
  });

  it("中黒と長音符は区切りにしない（カタカナの姓名が割れる）", () => {
    const parsed = parsePlotCharacters(
      ["- ヴォイド・コンストラクタ：父親", "- ギルドマスター 受付の主"].join("\n")
    );
    expect(parsed.entries).toEqual([
      { name: "ヴォイド・コンストラクタ", summary: "父親" },
      { name: "ギルドマスター", summary: "受付の主" },
    ]);
  });

  it("読めない行は unparsed に積む（黙って飛ばさない）", () => {
    const parsed = parsePlotCharacters(
      ["この節はあとで書き直す。", "- 灯：主人公"].join("\n")
    );
    expect(parsed.entries).toEqual([{ name: "灯", summary: "主人公" }]);
    expect(parsed.unparsed).toEqual(["この節はあとで書き直す。"]);
  });

  it("空の節では、何も拾わず何も報せない", () => {
    expect(parsePlotCharacters("")).toEqual({ entries: [], unparsed: [] });
    expect(parsePlotCharacters("\n\n- \n")).toEqual({
      entries: [],
      unparsed: [],
    });
    expect(parsePlotCharacters("<!-- ここに書きます -->")).toEqual({
      entries: [],
      unparsed: [],
    });
  });

  it("字下げした箇条書きは、直前の人物の説明の続きとして読む", () => {
    const parsed = parsePlotCharacters(
      ["- 灯：主人公", "  - 十七歳", "  - 幽霊が見える"].join("\n")
    );
    expect(parsed.entries).toEqual([
      { name: "灯", summary: "主人公 十七歳 幽霊が見える" },
    ]);
    expect(parsed.unparsed).toEqual([]);
  });
});

describe("節の内容ハッシュ", () => {
  const entries = [
    { name: "灯", summary: "主人公" },
    { name: "澪", summary: "親友" },
  ];

  it("同じ内容なら同じ", () => {
    expect(plotCharactersDigest(entries)).toBe(plotCharactersDigest([...entries]));
  });

  it("並べ替えただけでは変わらない（同じ提案を積み直さない）", () => {
    expect(plotCharactersDigest([...entries].reverse())).toBe(
      plotCharactersDigest(entries)
    );
  });

  it("説明が変われば変わる", () => {
    expect(
      plotCharactersDigest([{ name: "灯", summary: "主人公" }])
    ).not.toBe(plotCharactersDigest([{ name: "灯", summary: "主人公。十七歳" }]));
  });
});

describe("更新案の組み立て", () => {
  it("居ない名前は新規、同名で紹介文が違えば更新", () => {
    const existing = [character("char_001", "灯", { summary: "主人公" })];
    const plan = buildPlotCharacterUpdates(
      [
        { name: "灯", summary: "主人公。幽霊が見える。" },
        { name: "澪", summary: "灯の親友" },
      ],
      existing
    );

    expect(plan.updates).toHaveLength(1);
    expect(plan.updates[0].id).toBe("char_001");
    expect(plan.updates[0].summary).toBe("主人公。幽霊が見える。");
    expect(plan.creations).toEqual([{ name: "澪", summary: "灯の親友" }]);
    // 元のレコードは書き換えない
    expect(existing[0].summary).toBe("主人公");
  });

  it("紹介文が同じなら積まない", () => {
    const plan = buildPlotCharacterUpdates(
      [{ name: "灯", summary: "主人公" }],
      [character("char_001", "灯", { summary: "主人公" })]
    );
    expect(plan.updates).toEqual([]);
    expect(plan.creations).toEqual([]);
  });

  it("別名でも既存の人物に当てる", () => {
    const plan = buildPlotCharacterUpdates(
      [{ name: "月島灯", summary: "主人公" }],
      [character("char_001", "灯", { aliases: ["月島灯"] })]
    );
    expect(plan.updates).toHaveLength(1);
    expect(plan.updates[0].id).toBe("char_001");
    expect(plan.creations).toEqual([]);
  });

  it("名前だけの行は、既に居る人物には何も起こさない", () => {
    const plan = buildPlotCharacterUpdates(
      [{ name: "灯", summary: "" }],
      [character("char_001", "灯", { summary: "主人公" })]
    );
    expect(plan.updates).toEqual([]);
    expect(plan.creations).toEqual([]);
  });

  it("作者が確定させた人物（autoGenerated: false）は積まない", () => {
    const plan = buildPlotCharacterUpdates(
      [{ name: "灯", summary: "主人公。幽霊が見える。" }],
      [
        character("char_001", "灯", {
          summary: "主人公",
          autoGenerated: false,
        }),
      ]
    );
    expect(plan.updates).toEqual([]);
    expect(plan.skipped).toEqual([{ name: "灯", reason: "authorConfirmed" }]);
  });

  it("同じ名前の人物が複数居るときは、どれにも当てない", () => {
    const plan = buildPlotCharacterUpdates(
      [{ name: "お母さん", summary: "灯の母" }],
      [character("char_001", "お母さん"), character("char_002", "お母さん")]
    );
    expect(plan.updates).toEqual([]);
    expect(plan.creations).toEqual([]);
    expect(plan.skipped).toEqual([{ name: "お母さん", reason: "ambiguous" }]);
  });

  it("作者が「別人だ」と決めた呼び名では引き当てない（設計書6.5.8）", () => {
    const plan = buildPlotCharacterUpdates(
      [{ name: "アジャン", summary: "帝国の皇子" }],
      [
        character("char_001", "アジャーノ", {
          distinctFrom: [{ name: "アジャン", id: null }],
        }),
      ]
    );
    expect(plan.updates).toEqual([]);
    expect(plan.creations).toEqual([
      { name: "アジャン", summary: "帝国の皇子" },
    ]);
  });

  it("新規案は仮のIDで作り、抽出の新規と同じ初期値を持つ", () => {
    const [record] = buildNewCharacterRecords([
      { name: "澪", summary: "灯の親友" },
    ]);

    // 本当の番号は承認したときに採る（積んだ時点では決められない）
    expect(record.id).toBe(PENDING_CREATION_ID);
    expect(record.name).toBe("澪");
    expect(record.summary).toBe("灯の親友");
    expect(record.autoGenerated).toBe(true);
    expect(record.appearedChapters).toEqual([]);
    // 本文にはまだ出ていない（資料には「未登場（設定のみ）」と出る）
    expect(record.status).toBe("未登場");
    expect(record.authorNotes).toBe("");
  });

  it("名前だけの新規案は、紹介文を空のままにする", () => {
    const [record] = buildNewCharacterRecords([{ name: "密倉文佳", summary: "" }]);
    expect(record.summary).toBeNull();
  });

  it("長すぎる紹介文は、資料の上限まで切り詰めてから積む", () => {
    const long = "あ".repeat(200);
    const plan = buildPlotCharacterUpdates(
      [{ name: "灯", summary: long }],
      [character("char_001", "灯")]
    );
    expect(plan.updates).toHaveLength(1);
    expect([...(plan.updates[0].summary ?? "")].length).toBeLessThanOrEqual(80);
  });
});
