import { describe, expect, test } from "vitest";
import { deriveReading, fillReading } from "../../src/core/reading";
import { mergeExtractedCharacters } from "../../src/core/characterMerge";
import { emptyCharacter } from "../../src/models/character";

describe("カタカナ名からの読み生成", () => {
  test("カタカナをひらがなにする", () => {
    expect(deriveReading("ホンゴー")).toBe("ほんごー");
    expect(deriveReading("ジャック")).toBe("じゃっく");
  });

  test("中黒は読みに含めない", () => {
    // 辞書の「よみ」に記号が入ると変換で打ちにくい
    expect(deriveReading("リンセップ・アウクト")).toBe("りんせっぷあうくと");
    expect(deriveReading("マルキオ・イークェス")).toBe("まるきおいーくぇす");
  });

  test("長音符はそのまま残す", () => {
    expect(deriveReading("カッパー")).toBe("かっぱー");
  });

  test("空白や＝も区切りとして落とす", () => {
    expect(deriveReading("ヴァン＝ヘルシング")).toBe("ゔぁんへるしんぐ");
    expect(deriveReading("シル ヴィア")).toBe("しるゔぃあ");
  });

  test("漢字が混ざるなら機械的に決めない", () => {
    // 「灯」は「あかり」とも「ともし」とも読む。決め打ちできない
    expect(deriveReading("月島灯")).toBeUndefined();
    expect(deriveReading("アージュノス侯爵家の令息")).toBeUndefined();
  });

  test("英字が混ざる場合も決めない", () => {
    expect(deriveReading("A級冒険者")).toBeUndefined();
  });

  test("空文字は読みを作らない", () => {
    expect(deriveReading("   ")).toBeUndefined();
  });
});

describe("読みの補完", () => {
  test("空なら埋める", () => {
    expect(fillReading(null, "ホンゴー")).toBe("ほんごー");
    expect(fillReading("", "ホンゴー")).toBe("ほんごー");
  });

  test("既にある読みは上書きしない", () => {
    // 作者やAIが入れた読みを機械的な変換で潰さない
    expect(fillReading("ほんごう", "ホンゴー")).toBe("ほんごう");
  });

  test("作れない場合はそのまま", () => {
    expect(fillReading(null, "月島灯")).toBeNull();
  });
});

describe("抽出時に読みが入る", () => {
  test("カタカナの人物は読みが埋まる", () => {
    const merged = mergeExtractedCharacters(
      [],
      [
        {
          data: {
            name: "リンセップ・アウクト",
            entityType: "person" as const,
            evidence: "リンセップ・アウクトが歩いた。",
          },
          chapters: [1],
        },
      ]
    );

    expect(merged.characters[0].reading).toBe("りんせっぷあうくと");
  });

  test("漢字の人物はAIの推定を使う", () => {
    const merged = mergeExtractedCharacters(
      [],
      [
        {
          data: {
            name: "月島灯",
            entityType: "person" as const,
            reading: "つきしまあかり",
            evidence: "月島灯が歩いた。",
          },
          chapters: [1],
        },
      ]
    );

    expect(merged.characters[0].reading).toBe("つきしまあかり");
  });

  test("既存の読みを抽出で潰さない", () => {
    const existing = {
      ...emptyCharacter("char_001", "ホンゴー"),
      reading: "ほんごう",
      autoGenerated: true,
    };

    const merged = mergeExtractedCharacters(
      [existing],
      [
        {
          data: {
            name: "ホンゴー",
            entityType: "person" as const,
            evidence: "ホンゴーが歩いた。",
          },
          chapters: [2],
        },
      ]
    );

    expect(merged.characters[0].reading).toBe("ほんごう");
  });
});
