import { describe, expect, test } from "vitest";
import {
  forgetRejectedRelation,
  isSameRelation,
  recordRemovedRelations,
  settlePendingRelations,
  withoutRejectedRelations,
} from "../../../src/core/rejectedRelations";
import { applyCharacterEdits } from "../../../src/core/settingsEdit";
import { mergeExtractedCharacters } from "../../../src/core/characterMerge";
import { unifyCharacters } from "../../../src/core/characterUnify";
import {
  emptyCharacter,
  parseCharacter,
  type Character,
} from "../../../src/models/character";

/**
 * 退けた関係（作者の裁定、2026-09-23「退けた関係を記録する」）。
 *
 * 0.83.2（B3）で関係を直せるようになったが、**外部AIの提案で直しても、
 * その人物が `autoGenerated: true` のままだと、次の抽出が誤りを積み戻す**
 * ——抽出のマージは関係の言葉が違えば両方残すので、「ターナ=母」に
 * 直したところへ「ターナ=父の娘」がまた足される。
 *
 * 見張ること：
 *
 * 1. **退けた関係は、次の抽出で戻らない**（そして黙って捨てずに数える）
 * 2. **作者が同じ関係を手で入れ直したら、退けた記録から外れる**（作者の意思が勝つ）
 * 3. **外部AIの提案（propose）でも足されない**（mcpPropose.test.ts 側）
 * 4. 一致は「相手（相関図と同じ引き当て）」と「関係の言葉（前後の空白・
 *    全角半角をそろえて完全一致）」。**似ているだけのものは一致としない**
 */

const NOW = "2026-09-24T00:00:00.000Z";

function character(
  id: string,
  name: string,
  extra: Partial<Character> = {}
): Character {
  return { ...emptyCharacter(id, name), ...extra };
}

/** マイナ（関係を直された人物）とターナ（相手） */
function cast(extra: Partial<Character> = {}): Character[] {
  return [
    character("char_001", "マイナ", {
      relations: [{ name: "ターナ", relation: "母" }],
      rejectedRelations: [
        { target: "ターナ", relation: "父の娘", rejectedAt: NOW, via: "external" },
      ],
      appearedChapters: [1, 2],
      ...extra,
    }),
    character("char_002", "ターナ・ルー", { appearedChapters: [1] }),
  ];
}

describe("読み込み（parseCharacter）", () => {
  test("欄の無い古いファイルは空として読む", () => {
    const parsed = parseCharacter({ id: "char_001", name: "マイナ" });
    expect(parsed.rejectedRelations).toEqual([]);
  });

  test("書かれた記録はそのまま読み戻せる", () => {
    const record = {
      target: "ターナ",
      relation: "父の娘",
      rejectedAt: NOW,
      via: "panel",
    };
    const parsed = parseCharacter({
      id: "char_001",
      name: "マイナ",
      rejectedRelations: [record],
    });
    expect(parsed.rejectedRelations).toEqual([record]);
  });

  test("壊れた形は直さずに止める（規則2）", () => {
    expect(() =>
      parseCharacter({
        id: "char_001",
        name: "マイナ",
        rejectedRelations: [{ target: "", relation: "父の娘" }],
      })
    ).toThrow(/rejectedRelations/);
    expect(() =>
      parseCharacter({ id: "char_001", name: "マイナ", rejectedRelations: "ターナ" })
    ).toThrow(/rejectedRelations/);
  });
});

describe("一致の判定（isSameRelation）", () => {
  const characters = cast();

  test("前後の空白と全角半角の違いは同じとみなす", () => {
    const rejected = { target: "ターナ", relation: "父の娘" };
    expect(isSameRelation(characters, { name: " ターナ　", relation: "父の娘 " }, rejected)).toBe(true);
    expect(
      isSameRelation(
        characters,
        { name: "ﾀｰﾅ", relation: "父の娘" },
        rejected
      )
    ).toBe(true);
    expect(
      isSameRelation(
        characters,
        { name: "Ｋ", relation: "ＡＢ" },
        { target: "K", relation: "AB" }
      )
    ).toBe(true);
  });

  test("相手は相関図と同じ引き当て——姓名と名だけは同じ人", () => {
    // ターナ・ルー（char_002）は「ターナ」でも引ける
    expect(
      isSameRelation(
        characters,
        { name: "ターナ・ルー", relation: "父の娘" },
        { target: "ターナ", relation: "父の娘" }
      )
    ).toBe(true);
  });

  test("似ているだけの言葉は一致としない", () => {
    const rejected = { target: "ターナ", relation: "父の娘" };
    expect(isSameRelation(characters, { name: "ターナ", relation: "父の娘さん" }, rejected)).toBe(false);
    expect(isSameRelation(characters, { name: "ターナ", relation: "父の 娘" }, rejected)).toBe(false);
    expect(isSameRelation(characters, { name: "ターナ", relation: "娘" }, rejected)).toBe(false);
    // 相手が違えば、言葉が同じでも別の関係
    expect(isSameRelation(characters, { name: "リナ", relation: "父の娘" }, rejected)).toBe(false);
  });

  test("資料に居ない相手は、名前そのもので比べる", () => {
    expect(
      isSameRelation(
        characters,
        { name: "灯台守", relation: "恩人" },
        { target: "灯台守", relation: "恩人" }
      )
    ).toBe(true);
    expect(
      isSameRelation(
        characters,
        { name: "灯台守さん", relation: "恩人" },
        { target: "灯台守", relation: "恩人" }
      )
    ).toBe(false);
  });
});

describe("抽出のマージ（再現：退けた関係が次の抽出で戻らない）", () => {
  test("autoGenerated: true のままでも、退けた関係は足さず、件数に出す", () => {
    const existing = cast();
    const result = mergeExtractedCharacters(existing, [
      {
        data: {
          name: "マイナ",
          relations: [
            { name: "ターナ", relation: "父の娘" },
            { name: "リナ", relation: "友人" },
          ],
        },
        chapters: [3],
      },
    ]);
    const maina = result.characters.find((c) => c.id === "char_001");
    expect(maina?.relations).toEqual([
      { name: "ターナ", relation: "母" },
      { name: "リナ", relation: "友人" },
    ]);
    expect(result.skippedRejectedRelations).toEqual([
      { characterName: "マイナ", name: "ターナ", relation: "父の娘" },
    ]);
    // 退けた記録そのものは、抽出が書き換えない（AIは書かない欄）
    expect(maina?.rejectedRelations).toEqual(existing[0].rejectedRelations);
  });

  test("何話ぶん届いても、報告は1件にまとめる", () => {
    const result = mergeExtractedCharacters(cast(), [
      {
        data: { name: "マイナ", relations: [{ name: "ターナ", relation: "父の娘" }] },
        chapters: [3],
      },
      {
        data: {
          name: "マイナ",
          relations: [{ name: "ターナ・ルー", relation: "父の娘　" }],
        },
        chapters: [4],
      },
    ]);
    expect(result.skippedRejectedRelations).toHaveLength(1);
    const maina = result.characters.find((c) => c.id === "char_001");
    expect(maina?.relations).toEqual([{ name: "ターナ", relation: "母" }]);
  });

  test("退けた記録が無ければ、今までどおり足す", () => {
    const result = mergeExtractedCharacters(cast({ rejectedRelations: [] }), [
      {
        data: { name: "マイナ", relations: [{ name: "ターナ", relation: "父の娘" }] },
        chapters: [3],
      },
    ]);
    const maina = result.characters.find((c) => c.id === "char_001");
    expect(maina?.relations).toEqual([
      { name: "ターナ", relation: "母" },
      { name: "ターナ", relation: "父の娘" },
    ]);
    expect(result.skippedRejectedRelations).toEqual([]);
  });
});

describe("設定資料パネルでの編集（applyCharacterEdits）", () => {
  test("消した関係・言葉を変えた関係は、退けた関係として残る", () => {
    const characters = [
      character("char_001", "マイナ", {
        relations: [
          { name: "ターナ", relation: "父の娘" },
          { name: "リナ", relation: "友人" },
          { name: "灯台守", relation: "恩人" },
        ],
      }),
      character("char_002", "ターナ・ルー"),
    ];
    const edited = applyCharacterEdits(
      characters[0],
      { relations: "ターナ=母\nリナ=友人" },
      { characters, now: NOW }
    );
    expect(edited.relations).toEqual([
      { name: "ターナ", relation: "母" },
      { name: "リナ", relation: "友人" },
    ]);
    expect(edited.rejectedRelations).toEqual([
      { target: "ターナ", relation: "父の娘", rejectedAt: NOW, via: "panel" },
      { target: "灯台守", relation: "恩人", rejectedAt: NOW, via: "panel" },
    ]);
  });

  test("空白や全角半角だけを直したものは、退けたことにしない", () => {
    const characters = [
      character("char_001", "マイナ", {
        relations: [{ name: "ターナ", relation: "母 " }],
      }),
    ];
    const edited = applyCharacterEdits(
      characters[0],
      { relations: "ターナ=母" },
      { characters, now: NOW }
    );
    expect(edited.rejectedRelations).toEqual([]);
  });

  test("作者が同じ関係を手で入れ直したら、退けた記録から外れる（作者の意思が勝つ）", () => {
    const characters = cast();
    const edited = applyCharacterEdits(
      characters[0],
      { relations: "ターナ=母\nターナ・ルー=父の娘" },
      { characters, now: NOW }
    );
    expect(edited.relations).toContainEqual({ name: "ターナ・ルー", relation: "父の娘" });
    expect(edited.rejectedRelations).toEqual([]);
  });

  test("入れ直したあとは、次の抽出で同じ関係を足しても止めない", () => {
    const characters = cast();
    const edited = applyCharacterEdits(
      characters[0],
      { relations: "ターナ=母\nターナ=父の娘" },
      // AIの提案をそのまま採った形にして、抽出の対象に残す
      { characters, now: NOW, authorConfirmed: false }
    );
    const result = mergeExtractedCharacters([edited, characters[1]], [
      {
        data: { name: "マイナ", relations: [{ name: "ターナ", relation: "父の娘" }] },
        chapters: [5],
      },
    ]);
    expect(result.skippedRejectedRelations).toEqual([]);
  });

  test("関係欄を送ってこない保存では、退けた記録に触れない", () => {
    const characters = cast();
    const edited = applyCharacterEdits(characters[0], { role: "見習い" }, { characters, now: NOW });
    expect(edited.rejectedRelations).toEqual(characters[0].rejectedRelations);
  });
});

describe("承認の画面（settlePendingRelations / recordRemovedRelations）", () => {
  test("外部AIの提案で消えた関係は、承認したときに退けた関係として残る", () => {
    const current = character("char_001", "マイナ", {
      relations: [{ name: "ターナ", relation: "父の娘" }],
    });
    const approved = {
      ...current,
      relations: [{ name: "ターナ", relation: "母" }],
    };
    const characters = [current, character("char_002", "ターナ・ルー")];
    const recorded = recordRemovedRelations({
      before: current.relations,
      after: approved.relations,
      rejected: current.rejectedRelations,
      characters,
      via: "external",
      now: NOW,
    });
    expect(recorded).toEqual([
      { target: "ターナ", relation: "父の娘", rejectedAt: NOW, via: "external" },
    ]);
  });

  test("既に退けてある関係を二重に記録しない", () => {
    const characters = cast();
    const recorded = recordRemovedRelations({
      before: [{ name: "ターナ・ルー", relation: "父の娘" }],
      after: [],
      rejected: characters[0].rejectedRelations,
      characters,
      via: "panel",
      now: "2026-09-25T00:00:00.000Z",
    });
    expect(recorded).toEqual(characters[0].rejectedRelations);
  });

  test("古い更新案が退けた関係を持ち込んでも、足さずに数える", () => {
    // 更新案は積んだ時点の写し。**積んだあとに作者が退けた関係**が、
    // 「足される関係」として並んでしまう
    const [current, tana] = cast();
    const stale = {
      ...current,
      relations: [
        { name: "ターナ", relation: "母" },
        { name: "ターナ", relation: "父の娘" },
      ],
      rejectedRelations: [],
      role: "見習い",
    };
    const settled = settlePendingRelations(current, stale, [current, tana]);
    expect(settled.character.relations).toEqual([{ name: "ターナ", relation: "母" }]);
    expect(settled.skipped).toEqual([{ name: "ターナ", relation: "父の娘" }]);
    // 退けた記録は台帳の側が正（写しの古い記録で巻き戻さない）
    expect(settled.character.rejectedRelations).toEqual(current.rejectedRelations);
    // ほかの欄は触らない
    expect(settled.character.role).toBe("見習い");
  });

  test("いま台帳にある関係は、退けた記録と重なっても落とさない", () => {
    // 台帳にあるものを更新案から落とすと、承認で「消える」ことになる
    const [current, tana] = cast({
      relations: [{ name: "ターナ", relation: "父の娘" }],
    });
    const settled = settlePendingRelations(current, { ...current }, [current, tana]);
    expect(settled.character.relations).toEqual([{ name: "ターナ", relation: "父の娘" }]);
    expect(settled.skipped).toEqual([]);
  });
});

describe("退けた記録から外す（forgetRejectedRelation）", () => {
  test("指した1件だけを外す", () => {
    const [maina] = cast({
      rejectedRelations: [
        { target: "ターナ", relation: "父の娘", rejectedAt: NOW, via: "external" },
        { target: "灯台守", relation: "恩人", rejectedAt: NOW, via: "panel" },
      ],
    });
    const next = forgetRejectedRelation(maina, "ターナ", "父の娘");
    expect(next.rejectedRelations).toEqual([
      { target: "灯台守", relation: "恩人", rejectedAt: NOW, via: "panel" },
    ]);
    // 関係そのものは戻さない（戻すかどうかは作者が関係欄で決める）
    expect(next.relations).toEqual(maina.relations);
  });
});

describe("相手の選り分け（withoutRejectedRelations）", () => {
  test("退けた関係だけを外し、残りは並びを保つ", () => {
    const characters = cast();
    const outcome = withoutRejectedRelations(
      [
        { name: "リナ", relation: "友人" },
        { name: "ターナ", relation: "父の娘" },
        { name: "ターナ", relation: "母" },
      ],
      characters[0].rejectedRelations,
      characters
    );
    expect(outcome.kept).toEqual([
      { name: "リナ", relation: "友人" },
      { name: "ターナ", relation: "母" },
    ]);
    expect(outcome.skipped).toEqual([{ name: "ターナ", relation: "父の娘" }]);
  });
});

describe("人物をまとめる（unifyCharacters）", () => {
  test("両方の退けた記録を引き継ぐ", () => {
    const keep = character("char_001", "マイナ", {
      rejectedRelations: [
        { target: "ターナ", relation: "父の娘", rejectedAt: NOW, via: "external" },
      ],
    });
    const absorb = character("char_003", "マイ", {
      rejectedRelations: [
        { target: "灯台守", relation: "恩人", rejectedAt: NOW, via: "panel" },
      ],
    });
    const { unified } = unifyCharacters(keep, absorb);
    expect(unified.rejectedRelations).toEqual([
      ...keep.rejectedRelations,
      ...absorb.rejectedRelations,
    ]);
  });
});
