import { describe, expect, test } from "vitest";
import {
  decideByUpdatedAt,
  decideSettingsConflict,
  isSettingsJsonPath,
} from "../../../src/core/settingsConflictRule";

/**
 * 設定資料の衝突を、規則で決める（設計書5.5.18）。
 *
 * 作者の指示（2026-09-10）：「設定資料ファイルは作者が書き換えた部分が
 * 変わっていなければ、時系列的に新しいほうに自動で合わせてください」。
 *
 * **決めてよい線引きを、ここで固定する。** 広く取りすぎるとAIの抽出結果の
 * 違いまで作者への問いになり（0.44.0までがそうだった）、狭く取りすぎると
 * 作者が手で書いた値をもう一方の端末の読みが押し流す。
 */

/** 円記号。**文字列にそのまま置くと読みにくい**ので符号から作る */
const BS = String.fromCharCode(92);

/** 人物1件ぶんのJSON。既定はAIが作ったレコード */
function 人物(input: {
  summary?: string;
  authorNotes?: string;
  exportNote?: string;
  autoGenerated?: boolean;
  updatedAt?: string;
  appearedChapters?: number[];
  addressTerms?: unknown[];
  distinctFrom?: unknown[];
}): string {
  return JSON.stringify({
    schemaVersion: "0.1",
    id: "char_001",
    name: "太志",
    summary: input.summary ?? "紹介文",
    appearedChapters: input.appearedChapters ?? [1, 2],
    addressTerms: input.addressTerms ?? [],
    distinctFrom: input.distinctFrom ?? [],
    changes: [],
    authorNotes: input.authorNotes ?? "",
    exportNote: input.exportNote ?? "",
    autoGenerated: input.autoGenerated ?? true,
    updatedAt: input.updatedAt ?? "2026-09-01T00:00:00.000Z",
  });
}

describe("設定資料のJSONかの見分け", () => {
  test("設定フォルダーの下のJSONを見る", () => {
    expect(isSettingsJsonPath("短編/設定/characters/char_001_太志.json")).toBe(
      true
    );
    expect(isSettingsJsonPath("短編/設定/custom_fields.json")).toBe(true);
  });

  test("拡張機能の作業場所は対象にしない", () => {
    // 承認待ちは自動生成物として別に扱う（`mergePreview.ts`）
    expect(
      isSettingsJsonPath("短編/.aiwriter/pending-characters/char_001.json")
    ).toBe(false);
    expect(isSettingsJsonPath("短編/設定/_schema/character.json")).toBe(false);
  });

  test("本文は対象にしない", () => {
    expect(isSettingsJsonPath("短編/本文/第1話.txt")).toBe(false);
    // 設定フォルダーの外のJSONも見ない（作品ごとに置き場の名前は変えられる）
    expect(isSettingsJsonPath("短編/メモ/覚書.json")).toBe(false);
  });

  test("Windowsの区切りでも同じに見る", () => {
    expect(
      isSettingsJsonPath(`短編${BS}設定${BS}characters${BS}char_001.json`)
    ).toBe(true);
  });
});

describe("規則1：作者が書いた部分が同じなら、新しいほうへ", () => {
  test("別環境のほうが新しければ、別環境を採る", () => {
    const decision = decideSettingsConflict({
      ours: 人物({ summary: "こちらの読み", updatedAt: "2026-09-03T00:00:00.000Z" }),
      theirs: 人物({ summary: "むこうの読み", updatedAt: "2026-09-05T00:00:00.000Z" }),
    });

    expect(decision.side).toBe("theirs");
    expect(decision.reason).toContain("別の環境の側が新しい");
  });

  test("この端末のほうが新しければ、この端末を採る", () => {
    const decision = decideSettingsConflict({
      ours: 人物({ summary: "こちらの読み", updatedAt: "2026-09-07T00:00:00.000Z" }),
      theirs: 人物({ summary: "むこうの読み", updatedAt: "2026-09-05T00:00:00.000Z" }),
    });

    expect(decision.side).toBe("ours");
  });

  test("同じ時刻なら、順序を決められないのでこの端末を残す", () => {
    // **中身はどちらもAIの抽出結果**なので、いま画面に出ているものを残す
    const decision = decideSettingsConflict({
      ours: 人物({ summary: "こちらの読み" }),
      theirs: 人物({ summary: "むこうの読み" }),
    });

    expect(decision.side).toBe("ours");
    expect(decision.reason).toContain("更新時刻では新しいほうを決められない");
  });

  test("登場話数の違いは、作者の手とみなさない", () => {
    // 抽出が追記するだけの配列である（CLAUDE.md）
    const decision = decideSettingsConflict({
      ours: 人物({
        appearedChapters: [1, 2],
        updatedAt: "2026-09-03T00:00:00.000Z",
      }),
      theirs: 人物({
        appearedChapters: [1, 2, 3],
        updatedAt: "2026-09-05T00:00:00.000Z",
      }),
    });

    expect(decision.side).toBe("theirs");
  });
});

/*
  旧「規則2」（動いたのが片側だけなら、動いたほうを丸ごと残す）は、案3（2026-10-01）で
  **項目ごとに合わせる**形に広がった。丸ごと残すと、もう片側のAIの読みの変更が
  黙って消えていた。作者の手が入った項目は、これまでどおり時刻に関係なく残る
*/
describe("規則2：共通の祖先から片側だけが作者の項目を変えたら、その値を残す", () => {
  const 祖先 = 人物({ updatedAt: "2026-09-01T00:00:00.000Z" });

  function 中身(decision: ReturnType<typeof decideSettingsConflict>) {
    if (decision.side !== "merged") throw new Error(`merged ではない: ${decision.side}`);
    return JSON.parse(decision.text) as Record<string, unknown>;
  }

  test("この端末だけが作者メモを足したら、そのメモを残し、向こうの読みも入れる", () => {
    const decision = decideSettingsConflict({
      base: 祖先,
      ours: 人物({
        authorNotes: "この子は左利き",
        updatedAt: "2026-09-02T00:00:00.000Z",
      }),
      // 別環境は紹介文だけが変わった（AIの抽出）。**時刻は新しい**
      theirs: 人物({
        summary: "むこうの読み",
        updatedAt: "2026-09-09T00:00:00.000Z",
      }),
    });

    // **時刻では負けているが、作者の手は残る**
    const merged = 中身(decision);
    expect(merged.authorNotes).toBe("この子は左利き");
    expect(merged.summary).toBe("むこうの読み");
  });

  test("別環境だけが作者メモを足したら、そのメモを残す", () => {
    const decision = decideSettingsConflict({
      base: 祖先,
      ours: 人物({ summary: "こちらの読み", updatedAt: "2026-09-09T00:00:00.000Z" }),
      theirs: 人物({
        authorNotes: "編集部からの直し",
        updatedAt: "2026-09-02T00:00:00.000Z",
      }),
    });

    const merged = 中身(decision);
    expect(merged.authorNotes).toBe("編集部からの直し");
    expect(merged.summary).toBe("こちらの読み");
  });
});

describe("規則3：決めないもの", () => {
  test("両方で作者メモを変えたら、作者に選ばせる", () => {
    const decision = decideSettingsConflict({
      base: 人物({}),
      ours: 人物({ authorNotes: "こちらのメモ" }),
      theirs: 人物({ authorNotes: "むこうのメモ" }),
    });

    expect(decision.side).toBe("conflict");
    expect(decision.reason).toContain("作者が書いた部分が両方で違います");
  });

  test("作者が固定した呼称が違えば、決めない", () => {
    // `authorLocked: true` の呼称は変えない（CLAUDE.md）
    const locked = (term: string) => [
      {
        targetName: "美咲",
        targetId: null,
        forms: [{ term, category: null, context: null, firstChapter: 1, lastChapter: null, status: "current", evidence: null }],
        authorLocked: true,
      },
    ];
    const decision = decideSettingsConflict({
      ours: 人物({ addressTerms: locked("みさきさん") }),
      theirs: 人物({ addressTerms: locked("美咲") }),
    });

    expect(decision.side).toBe("conflict");
  });

  test("固定していない呼称の違いは、決めるのを妨げない", () => {
    // 抽出のたびに増える。**ここを作者の手に数えると、毎回問いになる**
    const free = (term: string) => [
      {
        targetName: "美咲",
        targetId: null,
        forms: [{ term, category: null, context: null, firstChapter: 1, lastChapter: null, status: "current", evidence: null }],
        authorLocked: false,
      },
    ];
    const decision = decideSettingsConflict({
      ours: 人物({ addressTerms: free("みさきさん"), updatedAt: "2026-09-03T00:00:00.000Z" }),
      theirs: 人物({ addressTerms: free("美咲"), updatedAt: "2026-09-05T00:00:00.000Z" }),
    });

    expect(decision.side).toBe("theirs");
  });

  test("壊れたJSONは決めない", () => {
    // **勝手に直さない**（CLAUDE.md）
    const decision = decideSettingsConflict({
      ours: "{ここが壊れている",
      theirs: 人物({}),
    });

    expect(decision.side).toBe("conflict");
    expect(decision.reason).toContain("JSONとして読めない");
  });
});

describe("作者が確定させたレコード（autoGenerated: false）", () => {
  test("紹介文が違えば、決めない", () => {
    // **登場話数の追記以外AIは触らない**約束なので、
    // 違っているならそれは作者の手である（CLAUDE.md）
    const decision = decideSettingsConflict({
      ours: 人物({
        autoGenerated: false,
        summary: "こちらで書いた紹介",
        updatedAt: "2026-09-03T00:00:00.000Z",
      }),
      theirs: 人物({
        autoGenerated: false,
        summary: "むこうで書いた紹介",
        updatedAt: "2026-09-05T00:00:00.000Z",
      }),
    });

    expect(decision.side).toBe("conflict");
  });

  test("中身が同じで更新時刻だけ違うなら、新しいほうへ", () => {
    // 保存し直しただけ。**これで問いを出すと、確定したレコードほど詰まる**
    const decision = decideSettingsConflict({
      ours: 人物({ autoGenerated: false, updatedAt: "2026-09-03T00:00:00.000Z" }),
      theirs: 人物({ autoGenerated: false, updatedAt: "2026-09-05T00:00:00.000Z" }),
    });

    expect(decision.side).toBe("theirs");
  });

  test("登場話数だけが違うなら、新しいほうへ", () => {
    const decision = decideSettingsConflict({
      ours: 人物({
        autoGenerated: false,
        appearedChapters: [1],
        updatedAt: "2026-09-05T00:00:00.000Z",
      }),
      theirs: 人物({
        autoGenerated: false,
        appearedChapters: [1, 2],
        updatedAt: "2026-09-03T00:00:00.000Z",
      }),
    });

    expect(decision.side).toBe("ours");
  });
});

describe("1件1ファイルではない台帳", () => {
  /** `custom_fields.json` のような、作者が直に書く台帳 */
  const 台帳 = (fields: string[], updatedAt: string) =>
    JSON.stringify({ schemaVersion: "0.1", fields, updatedAt });

  test("中身が違えば決めない（作者が直に書く場所である）", () => {
    const decision = decideSettingsConflict({
      ours: 台帳(["出身地"], "2026-09-03T00:00:00.000Z"),
      theirs: 台帳(["好きな食べ物"], "2026-09-05T00:00:00.000Z"),
    });

    expect(decision.side).toBe("conflict");
  });

  test("更新時刻だけが違えば、新しいほうへ", () => {
    const decision = decideSettingsConflict({
      ours: 台帳(["出身地"], "2026-09-03T00:00:00.000Z"),
      theirs: 台帳(["出身地"], "2026-09-05T00:00:00.000Z"),
    });

    expect(decision.side).toBe("theirs");
  });
});

/**
 * 「全部、新しいほうを採る」の中身（2026-09-11）。
 *
 * 作者の言葉：「全部最新を優先する選択肢をまず提示し、操作をシンプルに
 * してください」。13作品ぶんの分岐を1件ずつ選ばされて抜けられなくなった。
 * **決めるのは機械ではなく、そのボタンを押した作者である。**
 */
describe("更新時刻だけで決める", () => {
  test("この端末の側が新しければ、こちらを採る", () => {
    const decision = decideByUpdatedAt(
      人物({ summary: "こちら", updatedAt: "2026-09-05T00:00:00.000Z" }),
      人物({ summary: "むこう", updatedAt: "2026-09-03T00:00:00.000Z" })
    );

    expect(decision.side).toBe("ours");
  });

  test("別の環境の側が新しければ、そちらを採る", () => {
    // **作者メモが両側で違っていても採る。** `decideSettingsConflict` と
    // 違って、ここは作者が「まとめて片づける」と決めたあとの道である
    const decision = decideByUpdatedAt(
      人物({
        authorNotes: "こちらのメモ",
        updatedAt: "2026-09-03T00:00:00.000Z",
      }),
      人物({
        authorNotes: "むこうのメモ",
        updatedAt: "2026-09-05T00:00:00.000Z",
      })
    );

    expect(decision.side).toBe("theirs");
  });

  test("JSONとして読めなければ、この端末の側を残す", () => {
    // **壊れたJSONを勝手に直さない**（CLAUDE.md）
    const decision = decideByUpdatedAt("{壊れている", 人物({}));

    expect(decision.side).toBe("ours");
    expect(decision.reason).toContain("読めない");
  });
});

/**
 * 同じ資料を引き継いでいるなら、重ならない変更は訊かずに合わせる（作者の裁定、2026-10-01 案3）。
 *
 * 作者の言葉：「設定資料については、デスクトップなどで作成したものを引き継いでいる
 * ものと考えます。であれば、設定資料作成日が同じであれば何も出さず、衝突した時だけ
 * 最新優先か聞く、作者が書き換えた項目は更新しないで良さそう」。
 *
 * 作成の印は `createdAt`（伏線・予定などが持つ）。持たない資料（人物など）は、
 * **共通の祖先に同じファイルがあること**を引き継ぎの印にする（祖先が無い＝
 * 両方で別々に作った、は今までどおりの規則で扱う）。
 */
describe("案3：同じ資料を引き継いでいるとき", () => {
  /** 伏線1件ぶんのJSON。`createdAt` を持つ。既定はAIが見つけたもの */
  function 伏線(input: {
    note?: string;
    authorNotes?: string;
    plannedResolveChapter?: number | null;
    createdAt?: string;
    updatedAt?: string;
  }): string {
    return JSON.stringify(
      {
        schemaVersion: "0.2",
        id: "foreshadow_001",
        label: "銀の懐中時計",
        note: input.note ?? "祖父の形見",
        plantedChapter: 2,
        plantedQuote: "懐中時計",
        status: "open",
        resolvedChapter: null,
        resolvedQuote: "",
        plannedResolveChapter: input.plannedResolveChapter ?? null,
        source: "ai",
        autoGenerated: true,
        authorNotes: input.authorNotes ?? "",
        createdAt: input.createdAt ?? "2026-09-01T00:00:00.000Z",
        updatedAt: input.updatedAt ?? "2026-09-01T00:00:00.000Z",
      },
      null,
      2
    );
  }

  /** 決めた結果の中身。訊く（conflict）なら undefined */
  function 採った中身(
    decision: ReturnType<typeof decideSettingsConflict>,
    ours: string,
    theirs: string
  ): Record<string, unknown> | undefined {
    if (decision.side === "conflict") return undefined;
    const text =
      decision.side === "merged"
        ? decision.text
        : decision.side === "ours"
          ? ours
          : theirs;
    return JSON.parse(text) as Record<string, unknown>;
  }

  test("作成日が同じで、変えた項目が重ならなければ、両方を合わせて訊かない", () => {
    // こちらでは作者メモを書いた。向こうでは AI の読み（note）が変わった
    const ours = 伏線({ authorNotes: "第8話で回収する", updatedAt: "2026-09-03T00:00:00.000Z" });
    const theirs = 伏線({ note: "祖父の形見。止まったまま", updatedAt: "2026-09-05T00:00:00.000Z" });
    const decision = decideSettingsConflict({ base: 伏線({}), ours, theirs });

    expect(decision.side).toBe("merged");
    const merged = 採った中身(decision, ours, theirs);
    expect(merged?.authorNotes).toBe("第8話で回収する");
    expect(merged?.note).toBe("祖父の形見。止まったまま");
    // 更新時刻は新しいほう
    expect(merged?.updatedAt).toBe("2026-09-05T00:00:00.000Z");
    // 項目の並びは元のまま（差分を最小にする）
    expect(Object.keys(merged ?? {})).toEqual(Object.keys(JSON.parse(伏線({})) as object));
  });

  test("作者の書いた別々の項目なら、両方で変えても訊かない", () => {
    // 作者メモはこちら、回収予定は向こう。**同じ項目ではない**ので衝突ではない
    const ours = 伏線({ authorNotes: "こちらのメモ", updatedAt: "2026-09-03T00:00:00.000Z" });
    const theirs = 伏線({ plannedResolveChapter: 8, updatedAt: "2026-09-04T00:00:00.000Z" });
    const decision = decideSettingsConflict({ base: 伏線({}), ours, theirs });

    const merged = 採った中身(decision, ours, theirs);
    expect(merged?.authorNotes).toBe("こちらのメモ");
    expect(merged?.plannedResolveChapter).toBe(8);
  });

  test("片方は保存し直しただけなら、変えた側の中身を採って訊かない", () => {
    const ours = 伏線({ updatedAt: "2026-09-09T00:00:00.000Z" });
    const theirs = 伏線({ note: "向こうの読み", updatedAt: "2026-09-05T00:00:00.000Z" });
    const decision = decideSettingsConflict({ base: 伏線({}), ours, theirs });

    expect(採った中身(decision, ours, theirs)?.note).toBe("向こうの読み");
  });

  test("同じ作者の項目を両方で違う値に変えたら、訊く", () => {
    const decision = decideSettingsConflict({
      base: 伏線({}),
      ours: 伏線({ authorNotes: "こちらのメモ" }),
      theirs: 伏線({ authorNotes: "むこうのメモ" }),
    });

    expect(decision.side).toBe("conflict");
  });

  test("作成日が違えば、別々に作った資料なので訊く", () => {
    const decision = decideSettingsConflict({
      base: 伏線({}),
      ours: 伏線({ createdAt: "2026-09-02T00:00:00.000Z", note: "こちら" }),
      theirs: 伏線({ createdAt: "2026-09-03T00:00:00.000Z", note: "むこう" }),
    });

    expect(decision.side).toBe("conflict");
    expect(decision.reason).toContain("作成日");
  });

  test("作者が確定させた側の値は、相手のAIの読みで書き換えない", () => {
    // こちらで作者が確定（autoGenerated: false）して紹介文を直した。
    // 向こうは確定前のまま、AI の抽出で紹介文が変わり、登場話数が増えた
    const ours = 人物({
      summary: "作者が直した紹介",
      autoGenerated: false,
      updatedAt: "2026-09-03T00:00:00.000Z",
    });
    const theirs = 人物({
      summary: "AIの読み直し",
      appearedChapters: [1, 2, 3],
      updatedAt: "2026-09-09T00:00:00.000Z",
    });
    const decision = decideSettingsConflict({ base: 人物({ summary: "もとの紹介" }), ours, theirs });

    // **時刻では負けていても、作者の値を残す**。訊きもしない（作者の手は片側だけ）
    const merged = 採った中身(decision, ours, theirs);
    expect(merged?.summary).toBe("作者が直した紹介");
    expect(merged?.autoGenerated).toBe(false);
    // 登場話数の追記だけは、確定したレコードにも入ってよい（CLAUDE.md）
    expect(merged?.appearedChapters).toEqual([1, 2, 3]);
  });

  test("両方で作者が確定させて違う値にしたら、訊く", () => {
    const decision = decideSettingsConflict({
      base: 人物({ summary: "もと" }),
      ours: 人物({ summary: "こちらで書いた", autoGenerated: false }),
      theirs: 人物({ summary: "むこうで書いた", autoGenerated: false }),
    });

    expect(decision.side).toBe("conflict");
  });

  test("AIの読みどうしが同じ項目で食い違うなら、新しいほうを採って訊かない（規則1と同じ）", () => {
    const decision = decideSettingsConflict({
      base: 人物({ summary: "もと" }),
      ours: 人物({ summary: "こちらの読み", updatedAt: "2026-09-03T00:00:00.000Z" }),
      theirs: 人物({ summary: "むこうの読み", updatedAt: "2026-09-05T00:00:00.000Z" }),
    });

    expect(decision.side).toBe("theirs");
  });
});
