import { describe, expect, test } from "vitest";
import {
  abilitySchema,
  buildSchemaFiles,
  characterSchema,
  locationSchema,
  organizationSchema,
  schemaReadme,
  worldSchema,
} from "../../src/core/settingsSchema";
import { emptyCharacter } from "../../src/models/character";
import { emptyAbility } from "../../src/models/ability";
import { emptyLocation } from "../../src/models/location";
import { emptyOrganization } from "../../src/models/organization";
import { emptyWorldItem } from "../../src/models/world";
import { SUMMARY_MAX_CHARS } from "../../src/core/summaryLimit";

/**
 * 外部のAIへ渡すスキーマが、実際のデータ構造とずれていないかを固定する。
 *
 * ずれると、AIはスキーマどおりに書いたのに読み込みで落ちる。
 * 書いた側は成功したと思い込むので、原因にたどり着きにくい。
 * 抽出側で同じ取りこぼしを2度やっているので、同じ形で守る。
 */

function propertyNames(schema: Record<string, unknown>): string[] {
  return Object.keys(schema.properties as Record<string, unknown>);
}

const CASES = [
  {
    label: "登場人物",
    schema: characterSchema(),
    record: emptyCharacter("char_001", "灯") as unknown as Record<
      string,
      unknown
    >,
  },
  {
    label: "能力",
    schema: abilitySchema(),
    record: emptyAbility("abil_001", "神術") as unknown as Record<
      string,
      unknown
    >,
  },
  {
    label: "組織",
    schema: organizationSchema(),
    record: emptyOrganization("org_001", "ギルド") as unknown as Record<
      string,
      unknown
    >,
  },
  {
    label: "場所",
    schema: locationSchema(),
    record: emptyLocation("loc_001", "図書塔") as unknown as Record<
      string,
      unknown
    >,
  },
  {
    label: "世界観",
    schema: worldSchema(),
    record: emptyWorldItem("world_001", "詠唱の制約") as unknown as Record<
      string,
      unknown
    >,
  },
];

describe("スキーマとデータ構造を突き合わせる", () => {
  for (const { label, schema, record } of CASES) {
    test(`${label}：レコードの項目がすべてスキーマにある`, () => {
      const declared = new Set(propertyNames(schema));
      const missing = Object.keys(record).filter((key) => !declared.has(key));

      expect(
        missing,
        `スキーマに無い項目: ${missing.join("、")}。` +
          "settingsSchema.ts に足してください（外部AIがその項目を書けません）"
      ).toEqual([]);
    });

    test(`${label}：スキーマに無い項目を書かせない`, () => {
      // additionalProperties を許すと、AIが勝手な項目を足しても
      // 読み込み時に落ちるだけで、書いた側は成功したと思い込む
      expect(schema.additionalProperties).toBe(false);
    });

    test(`${label}：スキーマの項目がすべてレコードにある`, () => {
      const actual = new Set(Object.keys(record));
      const extra = propertyNames(schema).filter((key) => !actual.has(key));

      expect(
        extra,
        `データ構造に無い項目: ${extra.join("、")}。` +
          "モデルから消したならスキーマからも消してください"
      ).toEqual([]);
    });
  }
});

describe("AIへの注意書き", () => {
  const readme = schemaReadme("いじめられっ子");

  test("作者の記述を守る約束を必ず書く", () => {
    // スキーマでは表せない。ここに書かないと伝わらない
    expect(readme).toContain("authorNotes");
    expect(readme).toContain("書き換えない");
    expect(readme).toContain("autoGenerated");
    expect(readme).toContain("authorLocked");
  });

  test("字数の上限は定数から書く", () => {
    // 直書きすると、上限を変えたときに説明だけ古くなる
    expect(readme).toContain(`${SUMMARY_MAX_CHARS}字以内`);
  });

  test("承認待ちになることを伝える", () => {
    // すぐ反映されないと知らないと、AIは書けていないと判断して書き直す
    expect(readme).toContain("承認待ち");
  });

  test("生成物を編集しても消えることを伝える", () => {
    expect(readme).toContain("次の生成で消えます");
  });

  test("作品名を入れる", () => {
    expect(readme).toContain("いじめられっ子");
  });
});

describe("書き出すファイル一式", () => {
  test("スキーマ5種と説明書を出す", () => {
    const files = buildSchemaFiles("作品").map((file) => file.fileName);

    expect(files).toEqual([
      "README.md",
      "character.schema.json",
      "ability.schema.json",
      "organization.schema.json",
      "location.schema.json",
      "world.schema.json",
    ]);
  });

  test("JSONとして読める形で書く", () => {
    for (const file of buildSchemaFiles("作品")) {
      if (!file.fileName.endsWith(".json")) continue;
      expect(() => JSON.parse(file.content)).not.toThrow();
      // 末尾に改行を入れる。Gitの差分で「\ No newline」を出さない
      expect(file.content.endsWith("\n")).toBe(true);
    }
  });
});
