import { describe, expect, test } from "vitest";
import {
  findAbilityMergeCandidates,
  isContainedName,
  mergeExtractedAbilities,
  mergeExtractedLocations,
} from "../../src/core/settingsMerge";
import { emptyAbility } from "../../src/models/ability";
import { emptyLocation } from "../../src/models/location";

function mergeAbilities(names: string[]) {
  return mergeExtractedAbilities(
    [],
    names.map((name) => ({ data: { name }, chapters: [1] }))
  );
}

describe("能力のマージ", () => {
  test("同じ能力を話数付きでまとめる", () => {
    const result = mergeExtractedAbilities(
      [],
      [
        { data: { name: "灯火", description: "光を灯す" }, chapters: [1] },
        { data: { name: "灯火", userNames: ["灯"] }, chapters: [5] },
      ]
    );

    expect(result.abilities).toHaveLength(1);
    expect(result.abilities[0].appearedChapters).toEqual([1, 5]);
    expect(result.abilities[0].userNames).toEqual(["灯"]);
    expect(result.abilities[0].description).toBe("光を灯す");
  });

  test("別表記をaliasesへ集約する", () => {
    const result = mergeExtractedAbilities(
      [],
      [{ data: { name: "灯火", aliases: ["ともしび"] }, chapters: [1] }]
    );

    expect(result.abilities[0].aliases).toEqual(["ともしび"]);
  });

  test("作者が確定させた能力は話数追記だけにする", () => {
    const existing = emptyAbility("abil_001", "灯火");
    existing.autoGenerated = false;
    existing.description = "作者が書いた説明";
    existing.authorNotes = "作者メモ";

    const result = mergeExtractedAbilities(
      [existing],
      [
        {
          data: { name: "灯火", description: "AIが書いた説明" },
          chapters: [7],
        },
      ]
    );

    expect(result.abilities[0].description).toBe("作者が書いた説明");
    expect(result.abilities[0].authorNotes).toBe("作者メモ");
    expect(result.abilities[0].appearedChapters).toEqual([7]);
  });

  test("食い違う説明は上書きせずconflictsに残す", () => {
    const result = mergeExtractedAbilities(
      [],
      [
        { data: { name: "灯火", cost: "微量の魔力" }, chapters: [1] },
        { data: { name: "灯火", cost: "詠唱3秒" }, chapters: [2] },
      ]
    );

    expect(result.abilities[0].cost).toBe("微量の魔力");
    expect(result.conflicts).toEqual([
      { name: "灯火", field: "cost", values: ["微量の魔力", "詠唱3秒"] },
    ]);
    // 話数と並べれば、作中での変化かどうかを作者が読み分けられる
    expect(result.abilities[0].conflicts[0].observations).toEqual([
      { value: "微量の魔力", chapters: [] },
      { value: "詠唱3秒", chapters: [2] },
    ]);
  });

  test("同じ値が別の話にも出てきたら話数だけを足す", () => {
    const result = mergeExtractedAbilities(
      [],
      [
        { data: { name: "灯火", cost: "微量の魔力" }, chapters: [1] },
        { data: { name: "灯火", cost: "詠唱3秒" }, chapters: [2] },
        // 同じ「詠唱3秒」が第5話にも出てきた
        { data: { name: "灯火", cost: "詠唱3秒" }, chapters: [5] },
        // 先にあった「微量の魔力」も、第6話に出てきた時点で話数が分かる
        { data: { name: "灯火", cost: "微量の魔力" }, chapters: [6] },
      ]
    );

    expect(result.abilities[0].conflicts[0].observations).toEqual([
      { value: "微量の魔力", chapters: [6] },
      { value: "詠唱3秒", chapters: [2, 5] },
    ]);
  });

  test("入力レコードを書き換えない", () => {
    const existing = emptyAbility("abil_001", "灯火");
    const before = structuredClone(existing);

    mergeExtractedAbilities(
      [existing],
      [{ data: { name: "灯火", description: "光" }, chapters: [2] }]
    );

    expect(existing).toEqual(before);
  });
});

describe("能力の統合候補", () => {
  test("一方が他方を含む能力名を候補として挙げる", () => {
    // 「聖紋神術の同時発動」は使い方であって別能力ではない（実データで確認）
    const result = mergeAbilities(["聖紋神術", "聖紋神術の同時発動"]);

    // 自動では統合しない。作者が判断できるよう候補として出すだけ
    expect(result.abilities).toHaveLength(2);
    expect(result.mergeCandidates).toEqual([
      { names: ["聖紋神術", "聖紋神術の同時発動"], reason: "contains" },
    ]);
  });

  test("含まない別能力は候補にしない", () => {
    const result = mergeAbilities(["炎槍", "氷槍"]);

    expect(result.mergeCandidates).toEqual([]);
  });

  test("短すぎる語は誤検出の元なので候補にしない", () => {
    // 「聖言」が「聖言詠唱」に含まれるが、2文字では別能力の可能性が高い
    expect(isContainedName("聖言", "聖言詠唱")).toBe(false);
  });

  test("すでに別名として統合済みなら候補にしない", () => {
    const a = emptyAbility("abil_001", "聖紋神術");
    a.aliases = ["聖紋神術の同時発動"];

    expect(findAbilityMergeCandidates([a])).toEqual([]);
  });

  test("実データの能力名で誤検出が出ない", () => {
    const result = mergeAbilities([
      "神術",
      "仙術",
      "剣術",
      "槍術",
      "弓術",
      "遠当て",
      "雲歩",
      "炎槍",
      "聖言",
    ]);

    expect(result.mergeCandidates).toEqual([]);
  });
});

describe("場所のマージ", () => {
  test("同じ場所を話数付きでまとめ、地域を保持する", () => {
    const result = mergeExtractedLocations(
      [],
      [
        { data: { name: "図書塔", region: "王都リヴェルス" }, chapters: [1] },
        { data: { name: "図書塔", description: "魔導書庫" }, chapters: [3] },
      ]
    );

    expect(result.locations).toHaveLength(1);
    expect(result.locations[0].region).toBe("王都リヴェルス");
    expect(result.locations[0].description).toBe("魔導書庫");
    expect(result.locations[0].appearedChapters).toEqual([1, 3]);
  });

  test("作者が確定させた場所の説明を上書きしない", () => {
    const existing = emptyLocation("loc_001", "図書塔");
    existing.autoGenerated = false;
    existing.description = "作者が書いた説明";

    const result = mergeExtractedLocations(
      [existing],
      [{ data: { name: "図書塔", description: "AIの説明" }, chapters: [4] }]
    );

    expect(result.locations[0].description).toBe("作者が書いた説明");
    expect(result.locations[0].appearedChapters).toEqual([4]);
  });

  test("空白だけの名前は登録しない", () => {
    const result = mergeExtractedLocations(
      [],
      [{ data: { name: "   " }, chapters: [1] }]
    );

    expect(result.locations).toEqual([]);
    expect(result.changedIds).toEqual([]);
  });
});
