import { describe, expect, test } from "vitest";
import { emptyCharacter, type Character } from "../../../src/models/character";
import {
  authorSpeechStyleAsOf,
  recordSpeechStyleChange,
} from "../../../src/core/speechStyle";
import { recordAsOf } from "../../../src/core/settingsAsOf";
import { CHARACTER_AS_OF_FIELDS } from "../../../src/core/contradictionMaterial";
import { describeCharacter } from "../../../src/core/settingsSummary";

/**
 * 作者が「第N話から口調が変わった」と記録する（作者の裁定、2026-09-26 夕。
 * 残課題 J9。設計書 6.5.11）。
 *
 * 記録した話からは、矛盾検知（P-12）の材料の口調が記録した値になり、
 * 前の口調との違いを「食い違い」と読ませない。
 */
function person(): Character {
  const character = emptyCharacter("c1", "ミナ");
  character.speechStyle = "敬語／語尾「〜です」";
  character.speechStyleFacets = [
    { value: "敬語", chapters: [1], evidence: "おはようございます" },
    { value: "語尾「〜です」", chapters: [3], evidence: "それは私です" },
  ];
  character.appearedChapters = [1, 3, 8, 10];
  return character;
}

describe("口調の変化を記録する（J9）", () => {
  test("作者の値として changes に残し、本体と面と autoGenerated は変えない", () => {
    const before = person();
    before.autoGenerated = true;
    const after = recordSpeechStyleChange(before, 8, "ため口／語尾「〜だよ」");

    expect(after).toBeDefined();
    const changes = after!.changes.filter((change) => change.field === "speechStyle");
    expect(changes).toEqual([
      // 変わる前は、第7話の時点で材料に載る口調
      expect.objectContaining({
        value: "敬語／語尾「〜です」",
        chapters: [7],
        source: "author",
        confirmed: true,
      }),
      expect.objectContaining({
        value: "ため口／語尾「〜だよ」",
        chapters: [8],
        source: "author",
        confirmed: true,
      }),
    ]);
    // 本体と面は抽出の読みのまま。作者の値は変化の記録に置く
    expect(after!.speechStyle).toBe(before.speechStyle);
    expect(after!.speechStyleFacets).toEqual(before.speechStyleFacets);
    expect(after!.autoGenerated).toBe(true);
    // 元のレコードは書き換えない
    expect(before.changes).toEqual([]);
  });

  test("記録した話からは、材料の口調が記録した値になる", () => {
    const after = recordSpeechStyleChange(person(), 8, "ため口／語尾「〜だよ」")!;

    expect(recordAsOf(after, CHARACTER_AS_OF_FIELDS, 8).speechStyle).toBe(
      "ため口／語尾「〜だよ」"
    );
    expect(recordAsOf(after, CHARACTER_AS_OF_FIELDS, 12).speechStyle).toBe(
      "ため口／語尾「〜だよ」"
    );
  });

  test("記録した話より前は、これまでどおり面で巻き戻す", () => {
    const after = recordSpeechStyleChange(person(), 8, "ため口／語尾「〜だよ」")!;

    // 第2話では、第3話で見えた面はまだ載らない
    expect(recordAsOf(after, CHARACTER_AS_OF_FIELDS, 2).speechStyle).toBe("敬語");
    expect(recordAsOf(after, CHARACTER_AS_OF_FIELDS, 7).speechStyle).toBe(
      "敬語／語尾「〜です」"
    );
  });

  test("記録した話からの材料に、第N話からの変化として載る", () => {
    const after = recordSpeechStyleChange(person(), 8, "ため口／語尾「〜だよ」")!;
    const text = describeCharacter(recordAsOf(after, CHARACTER_AS_OF_FIELDS, 9), []);

    expect(text).toContain("口調: ため口／語尾「〜だよ」");
    expect(text).toContain("敬語／語尾「〜です」（第7話）→ ため口／語尾「〜だよ」（第8話）");
  });

  /*
    **記録より前の話の材料に、記録も後の面も漏らさない**（2026-09-25 精査 F1 と
    同じ漏れ）。「変わる前の口調」を「それ以前」として記録に並べると、その値
    （第3話の面を含む）が第2話の材料の変化の行に載る。
  */
  test("記録より前の話の材料には、記録も後で見える面も載らない", () => {
    const after = recordSpeechStyleChange(person(), 8, "ため口／語尾「〜だよ」")!;
    const text = describeCharacter(recordAsOf(after, CHARACTER_AS_OF_FIELDS, 2), []);

    expect(text).toContain("口調: 敬語");
    expect(text).not.toContain("ため口");
    expect(text).not.toContain("〜です");
  });

  test("面で巻き戻せない資料（本体を手で直した）でも、記録より前は本体を使う", () => {
    const handEdited = person();
    handEdited.speechStyle = "丁寧だが早口";
    const after = recordSpeechStyleChange(handEdited, 8, "ため口")!;

    expect(recordAsOf(after, CHARACTER_AS_OF_FIELDS, 5).speechStyle).toBe(
      "丁寧だが早口"
    );
    expect(recordAsOf(after, CHARACTER_AS_OF_FIELDS, 8).speechStyle).toBe("ため口");
  });

  test("2度記録すれば、話ごとにその時点の記録を使う", () => {
    const once = recordSpeechStyleChange(person(), 8, "ため口")!;
    const twice = recordSpeechStyleChange(once, 12, "荒っぽい口調")!;

    expect(authorSpeechStyleAsOf(twice.changes, 6)).toBeUndefined();
    expect(authorSpeechStyleAsOf(twice.changes, 9)).toBe("ため口");
    expect(authorSpeechStyleAsOf(twice.changes, 12)).toBe("荒っぽい口調");
    // 2度目の「変わる前」は1度目の記録なので、同じ値を二重に積まない
    const speech = twice.changes.filter((change) => change.field === "speechStyle");
    expect(speech.map((change) => [change.value, change.chapters])).toEqual([
      ["敬語／語尾「〜です」", [7]],
      ["ため口", [8, 11]],
      ["荒っぽい口調", [12]],
    ]);
  });

  test("受け取らないもの：話数が正の整数でない・口調が空・同じ話に別の記録がある", () => {
    expect(recordSpeechStyleChange(person(), 0, "ため口")).toBeUndefined();
    expect(recordSpeechStyleChange(person(), 2.5, "ため口")).toBeUndefined();
    expect(recordSpeechStyleChange(person(), 8, "   ")).toBeUndefined();
    const once = recordSpeechStyleChange(person(), 8, "ため口")!;
    // 同じ話に別の値を重ねると、どちらが正しいか決められない。先に落とさせる
    expect(recordSpeechStyleChange(once, 8, "荒っぽい口調")).toBeUndefined();
  });

  test("口調の記録が無い人物（面も本体も空）でも記録できる", () => {
    const blank = emptyCharacter("c2", "トオル");
    const after = recordSpeechStyleChange(blank, 5, "関西弁")!;

    expect(
      after.changes.filter((change) => change.field === "speechStyle")
    ).toEqual([expect.objectContaining({ value: "関西弁", chapters: [5] })]);
    expect(recordAsOf(after, CHARACTER_AS_OF_FIELDS, 6).speechStyle).toBe("関西弁");
  });
});
