import * as path from "path";
import { describe, expect, test } from "vitest";
import { buildSynopsisChapterMarks } from "../../src/core/synopsisChapters";
import type { Chapter } from "../../src/models/chapter";
import type { ChapterSynopsis, ChapterSynopsisSet } from "../../src/models/synopsis";
import type { EpisodeFile } from "../../src/models/types";

/**
 * あらすじの文書へ挟む章の印（設計書6.66.4の3）。
 *
 * 章の台帳は**話のパス**で章を指し、あらすじは**話数とファイル名**で
 * 話を指す。両者を突き合わせて「どのあらすじの直前に章の見出しを置くか」
 * を決めるのがここである。
 *
 * **束ね方は作品一覧と同じ部品**（`groupEpisodesByChapter`）を通す。
 * ここで別に束ねると、一覧の章の切れ目と文書の切れ目がずれる。
 */

const WORK_FOLDER = path.join("C:", "novels", "work");

function episodeFile(chapterStart: number, fileName: string): EpisodeFile {
  return {
    filePath: path.join(WORK_FOLDER, "本文", fileName),
    fileName,
    ext: ".txt",
    chapterStart,
    chapterEnd: chapterStart,
    subtitle: null,
    kind: "本編",
    isInitialName: false,
    counts: { net: 0, gross: 0, lines: 0, paragraphs: 0, manuscriptLines: 0 },
    hasMetadata: false,
    metaTitle: null,
    declaredCharCount: null,
    metaUpdatedAt: null,
    hasConflictMarkers: false,
    collectedCount: null,
  };
}

function synopsis(chapter: number, fileName: string): ChapterSynopsis {
  return {
    chapter,
    fileName,
    title: null,
    synopsis: `第${chapter}話のあらすじ。`,
    sourceHash: "hash",
    model: "test",
    promptVersion: "1.0",
    autoGenerated: true,
    authorNotes: "",
    emotion: null,
    updatedAt: null,
  };
}

/** 第1話〜第5話（001.txt〜005.txt） */
const files = [1, 2, 3, 4, 5].map((n) =>
  episodeFile(n, `${String(n).padStart(3, "0")}.txt`)
);

const set: ChapterSynopsisSet = {
  schemaVersion: "0.1",
  episodes: files.map((file) => synopsis(file.chapterStart!, file.fileName)),
};

function chapter(name: string, fileName: string): Chapter {
  return { name, startEpisodePath: `本文/${fileName}` };
}

describe("章の印の組み立て", () => {
  test("章の始まる話のあらすじを指す", () => {
    const marks = buildSynopsisChapterMarks(
      set,
      files,
      [chapter("第一章　出立", "003.txt")],
      WORK_FOLDER
    );

    expect(marks).toHaveLength(1);
    expect(marks[0].name).toBe("第一章　出立");
    expect(marks[0].startKey).toBe("#3");
    expect(marks[0].range).toBe("第3話〜第5話・3話");
  });

  test("章が無ければ印も無い（従来どおりの文書になる）", () => {
    expect(buildSynopsisChapterMarks(set, files, [], WORK_FOLDER)).toEqual([]);
  });

  test("開始の話が見つからない章は、印を作らない", () => {
    // 一覧と同じ扱い。束ねる場所が決まらないものを、当て推量で挟まない
    const marks = buildSynopsisChapterMarks(
      set,
      files,
      [chapter("第一章", "003.txt"), chapter("幻の章", "999.txt")],
      WORK_FOLDER
    );

    expect(marks.map((mark) => mark.name)).toEqual(["第一章"]);
  });

  test("あらすじが1つも無い章は、見出しだけを立てない", () => {
    // 第4話から始まる章だが、あらすじは第3話までしかない
    const partial: ChapterSynopsisSet = {
      schemaVersion: "0.1",
      episodes: set.episodes.slice(0, 3),
    };

    const marks = buildSynopsisChapterMarks(
      partial,
      files,
      [chapter("第一章", "002.txt"), chapter("第二章", "004.txt")],
      WORK_FOLDER
    );

    expect(marks.map((mark) => mark.name)).toEqual(["第一章"]);
  });

  test("章の途中の話しかあらすじが無ければ、その話を指す", () => {
    const partial: ChapterSynopsisSet = {
      schemaVersion: "0.1",
      episodes: [synopsis(5, "005.txt")],
    };

    const marks = buildSynopsisChapterMarks(
      partial,
      files,
      [chapter("第二章", "004.txt")],
      WORK_FOLDER
    );

    expect(marks[0].startKey).toBe("#5");
  });

  test("SNS記事では範囲の言い方も変える", () => {
    const marks = buildSynopsisChapterMarks(
      set,
      files,
      [chapter("八月", "003.txt")],
      WORK_FOLDER,
      "sns"
    );

    expect(marks[0].range).toBe("投稿3〜投稿5・3投稿");
  });

  test("合本（1ファイルに複数話）でも、ファイルの章に入る", () => {
    // 合本の中の話は同じファイル名を持つ。章はファイル単位で決まる
    const collected = [episodeFile(1, "全話.txt")];
    const collectedSet: ChapterSynopsisSet = {
      schemaVersion: "0.1",
      episodes: [synopsis(1, "全話.txt"), synopsis(2, "全話.txt")],
    };

    const marks = buildSynopsisChapterMarks(
      collectedSet,
      collected,
      [chapter("第一章", "全話.txt")],
      WORK_FOLDER
    );

    expect(marks[0].startKey).toBe("#1");
  });
});
