import { beforeEach, describe, expect, test, vi } from "vitest";
import * as path from "path";
import { SynopsisStore } from "../../src/core/synopsisStore";
import type { WorkEntry } from "../../src/models/types";
import type { ChapterSynopsis } from "../../src/models/synopsis";
import { FileSystemError, Uri, workspace } from "./support/vscodeStub";

const work: WorkEntry = {
  id: "w1",
  title: "テスト作品",
  folderPath: "C:\\novels\\テスト作品",
  registeredAt: new Date(0).toISOString(),
};

const storeFile = Uri.file(
  path.join(work.folderPath, "設定", "chapter_synopses.json")
).fsPath;

function episode(overrides: Partial<ChapterSynopsis> = {}): ChapterSynopsis {
  return {
    chapter: 17,
    fileName: "017.txt",
    title: null,
    synopsis: "あらすじ",
    sourceHash: "hash",
    model: "test",
    promptVersion: "1.0",
    autoGenerated: true,
    authorNotes: "",
    // 感情の測りは読み取れなければ null。省略すると作り物の型が
    // 「省略可」になり、ChapterSynopsis に収まらない。
    emotion: null,
    updatedAt: null,
    ...overrides,
  };
}

describe("あらすじの読み込み時の自己修復（重複の統合）", () => {
  const files = new Map<string, Uint8Array>();

  beforeEach(() => {
    files.clear();
    workspace.fs = {
      createDirectory: vi.fn(async () => {}),
      readFile: vi.fn(async (uri: { fsPath: string }) => {
        const bytes = files.get(uri.fsPath);
        if (!bytes) throw new FileSystemError("missing", "FileNotFound");
        return bytes;
      }),
      writeFile: vi.fn(async (uri: { fsPath: string }, bytes: Uint8Array) => {
        files.set(uri.fsPath, bytes);
      }),
      rename: vi.fn(
        async (
          from: { fsPath: string },
          to: { fsPath: string },
          options?: { overwrite?: boolean }
        ) => {
          const bytes = files.get(from.fsPath);
          if (!bytes) throw new Error("一時ファイルがありません");
          if (!options?.overwrite && files.has(to.fsPath)) {
            throw new FileSystemError("exists", "FileExists");
          }
          files.set(to.fsPath, bytes);
          files.delete(from.fsPath);
        }
      ),
      stat: vi.fn(async (uri: { fsPath: string }) => {
        if (!files.has(uri.fsPath)) {
          throw new FileSystemError("missing", "FileNotFound");
        }
        return {};
      }),
    };
  });

  function seed(episodes: ChapterSynopsis[]): void {
    files.set(
      storeFile,
      new TextEncoder().encode(
        `${JSON.stringify({ schemaVersion: "0.1", episodes }, null, 2)}\n`
      )
    );
  }

  test("重複が無ければそのまま返す", async () => {
    seed([episode({ chapter: 1 }), episode({ chapter: 2 })]);
    const set = await new SynopsisStore(work).load();
    expect(set.episodes).toHaveLength(2);
  });

  test("リネームで残った重複を1つにまとめ、ディスクの内容も直す", async () => {
    // 実機で見つかった不具合の再現：リネーム前後で2件になっていた状態
    seed([
      episode({
        fileName: "017.txt",
        title: null,
        synopsis: "旧",
        updatedAt: "2026-08-12T00:00:00.000Z",
      }),
      episode({
        fileName: "017_狐霊の進化と呪詛の謎.txt",
        title: "狐霊の進化と呪詛の謎",
        synopsis: "新",
        updatedAt: "2026-08-13T00:00:00.000Z",
      }),
    ]);

    const set = await new SynopsisStore(work).load();
    expect(set.episodes).toHaveLength(1);
    expect(set.episodes[0].synopsis).toBe("新");

    // 直した内容がディスクにも書き戻されている（次回読んだときも重複しない）
    const saved = JSON.parse(
      new TextDecoder().decode(files.get(storeFile))
    );
    expect(saved.episodes).toHaveLength(1);
  });

  test("ファイルが無ければ空として返す", async () => {
    const set = await new SynopsisStore(work).load();
    expect(set.episodes).toEqual([]);
  });

  test("空のあらすじを保存すると、次に読めなくなる（だから空を書かせない）", async () => {
    /*
      相談パネルの「取り消す」は、書く前が未記入なら空を書き戻す
      （設計書6.4.7）。plot.md と同じつもりでここへ空を書くと、**保存は
      通るのに次の読み込みで台帳ごと読めなくなる**——あらすじは非空を
      前提に検証しているためである（plot.md の「黙って効かない」より悪い）。

      **だから `applyChatEdit` は各話あらすじを空にしない**（その場で断る）。
      ここはその理由を記録する試験である。
    */
    seed([episode({ chapter: 1, synopsis: "書いたあらすじ" })]);
    const store = new SynopsisStore(work);
    const set = await store.load();

    await store.save({
      ...set,
      episodes: set.episodes.map((item) => ({ ...item, synopsis: "" })),
    });

    await expect(store.load()).rejects.toThrow(/synopsis/);
  });
});
