import { describe, expect, test } from "vitest";
import {
  MAX_CUSTOM_FIELDS,
  nextCustomFieldKey,
  parseCustomFieldSet,
  parseCustomFieldValues,
  validateNewField,
  type CustomFieldDefinition,
} from "../../src/models/customField";
import {
  applyCharacterEdits,
  editedCustomFields,
  toRecordEdits,
} from "../../src/core/settingsEdit";
import { emptyCharacter, parseCharacter } from "../../src/models/character";
import { diffCharacter } from "../../src/core/characterDiff";
import { buildCharacterMarkdown } from "../../src/core/settingsMarkdown";
import { describeCharacter } from "../../src/core/settingsSummary";
import {
  buildEnrichSchema,
  enrichableFields,
} from "../../src/prompts/settingsEnrich";

function definition(
  key: string,
  label: string,
  extra: Partial<CustomFieldDefinition> = {}
): CustomFieldDefinition {
  return { key, label, hint: "", multiline: false, ...extra };
}

describe("項目の定義", () => {
  test("見出しを変えても値が失われないよう、キーは連番にする", () => {
    // 見出しをそのままキーにすると、名前を直した瞬間に値と結び付かなくなる
    expect(nextCustomFieldKey([])).toBe("field_001");
    expect(nextCustomFieldKey([definition("field_001", "誕生日")])).toBe(
      "field_002"
    );
  });

  test("外したあとに足しても、キーは使い回さない", () => {
    // 使い回すと、残っている旧項目の値が別の項目に化けて現れる
    const remaining = [definition("field_003", "身長")];
    expect(nextCustomFieldKey(remaining)).toBe("field_004");
  });

  test("同じ名前は追加させない", () => {
    const existing = [definition("field_001", "誕生日")];
    expect(validateNewField(existing, "誕生日")).toContain("すでにあります");
    expect(validateNewField(existing, "身長")).toBeUndefined();
  });

  test("既定の項目名とぶつかる名前は断る", () => {
    // 通すと、追加項目の値が既定の項目を隠す
    expect(validateNewField([], "gender")).toContain("既定の項目名");
    expect(validateNewField([], "summary")).toContain("既定の項目名");
  });

  test("空の名前と長すぎる名前を断る", () => {
    expect(validateNewField([], "   ")).toContain("入力してください");
    expect(validateNewField([], "あ".repeat(21))).toContain("20字以内");
  });

  test("多すぎる項目を断る", () => {
    const many = Array.from({ length: MAX_CUSTOM_FIELDS }, (_, index) =>
      definition(`field_${index}`, `項目${index}`)
    );
    expect(validateNewField(many, "もう一つ")).toContain(
      `${MAX_CUSTOM_FIELDS}個まで`
    );
  });
});

describe("項目定義のJSON検証", () => {
  test("欠けた項目は既定値で補う", () => {
    const parsed = parseCustomFieldSet({
      fields: [{ key: "field_001", label: "誕生日" }],
    });
    expect(parsed.fields).toEqual([
      { key: "field_001", label: "誕生日", hint: "", multiline: false },
    ]);
  });

  test("壊れていたら勝手に直さず止める", () => {
    // 空として扱って上書きすると、作者が書いた定義がまるごと消える
    expect(() => parseCustomFieldSet({ fields: [{ key: "field_001" }] })).toThrow();
    expect(() => parseCustomFieldSet({ fields: "誕生日" })).toThrow();
    expect(() =>
      parseCustomFieldSet({
        fields: [
          { key: "field_001", label: "誕生日" },
          { key: "field_001", label: "身長" },
        ],
      })
    ).toThrow();
  });
});

describe("人物レコードが持つ追加項目の値", () => {
  test("空の値は持たない", () => {
    expect(
      parseCustomFieldValues({ field_001: "3月3日", field_002: "  " })
    ).toEqual({ field_001: "3月3日" });
  });

  test("文字列以外は受け付けない", () => {
    expect(() => parseCustomFieldValues({ field_001: 3 })).toThrow();
  });

  test("未設定なら空にする", () => {
    expect(parseCustomFieldValues(undefined)).toEqual({});
    expect(parseCharacter({ id: "char_001", name: "灯" }).customFields).toEqual(
      {}
    );
  });

  test("読み書きで値が残る", () => {
    const character = {
      ...emptyCharacter("char_001", "灯"),
      customFields: { field_001: "3月3日" },
    };
    expect(parseCharacter(character).customFields).toEqual({
      field_001: "3月3日",
    });
  });
});

describe("追加項目の書き換え", () => {
  test("空欄にすると値を消す", () => {
    expect(editedCustomFields({ field_001: "3月3日" }, { field_001: "" })).toEqual(
      {}
    );
  });

  test("画面に出ていない項目は巻き添えで消さない", () => {
    // 定義を外したあとも値だけ残る。保存のたびに消えると、
    // 項目を戻しても中身が空になっている
    const current = { field_001: "3月3日", field_009: "外した項目の値" };
    expect(editedCustomFields(current, { field_001: "3月4日" })).toEqual({
      field_001: "3月4日",
      field_009: "外した項目の値",
    });
  });

  test("作者が書き換えたら、以後の抽出で上書きされないようにする", () => {
    const edited = applyCharacterEdits(emptyCharacter("char_001", "灯"), {
      customFields: { field_001: "3月3日" },
    });
    expect(edited.customFields).toEqual({ field_001: "3月3日" });
    expect(edited.autoGenerated).toBe(false);
  });

  test("AIの提案を反映しただけなら作者確定にしない", () => {
    const edited = applyCharacterEdits(
      emptyCharacter("char_001", "灯"),
      { customFields: { field_001: "3月3日" } },
      { authorConfirmed: false }
    );
    expect(edited.autoGenerated).toBe(true);
  });
});

describe("画面から来たキーの振り分け", () => {
  test("custom: 付きだけを追加項目に回す", () => {
    expect(
      toRecordEdits({ role: "主人公", "custom:field_001": "3月3日" })
    ).toEqual({
      role: "主人公",
      customFields: { field_001: "3月3日" },
    });
  });

  test("追加項目が無ければ customFields を付けない", () => {
    // 空の {} を渡すと、渡されなかった項目まで触ったことになる
    expect(toRecordEdits({ role: "主人公" })).toEqual({ role: "主人公" });
  });
});

describe("追加項目の表示", () => {
  const fields = [
    definition("field_001", "誕生日"),
    definition("field_002", "口癖", { multiline: true }),
  ];
  const character = {
    ...emptyCharacter("char_001", "灯"),
    customFields: { field_001: "3月3日" },
  };

  test("設定資料集に、定義した順で出す", () => {
    const markdown = buildCharacterMarkdown([character], {
      workTitle: "作品",
      customFields: fields,
    });
    expect(markdown).toContain("- **誕生日**: 3月3日");
    // 値が無い項目は出さない。空の見出しが並ぶと読みにくい
    expect(markdown).not.toContain("口癖");
  });

  test("AIへ渡す現在の設定にも含める", () => {
    expect(describeCharacter(character, fields)).toContain("誕生日: 3月3日");
  });

  test("差分に見出しで出す", () => {
    const after = {
      ...character,
      customFields: { field_001: "3月4日" },
    };
    const diff = diffCharacter(character, after, fields);
    expect(diff.changes).toContainEqual({
      label: "誕生日",
      before: "3月3日",
      after: "3月4日",
    });
  });

  test("定義から外した項目の変化も見逃さない", () => {
    // 定義が無いからと差分に出さないと、気付けない書き換えになる
    const after = {
      ...character,
      customFields: { field_001: "3月3日", field_009: "増えた値" },
    };
    const diff = diffCharacter(character, after, fields);
    expect(diff.changes).toContainEqual({
      label: "field_009",
      before: "",
      after: "増えた値",
    });
  });
});

describe("AIへの項目提案", () => {
  const fields = [definition("field_001", "誕生日", { hint: "本文の記述から" })];

  test("人物には追加項目も提案させる", () => {
    const keys = enrichableFields("character", fields).map((field) => field.key);
    expect(keys).toContain("field_001");
    expect(keys).toContain("gender");
  });

  test("能力・場所には広げない", () => {
    expect(enrichableFields("ability", fields).map((f) => f.key)).not.toContain(
      "field_001"
    );
  });

  test("スキーマで必須にして、面倒な項目を落とさせない", () => {
    const schema = buildEnrichSchema("character", fields) as {
      properties: Record<string, unknown>;
      required: string[];
    };
    expect(schema.properties).toHaveProperty("field_001");
    expect(schema.required).toContain("field_001");
  });
});
