import * as path from "path";
import { beforeEach, describe, expect, test } from "vitest";
import { refreshSynopsisDoc } from "../../src/features/generateBlurb";
import type { WorkEntry } from "../../src/models/types";
import type { ChapterSynopsis } from "../../src/models/synopsis";
import {
  commands,
  FileSystemError,
  FileType,
  Uri,
  window,
  workspace,
} from "./support/vscodeStub";

/**
 * あらすじの文書に章の見出しが挟まること（設計書6.66.4の3）。
 *
 * ここは作り物のファイルシステムで `refreshSynopsisDoc` をそのまま動かす。
 * 文書の組み立てだけを別に呼ぶと、**台帳を読んで突き合わせる配線**
 * （いちばん壊れやすいところ）を確かめたことにならない。
 */

const work: WorkEntry = {
  id: "work_synopsis_chapters",
  title: "氷の街",
  folderPath: "C:\\novels\\work",
  registeredAt: "2026-09-04T00:00:00.000Z",
};

const disk = new Map<string, Uint8Array>();

function diskPath(filePath: string): string {
  return Uri.file(filePath).fsPath;
}

function put(relativePath: string, text: string): void {
  disk.set(
    diskPath(path.join(work.folderPath, relativePath)),
    new TextEncoder().encode(text)
  );
}

function read(relativePath: string): string {
  const bytes = disk.get(diskPath(path.join(work.folderPath, relativePath)));
  if (!bytes) throw new Error(`${relativePath} がありません`);
  return new TextDecoder().decode(bytes);
}

function installDisk(): void {
  const separator = path.sep;
  workspace.fs = {
    createDirectory: async () => undefined,
    readFile: async (uri: { fsPath: string }) => {
      const bytes = disk.get(uri.fsPath);
      if (!bytes) throw new FileSystemError("missing", "FileNotFound");
      return bytes;
    },
    writeFile: async (uri: { fsPath: string }, bytes: Uint8Array) => {
      disk.set(uri.fsPath, bytes);
    },
    rename: async (
      from: { fsPath: string },
      to: { fsPath: string },
      options?: { overwrite?: boolean }
    ) => {
      const bytes = disk.get(from.fsPath);
      if (!bytes) throw new FileSystemError("missing", "FileNotFound");
      if (!options?.overwrite && disk.has(to.fsPath)) {
        throw new FileSystemError("exists", "FileExists");
      }
      disk.set(to.fsPath, bytes);
      disk.delete(from.fsPath);
    },
    delete: async (uri: { fsPath: string }) => {
      disk.delete(uri.fsPath);
    },
    stat: async (uri: { fsPath: string }) => {
      if (disk.has(uri.fsPath)) {
        return { mtime: Date.UTC(2026, 8, 4, 5, 0, 0), size: 1 };
      }
      const prefix = uri.fsPath + separator;
      for (const key of disk.keys()) {
        if (key.startsWith(prefix)) return { mtime: 0, size: 0 };
      }
      throw new FileSystemError("missing", "FileNotFound");
    },
    readDirectory: async (uri: { fsPath: string }) => {
      const prefix = uri.fsPath + separator;
      const names = new Map<string, FileType>();
      for (const key of disk.keys()) {
        if (!key.startsWith(prefix)) continue;
        const rest = key.slice(prefix.length);
        const cut = rest.indexOf(separator);
        if (cut < 0) names.set(rest, FileType.File);
        else names.set(rest.slice(0, cut), FileType.Directory);
      }
      if (names.size === 0) throw new FileSystemError("missing", "FileNotFound");
      return [...names.entries()];
    },
  } as unknown as typeof workspace.fs;
}

function synopsis(chapter: number, fileName: string): ChapterSynopsis {
  return {
    chapter,
    fileName,
    title: null,
    synopsis: `第${chapter}話の出来事。`,
    sourceHash: "hash",
    model: "test",
    promptVersion: "1.0",
    autoGenerated: true,
    authorNotes: "",
    emotion: null,
    updatedAt: null,
  };
}

/** 第1話〜第4話の本文とあらすじを置く */
function writeWork(): void {
  for (const n of [1, 2, 3, 4]) {
    put(`本文/第${n}話.txt`, "あ\n\nい");
  }
  put(
    "設定/chapter_synopses.json",
    JSON.stringify({
      schemaVersion: "0.1",
      episodes: [1, 2, 3, 4].map((n) => synopsis(n, `第${n}話.txt`)),
    })
  );
}

function writeChapters(chapters: Array<{ name: string; startEpisodePath: string }>): void {
  put(
    "設定/章立て.json",
    JSON.stringify({ schemaVersion: "1", chapters })
  );
}

beforeEach(() => {
  disk.clear();
  installDisk();
  window.showErrorMessage = async () => undefined;
  window.showInformationMessage = async () => undefined;
  (
    commands as { executeCommand?: (...args: unknown[]) => unknown }
  ).executeCommand = () => Promise.resolve(undefined);
  writeWork();
});

describe("各話あらすじの文書に章の見出しを挟む", () => {
  test("章の始まる話の直前に、範囲つきの見出しが入る", async () => {
    writeChapters([
      { name: "第一章　出立", startEpisodePath: "本文/第2話.txt" },
      { name: "第二章　邂逅", startEpisodePath: "本文/第4話.txt" },
    ]);

    await refreshSynopsisDoc(work, work.title);
    const md = read("設定/synopsis.md");

    expect(md).toContain("### 第一章　出立（第2話〜第3話・2話）");
    expect(md).toContain("### 第二章　邂逅（第4話・1話）");
    // 章なしの第1話は先頭にそのまま残る
    expect(md.indexOf("第1話の出来事。")).toBeLessThan(
      md.indexOf("第一章　出立")
    );
    expect(md.indexOf("第一章　出立")).toBeLessThan(md.indexOf("第2話の出来事。"));
    expect(md.indexOf("第2話の出来事。")).toBeLessThan(md.indexOf("第二章　邂逅"));
  });

  test("台帳が無ければ、いままでどおりの文書になる", async () => {
    await refreshSynopsisDoc(work, work.title);
    const md = read("設定/synopsis.md");

    expect(md).toContain("## 各話あらすじ");
    expect(md).toContain("### 第1話");
    // 章の見出しが無いので、話は1段深くならない
    expect(md).not.toContain("#### ");
  });

  test("台帳が空でも、いままでどおりの文書になる", async () => {
    writeChapters([]);

    await refreshSynopsisDoc(work, work.title);

    expect(read("設定/synopsis.md")).not.toContain("#### ");
  });

  test("開始の話が見つからない章では、見出しを挟まない", async () => {
    writeChapters([
      { name: "第一章", startEpisodePath: "本文/第2話.txt" },
      { name: "幻の章", startEpisodePath: "本文/消えた話.txt" },
    ]);

    await refreshSynopsisDoc(work, work.title);
    const md = read("設定/synopsis.md");

    expect(md).toContain("### 第一章（第2話〜第4話・3話）");
    // 束ねる場所が決まらない章は、当て推量で挟まない
    expect(md).not.toContain("幻の章");
  });

  test("台帳が壊れていても、あらすじの文書は出る", async () => {
    put("設定/章立て.json", "{壊れています");

    await refreshSynopsisDoc(work, work.title);
    const md = read("設定/synopsis.md");

    expect(md).toContain("### 第1話");
    expect(md).not.toContain("#### ");
  });

  test("作者の紹介文は、章の見出しを足しても残る", async () => {
    put("設定/synopsis.md", "# 氷の街\n\n> ひとひらの嘘。\n\n作者が書いた紹介文。\n");
    writeChapters([{ name: "第一章", startEpisodePath: "本文/第1話.txt" }]);

    await refreshSynopsisDoc(work, work.title);
    const md = read("設定/synopsis.md");

    expect(md).toContain("作者が書いた紹介文。");
    expect(md).toContain("> ひとひらの嘘。");
    expect(md).toContain("### 第一章（第1話〜第4話・4話）");
  });
});
