import * as fs from "node:fs";
import * as nodePath from "node:path";
import { AIWRITER_DIR } from "../../models/types";
import { parseAbility } from "../../models/ability";
import { parseCharacter } from "../../models/character";
import {
  normalizeLocationName,
  parseLocation,
  type Location,
  type LocationRelation,
  type LocationRelationKind,
} from "../../models/location";
import {
  normalizeExtractedLocation,
  validateLocationRelations,
} from "../../core/settingsExtractionValidation";
import { parseOrganization } from "../../models/organization";
import {
  parseWorldItem,
  WORLD_CATEGORIES,
  WORLD_CATEGORY_LABELS,
  type WorldCategory,
} from "../../models/world";
import {
  ADD_ONLY_PROPOSE_FIELDS,
  EXTERNAL_PROPOSE_FIELDS,
  PENDING_KIND_SHORT_LABELS,
  PENDING_SETTINGS_DIR,
  buildPendingSettingsPayload,
  diffSettingsRecord,
  mergePendingSettingsRecord,
  parsePendingSettingsPayload,
  pendingSettingsFileName,
  type PendingSettingsKind,
  type PendingSettingsRecord,
} from "../../core/pendingSettingsMerge";
import { McpToolError, SETTINGS_SUBDIRS, chunkFromId, readSettingsRecords } from "./shared";

/**
 * 人物以外（能力・組織・場所・世界観）の更新案を、承認待ちへ置く
 * （設計書6.87.16。0.83.10、残課題の「作ること」7）。
 *
 * 置き場は人物と分けた `.aiwriter/pending-settings/<id>.json` で、
 * 作者が「更新分を反映」を押したときに出口（`applyPendingUpdates.ts` の
 * `reviewPendingSettingsUpdates`）が確かめる。**台帳には一切触れない。**
 *
 * ## 人物の道（`propose.ts`）と違うところ
 *
 * - **白名簿の外の欄は、断らずに `skipped` として返す**（リーダーの指示、
 *   2026-09-24）。黙って落とすのではなく、落とした欄と理由を必ず返すので、
 *   呼んだ側は「どれが入らなかったか」を読める。入れてよい欄が1つも
 *   残らなければ、置かずに断る
 * - **居ないレコードへの提案（新しく作る案）は断る。** 出口がまだ扱わない
 *   （`parsePendingSettingsPayload` が `kind` を読まない）ので、置いても
 *   作者の画面に出ないか、「古い案」として片付けられて消える
 * - **出口と同じ取り込み（`mergePendingSettingsRecord`）を、置く前にも通す。**
 *   取り込んでも何も変わらない案（いまと同じ値）は、出口で黙って片付けられる。
 *   置く前に分かるので、置かずに理由を返す
 *
 * **作者が確定させた記録（`autoGenerated: false`）にも置く**（作者の裁定、
 * 2026-09-24「３ＯＫ」）。人物の道が確定した人物にも置けるのと揃えた。
 * 反映は作者が差分を見て採ったときだけで、取り込みは出どころ
 * （`source: "external"`）を見て白名簿の欄だけを入れ、確定の印は変えない。
 *
 * ## 場所の位置関係（`relations`。2026-10-09の裁定）
 *
 * 場所だけ、関係の一覧を受ける。**製品の抽出と同じ検算**（
 * `validateLocationRelations`）を通ったものだけを置く——引用が本文に一続き・
 * 相手と値が引用の中・自分自身や4種以外は落とす。本文は `chunkId`
 * （`novel.prompt` が返したもの）で引くので、関係を渡すときは `chunkId` が要る。
 * 落とした関係は `skipped` で理由つきに返す（黙って落とさない）。
 * マージは出口（`mergePendingSettingsRecord`）が製品の関数で行う。
 *
 * 退けた関係（`core/rejectedRelations.ts`）は人物の関係だけの話で、
 * 人物以外の記録は関係の欄を持たないので、ここでは扱わない。
 */

/**
 * 種類ごとの白名簿。**ここに無い鍵は `skipped` へ回す。**
 *
 * 表そのものは `core/pendingSettingsMerge.ts` の `EXTERNAL_PROPOSE_FIELDS`
 * が持つ——出口が確定した記録へ入れてよい欄も同じ表で決めるので、2つに
 * 分けると片方だけ直ってずれる。入れないものと、その理由は `SKIP_REASONS`。
 */
export const RECORD_PROPOSE_FIELDS = EXTERNAL_PROPOSE_FIELDS;

const ADD_ONLY_FIELDS = ADD_ONLY_PROPOSE_FIELDS;

/** 白名簿の外の欄を落とした理由。**作者メモ・名前・ID は必ずここに入る** */
const SKIP_REASONS: Record<string, string> = {
  authorNotes: "作者が書く欄です（外からは変えません）",
  exportNote: "作者が書く欄です（外からは変えません）",
  aiNotes: "AIメモは、作者が掘り下げの画面で残すものです",
  name: "名前を変えるのは作者の操作です",
  id: "記録の素性です（外から名乗らせません）",
  autoGenerated: "記録の素性です（作者が確定させた印は作者のものです）",
  schemaVersion: "記録の素性です（外から名乗らせません）",
  updatedAt: "記録の素性です（外から名乗らせません）",
  reading: "読み仮名は作中で変わらないので、違う値は読み違いとして受けません",
  appearedChapters: "本文を数えて決まる値です",
  status: "本文を数えて決まる値です",
  evidence: "抽出が本文から写す値です",
  conflicts: "食い違いの扱いは製品のマージが決めます",
  userIds: "使い手の番号は製品が名前から引き当てます（userNames を使ってください）",
  spoilerLevel: "公開範囲は作者が決めます",
  customFields: "追加項目は、外からは受けません",
};

export interface RecordProposeInput {
  folder: string;
  recordKind: PendingSettingsKind;
  name: string;
  changes: Record<string, unknown>;
  reason: string;
  /** 場所の位置関係の引用を照らす本文（`novel.prompt` の chunkId）。関係を渡すときだけ要る */
  chunkId?: string;
}

export interface RecordProposeResult {
  /** 置いたファイル（作品フォルダーからの相対） */
  file: string;
  /** 人物以外は、いまのところ既存レコードの更新案だけ */
  kind: "update";
  source: "external";
  recordKind: PendingSettingsKind;
  recordId: string;
  name: string;
  /** 実際に書き換えた欄 */
  changedFields: string[];
  /**
   * 白名簿の外で、置かなかった欄と理由。
   * **黙って落とさない**——返さないと、呼んだ側は通ったと思い込む
   */
  skipped: Array<{ field: string; reason: string }>;
  nextStep: string;
  note: string;
}

/** 種類ごとの読み方。`pending.list` も同じ表で台帳を読む（写しを作らない） */
export const PARSERS: Record<PendingSettingsKind, (raw: unknown) => PendingSettingsRecord> = {
  ability: parseAbility,
  organization: parseOrganization,
  location: parseLocation,
  world: parseWorldItem,
};

/** 種類ごとの台帳の置き場（`設定/` の下）。`pending.list` も同じ表を使う */
export const SUBDIRS: Record<PendingSettingsKind, string> = {
  ability: SETTINGS_SUBDIRS.abilities,
  organization: SETTINGS_SUBDIRS.organizations,
  location: SETTINGS_SUBDIRS.locations,
  world: SETTINGS_SUBDIRS.world,
};

export function recordPropose(input: RecordProposeInput): RecordProposeResult {
  const kind = input.recordKind;
  const kindLabel = PENDING_KIND_SHORT_LABELS[kind];
  const name = input.name.trim();
  if (!name) {
    throw new McpToolError(`name が空です。どの${kindLabel}への提案かを書いてください。`);
  }
  const reason = input.reason?.trim() ?? "";
  if (!reason) {
    throw new McpToolError(
      "reason が空です。なぜそう提案するかは、作者が採否を決める唯一の材料なので省略できません。"
    );
  }

  const { picked, skipped } = splitByWhitelist(kind, input.changes);
  if (Object.keys(picked).length === 0) {
    throw new McpToolError(
      `changes に、${kindLabel}で受け付ける欄がありません` +
        (skipped.length > 0
          ? `（置かなかった欄：${skipped.map((item) => `${item.field}＝${item.reason}`).join("、")}）`
          : "") +
        `。受け付けるのは ${RECORD_PROPOSE_FIELDS[kind].join("・")} です。`
    );
  }

  // **無い作品フォルダーには置かない**（人物の道と同じ。`mkdirSync` は道を作ってしまう）
  if (!fs.existsSync(nodePath.resolve(input.folder))) {
    throw new McpToolError(
      `作品フォルダーが見つかりません: ${input.folder}（novel.scan が通る場所を指定してください）`
    );
  }

  const { records, unreadable } = readSettingsRecords(
    input.folder,
    SUBDIRS[kind],
    PARSERS[kind]
  );
  /*
    **名前だけで引き当てる**（人物の道と同じ）。別名でも引き当てると、
    同じ呼び方を持つ別の記録へ提案が入り、作者が承認すると別の資料が
    書き換わる——迷ったら断る側に倒す。
  */
  const current = records.find((record) => record.name === name);
  if (!current) {
    throw new McpToolError(notFoundMessage(input.folder, kind, name, unreadable));
  }

  const proposal = structuredClone(current) as PendingSettingsRecord &
    Record<string, unknown>;
  const changedFields = applyRecordChanges(kind, proposal, picked);
  if (kind === "location") {
    const relationResult = applyLocationRelations(
      input,
      current as Location,
      proposal as Location,
      picked.relations
    );
    skipped.push(...relationResult.skipped);
    if (relationResult.added) changedFields.push("relations");
  }
  if (changedFields.length === 0) {
    throw new McpToolError(
      `${name}（${kindLabel}）の提案は、いまの記録と同じです。置くものがありません。`
    );
  }

  // **製品と同じ検証を通してから書く**（6.87.6 の3）。包みごと読み直して、
  // 出口の読み取り（`PendingSettingsUpdateStore.loadAll`）が読める形かを見る
  const payload = buildPendingSettingsPayload(kind, proposal, {
    source: "external",
    reason,
  });
  let validated: PendingSettingsRecord;
  try {
    validated = parsePendingSettingsPayload(
      JSON.parse(JSON.stringify(payload)) as unknown
    ).record;
  } catch (error) {
    throw new McpToolError(
      `提案の形が、製品の検証を通りませんでした: ${error instanceof Error ? error.message : String(error)}`
    );
  }

  /*
    **出口と同じ取り込みを、置く前にも通す。** 取り込んだあとに差分が
    無い案は、出口が「古い案」として黙って片付ける。作者の画面には
    何も並ばず、呼んだ側は「置けた」と思い込む。
  */
  const merged = mergePendingSettingsRecord(kind, current, validated, {
    source: "external",
  });
  const diff = diffSettingsRecord(kind, current, merged, []);
  if (diff.changes.length === 0) {
    throw new McpToolError(
      `${name}（${kindLabel}）の提案は、取り込んでも記録が変わりません。置くものがありません。`
    );
  }

  const directory = nodePath.join(
    nodePath.resolve(input.folder),
    AIWRITER_DIR,
    PENDING_SETTINGS_DIR
  );
  const target = nodePath.join(directory, pendingSettingsFileName(validated));
  if (fs.existsSync(target)) {
    throw new McpToolError(
      `${name}（${kindLabel}）には、作者がまだ判断していない案があります（${relativeTo(input.folder, target)}）。` +
        "上書きすると作者が見る前の案が消えるので、置きませんでした。作者が「設定資料更新分反映」で採否を決めてから、もう一度提案してください。"
    );
  }

  try {
    fs.mkdirSync(directory, { recursive: true });
    // **新規作成だけ**（`wx`）。同時に2つ来たときも、先の案を上書きしない
    fs.writeFileSync(target, `${JSON.stringify(payload, null, 2)}\n`, {
      encoding: "utf8",
      flag: "wx",
    });
  } catch (error) {
    throw new McpToolError(
      `承認待ちへ置けませんでした: ${error instanceof Error ? error.message : String(error)}`
    );
  }

  return {
    file: relativeTo(input.folder, target),
    kind: "update",
    source: "external",
    recordKind: kind,
    recordId: validated.id,
    name: validated.name,
    changedFields,
    skipped,
    nextStep:
      "VS Code の詳細メニュー「設定資料更新分反映」で採否を決めます。作者が採るまで反映されません。",
    note:
      `台帳（設定/${SUBDIRS[kind]}）は書き換えていません。` +
      (skipped.length > 0
        ? `受け付けない欄 ${skipped.length}件は置いていません（skipped）。`
        : ""),
  };
}

/**
 * 白名簿で振り分ける。外の欄は理由つきで `skipped` へ。
 *
 * `undefined` の欄は「渡さなかった」と同じに扱う（JSON では来ないが、
 * 直に呼ばれたときに空の欄まで落としたと返さないため）。
 */
function splitByWhitelist(
  kind: PendingSettingsKind,
  changes: Record<string, unknown> | undefined
): {
  picked: Record<string, unknown>;
  skipped: Array<{ field: string; reason: string }>;
} {
  if (typeof changes !== "object" || changes === null || Array.isArray(changes)) {
    throw new McpToolError("changes はオブジェクトで渡してください。");
  }
  const allowed = new Set(RECORD_PROPOSE_FIELDS[kind]);
  const picked: Record<string, unknown> = {};
  const skipped: Array<{ field: string; reason: string }> = [];
  for (const [field, value] of Object.entries(changes)) {
    if (value === undefined) continue;
    if (allowed.has(field)) {
      picked[field] = value;
      continue;
    }
    skipped.push({
      field,
      reason:
        SKIP_REASONS[field] ??
        `${PENDING_KIND_SHORT_LABELS[kind]}では受け付けない欄です（受け付けるのは ${RECORD_PROPOSE_FIELDS[kind].join("・")}）`,
    });
  }
  return { picked, skipped };
}

/**
 * 提案を写しへ当てる。返すのは実際に変わった欄の名前。
 *
 * - 文の欄は**空で消させない**（実装ルール2・3。消すのは作者の操作）
 * - 別名・使い手は**足すだけ**
 * - 世界観の分類は決まった7つのどれか。画面の言葉（「世界の法則」）でも受ける
 */
function applyRecordChanges(
  kind: PendingSettingsKind,
  target: PendingSettingsRecord & Record<string, unknown>,
  changes: Record<string, unknown>
): string[] {
  const changed: string[] = [];
  for (const field of RECORD_PROPOSE_FIELDS[kind]) {
    const value = changes[field];
    if (value === undefined) continue;
    // 関係の一覧は文ではない。本文の検算が要るので `applyLocationRelations` が扱う
    if (field === "relations") continue;

    if (ADD_ONLY_FIELDS.has(field)) {
      if (!Array.isArray(value) || value.some((item) => typeof item !== "string")) {
        throw new McpToolError(`${field} は文字列の配列で渡してください。`);
      }
      const current = Array.isArray(target[field])
        ? [...(target[field] as string[])]
        : [];
      const before = current.length;
      for (const item of value as string[]) {
        const trimmed = item.trim();
        if (!trimmed || current.includes(trimmed)) continue;
        // 名前そのものを別名に入れない（出口も落とすが、変えた欄に数えないため）
        if (field === "aliases" && trimmed === target.name) continue;
        current.push(trimmed);
      }
      if (current.length !== before) {
        target[field] = current;
        changed.push(field);
      }
      continue;
    }

    if (typeof value !== "string") {
      throw new McpToolError(`${field} は文字列で渡してください。`);
    }
    const trimmed = value.trim();
    if (!trimmed) {
      throw new McpToolError(
        `${field} が空です。値を消す提案は受け付けません（消すのは作者の操作です）。`
      );
    }
    const next =
      kind === "world" && field === "category" ? worldCategoryOf(trimmed) : trimmed;
    if (target[field] === next) continue;
    target[field] = next;
    changed.push(field);
  }
  return changed;
}

/**
 * 場所の位置関係の提案を、製品の抽出と同じ検算に通して写しへ当てる。
 *
 * - 本文は `chunkId` で引く。無ければ断る（引用を照らせない関係は置かない）
 * - 検算を通らない関係は落とし、場所そのものの提案は残す（抽出と同じ）
 * - 写しに入れるのは**今回足す関係だけ**。いまの関係まで写すと、承認までの間に
 *   作者が消した関係を、古い写しが復活させる
 * - 同じ（種類, 相手, 値）が既にあるものは足さない
 */
function applyLocationRelations(
  input: RecordProposeInput,
  current: Location,
  proposal: Location,
  raw: unknown
): { added: boolean; skipped: Array<{ field: string; reason: string }> } {
  if (raw === undefined) return { added: false, skipped: [] };
  if (!Array.isArray(raw)) {
    throw new McpToolError(
      "relations は { target, kind, value, evidence } の配列で渡してください。"
    );
  }
  const chunkId = input.chunkId?.trim();
  if (!chunkId) {
    throw new McpToolError(
      "relations には chunkId が要ります（novel.prompt が返したもの）。" +
        "引用が本文にあるかを、こちらで照らし直すためです。"
    );
  }
  const chunk = chunkFromId(input.folder, chunkId);
  const extracted = normalizeExtractedLocation({
    name: current.name,
    aliases: current.aliases,
    relations: raw,
  });
  const { kept, dropped } = validateLocationRelations(extracted, chunk);
  const skipped = dropped.map((item) => ({
    field: item.name ?? "relations",
    reason:
      "本文の引用で確かめられませんでした（種類は within・adjacent・direction・distance、" +
      "引用は本文に一続きで、相手と方角・距離の値を含むこと）",
  }));
  // 形が合わず `normalizeExtractedLocation` が読み捨てた件も、黙らせない
  const unreadable = raw.length - extracted.relations!.length;
  if (unreadable > 0) {
    skipped.push({
      field: "relations",
      reason: `target と kind が文字列でない関係を ${unreadable} 件読み捨てました`,
    });
  }

  const known = new Set(
    (current.relations ?? []).map((relation) => relationKey(relation))
  );
  const fresh: LocationRelation[] = kept
    .map((relation) => ({
      kind: relation.kind as LocationRelationKind,
      target: relation.target,
      targetId: null,
      value: relation.value ?? null,
      chapters: relation.chapters ?? [],
      evidence: relation.evidence ?? null,
      authorLocked: false,
    }))
    .filter((relation) => !known.has(relationKey(relation)));
  if (fresh.length > 0) {
    proposal.relations = fresh;
  } else {
    delete proposal.relations;
  }
  return { added: fresh.length > 0, skipped };
}

function relationKey(relation: {
  kind: string;
  target: string;
  value?: string | null;
}): string {
  return [
    relation.kind,
    normalizeLocationName(relation.target),
    normalizeLocationName(relation.value ?? ""),
  ].join("\u0000");
}

/** 世界観の分類を、決まった7つのどれかへ。**似た言葉へ丸めない** */
function worldCategoryOf(value: string): WorldCategory {
  if ((WORLD_CATEGORIES as readonly string[]).includes(value)) {
    return value as WorldCategory;
  }
  const byLabel = WORLD_CATEGORIES.find(
    (category) => WORLD_CATEGORY_LABELS[category] === value
  );
  if (byLabel) return byLabel;
  throw new McpToolError(
    `category（世界観の分類）は次のどれかです: ` +
      WORLD_CATEGORIES.map(
        (category) => `${category}（${WORLD_CATEGORY_LABELS[category]}）`
      ).join("、")
  );
}

/**
 * 居ないレコードへの提案を断る文。
 *
 * **ほかの種類に同じ名前があれば、それも言う。** 「港町」を場所として
 * 探して見つからないが組織にある、という取り違えは起きやすく、
 * 名前だけ返されても呼んだ側は直しようがない。
 */
function notFoundMessage(
  folder: string,
  kind: PendingSettingsKind,
  name: string,
  unreadable: number
): string {
  const kindLabel = PENDING_KIND_SHORT_LABELS[kind];
  const elsewhere: string[] = [];
  for (const other of Object.keys(PARSERS) as PendingSettingsKind[]) {
    if (other === kind) continue;
    const { records } = readSettingsRecords(folder, SUBDIRS[other], PARSERS[other]);
    if (records.some((record) => record.name === name)) {
      elsewhere.push(`${PENDING_KIND_SHORT_LABELS[other]}（recordKind: "${other}"）`);
    }
  }
  const characters = readSettingsRecords(
    folder,
    SETTINGS_SUBDIRS.characters,
    parseCharacter
  ).records;
  if (characters.some((record) => record.name === name)) {
    elsewhere.push('人物（recordKind: "character"）');
  }

  return (
    `「${name}」という${kindLabel}は、台帳にありません（名前で引き当てています。別名では引き当てません）。` +
    `${kindLabel}を新しく作る案は、まだ置けません——作者が確かめる画面が新しい${kindLabel}を扱えないためです。` +
    "新しく作るときは作者に頼んでください。" +
    (elsewhere.length > 0 ? `同じ名前が ${elsewhere.join("・")} にあります。` : "") +
    (unreadable > 0
      ? `（${kindLabel}の台帳に読めないファイルが ${unreadable} 件あります。その中に居るのかもしれません）`
      : "")
  );
}

/** 作品フォルダーからの相対。区切りは読みやすいほうへ揃える */
function relativeTo(folder: string, target: string): string {
  return nodePath
    .relative(nodePath.resolve(folder), target)
    .split(nodePath.sep)
    .join("/");
}
