import * as fs from "node:fs";
import * as nodePath from "node:path";
import { z } from "zod";
import { AIWRITER_DIR } from "../../models/types";
import { emptyCharacter, parseCharacter, type Character } from "../../models/character";
import {
  PENDING_CREATION_ID,
  PENDING_DIR,
  buildPendingPayload,
  pendingFileName,
} from "../../core/pendingUpdateFormat";
import { withoutRejectedRelations } from "../../core/rejectedRelations";
import {
  FOLDER_INPUT,
  McpToolError,
  SETTINGS_SUBDIRS,
  readSettingsRecords,
} from "./shared";

/**
 * 設定資料の更新案を、承認待ちへ置く（設計書6.87.16）。
 *
 * **台帳（`設定/characters/*.json`）には一切触れない。** 置くのは
 * `.aiwriter/pending-characters/` だけで、作者が製品の「更新分を反映」
 * （`features/applyPendingUpdates.ts`）を押したときに、製品のマージが走る。
 *
 * ---
 *
 * **ここは 6.87.7「原稿を書き換える操作を外へ出さない」の例外ではない。**
 * 承認待ちへ置くのは書き換えではなく、編集部が本文を書き換えずに提案として
 * 置く（5.6）のと同じ扱いである。作者が押すまで、台帳は1バイトも変わらない。
 *
 * ---
 *
 * **受け付ける欄は白名簿で決める。** 作者が読んで採否を判断できる文字の欄
 * だけを通し、それ以外の鍵が来たら**鍵の名前を挙げて断る**——黙って落とすと、
 * 呼んだ側は「反映された」と思い込む。
 *
 * 通さないものと、その理由。
 *
 * - `authorNotes`・`exportNote`：作者が書いたもの（実装ルール2）
 * - `id`・`autoGenerated`・`authorLocked`：レコードの素性。外から名乗らせない
 * - `addressTerms`（呼称）：作者が固定した呼び方を持つ構造。差し替えは規則2に触れる
 * - `changes`・`conflicts`：話数の食い違いの扱いは製品のマージが決める（6.18）
 * - `appearedChapters`：本文を数えて決まる値。提案するものではない
 * - `reading`（読み仮名）：作中で変わらない項目なので、違う値は読み違いである
 *   （実装ルール2「読み仮名は畳まない」）。外からの提案も同じ理由で受けない
 */

/**
 * 受け付ける欄と、その説明。
 *
 * `appearance`（外見）を足してあるのは、`CHARACTER_TEXT_FIELDS` の中で
 * `summary`・`role`・`personality` と同じ「作者が読んで判断できる文章」だから。
 *
 * `relations`（関係）は 0.83.2 で足した（作者の依頼「B3」）。抽出の誤り
 * （「ターナ=父の娘」）を外部AIが見つけても置く口が無かった。**相手ごとの
 * 差し替え**で、承認の画面には消える関係と入る関係が1つずつ並ぶ（`applyRelations`）。
 * 呼称（`addressTerms`）と違って作者が固定する印（`authorLocked`）を持たない
 * 構造なので、規則2には触れない。
 */
const CHANGES_SCHEMA = z.looseObject({
  summary: z
    .string()
    .optional()
    .describe("一覧に出す短い紹介。長いものは製品側で切り詰められます"),
  aliases: z
    .array(z.string())
    .optional()
    .describe(
      "別名。足すだけで、既存の別名は消えません（重複は畳みます）。消したいときは作者に頼んでください"
    ),
  gender: z.string().optional().describe("性別。作品の言い方のままで構いません"),
  affiliation: z.string().optional().describe("所属（組織名・部署名）"),
  role: z.string().optional().describe("作中での役どころ"),
  personality: z.string().optional().describe("性格"),
  appearance: z.string().optional().describe("外見"),
  relations: z
    .array(z.object({ name: z.string(), relation: z.string() }))
    .optional()
    .describe(
      "関係（{name: 相手, relation: この人物から見た相手の続柄・立場}）。" +
        "書いた相手の関係は、いまの記録を置き換えます（ほかの相手の関係は残ります）。関係を消すだけの提案は受け付けません。" +
        "作者が退けた関係（人物の rejectedRelations）は足しません"
    ),
});

/** 白名簿。**ここに無い鍵は断る**（黙って落とさない） */
const ALLOWED_FIELDS = [
  "summary",
  "aliases",
  "gender",
  "affiliation",
  "role",
  "personality",
  "appearance",
  "relations",
] as const;

type AllowedField = (typeof ALLOWED_FIELDS)[number];

export const SETTINGS_PROPOSE_INPUT = {
  ...FOLDER_INPUT,
  name: z
    .string()
    .describe(
      "人物の名前。台帳にその名前の人物が居れば更新案、居なければ新規案になります（別名では引き当てません）"
    ),
  changes: CHANGES_SCHEMA.describe(
    // 受け付ける欄は下に並んでいるので、ここでは繰り返さない（一覧を小さく保つ）
    "変えたい欄だけを入れます。ここに無い鍵は断ります"
  ),
  reason: z
    .string()
    .describe(
      "なぜそう提案するか。作者が採否を決める材料なので、省略も空も断ります"
    ),
};

export interface SettingsProposeInput {
  folder: string;
  name: string;
  changes: Record<string, unknown>;
  reason: string;
}

export interface SettingsProposeResult {
  /** 置いたファイル（作品フォルダーからの相対） */
  file: string;
  /** 新規案か、既存レコードの更新案か */
  kind: "creation" | "update";
  source: "external";
  /** 対象のID。新規案は仮の番号（承認のときに採り直される） */
  characterId: string;
  name: string;
  /** 実際に書き換えた欄 */
  changedFields: string[];
  /**
   * 作者が退けた関係に一致したため、足さなかった関係（2026-09-23）。
   * **黙って落とさない**——返さないと、呼んだ側は通ったと思い込む
   */
  skippedRejectedRelations: Array<{ name: string; relation: string }>;
  /** 作者が次にすること */
  nextStep: string;
  note: string;
}

export function settingsPropose(
  input: SettingsProposeInput
): SettingsProposeResult {
  const name = input.name.trim();
  if (!name) {
    throw new McpToolError("name が空です。どの人物への提案かを書いてください。");
  }

  const reason = input.reason?.trim() ?? "";
  if (!reason) {
    throw new McpToolError(
      "reason が空です。なぜそう提案するかは、作者が採否を決める唯一の材料なので省略できません。"
    );
  }

  const changes = assertAllowedFields(input.changes);
  if (Object.keys(changes).length === 0) {
    throw new McpToolError(
      `changes が空です。変えたい欄（${ALLOWED_FIELDS.join("・")}）を1つ以上入れてください。`
    );
  }

  /*
    **無い作品フォルダーには置かない。** `mkdirSync` は道を作ってしまうので、
    綴りを間違えたまま置くと、作者がどこを見ても見つからない提案ができる
    （そして呼んだ側は成功したと思っている）。
  */
  if (!fs.existsSync(nodePath.resolve(input.folder))) {
    throw new McpToolError(
      `作品フォルダーが見つかりません: ${input.folder}（work.scan が通る場所を指定してください）`
    );
  }

  const { records } = readSettingsRecords(
    input.folder,
    SETTINGS_SUBDIRS.characters,
    parseCharacter
  );
  /*
    **名前だけで引き当てる。** 別名でも引き当てると、同じ呼び方を持つ
    別人へ提案が入る。取り違えたまま作者が承認すると、別人の資料が
    書き換わる——「迷ったら断る」の側に倒す。
  */
  const existing = records.find((record) => record.name === name);

  const base: Character = existing
    ? { ...existing }
    : emptyCharacter(PENDING_CREATION_ID, name);
  const kind = existing ? undefined : ("creation" as const);

  const skippedRejectedRelations: Array<{ name: string; relation: string }> = [];
  const changedFields = applyChanges(base, changes, records, skippedRejectedRelations);

  /*
    **提案が退けた関係だけだったら、置かずに断る。** 置いても承認の画面には
    何も並ばず（差分が無いので片付けられる）、呼んだ側は「置けた」と思い込む。
    作者が消した関係であることを、そのまま伝える。
  */
  if (changedFields.length === 0 && skippedRejectedRelations.length > 0) {
    throw new McpToolError(
      `${skippedRejectedRelations
        .map((item) => `「${item.name}=${item.relation}」`)
        .join("、")}は、作者が退けた関係です（消した・言葉を直した記録が残っています）。` +
        "足さないので、承認待ちへは置きませんでした。どうしても必要なら作者に頼んでください（作者が関係欄に入れ直すと記録から外れます）。"
    );
  }

  // **製品と同じ検証を通してから書く**（6.87.6 の3）。ここを迂回すると、
  // 作者の承認画面で初めて壊れたJSONが見つかることになる
  const validated = parseCharacter(base as unknown);

  const directory = nodePath.join(
    nodePath.resolve(input.folder),
    AIWRITER_DIR,
    PENDING_DIR
  );
  const target = nodePath.join(directory, pendingFileName(validated, kind));

  if (fs.existsSync(target)) {
    throw new McpToolError(
      `${name} には、作者がまだ判断していない案があります（${relativeTo(input.folder, target)}）。` +
        "上書きすると作者が見る前の案が消えるので、置きませんでした。作者が「設定資料更新分反映」で採否を決めてから、もう一度提案してください。"
    );
  }

  const payload = buildPendingPayload(validated, {
    kind,
    source: "external",
    reason,
  });

  try {
    fs.mkdirSync(directory, { recursive: true });
    // **新規作成だけ**（`wx`）。既にあるものは上の検査で断っているが、
    // 同時に2つ来たときのために、書くほうでも上書きを封じておく
    fs.writeFileSync(target, `${JSON.stringify(payload, null, 2)}\n`, {
      encoding: "utf8",
      flag: "wx",
    });
  } catch (error) {
    throw new McpToolError(
      `承認待ちへ置けませんでした: ${error instanceof Error ? error.message : String(error)}`
    );
  }

  return {
    file: relativeTo(input.folder, target),
    kind: kind ? "creation" : "update",
    source: "external",
    characterId: validated.id,
    name: validated.name,
    changedFields,
    skippedRejectedRelations,
    nextStep:
      "VS Code の詳細メニュー「設定資料更新分反映」で採否を決めます。作者が採るまで反映されません。",
    note:
      "台帳（設定/characters）は書き換えていません。" +
      (skippedRejectedRelations.length > 0
        ? `作者が退けた関係 ${skippedRejectedRelations.length}件は足していません（skippedRejectedRelations）。`
        : ""),
  };
}

/**
 * 白名簿に無い鍵を、名前を挙げて断る。
 *
 * **黙って落とさない。** 落とすと、呼んだ側は通ったと思い込み、
 * 作者には「提案したはずの欄が入っていない」としか見えない。
 */
function assertAllowedFields(
  changes: Record<string, unknown> | undefined
): Partial<Record<AllowedField, unknown>> {
  if (
    typeof changes !== "object" ||
    changes === null ||
    Array.isArray(changes)
  ) {
    throw new McpToolError("changes はオブジェクトで渡してください。");
  }
  const allowed = new Set<string>(ALLOWED_FIELDS);
  const rejected = Object.keys(changes).filter((key) => !allowed.has(key));
  if (rejected.length > 0) {
    throw new McpToolError(
      `受け付けない欄が含まれています: ${rejected.join("、")}。` +
        `受け付けるのは ${ALLOWED_FIELDS.join("・")} だけです。` +
        "作者メモ・呼称・話数・レコードの素性は、外からは変えられません。"
    );
  }
  const picked: Partial<Record<AllowedField, unknown>> = {};
  for (const key of ALLOWED_FIELDS) {
    if (changes[key] !== undefined) picked[key] = changes[key];
  }
  return picked;
}

/**
 * 更新案の中身を差し替える。返すのは実際に変えた欄の名前。
 *
 * `aliases` だけ**足すだけ**にしてある。差し替えを許すと、作者が手で足した
 * 呼び方が外からの提案1回で消える。
 */
function applyChanges(
  target: Character,
  changes: Partial<Record<AllowedField, unknown>>,
  /** 台帳の顔ぶれ。退けた関係の相手を、相関図と同じ規則で引き当てるのに使う */
  characters: readonly Character[],
  /** 退けた関係に一致して足さなかったものを積む先 */
  skippedRejected: Array<{ name: string; relation: string }>
): string[] {
  const changed: string[] = [];

  for (const field of ALLOWED_FIELDS) {
    const value = changes[field];
    if (value === undefined) continue;

    if (field === "relations") {
      if (applyRelations(target, value, characters, skippedRejected)) {
        changed.push("relations");
      }
      continue;
    }

    if (field === "aliases") {
      if (!Array.isArray(value) || value.some((item) => typeof item !== "string")) {
        throw new McpToolError("aliases は文字列の配列で渡してください。");
      }
      const merged = [...target.aliases];
      for (const alias of value as string[]) {
        const trimmed = alias.trim();
        if (!trimmed) continue;
        if (merged.includes(trimmed)) continue;
        merged.push(trimmed);
      }
      if (merged.length !== target.aliases.length) {
        target.aliases = merged;
        changed.push("aliases");
      }
      continue;
    }

    if (typeof value !== "string") {
      throw new McpToolError(`${field} は文字列で渡してください。`);
    }
    const trimmed = value.trim();
    if (!trimmed) {
      // **空で消させない**（実装ルール2・3）。「空文字」を提案として
      // 受けると、作者が書いた値が黙って消える
      throw new McpToolError(
        `${field} が空です。値を消す提案は受け付けません（消すのは作者の操作です）。`
      );
    }
    if (target[field] === trimmed) continue;
    target[field] = trimmed;
    changed.push(field);
  }

  return changed;
}

/**
 * 関係の提案を、**相手ごとの差し替え**として当てる（作者の依頼「B3」、2026-09-22 未明）。
 * 返すのは中身が変わったか。
 *
 * - **書いた相手の関係は、いまの記録を置き換える。** 足すだけにすると、
 *   抽出が入れた誤り（「ターナ=父の娘」）が消せず、直す提案にならない
 * - **書いていない相手の関係は残す。** 外からの提案1回で、作者が足した関係を
 *   まとめて消させない（`aliases` を足すだけにしたのと同じ考え）
 * - 差し替えた関係は**元の位置**に入れる（並びが崩れると、承認の差分が読みにくい）。
 *   まだ無い相手は末尾へ
 * - 相手の引き当ては**名前の完全一致だけ**（前後の空白は落とす）。敬称や別名の
 *   揺れまで寄せると、別人の関係を消しうる——迷ったら消さない。揺れた名前で
 *   来れば、元の関係は残り、承認の差分に両方が並ぶ
 * - **空の相手・空の関係は断る。** 関係を消すのは作者の操作である
 *
 * - **作者が退けた関係は足さない**（作者の裁定、2026-09-23）。一致の判定は
 *   抽出のマージと同じ（`rejectedRelations.ts`）。足さなかったものは
 *   `skippedRejected` に積んで呼んだ側へ返す。退けた関係では差し替えもしない
 *   （「ターナ=父の娘」だけが来て、いまの「ターナ=母」が消えることは無い）
 *
 * 承認の画面は製品の差分（`characterDiff` の葉）なので、消える関係と入る関係が
 * 1つずつ並び、入る側は ✕ で落とせる。マージはここと製品のコードが行い、AIには
 * させない（規則3）。
 */
function applyRelations(
  target: Character,
  value: unknown,
  characters: readonly Character[],
  skippedRejected: Array<{ name: string; relation: string }>
): boolean {
  if (!Array.isArray(value) || value.length === 0) {
    throw new McpToolError(
      "relations は {name, relation} の配列で、1件以上渡してください。"
    );
  }
  const proposed: Array<{ name: string; relation: string }> = [];
  for (const entry of value as unknown[]) {
    const record =
      typeof entry === "object" && entry !== null
        ? (entry as Record<string, unknown>)
        : {};
    const name = typeof record.name === "string" ? record.name.trim() : "";
    const relation =
      typeof record.relation === "string" ? record.relation.trim() : "";
    if (!name || !relation) {
      throw new McpToolError(
        "relations の各件には、空でない name（相手）と relation（関係）が要ります。" +
          "関係を消す提案は受け付けません（消すのは作者の操作です）。"
      );
    }
    if (proposed.some((item) => item.name === name && item.relation === relation)) {
      continue;
    }
    proposed.push({ name, relation });
  }

  const { kept: accepted, skipped } = withoutRejectedRelations(
    proposed,
    target.rejectedRelations,
    characters
  );
  skippedRejected.push(...skipped);

  const targets = new Set(accepted.map((item) => item.name));
  const next: Array<{ name: string; relation: string }> = [];
  const placed = new Set<string>();
  for (const current of target.relations) {
    const name = current.name.trim();
    if (!targets.has(name)) {
      next.push(current);
      continue;
    }
    // その相手の最初の位置に、提案の関係をまとめて入れる
    if (placed.has(name)) continue;
    placed.add(name);
    next.push(...accepted.filter((item) => item.name === name));
  }
  for (const item of accepted) {
    if (!placed.has(item.name)) next.push(item);
  }

  const same =
    next.length === target.relations.length &&
    next.every(
      (item, index) =>
        item.name === target.relations[index].name &&
        item.relation === target.relations[index].relation
    );
  if (same) return false;
  target.relations = next;
  return true;
}

/** 作品フォルダーからの相対。区切りは読みやすいほうへ揃える */
function relativeTo(folder: string, target: string): string {
  return nodePath
    .relative(nodePath.resolve(folder), target)
    .split(nodePath.sep)
    .join("/");
}
