import {
  BASE_SYSTEM_PROMPT,
  CHARACTER_EXTRACT_SCHEMA,
  CHARACTER_EXTRACT_VERSION,
  buildCharacterExtractPrompt,
  type CharacterExtractResult,
} from "../../prompts/characterExtract";
import {
  parseResult,
  validateCharacterExtractResult,
} from "../../core/characterExtractionValidation";
import { buildKnownCharacterNamesForPrompt } from "../../core/knownCharacterNames";
import { SettingsExtractionCollector } from "../../core/settingsExtractionCollect";
import type { Chunk } from "../../core/chunker";
import { parseCharacter } from "../../models/character";
import { parseAbility } from "../../models/ability";
import { parseLocation } from "../../models/location";
import { parseOrganization } from "../../models/organization";
import { parseWorldItem } from "../../models/world";
import {
  McpToolError,
  SETTINGS_SUBDIRS,
  chapterLabelOf,
  chunkFromId,
  chunkIdOf,
  chunksOfWorkFile,
  readSettingsRecords,
  selectChunks,
} from "./shared";
import { ollamaGenerate } from "./ollama";
import { askSampling } from "./sampling";
import {
  assertRunner,
  claudeNote,
  runChunks,
  runChunksBySampling,
  type RunnerKind,
  validateWith,
} from "./run";
import type { RunOutcome } from "./run";

/**
 * 設定資料の抽出（P-04a）を外から呼ぶ（設計書6.87.8 の4）。
 *
 * **並びは製品のまま**（6.87.6 の3）。既にいる人物・能力・場所・組織・
 * 世界観の名前を集めて `buildCharacterExtractPrompt` へ渡し、応答は
 * `parseResult` → `validateCharacterExtractResult` と、能力・場所・組織・
 * 世界観の4つの検算（`SettingsExtractionCollector.collect`）へ通す。
 *
 * **集約は製品のクラスをそのまま使う。** `collect` の中では総称を先に
 * 読み、人物側の所属も拾う——**その順そのものが意味を持っている**ので、
 * 外で検算を呼び直すと順が写しになる。
 *
 * ---
 *
 * **書き戻さない**（6.87.7）。製品はこのあと
 *
 *   抽出 → **コードでマージ** → 承認待ちへ積む → 作者が承認して保存
 *
 * と進むが、MCPが返すのは**マージの手前まで**である。マージは
 * `characterMerge` / `settingsMerge` の仕事で、既存レコードを
 * 書き換える判断が入る。**「読む・測る・提案する」の線はここに引く。**
 *
 * ---
 *
 * **製品と1つだけ違うところ**（正直に書く）。
 *
 * 製品はチャンクを順に回し、**前のチャンクで見つけた名前を次のチャンクの
 * 「既知」へ足していく**。`settings.run` は同じように育てるが、
 * **`settings.prompt` を1チャンクずつ呼ぶ形では育たない**——
 * そのときの「既知」は `設定/` に保存済みのものだけである。
 * 作品全体の出来ばえを測るなら `run` を使う。
 */

const VALIDATE_WITH = validateWith("settings");

/** 既知名の上限。**製品と同じところで切る**（`features/extractCharacters.ts`） */
const KNOWN_LIMIT = 50;
/** 世界観の見出しだけ多く渡す（同じ事柄が別の見出しで増えるのを防ぐため） */
const KNOWN_WORLD_LIMIT = 150;

/** `設定/` に保存済みのもの。プロンプトにも検算にも要る */
interface StoredSettings {
  characters: Array<{ name: string; aliases: string[] }>;
  /** 作者が手で書いた人物の名前。**この人の別名はコードでも触らない** */
  authorEditedNames: string[];
  abilityNames: string[];
  locationNames: string[];
  organizationNames: string[];
  worldNames: string[];
  abilityTerm: string | null;
}

function readStored(folder: string): StoredSettings {
  const people = readSettingsRecords(
    folder,
    SETTINGS_SUBDIRS.characters,
    parseCharacter
  ).records;
  const abilities = readSettingsRecords(
    folder,
    SETTINGS_SUBDIRS.abilities,
    parseAbility
  ).records;
  const locations = readSettingsRecords(
    folder,
    SETTINGS_SUBDIRS.locations,
    parseLocation
  ).records;
  const organizations = readSettingsRecords(
    folder,
    SETTINGS_SUBDIRS.organizations,
    parseOrganization
  ).records;
  const world = readSettingsRecords(
    folder,
    SETTINGS_SUBDIRS.world,
    parseWorldItem
  ).records;

  const names = (
    records: Array<{ name: string; aliases: string[] }>
  ): string[] =>
    [
      ...new Set(
        records
          .flatMap((record) => [record.name, ...record.aliases])
          .map((name) => name.trim())
          .filter(Boolean)
      ),
    ];

  return {
    characters: people.map((person) => ({
      name: person.name,
      aliases: person.aliases,
    })),
    // **作者が手で書いたものは、AIの読みで押し流さない**（CLAUDE.md 規則2）
    authorEditedNames: people
      .filter((person) => person.autoGenerated === false)
      .map((person) => person.name),
    abilityNames: names(abilities).slice(0, KNOWN_LIMIT),
    locationNames: names(locations).slice(0, KNOWN_LIMIT),
    organizationNames: names(organizations).slice(0, KNOWN_LIMIT),
    worldNames: world
      .map((item) => item.name.trim())
      .filter(Boolean)
      .slice(0, KNOWN_WORLD_LIMIT),
    // 作者が確定させた総称があれば、それを使う（揺らさない）
    abilityTerm: null,
  };
}

export interface SettingsChunkPrompt {
  chunkId: string;
  index: number;
  chapterLabel: string;
  chars: number;
  userPrompt: string;
  /** このチャンクへ渡した既知名の件数（切ったかを、呼ぶ側が読めるように） */
  knownCounts: {
    characters: number;
    abilities: number;
    locations: number;
    organizations: number;
    world: number;
  };
}

export interface SettingsPromptResult {
  promptVersion: string;
  systemPrompt: string;
  schema: unknown;
  validateWith: string;
  /**
   * **チャンクをまたいで既知名が育たない**ことの断り。
   * 作品全体の出来ばえを測るなら `settings.run` を使う
   */
  note: string;
  chunks: SettingsChunkPrompt[];
}

export interface SettingsPromptInput {
  folder: string;
  filePath: string;
  numCtx: number;
  chunkIndex?: number;
}

const ACROSS_CHUNKS_NOTE =
  "prompt は1回ごとに独立しています。製品は前のチャンクで見つけた名前を" +
  "次の「既知」へ足していくので、作品全体の出来ばえを測るなら" +
  "novel.run（feature: settings）を使ってください。";

function promptForChunk(
  relative: string,
  chunk: Chunk,
  maxChars: number,
  stored: StoredSettings,
  extractedSoFar: Array<{ data: { name: string; aliases?: string[] } }>,
  extraKnown: {
    abilities: string[];
    locations: string[];
    organizations: string[];
    world: string[];
  }
): SettingsChunkPrompt {
  // **既知の人物は「人数」で切る**（名前の件数で切ると、別名の多い作品で
  // 後ろの人物が丸ごと落ちる。`buildKnownCharacterNamesForPrompt`）
  const knownCharacters = buildKnownCharacterNamesForPrompt(
    stored.characters,
    extractedSoFar as Parameters<typeof buildKnownCharacterNamesForPrompt>[1]
  );
  const abilities = [
    ...new Set([...stored.abilityNames, ...extraKnown.abilities]),
  ].slice(0, KNOWN_LIMIT);
  const locations = [
    ...new Set([...stored.locationNames, ...extraKnown.locations]),
  ].slice(0, KNOWN_LIMIT);
  const organizations = [
    ...new Set([...stored.organizationNames, ...extraKnown.organizations]),
  ].slice(0, KNOWN_LIMIT);
  const world = [
    ...new Set([...stored.worldNames, ...extraKnown.world]),
  ].slice(0, KNOWN_WORLD_LIMIT);

  return {
    chunkId: chunkIdOf(relative, chunk, maxChars),
    index: chunk.index,
    chapterLabel: chapterLabelOf(chunk),
    chars: chunk.text.length,
    knownCounts: {
      characters: knownCharacters.length,
      abilities: abilities.length,
      locations: locations.length,
      organizations: organizations.length,
      world: world.length,
    },
    userPrompt: buildCharacterExtractPrompt({
      chunkText: chunk.text,
      chapterLabel: chapterLabelOf(chunk),
      knownCharacterNames: knownCharacters,
      knownAbilityNames: abilities,
      knownLocationNames: locations,
      knownOrganizationNames: organizations,
      knownWorldNames: world,
      abilityTerm: stored.abilityTerm ?? undefined,
    }),
  };
}

const NO_EXTRA = {
  abilities: [],
  locations: [],
  organizations: [],
  world: [],
};

export function settingsPrompt(
  input: SettingsPromptInput
): SettingsPromptResult {
  const stored = readStored(input.folder);
  const { chunks, maxChars } = chunksOfWorkFile(
    input.folder,
    input.filePath,
    input.numCtx
  );

  return {
    promptVersion: CHARACTER_EXTRACT_VERSION,
    systemPrompt: BASE_SYSTEM_PROMPT,
    schema: CHARACTER_EXTRACT_SCHEMA,
    validateWith: VALIDATE_WITH,
    note: ACROSS_CHUNKS_NOTE,
    chunks: selectChunks(chunks, input.chunkIndex).map((chunk) =>
      promptForChunk(input.filePath, chunk, maxChars, stored, [], NO_EXTRA)
    ),
  };
}

export interface SettingsValidateResult {
  chunkId: string;
  chapterLabel: string;
  /** 人物。`accepted` が取り出せたもの、`rejected` が検算で落ちたもの */
  characters: {
    accepted: unknown[];
    rejected: unknown[];
    droppedSharedBodyAliases: unknown[];
    droppedTruncatedAliases: unknown[];
    droppedSharedFamilyNameAliases: unknown[];
    droppedRelativeAliases: unknown[];
    correctedRelations: unknown[];
  };
  /** 能力・場所・組織・世界観。**製品の集約が数えたそのまま** */
  settings: {
    abilities: unknown[];
    locations: unknown[];
    organizations: unknown[];
    worldItems: unknown[];
    affiliations: string[];
    rejected: unknown[];
    abilityTerm: string | null;
  };
  /**
   * **ここから先は返さない。** マージ（既存レコードとの突き合わせ）と
   * 保存は製品の側の仕事で、MCPは読む・測る・提案するまでである。
   */
  note: string;
}

const NOT_MERGED_NOTE =
  "マージ（既存の資料との突き合わせ）と保存は行っていません。" +
  "これは取り出して検算したところまでの結果です。";

function validateAgainst(
  chunkId: string,
  chunk: Chunk,
  parsed: CharacterExtractResult,
  stored: StoredSettings,
  accumulator: SettingsExtractionCollector
): SettingsValidateResult {
  const people = validateCharacterExtractResult(parsed, chunk, {
    knownNames: stored.characters.flatMap((person) => [
      person.name,
      ...person.aliases,
    ]),
    authorEditedNames: stored.authorEditedNames,
  });

  // **製品の集約をそのまま通す。** 総称を先に読む・人物側の所属を拾う、
  // といった順そのものが意味を持っているので、外で検算を呼び直さない
  accumulator.collect(parsed, chunk);
  const gathered = accumulator.candidates();

  return {
    chunkId,
    chapterLabel: chapterLabelOf(chunk),
    characters: {
      accepted: people.accepted,
      rejected: people.rejected,
      droppedSharedBodyAliases: people.droppedSharedBodyAliases,
      droppedTruncatedAliases: people.droppedTruncatedAliases,
      droppedSharedFamilyNameAliases: people.droppedSharedFamilyNameAliases,
      droppedRelativeAliases: people.droppedRelativeAliases,
      correctedRelations: people.correctedRelations,
    },
    settings: {
      abilities: [...gathered.abilities],
      locations: [...gathered.locations],
      organizations: [...gathered.organizations],
      worldItems: [...gathered.worldItems],
      affiliations: gathered.affiliations,
      rejected: [...gathered.rejected],
      abilityTerm: gathered.abilityTerm,
    },
    note: NOT_MERGED_NOTE,
  };
}

export function settingsValidate(input: {
  folder: string;
  chunkId: string;
  response: string;
}): SettingsValidateResult {
  const parsed = parseResult(input.response);
  if (!parsed) {
    throw new McpToolError(
      "応答を読み取れませんでした（設定資料の抽出のスキーマに沿っていません。JSONの形か、項目が合っていません）。"
    );
  }
  return validateAgainst(
    input.chunkId,
    chunkFromId(input.folder, input.chunkId),
    parsed,
    readStored(input.folder),
    new SettingsExtractionCollector()
  );
}

export interface SettingsRunInput extends SettingsPromptInput {
  runner: RunnerKind;
  endpoint?: string;
  model?: string;
  allowRemote?: boolean;
}

export async function settingsRun(
  input: SettingsRunInput
): Promise<RunOutcome<SettingsChunkPrompt, SettingsValidateResult>> {
  // **省略を既定で埋めない**（設計書6.87.8 の5）
  assertRunner(input.runner);
  const prompts = settingsPrompt(input);
  if (input.runner === "claude") {
    return {
      runner: "claude",
      note: `${claudeNote(VALIDATE_WITH)} ${ACROSS_CHUNKS_NOTE}`,
      systemPrompt: prompts.systemPrompt,
      schema: prompts.schema,
      validateWith: VALIDATE_WITH,
      chunks: prompts.chunks,
    };
  }

  const model = input.model;
  if (input.runner === "ollama" && !model) {
    throw new McpToolError("runner が ollama のときは model が要ります。");
  }

  const stored = readStored(input.folder);
  const { chunks, maxChars } = chunksOfWorkFile(
    input.folder,
    input.filePath,
    input.numCtx
  );
  const selected = selectChunks(chunks, input.chunkIndex);

  /*
    **前のチャンクで見つけた名前を、次の「既知」へ足していく**（製品と同じ）。
    足さないと、同じ人物が話ごとに別人として返り、**AIは同じ相手の
    複数の呼び方を1つにまとめたがる**という癖もそのまま出る。
  */
  const accumulator = new SettingsExtractionCollector();
  const extractedPeople: Array<{ data: { name: string; aliases?: string[] } }> =
    [];

  /*
    **プロンプトは輪の中で組む。** 既知名が育つので、外で先に組んでおくと
    1つ目のチャンクの材料が最後まで使われることになる。`runChunks` は
    `chunkId` だけを見て失敗を数えるので、チャンクを添えて渡す。
  */
  const items = selected.map((chunk) => ({
    chunkId: chunkIdOf(input.filePath, chunk, maxChars),
    chunk,
  }));

  /** 答えたモデル。**sampling では呼び出し元が選ぶ**ので集めて返す */
  const answeredBy = new Set<string>();

  const callAI = async (
    userPrompt: string
  ): Promise<{ text: string; model: string }> => {
    if (input.runner === "sampling") {
      const reply = await askSampling({
        folder: input.folder,
        systemPrompt: prompts.systemPrompt,
        userPrompt,
      });
      return { text: reply.text, model: reply.model };
    }
    const response = await ollamaGenerate({
      endpoint: input.endpoint,
      model: model as string,
      systemPrompt: prompts.systemPrompt,
      userPrompt,
      schema: prompts.schema,
      numCtx: input.numCtx,
      allowRemote: input.allowRemote,
    });
    return { text: response.text, model: model as string };
  };

  const step = async ({ chunk }: { chunk: Chunk }) => {
    const gathered = accumulator.candidates();
    const item = promptForChunk(
      input.filePath,
      chunk,
      maxChars,
      stored,
      extractedPeople,
      {
        abilities: gathered.abilities.map((entry) => entry.data.name),
        locations: gathered.locations.map((entry) => entry.data.name),
        organizations: gathered.organizations.map((entry) => entry.data.name),
        world: gathered.worldItems.map((entry) => entry.data.name),
      }
    );

    /*
      **AIの呼び方だけを差し替える**（設計書6.87.12）。輪の作り——
      既知名を育てながらチャンクを回すところ——は両方で同じである。
    */
    const reply = await callAI(item.userPrompt);
    answeredBy.add(reply.model);

    const parsed = parseResult(reply.text);
    if (!parsed) {
      throw new McpToolError(
        "応答を読み取れませんでした（設定資料の抽出のスキーマに沿っていません。JSONの形か、項目が合っていません）。"
      );
    }
    const result = validateAgainst(
      item.chunkId,
      chunk,
      parsed,
      stored,
      accumulator
    );
    for (const person of result.characters.accepted) {
      const data = (person as { data?: { name?: string; aliases?: string[] } })
        .data;
      if (data?.name) {
        extractedPeople.push({
          data: { name: data.name, aliases: data.aliases ?? [] },
        });
      }
    }
    return result;
  };

  if (input.runner === "sampling") {
    return runChunksBySampling(items, async (item) => ({
      result: await step(item),
      // **輪の中で答えたモデルを拾う**（呼び出し元が選ぶので、こちらは知らない）
      model: [...answeredBy].pop() ?? "（不明）",
    }));
  }
  return runChunks(model as string, items, step);
}
