import {
  BASE_SYSTEM_PROMPT,
  CHARACTER_EXTRACT_SCHEMA,
  CHARACTER_EXTRACT_TEMPERATURE,
  CHARACTER_EXTRACT_VERSION,
  buildCharacterExtractPrompt,
  type CharacterExtractResult,
} from "../../prompts/characterExtract";
import {
  parseResult,
  validateCharacterExtractResult,
} from "../../core/characterExtractionValidation";
import { buildKnownCharacterNamesForPrompt } from "../../core/knownCharacterNames";
import { SettingsExtractionCollector } from "../../core/settingsExtractionCollect";
import type { Chunk } from "../../core/chunker";
import { parseCharacter } from "../../models/character";
import { parseAbility } from "../../models/ability";
import { parseLocation } from "../../models/location";
import { parseOrganization } from "../../models/organization";
import { parseWorldItem } from "../../models/world";
import {
  McpToolError,
  SETTINGS_SUBDIRS,
  chapterLabelOf,
  chunkFromId,
  chunkIdOf,
  chunksOfWorkFile,
  readSettingsRecords,
  selectChunks,
} from "./shared";
import { ollamaGenerate } from "./ollama";
import { askSampling } from "./sampling";
import {
  assertRunner,
  claudeNote,
  runChunks,
  runChunksBySampling,
  temperatureFor,
  type RunnerKind,
  validateWith,
} from "./run";
import type { RunOutcome } from "./run";
import { readExtractStash, stashExtractAnswer } from "./extractStash";
import { replayChunksOf } from "./extractCommit";
import { ExtractionReplay } from "../../core/externalExtractMerge";

/**
 * 設定資料の抽出（P-04a）を外から呼ぶ（設計書6.87.8 の4）。
 *
 * **並びは製品のまま**（6.87.6 の3）。既にいる人物・能力・場所・組織・
 * 世界観の名前を集めて `buildCharacterExtractPrompt` へ渡し、応答は
 * `parseResult` → `validateCharacterExtractResult` と、能力・場所・組織・
 * 世界観の4つの検算（`SettingsExtractionCollector.collect`）へ通す。
 *
 * **集約は製品のクラスをそのまま使う。** `collect` の中では総称を先に
 * 読み、人物側の所属も拾う——**その順そのものが意味を持っている**ので、
 * 外で検算を呼び直すと順が写しになる。
 *
 * ---
 *
 * **書き戻さない**（6.87.7）。製品はこのあと
 *
 *   抽出 → **コードでマージ** → 承認待ちへ積む → 作者が承認して保存
 *
 * と進むが、MCPが返すのは**マージの手前まで**である。マージは
 * `characterMerge` / `settingsMerge` の仕事で、既存レコードを
 * 書き換える判断が入る。**「読む・測る・提案する」の線はここに引く。**
 *
 * ---
 *
 * **製品と1つだけ違うところ**（正直に書く）。
 *
 * 製品はチャンクを順に回し、**前のチャンクで見つけた名前を次のチャンクの
 * 「既知」へ足していく**。`settings.run` は同じように育てるが、
 * **`settings.prompt` を1チャンクずつ呼ぶ形では育たない**——
 * そのときの「既知」は `設定/` に保存済みのものだけである。
 * 作品全体の出来ばえを測るなら `run` を使う。
 */

const VALIDATE_WITH = validateWith("settings");

/** 既知名の上限。**製品と同じところで切る**（`features/extractCharacters.ts`） */
const KNOWN_LIMIT = 50;
/** 世界観の見出しだけ多く渡す（同じ事柄が別の見出しで増えるのを防ぐため） */
const KNOWN_WORLD_LIMIT = 150;

/** `設定/` に保存済みのもの。プロンプトにも検算にも要る */
interface StoredSettings {
  characters: Array<{ name: string; aliases: string[] }>;
  /** 作者が手で書いた人物の名前。**この人の別名はコードでも触らない** */
  authorEditedNames: string[];
  abilityNames: string[];
  locationNames: string[];
  organizationNames: string[];
  worldNames: string[];
  abilityTerm: string | null;
}

function readStored(folder: string): StoredSettings {
  const people = readSettingsRecords(
    folder,
    SETTINGS_SUBDIRS.characters,
    parseCharacter
  ).records;
  const abilities = readSettingsRecords(
    folder,
    SETTINGS_SUBDIRS.abilities,
    parseAbility
  ).records;
  const locations = readSettingsRecords(
    folder,
    SETTINGS_SUBDIRS.locations,
    parseLocation
  ).records;
  const organizations = readSettingsRecords(
    folder,
    SETTINGS_SUBDIRS.organizations,
    parseOrganization
  ).records;
  const world = readSettingsRecords(
    folder,
    SETTINGS_SUBDIRS.world,
    parseWorldItem
  ).records;

  const names = (
    records: Array<{ name: string; aliases: string[] }>
  ): string[] =>
    [
      ...new Set(
        records
          .flatMap((record) => [record.name, ...record.aliases])
          .map((name) => name.trim())
          .filter(Boolean)
      ),
    ];

  return {
    characters: people.map((person) => ({
      name: person.name,
      aliases: person.aliases,
    })),
    // **作者が手で書いたものは、AIの読みで押し流さない**（CLAUDE.md 規則2）
    authorEditedNames: people
      .filter((person) => person.autoGenerated === false)
      .map((person) => person.name),
    abilityNames: names(abilities).slice(0, KNOWN_LIMIT),
    locationNames: names(locations).slice(0, KNOWN_LIMIT),
    organizationNames: names(organizations).slice(0, KNOWN_LIMIT),
    worldNames: world
      .map((item) => item.name.trim())
      .filter(Boolean)
      .slice(0, KNOWN_WORLD_LIMIT),
    // 作者が確定させた総称があれば、それを使う（揺らさない）
    abilityTerm: null,
  };
}

export interface SettingsChunkPrompt {
  chunkId: string;
  index: number;
  chapterLabel: string;
  chars: number;
  userPrompt: string;
  /** このチャンクへ渡した既知名の件数（切ったかを、呼ぶ側が読めるように） */
  knownCounts: {
    characters: number;
    abilities: number;
    locations: number;
    organizations: number;
    world: number;
  };
}

export interface SettingsPromptResult {
  promptVersion: string;
  systemPrompt: string;
  schema: unknown;
  /** 製品がこのプロンプトで使う温度（`prompts/*.ts`）。**写しを持たない** */
  temperature: number;
  validateWith: string;
  /**
   * **チャンクをまたいで既知名が育たない**ことの断り。
   * 作品全体の出来ばえを測るなら `settings.run` を使う
   */
  note: string;
  chunks: SettingsChunkPrompt[];
}

export interface SettingsPromptInput {
  folder: string;
  filePath: string;
  numCtx: number;
  chunkIndex?: number;
}

const ACROSS_CHUNKS_NOTE =
  "prompt は1回ごとに独立しています。製品は前のチャンクで見つけた名前を" +
  "次の「既知」へ足していくので、作品全体の出来ばえを測るなら" +
  "novel.run（feature: settings）を使ってください。";

function promptForChunk(
  relative: string,
  chunk: Chunk,
  maxChars: number,
  stored: StoredSettings,
  extractedSoFar: Array<{ data: { name: string; aliases?: string[] } }>,
  extraKnown: {
    abilities: string[];
    locations: string[];
    organizations: string[];
    world: string[];
  }
): SettingsChunkPrompt {
  // **既知の人物は「人数」で切る**（名前の件数で切ると、別名の多い作品で
  // 後ろの人物が丸ごと落ちる。`buildKnownCharacterNamesForPrompt`）
  const knownCharacters = buildKnownCharacterNamesForPrompt(
    stored.characters,
    extractedSoFar as Parameters<typeof buildKnownCharacterNamesForPrompt>[1]
  );
  const abilities = [
    ...new Set([...stored.abilityNames, ...extraKnown.abilities]),
  ].slice(0, KNOWN_LIMIT);
  const locations = [
    ...new Set([...stored.locationNames, ...extraKnown.locations]),
  ].slice(0, KNOWN_LIMIT);
  const organizations = [
    ...new Set([...stored.organizationNames, ...extraKnown.organizations]),
  ].slice(0, KNOWN_LIMIT);
  const world = [
    ...new Set([...stored.worldNames, ...extraKnown.world]),
  ].slice(0, KNOWN_WORLD_LIMIT);

  return {
    chunkId: chunkIdOf(relative, chunk, maxChars),
    index: chunk.index,
    chapterLabel: chapterLabelOf(chunk),
    chars: chunk.text.length,
    knownCounts: {
      characters: knownCharacters.length,
      abilities: abilities.length,
      locations: locations.length,
      organizations: organizations.length,
      world: world.length,
    },
    userPrompt: buildCharacterExtractPrompt({
      chunkText: chunk.text,
      chapterLabel: chapterLabelOf(chunk),
      knownCharacterNames: knownCharacters,
      knownAbilityNames: abilities,
      knownLocationNames: locations,
      knownOrganizationNames: organizations,
      knownWorldNames: world,
      abilityTerm: stored.abilityTerm ?? undefined,
    }),
  };
}

interface ExtraKnown {
  abilities: string[];
  locations: string[];
  organizations: string[];
  world: string[];
}

const NO_EXTRA: ExtraKnown = {
  abilities: [],
  locations: [],
  organizations: [],
  world: [],
};

/**
 * 貯め場所（`extractStash.ts`）に入っている答えから、受け入れた人物と
 * 集めた能力・場所・組織・世界観の名前を拾う（2026-10-02）。
 *
 * **製品では、前のチャンクで見つけた名前が次の「既知」へ育つ。** 外部AIが
 * 1チャンクずつ `prompt` → `validate`（stash）と回すとき、貯めた分を既知へ
 * 足せば、製品と同じ育ち方に近づく。拾い方は保存（`novel.extract.commit`）と
 * 同じ再生（`ExtractionReplay`）を通す——検算に落ちた名前まで既知に混ぜない。
 *
 * **読めない貯め場所でプロンプトを止めない。** ここは「あれば足す」材料で、
 * 読めないことは保存のとき（`novel.extract.commit`）に断る。
 */
function stashedKnown(folder: string): {
  people: Array<{ data: { name: string; aliases?: string[] } }>;
  extra: ExtraKnown;
} {
  let stashed;
  try {
    stashed = readExtractStash(folder);
  } catch {
    return { people: [], extra: NO_EXTRA };
  }
  if (stashed.length === 0) return { people: [], extra: NO_EXTRA };
  const { chunks } = replayChunksOf(folder, stashed);
  const replay = new ExtractionReplay(
    {
      characters: readSettingsRecords(folder, SETTINGS_SUBDIRS.characters, parseCharacter)
        .records,
      abilities: readSettingsRecords(folder, SETTINGS_SUBDIRS.abilities, parseAbility)
        .records,
      locations: readSettingsRecords(folder, SETTINGS_SUBDIRS.locations, parseLocation)
        .records,
      organizations: readSettingsRecords(
        folder,
        SETTINGS_SUBDIRS.organizations,
        parseOrganization
      ).records,
      world: readSettingsRecords(folder, SETTINGS_SUBDIRS.world, parseWorldItem).records,
    },
    new SettingsExtractionCollector()
  );
  for (const item of chunks) replay.accept(item.parsed, item.chunk);
  const gathered = replay.settings.candidates();
  return {
    people: replay.extracted.map((person) => ({
      data: { name: person.data.name, aliases: person.data.aliases ?? [] },
    })),
    extra: {
      abilities: gathered.abilities.map((entry) => entry.data.name),
      locations: gathered.locations.map((entry) => entry.data.name),
      organizations: gathered.organizations.map((entry) => entry.data.name),
      world: gathered.worldItems.map((entry) => entry.data.name),
    },
  };
}

export function settingsPrompt(
  input: SettingsPromptInput
): SettingsPromptResult {
  const stored = readStored(input.folder);
  const { chunks, maxChars } = chunksOfWorkFile(
    input.folder,
    input.filePath,
    input.numCtx
  );
  // 貯めた分の名前を既知へ足す（製品で既知名が育つのと揃える）
  const known = stashedKnown(input.folder);

  return {
    promptVersion: CHARACTER_EXTRACT_VERSION,
    systemPrompt: BASE_SYSTEM_PROMPT,
    schema: CHARACTER_EXTRACT_SCHEMA,
    temperature: CHARACTER_EXTRACT_TEMPERATURE,
    validateWith: VALIDATE_WITH,
    note: ACROSS_CHUNKS_NOTE,
    chunks: selectChunks(chunks, input.chunkIndex).map((chunk) =>
      promptForChunk(
        input.filePath,
        chunk,
        maxChars,
        stored,
        known.people,
        known.extra
      )
    ),
  };
}

export interface SettingsValidateResult {
  chunkId: string;
  chapterLabel: string;
  /** 人物。`accepted` が取り出せたもの、`rejected` が検算で落ちたもの */
  characters: {
    accepted: unknown[];
    /**
     * 検算で落ちたもの（`{ name, reason }`）。
     *
     * 名前を決められずに落ちたもの（`pronoun_name`・`descriptive_name`）には、
     * **そのレコードの中身が `details` に付く**。一人称の作品では語り手が
     * 名前を名乗らず、AIが外見まで読み取っていても丸ごと落ちるので、
     * 件数だけ返すと外から見ても「認識しているのに増えない」としか分からない
     * （`missedCharacters` と同じ考え方で、外部AIにも黙らない）。
     */
    rejected: unknown[];
    droppedSharedBodyAliases: unknown[];
    droppedTruncatedAliases: unknown[];
    droppedSharedFamilyNameAliases: unknown[];
    droppedRelativeAliases: unknown[];
    /** 推測・断りで、関係になっていなかった関係（測定台が数える） */
    droppedRelations: unknown[];
    correctedRelations: unknown[];
    /** 関係の欄に入った呼び名を、呼称へ移したもの（2026-10-03） */
    movedAddressRelations: unknown[];
    /** 名前と合わない読みを外したもの（2026-10-01） */
    droppedReadings: unknown[];
    /** 口調の欄だけ外したもの（根拠の台詞が無い・指示の写し。2026-09-25） */
    droppedSpeechStyles: unknown[];
  };
  /** 能力・場所・組織・世界観。**製品の集約が数えたそのまま** */
  settings: {
    abilities: unknown[];
    locations: unknown[];
    organizations: unknown[];
    worldItems: unknown[];
    affiliations: string[];
    rejected: unknown[];
    abilityTerm: string | null;
    /**
     * 能力体系の決まり。**総称だけでは足りない**——実機確認（2026-09-19）で
     * ここへプロンプトの指示文がそのまま入っており、外から読めないと
     * 起きたことに気づけない（設定資料の測定台が見張る）。
     */
    rules: string[];
  };
  /**
   * **ここから先は返さない。** マージ（既存レコードとの突き合わせ）と
   * 保存は製品の側の仕事で、MCPは読む・測る・提案するまでである。
   */
  note: string;
}

const NOT_MERGED_NOTE =
  "マージ（既存の資料との突き合わせ）と保存は行っていません。" +
  "これは取り出して検算したところまでの結果です。";

function validateAgainst(
  chunkId: string,
  chunk: Chunk,
  parsed: CharacterExtractResult,
  stored: StoredSettings,
  accumulator: SettingsExtractionCollector,
  /** この回の前のチャンクで受け入れた人物（AIに「既知」として見せたもの） */
  extractedPeople: ReadonlyArray<{
    data: { name: string; aliases?: string[] };
  }> = []
): SettingsValidateResult {
  const knownNames = stored.characters.flatMap((person) => [
    person.name,
    ...person.aliases,
  ]);
  const people = validateCharacterExtractResult(parsed, chunk, {
    knownNames,
    authorEditedNames: stored.authorEditedNames,
    // **製品と同じく、AIに見せた顔ぶれ**（既存＋この回の分）。その名前で
    // 返った人物は、本文に名前が無くても根拠なしにしない（2026-09-24）
    knownRecordNames: [
      ...knownNames,
      ...extractedPeople.flatMap((person) => [
        person.data.name,
        ...(person.data.aliases ?? []),
      ]),
    ],
  });

  // **製品の集約をそのまま通す。** 総称を先に読む・人物側の所属を拾う、
  // といった順そのものが意味を持っているので、外で検算を呼び直さない
  accumulator.collect(parsed, chunk, {
    abilities: stored.abilityNames,
    locations: stored.locationNames,
    organizations: stored.organizationNames,
  });
  const gathered = accumulator.candidates();

  return {
    chunkId,
    chapterLabel: chapterLabelOf(chunk),
    characters: {
      accepted: people.accepted,
      rejected: people.rejected,
      droppedSharedBodyAliases: people.droppedSharedBodyAliases,
      droppedTruncatedAliases: people.droppedTruncatedAliases,
      droppedSharedFamilyNameAliases: people.droppedSharedFamilyNameAliases,
      droppedRelativeAliases: people.droppedRelativeAliases,
      droppedRelations: people.droppedRelations,
      correctedRelations: people.correctedRelations,
      movedAddressRelations: people.movedAddressRelations,
      droppedSpeechStyles: people.droppedSpeechStyles,
      droppedReadings: people.droppedReadings,
    },
    settings: {
      abilities: [...gathered.abilities],
      locations: [...gathered.locations],
      organizations: [...gathered.organizations],
      worldItems: [...gathered.worldItems],
      affiliations: gathered.affiliations,
      rejected: [...gathered.rejected],
      abilityTerm: gathered.abilityTerm,
      rules: [...gathered.rules],
    },
    note: NOT_MERGED_NOTE,
  };
}

export function settingsValidate(input: {
  folder: string;
  chunkId: string;
  response: string;
  /**
   * 検算が通った答えを貯める（2026-10-02）。貯めた分は
   * `novel.extract.commit` が拡張機能の抽出と同じ形で資料へ保存する
   */
  stash?: boolean;
}): SettingsValidateResult & { stashed?: true } {
  const parsed = parseResult(input.response);
  if (!parsed) {
    throw new McpToolError(
      "応答を読み取れませんでした（設定資料の抽出のスキーマに沿っていません。JSONの形か、項目が合っていません）。"
    );
  }
  const chunk = chunkFromId(input.folder, input.chunkId);
  if (!input.stash) {
    return validateAgainst(
      input.chunkId,
      chunk,
      parsed,
      readStored(input.folder),
      new SettingsExtractionCollector()
    );
  }
  /*
    **貯めるときは、貯めた分の人物を「AIに見せた顔ぶれ」に入れて検算する。**
    `prompt` が貯めた分の名前を既知として渡しているので、その名前で返った
    人物を根拠なしとして落とすと、見せた画面と検算が食い違う。
    保存のときは貯めた答えから検算し直すので、ここの結果は報告用である。
  */
  const result = validateAgainst(
    input.chunkId,
    chunk,
    parsed,
    readStored(input.folder),
    new SettingsExtractionCollector(),
    stashedKnown(input.folder).people
  );
  stashExtractAnswer(input.folder, input.chunkId, chunk, parsed);
  return { ...result, stashed: true, note: `${result.note}${STASHED_NOTE}` };
}

const STASHED_NOTE =
  "この答えを貯めました。novel.extract.commit で、拡張機能の［設定資料を抽出］と同じ形で資料へ保存できます" +
  "（新しい記録は保存、既存の記録への変更は承認待ち）。";

export interface SettingsRunInput extends SettingsPromptInput {
  runner: RunnerKind;
  endpoint?: string;
  model?: string;
  allowRemote?: boolean;
  temperature?: number;
}

export async function settingsRun(
  input: SettingsRunInput
): Promise<RunOutcome<SettingsChunkPrompt, SettingsValidateResult>> {
  // **省略を既定で埋めない**（設計書6.87.8 の5）
  assertRunner(input.runner);
  const prompts = settingsPrompt(input);
  // **明示が無ければ製品と同じ**（6.87.16）。決め方は `run.ts` に1つだけ
  const temperature = temperatureFor(input, prompts.temperature);
  if (input.runner === "claude") {
    return {
      runner: "claude",
      note: `${claudeNote(VALIDATE_WITH)} ${ACROSS_CHUNKS_NOTE}`,
      systemPrompt: prompts.systemPrompt,
      schema: prompts.schema,
      temperature,
      validateWith: VALIDATE_WITH,
      chunks: prompts.chunks,
    };
  }

  const model = input.model;
  if (input.runner === "ollama" && !model) {
    throw new McpToolError("runner が ollama のときは model が要ります。");
  }

  const stored = readStored(input.folder);
  const { chunks, maxChars } = chunksOfWorkFile(
    input.folder,
    input.filePath,
    input.numCtx
  );
  const selected = selectChunks(chunks, input.chunkIndex);

  /*
    **前のチャンクで見つけた名前を、次の「既知」へ足していく**（製品と同じ）。
    足さないと、同じ人物が話ごとに別人として返り、**AIは同じ相手の
    複数の呼び方を1つにまとめたがる**という癖もそのまま出る。
  */
  const accumulator = new SettingsExtractionCollector();
  const extractedPeople: Array<{ data: { name: string; aliases?: string[] } }> =
    [];

  /*
    **プロンプトは輪の中で組む。** 既知名が育つので、外で先に組んでおくと
    1つ目のチャンクの材料が最後まで使われることになる。`runChunks` は
    `chunkId` だけを見て失敗を数えるので、チャンクを添えて渡す。
  */
  const items = selected.map((chunk) => ({
    chunkId: chunkIdOf(input.filePath, chunk, maxChars),
    chunk,
  }));

  /** 答えたモデル。**sampling では呼び出し元が選ぶ**ので集めて返す */
  const answeredBy = new Set<string>();

  const callAI = async (
    userPrompt: string
  ): Promise<{ text: string; model: string }> => {
    if (input.runner === "sampling") {
      const reply = await askSampling({
        folder: input.folder,
        systemPrompt: prompts.systemPrompt,
        userPrompt,
        temperature,
      });
      return { text: reply.text, model: reply.model };
    }
    const response = await ollamaGenerate({
      endpoint: input.endpoint,
      model: model as string,
      systemPrompt: prompts.systemPrompt,
      userPrompt,
      schema: prompts.schema,
      numCtx: input.numCtx,
      temperature,
      allowRemote: input.allowRemote,
    });
    return { text: response.text, model: model as string };
  };

  const step = async ({ chunk }: { chunk: Chunk }) => {
    const gathered = accumulator.candidates();
    const item = promptForChunk(
      input.filePath,
      chunk,
      maxChars,
      stored,
      extractedPeople,
      {
        abilities: gathered.abilities.map((entry) => entry.data.name),
        locations: gathered.locations.map((entry) => entry.data.name),
        organizations: gathered.organizations.map((entry) => entry.data.name),
        world: gathered.worldItems.map((entry) => entry.data.name),
      }
    );

    /*
      **AIの呼び方だけを差し替える**（設計書6.87.12）。輪の作り——
      既知名を育てながらチャンクを回すところ——は両方で同じである。
    */
    const reply = await callAI(item.userPrompt);
    answeredBy.add(reply.model);

    const parsed = parseResult(reply.text);
    if (!parsed) {
      throw new McpToolError(
        "応答を読み取れませんでした（設定資料の抽出のスキーマに沿っていません。JSONの形か、項目が合っていません）。"
      );
    }
    const result = validateAgainst(
      item.chunkId,
      chunk,
      parsed,
      stored,
      accumulator,
      extractedPeople
    );
    /*
      **sampling の答えは貯める**（2026-10-02）。チャンクキャッシュは
      モデル名の分からない答えを貯めない（`run.ts`）ので、ここで貯めないと
      `novel.extract.commit` で保存する道が無い。Ollama の道は今回の
      対象に入れていない（作者の裁定は外部AIが抽出を代わりに行う道。
      手元のAIなら拡張機能の［設定資料を抽出］で同じ保存ができる）
    */
    if (input.runner === "sampling") {
      stashExtractAnswer(input.folder, item.chunkId, chunk, parsed);
    }
    for (const person of result.characters.accepted) {
      const data = (person as { data?: { name?: string; aliases?: string[] } })
        .data;
      if (data?.name) {
        extractedPeople.push({
          data: { name: data.name, aliases: data.aliases ?? [] },
        });
      }
    }
    return result;
  };

  if (input.runner === "sampling") {
    return runChunksBySampling(items, temperature, async (item) => ({
      result: await step(item),
      // **輪の中で答えたモデルを拾う**（呼び出し元が選ぶので、こちらは知らない）
      model: [...answeredBy].pop() ?? "（不明）",
    }));
  }
  return runChunks(model as string, temperature, items, step);
}
