import * as vscode from "vscode";
import * as path from "path";
import type { WorkEntry } from "../models/types";
import { readWorkConfig, workPaths } from "../core/workRegistry";
import { atomicWriteFile, createManagedRecoveryPath } from "../core/atomicWrite";
import {
  buildPlotMarkdown,
  parsePlotMarkdown,
  type PlotSections,
} from "../core/plotDoc";
import {
  buildSynopsisMarkdown,
  parseSynopsisMarkdown,
  type SynopsisDoc,
} from "../core/synopsisDoc";
import { buildSynopsisListMarkdown } from "../core/synopsisMarkdown";
import { buildEmotionCurveMarkdown } from "../core/emotionCurve";
import { SynopsisStore } from "../core/synopsisStore";
import type { ChatEdit } from "../core/chatEdit";

/**
 * 相談パネルからの加筆修正を、実際に書き込む。
 *
 * **書き込み先は「真実の在り処」であって、読み物のMarkdownではない。**
 * `characters.md` などはJSONから毎回作り直される生成物なので、そこへ
 * 書いても次の生成で消える。各話あらすじも同じで、真実は
 * `chapter_synopses.json` にある（`synopsis.md` の該当部分は表示物）。
 *
 * **既存ファイルは上書きできない**（`atomicWrite.ts`）。どの経路でも
 * 「回復先へ退避 → 新規作成」の順で書く。作者の文書なので、失敗しても
 * 元が残るようにしておく。
 *
 * 戻り値は「どこへ書いたか」。作者に知らせるために使う。
 */
export async function applyChatEdit(
  work: WorkEntry,
  edit: ChatEdit
): Promise<string> {
  switch (edit.target.kind) {
    case "plot":
      return applyToPlot(work, edit.target.section, edit.content);
    case "blurb":
      return applyToSynopsisDoc(work, (current) => ({
        ...current,
        blurb: edit.content,
      }));
    case "catchphrase":
      return applyToSynopsisDoc(work, (current) => ({
        ...current,
        catchphrase: edit.content,
      }));
    case "episodeSynopsis":
      return applyToEpisodeSynopsis(work, edit.target.chapter, edit.content);
  }
}

async function applyToPlot(
  work: WorkEntry,
  section: keyof PlotSections,
  content: string
): Promise<string> {
  const target = await settingsFile(work, "plot.md");
  const current = await readText(target);
  const parsed = parsePlotMarkdown(current ?? "");

  const sections: PlotSections = { ...parsed.sections, [section]: content };
  const body = buildPlotMarkdown(work.title, sections, {
    extra: parsed.extra,
    hints: true,
  });

  await replaceFile(target, body);
  return "設定/plot.md";
}

async function applyToSynopsisDoc(
  work: WorkEntry,
  update: (current: SynopsisDoc) => SynopsisDoc
): Promise<string> {
  const target = await settingsFile(work, "synopsis.md");
  const current = await readText(target);
  const doc = update(
    current
      ? parseSynopsisMarkdown(current)
      : { catchphrase: null, blurb: "" }
  );

  // 各話あらすじと感情曲線も同じ文書に載る（6.6.2）。
  // 真実はJSON側なので毎回作り直す
  const sections = await buildEpisodeSection(work);
  const body = buildSynopsisMarkdown(
    work.title,
    doc,
    sections.episodes,
    sections.emotion
  );

  await replaceFile(target, body);
  return "設定/synopsis.md";
}

/**
 * 各話あらすじを書き換える。
 *
 * **`upsertSynopsis` は使わない。** あちらは「AIの抽出結果を差し込む」
 * ための関数で、作者が書き直したあらすじ（`autoGenerated: false`）を
 * 守るために差し替えを拒む。ここは作者自身が書き換えを指示した場面なので、
 * 拒まれては困る。代わりに、書いた結果を `autoGenerated: false` にして
 * **以後の自動生成から守る**（作者の指示で入った内容だから）。
 */
async function applyToEpisodeSynopsis(
  work: WorkEntry,
  chapter: number,
  content: string
): Promise<string> {
  const store = new SynopsisStore(work);
  const set = await store.load();

  const index = set.episodes.findIndex((item) => item.chapter === chapter);
  if (index < 0) {
    throw new Error(
      `第${chapter}話のあらすじが見つかりません。先に「各話あらすじを生成」を実行してください。`
    );
  }

  const episodes = set.episodes.map((item) => ({ ...item }));
  episodes[index] = {
    ...episodes[index],
    synopsis: content,
    autoGenerated: false,
    updatedAt: new Date().toISOString(),
  };

  await store.save({ ...set, episodes });

  // 読み物の側（synopsis.md）も追随させる。作らないと、
  // 開いた文書には古いあらすじが出たままになる
  try {
    await applyToSynopsisDoc(work, (current) => current);
  } catch {
    // 読み物を作り直せなくても、あらすじ本体は保存済み
  }
  return "設定/chapter_synopses.json";
}

async function buildEpisodeSection(
  work: WorkEntry
): Promise<{ episodes: string; emotion: string }> {
  try {
    const set = await new SynopsisStore(work).load();
    if (set.episodes.length === 0) return { episodes: "", emotion: "" };
    return {
      episodes: buildSynopsisListMarkdown(set, {
        workTitle: work.title,
        headingLevel: 2,
        includeTitle: false,
      }),
      emotion: buildEmotionCurveMarkdown(set.episodes),
    };
  } catch {
    return { episodes: "", emotion: "" };
  }
}

async function settingsFile(
  work: WorkEntry,
  fileName: string
): Promise<string> {
  const config = await readWorkConfig(work);
  return path.join(workPaths(work, config).settings, fileName);
}

async function readText(target: string): Promise<string | undefined> {
  try {
    const bytes = await vscode.workspace.fs.readFile(vscode.Uri.file(target));
    return new TextDecoder().decode(bytes);
  } catch {
    return undefined;
  }
}

/** 既存ファイルは上書きできないので、退避してから作り直す */
async function replaceFile(target: string, body: string): Promise<void> {
  await vscode.workspace.fs.createDirectory(
    vscode.Uri.file(path.dirname(target))
  );

  if (await exists(target)) {
    const recoveryPath = await createManagedRecoveryPath(target);
    const bytes = await vscode.workspace.fs.readFile(vscode.Uri.file(target));
    await atomicWriteFile(recoveryPath, bytes, { mode: "create" });
    await vscode.workspace.fs.delete(vscode.Uri.file(target), {
      useTrash: false,
    });
  }

  await atomicWriteFile(target, new TextEncoder().encode(body), {
    mode: "create",
  });
}

async function exists(filePath: string): Promise<boolean> {
  try {
    await vscode.workspace.fs.stat(vscode.Uri.file(filePath));
    return true;
  } catch {
    return false;
  }
}
