import * as vscode from "vscode";
import * as path from "../core/paths";
import type { WorkEntry } from "../models/types";
import { readWorkConfig, workPaths } from "../core/workRegistry";
import { atomicWriteFile, createManagedRecoveryPath } from "../core/atomicWrite";
import {
  parsePlotMarkdown,
  updatePlotMarkdown,
  type PlotSections,
} from "../core/plotDoc";
import {
  buildSynopsisMarkdown,
  parseSynopsisMarkdown,
  type SynopsisDoc,
} from "../core/synopsisDoc";
import { buildSynopsisListMarkdown } from "../core/synopsisMarkdown";
import { loadSynopsisChapterMarks } from "../core/synopsisChapters";
import { buildEmotionCurveMarkdown } from "../core/emotionCurve";
import { SynopsisStore } from "../core/synopsisStore";
import type { ChatEdit, ChatEditTarget } from "../core/chatEdit";

/**
 * 相談パネルからの加筆修正を、実際に書き込む。
 *
 * **書き込み先は「真実の在り処」であって、読み物のMarkdownではない。**
 * `characters.md` などはJSONから毎回作り直される生成物なので、そこへ
 * 書いても次の生成で消える。各話あらすじも同じで、真実は
 * `chapter_synopses.json` にある（`synopsis.md` の該当部分は表示物）。
 *
 * **既存ファイルは上書きできない**（`atomicWrite.ts`）。どの経路でも
 * 「回復先へ退避 → 新規作成」の順で書く。作者の文書なので、失敗しても
 * 元が残るようにしておく。
 *
 * 戻り値は「どこへ書いたか」。作者に知らせるために使う。
 */
export async function applyChatEdit(
  work: WorkEntry,
  edit: ChatEdit,
  options: {
    /**
     * 空の中身も書く（**取り消し専用**。設計書6.4.7）。
     *
     * **AIには渡させない。** `ChatEdit` の中ではなく呼び出しの引数に
     * 置いてあるのは、AIが返した値からこの印が立つ余地を残さないためである。
     * 普通の書き込みでは `parseChatEdit` が空の `content` を弾くので、
     * ここが立つのは「書く前の値（空かもしれない）へ戻す」ときだけになる。
     */
    allowEmpty?: boolean;
  } = {}
): Promise<string> {
  switch (edit.target.kind) {
    case "plot":
      return applyToPlot(
        work,
        edit.target.section,
        edit.content,
        options.allowEmpty ?? false
      );
    case "blurb":
      return applyToSynopsisDoc(work, (current) => ({
        ...current,
        blurb: edit.content,
      }));
    case "catchphrase":
      return applyToSynopsisDoc(work, (current) => ({
        ...current,
        catchphrase: edit.content,
      }));
    case "episodeSynopsis":
      return applyToEpisodeSynopsis(work, edit.target.chapter, edit.content);
  }
}

/**
 * いま入っている値を読む（取り消しのために控える）。
 *
 * **書く前に控えておく。** 頼まれた書き込みは確認を出さずに行うように
 * なった（設計書6.4.7・2026-09-21の作者の裁定）ので、**戻せる道を
 * その場に出す**必要がある。控えが無ければ、書いたあとに「元は何だったか」を
 * 誰も知らない。
 *
 * 読めない・まだ書かれていないときは空文字を返す。「書かれていなかった」
 * ことも、戻すべき状態である。
 */
export async function readChatEditTarget(
  work: WorkEntry,
  target: ChatEditTarget
): Promise<string> {
  switch (target.kind) {
    case "plot": {
      const text = await readText(await settingsFile(work, "plot.md"));
      return text ? (parsePlotMarkdown(text).sections[target.section] ?? "") : "";
    }
    case "blurb":
    case "catchphrase": {
      const text = await readText(await settingsFile(work, "synopsis.md"));
      if (!text) return "";
      const doc = parseSynopsisMarkdown(text);
      return target.kind === "blurb" ? doc.blurb : (doc.catchphrase ?? "");
    }
    case "episodeSynopsis": {
      try {
        const set = await new SynopsisStore(work).load();
        const found = set.episodes.find(
          (item) => item.chapter === target.chapter
        );
        return found?.synopsis ?? "";
      } catch {
        // 台帳がまだ無い。書けば作られるので、控えは空でよい
        return "";
      }
    }
  }
}

async function applyToPlot(
  work: WorkEntry,
  section: keyof PlotSections,
  content: string,
  allowEmpty: boolean
): Promise<string> {
  const target = await settingsFile(work, "plot.md");
  const current = await readText(target);
  // **作者の文書の形を変えない。** 節に分解して組み直すと、作者が立てた
  // 見出しが末尾へ寄り、順番も決まった並びへ戻る（作者の指示、2026-08-16）
  const body = updatePlotMarkdown(
    current ?? "",
    { [section]: content },
    { workTitle: work.title, allowEmpty }
  );

  await replaceFile(target, body);
  return "設定/plot.md";
}

async function applyToSynopsisDoc(
  work: WorkEntry,
  update: (current: SynopsisDoc) => SynopsisDoc
): Promise<string> {
  const target = await settingsFile(work, "synopsis.md");
  const current = await readText(target);
  const doc = update(
    current
      ? parseSynopsisMarkdown(current)
      : { catchphrase: null, blurb: "" }
  );

  // 各話あらすじと感情曲線も同じ文書に載る（6.6.2）。
  // 真実はJSON側なので毎回作り直す
  const sections = await buildEpisodeSection(work);
  const body = buildSynopsisMarkdown(
    work.title,
    doc,
    sections.episodes,
    sections.emotion
  );

  await replaceFile(target, body);
  return "設定/synopsis.md";
}

/**
 * 各話あらすじを書き換える。
 *
 * **`upsertSynopsis` は使わない。** あちらは「AIの抽出結果を差し込む」
 * ための関数で、作者が書き直したあらすじ（`autoGenerated: false`）を
 * 守るために差し替えを拒む。ここは作者自身が書き換えを指示した場面なので、
 * 拒まれては困る。代わりに、書いた結果を `autoGenerated: false` にして
 * **以後の自動生成から守る**（作者の指示で入った内容だから）。
 */
async function applyToEpisodeSynopsis(
  work: WorkEntry,
  chapter: number,
  content: string
): Promise<string> {
  /*
    **空にはできない**（2026-09-21）。台帳は非空を前提に検証しているので、
    空を書くと**保存は通るのに次の読み込みで台帳ごと読めなくなる**
    （`test/unit/core/synopsisStore.test.ts`）。取り消しで空が来たときのために
    ここで断る——`plot.md` のように「空へ戻す」はできない対象である。
  */
  if (content === "") {
    throw new Error(
      `第${chapter}話のあらすじは空にできません（あらすじの記録が読めなくなるため）。` +
        "手で書き換えてください。"
    );
  }

  const store = new SynopsisStore(work);
  const set = await store.load();

  const index = set.episodes.findIndex((item) => item.chapter === chapter);
  if (index < 0) {
    throw new Error(
      `第${chapter}話のあらすじが見つかりません。先に「各話あらすじ」を実行してください。`
    );
  }

  const episodes = set.episodes.map((item) => ({ ...item }));
  episodes[index] = {
    ...episodes[index],
    synopsis: content,
    autoGenerated: false,
    updatedAt: new Date().toISOString(),
  };

  await store.save({ ...set, episodes });

  // 読み物の側（synopsis.md）も追随させる。作らないと、
  // 開いた文書には古いあらすじが出たままになる
  try {
    await applyToSynopsisDoc(work, (current) => current);
  } catch {
    // 読み物を作り直せなくても、あらすじ本体は保存済み
  }
  return "設定/chapter_synopses.json";
}

async function buildEpisodeSection(
  work: WorkEntry
): Promise<{ episodes: string; emotion: string }> {
  try {
    const set = await new SynopsisStore(work).load();
    if (set.episodes.length === 0) return { episodes: "", emotion: "" };
    return {
      episodes: buildSynopsisListMarkdown(set, {
        workTitle: work.title,
        headingLevel: 2,
        includeTitle: false,
        // 章の見出しも `generateBlurb` と同じ形で挟む（設計書6.66.4の3）。
        // 片方だけ挟むと、書き換えた経路によって文書の形が変わる
        chapters: await loadSynopsisChapterMarks(work, set),
      }),
      emotion: buildEmotionCurveMarkdown(set.episodes),
    };
  } catch {
    return { episodes: "", emotion: "" };
  }
}

async function settingsFile(
  work: WorkEntry,
  fileName: string
): Promise<string> {
  const config = await readWorkConfig(work);
  return path.join(workPaths(work, config).settings, fileName);
}

async function readText(target: string): Promise<string | undefined> {
  try {
    const bytes = await vscode.workspace.fs.readFile(path.toUri(target));
    return new TextDecoder().decode(bytes);
  } catch {
    return undefined;
  }
}

/** 既存ファイルは上書きできないので、退避してから作り直す */
async function replaceFile(target: string, body: string): Promise<void> {
  await vscode.workspace.fs.createDirectory(
    path.toUri(path.dirname(target))
  );

  if (await exists(target)) {
    const recoveryPath = await createManagedRecoveryPath(target);
    const bytes = await vscode.workspace.fs.readFile(path.toUri(target));
    await atomicWriteFile(recoveryPath, bytes, { mode: "create" });
    await vscode.workspace.fs.delete(path.toUri(target), {
      useTrash: false,
    });
  }

  await atomicWriteFile(target, new TextEncoder().encode(body), {
    mode: "create",
  });
}

async function exists(filePath: string): Promise<boolean> {
  try {
    await vscode.workspace.fs.stat(path.toUri(filePath));
    return true;
  } catch {
    return false;
  }
}
