import * as vscode from "vscode";
import type { WorkEntry } from "../models/types";
import {
  addForeshadow,
  createForeshadowStore,
} from "../core/foreshadowStore";
import {
  buildEmptyForeshadowGuide,
  buildForeshadowMarkdown,
  FORESHADOW_LIST_TITLE,
} from "../core/foreshadowMarkdown";
import { logFailure } from "../core/logger";
import { askText } from "../views/dialogs";
import { openGeneratedMarkdown } from "../views/openDocument";
import type { ForeshadowFromContradiction } from "./proposalPanel";

/**
 * 伏線追跡の土台（設計書6.35）。
 *
 * **この版ではAIを使わない。** 配置・回収の自動検知（P-25/P-26）は
 * 次の弾で入る。ここで作るのは、検知した結果を受け止める台帳と、
 * 作者が手で足す口、そして矛盾検知からの転送口である。
 *
 * 台帳が先に無いと、検知だけ作っても入れる先が無い。
 */

export async function openForeshadows(work: WorkEntry): Promise<void> {
  const store = createForeshadowStore(work);

  let loaded: Awaited<ReturnType<typeof store.loadAll>>;
  try {
    loaded = await store.loadAll();
  } catch (error) {
    void vscode.window.showErrorMessage(
      `伏線の台帳を読み込めませんでした：${messageOf(error)}`
    );
    return;
  }

  // **読めなかったファイルは黙って落とさない。** 勝手に直しはしないが、
  // 一覧に出ていないものがあることは伝える
  if (loaded.errors.length > 0) {
    void vscode.window.showWarningMessage(
      `読み込めない伏線が ${loaded.errors.length} 件あります（${loaded.errors
        .map((error) => error.file)
        .join("、")}）。残りだけを並べます。`
    );
  }

  const content =
    loaded.records.length === 0
      ? buildEmptyForeshadowGuide()
      : buildForeshadowMarkdown(loaded.records);

  // どの画面で読むかは作者の割り当てに任せる（`openGeneratedMarkdown`）
  await openGeneratedMarkdown(FORESHADOW_LIST_TITLE, content, {
    preview: false,
  });
}

/**
 * 伏線を手で追加する。
 *
 * **取りやめの道を各入力で保つ。** `askText` は取りやめると `undefined` を
 * 返すので、空文字（「書かないことにした」）と区別して扱う。
 */
export async function addForeshadowByHand(work: WorkEntry): Promise<void> {
  const label = await askText({
    title: "伏線を手で追加（1/3）",
    prompt: "伏線の短い名を入れてください（例：銀の懐中時計）",
    ignoreFocusOut: true,
    validateInput: (value) =>
      value.trim().length === 0 ? "名前を入れてください。" : undefined,
  });
  if (label === undefined) return;

  const note = await askText({
    title: "伏線を手で追加（2/3）",
    prompt: "何を示唆しているかを書いてください（空のままでも構いません）",
    ignoreFocusOut: true,
  });
  if (note === undefined) return;

  const chapterText = await askText({
    title: "伏線を手で追加（3/3）",
    prompt: "張った話数を数字で入れてください（分からなければ空のまま）",
    ignoreFocusOut: true,
    validateInput: (value) => {
      const trimmed = value.trim();
      if (trimmed.length === 0) return undefined;
      return /^\d+$/.test(trimmed)
        ? undefined
        : "半角の数字で入れてください（分からなければ空のままにしてください）。";
    },
  });
  if (chapterText === undefined) return;

  const plantedChapter = chapterText.trim()
    ? parseInt(chapterText.trim(), 10)
    : null;

  try {
    const saved = await addForeshadow(work, {
      label: label.trim(),
      note: note.trim(),
      plantedChapter,
      source: "author",
      // 作者が書いたものなので、AI生成ではない
      autoGenerated: false,
    });
    void vscode.window.showInformationMessage(
      `「${saved.label}」を伏線として登録しました。「伏線の一覧を開く」で見られます。`
    );
  } catch (error) {
    const detail = messageOf(error);
    logFailure("伏線の登録に失敗", { 伏線: label.trim(), 詳細: detail });
    void vscode.window.showErrorMessage(`伏線を登録できませんでした：${detail}`);
  }
}

/**
 * 矛盾検知の指摘を、伏線として台帳へ入れる（設計書6.35.4）。
 *
 * **この経路だけは直接保存してよい。** 検知結果の自動保存は禁じているが、
 * ここは作者が「伏線として登録」を押した時点で承認済みだからである。
 *
 * 失敗しても例外を投げず、理由を返す。提案パネルは1件の失敗で
 * 一覧ごと落ちてはいけない（他の指摘の判断が消える）。
 */
export async function registerForeshadowFromContradiction(
  work: WorkEntry,
  source: ForeshadowFromContradiction
): Promise<{ ok: boolean; reason?: string }> {
  try {
    await addForeshadow(work, {
      label: source.label,
      note: source.note,
      plantedChapter: source.chapter,
      plantedQuote: source.quote,
      source: "contradiction",
      // 元をたどればAIの指摘なので、作者が確定させた記述とは区別する
      autoGenerated: true,
    });
    return { ok: true };
  } catch (error) {
    const detail = messageOf(error);
    logFailure("矛盾からの伏線登録に失敗", {
      伏線: source.label,
      詳細: detail,
    });
    return { ok: false, reason: detail };
  }
}

function messageOf(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}
