import * as vscode from "vscode";
import * as path from "../core/paths";
import type { WorkEntry } from "../models/types";
import { AIRegistry, ensureConfigured } from "../ai/registry";
import { confirmProviderReachable } from "./aiConnectivity";
import { AIError, recoveryForAIError } from "../ai/types";
import {
  resolveOutputTokensForPlanning,
  resolveOutputTokensForSend,
} from "../ai/outputLimit";
import { scanWork } from "../core/scanner";
import {
  episodeBodyLabel,
  loadEpisodeBodies,
  needsSubtitle,
  type EpisodeBody,
} from "../core/episodeBodies";
import { SynopsisStore, SynopsisStoreError } from "../core/synopsisStore";
import {
  findSynopsis,
  upsertSynopsis,
  type ChapterSynopsisSet,
} from "../models/synopsis";
import {
  describeSubtitleRejection,
  parseSynopsisResult,
  validateSynopsisResult,
} from "../core/synopsisValidation";
import {
  SYNOPSIS_SCHEMA,
  SYNOPSIS_SYSTEM_PROMPT,
  SYNOPSIS_TEMPERATURE,
  buildSynopsisPrompt,
  synopsisPromptVersion,
  type SubtitleSuggestion,
} from "../prompts/synopsis";
import { CharacterStore } from "../core/characterStore";
import { ReaderTargetStore } from "../core/readerTargetStore";
import { readerTypeCacheMark } from "../core/readerTarget";
import type { ReaderProfile } from "../models/readerProfile";
import { withAiTurnProgress } from "./aiTurn";
import {
  logFailure,
  logStep,
  responseExcerptForLog,
  useLogFile,
} from "../core/logger";
import { renameEpisodeFile } from "../core/episodeRename";
import { confirmFormatFit } from "./formatFitPrompt";
import { cancelItem, isCancelItem } from "../views/dialogs";
import { estimateCallsTimeFor } from "../ai/runTimeEstimate";
import { describeCallTimeEstimate } from "../core/etaEstimate";

/**
 * 速さを測っていないときの、1話あたりの決め打ちの秒数（設計書6.8.19）。
 * **これまでの目安の値そのもの**（`features/extractCharacters.ts` と同じ考え方）。
 */
const SYNOPSIS_FALLBACK_SECONDS_PER_EPISODE = 15;
import {
  confirmRun,
  notifyDone,
  warnWithLog,
  whenNoticePicked,
} from "../views/notify";

/**
 * 各話あらすじの生成（P-07）と、サブタイトルの提案・リネーム。
 *
 * **話を単位にした初めての機能**である。設定抽出はチャンク単位で、
 * 話をまたいでまとめて送っていたが、あらすじは1話に1本作るため、
 * まとめずに1話ずつ送る。
 *
 * 作り直しの判断は「本文のハッシュ＋モデル名＋プロンプトの版」で行う。
 * 変わっていない話は呼ばない（設定抽出のキャッシュと同じ考え方）。
 */

/** 前話のあらすじを何件まで文脈として渡すか */
const PREVIOUS_SYNOPSES_LIMIT = 3;

export async function generateSynopses(
  work: WorkEntry,
  registry: AIRegistry
): Promise<boolean> {
  useLogFile(work.folderPath);

  // 短編では1件しか作れず、感情曲線も線にならない（設計書6.4.5）
  if (!(await confirmFormatFit(work, "episodeSynopses"))) return false;

  const resolved = await ensureConfigured(registry, "generate");
  if (!resolved) return false;

  const scan = await scanWork(work);
  if (scan.episodes.length === 0) {
    vscode.window.showWarningMessage("本文ファイルが見つかりません。");
    return false;
  }

  const loaded = await loadEpisodeBodies(scan.episodes);
  if (loaded.bodies.length === 0) {
    vscode.window.showWarningMessage("あらすじを作れる本文がありません。");
    return false;
  }

  const store = new SynopsisStore(work);
  let set: ChapterSynopsisSet;
  try {
    set = await store.load();
  } catch (error) {
    // 壊れたJSONを空として扱うと、作者が書き直したあらすじが消える
    reportStoreError(error);
    return false;
  }

  set = await syncStaleFileNamesAndTitles(store, set, loaded.bodies);

  /*
    **サブタイトルは宛先を見て選ばせる**（作者の依頼、2026-09-22
    「サブタイトルの提案に、ターゲット読者を考慮させるようにしてください」）。
    同じ話でも、回遊層に効く題と考察層に効く題は違う。

    **診断していなければ渡さない**（一般論のまま）。読めなくても止めない
    ——題の選び方が今までどおりに戻るだけで、あらすじは作れる。

    **読むのは作り直しの判断より前**（0.75.3）。読者像は版へ混ざるので、
    あとから読むと「作り直すかどうか」を古い前提で決めることになる。
  */
  let readerProfile: ReaderProfile | undefined;
  try {
    readerProfile = await new ReaderTargetStore(work).load();
  } catch (error) {
    logFailure("あらすじ生成: 読者像の台帳を読めませんでした", {
      作品: work.title,
      詳細: error instanceof Error ? error.message : String(error),
    });
  }
  const readerTypeMark = readerTypeCacheMark(readerProfile);
  /** その話を作り直すかどうかを決める版。サブタイトルの回だけ読者像が混ざる */
  const versionFor = (episode: EpisodeBody): string =>
    synopsisPromptVersion({
      needsSubtitle: needsSubtitle(episode),
      readerTypeMark,
    });

  // 作り直しが要る話だけを選ぶ
  const pending = loaded.bodies.filter((episode) => {
    const existing = findSynopsis(
      set,
      episode.file.fileName,
      episode.chapter
    );
    if (!existing) return true;
    if (!existing.autoGenerated) return false; // 作者が書いたものは触らない
    return (
      existing.sourceHash !== episode.hash ||
      existing.model !== resolved.model ||
      existing.promptVersion !== versionFor(episode)
    );
  });

  if (pending.length === 0) {
    vscode.window.showInformationMessage(
      "すべての話のあらすじが最新です。本文を変えた話だけを作り直します。"
    );
    return true;
  }

  // **繋がるかを、費用の確認より先に確かめる**（設計書6.51）。
  // 繋がらないと分かっているのに料金の話をしても意味がない。
  // 置くのは「作り直しが要る話が1つも無い」で抜けたあと——
  // AIを1度も呼ばない回に起動を促しても、作者を迷わせるだけである
  // （`checkTypos.ts` が `pending.length > 0` のときだけ呼ぶのと同じ）。
  // モデル名を渡すのは、LM Studioをこの場から起こしたときの読み込みに要るため
  if (
    !(await confirmProviderReachable(
      resolved.provider,
      "各話あらすじの作成",
      resolved.model
    ))
  ) {
    return false;
  }

  /*
    **目安は送る量と速さから出す**（設計書6.8.19。ノートPCの実機、
    2026-09-23。人物抽出で「目安 2 分」が実際は31分だった）。CPUだけの
    機械では本文の読み込みが時間の大半なので、1話の長さが効く。

    送る字数は実際の組み方で数える。人物名の一覧だけは確認のあとで読む
    ので入れていない（100人ぶんでも数百字）。速さを測っていなければ、
    これまでの15秒へ落ちる。
  */
  const timeEstimate = estimateCallsTimeFor({
    providerId: resolved.provider.id,
    model: resolved.model,
    feature: "synopsis",
    inputChars: pending.map(
      (episode) =>
        SYNOPSIS_SYSTEM_PROMPT.length +
        buildSynopsisPrompt({
          chapterLabel: episodeBodyLabel(episode),
          chapterText: episode.body,
          previousSynopses: previousSynopsesFor(set, episode),
          characterNames: [],
          needsSubtitle: needsSubtitle(episode),
          readerProfile,
        }).length
    ),
    fallbackSecondsPerCall: SYNOPSIS_FALLBACK_SECONDS_PER_EPISODE,
  });
  const costNotice = resolved.provider.isPaid
    ? `\n${resolved.provider.displayName} は呼び出すたびに課金されます。`
    : "";
  const confirmed = await confirmRun(
    `${loaded.bodies.length} 話中 ${pending.length} 話のあらすじを作ります` +
      `（変わっていない ${loaded.bodies.length - pending.length} 話はスキップ）。\n` +
      `モデル: ${resolved.model} / ` +
      (timeEstimate
        ? describeCallTimeEstimate(timeEstimate)
        : "目安は出せません") +
      costNotice,
    "実行",
    // どの作品かを確認画面に出す（ノートPCの実機、2026-09-23）
    { remember: { id: "ai.run.generateSynopses" }, workTitle: work.title }
  );
  if (!confirmed) return false;

  // 人物名は表記を揃えるために渡す。モブは名前が普通名詞になりがちで、
  // あらすじの文中に混ざると読みにくい
  const characterNames = (await new CharacterStore(work).loadAll()).characters
    .filter((character) => !character.isMob)
    .map((character) => character.name);

  // **応答の見込みに実測を使う**（設計書6.65.16の2、6.77の第2段）。
  // あらすじは1話ぶんで短いが、渡さないとOllamaの `num_ctx` が
  // 既定の8,192で確保される
  const plannedOutputTokens = resolveOutputTokensForPlanning(
    resolved.provider.id,
    resolved.model,
    "synopsis"
  );
  // **場所の確保（上）と、実際に送る上限（下）は別物である**（設計書6.77の
  // 第2段）。上を上限として送ると、測っていないモデルでは上限が設定値の
  // 半分になり、長い応答が途中で切れる
  const sendOutputTokens = resolveOutputTokensForSend(
    resolved.provider.id,
    resolved.model,
    "synopsis"
  );

  const failures: Array<{ label: string; message: string }> = [];
  const subtitleCandidates: Array<{
    episode: EpisodeBody;
    suggestions: SubtitleSuggestion[];
  }> = [];
  let done = 0;
  let cancelled = false;

  // **ほかの一括処理と重ならないよう、実行の札を取る**（設計書6.76）。
  // 話の数だけAIを呼ぶので、ほかの一括処理と交互に流すと
  // モデルの読み込み直しが往復する
  await withAiTurnProgress(
    "あらすじを作っています",
    { label: "各話あらすじの生成", onCancelled: () => (cancelled = true) },
    async (progress, token) => {
      for (const episode of pending) {
        if (token.isCancellationRequested) {
          cancelled = true;
          break;
        }
        progress.report({
          message: `${done + 1}/${pending.length} ${episodeBodyLabel(episode)}`,
        });

        // **話と話の間だけでなく、1話の途中でも止まるようにする。**
        // 1話ぶんの呼び出しに数十秒かかるので、上のループ先頭の判定だけ
        // では「押したのにその話が終わるまで止まらない」ことになる（0.28.3）
        const controller = new AbortController();
        token.onCancellationRequested(() => controller.abort());

        try {
          const response = await resolved.provider.generate({
            systemPrompt: SYNOPSIS_SYSTEM_PROMPT,
            userPrompt: buildSynopsisPrompt({
              chapterLabel: episodeBodyLabel(episode),
              chapterText: episode.body,
              previousSynopses: previousSynopsesFor(set, episode),
              characterNames: characterNames.slice(0, 100),
              needsSubtitle: needsSubtitle(episode),
              // サブタイトルを出させる回だけ、プロンプト側で使われる
              readerProfile,
            }),
            model: resolved.model,
            // あらすじは事実を並べるだけなので、揺らす必要がない
            temperature: SYNOPSIS_TEMPERATURE,
            maxOutputTokens: sendOutputTokens,
            plannedOutputTokens,
            jsonSchema: SYNOPSIS_SCHEMA as unknown as object,
            disableThinking: true,
            signal: controller.signal,
            meta: { feature: "synopsis", workFolder: work.folderPath },
          });

          const parsed = parseSynopsisResult(response.text);
          if (!parsed) {
            failures.push({
              label: episodeBodyLabel(episode),
              message: response.truncated
                ? "応答が出力上限で切り詰められました。"
                : "応答を読み取れませんでした。",
            });
            logFailure(`あらすじ生成（${episodeBodyLabel(episode)}）`, {
              理由: "応答を読み取れません",
              応答: responseExcerptForLog(response.text),
            });
            continue;
          }

          const validated = validateSynopsisResult(parsed);
          if (!validated.synopsis) {
            failures.push({
              label: episodeBodyLabel(episode),
              message: "あらすじが空でした。",
            });
            continue;
          }

          const result = upsertSynopsis(set, {
            chapter: episode.chapter,
            fileName: episode.file.fileName,
            title: episode.title,
            synopsis: validated.synopsis,
            sourceHash: episode.hash,
            model: resolved.model,
            // **作ったときと同じ版を控える。** 判定と食い違うと、
            // 次の実行で必ず作り直すか、二度と作り直さないかになる
            promptVersion: versionFor(episode),
            autoGenerated: true,
            authorNotes: "",
            emotion: validated.emotion,
            updatedAt: new Date().toISOString(),
          });
          set = result.set;

          for (const dropped of validated.rejectedSubtitles) {
            logStep(
              `サブタイトル案を却下（${episodeBodyLabel(episode)}）: ` +
                `「${dropped.text}」${describeSubtitleRejection(dropped.reason)}`
            );
          }
          if (needsSubtitle(episode) && validated.subtitles.length > 0) {
            subtitleCandidates.push({
              episode,
              suggestions: validated.subtitles,
            });
          }
        } catch (error) {
          const message =
            error instanceof AIError
              ? `${error.message} ${recoveryForAIError(error)}`
              : error instanceof Error
                ? error.message
                : String(error);
          failures.push({ label: episodeBodyLabel(episode), message });
          logFailure(`あらすじ生成（${episodeBodyLabel(episode)}）`, {
            種別: error instanceof AIError ? error.kind : "unknown",
            内容: message,
          });
        } finally {
          done++;
        }
      }
    }
  );

  // 途中で止めても、そこまでの結果は保存する。捨てると呼び出しが無駄になる
  try {
    await store.save(set);
  } catch (error) {
    reportStoreError(error);
    return false;
  }

  if (subtitleCandidates.length > 0 && !cancelled) {
    proposeSubtitles(subtitleCandidates, work.folderPath);
  }

  reportResult({
    total: pending.length,
    failures,
    cancelled,
  });
  return failures.length < pending.length;
}

/**
 * サブタイトルが後から付いた（＝ファイル名がリネームされた）話の
 * ファイル名・タイトルだけを、AIを呼ばずにその場で追随させる。
 *
 * **本文が変わっていなければ、あらすじの作り直しは走らない。**
 * `pending`の判定は本文のハッシュ・モデル・プロンプト版でしか見ておらず、
 * リネームだけでは「作り直しが要る話」に入らない。そのため、サブタイトル
 * 提案（`proposeSubtitles`）でファイル名を変えても、`chapter_synopses.json`
 * 側の`title`が古いまま取り残される（実機で発覚：本文は変えていないのに
 * 「第18話」のようにサブタイトルが表示されなくなっていた。2026-08-13）。
 *
 * AIを呼ばない軽い同期なので、`pending`が0件で終わる場合でも必ず行う。
 */
async function syncStaleFileNamesAndTitles(
  store: SynopsisStore,
  set: ChapterSynopsisSet,
  bodies: EpisodeBody[]
): Promise<ChapterSynopsisSet> {
  let changed = false;

  for (const episode of bodies) {
    const existing = findSynopsis(set, episode.file.fileName, episode.chapter);
    if (!existing || !existing.autoGenerated) continue;
    if (existing.sourceHash !== episode.hash) continue; // 内容が変わっていれば通常の作り直しに任せる
    if (existing.fileName === episode.file.fileName && existing.title === episode.title) {
      continue;
    }

    const result = upsertSynopsis(set, {
      ...existing,
      fileName: episode.file.fileName,
      title: episode.title,
    });
    set = result.set;
    changed = true;
  }

  if (!changed) return set;

  try {
    await store.save(set);
  } catch (error) {
    reportStoreError(error);
    // 保存できなくても、この回のあらすじ生成自体は続ける
  }
  return set;
}

/**
 * 直前の話のあらすじを文脈として渡す。
 *
 * 全話を渡すと本文が入らなくなるので、直前の数話だけにする。
 * **前話の出来事を持ち込ませないよう、プロンプト側でも釘を刺している。**
 */
function previousSynopsesFor(
  set: ChapterSynopsisSet,
  episode: EpisodeBody
): string[] {
  if (episode.chapter === null) return [];
  return set.episodes
    .filter((item) => item.chapter !== null && item.chapter < episode.chapter!)
    .slice(-PREVIOUS_SYNOPSES_LIMIT)
    .map((item) => `第${item.chapter}話: ${item.synopsis}`);
}

/**
 * サブタイトル案を見せて、選ばれたらファイル名を変える。
 *
 * **まとめて自動でリネームしない。** ファイル名は作者の作品の一部であり、
 * 外部ツールやGitの履歴にも影響する。1話ずつ選ばせる。
 */
function proposeSubtitles(
  candidates: Array<{ episode: EpisodeBody; suggestions: SubtitleSuggestion[] }>,
  workFolder: string
): void {
  /*
    **「確認する」が押されるのを待たない**（ノートPCの実機、2026-09-23）。
    ここで待つと、知らせを閉じるまで各話あらすじの「動いている」札を持った
    ままになり、結果の知らせ（何話作ったか）も閉じるまで出なかった。
    押されたら、そこから1話ずつ選ばせる。
  */
  whenNoticePicked(
    vscode.window.showInformationMessage(
      `サブタイトルの案が ${candidates.length} 話ぶんあります。確認しますか？`,
      "確認する",
      "あとで"
    ),
    async (start) => {
      if (start === "確認する") await reviewSubtitles(candidates);
    },
    { label: "サブタイトルの案", workFolder }
  );
}

/** サブタイトル案を1話ずつ選ばせ、選ばれたらファイル名を変える */
async function reviewSubtitles(
  candidates: Array<{ episode: EpisodeBody; suggestions: SubtitleSuggestion[] }>
): Promise<void> {
  for (const { episode, suggestions } of candidates) {
    const picked = await vscode.window.showQuickPick(
      [
        ...suggestions.map((suggestion) => ({
          label: suggestion.text,
          description: `${suggestion.text.length}字 / ${suggestion.kind}`,
          detail: suggestion.reason ?? undefined,
          suggestion,
        })),
        {
          label: "$(close) このままにする",
          description: "ファイル名を変えない",
          suggestion: undefined,
        },
        // 「このままにする」はこの話だけ。取りやめは残りも見ない
        cancelItem("やめる（残りも見ない）"),
      ],
      {
        title: `${episodeBodyLabel(episode)} のサブタイトル`,
        placeHolder: "選ぶとファイル名が変わります",
        ignoreFocusOut: true,
      }
    );
    // 取りやめ（Escも同じ）は残りも見ない。「このままにする」はこの話だけ
    if (!picked || isCancelItem(picked)) return;
    if (!("suggestion" in picked) || !picked.suggestion) continue;

    try {
      const renamed = await renameEpisodeFile(
        episode.file,
        picked.suggestion.text
      );
      logStep(
        `リネーム: ${episode.file.fileName} → ${path.basename(renamed)}`
      );
      notifyDone(
        `${episode.file.fileName} を ${path.basename(renamed)} に変えました。`
      );
    } catch (error) {
      logFailure(`リネーム（${episode.file.fileName}）`, {
        内容: error instanceof Error ? error.message : String(error),
      });
      vscode.window.showWarningMessage(
        `${episode.file.fileName} の名前を変えられませんでした: ${
          error instanceof Error ? error.message : String(error)
        }`
      );
    }
  }
}

function reportResult(result: {
  total: number;
  failures: Array<{ label: string; message: string }>;
  cancelled: boolean;
}): void {
  const succeeded = result.total - result.failures.length;
  const head = result.cancelled
    ? `中止しました。${succeeded} 話ぶんは保存しています。`
    : `${succeeded} 話のあらすじを作りました。`;

  if (result.failures.length === 0) {
    vscode.window.showInformationMessage(head);
    return;
  }

  const shown = result.failures
    .slice(0, 3)
    .map((failure) => `${failure.label}: ${failure.message}`)
    .join("\n");
  void warnWithLog(`${head}\n失敗 ${result.failures.length} 話\n${shown}`);
}

function reportStoreError(error: unknown): void {
  if (error instanceof SynopsisStoreError) {
    vscode.window.showErrorMessage(error.message);
    return;
  }
  vscode.window.showErrorMessage(
    `あらすじを保存できませんでした: ${
      error instanceof Error ? error.message : String(error)
    }`
  );
}
