import * as vscode from "vscode";
import * as path from "../core/paths";
import type { WorkEntry } from "../models/types";
import { AIRegistry, ensureConfigured } from "../ai/registry";
import { confirmProviderReachable } from "./aiConnectivity";
import { AIError, recoveryForAIError } from "../ai/types";
import { scanWork } from "../core/scanner";
import {
  episodeBodyLabel,
  loadEpisodeBodies,
  needsSubtitle,
  type EpisodeBody,
} from "../core/episodeBodies";
import { SynopsisStore, SynopsisStoreError } from "../core/synopsisStore";
import {
  findSynopsis,
  upsertSynopsis,
  type ChapterSynopsisSet,
} from "../models/synopsis";
import {
  describeSubtitleRejection,
  parseSynopsisResult,
  validateSynopsisResult,
} from "../core/synopsisValidation";
import {
  SYNOPSIS_SCHEMA,
  SYNOPSIS_SYSTEM_PROMPT,
  SYNOPSIS_VERSION,
  buildSynopsisPrompt,
  type SubtitleSuggestion,
} from "../prompts/synopsis";
import { CharacterStore } from "../core/characterStore";
import { withCancellableProgress } from "../views/progress";
import { logFailure, logStep, showLog, useLogFile } from "../core/logger";
import { renameEpisodeFile } from "../core/episodeRename";
import { confirmFormatFit } from "./formatFitPrompt";
import { cancelItem, isCancelItem } from "../views/dialogs";

/**
 * 各話あらすじの生成（P-07）と、サブタイトルの提案・リネーム。
 *
 * **話を単位にした初めての機能**である。設定抽出はチャンク単位で、
 * 話をまたいでまとめて送っていたが、あらすじは1話に1本作るため、
 * まとめずに1話ずつ送る。
 *
 * 作り直しの判断は「本文のハッシュ＋モデル名＋プロンプトの版」で行う。
 * 変わっていない話は呼ばない（設定抽出のキャッシュと同じ考え方）。
 */

/** 前話のあらすじを何件まで文脈として渡すか */
const PREVIOUS_SYNOPSES_LIMIT = 3;

export async function generateSynopses(
  work: WorkEntry,
  registry: AIRegistry
): Promise<boolean> {
  useLogFile(work.folderPath);

  // 短編では1件しか作れず、感情曲線も線にならない（設計書6.4.5）
  if (!(await confirmFormatFit(work, "episodeSynopses"))) return false;

  const resolved = await ensureConfigured(registry, "generate");
  if (!resolved) return false;

  const scan = await scanWork(work);
  if (scan.episodes.length === 0) {
    vscode.window.showWarningMessage("本文ファイルが見つかりません。");
    return false;
  }

  const loaded = await loadEpisodeBodies(scan.episodes);
  if (loaded.bodies.length === 0) {
    vscode.window.showWarningMessage("あらすじを作れる本文がありません。");
    return false;
  }

  const store = new SynopsisStore(work);
  let set: ChapterSynopsisSet;
  try {
    set = await store.load();
  } catch (error) {
    // 壊れたJSONを空として扱うと、作者が書き直したあらすじが消える
    reportStoreError(error);
    return false;
  }

  set = await syncStaleFileNamesAndTitles(store, set, loaded.bodies);

  // 作り直しが要る話だけを選ぶ
  const pending = loaded.bodies.filter((episode) => {
    const existing = findSynopsis(
      set,
      episode.file.fileName,
      episode.chapter
    );
    if (!existing) return true;
    if (!existing.autoGenerated) return false; // 作者が書いたものは触らない
    return (
      existing.sourceHash !== episode.hash ||
      existing.model !== resolved.model ||
      existing.promptVersion !== SYNOPSIS_VERSION
    );
  });

  if (pending.length === 0) {
    vscode.window.showInformationMessage(
      "すべての話のあらすじが最新です。本文を変えた話だけを作り直します。"
    );
    return true;
  }

  // **繋がるかを、費用の確認より先に確かめる**（設計書6.51）。
  // 繋がらないと分かっているのに料金の話をしても意味がない。
  // 置くのは「作り直しが要る話が1つも無い」で抜けたあと——
  // AIを1度も呼ばない回に起動を促しても、作者を迷わせるだけである
  // （`checkTypos.ts` が `pending.length > 0` のときだけ呼ぶのと同じ）。
  // モデル名を渡すのは、LM Studioをこの場から起こしたときの読み込みに要るため
  if (
    !(await confirmProviderReachable(
      resolved.provider,
      "各話あらすじの作成",
      resolved.model
    ))
  ) {
    return false;
  }

  const estimateMinutes = Math.ceil((pending.length * 15) / 60);
  const costNotice = resolved.provider.isPaid
    ? `\n${resolved.provider.displayName} は呼び出すたびに課金されます。`
    : "";
  const confirm = await vscode.window.showInformationMessage(
    `${loaded.bodies.length} 話中 ${pending.length} 話のあらすじを作ります` +
      `（変わっていない ${loaded.bodies.length - pending.length} 話はスキップ）。\n` +
      `モデル: ${resolved.model} / 目安 ${estimateMinutes} 分程度${costNotice}`,
    "実行",
    "中止"
  );
  if (confirm !== "実行") return false;

  // 人物名は表記を揃えるために渡す。モブは名前が普通名詞になりがちで、
  // あらすじの文中に混ざると読みにくい
  const characterNames = (await new CharacterStore(work).loadAll()).characters
    .filter((character) => !character.isMob)
    .map((character) => character.name);

  const failures: Array<{ label: string; message: string }> = [];
  const subtitleCandidates: Array<{
    episode: EpisodeBody;
    suggestions: SubtitleSuggestion[];
  }> = [];
  let done = 0;
  let cancelled = false;

  await withCancellableProgress(
    "あらすじを作っています",
    async (progress, token) => {
      for (const episode of pending) {
        if (token.isCancellationRequested) {
          cancelled = true;
          break;
        }
        progress.report({
          message: `${done + 1}/${pending.length} ${episodeBodyLabel(episode)}`,
        });

        // **話と話の間だけでなく、1話の途中でも止まるようにする。**
        // 1話ぶんの呼び出しに数十秒かかるので、上のループ先頭の判定だけ
        // では「押したのにその話が終わるまで止まらない」ことになる（0.28.3）
        const controller = new AbortController();
        token.onCancellationRequested(() => controller.abort());

        try {
          const response = await resolved.provider.generate({
            systemPrompt: SYNOPSIS_SYSTEM_PROMPT,
            userPrompt: buildSynopsisPrompt({
              chapterLabel: episodeBodyLabel(episode),
              chapterText: episode.body,
              previousSynopses: previousSynopsesFor(set, episode),
              characterNames: characterNames.slice(0, 100),
              needsSubtitle: needsSubtitle(episode),
            }),
            model: resolved.model,
            // あらすじは事実を並べるだけなので、揺らす必要がない
            temperature: 0.3,
            jsonSchema: SYNOPSIS_SCHEMA as unknown as object,
            disableThinking: true,
            signal: controller.signal,
            meta: { feature: "synopsis", workFolder: work.folderPath },
          });

          const parsed = parseSynopsisResult(response.text);
          if (!parsed) {
            failures.push({
              label: episodeBodyLabel(episode),
              message: response.truncated
                ? "応答が出力上限で切り詰められました。"
                : "応答を読み取れませんでした。",
            });
            logFailure(`あらすじ生成（${episodeBodyLabel(episode)}）`, {
              理由: "応答を読み取れません",
              応答: response.text.slice(0, 400),
            });
            continue;
          }

          const validated = validateSynopsisResult(parsed);
          if (!validated.synopsis) {
            failures.push({
              label: episodeBodyLabel(episode),
              message: "あらすじが空でした。",
            });
            continue;
          }

          const result = upsertSynopsis(set, {
            chapter: episode.chapter,
            fileName: episode.file.fileName,
            title: episode.title,
            synopsis: validated.synopsis,
            sourceHash: episode.hash,
            model: resolved.model,
            promptVersion: SYNOPSIS_VERSION,
            autoGenerated: true,
            authorNotes: "",
            emotion: validated.emotion,
            updatedAt: new Date().toISOString(),
          });
          set = result.set;

          for (const dropped of validated.rejectedSubtitles) {
            logStep(
              `サブタイトル案を却下（${episodeBodyLabel(episode)}）: ` +
                `「${dropped.text}」${describeSubtitleRejection(dropped.reason)}`
            );
          }
          if (needsSubtitle(episode) && validated.subtitles.length > 0) {
            subtitleCandidates.push({
              episode,
              suggestions: validated.subtitles,
            });
          }
        } catch (error) {
          const message =
            error instanceof AIError
              ? `${error.message} ${recoveryForAIError(error)}`
              : error instanceof Error
                ? error.message
                : String(error);
          failures.push({ label: episodeBodyLabel(episode), message });
          logFailure(`あらすじ生成（${episodeBodyLabel(episode)}）`, {
            種別: error instanceof AIError ? error.kind : "unknown",
            内容: message,
          });
        } finally {
          done++;
        }
      }
    }
  );

  // 途中で止めても、そこまでの結果は保存する。捨てると呼び出しが無駄になる
  try {
    await store.save(set);
  } catch (error) {
    reportStoreError(error);
    return false;
  }

  if (subtitleCandidates.length > 0 && !cancelled) {
    await proposeSubtitles(subtitleCandidates);
  }

  reportResult({
    total: pending.length,
    failures,
    cancelled,
  });
  return failures.length < pending.length;
}

/**
 * サブタイトルが後から付いた（＝ファイル名がリネームされた）話の
 * ファイル名・タイトルだけを、AIを呼ばずにその場で追随させる。
 *
 * **本文が変わっていなければ、あらすじの作り直しは走らない。**
 * `pending`の判定は本文のハッシュ・モデル・プロンプト版でしか見ておらず、
 * リネームだけでは「作り直しが要る話」に入らない。そのため、サブタイトル
 * 提案（`proposeSubtitles`）でファイル名を変えても、`chapter_synopses.json`
 * 側の`title`が古いまま取り残される（実機で発覚：本文は変えていないのに
 * 「第18話」のようにサブタイトルが表示されなくなっていた。2026-08-13）。
 *
 * AIを呼ばない軽い同期なので、`pending`が0件で終わる場合でも必ず行う。
 */
async function syncStaleFileNamesAndTitles(
  store: SynopsisStore,
  set: ChapterSynopsisSet,
  bodies: EpisodeBody[]
): Promise<ChapterSynopsisSet> {
  let changed = false;

  for (const episode of bodies) {
    const existing = findSynopsis(set, episode.file.fileName, episode.chapter);
    if (!existing || !existing.autoGenerated) continue;
    if (existing.sourceHash !== episode.hash) continue; // 内容が変わっていれば通常の作り直しに任せる
    if (existing.fileName === episode.file.fileName && existing.title === episode.title) {
      continue;
    }

    const result = upsertSynopsis(set, {
      ...existing,
      fileName: episode.file.fileName,
      title: episode.title,
    });
    set = result.set;
    changed = true;
  }

  if (!changed) return set;

  try {
    await store.save(set);
  } catch (error) {
    reportStoreError(error);
    // 保存できなくても、この回のあらすじ生成自体は続ける
  }
  return set;
}

/**
 * 直前の話のあらすじを文脈として渡す。
 *
 * 全話を渡すと本文が入らなくなるので、直前の数話だけにする。
 * **前話の出来事を持ち込ませないよう、プロンプト側でも釘を刺している。**
 */
function previousSynopsesFor(
  set: ChapterSynopsisSet,
  episode: EpisodeBody
): string[] {
  if (episode.chapter === null) return [];
  return set.episodes
    .filter((item) => item.chapter !== null && item.chapter < episode.chapter!)
    .slice(-PREVIOUS_SYNOPSES_LIMIT)
    .map((item) => `第${item.chapter}話: ${item.synopsis}`);
}

/**
 * サブタイトル案を見せて、選ばれたらファイル名を変える。
 *
 * **まとめて自動でリネームしない。** ファイル名は作者の作品の一部であり、
 * 外部ツールやGitの履歴にも影響する。1話ずつ選ばせる。
 */
async function proposeSubtitles(
  candidates: Array<{ episode: EpisodeBody; suggestions: SubtitleSuggestion[] }>
): Promise<void> {
  const start = await vscode.window.showInformationMessage(
    `サブタイトルの案が ${candidates.length} 話ぶんあります。確認しますか？`,
    "確認する",
    "あとで"
  );
  if (start !== "確認する") return;

  for (const { episode, suggestions } of candidates) {
    const picked = await vscode.window.showQuickPick(
      [
        ...suggestions.map((suggestion) => ({
          label: suggestion.text,
          description: `${suggestion.text.length}字 / ${suggestion.kind}`,
          detail: suggestion.reason ?? undefined,
          suggestion,
        })),
        {
          label: "$(close) このままにする",
          description: "ファイル名を変えない",
          suggestion: undefined,
        },
        // 「このままにする」はこの話だけ。取りやめは残りも見ない
        cancelItem("やめる（残りも見ない）"),
      ],
      {
        title: `${episodeBodyLabel(episode)} のサブタイトル`,
        placeHolder: "選ぶとファイル名が変わります",
        ignoreFocusOut: true,
      }
    );
    // 取りやめ（Escも同じ）は残りも見ない。「このままにする」はこの話だけ
    if (!picked || isCancelItem(picked)) return;
    if (!("suggestion" in picked) || !picked.suggestion) continue;

    try {
      const renamed = await renameEpisodeFile(
        episode.file,
        picked.suggestion.text
      );
      logStep(
        `リネーム: ${episode.file.fileName} → ${path.basename(renamed)}`
      );
      vscode.window.showInformationMessage(
        `${episode.file.fileName} を ${path.basename(renamed)} に変えました。`
      );
    } catch (error) {
      logFailure(`リネーム（${episode.file.fileName}）`, {
        内容: error instanceof Error ? error.message : String(error),
      });
      vscode.window.showWarningMessage(
        `${episode.file.fileName} の名前を変えられませんでした: ${
          error instanceof Error ? error.message : String(error)
        }`
      );
    }
  }
}

function reportResult(result: {
  total: number;
  failures: Array<{ label: string; message: string }>;
  cancelled: boolean;
}): void {
  const succeeded = result.total - result.failures.length;
  const head = result.cancelled
    ? `中止しました。${succeeded} 話ぶんは保存しています。`
    : `${succeeded} 話のあらすじを作りました。`;

  if (result.failures.length === 0) {
    vscode.window.showInformationMessage(head);
    return;
  }

  const shown = result.failures
    .slice(0, 3)
    .map((failure) => `${failure.label}: ${failure.message}`)
    .join("\n");
  vscode.window
    .showWarningMessage(
      `${head}\n失敗 ${result.failures.length} 話\n${shown}`,
      "ログを見る"
    )
    .then((answer) => {
      if (answer === "ログを見る") showLog();
    });
}

function reportStoreError(error: unknown): void {
  if (error instanceof SynopsisStoreError) {
    vscode.window.showErrorMessage(error.message);
    return;
  }
  vscode.window.showErrorMessage(
    `あらすじを保存できませんでした: ${
      error instanceof Error ? error.message : String(error)
    }`
  );
}
