import * as vscode from "vscode";
import { WorkEntry } from "../models/types";
import type { Character } from "../models/character";
import type { Ability, AbilitySystem } from "../models/ability";
import type { Location } from "../models/location";
import { membersOf, type Organization } from "../models/organization";
import {
  WORLD_CATEGORIES,
  WORLD_CATEGORY_LABELS,
  type WorldItem,
} from "../models/world";
import type { AiNote, AiNoteSource } from "../models/aiNote";
import { CharacterStore } from "../core/characterStore";
import {
  AbilitySystemStore,
  createAbilityStore,
  createLocationStore,
  createOrganizationStore,
  createWorldStore,
} from "../core/abilityStore";
import type { SettingsStore } from "../core/settingsStore";
import {
  applyAbilityEdits,
  applyCharacterEdits,
  applyLocationEdits,
  applyOrganizationEdits,
  applyWorldItemEdits,
  appendAiNote,
  removeAiNote,
  toRecordEdits,
  CUSTOM_FIELD_PREFIX,
  SettingsEditError,
  type EditOptions,
  type RecordEdits,
} from "../core/settingsEdit";
import {
  describeAbility,
  describeCharacter,
  describeLocation,
  describeOrganization,
  describeWorldItem,
  KIND_LABELS,
  type SettingsKind,
} from "../core/settingsSummary";
import {
  describeConflictValues,
  formatChapters,
} from "../core/settingsMarkdown";
import type { RecordConflict } from "../models/jsonValidation";
import {
  buildAbilityListItems,
  buildCharacterListItems,
  buildLocationListItems,
  buildOrganizationListItems,
  buildWorldListItems,
  type SettingsListItem,
} from "../core/settingsList";
import {
  collectMentionExcerpts,
  EXCERPT_MAX_CHARS,
  type ExcerptSource,
  type MentionExcerpt,
} from "../core/mentionExcerpts";
import { decideContextSize } from "../core/chunker";
import { resolveMaxOutputTokens } from "../ai/outputLimit";
import { loadExcerptSources } from "../core/manuscriptSources";
import { expandNameVariants } from "../core/termIndex";
import { evidencePhrases } from "../core/groundedEvidence";
import { AIRegistry, ensureConfigured } from "../ai/registry";
import { AIError, recoveryForAIError } from "../ai/types";
import {
  buildSettingsChatPrompt,
  SETTINGS_ASSISTANT_SYSTEM_PROMPT,
  type ChatTurn,
} from "../prompts/settingsChat";
import {
  buildEnrichPrompt,
  buildEnrichSchema,
  enrichableFields,
  type EnrichableField,
} from "../prompts/settingsEnrich";
import { isMeaningfulValue } from "../core/characterExtractionValidation";
import { CustomFieldStore } from "../core/customFieldStore";
import type { CustomFieldDefinition } from "../models/customField";
import { clampSummary, SUMMARY_MAX_CHARS } from "../core/summaryLimit";
import { buildSettingsPanelHtml } from "../views/settingsPanelHtml";
import { renderMarkdownLite } from "../core/markdownLite";
import { withCancellableProgress } from "../views/progress";
import { logFailure } from "../core/logger";

/**
 * 設定資料パネル。
 *
 * 資料を読むだけでなく、その場で直せて、AIに掘り下げさせられるようにする。
 * JSONを直接開いて編集するより間違えにくく、
 * 「どの項目を触ってよいか」が画面から分かる。
 *
 * **AIが書いたものは作者が承認するまで保存しない。**
 * 掘り下げは本文の逐語照合ができない解釈であり、
 * 抽出結果と同じ扱いで自動保存すると、
 * どこまでが本文に書いてあることなのか分からなくなるため。
 */

/** パネルが扱う設定レコード。種別が増えるたびに union を書き足さないための別名 */
type SettingsRecord = Character | Ability | Organization | Location | WorldItem;

/** 作品ごとに1枚だけ開く。同じ作品で何枚も開いても混乱するだけ */
const openPanels = new Map<string, SettingsPanel>();

export async function openSettingsPanel(
  context: vscode.ExtensionContext,
  work: WorkEntry,
  registry: AIRegistry,
  options: { beside?: boolean } = {}
): Promise<SettingsPanel> {
  const existing = openPanels.get(work.id);
  if (existing) {
    existing.reveal(options.beside);
    return existing;
  }
  const panel = new SettingsPanel(context, work, registry, options.beside);
  openPanels.set(work.id, panel);
  await panel.initialize();
  return panel;
}

/** 開いていれば返す。本文のクリックに追従させるために使う */
export function findOpenSettingsPanel(
  workId: string
): SettingsPanel | undefined {
  return openPanels.get(workId);
}

interface DetailField {
  /** 作者が足した項目は `custom:` を付けて区別する */
  key: string;
  label: string;
  value: string;
  multiline: boolean;
  /**
   * チェックボックスで見せる項目。
   * 値は入なら "1"、切なら空文字で受け渡す。
   */
  check?: boolean;
  /** 決まった値から選ぶ項目。画面では選択肢として出す */
  choices?: Array<{ value: string; label: string }>;
}

/** 世界観の分類。画面には日本語の見出しを出し、保存するのは英字のキー */
const WORLD_CATEGORY_CHOICES = WORLD_CATEGORIES.map((category) => ({
  value: category,
  label: WORLD_CATEGORY_LABELS[category],
}));

interface DetailView {
  kind: SettingsKind;
  id: string;
  name: string;
  autoGenerated: boolean;
  /** 名前のすぐ下に出す要点。登場話・食い違いなど、作者が毎回見るもの */
  readOnly: Array<{ label: string; value: string }>;
  fields: DetailField[];
  /**
   * 画面のいちばん下へ回す参考情報。
   *
   * 抽出根拠は「AIがどこを見てそう書いたか」の記録で、
   * 疑わしいときにだけ読むものである。名前の直下に置くと、
   * 毎回読む項目（登場話や編集欄）が押し下げられて読みにくい。
   */
  reference: Array<{ label: string; value: string }>;
  /** html は整形済み。画面側でそのまま挿入する */
  aiNotes: Array<AiNote & { html: string }>;
}

/** メモをそのまま渡さず、整形したHTMLを添える */
function withRenderedNotes(notes: AiNote[]): Array<AiNote & { html: string }> {
  return notes.map((note) => ({ ...note, html: renderMarkdownLite(note.text) }));
}

export class SettingsPanel {
  private readonly panel: vscode.WebviewPanel;
  private readonly characterStore: CharacterStore;
  private readonly abilityStore: SettingsStore<Ability>;
  private readonly locationStore: SettingsStore<Location>;
  private readonly organizationStore: SettingsStore<Organization>;
  private readonly worldStore: SettingsStore<WorldItem>;
  private readonly systemStore: AbilitySystemStore;
  private readonly customFieldStore: CustomFieldStore;

  private characters: Character[] = [];
  private abilities: Ability[] = [];
  private locations: Location[] = [];
  private organizations: Organization[] = [];
  private worldItems: WorldItem[] = [];
  private abilitySystem: AbilitySystem | undefined;
  private customFields: CustomFieldDefinition[] = [];
  private loadErrors: Array<{ file: string; message: string }> = [];

  /** 本文は重いので一度読んだら使い回す。パネルを閉じるまで有効 */
  private excerptSources: ExcerptSource[] | undefined;
  /** 選択中のレコードごとのやり取り。保存はしない */
  private readonly chatHistory = new Map<string, ChatTurn[]>();

  constructor(
    context: vscode.ExtensionContext,
    private readonly work: WorkEntry,
    private readonly registry: AIRegistry,
    beside = false
  ) {
    this.characterStore = new CharacterStore(work);
    this.abilityStore = createAbilityStore(work);
    this.locationStore = createLocationStore(work);
    this.organizationStore = createOrganizationStore(work);
    this.worldStore = createWorldStore(work);
    this.systemStore = new AbilitySystemStore(work);
    this.customFieldStore = new CustomFieldStore(work);

    this.panel = vscode.window.createWebviewPanel(
      "novelai.settings",
      `設定資料: ${work.title}`,
      // 本文の右側に並べる。本文を読みながら設定を見られるようにするため
      beside
        ? { viewColumn: vscode.ViewColumn.Beside, preserveFocus: true }
        : vscode.ViewColumn.Active,
      { enableScripts: true, retainContextWhenHidden: true }
    );
    context.subscriptions.push(this.panel);

    this.panel.onDidDispose(() => openPanels.delete(work.id));
    this.panel.webview.onDidReceiveMessage((message: unknown) => {
      void this.handleMessage(message as PanelMessage);
    });
  }

  reveal(beside = false): void {
    // preserveFocus を立てるのは、本文を書きながら見るときに
    // カーソルが資料側へ飛ばないようにするため
    this.panel.reveal(
      beside ? vscode.ViewColumn.Beside : undefined,
      beside
    );
  }

  get workId(): string {
    return this.work.id;
  }

  /**
   * 外から特定の1件を選ばせる。本文中の用語をクリックしたときに使う。
   * 一覧の選択状態も合わせるため、画面側で種別タブごと切り替える。
   */
  showRecord(kind: SettingsKind, id: string): void {
    const detail = this.detailOf(kind, id);
    if (!detail) return;
    this.post({ type: "focus", kind, id, detail });
  }

  async initialize(): Promise<void> {
    const nonce = createNonce();
    this.panel.webview.html = buildSettingsPanelHtml(
      nonce,
      this.panel.webview.cspSource
    );
    await this.loadAll();
  }

  private async loadAll(): Promise<void> {
    const loadedCharacters = await this.characterStore.loadAll();
    const loadedAbilities = await this.abilityStore.loadAll();
    const loadedLocations = await this.locationStore.loadAll();
    const loadedOrganizations = await this.organizationStore.loadAll();
    const loadedWorld = await this.worldStore.loadAll();

    this.characters = loadedCharacters.characters;
    this.abilities = loadedAbilities.records;
    this.locations = loadedLocations.records;
    this.organizations = loadedOrganizations.records;
    this.worldItems = loadedWorld.records;
    this.loadErrors = [
      ...loadedCharacters.errors,
      ...loadedAbilities.errors,
      ...loadedLocations.errors,
      ...loadedOrganizations.errors,
      ...loadedWorld.errors,
    ];

    // 能力体系が壊れていても、人物と場所は読めるので画面は出す
    try {
      this.abilitySystem = await this.systemStore.load();
    } catch {
      this.abilitySystem = undefined;
    }

    // 項目の定義が読めなくても、既定の項目は編集できる。
    // 直し方は「一覧に項目を増やす」で伝えるので、ここでは黙って空にする
    this.customFields = await this.customFieldStore.loadFields();

    this.post({ type: "init", groups: this.groups(), notice: this.notice() });
  }

  private notice(): string {
    if (this.loadErrors.length === 0) return "";
    // 壊れたJSONは勝手に直さない。何が読めていないかだけ伝える
    return `読み込めない設定ファイルが ${this.loadErrors.length} 件あります（${this.loadErrors
      .map((error) => error.file)
      .join("、")}）。その項目は一覧に出ていません。`;
  }

  private groups(): Record<SettingsKind, SettingsListItem[]> {
    return {
      character: buildCharacterListItems(this.characters),
      ability: buildAbilityListItems(this.abilities),
      organization: buildOrganizationListItems(
        this.organizations,
        this.characters
      ),
      location: buildLocationListItems(this.locations),
      world: buildWorldListItems(this.worldItems),
    };
  }

  private find(
    kind: SettingsKind,
    id: string
  ): SettingsRecord | undefined {
    if (kind === "character") {
      return this.characters.find((item) => item.id === id);
    }
    if (kind === "ability") return this.abilities.find((item) => item.id === id);
    if (kind === "organization") {
      return this.organizations.find((item) => item.id === id);
    }
    if (kind === "world") return this.worldItems.find((item) => item.id === id);
    return this.locations.find((item) => item.id === id);
  }

  private detailOf(kind: SettingsKind, id: string): DetailView | undefined {
    const record = this.find(kind, id);
    if (!record) return undefined;

    if (kind === "character") {
      const character = record as Character;
      return {
        kind,
        id,
        name: character.name,
        autoGenerated: character.autoGenerated,
        readOnly: [
          { label: "登場話", value: formatChapters(character.appearedChapters) },
          { label: "一人称", value: character.firstPerson.default ?? "" },
        ].filter((entry) => entry.value),
        reference: referenceLines(character.conflicts, character.evidence),
        fields: [
          field("name", "名前", character.name),
          // 紹介は文章なので、1行の入力欄では書いた内容が隠れる
          field(
            "summary",
            `紹介（${SUMMARY_MAX_CHARS}字以内）`,
            character.summary,
            true
          ),
          field("gender", "性別", character.gender),
          field("affiliation", "所属", character.affiliation),
          field("reading", "読み", character.reading),
          field("aliases", "別名（読点区切り）", character.aliases.join("、")),
          field("role", "役割", character.role),
          field("personality", "性格", character.personality, true),
          field("appearance", "外見", character.appearance, true),
          // AIの判定を作者が直せるようにする。外れていると、その人物は
          // 一覧の下へ回り、用語ハイライトとIME辞書からも消えたままになる
          checkField(
            "isMob",
            "モブ・集団として扱う（一覧の下へまとめ、ハイライトと辞書から外す）",
            character.isMob
          ),
          // 作者が足した項目は、既定の項目のあと・メモの前に並べる
          ...customFieldControls(character, this.customFields),
          field("authorNotes", "作者メモ", character.authorNotes, true),
          field("exportNote", "資料用の補足", character.exportNote, true),
        ],
        aiNotes: withRenderedNotes(character.aiNotes),
      };
    }

    if (kind === "ability") {
      const ability = record as Ability;
      return {
        kind,
        id,
        name: ability.name,
        autoGenerated: ability.autoGenerated,
        readOnly: [
          { label: "使い手", value: ability.userNames.join("、") },
          { label: "登場話", value: formatChapters(ability.appearedChapters) },
        ].filter((entry) => entry.value),
        reference: referenceLines(ability.conflicts, ability.evidence),
        fields: [
          field("name", "名前", ability.name),
          field(
            "summary",
            `紹介（${SUMMARY_MAX_CHARS}字以内）`,
            ability.summary,
            true
          ),
          field("reading", "読み", ability.reading),
          field("aliases", "別名（読点区切り）", ability.aliases.join("、")),
          field("category", "分類", ability.category),
          field("description", "説明", ability.description, true),
          field("cost", "代償", ability.cost, true),
          field("limitation", "制約", ability.limitation, true),
          field("authorNotes", "作者メモ", ability.authorNotes, true),
          field("exportNote", "資料用の補足", ability.exportNote, true),
        ],
        aiNotes: withRenderedNotes(ability.aiNotes),
      };
    }

    if (kind === "organization") {
      const organization = record as Organization;
      // 所属は人物側にしかない。組織だけ見ても誰がいるか分からないので引く
      const members = membersOf(organization, this.characters);
      return {
        kind,
        id,
        name: organization.name,
        autoGenerated: organization.autoGenerated,
        readOnly: [
          { label: "所属する人物", value: members.join("、") },
          {
            label: "登場話",
            value: formatChapters(organization.appearedChapters),
          },
        ].filter((entry) => entry.value),
        reference: referenceLines(organization.conflicts, organization.evidence),
        fields: [
          field("name", "名前", organization.name),
          field(
            "summary",
            `紹介（${SUMMARY_MAX_CHARS}字以内）`,
            organization.summary,
            true
          ),
          field("reading", "読み", organization.reading),
          field(
            "aliases",
            "別名（読点区切り）",
            organization.aliases.join("、")
          ),
          field("category", "種別", organization.category),
          field("parent", "上位組織", organization.parent),
          field("description", "説明", organization.description, true),
          field("authorNotes", "作者メモ", organization.authorNotes, true),
          field("exportNote", "資料用の補足", organization.exportNote, true),
        ],
        aiNotes: withRenderedNotes(organization.aiNotes),
      };
    }

    if (kind === "world") {
      const item = record as WorldItem;
      return {
        kind,
        id,
        name: item.name,
        autoGenerated: item.autoGenerated,
        readOnly: [
          { label: "登場話", value: formatChapters(item.appearedChapters) },
        ].filter((entry) => entry.value),
        reference: referenceLines(item.conflicts, item.evidence),
        fields: [
          field("name", "見出し（15字以内）", item.name),
          // 分類は決まった7種。自由入力にすると綴りの揺れで
          // 資料の節が増え、読み込み時の検証でも落ちる
          choiceField("category", "分類", item.category, WORLD_CATEGORY_CHOICES),
          field(
            "aliases",
            "別の言い方（読点区切り）",
            item.aliases.join("、")
          ),
          field("description", "内容", item.description, true),
          field("authorNotes", "作者メモ", item.authorNotes, true),
          field("exportNote", "資料用の補足", item.exportNote, true),
        ],
        aiNotes: withRenderedNotes(item.aiNotes),
      };
    }

    const location = record as Location;
    return {
      kind,
      id,
      name: location.name,
      autoGenerated: location.autoGenerated,
      readOnly: [
        { label: "登場話", value: formatChapters(location.appearedChapters) },
      ].filter((entry) => entry.value),
      reference: referenceLines(location.conflicts, location.evidence),
      fields: [
        field("name", "名前", location.name),
        field(
            "summary",
            `紹介（${SUMMARY_MAX_CHARS}字以内）`,
            location.summary,
            true
          ),
        field("reading", "読み", location.reading),
        field("aliases", "別名（読点区切り）", location.aliases.join("、")),
        field("region", "地域", location.region),
        field("description", "説明", location.description, true),
        field("authorNotes", "作者メモ", location.authorNotes, true),
        field("exportNote", "資料用の補足", location.exportNote, true),
      ],
      aiNotes: withRenderedNotes(location.aiNotes),
    };
  }

  private async handleMessage(message: PanelMessage): Promise<void> {
    try {
      switch (message.type) {
        case "ready":
          this.post({
            type: "init",
            groups: this.groups(),
            notice: this.notice(),
          });
          return;
        case "select":
          this.postDetail(message.kind, message.id);
          return;
        case "save":
          await this.handleSave(message.kind, message.id, message.edits);
          return;
        case "enrich":
          await this.handleEnrich(message.kind, message.id);
          return;
        case "applyProposal":
          await this.handleApplyProposal(message);
          return;
        case "approveNote":
          await this.handleApproveNote(message);
          return;
        case "deleteNote":
          await this.handleDeleteNote(message.kind, message.id, message.noteId);
          return;
        case "chat":
          await this.handleChat(message.kind, message.id, message.question);
          return;
      }
    } catch (error) {
      this.setBusy(false);
      this.post({ type: "error", message: describeError(error) });
    }
  }

  private postDetail(kind: SettingsKind, id: string): void {
    const detail = this.detailOf(kind, id);
    if (!detail) {
      this.post({ type: "error", message: "選択した設定が見つかりません。" });
      return;
    }
    this.post({ type: "detail", detail });
  }

  private async handleSave(
    kind: SettingsKind,
    id: string,
    edits: Record<string, string>
  ): Promise<void> {
    const record = this.find(kind, id);
    if (!record) {
      this.post({ type: "error", message: "選択した設定が見つかりません。" });
      return;
    }

    const updated = this.applyEdits(kind, record, toRecordEdits(edits));
    await this.persist(kind, updated);
    await this.reloadAfterSave(kind, id, "保存しました。");
  }

  private applyEdits(
    kind: SettingsKind,
    record: SettingsRecord,
    edits: RecordEdits,
    options?: EditOptions
  ): SettingsRecord {
    if (kind === "character") {
      return applyCharacterEdits(record as Character, edits, options);
    }
    if (kind === "ability") {
      return applyAbilityEdits(record as Ability, edits, options);
    }
    if (kind === "organization") {
      return applyOrganizationEdits(record as Organization, edits, options);
    }
    if (kind === "world") {
      return applyWorldItemEdits(record as WorldItem, edits, options);
    }
    return applyLocationEdits(record as Location, edits, options);
  }

  private async persist(
    kind: SettingsKind,
    record: SettingsRecord
  ): Promise<void> {
    if (kind === "character") {
      // 既存ファイルは上書きできないため、退避してから作り直す必要がある。
      // save() を直接呼ぶと保存が必ず失敗する
      await this.characterStore.saveOrUpdate(record as Character);
      return;
    }
    if (kind === "ability") {
      await this.abilityStore.saveAll([record as Ability]);
      return;
    }
    if (kind === "organization") {
      await this.organizationStore.saveAll([record as Organization]);
      return;
    }
    if (kind === "world") {
      await this.worldStore.saveAll([record as WorldItem]);
      return;
    }
    await this.locationStore.saveAll([record as Location]);
  }

  /**
   * 保存後は読み直す。
   * ストアが持つハッシュと画面の内容がずれると、
   * 次の保存が「外部で変更された」と誤検出されるため。
   */
  private async reloadAfterSave(
    kind: SettingsKind,
    id: string,
    notice: string
  ): Promise<void> {
    await this.loadAll();
    const detail = this.detailOf(kind, id);
    this.post({
      type: "saved",
      detail,
      groups: this.groups(),
      notice,
    });
  }

  /**
   * 各項目に入れる値をAIに提案させる。
   *
   * 掘り下げ（文章のメモ）と違い、設定資料の項目そのものを埋めるためのもの。
   * **提案は保存しない。** 項目ごとに現在の値と並べて見せ、
   * 作者が選んだものだけを書き込む。
   */
  private async handleEnrich(kind: SettingsKind, id: string): Promise<void> {
    const record = this.find(kind, id);
    if (!record) {
      this.post({ type: "error", message: "選択した設定が見つかりません。" });
      return;
    }

    const resolved = await ensureConfigured(this.registry);
    if (!resolved) return;

    const excerpts = await this.excerptsFor(kind, record);
    const prompt = buildEnrichPrompt({
      workTitle: this.work.title,
      kind,
      target: {
        kindLabel: KIND_LABELS[kind],
        name: record.name,
        currentSettings: this.describe(kind, record),
      },
      excerpts,
      customFields: this.customFields,
    });

    const text = await this.generate(
      prompt,
      `「${record.name}」の項目を充実させています`,
      buildEnrichSchema(kind, this.customFields)
    );
    if (text === undefined) return;

    const parsed = parseEnrichResult(text);
    if (!parsed) {
      this.post({
        type: "error",
        message:
          "AIの応答をJSONとして解析できませんでした。もう一度試してください。",
      });
      return;
    }

    const current = record as unknown as Record<string, unknown>;
    const proposals: FieldProposal[] = [];
    for (const field of enrichableFields(kind, this.customFields)) {
      const proposed = clampField(field, parsed[field.key]);
      if (!proposed) continue;
      // 追加項目の値は customFields の中にある
      const before = field.custom
        ? (record as Character).customFields[field.key] ?? ""
        : asText(current[field.key]);
      if (before === proposed) continue;
      proposals.push({
        // 反映するときに、既定の項目と同じ経路で書き戻せるようにする
        key: field.custom ? `${CUSTOM_FIELD_PREFIX}${field.key}` : field.key,
        label: field.label,
        before,
        after: proposed,
        multiline: field.multiline === true,
        // 空欄を埋める提案だけを既定で選ぶ。
        // 作者が書いた内容の置き換えは、必ず自分で選んでもらう
        selected: before.length === 0,
      });
    }

    if (proposals.length === 0) {
      this.post({
        type: "error",
        message:
          "本文から新しく書ける内容は見つかりませんでした。抜粋の範囲に手掛かりが無いようです。",
      });
      return;
    }

    this.post({ type: "proposal", kind, id, proposals, model: resolved.model });
  }

  /** 作者が選んだ項目だけを書き込む */
  private async handleApplyProposal(
    message: ApplyProposalMessage
  ): Promise<void> {
    const record = this.find(message.kind, message.id);
    if (!record) {
      this.post({ type: "error", message: "選択した設定が見つかりません。" });
      return;
    }

    const edits = toRecordEdits(message.values);

    // AIの提案を採用しただけなので、作者が確定させた記述としては扱わない。
    // 作者確定にすると、その人物は以後の抽出から締め出されてしまう
    const updated = this.applyEdits(message.kind, record, edits, {
      authorConfirmed: false,
    });
    await this.persist(message.kind, updated);
    await this.reloadAfterSave(
      message.kind,
      message.id,
      `${Object.keys(message.values).length} 項目を反映しました。` +
        "この内容は以後の抽出で更新されることがあります。"
    );
  }

  private async handleChat(
    kind: SettingsKind,
    id: string,
    question: string
  ): Promise<void> {
    const record = this.find(kind, id);
    if (!record) {
      this.post({ type: "error", message: "選択した設定が見つかりません。" });
      return;
    }

    const resolved = await ensureConfigured(this.registry);
    if (!resolved) return;

    const key = `${kind}:${id}`;
    const history = this.chatHistory.get(key) ?? [];
    const excerpts = await this.excerptsFor(kind, record);

    const prompt = buildSettingsChatPrompt({
      workTitle: this.work.title,
      target: {
        kindLabel: KIND_LABELS[kind],
        name: record.name,
        currentSettings: this.describe(kind, record),
      },
      question,
      excerpts,
      history,
    });

    const text = await this.generate(prompt, `「${record.name}」について調べています`);
    if (text === undefined) return;

    this.chatHistory.set(key, [
      ...history,
      { role: "author", text: question },
      { role: "assistant", text },
    ]);
    // AIはMarkdownで返してくる。記号のまま見せないよう整形して渡す
    this.post({
      type: "chatAnswer",
      text,
      html: renderMarkdownLite(text),
      question,
      model: resolved.model,
    });
  }

  private async handleApproveNote(message: ApproveNoteMessage): Promise<void> {
    const record = this.find(message.kind, message.id);
    if (!record) {
      this.post({ type: "error", message: "選択した設定が見つかりません。" });
      return;
    }

    const resolved = this.registry.resolve();
    const updated = appendAiNote(record, {
      topic: message.topic,
      text: message.text,
      model: resolved?.model ?? "",
      source: message.source,
    });
    await this.persist(message.kind, updated as SettingsRecord);
    await this.reloadAfterSave(message.kind, message.id, "掘り下げを追記しました。");
  }

  private async handleDeleteNote(
    kind: SettingsKind,
    id: string,
    noteId: string
  ): Promise<void> {
    const record = this.find(kind, id);
    if (!record) return;
    const updated = removeAiNote(record, noteId);
    await this.persist(kind, updated as SettingsRecord);
    await this.reloadAfterSave(kind, id, "掘り下げを削除しました。");
  }

  private describe(
    kind: SettingsKind,
    record: SettingsRecord
  ): string {
    if (kind === "character") {
      return describeCharacter(record as Character, this.customFields);
    }
    if (kind === "ability") {
      return describeAbility(record as Ability, this.abilitySystem);
    }
    if (kind === "organization") {
      const organization = record as Organization;
      return describeOrganization(
        organization,
        membersOf(organization, this.characters)
      );
    }
    if (kind === "world") return describeWorldItem(record as WorldItem);
    return describeLocation(record as Location);
  }

  /** その設定が出てくる場面を本文から集める */
  private async excerptsFor(
    kind: SettingsKind,
    record: SettingsRecord
  ): Promise<MentionExcerpt[]> {
    if (!this.excerptSources) {
      const loaded = await withCancellableProgress(
        "本文を読み込んでいます",
        async () => loadExcerptSources(this.work)
      );
      this.excerptSources = loaded.sources;
      if (loaded.conflicted.length > 0) {
        this.post({
          type: "error",
          message: `未解決の競合があるファイルは参照していません（${loaded.conflicted.join(
            "、"
          )}）。`,
        });
      }
    }
    // フルネームで登録されていても、本文には片方しか出てこないことが多い。
    // 広げないと、その人物の場面がほとんど集まらない
    return collectMentionExcerpts(
      this.excerptSources,
      searchTermsFor(kind, record)
    );
  }

  /** AIを1回呼ぶ。失敗したら理由と次の操作を画面に出す */
  private async generate(
    prompt: string,
    progressLabel: string,
    jsonSchema?: object
  ): Promise<string | undefined> {
    const resolved = await ensureConfigured(this.registry);
    if (!resolved) return undefined;

    const modelInfo = await this.registry.resolveModelInfo();
    const configuredNumCtx = vscode.workspace
      .getConfiguration("novelai")
      .get<number>("ollama.numCtx", 0);
    // 本文の抜粋は既定で最大12,000字あり、16,384で固定すると入り切らない。
    // 抽出側と同じく、送るものから必要量を計算する
    const numCtx =
      configuredNumCtx > 0
        ? configuredNumCtx
        : decideContextSize({
            chunkChars: EXCERPT_MAX_CHARS,
            outputTokens: resolveMaxOutputTokens(),
            contextWindow: modelInfo?.contextWindow ?? 16384,
          });

    this.setBusy(true, progressLabel);
    try {
      const result = await withCancellableProgress(
        progressLabel,
        async (_progress, token) => {
          const controller = new AbortController();
          token.onCancellationRequested(() => controller.abort());
          return resolved.provider.generate({
            systemPrompt: SETTINGS_ASSISTANT_SYSTEM_PROMPT,
            userPrompt: prompt,
            model: resolved.model,
            // 掘り下げは多少ふくらみがあってよい。抽出（0.2）より少し高くする。
            // 項目の提案は設定として書くので、控えめにする
            temperature: jsonSchema ? 0.3 : 0.5,
            numCtx,
            jsonSchema,
            disableThinking: true,
            signal: controller.signal,
          });
        }
      );

      if (result.truncated) {
        this.post({
          type: "error",
          message:
            "AIの応答が出力上限で切り詰められました。観点を絞って、もう一度試してください。",
        });
        return undefined;
      }
      const text = result.text.trim();
      if (!text) {
        this.post({
          type: "error",
          message: "AIの応答が空でした。モデル設定を確認してください。",
        });
        return undefined;
      }
      return text;
    } catch (error) {
      this.post({
        type: "error",
        message: describeError(error, {
          provider: resolved.provider.displayName,
          model: resolved.model,
        }),
      });
      return undefined;
    } finally {
      this.setBusy(false);
    }
  }

  private setBusy(busy: boolean, label = ""): void {
    this.post({ type: "busy", busy, label });
  }

  private post(message: OutgoingMessage): void {
    void this.panel.webview.postMessage(message);
  }
}

function field(
  key: keyof RecordEdits,
  label: string,
  value: string | null,
  multiline = false
): DetailField {
  return { key, label, value: value ?? "", multiline };
}

/**
 * 入・切だけの項目。
 * 画面との受け渡しは他の項目と同じ文字列にそろえ、
 * 入を "1"、切を空文字で表す（保存の経路を分けない）。
 */
function checkField(
  key: keyof RecordEdits,
  label: string,
  on: boolean
): DetailField {
  return { key, label, value: on ? "1" : "", multiline: false, check: true };
}

/**
 * 本文から場面を集めるときの検索語。
 *
 * **世界観だけは名前で引けない。** 見出し（「詠唱の制約」）は
 * こちらが付けた言葉で、本文には出てこない。名前だけで引くと
 * 場面が1つも集まらず、相談も項目の充実も材料なしで動くことになる。
 * 逐語引用である evidence を手掛かりにする。
 */
export function searchTermsFor(
  kind: SettingsKind,
  record: { name: string; aliases: string[]; evidence?: string | null }
): string[] {
  const names = expandNameVariants([record.name, ...record.aliases]);
  if (kind !== "world") return names;
  return [...names, ...evidencePhrases(record.evidence)];
}

/** 決まった値から選ぶ項目 */
function choiceField(
  key: keyof RecordEdits,
  label: string,
  value: string,
  choices: Array<{ value: string; label: string }>
): DetailField {
  return { key, label, value, multiline: false, choices };
}

/** 作者が足した項目の入力欄 */
function customFieldControls(
  character: Character,
  definitions: CustomFieldDefinition[]
): DetailField[] {
  return definitions.map((definition) => ({
    key: `${CUSTOM_FIELD_PREFIX}${definition.key}`,
    label: definition.label,
    value: character.customFields[definition.key] ?? "",
    multiline: definition.multiline,
  }));
}

/**
 * 画面のいちばん下へ回す参考情報。
 *
 * **食い違いも抽出根拠も、名前の直下から下げた。**
 * どちらも作者が毎回読むものではないのに量が多く、
 * 上に置くと編集欄が画面の外へ押し出される（実際に読みにくいと指摘があった）。
 * 消さずに残すのは、食い違いが作者の判断待ちであり、
 * 抽出根拠が「AIがどこを見てそう書いたか」を確かめる唯一の手掛かりだからである。
 *
 * 食い違いを先に置くのは、こちらだけが作者の操作を待っているため。
 *
 * 「食い違い」ではなく「変化かもしれない」と書くのは、
 * 小説では登場人物が作中で変わるからである。AIの取り違えと
 * 作中での変化を区別できるよう、値を話数と並べて出す。
 */
function referenceLines(
  conflicts: RecordConflict[],
  evidence: string | null
): Array<{ label: string; value: string }> {
  return [
    ...conflicts.map((conflict) => ({
      label: `変化かもしれない（${conflict.field}）`,
      value: [describeConflictValues(conflict), conflict.note ?? ""]
        .filter((part) => part)
        .join(" — "),
    })),
    { label: "抽出根拠", value: evidence ?? "" },
  ].filter((entry) => entry.value);
}

/** AIの応答をJSONとして読む。前後に余計な文字が付くことがある */
function parseEnrichResult(
  text: string
): Record<string, unknown> | undefined {
  const start = text.indexOf("{");
  const end = text.lastIndexOf("}");
  if (start === -1 || end <= start) return undefined;
  try {
    const parsed: unknown = JSON.parse(text.slice(start, end + 1));
    if (typeof parsed !== "object" || parsed === null) return undefined;
    return parsed as Record<string, unknown>;
  } catch {
    return undefined;
  }
}

/** 提案された値を、長さの制限まで含めて整える */
function clampField(field: EnrichableField, value: unknown): string {
  if (typeof value !== "string") return "";
  const text = value.trim();
  if (!text) return "";
  // AIは「不明」「なし」「（本文から読み取れる記述なし）」を値として返してくる。
  // 判定は抽出側と共有する（片方だけ直しても、もう片方から入り込む）
  if (!isMeaningfulValue(text)) return "";
  return field.maxChars ? (clampSummary(text, field.maxChars) ?? "") : text;
}

function asText(value: unknown): string {
  return typeof value === "string" ? value : "";
}

function describeError(
  error: unknown,
  /** どのAIのどのモデルで起きたか。切り替え後に前のAIの失敗と取り違えないため */
  used?: { provider: string; model: string }
): string {
  if (error instanceof AIError) {
    // 画面には出さない技術的な内容をログへ残す
    logFailure("設定資料パネルでのAI呼び出しの失敗", {
      使用中のAI: used ? `${used.provider} / ${used.model}` : "不明",
      種別: error.kind,
      詳細: error.detail,
    });
    // 残高不足は原因がはっきりしているので、そのまま伝える。
    // 「AI処理に失敗しました」だけでは何をすればよいか分からない
    if (error.kind === "insufficient_credit") return error.message;
    return `AI処理に失敗しました。${recoveryForAIError(error)}（詳細はログを参照）`;
  }
  if (error instanceof SettingsEditError) return error.message;
  if (error instanceof Error) return error.message;
  return String(error);
}

function createNonce(): string {
  const chars =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
  let value = "";
  for (let i = 0; i < 32; i++) {
    value += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return value;
}

export interface FieldProposal {
  key: string;
  label: string;
  before: string;
  after: string;
  multiline: boolean;
  /** 既定で選ばれているか。空欄を埋める提案だけを既定にする */
  selected: boolean;
}

interface ApplyProposalMessage {
  type: "applyProposal";
  kind: SettingsKind;
  id: string;
  /** 作者が選んだ項目だけ */
  values: Record<string, string>;
}

type PanelMessage =
  | { type: "ready" }
  | { type: "enrich"; kind: SettingsKind; id: string }
  | ApplyProposalMessage
  | { type: "select"; kind: SettingsKind; id: string }
  | {
      type: "save";
      kind: SettingsKind;
      id: string;
      /** 画面から来る生のキー。`custom:` 付きが混ざる */
      edits: Record<string, string>;
    }
  | ApproveNoteMessage
  | { type: "deleteNote"; kind: SettingsKind; id: string; noteId: string }
  | { type: "chat"; kind: SettingsKind; id: string; question: string };

interface ApproveNoteMessage {
  type: "approveNote";
  kind: SettingsKind;
  id: string;
  topic: string;
  text: string;
  source: AiNoteSource;
}

type OutgoingMessage =
  | {
      type: "init";
      groups: Record<SettingsKind, SettingsListItem[]>;
      notice: string;
    }
  | { type: "detail"; detail: DetailView }
  | {
      type: "focus";
      kind: SettingsKind;
      id: string;
      detail: DetailView;
    }
  | {
      type: "saved";
      detail: DetailView | undefined;
      groups: Record<SettingsKind, SettingsListItem[]>;
      notice: string;
    }
  | {
      type: "proposal";
      kind: SettingsKind;
      id: string;
      proposals: FieldProposal[];
      model: string;
    }
  | {
      type: "chatAnswer";
      text: string;
      html: string;
      question: string;
      model: string;
    }
  | { type: "busy"; busy: boolean; label: string }
  | { type: "error"; message: string };
