import * as vscode from "vscode";
import { WorkEntry } from "../models/types";
import type { Character } from "../models/character";
import type { Ability, AbilitySystem } from "../models/ability";
import type { Location } from "../models/location";
import type { AiNote, AiNoteSource } from "../models/aiNote";
import { CharacterStore } from "../core/characterStore";
import {
  AbilitySystemStore,
  createAbilityStore,
  createLocationStore,
} from "../core/abilityStore";
import type { SettingsStore } from "../core/settingsStore";
import {
  applyAbilityEdits,
  applyCharacterEdits,
  applyLocationEdits,
  appendAiNote,
  removeAiNote,
  SettingsEditError,
  type RecordEdits,
} from "../core/settingsEdit";
import {
  describeAbility,
  describeCharacter,
  describeLocation,
  KIND_LABELS,
  type SettingsKind,
} from "../core/settingsSummary";
import { formatChapters } from "../core/settingsMarkdown";
import {
  collectMentionExcerpts,
  type ExcerptSource,
  type MentionExcerpt,
} from "../core/mentionExcerpts";
import { loadExcerptSources } from "../core/manuscriptSources";
import { AIRegistry, ensureConfigured } from "../ai/registry";
import { AIError, recoveryForAIError } from "../ai/types";
import {
  buildDeepDivePrompt,
  buildSettingsChatPrompt,
  SETTINGS_ASSISTANT_SYSTEM_PROMPT,
  type ChatTurn,
} from "../prompts/settingsDeepDive";
import { buildSettingsPanelHtml } from "../views/settingsPanelHtml";
import { withCancellableProgress } from "../views/progress";

/**
 * 設定資料パネル。
 *
 * 資料を読むだけでなく、その場で直せて、AIに掘り下げさせられるようにする。
 * JSONを直接開いて編集するより間違えにくく、
 * 「どの項目を触ってよいか」が画面から分かる。
 *
 * **AIが書いたものは作者が承認するまで保存しない。**
 * 掘り下げは本文の逐語照合ができない解釈であり、
 * 抽出結果と同じ扱いで自動保存すると、
 * どこまでが本文に書いてあることなのか分からなくなるため。
 */

/** 作品ごとに1枚だけ開く。同じ作品で何枚も開いても混乱するだけ */
const openPanels = new Map<string, SettingsPanel>();

export async function openSettingsPanel(
  context: vscode.ExtensionContext,
  work: WorkEntry,
  registry: AIRegistry
): Promise<void> {
  const existing = openPanels.get(work.id);
  if (existing) {
    existing.reveal();
    return;
  }
  const panel = new SettingsPanel(context, work, registry);
  openPanels.set(work.id, panel);
  await panel.initialize();
}

interface ListItem {
  id: string;
  name: string;
  sub: string;
}

interface DetailField {
  key: keyof RecordEdits;
  label: string;
  value: string;
  multiline: boolean;
}

interface DetailView {
  kind: SettingsKind;
  id: string;
  name: string;
  autoGenerated: boolean;
  readOnly: Array<{ label: string; value: string }>;
  fields: DetailField[];
  aiNotes: AiNote[];
}

class SettingsPanel {
  private readonly panel: vscode.WebviewPanel;
  private readonly characterStore: CharacterStore;
  private readonly abilityStore: SettingsStore<Ability>;
  private readonly locationStore: SettingsStore<Location>;
  private readonly systemStore: AbilitySystemStore;

  private characters: Character[] = [];
  private abilities: Ability[] = [];
  private locations: Location[] = [];
  private abilitySystem: AbilitySystem | undefined;
  private loadErrors: Array<{ file: string; message: string }> = [];

  /** 本文は重いので一度読んだら使い回す。パネルを閉じるまで有効 */
  private excerptSources: ExcerptSource[] | undefined;
  /** 選択中のレコードごとのやり取り。保存はしない */
  private readonly chatHistory = new Map<string, ChatTurn[]>();

  constructor(
    context: vscode.ExtensionContext,
    private readonly work: WorkEntry,
    private readonly registry: AIRegistry
  ) {
    this.characterStore = new CharacterStore(work);
    this.abilityStore = createAbilityStore(work);
    this.locationStore = createLocationStore(work);
    this.systemStore = new AbilitySystemStore(work);

    this.panel = vscode.window.createWebviewPanel(
      "novelai.settings",
      `設定資料: ${work.title}`,
      vscode.ViewColumn.Active,
      { enableScripts: true, retainContextWhenHidden: true }
    );
    context.subscriptions.push(this.panel);

    this.panel.onDidDispose(() => openPanels.delete(work.id));
    this.panel.webview.onDidReceiveMessage((message: unknown) => {
      void this.handleMessage(message as PanelMessage);
    });
  }

  reveal(): void {
    this.panel.reveal();
  }

  async initialize(): Promise<void> {
    const nonce = createNonce();
    this.panel.webview.html = buildSettingsPanelHtml(
      nonce,
      this.panel.webview.cspSource
    );
    await this.loadAll();
  }

  private async loadAll(): Promise<void> {
    const loadedCharacters = await this.characterStore.loadAll();
    const loadedAbilities = await this.abilityStore.loadAll();
    const loadedLocations = await this.locationStore.loadAll();

    this.characters = loadedCharacters.characters;
    this.abilities = loadedAbilities.records;
    this.locations = loadedLocations.records;
    this.loadErrors = [
      ...loadedCharacters.errors,
      ...loadedAbilities.errors,
      ...loadedLocations.errors,
    ];

    // 能力体系が壊れていても、人物と場所は読めるので画面は出す
    try {
      this.abilitySystem = await this.systemStore.load();
    } catch {
      this.abilitySystem = undefined;
    }

    this.post({ type: "init", groups: this.groups(), notice: this.notice() });
  }

  private notice(): string {
    if (this.loadErrors.length === 0) return "";
    // 壊れたJSONは勝手に直さない。何が読めていないかだけ伝える
    return `読み込めない設定ファイルが ${this.loadErrors.length} 件あります（${this.loadErrors
      .map((error) => error.file)
      .join("、")}）。その項目は一覧に出ていません。`;
  }

  private groups(): Record<SettingsKind, ListItem[]> {
    return {
      character: this.characters.map((character) => ({
        id: character.id,
        name: character.name,
        sub: [
          character.role ?? "",
          character.isMob ? "モブ" : "",
          character.aiNotes.length > 0
            ? `掘り下げ${character.aiNotes.length}`
            : "",
        ]
          .filter((part) => part)
          .join(" / "),
      })),
      ability: this.abilities.map((ability) => ({
        id: ability.id,
        name: ability.name,
        sub: [
          ability.category ?? "",
          ability.aiNotes.length > 0 ? `掘り下げ${ability.aiNotes.length}` : "",
        ]
          .filter((part) => part)
          .join(" / "),
      })),
      location: this.locations.map((location) => ({
        id: location.id,
        name: location.name,
        sub: [
          location.region ?? "",
          location.aiNotes.length > 0
            ? `掘り下げ${location.aiNotes.length}`
            : "",
        ]
          .filter((part) => part)
          .join(" / "),
      })),
    };
  }

  private find(
    kind: SettingsKind,
    id: string
  ): Character | Ability | Location | undefined {
    if (kind === "character") {
      return this.characters.find((item) => item.id === id);
    }
    if (kind === "ability") return this.abilities.find((item) => item.id === id);
    return this.locations.find((item) => item.id === id);
  }

  private detailOf(kind: SettingsKind, id: string): DetailView | undefined {
    const record = this.find(kind, id);
    if (!record) return undefined;

    if (kind === "character") {
      const character = record as Character;
      return {
        kind,
        id,
        name: character.name,
        autoGenerated: character.autoGenerated,
        readOnly: [
          { label: "登場話", value: formatChapters(character.appearedChapters) },
          { label: "一人称", value: character.firstPerson.default ?? "" },
          { label: "抽出根拠", value: character.evidence ?? "" },
          ...conflictLines(character.conflicts),
        ].filter((entry) => entry.value),
        fields: [
          field("name", "名前", character.name),
          field("reading", "読み", character.reading),
          field("aliases", "別名（読点区切り）", character.aliases.join("、")),
          field("role", "役割", character.role),
          field("personality", "性格", character.personality, true),
          field("appearance", "外見", character.appearance, true),
          field("authorNotes", "作者メモ", character.authorNotes, true),
          field("exportNote", "資料用の補足", character.exportNote, true),
        ],
        aiNotes: character.aiNotes,
      };
    }

    if (kind === "ability") {
      const ability = record as Ability;
      return {
        kind,
        id,
        name: ability.name,
        autoGenerated: ability.autoGenerated,
        readOnly: [
          { label: "使い手", value: ability.userNames.join("、") },
          { label: "登場話", value: formatChapters(ability.appearedChapters) },
          { label: "抽出根拠", value: ability.evidence ?? "" },
          ...conflictLines(ability.conflicts),
        ].filter((entry) => entry.value),
        fields: [
          field("name", "名前", ability.name),
          field("reading", "読み", ability.reading),
          field("aliases", "別名（読点区切り）", ability.aliases.join("、")),
          field("category", "分類", ability.category),
          field("description", "説明", ability.description, true),
          field("cost", "代償", ability.cost, true),
          field("limitation", "制約", ability.limitation, true),
          field("authorNotes", "作者メモ", ability.authorNotes, true),
          field("exportNote", "資料用の補足", ability.exportNote, true),
        ],
        aiNotes: ability.aiNotes,
      };
    }

    const location = record as Location;
    return {
      kind,
      id,
      name: location.name,
      autoGenerated: location.autoGenerated,
      readOnly: [
        { label: "登場話", value: formatChapters(location.appearedChapters) },
        { label: "抽出根拠", value: location.evidence ?? "" },
        ...conflictLines(location.conflicts),
      ].filter((entry) => entry.value),
      fields: [
        field("name", "名前", location.name),
        field("reading", "読み", location.reading),
        field("aliases", "別名（読点区切り）", location.aliases.join("、")),
        field("region", "地域", location.region),
        field("description", "説明", location.description, true),
        field("authorNotes", "作者メモ", location.authorNotes, true),
        field("exportNote", "資料用の補足", location.exportNote, true),
      ],
      aiNotes: location.aiNotes,
    };
  }

  private async handleMessage(message: PanelMessage): Promise<void> {
    try {
      switch (message.type) {
        case "ready":
          this.post({
            type: "init",
            groups: this.groups(),
            notice: this.notice(),
          });
          return;
        case "select":
          this.postDetail(message.kind, message.id);
          return;
        case "save":
          await this.handleSave(message.kind, message.id, message.edits);
          return;
        case "deepDive":
          await this.handleDeepDive(message.kind, message.id, message.topic);
          return;
        case "approveNote":
          await this.handleApproveNote(message);
          return;
        case "deleteNote":
          await this.handleDeleteNote(message.kind, message.id, message.noteId);
          return;
        case "chat":
          await this.handleChat(message.kind, message.id, message.question);
          return;
      }
    } catch (error) {
      this.setBusy(false);
      this.post({ type: "error", message: describeError(error) });
    }
  }

  private postDetail(kind: SettingsKind, id: string): void {
    const detail = this.detailOf(kind, id);
    if (!detail) {
      this.post({ type: "error", message: "選択した設定が見つかりません。" });
      return;
    }
    this.post({ type: "detail", detail });
  }

  private async handleSave(
    kind: SettingsKind,
    id: string,
    edits: RecordEdits
  ): Promise<void> {
    const record = this.find(kind, id);
    if (!record) {
      this.post({ type: "error", message: "選択した設定が見つかりません。" });
      return;
    }

    const updated = this.applyEdits(kind, record, edits);
    await this.persist(kind, updated);
    await this.reloadAfterSave(kind, id, "保存しました。");
  }

  private applyEdits(
    kind: SettingsKind,
    record: Character | Ability | Location,
    edits: RecordEdits
  ): Character | Ability | Location {
    if (kind === "character") {
      return applyCharacterEdits(record as Character, edits);
    }
    if (kind === "ability") return applyAbilityEdits(record as Ability, edits);
    return applyLocationEdits(record as Location, edits);
  }

  private async persist(
    kind: SettingsKind,
    record: Character | Ability | Location
  ): Promise<void> {
    if (kind === "character") {
      await this.characterStore.save(record as Character);
      return;
    }
    if (kind === "ability") {
      await this.abilityStore.saveAll([record as Ability]);
      return;
    }
    await this.locationStore.saveAll([record as Location]);
  }

  /**
   * 保存後は読み直す。
   * ストアが持つハッシュと画面の内容がずれると、
   * 次の保存が「外部で変更された」と誤検出されるため。
   */
  private async reloadAfterSave(
    kind: SettingsKind,
    id: string,
    notice: string
  ): Promise<void> {
    await this.loadAll();
    const detail = this.detailOf(kind, id);
    this.post({
      type: "saved",
      detail,
      groups: this.groups(),
      notice,
    });
  }

  private async handleDeepDive(
    kind: SettingsKind,
    id: string,
    topic: string
  ): Promise<void> {
    const record = this.find(kind, id);
    if (!record) {
      this.post({ type: "error", message: "選択した設定が見つかりません。" });
      return;
    }

    const resolved = await ensureConfigured(this.registry);
    if (!resolved) return;

    const excerpts = await this.excerptsFor(record);
    const prompt = buildDeepDivePrompt({
      workTitle: this.work.title,
      target: {
        kindLabel: KIND_LABELS[kind],
        name: record.name,
        currentSettings: this.describe(kind, record),
      },
      topic,
      excerpts,
    });

    const text = await this.generate(
      prompt,
      `「${record.name}」を掘り下げています（本文 ${totalChars(
        excerpts
      ).toLocaleString("ja-JP")}字を参照）`
    );
    if (text === undefined) return;

    // ここでは保存しない。作者が内容を見て「追記する」を押すまで下書きのまま
    this.post({
      type: "draft",
      topic,
      text,
      model: resolved.model,
    });
  }

  private async handleChat(
    kind: SettingsKind,
    id: string,
    question: string
  ): Promise<void> {
    const record = this.find(kind, id);
    if (!record) {
      this.post({ type: "error", message: "選択した設定が見つかりません。" });
      return;
    }

    const resolved = await ensureConfigured(this.registry);
    if (!resolved) return;

    const key = `${kind}:${id}`;
    const history = this.chatHistory.get(key) ?? [];
    const excerpts = await this.excerptsFor(record);

    const prompt = buildSettingsChatPrompt({
      workTitle: this.work.title,
      target: {
        kindLabel: KIND_LABELS[kind],
        name: record.name,
        currentSettings: this.describe(kind, record),
      },
      question,
      excerpts,
      history,
    });

    const text = await this.generate(prompt, `「${record.name}」について調べています`);
    if (text === undefined) return;

    this.chatHistory.set(key, [
      ...history,
      { role: "author", text: question },
      { role: "assistant", text },
    ]);
    this.post({ type: "chatAnswer", text, question });
  }

  private async handleApproveNote(message: ApproveNoteMessage): Promise<void> {
    const record = this.find(message.kind, message.id);
    if (!record) {
      this.post({ type: "error", message: "選択した設定が見つかりません。" });
      return;
    }

    const resolved = this.registry.resolve();
    const updated = appendAiNote(record, {
      topic: message.topic,
      text: message.text,
      model: resolved?.model ?? "",
      source: message.source,
    });
    await this.persist(message.kind, updated as Character | Ability | Location);
    await this.reloadAfterSave(message.kind, message.id, "掘り下げを追記しました。");
  }

  private async handleDeleteNote(
    kind: SettingsKind,
    id: string,
    noteId: string
  ): Promise<void> {
    const record = this.find(kind, id);
    if (!record) return;
    const updated = removeAiNote(record, noteId);
    await this.persist(kind, updated as Character | Ability | Location);
    await this.reloadAfterSave(kind, id, "掘り下げを削除しました。");
  }

  private describe(
    kind: SettingsKind,
    record: Character | Ability | Location
  ): string {
    if (kind === "character") return describeCharacter(record as Character);
    if (kind === "ability") {
      return describeAbility(record as Ability, this.abilitySystem);
    }
    return describeLocation(record as Location);
  }

  /** その設定が出てくる場面を本文から集める */
  private async excerptsFor(
    record: Character | Ability | Location
  ): Promise<MentionExcerpt[]> {
    if (!this.excerptSources) {
      const loaded = await withCancellableProgress(
        "本文を読み込んでいます",
        async () => loadExcerptSources(this.work)
      );
      this.excerptSources = loaded.sources;
      if (loaded.conflicted.length > 0) {
        this.post({
          type: "error",
          message: `未解決の競合があるファイルは参照していません（${loaded.conflicted.join(
            "、"
          )}）。`,
        });
      }
    }
    return collectMentionExcerpts(this.excerptSources, [
      record.name,
      ...record.aliases,
    ]);
  }

  /** AIを1回呼ぶ。失敗したら理由と次の操作を画面に出す */
  private async generate(
    prompt: string,
    progressLabel: string
  ): Promise<string | undefined> {
    const resolved = await ensureConfigured(this.registry);
    if (!resolved) return undefined;

    const modelInfo = await this.registry.resolveModelInfo();
    const configuredNumCtx = vscode.workspace
      .getConfiguration("novelai")
      .get<number>("ollama.numCtx", 0);
    const numCtx =
      configuredNumCtx > 0
        ? configuredNumCtx
        : Math.min(modelInfo?.contextWindow ?? 16384, 16384);

    this.setBusy(true, progressLabel);
    try {
      const result = await withCancellableProgress(
        progressLabel,
        async (_progress, token) => {
          const controller = new AbortController();
          token.onCancellationRequested(() => controller.abort());
          return resolved.provider.generate({
            systemPrompt: SETTINGS_ASSISTANT_SYSTEM_PROMPT,
            userPrompt: prompt,
            model: resolved.model,
            // 掘り下げは多少ふくらみがあってよい。抽出（0.2）より少し高くする
            temperature: 0.5,
            numCtx,
            disableThinking: true,
            signal: controller.signal,
          });
        }
      );

      if (result.truncated) {
        this.post({
          type: "error",
          message:
            "AIの応答が出力上限で切り詰められました。観点を絞って、もう一度試してください。",
        });
        return undefined;
      }
      const text = result.text.trim();
      if (!text) {
        this.post({
          type: "error",
          message: "AIの応答が空でした。モデル設定を確認してください。",
        });
        return undefined;
      }
      return text;
    } catch (error) {
      this.post({ type: "error", message: describeError(error) });
      return undefined;
    } finally {
      this.setBusy(false);
    }
  }

  private setBusy(busy: boolean, label = ""): void {
    this.post({ type: "busy", busy, label });
  }

  private post(message: OutgoingMessage): void {
    void this.panel.webview.postMessage(message);
  }
}

function field(
  key: keyof RecordEdits,
  label: string,
  value: string | null,
  multiline = false
): DetailField {
  return { key, label, value: value ?? "", multiline };
}

/** 食い違いは作者の判断待ち。編集欄ではなく読み取り専用で見せる */
function conflictLines(
  conflicts: Array<{ field: string; values: string[]; note: string | null }>
): Array<{ label: string; value: string }> {
  return conflicts.map((conflict) => ({
    label: `食い違い（${conflict.field}）`,
    value: [conflict.values.join(" / "), conflict.note ?? ""]
      .filter((part) => part)
      .join(" — "),
  }));
}

function totalChars(excerpts: MentionExcerpt[]): number {
  return excerpts.reduce((sum, excerpt) => sum + excerpt.text.length, 0);
}

function describeError(error: unknown): string {
  if (error instanceof AIError) {
    return `AI処理に失敗しました。${recoveryForAIError(error)}`;
  }
  if (error instanceof SettingsEditError) return error.message;
  if (error instanceof Error) return error.message;
  return String(error);
}

function createNonce(): string {
  const chars =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
  let value = "";
  for (let i = 0; i < 32; i++) {
    value += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return value;
}

type PanelMessage =
  | { type: "ready" }
  | { type: "select"; kind: SettingsKind; id: string }
  | { type: "save"; kind: SettingsKind; id: string; edits: RecordEdits }
  | { type: "deepDive"; kind: SettingsKind; id: string; topic: string }
  | ApproveNoteMessage
  | { type: "deleteNote"; kind: SettingsKind; id: string; noteId: string }
  | { type: "chat"; kind: SettingsKind; id: string; question: string };

interface ApproveNoteMessage {
  type: "approveNote";
  kind: SettingsKind;
  id: string;
  topic: string;
  text: string;
  source: AiNoteSource;
}

type OutgoingMessage =
  | {
      type: "init";
      groups: Record<SettingsKind, ListItem[]>;
      notice: string;
    }
  | { type: "detail"; detail: DetailView }
  | {
      type: "saved";
      detail: DetailView | undefined;
      groups: Record<SettingsKind, ListItem[]>;
      notice: string;
    }
  | { type: "draft"; topic: string; text: string; model: string }
  | { type: "chatAnswer"; text: string; question: string }
  | { type: "busy"; busy: boolean; label: string }
  | { type: "error"; message: string };
