/**
 * 広報の動画、場面3「書く」を台本どおりに撮る（設計書6.114。作者の依頼、2026-10-10）。
 *
 * 作者の依頼：「原稿エディターで縦書横書きの切り替え→資料のチップ表示→右クリックで設定資料を開く
 * →エディター上での資料の切り替え実演→設定資料を最大化して一覧を出し、資料を切り替え
 * →原稿エディター最大化で縦書き入力で煽り文句を打ち込む」。煽り文句は作者が選んだ `TAGLINE`。
 *
 * 走らせ方：`npm run promo:record -- writeScene`（この場面だけ。名前を省けば全場面）。
 * **`npm run check` にも `test:e2e` にも入れない**——検査ではなく撮影で、ffmpeg が要る。
 * **作者が使っている機械では走らせない**（テスト用 VS Code が焦点を奪う。ノートPCで撮る）。
 *
 * 作りは場面2「直す」（`fixScene.promo.ts`）と同じ：本物の VS Code を画面の外で起こし、
 * 一時フォルダーへ作った**見本の作品**を開き、Playwright で押す。字幕・矢印・星・キーの札は
 * 録る側で重ねる（`support/overlay.ts`）。製品のコードは変えない。
 *
 * 製品のどの操作を撮っているか（コードで確かめた。2026-10-10）：
 * - 縦横の切り替え：原稿エディターの上の帯の［縦書きにする／横書きにする］（`#dir`。その場で組み直す）
 * - 資料のチップ：用語の上に**本物のマウスを載せる**と出る小窓（`#tip`。名前・種別・紹介の一文。
 *   設計書6.34.3「ホバーのチップ」）。色は CSS Custom Highlight API（`novelai-term-*`）
 * - 右クリックで設定資料：品書きの先頭「設定資料を見る」（`openTerm`）。設定資料パネルが
 *   原稿の右の列に、一覧を畳んで開く
 * - エディター上での資料の切り替え：**設定資料パネルを開いたまま、本文の別の用語を右クリックする**
 *   ——品書きを選ばなくても、右クリックそのものでパネルがその用語へ切り替わる（`previewTerm`。
 *   作者の指示 2026-08-28「すでに設定資料パネルが開いている場合は、該当項目の設定資料を表示」）
 * - 最大化：VS Code の「エディター グループの最大化の切り替え」（`workbench.action.toggleMaximizeEditorGroup`。
 *   製品の機能ではない）。一覧は設定資料パネルの［▶ 一覧を出す］（`#reopen`）
 *
 * - **作者の原稿・確認用コピーは使わない。** 見本の作品は下の `EPISODES`・`CHARACTERS`・`LOCATIONS`
 * - **AI は呼ばない。** 設定資料は製品と同じ形のファイルを、起こす前に置く
 *
 * 出力：
 * - `release/promo/write-raw.webm`（録ったまま。起動の様子も入っている）
 * - `release/promo/write.mp4`（X 用。頭を切ったもの）
 * - `media/promo/write.gif`（Marketplace の説明用）
 */
import { mkdir, rename, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { ElectronApplication, Frame, Page } from "playwright-core";
import { expect, test } from "vitest";
import { emptyCharacter, type Character } from "../../../src/models/character";
import { emptyLocation, locationFileName, type Location } from "../../../src/models/location";
import { DEFAULT_SETTINGS_DIR } from "../../../src/models/types";
import { caretPosition, composeText, manuscriptFrames, openEpisode, placeCaretAfter } from "../support/manuscriptFrame";
import { defaultCharactersFolder, settingsPanelFrame, writeCharactersTo } from "../support/settingsFixture";
import { resizeWindows, withVsCode, type E2ESession, type FixtureEpisode } from "../support/vscodeApp";
import { waitUntil } from "../support/wait";
import { clearNotifications, editorGroupTabs, pressWorkbenchKey, tabLocator } from "../support/workbenchDom";
import { durationSeconds, findFfmpeg, toGif, toMp4 } from "./support/encode";
import {
  clickWithCursor,
  hideCaption,
  hideCursor,
  hideTitleCard,
  hoverWithCursor,
  parkCursor,
  showCaption,
  showCursor,
  showKeyBadge,
  showTitleCard,
  type CaptionPlace,
} from "./support/overlay";

const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
/** 録ったままの動画と MP4 の置き場（`.gitignore` の `/release/` の下。repo に入れない） */
const RELEASE_DIR = path.join(repositoryRoot, "release", "promo");
/** GIF の置き場（README から参照するので repo に置く。VSIX には入れない——`.vscodeignore`） */
const MEDIA_DIR = path.join(repositoryRoot, "media", "promo");

/** 動画の画角。窓の中身の大きさと、録画の大きさを揃える（揃えないと縮んで字がぼける） */
const SIZE = { width: 1280, height: 720 };

/*
  **作者が見てから直せる文言は、ここに集めておく。**
  表題・字幕・煽り文句を変えるだけなら、下の台本の本体は触らなくてよい
*/
/** 冒頭の表題（白地） */
const TITLE = { title: "統合小説執筆環境", subtitle: "書く — 原稿の横に、設定資料" };
/** 結びの表題（白地） */
const CLOSING = { title: "統合小説執筆環境", subtitle: "VS Code の拡張機能" };
/** 段ごとの字幕 */
const CAPTIONS = {
  direction: "縦書きと横書き、ボタン1つで",
  terms: "登場人物や場所は、色で見分けられます",
  rightClick: "右クリックで、その人物の設定資料へ",
  follow: "書きながら、資料を切り替え",
  list: "一覧から、どの資料へも",
};
/** 最後に縦書きで打ち込む煽り文句（作者が選んだもの、2026-10-10） */
const TAGLINE = "書くこと以外、引き受けます。";
/** 煽り文句を1字ずつ打つ間（ミリ秒）。打っている絵に見える速さ */
const TYPE_INTERVAL_MS = 150;

/** 作品の題。設定資料パネルのタブ「設定資料: …」に写る */
const WORK_TITLE = "白い切符";
const EPISODE = "001_白い切符.txt";
/** 本文の最後の文（煽り文句はこの次の行へ打つ） */
const LAST_SENTENCE = "古い時計が九時を打った。";

/**
 * 見本の話（広報用の作り物）。人物2人（ミナ・灰谷）と場所2つ（白川駅・旧市街）が出る。
 * 3人目の人物（千景）は本文に出さない——「一覧からなら、本文に出ていない資料へも行ける」絵にするため
 */
const EPISODES: FixtureEpisode[] = [
  {
    name: EPISODE,
    text: [
      "　白川駅の改札を抜けると、雨はもう上がっていた。",
      "　ミナは切符を握ったまま、旧市街へ続く坂を見上げる。",
      "　「遅かったな」",
      "　ベンチの灰谷が、読みかけの本を閉じた。",
      "　ミナは答えず、彼の隣に腰を下ろした。",
      `　坂の上で、${LAST_SENTENCE}`,
      "",
    ].join("\n"),
  },
];

/**
 * 人物の設定資料（製品が読む形。`models/character.ts`）。
 *
 * **紹介（summary）を必ず入れる**——無いとチップが「（紹介はまだありません）」になる。
 * **紹介にほかの人物の名前を書かない**——段5で「前の人物の名前が消えたか」でパネルの
 * 切り替わりを確かめるので、紹介に名前があると見分けられない
 */
const CHARACTERS: Character[] = [
  {
    ...emptyCharacter("char_001", "ミナ"),
    reading: "みな",
    summary: "終電のあとの駅に降り立つ、物語の語り手。",
    role: "主人公",
    appearedChapters: [1],
    autoGenerated: false,
  },
  {
    ...emptyCharacter("char_002", "灰谷"),
    reading: "はいたに",
    summary: "駅のベンチで本を読みながら、誰かを待っている青年。",
    role: "案内人",
    appearedChapters: [1],
    autoGenerated: false,
  },
  {
    ...emptyCharacter("char_003", "千景"),
    reading: "ちかげ",
    summary: "古い時計店を継いだ、物静かな店主。",
    role: "協力者",
    autoGenerated: false,
  },
];

/** 場所の設定資料（製品が読む形。`models/location.ts`。ファイル名も製品の `locationFileName`） */
const LOCATIONS: Location[] = [
  {
    ...emptyLocation("loc_001", "白川駅"),
    reading: "しらかわえき",
    summary: "終電が出たあとも明かりの消えない、小さな駅。",
    appearedChapters: [1],
    autoGenerated: false,
  },
  {
    ...emptyLocation("loc_002", "旧市街"),
    reading: "きゅうしがい",
    summary: "坂の上に広がる古い町並み。時計台がある。",
    appearedChapters: [1],
    autoGenerated: false,
  },
];

/**
 * 設定資料を、**起こす前に**作品フォルダーへ置く（`LaunchOptions.prepareWork`）。
 * 起きている VS Code の下で書くと、見張りの「拡張機能の外で変更されました」が出る時機が揺れる
 */
async function prepareSettings(workFolder: string): Promise<void> {
  await writeCharactersTo(defaultCharactersFolder(workFolder), CHARACTERS);
  const locations = path.join(workFolder, DEFAULT_SETTINGS_DIR, "locations");
  await mkdir(locations, { recursive: true });
  for (const location of LOCATIONS) {
    await writeFile(path.join(locations, locationFileName(location)), `${JSON.stringify(location, null, 2)}\n`, "utf8");
  }
}

/** 使い捨ての settings.json へ足す見た目（場面2と同じ。白地・要らない部分を隠す・字を大きく） */
const PROMO_SETTINGS: Record<string, unknown> = {
  "workbench.colorTheme": "Default Light Modern",
  "workbench.activityBar.location": "hidden",
  "workbench.statusBar.visible": false,
  "workbench.layoutControl.enabled": false,
  "workbench.editor.editorActionsLocation": "hidden",
  // 題の帯は OS の枠に任せる（VS Code が描く帯は録画に写り、「[Extension Development Host]」と出る）
  "window.titleBarStyle": "native",
  "window.commandCenter": false,
  "window.menuBarVisibility": "hidden",
  "editor.minimap.enabled": false,
  "breadcrumbs.enabled": false,
  // 1段ぶん大きく（約120%）。1280×720 の動画で字が読めるように
  "window.zoomLevel": 1,
};

/** 左の列（エクスプローラー）を閉じるキー。設定では閉じた状態で起こせない（場面2と同じ） */
const CLOSE_SIDEBAR_KEY = "ctrl+alt+shift+f9";
const CLOSE_SIDEBAR_PRESS = "Control+Alt+Shift+F9";
/**
 * エディターの列の最大化を切り替えるキー（使い捨ての keybindings.json）。
 *
 * VS Code の既定は2段のキー **Ctrl+K Ctrl+M**（1.138.0 の本体で `mo(2089,2091)` と確かめた）で、
 * 画面の札にはその既定を出す。押すのは同じコマンドに割り当てた1段のキー——2段のキーは、
 * 焦点が WebView（原稿エディター・設定資料パネル）の中にあると1段目が届かないことがあり
 * （`workbenchDom.ts` の `pressWorkbenchKey`）、撮影の途中で止まりやすいため
 */
const MAXIMIZE_KEY = "ctrl+alt+shift+x";
const MAXIMIZE_PRESS = "Control+Alt+Shift+KeyX";
const MAXIMIZE_BADGE = "Ctrl+K Ctrl+M";

/** 見せる間を取る（見ている人に読ませるための間。画面の状態を待つ所は `waitUntil`） */
function hold(page: Page, ms: number): Promise<void> {
  return page.waitForTimeout(ms);
}

/** 窓の中身の大きさ（場面2と同じ。比が 16:9 からずれると録画に帯が出る） */
async function contentSize(app: ElectronApplication): Promise<{ width: number; height: number }> {
  return app.evaluate(({ BrowserWindow }) => {
    for (const win of BrowserWindow.getAllWindows()) {
      if (win.isDestroyed()) continue;
      const [width, height] = win.getContentSize();
      return { width, height };
    }
    return { width: 0, height: 0 };
  });
}

/**
 * 字幕の帯の置き場。**段ごとに空いている所が違う**ので分ける。
 * - 原稿だけ（横書き）：本文は上の6行だけなので、下の真ん中が空く
 * - 原稿と設定資料の2列：左の原稿の下（場面2と同じ）
 * - 設定資料の最大化：下の端（一覧と資料の中身にかからないよう、できるだけ下へ）
 */
const CAPTION_SOLO: CaptionPlace = { left: "50%", bottom: "14%" };
const CAPTION_TWO_COLUMNS: CaptionPlace = { left: "25%", bottom: "16%" };
const CAPTION_PANEL_MAX: CaptionPlace = { left: "60%", bottom: "4%" };

/** 描いたカーソルの退かし場（窓の幅・高さに対する割合）。本文・字幕・キーの札にかからない所 */
const PARK_SOLO = { x: 0.9, y: 0.9 };
const PARK_TWO_COLUMNS = { x: 0.9, y: 0.93 };
/** 縦書きで最大化した原稿：本文は右から組まれ、左下が空く */
const PARK_VERTICAL = { x: 0.08, y: 0.9 };

/** 割合で指した点を、ワークベンチの文書の座標へ */
async function viewportPoint(page: Page, at: { x: number; y: number }): Promise<{ x: number; y: number }> {
  return page.evaluate((at) => ({ x: Math.round(window.innerWidth * at.x), y: Math.round(window.innerHeight * at.y) }), at);
}

/**
 * 本物のマウスを、割合で指した点へ動かす（描いた矢印は動かさない）。
 * `window.zoomLevel: 1` で文書の座標は窓の画素より約2割小さいので、画素の決め打ちでは
 * 窓の外を指すことがある。割合から測る
 */
async function moveRealMouse(page: Page, at: { x: number; y: number }): Promise<void> {
  const point = await viewportPoint(page, at);
  await page.mouse.move(point.x, point.y);
}

/** 本文 `marker` を描いている原稿エディターの面（列の最大化などで探し直すため） */
async function manuscriptFrameWith(page: Page, marker: string): Promise<Frame> {
  let found: Frame | undefined;
  await waitUntil(
    async () => {
      for (const frame of await manuscriptFrames(page)) {
        if ((await composeText(frame).catch(() => "")).includes(marker)) {
          found = frame;
          return true;
        }
      }
      return false;
    },
    "原稿エディターの面が見つかる",
    15_000
  );
  if (!found) throw new Error("原稿エディターの面が見つかりません");
  return found;
}

/** 組んで書く面が縦書きか */
async function isVertical(frame: Frame): Promise<boolean> {
  return frame.evaluate(() => {
    const compose = document.getElementById("compose");
    return compose ? getComputedStyle(compose).writingMode.startsWith("vertical") : false;
  });
}

/**
 * 組んで書く面の `nth` 番目（0から）の `word` の真ん中を、`#compose` の左上からの位置で返す
 * （`clickWithCursor` の `position` に渡す。`manuscriptTermsEol.test.ts` の `rightClickWord` と同じ測り方）。
 * 用語は要素でなく色の範囲（Highlight API）なので、要素では狙えない
 */
async function wordPosition(frame: Frame, word: string, nth = 0): Promise<{ x: number; y: number }> {
  const position = await frame.evaluate(
    ({ text, index }) => {
      const compose = document.getElementById("compose");
      if (!compose) return undefined;
      const walker = document.createTreeWalker(compose, NodeFilter.SHOW_TEXT);
      let seen = 0;
      for (let node = walker.nextNode(); node; node = walker.nextNode()) {
        let at = (node.textContent ?? "").indexOf(text);
        while (at >= 0) {
          if (seen === index) {
            const range = document.createRange();
            range.setStart(node, at);
            range.setEnd(node, at + text.length);
            const rect = range.getBoundingClientRect();
            const box = compose.getBoundingClientRect();
            return { x: rect.left + rect.width / 2 - box.left, y: rect.top + rect.height / 2 - box.top };
          }
          seen += 1;
          at = (node.textContent ?? "").indexOf(text, at + 1);
        }
      }
      return undefined;
    },
    { text: word, index: nth }
  );
  if (!position) throw new Error(`組んで書く面に ${nth + 1} 番目の「${word}」が見つかりません`);
  return position;
}

/** 色が載っている字（`novelai-term-<kind>` の範囲が指す字）を、本文の順に */
async function coloredTerms(frame: Frame, kind: "character" | "location"): Promise<string[]> {
  return frame.evaluate((name) => {
    const registry = (globalThis as unknown as {
      CSS?: { highlights?: { get(name: string): Iterable<AbstractRange> | undefined } };
    }).CSS?.highlights;
    const highlight = registry?.get(name);
    if (!highlight) return [];
    const ranges = Array.from(highlight) as Range[];
    ranges.sort((a, b) => a.compareBoundaryPoints(Range.START_TO_START, b));
    return ranges.map((range) => range.toString());
  }, `novelai-term-${kind}`);
}

/** いま出ているチップの名前と種別（出ていなければ undefined） */
async function tipShown(frame: Frame): Promise<{ name: string; kind: string } | undefined> {
  return frame.evaluate(() => {
    const tip = document.getElementById("tip");
    if (!tip || !tip.classList.contains("open")) return undefined;
    return {
      name: tip.querySelector(".tip-name")?.textContent ?? "",
      kind: tip.querySelector(".tip-kind")?.textContent ?? "",
    };
  });
}

/** 用語にカーソルを載せて、そのチップが出るまで待つ */
async function hoverTerm(page: Page, frame: Frame, word: string, kindLabel: string): Promise<void> {
  await hoverWithCursor(page, frame.locator("#compose"), `本文の「${word}」`, { position: await wordPosition(frame, word) });
  await waitUntil(
    async () => {
      const tip = await tipShown(frame);
      return tip?.name === word && tip.kind === kindLabel;
    },
    `「${word}」のチップ（${kindLabel}）が出る`,
    10_000
  ).catch(async (error: unknown) => {
    throw new Error(`${String(error)}（いまのチップ：${JSON.stringify(await tipShown(frame))}）`);
  });
}

/** 右クリックの品書きが開いているか */
async function menuOpen(frame: Frame): Promise<boolean> {
  return frame.evaluate(() => document.getElementById("menu")?.classList.contains("open") === true);
}

/**
 * 用語を右クリックする（描いたカーソルで）。品書きが開き、**先頭が「設定資料を見る」**
 * ——用語の上を押せている印——であることを確かめる
 */
async function rightClickTerm(page: Page, frame: Frame, word: string): Promise<void> {
  await clickWithCursor(page, frame.locator("#compose"), `本文の「${word}」`, {
    position: await wordPosition(frame, word),
    button: "right",
  });
  await waitUntil(async () => await menuOpen(frame), `「${word}」の右クリックで品書きが開く`, 10_000);
  const first = (await frame.locator("#menu .item").first().innerText()).trim();
  if (first !== "設定資料を見る") {
    throw new Error(`「${word}」の右クリックの品書きの先頭が「設定資料を見る」ではありません（用語を外しています）: ${first}`);
  }
}

/**
 * 品書きを Esc で閉じる（右クリックで切り替えたあと、品書きは選ばずに閉じる）。
 * Esc は原稿の面へ向けて押す——右クリックで焦点が iframe へ移ったかは確かでないため、
 * `locator.press` で面に焦点を置いてから押す（品書きは文書の keydown で閉じる）
 */
async function closeMenu(frame: Frame): Promise<void> {
  await frame.locator("#compose").press("Escape");
  await waitUntil(async () => !(await menuOpen(frame)), "右クリックの品書きが閉じる", 5_000);
}

/** 設定資料パネルの様子（一覧を畳んでいるか・右の中身の字） */
async function panelState(frame: Frame): Promise<{ collapsed: boolean; detail: string }> {
  return frame.evaluate(() => ({
    collapsed: document.body.classList.contains("collapsed"),
    detail: document.getElementById("detail")?.innerText ?? "",
  }));
}

/** 設定資料パネルの中身が `name` になり、`gone` の名前がもう出ていないことを待つ */
async function waitPanelShows(frame: Frame, name: string, gone: readonly string[], label: string): Promise<void> {
  await waitUntil(
    async () => {
      const { detail } = await panelState(frame);
      return detail.includes(name) && gone.every((other) => !detail.includes(other));
    },
    label,
    15_000
  ).catch(async (error: unknown) => {
    throw new Error(`${String(error)}（パネルの中身：${(await panelState(frame)).detail.slice(0, 160)}）`);
  });
}

/** 設定資料のタブが1枚だけであること（右クリックのたびに新しいパネルが開いていないか） */
async function assertOneSettingsTab(page: Page, when: string): Promise<void> {
  const tabs = (await editorGroupTabs(page)).flat().filter((name) => name.startsWith("設定資料"));
  if (tabs.length !== 1) throw new Error(`${when}、設定資料のタブが ${tabs.length} 枚です: ${JSON.stringify(tabs)}`);
}

/** WebView の面の幅が、窓の幅の8割を超えているか（その列が最大化されているか） */
async function fillsWindow(page: Page, frame: Frame): Promise<boolean> {
  const inner = await frame.evaluate(() => window.innerWidth).catch(() => 0);
  const outer = await page.evaluate(() => window.innerWidth);
  return inner > outer * 0.8;
}

/** 最大化のキーを押す（右上に Ctrl+K Ctrl+M の札を出して） */
async function toggleMaximize(page: Page): Promise<void> {
  await showKeyBadge(page, MAXIMIZE_BADGE);
  await pressWorkbenchKey(page, MAXIMIZE_PRESS);
}

/** 本体のタブ（列の見出し）を描いたカーソルで押す。押した列が焦点を持つ */
async function clickTab(session: E2ESession, name: string): Promise<void> {
  // 名前が当たるタブ（拡張子のあり／なしを問わない。1.141.0 は `.label-name` から拡張子を外す）。
  // 当たらなければ、パネルの題の一部で探す前の形へ戻る
  const exact = await tabLocator(session.page, name);
  const tab =
    (await exact.count()) > 0
      ? exact
      : session.page
          .locator(".tabs-container .tab")
          .filter({ has: session.page.locator(".label-name", { hasText: name }) })
          .first();
  await tab.waitFor({ state: "visible", timeout: 10_000 });
  await clickWithCursor(session.page, tab.locator(".label-name").first(), `タブ「${name}」`);
  // 本物のマウスをタブの上に残すと、VS Code の吹き出し（タブの場所の表示）が出て録画に写る。
  // 描いた矢印は押した所に残し、本物のマウスだけ窓の下の端へ逃がす
  await moveRealMouse(session.page, { x: 0.5, y: 0.98 });
}

test("場面3「書く」を撮る", async () => {
  await mkdir(RELEASE_DIR, { recursive: true });
  await mkdir(MEDIA_DIR, { recursive: true });
  const videoDir = path.join(RELEASE_DIR, "raw-write");
  await rm(videoDir, { recursive: true, force: true });

  let videoStartedAt = 0;
  let sceneStartedAt = 0;
  let sceneEndedAt = 0;
  /** 見せ場の時刻（場面の頭から）。撮ったあと、こまを抜いて確かめるため */
  const marks: { label: string; ms: number }[] = [];

  const { videoPath } = await withVsCode(
    "広報・書く",
    EPISODES,
    async (session) => {
      const { page } = session;
      // **まず白い表題で覆う。** その下で、話を開くなどの段取りを済ませる
      await showTitleCard(page, TITLE.title, TITLE.subtitle);
      await resizeWindows(session.app, SIZE);
      await waitUntil(
        async () => {
          const actual = await contentSize(session.app);
          return actual.width === SIZE.width && actual.height === SIZE.height;
        },
        `窓の中身が ${SIZE.width}×${SIZE.height} になる`,
        10_000
      ).catch(async (error: unknown) => {
        throw new Error(`${String(error)}（いま ${JSON.stringify(await contentSize(session.app))}）`);
      });
      sceneStartedAt = Date.now();
      videoStartedAt = session.videoStartedAt ?? sceneStartedAt;
      const mark = (label: string) => marks.push({ label, ms: Date.now() - sceneStartedAt });

      await page.keyboard.press(CLOSE_SIDEBAR_PRESS);
      let frame = await openEpisode(page, EPISODE, LAST_SENTENCE);
      // 色が載り終わるまで待つ（人物：ミナ×2・灰谷、場所：白川駅・旧市街）
      await waitUntil(
        async () =>
          (await coloredTerms(frame, "character")).length === 3 && (await coloredTerms(frame, "location")).length === 2,
        "人物3か所・場所2か所に色が付く",
        30_000
      ).catch(async (error: unknown) => {
        throw new Error(
          `${String(error)}（人物：${JSON.stringify(await coloredTerms(frame, "character"))}／場所：${JSON.stringify(
            await coloredTerms(frame, "location")
          )}）`
        );
      });
      if (await isVertical(frame)) throw new Error("見本の話が縦書きで開きました（横書きで始める台本です）");
      const dir = frame.locator("#dir");
      if ((await dir.innerText()).trim() !== "縦書きにする") {
        throw new Error(`上の帯のボタンが［縦書きにする］ではありません: ${(await dir.innerText()).trim()}`);
      }
      await clearNotifications(page);
      // 本物のマウスは本文の下の空いた所へ（用語の上に残るとチップが写る）
      await moveRealMouse(page, { x: 0.5, y: 0.93 });
      const parkSolo = await viewportPoint(page, PARK_SOLO);
      await showCursor(page, parkSolo.x, parkSolo.y);

      const shown = Date.now() - sceneStartedAt;
      if (shown < 2_500) await hold(page, 2_500 - shown);
      await hideTitleCard(page);

      /* ── 1. 縦書きと横書き ── */
      await showCaption(page, CAPTIONS.direction, CAPTION_SOLO);
      await hold(page, 1_000);
      await clickWithCursor(page, dir, "［縦書きにする］");
      mark("［縦書きにする］を押した");
      await waitUntil(async () => await isVertical(frame), "1段目：縦書きになる", 10_000);
      await hold(page, 2_200);
      if ((await dir.innerText()).trim() !== "横書きにする") throw new Error("縦書きにしたのに、ボタンが［横書きにする］になっていません");
      await clickWithCursor(page, dir, "［横書きにする］");
      mark("［横書きにする］を押した");
      await waitUntil(async () => !(await isVertical(frame)), "1段目：横書きに戻る", 10_000);
      await hold(page, 1_400);

      /* ── 2. 用語の色とチップ ── */
      await showCaption(page, CAPTIONS.terms, CAPTION_SOLO);
      await hold(page, 1_500);
      await hoverTerm(page, frame, "灰谷", "人物");
      mark("「灰谷」のチップ");
      await hold(page, 2_000);
      await hoverTerm(page, frame, "白川駅", "場所");
      mark("「白川駅」のチップ");
      await hold(page, 2_000);

      /* ── 3. 右クリックで設定資料 ── */
      await showCaption(page, CAPTIONS.rightClick, CAPTION_SOLO);
      await hold(page, 900);
      await rightClickTerm(page, frame, "ミナ");
      mark("「ミナ」を右クリック");
      await hold(page, 700);
      await clickWithCursor(page, frame.locator("#menu .item", { hasText: "設定資料を見る" }).first(), "品書きの「設定資料を見る」");
      mark("「設定資料を見る」を押した");
      let settings: Frame | undefined;
      await waitUntil(
        async () => {
          settings = await settingsPanelFrame(session);
          return settings !== undefined && (await panelState(settings)).detail.includes("ミナ");
        },
        "3段目：設定資料パネルに「ミナ」が出る",
        30_000
      );
      if (!settings) throw new Error("設定資料パネルが見つかりません");
      const panel = settings;
      if (!(await panelState(panel)).collapsed) throw new Error("3段目：本文から開いた設定資料の一覧が畳まれていません");
      await assertOneSettingsTab(page, "3段目");
      // 原稿の列が狭くなって組み直されるので、面を探し直す
      frame = await manuscriptFrameWith(page, LAST_SENTENCE);
      const parkTwo = await viewportPoint(page, PARK_TWO_COLUMNS);
      await parkCursor(page, parkTwo.x, parkTwo.y);
      await moveRealMouse(page, { x: 0.25, y: 0.93 });
      await showCaption(page, CAPTIONS.rightClick, CAPTION_TWO_COLUMNS);
      await hold(page, 2_200);

      /* ── 4. 書きながら資料を切り替え（パネルを開いたまま、別の用語を右クリック） ── */
      await showCaption(page, CAPTIONS.follow, CAPTION_TWO_COLUMNS);
      await hold(page, 900);
      await rightClickTerm(page, frame, "灰谷");
      mark("「灰谷」を右クリック（パネルが切り替わる）");
      await waitPanelShows(panel, "灰谷", ["ミナ"], "4段目：右クリックだけで、設定資料パネルが「灰谷」へ切り替わる");
      await hold(page, 1_200);
      await closeMenu(frame);
      await hold(page, 900);
      await rightClickTerm(page, frame, "白川駅");
      mark("「白川駅」を右クリック（パネルが切り替わる）");
      await waitPanelShows(panel, "白川駅", ["灰谷"], "4段目：右クリックだけで、設定資料パネルが「白川駅」へ切り替わる");
      await hold(page, 1_200);
      await closeMenu(frame);
      await assertOneSettingsTab(page, "4段目");
      await parkCursor(page, parkTwo.x, parkTwo.y);
      await hold(page, 1_200);

      /* ── 5. 設定資料を最大化して一覧から切り替え ── */
      await hideCaption(page);
      // 最大化は焦点のある列に効く。パネルは焦点を取らずに開いた（preserveFocus）ので、タブを押して移す
      await clickTab(session, `設定資料: ${WORK_TITLE}`);
      await hold(page, 400);
      await toggleMaximize(page);
      mark("設定資料の列を最大化");
      await waitUntil(async () => await fillsWindow(page, panel), "5段目：設定資料パネルが窓いっぱいに広がる", 10_000);
      await showCaption(page, CAPTIONS.list, CAPTION_PANEL_MAX);
      await hold(page, 1_200);
      await clickWithCursor(page, panel.locator("#reopen"), "［▶ 一覧を出す］");
      mark("［一覧を出す］を押した");
      await waitUntil(
        async () =>
          !(await panelState(panel)).collapsed && (await panel.locator("#list .item", { hasText: "旧市街" }).count()) > 0,
        "5段目：一覧が開き、場所の「旧市街」が並ぶ",
        10_000
      );
      await hold(page, 1_000);
      await clickWithCursor(page, panel.locator("#list .item", { hasText: "旧市街" }).first(), "一覧の「旧市街」");
      await waitPanelShows(panel, "旧市街", ["白川駅"], "5段目：一覧から「旧市街」へ切り替わる");
      mark("一覧の「旧市街」を押した");
      await hold(page, 1_400);
      await clickWithCursor(page, panel.locator("#tabs button", { hasText: "登場人物" }).first(), "一覧のタブ「登場人物」");
      await waitUntil(
        async () => (await panel.locator("#list .item", { hasText: "千景" }).count()) > 0,
        "5段目：一覧に人物の「千景」が並ぶ",
        10_000
      );
      await hold(page, 800);
      await clickWithCursor(page, panel.locator("#list .item", { hasText: "千景" }).first(), "一覧の「千景」");
      await waitPanelShows(panel, "千景", ["旧市街"], "5段目：一覧から「千景」へ切り替わる");
      mark("一覧の「千景」を押した（本文に出ていない人物）");
      await hold(page, 2_200);

      /* ── 6. 原稿エディターを最大化して、縦書きで煽り文句を打つ ── */
      await hideCaption(page);
      // 設定資料の最大化を戻す → 原稿の列へ焦点を移す → 原稿の列を最大化
      await toggleMaximize(page);
      await waitUntil(async () => !(await fillsWindow(page, panel)), "6段目：設定資料の最大化が戻る", 10_000);
      await hold(page, 600);
      await clickTab(session, EPISODE);
      await hold(page, 400);
      await toggleMaximize(page);
      frame = await manuscriptFrameWith(page, LAST_SENTENCE);
      await waitUntil(async () => await fillsWindow(page, frame), "6段目：原稿エディターが窓いっぱいに広がる", 10_000);
      mark("原稿の列を最大化");
      await hold(page, 900);
      const dirNow = frame.locator("#dir");
      if ((await dirNow.innerText()).trim() !== "縦書きにする") throw new Error("6段目：原稿が横書きのままではありません");
      await clickWithCursor(page, dirNow, "［縦書きにする］");
      await waitUntil(async () => await isVertical(frame), "6段目：縦書きになる", 10_000);
      mark("縦書きにした");
      const parkVertical = await viewportPoint(page, PARK_VERTICAL);
      await parkCursor(page, parkVertical.x, parkVertical.y);
      await hold(page, 900);
      // 最後の文の末へカーソルを置き、改行して1字ずつ打つ（日本語は確定した字で入る。
      // IME の変換の途中の絵は写せない——スキル e2e「見張れないもの」）
      await placeCaretAfter(frame, LAST_SENTENCE);
      // placeCaretAfter は本文を押して焦点を移す。本物のマウスは本文の外の左下へ逃がす
      await page.mouse.move(parkVertical.x, parkVertical.y);
      await hold(page, 500);
      await page.keyboard.press("Enter");
      mark("煽り文句を打ち始める");
      for (const char of TAGLINE) {
        await page.keyboard.insertText(char);
        await hold(page, TYPE_INTERVAL_MS);
      }
      await waitUntil(
        async () => (await caretPosition(frame))?.lineText === TAGLINE,
        `6段目：「${TAGLINE}」が最後の文の次の行に入る`,
        10_000
      ).catch(async (error: unknown) => {
        throw new Error(`${String(error)}（カーソルの行：${JSON.stringify(await caretPosition(frame))}）`);
      });
      if (!(await isVertical(frame))) throw new Error("6段目：打ち終わったら横書きに戻っていました");
      mark("煽り文句を打ち終えた");
      await hold(page, 2_800);

      // 結び
      await showTitleCard(page, CLOSING.title, CLOSING.subtitle);
      await hideCursor(page);
      await hold(page, 2_700);
      // ここで切る。このあと窓を閉じる途中のこまを動画に入れない
      sceneEndedAt = Date.now();
    },
    {
      settings: PROMO_SETTINGS,
      keybindings: [
        { key: CLOSE_SIDEBAR_KEY, command: "workbench.action.closeSidebar" },
        { key: MAXIMIZE_KEY, command: "workbench.action.toggleMaximizeEditorGroup" },
      ],
      recordVideo: { dir: videoDir, size: SIZE },
      windowSize: SIZE,
      workTitle: WORK_TITLE,
      prepareWork: ({ workFolder }) => prepareSettings(workFolder),
    }
  ).catch((error: unknown) => {
    // 途中で止まっても、録ったままの動画（`raw-write/`）のどこを見ればよいかは残す
    const offset = (sceneStartedAt - videoStartedAt) / 1000;
    process.stdout.write(
      marks.map((m) => `[広報] 録ったままの動画の ${(offset + m.ms / 1000).toFixed(2)} 秒: ${m.label}`).join("\n") + "\n"
    );
    throw error;
  });

  expect(videoPath, "動画が録れていません").toBeTruthy();
  const raw = path.join(RELEASE_DIR, "write-raw.webm");
  await rm(raw, { force: true });
  await rename(videoPath as string, raw);
  await rm(videoDir, { recursive: true, force: true });

  // 頭と尻の切り方は場面2と同じ（表題の白の中で切る）
  const startSeconds = Math.max(0, (sceneStartedAt - videoStartedAt) / 1000 + 0.4);
  const lengthSeconds = (sceneEndedAt - sceneStartedAt) / 1000 - 0.7;

  const ffmpegPath = await findFfmpeg();
  if (!ffmpegPath) {
    console.error(`[広報] ffmpeg が見つからないので、変換を飛ばしました。録ったまま: ${raw}`);
    console.error(`[広報] 頭を切る位置: ${startSeconds.toFixed(2)} 秒`);
    return;
  }
  const mp4 = path.join(RELEASE_DIR, "write.mp4");
  const gif = path.join(MEDIA_DIR, "write.gif");
  await toMp4(ffmpegPath, raw, mp4, startSeconds, lengthSeconds);
  const gifInfo = await toGif(ffmpegPath, mp4, gif);
  const seconds = await durationSeconds(ffmpegPath, mp4);
  const megabytes = async (file: string) => ((await stat(file)).size / 1024 / 1024).toFixed(2);
  process.stdout.write(
    [
      `[広報] 頭を切った位置: ${startSeconds.toFixed(2)} 秒`,
      `[広報] MP4: ${mp4}（${seconds?.toFixed(1) ?? "?"} 秒・${await megabytes(mp4)} MB）`,
      `[広報] GIF: ${gif}（${gifInfo.fps}fps・幅${gifInfo.width}px・${await megabytes(gif)} MB）`,
      ...marks.map((m) => `[広報] MP4 の ${Math.max(0, m.ms / 1000 - 0.4).toFixed(2)} 秒: ${m.label}`),
    ].join("\n") + "\n"
  );
});
