import { afterEach, describe, expect, test } from "vitest";
import fs from "node:fs";
import os from "node:os";
import nodePath from "node:path";
import { chatPrompt } from "../../../src/mcp/tools/chat";
import { buildFeatureGuideForQuestion } from "../../../src/core/featureGuide";
import { buildWorkChatSystemPrompt } from "../../../src/prompts/workChat";
import {
  buildReaderAimPrompt,
  buildReaderTypeGlossaryPrompt,
  buildReaderTypeUnknownPrompt,
} from "../../../src/prompts/readerTarget";
import { readerReactionChatBlockFor } from "../../../src/core/readerAdviceChat";
import { emptyPostingLedger } from "../../../src/models/posting";
import { CHARACTER_NAMES_HEADING } from "../../../src/core/chatFileRequest";

/**
 * MCP の相談が、製品の相談（P-21、`features/workChatPanel.ts`）と**同じ材料**を
 * 組むか（残課題 R6、2026-10-01）。
 *
 * 以前の MCP は、製品が毎回渡している「使い方の束」（`featureGuide`）と
 * 「読者を決めていないことの断り」「読者の区分の一覧」を渡していなかった。
 * 外から相談の出来を測ると、**製品に無い答えを見ることになる**
 * （CLAUDE.md の失敗5）。
 *
 * ここで比べる相手は、製品が呼んでいる**同じ関数の出力**である。
 * 文字列を写して比べると、製品の側が変わったときに試験だけが古くなる。
 */

const temporary: string[] = [];

afterEach(() => {
  for (const folder of temporary.splice(0)) {
    fs.rmSync(folder, { recursive: true, force: true });
  }
});

/** 読者を決めていない作品（`設定/読者像.json` が無い）を一時に作る */
function workWithoutReader(): string {
  const folder = fs.mkdtempSync(nodePath.join(os.tmpdir(), "novelai-chat-materials-"));
  temporary.push(folder);
  fs.mkdirSync(nodePath.join(folder, "本文"), { recursive: true });
  fs.mkdirSync(nodePath.join(folder, "設定", "characters"), { recursive: true });
  fs.writeFileSync(
    nodePath.join(folder, "本文", "001_はじまり.txt"),
    "朝の光が差し込んだ。\n"
  );
  const character = (id: string, name: string, isMob: boolean) =>
    JSON.stringify({
      id,
      name,
      isMob,
      autoGenerated: true,
      appearances: [],
    });
  fs.writeFileSync(
    nodePath.join(folder, "設定", "characters", "char_0001.json"),
    character("char_0001", "灯", false)
  );
  fs.writeFileSync(
    nodePath.join(folder, "設定", "characters", "char_0002.json"),
    character("char_0002", "通りすがりの男", true)
  );
  return folder;
}

describe("使い方の束（featureGuide）", () => {
  test("操作の質問では、製品と同じ目次と説明を問いの後ろに添える", () => {
    const folder = workWithoutReader();
    const question = "誤字脱字検知はどこから使えますか";
    const guide = buildFeatureGuideForQuestion({ question, recentAuthorTurns: [] });

    const result = chatPrompt({ folder, question });

    expect(guide.topic).not.toBe("craft");
    expect(result.userPrompt).toContain(guide.text.trim());
    // 目次を渡す回は、システムプロンプトの使い方の節も入る（製品の切り替えと同じ）
    expect(
      result.systemPrompt.startsWith(buildWorkChatSystemPrompt({ featureIndex: true }))
    ).toBe(true);
  });

  test("創作の相談では、製品と同じく目次を落とした束になる", () => {
    const folder = workWithoutReader();
    const question = "主人公の動機が弱い気がします。どう膨らませればいいでしょう";
    const guide = buildFeatureGuideForQuestion({ question, recentAuthorTurns: [] });

    const result = chatPrompt({ folder, question });

    expect(guide.topic).toBe("craft");
    expect(result.userPrompt).toContain(guide.text.trim());
    expect(
      result.systemPrompt.startsWith(buildWorkChatSystemPrompt({ featureIndex: false }))
    ).toBe(true);
    expect(
      result.systemPrompt.startsWith(buildWorkChatSystemPrompt({ featureIndex: true }))
    ).toBe(false);
  });

  test("追い質問は、直前の作者の発言も選ぶ材料にする（製品と同じ）", () => {
    const folder = workWithoutReader();
    const history = [
      { role: "author" as const, text: "誤字脱字検知を使いたい" },
      { role: "assistant" as const, text: "詳細メニューにあります。" },
    ];
    const question = "それはどこ？";
    const guide = buildFeatureGuideForQuestion({
      question,
      recentAuthorTurns: ["誤字脱字検知を使いたい"],
    });

    const result = chatPrompt({ folder, question, history });

    expect(result.userPrompt).toContain(guide.text.trim());
  });

  test("featureIndex: false を渡したときだけ、使い方を渡さない（以前の測り方）", () => {
    const folder = workWithoutReader();
    const question = "誤字脱字検知はどこから使えますか";

    const result = chatPrompt({ folder, question, featureIndex: false });

    expect(result.userPrompt).not.toContain("【この拡張機能の操作の目次");
    expect(
      result.systemPrompt.startsWith(buildWorkChatSystemPrompt({ featureIndex: true }))
    ).toBe(false);
  });
});

describe("読者の材料", () => {
  test("読者を決めていない作品では、決めていないことだけを渡す（製品と同じ）", () => {
    const folder = workWithoutReader();

    const result = chatPrompt({ folder, question: "この場面はどうでしょう" });

    expect(result.systemPrompt).toContain(buildReaderTypeUnknownPrompt());
    expect(result.systemPrompt).not.toContain(buildReaderTypeGlossaryPrompt());
  });

  test("読者の話をしている回だけ、区分の一覧を添える（製品と同じ）", () => {
    const folder = workWithoutReader();

    const result = chatPrompt({ folder, question: "この作品の読者は誰だと思いますか" });

    expect(result.systemPrompt).toContain(buildReaderTypeUnknownPrompt());
    expect(result.systemPrompt).toContain(buildReaderTypeGlossaryPrompt());
  });

  /**
   * ターゲットシートの狙いと理由（設計書6.108.6 の⑤。0.98.8）。製品の相談と
   * 同じく、狙いがあれば毎回足し、読者像が無くても「まだ決めていません」は送らない。
   */
  test("シートに狙いと理由があれば、名前と理由を渡す（製品と同じ）", () => {
    const folder = workWithoutReader();
    fs.writeFileSync(
      nodePath.join(folder, "設定", "ターゲットシート.md"),
      [
        "# ターゲットシート",
        "<!-- 作者の欄 ここから -->",
        "狙い：考察層",
        "理由：伏線を拾ってくれる人に届けたい",
        "<!-- ここまで -->",
      ].join("\n")
    );

    const result = chatPrompt({ folder, question: "この場面はどうでしょう" });

    expect(result.systemPrompt).toContain(
      buildReaderAimPrompt(["lore_deep"], "伏線を拾ってくれる人に届けたい")
    );
    expect(result.systemPrompt).not.toContain(buildReaderTypeUnknownPrompt());
    expect(result.diagnoses.readerAim).toBe(true);
  });

  test("印の無い同名のファイルからは、狙いを読まない（製品と同じ）", () => {
    const folder = workWithoutReader();
    fs.writeFileSync(
      nodePath.join(folder, "設定", "ターゲットシート.md"),
      "自分のメモ\n狙い：考察層\n"
    );

    const result = chatPrompt({ folder, question: "この場面はどうでしょう" });

    expect(result.systemPrompt).not.toContain("【作者が狙う読者】");
    expect(result.diagnoses.readerAim).toBe(false);
  });

  test("読者の反応の話なら、投稿状態の材料を足す（台帳が無ければ空の台帳として）", async () => {
    const folder = workWithoutReader();
    const question = "PVが伸びないのはなぜでしょう";
    const block = await readerReactionChatBlockFor(question, async () =>
      emptyPostingLedger()
    );

    const result = chatPrompt({ folder, question });

    expect(block).toBeDefined();
    expect(result.systemPrompt).toContain(block!.text);
  });
});

describe("作品の材料（人物名）", () => {
  test("製品と同じ見出しと並べ方で、端役を除いた名前を渡す", () => {
    const folder = workWithoutReader();

    const result = chatPrompt({ folder, question: "この場面はどうでしょう" });

    expect(result.reference).toContain(`${CHARACTER_NAMES_HEADING}灯`);
    expect(result.reference.join("\n")).not.toContain("通りすがりの男");
  });
});
