import { describe, expect, test, afterEach } from "vitest";
import fs from "node:fs";
import os from "node:os";
import nodePath from "node:path";
import { openingPrompt, openingValidate } from "../../../src/mcp/tools/opening";
import {
  nameCollisions,
  namePrompt,
  nameValidate,
} from "../../../src/mcp/tools/name";
import {
  plotReversePrompt,
  plotReverseValidate,
} from "../../../src/mcp/tools/plot";
import { chapterPrompt, chapterValidate } from "../../../src/mcp/tools/chapter";
import {
  blurbPrompt,
  blurbValidate,
  catchphraseValidate,
} from "../../../src/mcp/tools/blurb";

/**
 * 外から呼べるようにした5つの「判断」（0.66.0。設計書6.87.13）。
 *
 * **作者の指示（2026-09-16）**：「ありそう部分を実装してください」。
 *
 * ## ここで見張りたいこと
 *
 * 1. **材料が足りないまま通さない。** プロット逆算はあらすじが無いと
 *    「冒頭だけを見て中盤以降を作る」ことになる——それは読み取りではなく
 *    創作で、**もっともらしい嘘が返る**
 * 2. **判断をAIに任せない**（CLAUDE.md 規則3）。字数・名前の衝突・
 *    実在する話数は、どれもコードが決められる
 * 3. **黙って減らさない。** 落としたものは理由とともに返す
 */

const WORK = nodePath.join(__dirname, "..", "..", "fixtures", "mcp-work");

const temporary: string[] = [];

afterEach(() => {
  for (const folder of temporary.splice(0)) {
    fs.rmSync(folder, { recursive: true, force: true });
  }
});

/** 作り物の作品を写して、一部を差し替えられるようにする */
function copiedWork(): string {
  const folder = fs.mkdtempSync(nodePath.join(os.tmpdir(), "novelai-judge-"));
  fs.cpSync(WORK, folder, { recursive: true });
  temporary.push(folder);
  return folder;
}

describe("冒頭診断（P-24）", () => {
  test("第1話の冒頭だけを渡す", () => {
    const prompt = openingPrompt({ folder: WORK });
    expect(prompt.excerptChars).toBeGreaterThan(0);
    expect(prompt.userPrompt).toContain("冒頭");
    // **診断の前提を返り値に残す**（どのファイルの何字を見たか）
    expect(prompt.readFrom).toBeTruthy();
  });

  test("プロットがあれば、ジャンルとログラインも渡る", () => {
    const prompt = openingPrompt({ folder: WORK });
    expect(prompt.hasPlot).toBe(true);
  });

  test("**プロットが無くても止めない**（材料が1つ減るだけ）", () => {
    const folder = copiedWork();
    fs.rmSync(nodePath.join(folder, "設定", "plot.md"));
    const prompt = openingPrompt({ folder });
    expect(prompt.hasPlot).toBe(false);
    expect(prompt.userPrompt).toContain("冒頭");
  });

  test("**作品情報（about.txt）を第1話と間違えない**", () => {
    /*
      **2026-09-16、作者の実データで見つけた**（単体テストでは出なかった）。
      カクヨムからダウンロードした作品には `about.txt`（タイトル・作者名・
      ジャンルが並ぶ作品情報）が入っており、**名前順では先頭に来る**——
      冒頭診断が、第1話ではなく作品説明を診断していた。

      製品の走査（`core/scanner.ts` の `compareEpisodes`）と同じ考えで、
      **話数の読めないファイルは後ろへ置く。**
    */
    const folder = copiedWork();
    fs.writeFileSync(
      nodePath.join(folder, "本文", "about.txt"),
      "【タイトル】\n灯台の合本\n\n【作者名】\n試験\n\n【ジャンル】\n現代ドラマ\n",
      "utf8"
    );
    const prompt = openingPrompt({ folder });
    expect(prompt.readFrom).not.toContain("about");
    expect(prompt.userPrompt).not.toContain("【作者名】");
  });

  test("読み取れない応答は断る（空として流さない）", () => {
    expect(() => openingValidate({ response: "わかりません" })).toThrow(
      /読み取れません/
    );
  });
});

describe("名前の候補（P-29）", () => {
  test("**本文を送らない**", () => {
    const prompt = namePrompt({ folder: WORK, characterName: "少年" });
    const body = fs.readFileSync(
      nodePath.join(WORK, "本文", "004_よあけ.txt"),
      "utf8"
    );
    // 本文の書き出しが混ざっていないこと（送るのは名前と世界観だけ）
    const head = body.trim().slice(0, 12);
    expect(prompt.userPrompt).not.toContain(head);
  });

  test("世界観の節は渡る（名前の系統は世界の作りから決まる）", () => {
    const prompt = namePrompt({ folder: WORK, characterName: "少年" });
    expect(prompt.hasSetting).toBe(true);
    expect(prompt.userPrompt).toContain("港町");
  });

  test("居ない人物は断り、**居る人を挙げて返す**", () => {
    expect(() =>
      namePrompt({ folder: WORK, characterName: "いない人" })
    ).toThrow(/少年/);
  });

  test("**ほかの人と衝突する候補はコードが落とす**（AIの申告を信じない）", () => {
    /*
      **製品と同じ絞り方にしてある**（`screenNameCandidates` に
      付け替える本人を除いた一覧を渡す）。本人を混ぜると、自分自身と
      衝突して候補が全部落ちる。
    */
    const folder = copiedWork();
    fs.writeFileSync(
      nodePath.join(folder, "設定", "characters", "char_0002.json"),
      JSON.stringify({
        schemaVersion: "0.1",
        id: "char_0002",
        name: "海斗",
        reading: "かいと",
        aliases: [],
        summary: "同じ船に乗る漁師。",
        appearedChapters: [2],
        autoGenerated: false,
        authorNotes: "",
        updatedAt: "2026-09-16T00:00:00.000Z",
      }),
      "utf8"
    );

    const result = nameValidate({
      folder,
      characterName: "少年",
      response: JSON.stringify({
        candidates: [
          { name: "海斗", reading: "かいと", reason: "既に居る人と同じ" },
          { name: "燈真", reading: "とうま", reason: "別の響き" },
        ],
      }),
    });
    const kept = result.accepted.map((candidate) => candidate.name);
    expect(kept).not.toContain("海斗");
    expect(kept).toContain("燈真");
    // **黙って減らさない**（落とした理由が残る）
    expect(result.rejected.length).toBeGreaterThan(0);
  });

  test("読み取れない応答は断る", () => {
    expect(() =>
      nameValidate({ folder: WORK, characterName: "少年", response: "{}" })
    ).toThrow(/読み取れません/);
  });

  test("衝突の点検は、AIを使わずに答える", () => {
    const result = nameCollisions({ folder: WORK });
    expect(Array.isArray(result.collisions)).toBe(true);
    expect(result.note).toContain("AIを使わず");
  });
});

describe("プロット逆算（P-02）", () => {
  test("あらすじがあれば組める", () => {
    const prompt = plotReversePrompt({ folder: WORK });
    expect(prompt.synopsisCount).toBeGreaterThan(0);
    expect(prompt.userPrompt).toContain("防波堤");
  });

  test("**あらすじが無ければ断る**（冒頭だけで中盤を作らせない）", () => {
    /*
      ここが、この道具のいちばん大事なところである。冒頭だけを見て
      中盤以降を推測させると、**本文に無い筋書きが返る**——
      それは読み取りではなく創作で、しかも読んだ側には区別が付かない。
    */
    const folder = copiedWork();
    fs.rmSync(nodePath.join(folder, "設定", "chapter_synopses.json"));
    expect(() => plotReversePrompt({ folder })).toThrow(/あらすじ/);
  });

  test("目安の字数を超えても**捨てない**（超えたことだけ伝える）", () => {
    const long = "あ".repeat(500);
    const result = plotReverseValidate({
      response: JSON.stringify({ logline: long }),
    });
    expect(result.sections.logline).toBe(long);
    expect(result.overLimit.length).toBeGreaterThan(0);
    expect(result.note).toContain("書き換えていません");
  });

  test("読み取れない応答は断る", () => {
    expect(() => plotReverseValidate({ response: "できません" })).toThrow(
      /読み取れません/
    );
  });
});

describe("章立て（P-31）", () => {
  test("合本も話ごとに並べて渡す（材料が痩せない）", () => {
    const prompt = chapterPrompt({ folder: WORK });
    // fixture の合本には複数話が入っている
    expect(prompt.episodeCount).toBeGreaterThan(1);
    expect(prompt.synopsisCount).toBeGreaterThan(0);
  });

  test("**実在しない話数の区切りは落とす**", () => {
    const result = chapterValidate({
      folder: WORK,
      response: JSON.stringify({
        chapters: [
          { name: "第一章　灯", startEpisode: 1 },
          { name: "第二章　幻", startEpisode: 9999 },
        ],
      }),
    });
    if (result.mode !== "chapters") throw new Error("形が違う");
    const starts = result.chapters.map((chapter) => chapter.startEpisode);
    expect(starts).not.toContain(9999);
    // **黙って減らさない**
    expect(result.rejected.length).toBeGreaterThan(0);
  });

  test("名前だけのときは、区切りを動かさない", () => {
    const result = chapterValidate({
      folder: WORK,
      nameOnly: 2,
      response: JSON.stringify({
        chapters: [
          { name: "灯の章", startEpisode: 1 },
          { name: "波の章", startEpisode: 1 },
          { name: "余った案", startEpisode: 1 },
        ],
      }),
    });
    if (result.mode !== "nameOnly") throw new Error("形が違う");
    expect(result.names.length).toBeLessThanOrEqual(2);
    expect(result.note).toContain("区切りは動かしていません");
  });
});

describe("作品紹介文（P-06）とキャッチコピー（P-08）", () => {
  test("材料が揃えば組める", () => {
    const prompt = blurbPrompt({ folder: WORK });
    expect(prompt.synopsisCount).toBeGreaterThan(0);
    expect(prompt.targetChars.min).toBeGreaterThan(0);
  });

  test("**短すぎるほうも測る**（1行で終わった紹介文を満点にしない）", () => {
    const result = blurbValidate({
      response: JSON.stringify({ blurb: "海辺の物語。" }),
    });
    expect(result.tooShort).toBe(true);
    expect(result.tooLong).toBe(false);
    // **捨てない**（投稿サイトによって上限が違う）
    expect(result.blurb).toBe("海辺の物語。");
  });

  test("長すぎるときも捨てず、外れたことを伝える", () => {
    const result = blurbValidate({
      response: JSON.stringify({ blurb: "あ".repeat(800) }),
    });
    expect(result.tooLong).toBe(true);
    expect(result.note).toContain("外れています");
  });

  test("**キャッチコピーは字数を超えたら落とす**（貼れない案を選ばせない）", () => {
    const result = catchphraseValidate({
      response: JSON.stringify({
        catchphrases: [
          { text: "父を待つ冬。", kind: "感情", intent: "" },
          { text: "あ".repeat(60), kind: "世界観", intent: "" },
        ],
      }),
    });
    expect(result.candidates).toHaveLength(1);
    expect(result.dropped).toHaveLength(1);
    expect(result.dropped[0].reason).toContain("上限");
  });

  test("読み取れない応答は断る", () => {
    expect(() => blurbValidate({ response: "書けません" })).toThrow(
      /読み取れません/
    );
    expect(() => catchphraseValidate({ response: "{}" })).toThrow(
      /読み取れません/
    );
  });
});
