import { describe, expect, it, beforeEach, afterEach } from "vitest";
import fs from "node:fs";
import os from "node:os";
import nodePath from "node:path";
import { createHash } from "node:crypto";
import { settingsPropose } from "../../../src/mcp/tools/propose";
import { McpToolError } from "../../../src/mcp/tools/shared";
import {
  exposureOf,
  setExternalClientName,
} from "../../../src/mcp/tools/accessLog";
import { assertExternalAccessAllowed } from "../../../src/mcp/tools/permission";
import {
  PENDING_CREATION_ID,
  pendingSourceLabel,
  readKind,
  readReason,
  readSource,
  unwrapPendingCharacter,
} from "../../../src/core/pendingUpdateFormat";
import { parseCharacter } from "../../../src/models/character";
import { diffCharacter } from "../../../src/core/characterDiff";

/**
 * 設定資料の更新案を承認待ちへ置く道具（設計書6.87.16）。
 *
 * **いちばん見張りたいのは1つ。台帳（`設定/characters/*.json`）が
 * 1バイトも変わらないこと。** ここが破れると、外部AIが作者の資料を
 * 黙って書き換えられることになる——このプロジェクトが避けてきた失敗
 * そのものである。だから、置く前と置いた後でハッシュを比べる。
 *
 * 次に見張るのは**断りどころ**。白名簿に無い欄・空の理由・未判断の案が
 * あるとき、黙って通さず、鍵の名前まで挙げて断ることを確かめる。
 */

const FIXTURE = nodePath.join(__dirname, "..", "..", "fixtures", "mcp-work");
const TEST_CLIENT = "試験";

const temporary: string[] = [];

/**
 * 作り物の作品を一時フォルダーへ写して、許可の印を置く。
 *
 * **fixture そのものへは書かない。** この道具は書く道具なので、
 * 走らせるたびにリポジトリのファイルが増えてしまう。
 */
function workCopy(): string {
  const folder = fs.mkdtempSync(nodePath.join(os.tmpdir(), "novelai-propose-"));
  fs.cpSync(FIXTURE, folder, { recursive: true });
  fs.mkdirSync(nodePath.join(folder, ".aiwriter"), { recursive: true });
  fs.writeFileSync(
    nodePath.join(folder, ".aiwriter", "external-access.json"),
    JSON.stringify({
      clients: [
        {
          name: TEST_CLIENT,
          tools: ["*"],
          sampling: false,
          decidedAt: "2026-09-17T00:00:00.000Z",
          decidedOn: "テスト",
          note: "",
        },
      ],
    }),
    "utf8"
  );
  temporary.push(folder);
  return folder;
}

/** 台帳の中身の指紋。**1バイトでも変われば変わる** */
function ledgerFingerprint(folder: string): string {
  const dir = nodePath.join(folder, "設定", "characters");
  const hash = createHash("sha256");
  for (const name of fs.readdirSync(dir).sort()) {
    hash.update(name);
    hash.update(fs.readFileSync(nodePath.join(dir, name)));
  }
  return hash.digest("hex");
}

function pendingDir(folder: string): string {
  return nodePath.join(folder, ".aiwriter", "pending-characters");
}

function readPending(folder: string, fileName: string): unknown {
  return JSON.parse(
    fs.readFileSync(nodePath.join(pendingDir(folder), fileName), "utf8")
  );
}

beforeEach(() => {
  setExternalClientName(TEST_CLIENT);
});

afterEach(() => {
  setExternalClientName("");
  for (const folder of temporary.splice(0)) {
    fs.rmSync(folder, { recursive: true, force: true });
  }
});

describe("novel.propose——既存人物への更新案", () => {
  it("承認待ちへ置く。台帳は1バイトも変わらない", () => {
    const folder = workCopy();
    const before = ledgerFingerprint(folder);

    const result = settingsPropose({
      folder,
      name: "少年",
      changes: { summary: "父の船を待ちながら、港の灯を守っている。" },
      reason: "第4話で灯台の当番を引き受けているため。",
    });

    // **ここが本丸。** 台帳へ触れていない
    expect(ledgerFingerprint(folder)).toBe(before);

    expect(result.kind).toBe("update");
    expect(result.source).toBe("external");
    expect(result.characterId).toBe("char_0001");
    expect(result.changedFields).toEqual(["summary"]);
    expect(result.file).toBe(".aiwriter/pending-characters/char_0001.json");
    expect(result.nextStep).toContain("設定資料更新分反映");
    expect(result.note).toContain("台帳");

    const payload = readPending(folder, "char_0001.json") as Record<
      string,
      unknown
    >;
    expect(payload.source).toBe("external");
    expect(payload.reason).toBe("第4話で灯台の当番を引き受けているため。");
    expect(payload.kind).toBeUndefined();

    const character = parseCharacter(unwrapPendingCharacter(payload));
    expect(character.summary).toBe("父の船を待ちながら、港の灯を守っている。");
    // **ほかの欄は元のまま**（写しを作って1欄だけ差し替えている）
    expect(character.name).toBe("少年");
    expect(character.aliases).toEqual(["灯の子"]);
    expect(character.appearedChapters).toEqual([1, 2, 3, 4]);
    expect(character.autoGenerated).toBe(false);
    expect(character.authorNotes).toBe("");
  });

  it("aliases は足すだけ。既存の別名は残り、重複は畳む", () => {
    const folder = workCopy();
    settingsPropose({
      folder,
      name: "少年",
      changes: { aliases: ["灯の子", "港の子"] },
      reason: "第2話で「港の子」と呼ばれているため。",
    });

    const character = parseCharacter(
      unwrapPendingCharacter(readPending(folder, "char_0001.json"))
    );
    expect(character.aliases).toEqual(["灯の子", "港の子"]);
  });

  it("置いたファイルを、製品側の読み取りが external として読める", () => {
    const folder = workCopy();
    settingsPropose({
      folder,
      name: "少年",
      changes: { role: "灯台の当番" },
      reason: "第4話の描写から。",
    });

    const payload = readPending(folder, "char_0001.json");
    expect(readSource(payload)).toBe("external");
    expect(readKind(payload)).toBeUndefined();
    expect(readReason(payload)).toBe("第4話の描写から。");
    // 画面に出す文言も揃っている（`pendingUpdates` からも同じものが出る）
    expect(pendingSourceLabel(readSource(payload))).toBe("外部AIから");
  });
});

describe("novel.propose——断りどころ", () => {
  it("白名簿に無い鍵は断る。断り文句に鍵の名前が出る", () => {
    const folder = workCopy();
    expect(() =>
      settingsPropose({
        folder,
        name: "少年",
        changes: { authorNotes: "勝手なメモ", addressTerms: [] },
        reason: "理由はある",
      })
    ).toThrow(McpToolError);

    try {
      settingsPropose({
        folder,
        name: "少年",
        changes: { authorNotes: "勝手なメモ", addressTerms: [] },
        reason: "理由はある",
      });
      throw new Error("断られなかった");
    } catch (error) {
      const message = (error as Error).message;
      // **黙って落とさない。** どの鍵が弾かれたかを名指しする
      expect(message).toContain("authorNotes");
      expect(message).toContain("addressTerms");
    }

    // 断ったので、何も置かれていない
    expect(fs.existsSync(pendingDir(folder))).toBe(false);
  });

  it("reason が空なら断る", () => {
    const folder = workCopy();
    expect(() =>
      settingsPropose({
        folder,
        name: "少年",
        changes: { summary: "何か" },
        reason: "   ",
      })
    ).toThrow(/reason/);
    expect(fs.existsSync(pendingDir(folder))).toBe(false);
  });

  it("changes が空なら断る", () => {
    const folder = workCopy();
    expect(() =>
      settingsPropose({
        folder,
        name: "少年",
        changes: {},
        reason: "理由はある",
      })
    ).toThrow(/changes/);
  });

  it("欄を空文字で消させない", () => {
    const folder = workCopy();
    expect(() =>
      settingsPropose({
        folder,
        name: "少年",
        changes: { summary: "" },
        reason: "理由はある",
      })
    ).toThrow(/summary/);
  });

  it("無い作品フォルダーには置かない（道を作らない）", () => {
    // 綴りを間違えたまま置くと、作者がどこを見ても見つからない提案ができる
    const missing = nodePath.join(os.tmpdir(), "novelai-propose-ないはず");
    expect(() =>
      settingsPropose({
        folder: missing,
        name: "少年",
        changes: { summary: "何か" },
        reason: "理由はある",
      })
    ).toThrow(/見つかりません/);
    expect(fs.existsSync(missing)).toBe(false);
  });

  it("同じ人物に未判断の案があれば、2回目は断る（上書きしない）", () => {
    const folder = workCopy();
    settingsPropose({
      folder,
      name: "少年",
      changes: { summary: "最初の案" },
      reason: "最初の理由",
    });

    expect(() =>
      settingsPropose({
        folder,
        name: "少年",
        changes: { summary: "あとの案" },
        reason: "あとの理由",
      })
    ).toThrow(/まだ判断していない/);

    // **先に置いた案が残っている。** 消えたら、作者が見る前の案が失われる
    const character = parseCharacter(
      unwrapPendingCharacter(readPending(folder, "char_0001.json"))
    );
    expect(character.summary).toBe("最初の案");
  });
});

/**
 * 関係（`relations`）の提案（作者の依頼「B3」、2026-09-22 未明）。
 *
 * 作者の作品で、マイナの関係に「ターナ＝父の娘」（正しくは母）が入っていたが、
 * 外部AIが気づいても置く口が無かった。**相手ごとの差し替え**にする——
 * 足すだけにすると、誤った「父の娘」が消せず、直す提案にならない。
 * 書いていない相手の関係は残す（外からの提案1回で、作者が足した関係を
 * まとめて消させない）。
 */
describe("novel.propose——関係（relations）", () => {
  /** 作り物の人物に関係を持たせる（写した一時フォルダーの中だけで） */
  function giveRelations(
    folder: string,
    relations: Array<{ name: string; relation: string }>
  ): void {
    const file = nodePath.join(folder, "設定", "characters", "char_0001.json");
    const record = JSON.parse(fs.readFileSync(file, "utf8")) as Record<string, unknown>;
    record.relations = relations;
    fs.writeFileSync(file, JSON.stringify(record, null, 2), "utf8");
  }

  it("書いた相手の関係だけを差し替える。ほかの相手の関係は残る。台帳は変わらない", () => {
    const folder = workCopy();
    giveRelations(folder, [
      { name: "ターナ", relation: "父の娘" },
      { name: "リナ", relation: "友人" },
    ]);
    const before = ledgerFingerprint(folder);

    const result = settingsPropose({
      folder,
      name: "少年",
      changes: { relations: [{ name: "ターナ", relation: "母" }] },
      reason: "第3話で「お母さん」と呼んでいるため。",
    });

    expect(ledgerFingerprint(folder)).toBe(before);
    expect(result.changedFields).toEqual(["relations"]);
    const character = parseCharacter(
      unwrapPendingCharacter(readPending(folder, "char_0001.json"))
    );
    // 差し替えた相手は元の位置に入る（並びが崩れると、差分が読みにくい）
    expect(character.relations).toEqual([
      { name: "ターナ", relation: "母" },
      { name: "リナ", relation: "友人" },
    ]);
  });

  it("まだ無い相手の関係は、末尾へ足す", () => {
    const folder = workCopy();
    giveRelations(folder, [{ name: "リナ", relation: "友人" }]);
    settingsPropose({
      folder,
      name: "少年",
      changes: { relations: [{ name: "灯台守", relation: "恩人" }] },
      reason: "第4話で船の話を教わっているため。",
    });
    const character = parseCharacter(
      unwrapPendingCharacter(readPending(folder, "char_0001.json"))
    );
    expect(character.relations).toEqual([
      { name: "リナ", relation: "友人" },
      { name: "灯台守", relation: "恩人" },
    ]);
  });

  it("中身が同じなら、変えた欄に数えない", () => {
    const folder = workCopy();
    giveRelations(folder, [{ name: "リナ", relation: "友人" }]);
    const result = settingsPropose({
      folder,
      name: "少年",
      changes: {
        relations: [{ name: "リナ", relation: "友人" }],
        role: "灯台の当番",
      },
      reason: "第4話の描写から。",
    });
    expect(result.changedFields).toEqual(["role"]);
  });

  it("関係を空で消させない・形の違うものは断る", () => {
    const folder = workCopy();
    const call = (relations: unknown) => () =>
      settingsPropose({
        folder,
        name: "少年",
        changes: { relations },
        reason: "理由はある",
      });
    // 空の関係＝その相手の関係を消す提案。消すのは作者の操作
    expect(call([{ name: "ターナ", relation: "  " }])).toThrow(/relations/);
    expect(call([{ name: "", relation: "母" }])).toThrow(/relations/);
    expect(call([])).toThrow(/relations/);
    expect(call("ターナ=母")).toThrow(/relations/);
    expect(call([{ name: "ターナ" }])).toThrow(/relations/);
    expect(fs.existsSync(pendingDir(folder))).toBe(false);
  });

  it("承認の画面は、消える関係と入る関係を1つずつ見せる", () => {
    // 承認は製品の差分（`characterDiff` の葉）を通る。誤りの「父の娘」が
    // 消えることが、作者に見えていなければならない
    const folder = workCopy();
    giveRelations(folder, [{ name: "ターナ", relation: "父の娘" }]);
    settingsPropose({
      folder,
      name: "少年",
      changes: { relations: [{ name: "ターナ", relation: "母" }] },
      reason: "第3話から。",
    });
    const current = parseCharacter(
      JSON.parse(
        fs.readFileSync(
          nodePath.join(folder, "設定", "characters", "char_0001.json"),
          "utf8"
        )
      )
    );
    const proposed = parseCharacter(
      unwrapPendingCharacter(readPending(folder, "char_0001.json"))
    );
    const diff = diffCharacter(current, proposed);
    const relationChange = diff.changes.find((change) => change.label === "関係");
    expect(relationChange?.entries).toEqual([
      { key: "relation:ターナ:母", text: "ターナ=母", state: "added" },
      { key: "relation:ターナ:父の娘", text: "ターナ=父の娘", state: "removed" },
    ]);
  });
});

describe("novel.propose——台帳に無い名前", () => {
  it("creation として new_… に置き、IDは仮のまま", () => {
    const folder = workCopy();
    const before = ledgerFingerprint(folder);

    const result = settingsPropose({
      folder,
      name: "灯台守",
      changes: { role: "港の灯を守る老人", summary: "少年に船の話をする。" },
      reason: "第3話に出てくるが、台帳に居ないため。",
    });

    expect(ledgerFingerprint(folder)).toBe(before);
    expect(result.kind).toBe("creation");
    expect(result.file).toBe(".aiwriter/pending-characters/new_灯台守.json");
    expect(result.characterId).toBe(PENDING_CREATION_ID);

    const payload = readPending(folder, "new_灯台守.json");
    expect(readKind(payload)).toBe("creation");
    expect(readSource(payload)).toBe("external");

    const character = parseCharacter(unwrapPendingCharacter(payload));
    // **仮の番号のまま。** 本当の採番は作者が承認したときに行う
    expect(character.id).toBe(PENDING_CREATION_ID);
    expect(character.name).toBe("灯台守");
    expect(character.role).toBe("港の灯を守る老人");
  });
});

describe("novel.propose——記録と門番", () => {
  it("原稿は外へ出ないので、記録の段階は none", () => {
    // 呼び出し元が持ち込んだ内容を置くだけで、こちらからは何も返さない
    expect(exposureOf("novel.propose", { folder: "x", name: "少年" })).toBe(
      "none"
    );
  });

  it("門番を素通りしない（許可の無い作品では断られる）", () => {
    const folder = fs.mkdtempSync(
      nodePath.join(os.tmpdir(), "novelai-propose-denied-")
    );
    temporary.push(folder);
    // 印が無い＝まだ意思確認していない＝拒否
    expect(() =>
      assertExternalAccessAllowed({ folder }, "novel.propose")
    ).toThrow();
  });
});
