import { afterEach, describe, expect, it } from "vitest";
import fs from "node:fs";
import os from "node:os";
import nodePath from "node:path";
import { createHash } from "node:crypto";
import { synopsisCommit } from "../../../src/mcp/tools/synopsisCommit";
import {
  readSynopsisStash,
  synopsisStashFileOf,
} from "../../../src/mcp/tools/synopsisStash";
import { synopsisValidate } from "../../../src/mcp/tools/episode";
import { blurbValidate } from "../../../src/mcp/tools/blurb";
import { novelValidate } from "../../../src/mcp/tools/features";
import { exposureOf } from "../../../src/mcp/tools/accessLog";
import {
  SYNOPSIS_SCHEMA_VERSION,
  parseSynopsisSet,
} from "../../../src/models/synopsis";
import { synopsisPromptVersion } from "../../../src/prompts/synopsis";
import { readerTypeCacheMark } from "../../../src/core/readerTarget";
import { hashText } from "../../../src/core/hash";
import { parseEpisodeMetadata } from "../../../src/core/metadataParser";
import { splitEpisodeBodyParts } from "../../../src/core/episodeBodyParts";
import {
  buildSynopsisMarkdown,
  parseSynopsisMarkdown,
} from "../../../src/core/synopsisDoc";
import { buildSynopsisListMarkdown } from "../../../src/core/synopsisMarkdown";
import { buildEmotionCurveMarkdown } from "../../../src/core/emotionCurve";

/**
 * 外部AIの各話あらすじ・作品紹介文を、資料へ保存する道（`novel.synopsis.commit`。
 * 作者の裁定 2026-10-02「何もない状態からであれば承認は不要」）。
 *
 * **いちばん見張りたいのは、既にあるあらすじ・紹介文が1バイトも変わらないこと。**
 * 製品のボタンは本文の変わった話を作り直すが、外からの保存は「まだ無い話を
 * 足す」「無いファイルを作る」だけに留める。
 */

const temporary: string[] = [];

/** ファイル名が数字だけ（サブタイトルを提案する話） */
const EPISODE_1 = "001.txt";
const EPISODE_2 = "002_嵐.txt";
const TEXT_1 =
  "　港町に灯という娘がいた。\n" +
  "　灯は毎晩、灯台に火をともした。\n";
const TEXT_2 =
  "　嵐の夜、漁師の岩男が港町へ戻ってきた。\n" +
  "　岩男は灯に礼を言った。\n";

const ANSWER_1 = {
  synopsis: "港町の娘・灯が、毎晩灯台に火をともす。",
  subtitles: [{ text: "灯台の娘", kind: "出来事型", reason: "主人公を示す" }],
  confidence: "high",
  emotion: { intensity: 2, valence: 1, dominant: "楽", reason: "穏やかな日常" },
};
const ANSWER_2 = {
  synopsis: "嵐の夜、漁師の岩男が港町へ戻り、灯に礼を言う。",
  subtitles: [],
  confidence: "high",
  emotion: { intensity: 6, valence: 2, dominant: "喜", reason: "無事の帰還" },
};
const BLURB_TEXT = "港町で灯台を守る娘・灯。嵐の夜、ひとりの漁師が戻ってくる。";

function makeWork(): string {
  const folder = fs.mkdtempSync(nodePath.join(os.tmpdir(), "novelai-synopsis-commit-"));
  temporary.push(folder);
  fs.mkdirSync(nodePath.join(folder, "本文"), { recursive: true });
  fs.writeFileSync(nodePath.join(folder, "本文", EPISODE_1), TEXT_1, "utf8");
  fs.writeFileSync(nodePath.join(folder, "本文", EPISODE_2), TEXT_2, "utf8");
  return folder;
}

function stash(folder: string, episode: string, answer: object): void {
  synopsisValidate({
    folder,
    filePath: `本文/${episode}`,
    response: JSON.stringify(answer),
    stash: true,
  });
}

function stashBoth(folder: string): void {
  // 話の順と逆に貯めて、並べ直しも試す
  stash(folder, EPISODE_2, ANSWER_2);
  stash(folder, EPISODE_1, ANSWER_1);
}

const synopsesFile = (folder: string): string =>
  nodePath.join(folder, "設定", "chapter_synopses.json");

/** 作者が書き直した第2話のあらすじ（CRLF・既存のファイル） */
const AUTHOR_EPISODE_2 = {
  chapter: 2,
  fileName: EPISODE_2,
  title: "嵐",
  synopsis: "作者が書き直したあらすじ。",
  sourceHash: "old",
  model: "gemma4:e4b",
  promptVersion: "2.1",
  autoGenerated: false,
  authorNotes: "作者のメモ",
  emotion: null,
  updatedAt: "2026-09-01T00:00:00.000Z",
  // 製品が知らない欄も残す（読んだままの形で書き戻すことを見る）
  extra: "作者が足した欄",
};

function writeExistingSynopses(folder: string): Buffer {
  fs.mkdirSync(nodePath.join(folder, "設定"), { recursive: true });
  const text = `${JSON.stringify(
    { schemaVersion: SYNOPSIS_SCHEMA_VERSION, episodes: [AUTHOR_EPISODE_2] },
    null,
    2
  )}\n`.replace(/\n/g, "\r\n");
  fs.writeFileSync(synopsesFile(folder), text, "utf8");
  return fs.readFileSync(synopsesFile(folder));
}

/** `設定/` の下の全ファイルの指紋 */
function fingerprints(folder: string): Map<string, string> {
  const result = new Map<string, string>();
  const base = nodePath.join(folder, "設定");
  if (!fs.existsSync(base)) return result;
  const walk = (dir: string): void => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = nodePath.join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else {
        result.set(
          nodePath.relative(folder, full),
          createHash("sha256").update(fs.readFileSync(full)).digest("hex")
        );
      }
    }
  };
  walk(base);
  return result;
}

/** 製品の各話あらすじが使う本文のハッシュ（`loadEpisodeBodies` と同じ材料） */
function productHashOf(text: string): string {
  return hashText(parseEpisodeMetadata(text).body);
}

afterEach(() => {
  for (const folder of temporary.splice(0)) {
    fs.rmSync(folder, { recursive: true, force: true });
  }
});

describe("novel.synopsis.commit（episodes）——何もない作品", () => {
  it("設定/ が無い作品に、製品の SynopsisStore と同じ字面で作る", () => {
    const folder = makeWork();
    stashBoth(folder);

    const result = synopsisCommit({ folder, kind: "episodes" });
    if (result.kind !== "episodes") throw new Error("kind");

    expect(result.createdCount).toBe(2);
    expect(result.created.map((item) => item.label)).toEqual(["第1話", "第2話"]);
    expect(result.refused).toEqual([]);
    expect(result.recoveryPath).toBeNull();

    const text = fs.readFileSync(synopsesFile(folder), "utf8");
    const set = parseSynopsisSet(JSON.parse(text));
    // 製品の `SynopsisStore.save` と同じ字面（字下げ2つ・LF・末尾改行）
    expect(text).toBe(
      `${JSON.stringify({ schemaVersion: SYNOPSIS_SCHEMA_VERSION, episodes: set.episodes }, null, 2)}\n`
    );
    expect(set.episodes.map((item) => item.chapter)).toEqual([1, 2]);

    const [first, second] = set.episodes;
    expect(first.fileName).toBe(EPISODE_1);
    expect(first.title).toBeNull();
    expect(first.synopsis).toBe(ANSWER_1.synopsis);
    // 製品の作り直しの判断と同じ材料（本文のハッシュ・版）
    expect(first.sourceHash).toBe(productHashOf(TEXT_1));
    expect(first.promptVersion).toBe(
      synopsisPromptVersion({
        needsSubtitle: true,
        readerTypeMark: readerTypeCacheMark(undefined),
      })
    );
    expect(first.autoGenerated).toBe(true);
    expect(first.authorNotes).toBe("");
    expect(first.model).toBeNull();
    expect(first.emotion).toEqual(ANSWER_1.emotion);
    expect(second.title).toBe("嵐");
    expect(second.promptVersion).toBe(
      synopsisPromptVersion({ needsSubtitle: false, readerTypeMark: "none" })
    );

    // 貯め場所は消える
    expect(fs.existsSync(synopsisStashFileOf(folder))).toBe(false);
  });

  it("ハッシュの材料は製品の loadEpisodeBodies と同じ（シーンメモを消した本文）", () => {
    const withMemo = `${TEXT_1}// メモ：ここで嵐を予感させる\n`;
    const parts = splitEpisodeBodyParts(withMemo, { chapter: 1, title: null });
    expect(parts).toHaveLength(1);
    expect(parts[0].body).not.toContain("メモ：");
  });
});

describe("novel.synopsis.commit（episodes）——既にある作品", () => {
  it("まだ無い話だけを足し、既にある話は1バイトも変えない（元は退避する）", () => {
    const folder = makeWork();
    const original = writeExistingSynopses(folder);
    stashBoth(folder);

    const result = synopsisCommit({ folder, kind: "episodes" });
    if (result.kind !== "episodes") throw new Error("kind");

    expect(result.created.map((item) => item.label)).toEqual(["第1話"]);
    expect(result.refused.map((item) => item.label)).toEqual(["第2話"]);

    const text = fs.readFileSync(synopsesFile(folder), "utf8");
    // 改行の形は元のまま（CRLF）
    expect(text.includes("\r\n")).toBe(true);
    expect(text.replace(/\r\n/g, "").includes("\n")).toBe(false);
    const raw = JSON.parse(text) as { episodes: unknown[] };
    // 作者のエントリは読んだままの形（製品の知らない欄まで）で、話数の順の2番目
    expect(raw.episodes[1]).toEqual(AUTHOR_EPISODE_2);
    // そのエントリの字面も、元のファイルにあったものと同じ
    const entryText = JSON.stringify(AUTHOR_EPISODE_2, null, 2)
      .split("\n")
      .map((line) => `    ${line}`)
      .join("\r\n")
      .trimStart();
    expect(text).toContain(entryText);
    expect(parseSynopsisSet(raw).episodes.map((item) => item.chapter)).toEqual([1, 2]);

    // 元のファイルは回復先へ、そのままのバイトで
    expect(result.recoveryPath).toMatch(/^設定\/\.novelai-recovery\/[0-9a-f]{64}-\d{13}-\d{8}-/);
    const recovered = fs.readFileSync(nodePath.join(folder, result.recoveryPath!));
    expect(recovered.equals(original)).toBe(true);
  });

  it("足す話が無ければ、ファイルに触れない（退避もしない）", () => {
    const folder = makeWork();
    writeExistingSynopses(folder);
    stash(folder, EPISODE_2, ANSWER_2);
    const before = fingerprints(folder);

    const result = synopsisCommit({ folder, kind: "episodes" });

    expect(result.createdCount).toBe(0);
    expect(result.refused).toHaveLength(1);
    expect(fingerprints(folder)).toEqual(before);
  });

  it("製品が作ったあらすじ（autoGenerated: true）でも、既にあれば変えない", () => {
    const folder = makeWork();
    fs.mkdirSync(nodePath.join(folder, "設定"), { recursive: true });
    fs.writeFileSync(
      synopsesFile(folder),
      `${JSON.stringify(
        {
          schemaVersion: SYNOPSIS_SCHEMA_VERSION,
          episodes: [{ ...AUTHOR_EPISODE_2, autoGenerated: true }],
        },
        null,
        2
      )}\n`,
      "utf8"
    );
    stash(folder, EPISODE_2, ANSWER_2);
    const before = fingerprints(folder);

    const result = synopsisCommit({ folder, kind: "episodes" });

    expect(result.refused.map((item) => item.label)).toEqual(["第2話"]);
    expect(fingerprints(folder)).toEqual(before);
  });
});

describe("novel.synopsis.commit（episodes）——止まるところ・捨てるところ", () => {
  it("本文が変わった話の貯めは捨てる", () => {
    const folder = makeWork();
    stashBoth(folder);
    fs.writeFileSync(nodePath.join(folder, "本文", EPISODE_1), `${TEXT_1}　灯は眠った。\n`, "utf8");

    const result = synopsisCommit({ folder, kind: "episodes" });

    expect(result.discarded.map((item) => item.label)).toEqual(["第1話"]);
    const set = parseSynopsisSet(JSON.parse(fs.readFileSync(synopsesFile(folder), "utf8")));
    expect(set.episodes.map((item) => item.chapter)).toEqual([2]);
  });

  it("壊れた chapter_synopses.json があれば、何も書かずに止まる（貯め場所も残す）", () => {
    const folder = makeWork();
    stashBoth(folder);
    fs.mkdirSync(nodePath.join(folder, "設定"), { recursive: true });
    fs.writeFileSync(synopsesFile(folder), "{ これは壊れている", "utf8");
    const before = fingerprints(folder);

    expect(() => synopsisCommit({ folder, kind: "episodes" })).toThrow(/読めません/);

    expect(fingerprints(folder)).toEqual(before);
    expect(readSynopsisStash(folder).episodes).toHaveLength(2);
  });

  it("形の違う chapter_synopses.json（あらすじが空）でも止まる", () => {
    const folder = makeWork();
    stashBoth(folder);
    fs.mkdirSync(nodePath.join(folder, "設定"), { recursive: true });
    fs.writeFileSync(
      synopsesFile(folder),
      JSON.stringify({ schemaVersion: "0.1", episodes: [{ fileName: "x.txt", synopsis: "" }] }),
      "utf8"
    );
    const before = fingerprints(folder);

    expect(() => synopsisCommit({ folder, kind: "episodes" })).toThrow(/読めません/);
    expect(fingerprints(folder)).toEqual(before);
  });

  it("dryRun は書かず、貯め場所も残す", () => {
    const folder = makeWork();
    writeExistingSynopses(folder);
    stashBoth(folder);
    const before = fingerprints(folder);

    const result = synopsisCommit({ folder, kind: "episodes", dryRun: true });

    expect(result.dryRun).toBe(true);
    expect(result.createdCount).toBe(1);
    expect(fingerprints(folder)).toEqual(before);
    expect(readSynopsisStash(folder).episodes).toHaveLength(2);
  });

  it("貯めたものが無ければ、どう貯めるかを添えて断る", () => {
    const folder = makeWork();
    expect(() => synopsisCommit({ folder, kind: "episodes" })).toThrow(/stash: true/);
  });
});

describe("novel.synopsis.commit（blurb）", () => {
  function stashBlurbOf(folder: string): void {
    blurbValidate({
      folder,
      response: JSON.stringify({ blurb: BLURB_TEXT, spoiler_check: "", confidence: "high" }),
      stash: true,
    });
  }

  it("synopsis.md が無ければ、製品と同じ組み立てで作る（各話あらすじの欄つき）", () => {
    const folder = makeWork();
    stashBoth(folder);
    synopsisCommit({ folder, kind: "episodes" });
    stashBlurbOf(folder);

    const result = synopsisCommit({ folder, kind: "blurb" });
    if (result.kind !== "blurb") throw new Error("kind");

    expect(result.created).toBe(true);
    const target = nodePath.join(folder, "設定", "synopsis.md");
    const text = fs.readFileSync(target, "utf8");
    const set = parseSynopsisSet(JSON.parse(fs.readFileSync(synopsesFile(folder), "utf8")));
    const title = nodePath.basename(folder);
    expect(text).toBe(
      buildSynopsisMarkdown(
        title,
        { catchphrase: null, blurb: BLURB_TEXT },
        buildSynopsisListMarkdown(set, { workTitle: title, headingLevel: 2, includeTitle: false }),
        buildEmotionCurveMarkdown(set.episodes)
      )
    );
    // 製品の読み取りで紹介文として読める
    expect(parseSynopsisMarkdown(text).blurb).toBe(BLURB_TEXT);
    expect(text).toContain(ANSWER_1.synopsis);
    expect(readSynopsisStash(folder).blurb).toBeNull();
  });

  it("synopsis.md が既にあれば、1バイトも変えずに断る（紹介文は返す）", () => {
    const folder = makeWork();
    fs.mkdirSync(nodePath.join(folder, "設定"), { recursive: true });
    fs.writeFileSync(nodePath.join(folder, "設定", "synopsis.md"), "# 作者の文書\n\n作者の紹介文\n", "utf8");
    stashBlurbOf(folder);
    const before = fingerprints(folder);

    const result = synopsisCommit({ folder, kind: "blurb" });
    if (result.kind !== "blurb") throw new Error("kind");

    expect(result.created).toBe(false);
    expect(result.refused).toHaveLength(1);
    expect(result.blurb).toBe(BLURB_TEXT);
    expect(fingerprints(folder)).toEqual(before);
  });

  it("dryRun は書かない", () => {
    const folder = makeWork();
    stashBlurbOf(folder);

    const result = synopsisCommit({ folder, kind: "blurb", dryRun: true });

    expect(result.createdCount).toBe(1);
    expect(fs.existsSync(nodePath.join(folder, "設定", "synopsis.md"))).toBe(false);
    expect(readSynopsisStash(folder).blurb).not.toBeNull();
  });

  it("chapter_synopses.json が壊れていれば作らない", () => {
    const folder = makeWork();
    fs.mkdirSync(nodePath.join(folder, "設定"), { recursive: true });
    fs.writeFileSync(synopsesFile(folder), "{ 壊れている", "utf8");
    stashBlurbOf(folder);

    expect(() => synopsisCommit({ folder, kind: "blurb" })).toThrow(/読めません/);
    expect(fs.existsSync(nodePath.join(folder, "設定", "synopsis.md"))).toBe(false);
  });
});

describe("貯める口", () => {
  it("novel.validate（synopsis・blurb）の stash: true で貯まる", () => {
    const folder = makeWork();
    novelValidate({
      folder,
      feature: "synopsis",
      filePath: `本文/${EPISODE_1}`,
      response: JSON.stringify(ANSWER_1),
      stash: true,
    });
    novelValidate({
      folder,
      feature: "blurb",
      response: JSON.stringify({ blurb: BLURB_TEXT }),
      stash: true,
    });
    const stashed = readSynopsisStash(folder);
    expect(stashed.episodes).toHaveLength(1);
    expect(stashed.episodes[0].sourceHash).toBe(productHashOf(TEXT_1));
    expect(stashed.blurb?.blurb).toBe(BLURB_TEXT);
  });

  it("同じ話を貯め直したら差し替える", () => {
    const folder = makeWork();
    stash(folder, EPISODE_1, ANSWER_1);
    stash(folder, EPISODE_1, { ...ANSWER_1, synopsis: "作り直したあらすじ。" });
    const stashed = readSynopsisStash(folder);
    expect(stashed.episodes).toHaveLength(1);
    expect(stashed.episodes[0].synopsis).toBe("作り直したあらすじ。");
  });

  it("空のあらすじは貯めない", () => {
    const folder = makeWork();
    expect(() => stash(folder, EPISODE_1, { ...ANSWER_1, synopsis: "" })).toThrow(/空/);
    expect(fs.existsSync(synopsisStashFileOf(folder))).toBe(false);
  });

  it("stash を付けなければ貯めない", () => {
    const folder = makeWork();
    synopsisValidate({
      folder,
      filePath: `本文/${EPISODE_1}`,
      response: JSON.stringify(ANSWER_1),
    });
    expect(fs.existsSync(synopsisStashFileOf(folder))).toBe(false);
  });

  it("原稿を外へ出さない道具として記録する", () => {
    expect(exposureOf("novel.synopsis.commit", { folder: "x" })).toBe("none");
  });
});
