import { afterEach, beforeEach, describe, expect, test, vi } from "vitest";
import fs from "node:fs";
import os from "node:os";
import nodePath from "node:path";

/**
 * 「AIで再読込」（P-20、設計書6.31.1）を外から呼ぶ feature `settingsEnrich`
 * （作者の裁定、2026-10-01）。
 *
 * 実機確認で、口調の出来の3項目が画面でしか確かめられずに残った——外から
 * 測る口が無かったため。ここで見張るのは4つ。
 *
 * 1. **プロンプトが製品と同じ材料で組まれる**（写しを作らない。CLAUDE.md の失敗5）
 * 2. **検算が製品と同じ関数を通る**（`core/settingsEnrichCheck.ts`）
 * 3. **作者が書いた項目は提案の対象にしない**（実装ルール2）
 * 4. **結果は資料へ直接書かない**（設計書6.87.8「読む・測る・提案するだけ」）
 */

/** Ollama の応答の差し替え（`novel.run` の ollama の道を、外へ出さずに通す） */
let ollamaReply = "{}";
vi.mock("../../../src/mcp/tools/ollama", async (importOriginal) => {
  const actual =
    await importOriginal<typeof import("../../../src/mcp/tools/ollama")>();
  return {
    ...actual,
    ollamaGenerate: async () => ({ text: ollamaReply }),
  };
});

import {
  novelPrompt,
  novelRun,
  novelValidate,
  type FeatureCallInput,
} from "../../../src/mcp/tools/features";
import {
  FEATURE_LABELS,
  FEATURE_NAMES,
  FEATURE_HINTS,
} from "../../../src/core/mcpFeatures";
import {
  SETTINGS_ENRICH_TEMPERATURE,
  SETTINGS_ENRICH_VERSION,
  buildEnrichPrompt,
  buildEnrichSchema,
  enrichableFields,
} from "../../../src/prompts/settingsEnrich";
import { SETTINGS_ASSISTANT_SYSTEM_PROMPT } from "../../../src/prompts/settingsChat";
import {
  checkEnrichProposals,
  describeEnrichTarget,
  parseEnrichResult,
  searchTermsFor,
} from "../../../src/core/settingsEnrichCheck";
import { collectMentionExcerpts } from "../../../src/core/mentionExcerpts";
import { excerptSourcesOfEpisode } from "../../../src/core/excerptSourceOf";
import { parseEpisodeFileName } from "../../../src/core/episodeParser";
import { parseEpisodeMetadata } from "../../../src/core/metadataParser";
import { KIND_LABELS } from "../../../src/core/settingsSummary";
import { parseCharacter } from "../../../src/models/character";
import { workTitleOf } from "../../../src/mcp/tools/shared";
import { SPEECH_STYLE_ASPECTS } from "../../../src/core/speechStyle";

const temporary: string[] = [];

afterEach(() => {
  for (const folder of temporary.splice(0)) {
    fs.rmSync(folder, { recursive: true, force: true });
  }
});

beforeEach(() => {
  ollamaReply = "{}";
});

const EPISODE_1 =
  "港の朝は早い。\n美咲は「あたし、もう行くね」と言って、網を肩に担いだ。\n" +
  "風が強く、帆がばたついていた。\n";
const EPISODE_2 =
  "灯台の下で、美咲は兄の帰りを待った。\n「遅いなあ、ほんとに」と美咲はつぶやいた。\n" +
  "宗一は黙って船を見ていた。\n";

/** 作り物の作品。人物は2人——抽出が作った美咲と、作者が確定させた宗一 */
function makeWork(): string {
  const folder = fs.mkdtempSync(nodePath.join(os.tmpdir(), "novelai-enrich-"));
  temporary.push(folder);
  const body = nodePath.join(folder, "本文");
  fs.mkdirSync(body, { recursive: true });
  fs.writeFileSync(nodePath.join(body, "001_港.txt"), EPISODE_1, "utf8");
  fs.writeFileSync(nodePath.join(body, "002_灯台.txt"), EPISODE_2, "utf8");

  const characters = nodePath.join(folder, "設定", "characters");
  fs.mkdirSync(characters, { recursive: true });
  const misaki = {
    schemaVersion: "0.1",
    id: "char_0001",
    name: "美咲",
    aliases: [],
    summary: "港町の娘。",
    appearedChapters: [1, 2],
    autoGenerated: true,
    authorNotes: "",
    updatedAt: "2026-09-12T00:00:00.000Z",
  };
  const soichi = {
    schemaVersion: "0.1",
    id: "char_0002",
    name: "宗一",
    aliases: [],
    summary: "美咲の兄。",
    personality: "作者が書いた性格",
    appearedChapters: [2],
    autoGenerated: false,
    authorNotes: "作者のメモ（外へ出さない）",
    updatedAt: "2026-09-12T00:00:00.000Z",
  };
  fs.writeFileSync(
    nodePath.join(characters, "char_0001.json"),
    JSON.stringify(misaki, null, 2),
    "utf8"
  );
  fs.writeFileSync(
    nodePath.join(characters, "char_0002.json"),
    JSON.stringify(soichi, null, 2),
    "utf8"
  );
  return folder;
}

function call(
  folder: string,
  options: Record<string, unknown>,
  extra: Partial<FeatureCallInput> = {}
): FeatureCallInput {
  return {
    folder,
    feature: "settingsEnrich" as FeatureCallInput["feature"],
    options,
    ...extra,
  };
}

/** 製品の `loadExcerptSources` と同じ割り方で、本文を出典つきにする（走査の順） */
function productSources(folder: string) {
  const body = nodePath.join(folder, "本文");
  return fs
    .readdirSync(body)
    .sort()
    .flatMap((fileName) => {
      const text = fs.readFileSync(nodePath.join(body, fileName), "utf8");
      const parsed = parseEpisodeFileName(fileName);
      const meta = parseEpisodeMetadata(text);
      return excerptSourcesOfEpisode(
        {
          filePath: nodePath.join(body, fileName),
          fileName,
          metaTitle: meta.title,
          subtitle: parsed.subtitle ?? meta.title,
          kind: parsed.kind,
          chapterStart: parsed.chapterStart,
          chapterEnd: parsed.chapterEnd,
        },
        text
      );
    });
}

function readCharacter(folder: string, file: string) {
  return parseCharacter(
    JSON.parse(
      fs.readFileSync(nodePath.join(folder, "設定", "characters", file), "utf8")
    )
  );
}

/** フォルダーの中身の指紋（書いていないことを確かめる） */
function fingerprint(folder: string): string {
  const entries: string[] = [];
  const walk = (dir: string) => {
    for (const name of fs.readdirSync(dir).sort()) {
      const full = nodePath.join(dir, name);
      if (fs.statSync(full).isDirectory()) walk(full);
      else entries.push(`${nodePath.relative(folder, full)}=${fs.readFileSync(full, "utf8")}`);
    }
  };
  walk(folder);
  return entries.join("\n");
}

describe("feature の一覧", () => {
  test("settingsEnrich が載っていて、呼び名と一言がある", () => {
    expect(FEATURE_NAMES as readonly string[]).toContain("settingsEnrich");
    const key = "settingsEnrich" as (typeof FEATURE_NAMES)[number];
    expect(FEATURE_LABELS[key]).toBeTruthy();
    expect(FEATURE_HINTS[key]).toBeTruthy();
  });
});

describe("プロンプトは製品と同じ材料で組む", () => {
  test("【現在の設定】・本文の抜粋・留意点・スキーマ・温度が製品の組み方と同じ", () => {
    const folder = makeWork();
    const notes = "他の登場人物宗一の情報が混入しています。";
    const prompt = novelPrompt(call(folder, { name: "美咲", notes })) as Record<
      string,
      unknown
    >;

    const record = readCharacter(folder, "char_0001.json");
    const excerpts = collectMentionExcerpts(
      productSources(folder),
      searchTermsFor("character", record)
    );
    const expected = buildEnrichPrompt({
      workTitle: workTitleOf(folder),
      kind: "character",
      target: {
        kindLabel: KIND_LABELS.character,
        name: record.name,
        currentSettings: describeEnrichTarget("character", record, {
          customFields: [],
          characters: [
            record,
            readCharacter(folder, "char_0002.json"),
          ],
        }),
      },
      excerpts,
      customFields: [],
      notes,
    });

    expect(prompt.userPrompt).toBe(expected);
    expect(prompt.schema).toEqual(buildEnrichSchema("character", []));
    expect(prompt.systemPrompt).toBe(SETTINGS_ASSISTANT_SYSTEM_PROMPT);
    expect(prompt.temperature).toBe(SETTINGS_ENRICH_TEMPERATURE);
    expect(String(prompt.promptVersion)).toContain(SETTINGS_ENRICH_VERSION);
    // 抜粋に本文の台詞が入っている（名前で引けている）
    expect(prompt.userPrompt).toContain("あたし、もう行くね");
  });

  test("ほかの記録の名前の中の一致と、長いカタカナ語の一部の一致は抜粋に入れない", () => {
    // 2026-10-02：「フォー」が「フォートラン」に当たり、抜粋が別の語の場面で埋まった
    const folder = makeWork();
    fs.writeFileSync(
      nodePath.join(folder, "本文", "003_商会.txt"),
      // 抜粋は一致の前後200字ずつなので、長い行で場面を離す
      "美咲商会の看板が風に鳴った。\n" +
        `${"波".repeat(500)}\n` +
        "美咲は商会の前で足を止めた。\n",
      "utf8"
    );
    const organizations = nodePath.join(folder, "設定", "organizations");
    fs.mkdirSync(organizations, { recursive: true });
    fs.writeFileSync(
      nodePath.join(organizations, "org_0001.json"),
      JSON.stringify({ schemaVersion: "0.1", id: "org_0001", name: "美咲商会" }),
      "utf8"
    );
    const prompt = novelPrompt(call(folder, { name: "美咲" })) as Record<string, unknown>;

    expect(prompt.userPrompt).not.toContain("看板が風に鳴った");
    expect(prompt.userPrompt).toContain("商会の前で足を止めた");
  });

  test("カタカナの別名は、長いカタカナ語の中では当てない", () => {
    const folder = makeWork();
    const file = nodePath.join(folder, "設定", "characters", "char_0001.json");
    const misaki = JSON.parse(fs.readFileSync(file, "utf8"));
    fs.writeFileSync(file, JSON.stringify({ ...misaki, aliases: ["ミサ"] }), "utf8");
    fs.writeFileSync(
      nodePath.join(folder, "本文", "003_祭.txt"),
      "ミサイルが空を裂いた。\n",
      "utf8"
    );
    const prompt = novelPrompt(call(folder, { name: "美咲" })) as Record<string, unknown>;

    expect(prompt.userPrompt).not.toContain("ミサイル");
    expect(prompt.userPrompt).toContain("あたし、もう行くね");
  });

  test("id でも指せる", () => {
    const folder = makeWork();
    const prompt = novelPrompt(call(folder, { id: "char_0002" })) as Record<string, unknown>;
    expect(prompt.name).toBe("宗一");
  });

  test("name も id も無ければ、名前を挙げて断る", () => {
    const folder = makeWork();
    expect(() => novelPrompt(call(folder, {}))).toThrow(/name/);
  });

  test("台帳に居ない名前は断る（別名や似た名前へ寄せない）", () => {
    const folder = makeWork();
    expect(() => novelPrompt(call(folder, { name: "美咲さん" }))).toThrow(/見つかりません/);
  });
});

describe("検算は製品と同じ関数を通る", () => {
  test("口調の指示の写し・無い話の引用・いまと同じ値・「不明」を落とす", () => {
    const folder = makeWork();
    const response = JSON.stringify({
      gender: "不明",
      summary: "港町の娘。",
      affiliation: null,
      role: "第17話から網元",
      personality: "明るく、ためらわずに動く（網を担いで先に出ていく）",
      speechStyle: SPEECH_STYLE_ASPECTS.slice(0, 3).join("・"),
      appearance: null,
      misattributed: [],
    });
    const result = novelValidate(
      call(folder, { name: "美咲" }, { response })
    ) as {
      proposals: Array<{ field: string; after: string; fillsBlank: boolean }>;
      dropped: {
        unknownCitations: Array<{ label: string; chapters: number[] }>;
        speechEchoes: number;
      };
    };

    expect(result.proposals.map((item) => item.field)).toEqual(["personality"]);
    expect(result.proposals[0].fillsBlank).toBe(true);
    expect(result.dropped.unknownCitations).toEqual([
      { label: "役割", chapters: [17] },
    ]);
    expect(result.dropped.speechEchoes).toBe(1);

    // **製品が通る関数と同じ答え**（写しを持っていれば、ここがずれる）
    const record = readCharacter(folder, "char_0001.json");
    const excerpts = collectMentionExcerpts(
      productSources(folder),
      searchTermsFor("character", record)
    );
    const parsed = parseEnrichResult(response);
    if (!parsed) throw new Error("応答を読めない");
    const product = checkEnrichProposals({
      kind: "character",
      record,
      customFields: [],
      parsed,
      excerptText: excerpts.map((excerpt) => excerpt.text).join("\n"),
      knownChapters: new Set([1, 2]),
    });
    expect(result.proposals.map((item) => [item.field, item.after])).toEqual(
      product.proposals.map((item) => [item.field.key, item.after])
    );
  });

  test("はじいた記述は本文と照合し、照合できないものは落として数える", () => {
    const folder = makeWork();
    const response = JSON.stringify({
      gender: null,
      summary: null,
      affiliation: null,
      role: null,
      personality: null,
      speechStyle: null,
      appearance: null,
      misattributed: [
        {
          belongsTo: "宗一",
          field: "personality",
          value: "無口",
          evidence: "宗一は黙って船を見ていた。",
        },
        {
          belongsTo: "宗一",
          field: "personality",
          value: "陽気",
          evidence: "本文に無い作り話の引用",
        },
      ],
    });
    const result = novelValidate(call(folder, { name: "美咲" }, { response })) as {
      misattributed: Array<{ belongsTo: string; value: string }>;
      dropped: { misattributed: number };
    };
    expect(result.misattributed.map((item) => item.value)).toEqual(["無口"]);
    expect(result.dropped.misattributed).toBe(1);
  });

  test("読めない応答は断る（空として流さない）", () => {
    const folder = makeWork();
    expect(() =>
      novelValidate(call(folder, { name: "美咲" }, { response: "わかりません" }))
    ).toThrow(/読み取れません/);
  });
});

describe("作者が書いた項目は提案の対象にしない", () => {
  test("確定した人物の、作者の値がある欄は承認待ちの案に入れない（空欄を埋める案は入れる）", () => {
    const folder = makeWork();
    const response = JSON.stringify({
      gender: "男性",
      summary: null,
      affiliation: null,
      role: null,
      personality: "寡黙で、船から目を離さない",
      speechStyle: null,
      appearance: null,
      // スキーマに無い欄が返っても、提案にはしない
      authorNotes: "AIが書き換えた作者メモ",
      misattributed: [],
    });
    const result = novelValidate(call(folder, { name: "宗一" }, { response })) as {
      autoGenerated: boolean;
      proposals: Array<{ field: string }>;
      proposeArgs: { changes: Record<string, unknown> } | null;
      notProposed: Array<{ field: string; reason: string }>;
    };
    expect(result.autoGenerated).toBe(false);
    // 画面と同じく、提案としては見せる（作者が自分で選ぶもの）
    expect(result.proposals.map((item) => item.field).sort()).toEqual(
      ["gender", "personality"].sort()
    );
    // 承認待ちへ置く案には、作者の値の置き換えを入れない
    expect(result.proposeArgs?.changes).toEqual({ gender: "男性" });
    expect(result.notProposed.map((item) => item.field)).toEqual(["personality"]);
    expect(result.notProposed[0].reason).toMatch(/作者/);

    const all = JSON.stringify(result);
    expect(all).not.toContain("AIが書き換えた作者メモ");
    expect(all).not.toContain("authorNotes");
  });

  test("提案できる項目の表に、作者メモ・資料用の補足・呼称・確定の印は無い", () => {
    for (const kind of ["character", "ability", "organization", "location", "world"] as const) {
      const keys = enrichableFields(kind).map((field) => field.key);
      for (const key of ["authorNotes", "exportNote", "addressTerms", "autoGenerated", "authorLocked", "id", "name"]) {
        expect(keys).not.toContain(key);
      }
    }
  });
});

describe("結果は資料へ直接書かない", () => {
  test("prompt・validate・run（claude と ollama）のどれも、作品フォルダーを1バイトも変えない", async () => {
    const folder = makeWork();
    const before = fingerprint(folder);
    const response = JSON.stringify({
      gender: "女性",
      summary: null,
      affiliation: null,
      role: null,
      personality: "明るく、ためらわずに動く",
      speechStyle: "一人称は「あたし」。語尾を伸ばす",
      appearance: null,
      misattributed: [],
    });

    novelPrompt(call(folder, { name: "美咲" }));
    novelValidate(call(folder, { name: "美咲" }, { response }));
    const claude = (await novelRun(
      call(folder, { name: "美咲" }, { runner: "claude" })
    )) as { runner: string; userPrompt: string };
    expect(claude.runner).toBe("claude");

    ollamaReply = response;
    const ollama = (await novelRun(
      call(folder, { name: "美咲" }, { runner: "ollama", model: "test-model" })
    )) as {
      runner: string;
      result: {
        proposals: Array<{ field: string }>;
        proposeArgs: {
          kind: string;
          recordKind: string;
          name: string;
          reason: string;
          changes: Record<string, unknown>;
        } | null;
      };
    };
    expect(ollama.runner).toBe("ollama");
    expect(ollama.result.proposals.map((item) => item.field)).toContain("speechStyle");
    // **呼び手が novel.propose へそのまま渡せる形**で返す（置くのは呼び手）
    expect(ollama.result.proposeArgs).toMatchObject({
      kind: "settings",
      recordKind: "character",
      name: "美咲",
      changes: {
        gender: "女性",
        personality: "明るく、ためらわずに動く",
        speechStyle: "一人称は「あたし」。語尾を伸ばす",
      },
    });
    expect(ollama.result.proposeArgs?.reason).toBeTruthy();

    expect(fingerprint(folder)).toBe(before);
    expect(fs.existsSync(nodePath.join(folder, ".aiwriter"))).toBe(false);
  });
});
