import type { SettingsExportData } from "../../../src/core/settingsExportProfiles";
import { emptyAbility, emptyAbilitySystem } from "../../../src/models/ability";
import { emptyCharacter, type Character } from "../../../src/models/character";
import { emptyLocation } from "../../../src/models/location";
import { emptyOrganization } from "../../../src/models/organization";
import { emptyWorldItem } from "../../../src/models/world";

/**
 * 設定資料の書き出し（設計書6.75）の試験材料。
 *
 * **Markdown・HTML・CSV・Word・差分が同じ材料を読む。** 形式ごとに材料を
 * 作ると、「Markdown では伏せた名前が CSV から漏れる」ような食い違いを
 * 試験が見落とす（同じ材料で比べて初めて分かる）。
 *
 * 伏せるべきものを意図して混ぜてある：作者だけの印の人物（終幕の男）、
 * 第9話で初めて出る人物（白鳥）、未登場の人物、作者のメモ（authorNotes）。
 */

export const FIXTURE_AT = new Date(2026, 8, 5, 14, 30, 0);

export const FIXTURE_OPTIONS = {
  workTitle: "灯の塔",
  authorName: "野中ひさ",
  at: FIXTURE_AT,
};

/** 作者のメモ。**どの形式にも出てはいけない** */
export const AUTHOR_NOTE_TEXT = "作者だけの覚え書き：結末で灯は消える";

/** 作者だけの印を付けた人物の名前。**どの形式にも出てはいけない** */
export const HIDDEN_NAME = "終幕の男";

function main(): Character {
  return {
    ...emptyCharacter("char_001", "月島灯"),
    reading: "つきしまあかり",
    aliases: ["灯ちゃん"],
    summary: "主人公。転生した女子高生。",
    gender: "女性",
    affiliation: "窓口課",
    role: "案内係",
    personality: "人見知りだが芯は強い",
    appearance: "小柄で猫っ毛",
    physical: {
      age: "17歳",
      height: "152cm",
      build: "細身",
      hair: "黒のショート",
      eyes: "琥珀色",
      skin: "色白",
      distinctive: "左目の下にほくろ",
      clothing: "紺のブレザーに赤いマフラー",
    },
    firstPerson: {
      default: "わたし",
      variants: [
        { form: "あたし", context: "親しい相手", chapters: [3], evidence: null },
      ],
    },
    defaultSecondPerson: "あなた",
    addressTerms: [
      {
        targetName: "白鳥",
        targetId: null,
        forms: [
          {
            term: "白鳥さん",
            category: null,
            context: null,
            firstChapter: 9,
            lastChapter: null,
            status: "current",
            evidence: null,
          },
        ],
        authorLocked: false,
      },
      {
        targetName: HIDDEN_NAME,
        targetId: null,
        forms: [
          {
            term: "あの人",
            category: null,
            context: null,
            firstChapter: 1,
            lastChapter: null,
            status: "current",
            evidence: null,
          },
        ],
        authorLocked: false,
      },
    ],
    relations: [
      { name: "白鳥", relation: "同僚" },
      { name: HIDDEN_NAME, relation: "宿敵" },
    ],
    abilities: [
      {
        abilityId: "abil_001",
        name: "霊視",
        mastery: "習得済み",
        note: null,
        firstChapter: 2,
        appearedChapters: [2],
        evidence: null,
        autoGenerated: true,
      },
    ],
    appearedChapters: [1, 2, 3],
    authorNotes: AUTHOR_NOTE_TEXT,
    exportNote: "資料向けの補足, \"引用\"あり",
    customFields: { theme: "再生" },
    conflicts: [
      {
        field: "appearance",
        values: ["黒髪", "銀髪"],
        chapters: [1, 7],
        note: null,
        observations: [
          { value: "黒髪", chapters: [1] },
          { value: "銀髪", chapters: [7] },
        ],
      },
    ],
    changes: [
      {
        field: "role",
        value: "案内係",
        chapters: [1],
        timepointId: null,
        note: null,
        evidence: null,
        source: "extracted",
      },
    ],
    aiNotes: [
      {
        id: "note_001",
        createdAt: "",
        topic: "内面",
        text: "母への負い目が行動の軸になっている。\n二行目 <b>&</b>",
        model: "gemma",
        source: "deep_dive",
      },
    ],
  };
}

export function fixtureData(): SettingsExportData {
  return {
    characters: [
      main(),
      {
        ...emptyCharacter("char_002", "白鳥"),
        reading: "しらとり",
        summary: "第9話で現れる同僚。",
        affiliation: "窓口課",
        appearedChapters: [9],
      },
      {
        ...emptyCharacter("char_003", HIDDEN_NAME),
        summary: "黒幕。",
        spoilerLevel: "author_only",
        appearedChapters: [1],
      },
      {
        ...emptyCharacter("char_004", "通行人たち"),
        isMob: true,
        appearedChapters: [1, 2],
      },
    ],
    locations: [
      {
        ...emptyLocation("loc_001", "図書塔"),
        reading: "としょとう",
        aliases: ["塔"],
        summary: "物語の起点になる建物。",
        region: "王都",
        description: "石造りの八角形。<屋根>に銅の風見鶏 & 鐘。",
        appearedChapters: [1, 2],
        exportNote: "外観の資料あり",
      },
      {
        ...emptyLocation("loc_002", "港"),
        description: "霧の多い港。",
        appearedChapters: [2],
      },
    ],
    abilities: [
      {
        ...emptyAbility("abil_001", "霊視"),
        summary: "死者の残滓が見える。",
        description: "触れた物の記憶を読む。",
        cost: "頭痛",
        userNames: ["月島灯", HIDDEN_NAME],
        appearedChapters: [2],
      },
    ],
    abilitySystem: emptyAbilitySystem(),
    organizations: [
      {
        ...emptyOrganization("org_001", "窓口課"),
        summary: "主人公の職場。",
        description: "市役所の一部署。",
        appearedChapters: [1],
      },
    ],
    world: [
      {
        ...emptyWorldItem("wld_001", "残滓"),
        description: "死者が遺す想いの断片。",
        appearedChapters: [1],
      },
      {
        ...emptyWorldItem("wld_002", "灯守"),
        category: "society",
        description: "灯を守る役目。\n二行目もある。",
        appearedChapters: [3],
      },
    ],
    customFields: [
      { key: "theme", label: "主題", hint: "", multiline: false },
    ],
  };
}
