import type { Chunk } from "./chunker";
import {
  DESCRIPTIVE_ROLE_WORDS,
  GENERIC_ROLE_WORDS,
  KINSHIP_WORDS,
  PRONOUN_WORDS,
} from "./genericPersonWords";
import { stripHonorific } from "./nameHonorific";
import { familyNameCandidates } from "./familyName";
import { chaptersForCandidate, isGroundedInChunk } from "./groundedEvidence";
import {
  clampSpeechStyle,
  isSpeechStyleEcho,
  speechQuoteProblem,
  type SpeechStyleRejectionReason,
} from "./speechStyle";
import type {
  CharacterExtractResult,
  ExtractedCharacter,
} from "../prompts/characterExtract";

export type CharacterRejectionReason =
  | "invalid_shape"
  | "invalid_name"
  /** 名前が代名詞だけ（「僕」「あんた」）。誰を指しているのか決められない */
  | "pronoun_name"
  /**
   * 呼び名ではなく説明（「主人公」「密倉の母親」）。
   * AIがその場で作った言い方で、本文の誰もそう呼んでいない
   */
  | "descriptive_name"
  | "non_person"
  | "collective"
  | "ungrounded";

/**
 * 捨てたレコードの中身。**名前を決められなかった2つの理由のときだけ**持つ
 * （`pronoun_name`・`descriptive_name`）。
 *
 * 一人称の作品では、語り手が自分の名前を名乗らないことがある。AIは外見や
 * 性格まで読み取っていても「僕」「語り手」としか呼べず、レコードごと捨てられる。
 * **捨てること自体は正しい**（「僕」という名前の人物が台帳に入ったら壊れる）が、
 * 件数しか残らないと、作者には「認識していそうなのに増えない」としか見えない。
 * そこで中身を持ち回し、完了報告へ添える（設計書6.10.6 の「落としたことを言う」）。
 *
 * ほかの理由（`ungrounded` など）には付けない。語り手の可能性があるのは
 * この2つだけで、全部に付けると報告が騒がしくなり肝心の行が読まれなくなる。
 *
 * 項目を絞っているのは、**作者が「誰のことか」を見当できれば足りる**ためである。
 */
export interface RejectedCharacterDetails {
  /** 紹介 */
  summary?: string;
  /** 役割 */
  role?: string;
  /** 外見 */
  appearance?: string;
  /** 性別 */
  gender?: string;
}

export interface RejectedCharacterCandidate {
  name: string | null;
  reason: CharacterRejectionReason;
  /**
   * 捨てたレコードの中身。中身のある項目が1つも無ければ**付けない**
   * （空の括弧が並ぶだけの報告にしないため）。
   */
  details?: RejectedCharacterDetails;
}

export interface AcceptedCharacterCandidate {
  data: ExtractedCharacter;
  chapters: number[];
}

/** 別名を落としたことの記録。**黙って消さない**ので、報告に出すために持つ */
export interface DroppedAliasRecord {
  /** 落とした先の人物 */
  characterName: string;
  /** 落とした別名 */
  alias: string;
  /** 落とした理由になった相手（体の共有のときだけ） */
  partner?: string;
}

/**
 * 関係を落とした理由。**2通りを分けて持つ**（作者の裁定、2026-09-19）。
 *
 * - `not_a_relation`：**言い回し**で落としたもの。推測・伝聞・「本文に書かれて
 *   いない」という断りを、関係の値として書いてきた（`not_an_ability`・
 *   `not_a_place` と同じ作法）
 * - `sentence_shaped`：**構造**で落としたもの。関係の欄に短い語ではなく
 *   文が入っていた
 *
 * 分けて持つのは、**次にどちらの網を直せばよいかを記録から読むため**である。
 * 言い回しの表は言い換えられるたびに増えるので、構造だけで落ちた件数が
 * 見えないと、表を足す意味があったのか測れない。
 */
export type RelationRejectionReason = "not_a_relation" | "sentence_shaped";

/** 関係を落としたことの記録。**黙って消さない**ので、報告に出すために持つ */
export interface DroppedRelationRecord {
  /** 落とした先の人物 */
  characterName: string;
  /** 関係の相手 */
  partner: string;
  /** AIが書いてきた関係（落とした値そのまま） */
  relation: string;
  reason: RelationRejectionReason;
}

/**
 * 口調を落としたことの記録（2026-09-25）。**人物は残し、口調の欄だけを外す。**
 * 黙って消さないので、報告に出すために持つ。
 */
export interface DroppedSpeechStyleRecord {
  characterName: string;
  /** AIが書いてきた口調（落とした値そのまま） */
  speechStyle: string;
  /** AIが根拠として写してきた台詞（無ければ null） */
  speechEvidence: string | null;
  reason: SpeechStyleRejectionReason;
}

/** 向きが逆だった関係を直した記録（設計書6.18） */
export interface CorrectedRelationRecord {
  characterName: string;
  /** 相手の名前（「お母さん」など、親族語を含んだ呼び名） */
  partner: string;
  /** AIが書いてきた関係（この人物側から見た語＝逆向き） */
  from: string;
  /** 直したあとの関係（相手側から見た語） */
  to: string;
}

export interface CharacterValidationResult {
  accepted: AcceptedCharacterCandidate[];
  rejected: RejectedCharacterCandidate[];
  /**
   * 憑依・転生などで体を共有している相手の呼び名を、別名から落としたもの。
   * AIは「体を共有＝同一人物が別の呼称で登場」と読むため、コードで検算する。
   */
  droppedSharedBodyAliases: DroppedAliasRecord[];
  /** 敬称の途中で切れた別名として落としたもの（「母親さ」） */
  droppedTruncatedAliases: DroppedAliasRecord[];
  /**
   * 2人以上が名乗る姓だったため、別名から落としたもの（「中神」「中神くん」）。
   * 誰を指しているのか決められない呼び名なので、誰の別名にもしない。
   */
  droppedSharedFamilyNameAliases: DroppedAliasRecord[];
  /**
   * 自分の身内を指す別名として落としたもの（息子のレコードの「三門の母」）。
   * AIが本人の別名として返してくるので、コードで検算する。
   */
  droppedRelativeAliases: DroppedAliasRecord[];
  /**
   * 関係ではないもの（推測・伝聞・「本文に書かれていない」という断り、
   * および関係の欄に入った文）として落とした関係。AIが自分で
   * 「明記されていない」と書きながら関係を立てるので、コードで検算する。
   * どちらの網で落ちたかは `reason` に入る。
   */
  droppedRelations: DroppedRelationRecord[];
  /** 向きが逆だった親族関係を直したもの（相手「お母さん」に「息子」） */
  correctedRelations: CorrectedRelationRecord[];
  /**
   * 口調の欄だけを外したもの（2026-09-25）。根拠の台詞が本文の台詞に
   * 無い・指示の言葉の写し、のどちらか。人物そのものは受け入れている。
   */
  droppedSpeechStyles: DroppedSpeechStyleRecord[];
}

export interface CharacterValidationOptions {
  /**
   * 既存レコードの名前・別名。
   *
   * 途中で切れた別名（「母親さ」）を弾くには、**完全な形が実在する裏付け**が要る。
   * 同じ抽出結果の中だけでは足りない——切れた形だけが返ってきた話もあるため。
   */
  knownNames?: readonly string[];
  /**
   * 作者が手で書いた既存レコード（`autoGenerated: false`）の名前。
   *
   * この人物の別名には**コードの検算でも触らない**（CLAUDE.md 規則2）。
   * 姓が共有されていても、作者が「この人をそう呼ぶ」と書いたのなら、
   * AIの読みを直す話ではない。
   */
  authorEditedNames?: readonly string[];
  /**
   * AIに「既知の登場人物」として見せた名前・別名（既存レコード＋この回で
   * すでに受け入れた人物）。
   *
   * **name がここにあれば、その話の本文に name が無くても根拠なしにしない**
   * （2026-09-24 の裁定。引用の照合は残す）。プロンプトは「既知と同じなら
   * 既知の名前を name に」と頼んでいるので、本文が「相沢くん」としか
   * 書かない話では、指示どおりの「相沢 春人」が必ず落ちていた。
   *
   * `knownNames` と分けるのは、あちらが**ループの前に1回だけ作る**
   * （切れた別名の裏付けを実行ごとに揺らさない）のに対し、こちらは
   * AIに見せたものと揃える必要があるため。
   */
  knownRecordNames?: readonly string[];
}

const MAX_NAME_LENGTH = 30;
const SENTENCE_PUNCTUATION = /[、。，,.！？!?；;：:\r\n]/u;
const WRAPPING_PUNCTUATION =
  /^(?:[「『“‘"（(【《〈])|(?:[」』”’"）)】》〉])$/u;
// 助詞だけでは「こはる」のような名前も巻き込むため、文末の活用形まで限定する。
const SENTENCE_LIKE_NAME_PATTERN =
  /[はがをにへでとも][^、。！？!?\r\n]{1,20}(?:った|いた|した|された|ていた|ている|している|なかった|だった|でした|ました|ません)$/u;
/**
 * 名前の代わりに置かれる穴埋め語。
 *
 * **「主人公」はここから外した**（0.43.4）。同じ形の「密倉の母親」
 * 「語り手」と揃えて `descriptive_name` で弾く——理由が分かれていると、
 * 完了報告で「説明的な名前が何件返ってきたか」が読めない。
 */
const PLACEHOLDER_NAME_PATTERN =
  /^(null|undefined|不明|なし|誰か|n\/?a|none|[（(]?主[）)]?)$/i;

/**
 * それ自体が「値が無い」ことしか言っていない語。
 *
 * 名前用の `PLACEHOLDER_NAME_PATTERN`・`DESCRIPTIVE_ROLE_WORDS` は使い回せない。
 * あちらは「誰か」「主人公」を弾くが、これらは役割の値としては正しい
 * （role: "主人公"）。
 */
const EMPTY_VALUE_PATTERN =
  /^[（(]?(?:null|undefined|n\/?a|none|なし|無し|不明|未詳|記述なし|記載なし|描写なし|該当なし|特になし|読み取れない|判断できない|見当たらない|[-—―ー・?？])[）)]?$/i;

/**
 * 「〜の記述はなし」と、値の代わりに不在を述べている文。
 *
 * AIは null にする代わりに「（本文から読み取れる性格に関する記述なし）」と
 * 書いてくることがあり、そのまま設定資料へ載っていた（実データで発生）。
 * プロンプトでも禁じているが、指示だけでは守られないのでコード側でも弾く。
 *
 * **不在を述べたあとに中身が続く文は残す。**
 * 「（生前の記述は本文中になし。憑依後は手足がスラリとしている）」のように、
 * 後半に本当の情報が入っていることがある。
 * 同じ理由で「記述は少ない」も残す（無いとは言っていない）。
 */
const ABSENCE_SENTENCE_PATTERN =
  /^[（(]?[^)）]{0,30}(?:記述|描写|言及|記載|情報)(?:は)?(?:なし|無し|ありません|ない)[。.]?[）)]?$/u;

/**
 * 「本文から読み取れない」型の不在文。
 *
 * 上の2つでは**実データを取りこぼしていた**（2026-08-15に発見）。
 * 「（本文から読み取れない）」は語の前に「本文から」が付くため
 * `EMPTY_VALUE_PATTERN` に一致せず、「記述は確認できない」は
 * 「記述」と「ない」の間に動詞が挟まるため `ABSENCE_SENTENCE_PATTERN` にも
 * 一致しなかった。結果、主人公の性格欄に「（本文から読み取れない）」が
 * そのまま載っていた。
 *
 * 誤って消さないための条件を2つ置く。
 * 1. **本文・記述・描写などの語を含むこと。** 「感情の起伏がない」のように
 *    それ自体が性格である値を消さないため
 * 2. **文の途中に句点が無いこと。** 「（生前の記述は本文中になし。憑依後は
 *    手足がスラリとしている）」のように、不在を述べたあと中身が続く値を残すため
 *
 * 「記述は少ない」を消さないよう、打ち消しの語も限定して並べる（「少ない」は入れない）。
 */
const ABSENCE_NEGATION_PATTERN =
  /^[（(]?[^)）。]{0,50}(?:本文|記述|描写|言及|記載|情報)[^)）。]{0,20}(?:読み取れない|確認できない|見当たらない|判断できない|特定できない|わからない|分からない|ありません|存在しない)[。.]?[）)]?$/u;

/**
 * 中身のある値か。空欄と同じ扱いにするものを弾く。
 *
 * 名前ではなく説明系の項目（性格・外見・説明など）に使う。
 */
export function isMeaningfulValue(value: string | null | undefined): boolean {
  if (!value) return false;
  const text = value.trim();
  if (!text) return false;
  if (EMPTY_VALUE_PATTERN.test(text)) return false;
  if (ABSENCE_SENTENCE_PATTERN.test(text)) return false;
  return !ABSENCE_NEGATION_PATTERN.test(text);
}
const COLLECTIVE_SUFFIX_PATTERN = /(?:たち|一同|一行|一団|人々|一族)$/u;
/**
 * 代名詞。一覧は `core/genericPersonWords.ts` が1か所で持つ（設計書6.5.9）。
 * 「重複をまとめる」の側も同じ一覧を見るので、写しを作らない。
 */
const PRONOUNS = new Set(PRONOUN_WORDS);
/**
 * 説明的な役割語・家族関係語。一覧は同じく `genericPersonWords.ts` が持つ。
 * 家族関係語は**単独では弾かない**——「〇〇の△△」の△△を見るためだけに使う。
 */
const DESCRIPTIVE_ROLES = new Set(DESCRIPTIVE_ROLE_WORDS);
/**
 * 家族関係語。**単独では弾かない**——「〇〇の△△」の△△を見るためだけに使う
 * （`isOwnRelativeAlias`）。一覧は `genericPersonWords.ts` が1か所で持つ。
 */
const KINSHIP = new Set(KINSHIP_WORDS);

/**
 * 職業・立場を指すだけの語。一覧は `genericPersonWords.ts` が1か所で持つ。
 *
 * **名寄せ（`characterMerge.ts`）も同じ一覧を見る。** 写しを持っていた頃は、
 * 抽出では弾く語が名寄せでは同一人物の根拠になっていた（設計書6.5.9）。
 */
const GENERIC_ROLES = new Set(GENERIC_ROLE_WORDS);
const ENTITY_TYPES = new Set(["person", "group", "location", "unknown"]);

/**
 * AI応答を人物マージへ渡せる形に正規化し、受理・除外理由を分ける。
 * AIが返した候補は信頼せず、各候補を必ず1つの結果にだけ分類する。
 */
export function validateCharacterExtractResult(
  result: CharacterExtractResult,
  chunk: Chunk,
  options: CharacterValidationOptions = {}
): CharacterValidationResult {
  const accepted: AcceptedCharacterCandidate[] = [];
  const rejected: RejectedCharacterCandidate[] = [];
  const droppedSharedBodyAliases: DroppedAliasRecord[] = [];
  const droppedTruncatedAliases: DroppedAliasRecord[] = [];
  const droppedSharedFamilyNameAliases: DroppedAliasRecord[] = [];
  const droppedRelativeAliases: DroppedAliasRecord[] = [];
  const droppedRelations: DroppedRelationRecord[] = [];
  const correctedRelations: CorrectedRelationRecord[] = [];
  const droppedSpeechStyles: DroppedSpeechStyleRecord[] = [];
  const rawCharacters: unknown = result.characters;

  if (!Array.isArray(rawCharacters)) {
    return {
      accepted,
      rejected: [{ name: null, reason: "invalid_shape" }],
      droppedSharedBodyAliases,
      droppedTruncatedAliases,
      droppedSharedFamilyNameAliases,
      droppedRelativeAliases,
      droppedRelations,
      correctedRelations,
      droppedSpeechStyles,
    };
  }

  // **根拠の照合より前に、別名の掃除を済ませる。**
  // 別名は話数の割り当てにも使われるので、別人の呼び名が混ざったままだと、
  // その人物が出ていない話まで「登場」として付いてしまう。
  //
  // ただし**根拠の照合には掃除前の呼び名を使う**（`groundingNames`）。
  // AIは「母親さん」と書かれた場面から圭織のレコードを作り、引用にも
  // その呼び名しか入れてこないことがある。掃除後の名前で照合すると、
  // 本文に実在する人物が「根拠なし」で消える。
  const survived: ExtractedCharacter[] = [];
  const groundingNames = new Map<ExtractedCharacter, string[]>();
  for (const raw of rawCharacters) {
    if (!isRecord(raw) || typeof raw.name !== "string") {
      rejected.push({ name: candidateName(raw), reason: "invalid_shape" });
      continue;
    }
    if (
      "entityType" in raw &&
      raw.entityType !== undefined &&
      (typeof raw.entityType !== "string" || !ENTITY_TYPES.has(raw.entityType))
    ) {
      rejected.push({ name: raw.name.trim() || null, reason: "invalid_shape" });
      continue;
    }

    const character = normalizeExtractedCharacter(raw);
    if (!isValidName(character.name)) {
      rejected.push({ name: character.name, reason: "invalid_name" });
      continue;
    }
    // 代名詞だけの名前は、誰を指しているのか決められない（設計書6.5.9）。
    // **プロンプトで禁じても返ってくる**——qwen3:8b でも gemma4:26b でも
    // 「僕」という人物レコードが作られた（実機確認A-18の2026-09-08）ので、
    // コードで弾く。捨てた件数と理由は完了報告に出す（黙って捨てない）
    if (isPronounName(character.name)) {
      rejected.push(rejectedWithDetails(character, "pronoun_name"));
      continue;
    }
    // 説明的な名前（「主人公」「密倉の母親」）は、AIがその場で作った言い方で、
    // 本文の誰もそう呼んでいない（設計書6.5.9）。プロンプトは
    // 「仮の名前や説明的な名前を発明してレコードを作らない」と禁じているが
    // gemma4:26b でも返ってきた。**代名詞と同じく、理由付きで除外して報告に出す**
    if (isDescriptiveName(character.name)) {
      rejected.push(rejectedWithDetails(character, "descriptive_name"));
      continue;
    }
    // 「兵士たち」のような集団名詞はモブとして残す。
    // 本文に出ている以上、消すと情報が失われるため、
    // ネームドキャラと区別できる印を付けたうえで保持する。
    //
    // 対象を集団名詞に限るのは、entityType: "group" が
    // 「星環評議会」（組織）や「銀翼族」（種族）にも使われるためである。
    // 組織や種族はモブキャラではないので、これまでどおり除外する。
    // 「姉」「先生」のような関係語・汎用役職も、特定個人を指す参照であり
    // 群衆ではないため対象にしない。
    if (isCollectiveName(character.name)) {
      character.isMob = true;
    } else if (
      (character.entityType !== undefined &&
        character.entityType !== "person") ||
      GENERIC_ROLES.has(character.name)
    ) {
      rejected.push({ name: character.name, reason: "non_person" });
      continue;
    }

    // 自分の身内を指す別名は `normalizeExtractedCharacter` が既に落としている。
    // あちらは純粋な正規化で記録を持てないので、**生の別名と突き合わせて
    // ここで拾う**——落とした分は黙って捨てず、完了報告に出す
    for (const alias of cleanStringArray(raw.aliases)) {
      if (alias === character.name) continue;
      if (!isOwnRelativeAlias(alias, character.name)) continue;
      droppedRelativeAliases.push({ characterName: character.name, alias });
    }

    survived.push(character);
    groundingNames.set(character, [
      character.name,
      ...(character.aliases ?? []),
    ]);
  }

  // 別人の呼び名・切れた呼び名を別名から落とし、関係の向きを直す。
  // どれも**AIの読みをコードで検算する**もので、落とした分は結果に載せる
  cleanSharedBodyAliases(survived, droppedSharedBodyAliases);
  cleanTruncatedAliases(
    survived,
    options.knownNames ?? [],
    droppedTruncatedAliases
  );
  cleanSharedFamilyNameAliases(
    survived,
    options.authorEditedNames ?? [],
    droppedSharedFamilyNameAliases
  );
  // **姓の検算より後に置く。** 推測で書かれた関係でも「相手の名前」のほうは
  // 本文の呼び名で、同じ姓の人が複数いることの証拠になる
  // （`cleanSharedFamilyNameAliases`）。先に捨てるとその証拠まで消える
  dropSpeculativeRelations(survived, droppedRelations);
  fixRelationDirections(survived, correctedRelations);

  for (const character of survived) {
    const names = groundingNames.get(character) ?? [character.name];
    const knownRecordNames = options.knownRecordNames ?? [];
    if (
      !isGroundedInChunk(names, character.evidence, chunk.text, knownRecordNames)
    ) {
      // **口調の根拠の台詞でも、この話にいることの裏付けになる**（2026-09-25）。
      // 口調の欄を足したあと、gemma4:26b が人物の引用を名前だけ（「太志」）や
      // 言い換え（「自称天使が、」→本文は「自称天使は」）で返し、台詞のほうは
      // 逐語で写してくる回が増えた（作品の写し3作で、根拠なしが前後2回とも
      // 1〜2件→6件）。台詞も本文からの逐語引用で、名前の照合は同じく掛かる
      // ので、捏造を通す穴にはならない。通ったら、資料に残す根拠も台詞に替える
      // （言い換えた引用を「抽出根拠」として残さない）
      const speechQuote = character.speechEvidence?.trim();
      if (
        !speechQuote ||
        !isGroundedInChunk(names, speechQuote, chunk.text, knownRecordNames)
      ) {
        rejected.push({ name: character.name, reason: "ungrounded" });
        continue;
      }
      character.evidence = speechQuote;
    }

    // 口調は、根拠の台詞が本文の台詞の中にあるときだけ残す（2026-09-25）。
    // **人物ごとは落とさない**——口調が読めなかっただけで、人物は本文にいる
    checkSpeechStyle(character, chunk.text, droppedSpeechStyles);

    // 話数は、引用が本文のどの位置にあるかで決める。
    // 複数の話をまとめて送っているとき、チャンク全体の話数を付けると
    // 「第3話にしか出ない人物が第1〜4話に登場」になってしまう
    accepted.push({
      data: character,
      chapters: chaptersForCandidate(
        chunk,
        [character.name, ...(character.aliases ?? [])],
        character.evidence
      ),
    });
  }

  return {
    accepted,
    rejected,
    droppedSharedBodyAliases,
    droppedTruncatedAliases,
    droppedSharedFamilyNameAliases,
    droppedRelativeAliases,
    droppedRelations,
    correctedRelations,
    droppedSpeechStyles,
  };
}

/**
 * 口調の欄を検算する（2026-09-25。`core/speechStyle.ts`）。**渡した候補を書き換える。**
 *
 * - 値が空・不在文（「記述なし」）→ 黙って外す（空欄と同じ。報告に出す値が無い）
 * - 指示の言葉・例の写し → 外して記録（`instruction_echo`）
 * - 根拠の台詞が無い・本文に無い・地の文 → 外して記録
 * - 通ったら長さの上限で切る（捨てずに切る。紹介と同じ）
 *
 * 根拠の引用（`speechEvidence`）は、通ったときだけ残す。マージが面の根拠として持つ。
 */
function checkSpeechStyle(
  character: ExtractedCharacter,
  chunkText: string,
  dropped: DroppedSpeechStyleRecord[]
): void {
  const value = character.speechStyle?.trim();
  const quote = character.speechEvidence?.trim() || null;
  const clear = (): void => {
    delete character.speechStyle;
    delete character.speechEvidence;
  };
  if (!value || !isMeaningfulValue(value)) {
    clear();
    return;
  }
  const reason: SpeechStyleRejectionReason | null = isSpeechStyleEcho(value, chunkText)
    ? "instruction_echo"
    : speechQuoteProblem(quote, chunkText);
  if (reason !== null) {
    dropped.push({
      characterName: character.name,
      speechStyle: value,
      speechEvidence: quote,
      reason,
    });
    clear();
    return;
  }
  character.speechStyle = clampSpeechStyle(value);
  character.speechEvidence = quote;
}

/**
 * 体を共有していても人格が別なら別人である、という検算（設計書6.5.9）。
 *
 * **AIは「憑依で体を共有＝同一人物が別の呼称で登場」と読む。**
 * プロンプトの【登場人物の抽出ルール】に禁止を足したが、指示だけでは守られない
 * （実データで `char_006_文佳` の別名に別人の「太志」「三門太志」が入った）。
 * 関係にそう書いてある以上、**その2人は別人である**と読めるので、
 * 相手の呼び名を自分の別名から落とす。
 *
 * **両方向に効かせる。** 「太志が文佳に憑依している」と書かれるのは
 * 片方のレコードだけのことが多く、汚染されるのはもう片方（文佳）の別名だった。
 * 片側からしか掃除しないと、実データで起きた汚染がそのまま残る。
 */
function cleanSharedBodyAliases(
  characters: ExtractedCharacter[],
  dropped: DroppedAliasRecord[]
): void {
  const byKey = new Map<string, ExtractedCharacter>();
  for (const character of characters) {
    byKey.set(normalizeForCompare(character.name), character);
    for (const alias of character.aliases ?? []) {
      if (!byKey.has(normalizeForCompare(alias))) {
        byKey.set(normalizeForCompare(alias), character);
      }
    }
  }

  // この人物の別名から落とすべき呼び名（正規化済み）→ 理由になった相手。
  // 相手の名前まで持つのは、報告で「誰と混ざったのか」を出すためである
  const blocked = new Map<ExtractedCharacter, Map<string, string>>();
  const block = (
    owner: ExtractedCharacter,
    names: readonly string[],
    partner: string
  ): void => {
    const keys = blocked.get(owner) ?? new Map<string, string>();
    const ownKey = normalizeForCompare(owner.name);
    for (const name of names) {
      const key = normalizeForCompare(name);
      // 自分自身の名前は落とさない。落とすと本人が引けなくなる
      if (!key || key === ownKey || keys.has(key)) continue;
      keys.set(key, partner);
    }
    blocked.set(owner, keys);
  };

  for (const character of characters) {
    for (const relation of character.relations ?? []) {
      if (!SHARED_BODY_RELATION.test(relation.relation)) continue;
      const other = byKey.get(normalizeForCompare(relation.name));
      if (other === character) continue;

      // 相手のレコードが同じ抽出結果にあれば、その name・aliases も落とす。
      // 無ければ関係に書かれた名前だけを落とす（レコードが後の話で作られる）
      const otherNames = other
        ? [other.name, ...(other.aliases ?? [])]
        : [relation.name];
      block(character, [relation.name, ...otherNames], relation.name);
      if (other) {
        block(other, [character.name, ...(character.aliases ?? [])], character.name);
      }
    }
  }

  for (const [character, keys] of blocked) {
    const kept: string[] = [];
    for (const alias of character.aliases ?? []) {
      const partner = keys.get(normalizeForCompare(alias));
      if (partner !== undefined) {
        dropped.push({ characterName: character.name, alias, partner });
        continue;
      }
      kept.push(alias);
    }
    character.aliases = kept;
  }
}

/**
 * 敬称の途中で切れた別名を落とす（「母親さ」＝「母親さん」の切れた形）。
 *
 * **裏付けのあるときだけ弾く。** 語尾だけで判定すると「つかさ」「おじいさま」
 * のような正しい呼び名まで落ちる。「ん」を足した形が、同じ抽出結果か
 * 既存レコードのどこかに実在するときに限る。
 */
function cleanTruncatedAliases(
  characters: ExtractedCharacter[],
  knownNames: readonly string[],
  dropped: DroppedAliasRecord[]
): void {
  const known = new Set<string>();
  for (const name of knownNames) known.add(normalizeSpacingOnly(name));
  for (const character of characters) {
    known.add(normalizeSpacingOnly(character.name));
    for (const alias of character.aliases ?? []) {
      known.add(normalizeSpacingOnly(alias));
    }
  }

  for (const character of characters) {
    const kept: string[] = [];
    for (const alias of character.aliases ?? []) {
      if (isTruncatedAlias(alias, known)) {
        dropped.push({ characterName: character.name, alias });
        continue;
      }
      kept.push(alias);
    }
    character.aliases = kept;
  }
}

/**
 * 2人以上が名乗る姓は、誰の別名にもしない（作者の報告、2026-09-12
 * 「苗字で存在が混ざってそうです」）。
 *
 * 実データで「中神」を名乗る人物が4人いるのに（鷹人・隼人・亜紀・杏奈）、
 * 姓だけの「中神」「中神くん」が鷹人ひとりの別名に付いていた。
 * 別名は**用語ハイライト・IME辞書・矛盾検知の手がかり**に使われるので、
 * 混ざったままだと別人の台詞や描写をこの人物のものとして数える。
 *
 * 歯止めは「重複をまとめる」側（`characterMerge.honorificFamilyNamePair`）に
 * しか無く、抽出の検算には無かった。姓の取り出しは
 * `familyName.familyNameCandidates` が1か所で持つ（写しを作らない）。
 *
 * **落とすのは、敬称を外すとその姓そのものになる別名だけ。**
 * 「中神鷹人」のように名まで含む形は本人を指すので残す。
 */
function cleanSharedFamilyNameAliases(
  characters: ExtractedCharacter[],
  authorEditedNames: readonly string[],
  dropped: DroppedAliasRecord[]
): void {
  // 姓 → その姓を名乗る人物。**レコード単位で数える**——
  // 同じ人物が空白あり・なしの両方で候補を出しても1人である
  const owners = new Map<string, Set<string>>();
  const note = (family: string, who: string): void => {
    const holders = owners.get(family) ?? new Set<string>();
    holders.add(who);
    owners.set(family, holders);
  };
  for (const character of characters) {
    const bare = normalizeSpacingOnly(character.name);
    for (const family of familyNameCandidates(character.name)) {
      note(family, bare);
    }
    /*
      **関係の相手も、その姓を名乗る人として数える**（本体の検収、2026-09-12）。

      レコードの名前だけを数えると、実データで発火しない。作者の画面では
      「中神 鷹人」のレコードに「中神隼人＝兄」「中神亜紀＝妻」が並んでいたが、
      **その2人のレコードが同じ抽出結果に立っているとは限らない**
      （後の話で作られる／別のチャンクに出る）。それでも**作中に同じ姓の人が
      複数いることの証拠としては十分**である。

      数えるのは**人の名前の形をしたものだけ**にする——関係の相手欄には
      「母親」「担任」のような役割語も入るので、姓の候補が取れるものに限る
      （`familyNameCandidates` が漢字の姓＋名しか返さない）。
    */
    for (const relation of character.relations ?? []) {
      const partner = normalizeSpacingOnly(relation.name ?? "");
      if (!partner) continue;
      for (const family of familyNameCandidates(relation.name)) {
        note(family, partner);
      }
    }
  }

  const ambiguous = new Set<string>();
  for (const [family, holders] of owners) {
    if (holders.size >= 2) ambiguous.add(family);
  }
  if (ambiguous.size === 0) return;

  const authorEdited = new Set(authorEditedNames.map(normalizeSpacingOnly));

  for (const character of characters) {
    const bareName = normalizeSpacingOnly(character.name);
    // 「中神」という名前の人物が立っているなら、その人にとって姓は本名である。
    // 別名（「中神さん」）も本人を指すので触らない
    if (ambiguous.has(bareName)) continue;
    // 作者が手で書いたレコードは、AIの読みを直す対象ではない（CLAUDE.md 規則2）
    if (authorEdited.has(bareName)) continue;

    const kept: string[] = [];
    for (const alias of character.aliases ?? []) {
      if (ambiguous.has(stripHonorific(normalizeSpacingOnly(alias)))) {
        dropped.push({ characterName: character.name, alias });
        continue;
      }
      kept.push(alias);
    }
    character.aliases = kept;
  }
}

/** 敬称の途中で切れた形になりうる語尾。「ん」が落ちた形だけを見る */
const TRUNCATED_ALIAS_TAILS = ["ちゃ", "さ", "く"] as const;

/**
 * その別名は「ん」が落ちた形か。
 *
 * `known` には、同じ抽出結果と既存レコードの名前・別名を
 * `normalizeSpacingOnly` 済みで入れる。**敬称は落とさない**——
 * 落とすと「太志く」の裏付けが「太志」で取れてしまい、判定にならない。
 */
export function isTruncatedAlias(
  alias: string,
  known: ReadonlySet<string>
): boolean {
  const text = alias.trim();
  // 1字だけの「さ」「く」は別名として意味を成さないが、
  // ここで弾くと語尾だけの判定になるので、裏付けの条件は同じにする
  if (text.length < 2) return false;
  if (!TRUNCATED_ALIAS_TAILS.some((tail) => text.endsWith(tail))) return false;
  return known.has(normalizeSpacingOnly(`${text}ん`));
}

/**
 * 「関係ではないもの」を関係から落とす（実装ルール3の検算）。
 *
 * **AIは自分で「明記されていない」と断りながら関係を書いてくる。**
 * 実データ（gemma4:26b、2026-09-19の測定）で
 * `{"from":"リーナ・ヴェイル","to":"ヨナ",
 *   "relation":"（関係性は明記されていないが、親密な様子が見られる）"}`
 * が出た。プロンプトP-04aは「推測で書かないこと。『仲が良さそう』
 * 『敵かもしれない』は関係ではありません」と既に禁じているので、
 * **指示ではなくコードで落とす**。
 *
 * 落とすのは**関係の言い方が推測・断りだったとき**だけで、相手の名前は見ない。
 * 名前のほうは本文に出ている呼び名でありうる。
 *
 * **網は2つある。** 言い回し（`isSpeculativeRelation`）と、構造
 * （`isSentenceShapedRelation`）。言い回しだけでは追いかけっこになるため
 * （同じ断りが「明記されていないが」とも「不明だが」とも書かれた）、
 * 「関係の欄に文が入っている」という形でも落とす。
 */
function dropSpeculativeRelations(
  characters: ExtractedCharacter[],
  dropped: DroppedRelationRecord[]
): void {
  for (const character of characters) {
    if (!character.relations) continue;
    const kept: NonNullable<ExtractedCharacter["relations"]> = [];
    for (const relation of character.relations) {
      const reason = relationRejectionReason(relation.relation);
      if (reason !== null) {
        dropped.push({
          characterName: character.name,
          partner: relation.name,
          relation: relation.relation,
          reason,
        });
        continue;
      }
      kept.push(relation);
    }
    character.relations = kept;
  }
}

/**
 * その関係を落とすか。落とすなら理由、残すなら null。
 *
 * **言い回しを先に見る。** 両方に当たる値（実測で出た
 * 「（関係性は明記されていないが、〜）」は両方に当たる）の理由が、
 * 網を足すたびに入れ替わると、前に取った測定結果と突き合わせられなくなる。
 */
function relationRejectionReason(
  relation: string
): RelationRejectionReason | null {
  if (isSpeculativeRelation(relation)) return "not_a_relation";
  if (isSentenceShapedRelation(relation)) return "sentence_shaped";
  return null;
}

/**
 * 関係の値が「関係」ではなく、推測・伝聞・不在の断りになっている言い方。
 *
 * **広げないことのほうが大事である。** 正しい関係を落とすと、資料から
 * その繋がりが消えて二度と戻らない——とくに「憑依している」「入れ替わっている」
 * 「その名を騙っている」は、**別人判定（`SHARED_BODY_RELATION`）の
 * 手がかり**でもあるので、落とすと人物の同一性の仕組みごと壊れる。
 * だから「言い切っていない印」がはっきり出ている形だけを並べる。
 */
const SPECULATIVE_RELATION_PATTERNS: readonly RegExp[] = [
  // 1. 本文に無いと自分で断った形（「関係性は明記されていない」）。
  //    「記載がない」「描写はありません」まで同じ形で拾う
  /(?:明記|記載|記述|描写|言及)(?:は|が|も)?(?:されて)?(?:い)?(?:ない|ありません|ません|無い|なし)/u,
  /書かれて(?:い)?(?:ない|ません)/u,
  // 「（関係性は不明だが、親密な様子が見える）」。2026-09-19の測定で、同じ
  // 断りが「明記されていない」とも「不明」とも書かれた——**同じ意味の
  // 言い換えは何通りでも出てくる**ので、関係そのものを不明と言った形も見る。
  // 「生死不明の兄」は落とさない（不明なのは関係ではなく安否である）
  /(?:関係性|関係|続柄|間柄)(?:は|が|も)?(?:不明|不詳|わからない|分からない|明らかで(?:は)?ない|特定できない)/u,
  // 「不明だが」「不明ながら」のように、断ったうえで様子を続ける形
  /不明(?:だ|です)?(?:が|けど|けれど|ものの|ながら)/u,
  // 2. 推量の助動詞・言い回し
  /かも(?:しれ|知れ)(?:ない|ません|ず)/u,
  /思われ(?:る|ます)/u,
  /推測|推察/u,
  /おそらく|恐らく/u,
  // 「恋人である可能性がある」。関係語そのものに「可能性」は入らない
  /可能性/u,
  /よう(?:だ|です)|ように(?:見え|思え|感じ)/u,
  /噂|うわさ/u,
  /断定(?:は)?できない|定かで(?:は)?ない/u,
  // 3. 様態の「〜そう」（「仲が良さそう」「険悪そうに見える」）。
  //    **末尾か、関係を言い換える名詞の直前だけ**に限る——真ん中の「そう」まで
  //    拾うと「そうだん相手」のような書き方を巻き込む
  /そう(?:だ|です|に見える|に思える|に感じる)?$/u,
  /そうな(?:関係|様子|雰囲気|仲|間柄)/u,
];

/**
 * その関係は、関係ではなく推測・断りか。
 *
 * 純粋関数にしてあるのは、**どこまで落とすかの境界をテストで固定する**
 * ためである（`correctRelationDirection` と同じ理由）。
 */
export function isSpeculativeRelation(relation: string): boolean {
  const value = relation.trim();
  if (!value) return false;
  // 「なし」「不明」「（記述なし）」のような、値が無いことしか言っていない形。
  // 判定は説明欄と1か所で持つ（同じものを2通りに書かない）
  if (!isMeaningfulValue(value)) return true;
  return SPECULATIVE_RELATION_PATTERNS.some((pattern) => pattern.test(value));
}

/**
 * 値が丸ごと括弧で囲まれている形。囲みの中身を取り出す。
 *
 * 中に別の括弧が入っている形は見ない（「（Aの（B））」のような入れ子は、
 * どこまでが囲みなのか形からは決められないため、落とさない側へ倒す）。
 */
const WHOLLY_PARENTHESIZED_RELATION = /^[（(]([^（()）]*)[）)]$/u;
/** 文の区切り。関係語には入らない */
const RELATION_SENTENCE_PUNCTUATION = /[、。，．,.]/u;
/**
 * 関係の値の長さの上限（字）。**実測の最大が34字**だったので、
 * 6字の余裕を足してここに置く。
 */
const RELATION_MAX_LENGTH = 40;
/**
 * 丸ごと括弧の中身の長さの上限（字）。**実データの唯一の例
 * 「（間接的な関わり）」が中身7字**だったので、倍以上の余裕を取ってここに置く。
 */
const PARENTHESIZED_RELATION_MAX_INNER_LENGTH = 15;

/**
 * その関係の値は、**関係語ではなく文**になっているか（構造で落とす網）。
 *
 * **言い回しの表だけでは追いかけっこになる。** 同じ条件で2回測っただけで、
 * AIは同じ断りを「（関係性は明記されていないが、…）」と
 * 「（関係性は不明だが、…）」の2通りで書いてきた（2026-09-19、gemma4:26b）。
 * 関係の欄に入るべきは「兄」「幼なじみ」「憑依している」のような**短い語**
 * であって文ではないので、**文であること自体**を理由に落とす
 * （作者の裁定、2026-09-19「構造でも切る」）。
 *
 * **線は推測ではなく実測で引いた。** 作者の設定資料13作品・157ファイルにある
 * 本物の関係 508件を数えた結果、
 *   - 長さは 最短1字／中央3字／p90 10字／p95 15字／p99 25字／**最大34字**
 *   - 句読点を含む値は15件（2.9%）で、**いずれも「同級生（引用）」の形**——
 *     括弧の外に関係語がある
 *   - **丸ごと括弧で囲まれた値は1件だけ**（「（間接的な関わり）」）で、
 *     その1件に句読点は無い
 * 下の3つの線は、この508件のどれにも当たらない（誤爆0件を確かめてから引いた）。
 *
 * **別人判定の手がかりは、構造では落とさない。** 「憑依している」
 * 「入れ替わっている」は人物の同一性を決める語で（`SHARED_BODY_RELATION`、
 * 設計書6.95）、実データにも括弧つき26字の形がある。落とすと、憑依した側と
 * された側が1つのレコードにまとまる。言い回しの網はこれまでどおり効かせる
 * （「憑依しているかもしれない」は推測なので落ちる）。
 */
export function isSentenceShapedRelation(relation: string): boolean {
  const value = relation.trim();
  if (!value) return false;
  if (SHARED_BODY_RELATION.test(value)) return false;

  // 1. 長すぎる。括弧を使わずに説明を書いてきた形を拾う
  if ([...value].length > RELATION_MAX_LENGTH) return true;

  // 2. 丸ごと括弧の断り書き。**関係語が1つも無く、注釈だけ**の形である。
  //    「案内役（引用）」のように括弧の外に関係語があるものは、
  //    関係として読めるのでここには入らない
  const inner = WHOLLY_PARENTHESIZED_RELATION.exec(value)?.[1];
  if (inner === undefined) return false;
  if (RELATION_SENTENCE_PUNCTUATION.test(inner)) return true;
  return [...inner].length >= PARENTHESIZED_RELATION_MAX_INNER_LENGTH;
}

/**
 * 親族関係の向きを直す（設計書6.18）。
 *
 * relations は**その人物のレコードから見た**相手との関係だが、
 * AIは自分の側の語を書いてくることがある（実データの `char_001_三門太志` に
 * `{"name":"お母さん","relation":"息子"}`）。相手の名前そのものに親族語が
 * 入っていれば、どちらから見た語かはコードで決められる。
 */
function fixRelationDirections(
  characters: ExtractedCharacter[],
  corrected: CorrectedRelationRecord[]
): void {
  for (const character of characters) {
    for (const relation of character.relations ?? []) {
      const fixed = correctRelationDirection(relation.name, relation.relation);
      if (fixed === null || fixed === relation.relation) continue;
      corrected.push({
        characterName: character.name,
        partner: relation.name,
        from: relation.relation,
        to: fixed,
      });
      relation.relation = fixed;
    }
  }
}

/**
 * 親族語の対。**相手の名前に入っている語**から、正しい関係語を決める。
 *
 * ひらがなの言い方（「おじいさま」「かあさん」）は頭に固定する。
 * 途中の一致まで拾うと「ふじいさん」のような人名を巻き込む。
 * 漢字の語は「三門の母」のように名前の途中にも出るので位置を縛らない。
 *
 * 並び順に意味がある。「祖母」は「母」を含むため、先に見ないと
 * 「祖母」の相手を「母」へ直してしまう。
 */
const KINSHIP_RULES: ReadonlyArray<{
  /** 相手の名前に現れる語 */
  inName: RegExp;
  /** その人物の側から見た語。これが relation に来ていたら向きが逆 */
  reverse: RegExp;
  /** 直したあとの関係 */
  corrected: string;
}> = [
  { inName: /祖母|^お?ばあ/u, reverse: /^孫/u, corrected: "祖母" },
  { inName: /祖父|^お?じい/u, reverse: /^孫/u, corrected: "祖父" },
  { inName: /母|^お?かあ/u, reverse: /^(?:息子|娘)/u, corrected: "母" },
  { inName: /父|^お?とう/u, reverse: /^(?:息子|娘)/u, corrected: "父" },
  { inName: /姉|^お?ねえ/u, reverse: /^(?:弟|妹)/u, corrected: "姉" },
  { inName: /兄|^お?にい/u, reverse: /^(?:弟|妹)/u, corrected: "兄" },
  { inName: /弟/u, reverse: /^(?:兄|姉)/u, corrected: "弟" },
  { inName: /妹/u, reverse: /^(?:兄|姉)/u, corrected: "妹" },
];

/**
 * 関係の向きを直す。直す必要が無ければ元の値、判断できなければ null。
 *
 * 純粋関数にしてあるのは、境界（どこまで直すか）をテストで固定するためである。
 */
export function correctRelationDirection(
  partnerName: string,
  relation: string
): string | null {
  const name = partnerName.trim();
  const value = relation.trim();
  if (!name || !value) return null;

  const matched = KINSHIP_RULES.filter((rule) => rule.inName.test(name));
  // 「兄妹」のように2つの親族語が入った呼び名は、どちら側か決められない
  if (matched.length !== 1) return null;

  const rule = matched[0];
  // 既に相手側の語が書かれているなら触らない（「母の再婚相手」など）
  if (rule.inName.test(value)) return value;
  if (!rule.reverse.test(value)) return value;
  return rule.corrected;
}

/**
 * 体を共有していても人格は別、と読める関係の言い方。
 *
 * プロンプトの【関係の抽出ルール】4番が書かせている語をそのまま拾う。
 * 「騙」は「その名を騙っている」（成り代わり）を拾うためである。
 */
const SHARED_BODY_RELATION =
  /憑依|入れ替わ|入れ替え|転生|身体を共有|体を共有|成り代わ|騙|変装|偽名/u;

/** 空白だけを落とす。敬称は落とさない（「文佳ちゃん」を「文佳」にしない） */
function normalizeSpacingOnly(name: string): string {
  return name.replace(/[\s　]/gu, "");
}

/**
 * 呼び名どうしの照合用。空白・中黒を落とし、末尾の敬称も落とす。
 *
 * 別人の呼び名を落とす判定では、**強めに寄せてよい**。
 * 「文佳ちゃん」を残しても、それは別人（憑依された側）の呼び名だからである。
 */
function normalizeForCompare(name: string): string {
  const base = normalizeSpacingOnly(name)
    .replace(/[・･]/gu, "")
    .toLowerCase();
  for (const suffix of COMPARE_HONORIFICS) {
    if (base.endsWith(suffix) && base.length > suffix.length) {
      return base.slice(0, -suffix.length);
    }
  }
  return base;
}

/**
 * 照合でだけ落とす敬称。
 *
 * `characterMerge.normalizeName` を呼ばないのは、`core` の中で
 * 検証がマージへ依存する向きを作らないためである（依存は models へ向ける）。
 * ここは別人判定の網なので、よく使う形だけで足りる。
 */
const COMPARE_HONORIFICS = [
  "ちゃん",
  "さん",
  "くん",
  "君",
  "さま",
  "様",
  "殿",
  "先輩",
];

/**
 * AI応答から受け取る、単純な文字列の項目。
 *
 * 名前・別名・呼称・関係のように構造を持つものは個別に扱うのでここには入れない。
 * プロンプトのスキーマと突き合わせるテストがこの配列を参照している。
 */
export const EXTRACTED_TEXT_FIELDS = [
  "reading",
  "summary",
  "affiliation",
  "gender",
  "role",
  "personality",
  "appearance",
  "speechStyle",
  "speechEvidence",
  "firstPerson",
  "defaultSecondPerson",
  "evidence",
] as const;

/** AI応答を後段が安全に扱える形へ正規化する。 */
export function normalizeExtractedCharacter(
  raw: Record<string, unknown>
): ExtractedCharacter {
  const name = typeof raw.name === "string" ? raw.name.trim() : "";
  const character: ExtractedCharacter = {
    name,
    aliases: cleanStringArray(raw.aliases).filter(
      (alias) => alias !== name && isValidAlias(alias, name)
    ),
  };

  if (
    typeof raw.entityType === "string" &&
    ENTITY_TYPES.has(raw.entityType)
  ) {
    character.entityType = raw.entityType as NonNullable<
      ExtractedCharacter["entityType"]
    >;
  }
  if (typeof raw.isMob === "boolean") {
    character.isMob = raw.isMob;
  }

  // ここは受け取る項目の白紙リストである。
  // **プロンプトに項目を足したら、必ずここにも足すこと。**
  // 足し忘れると、AIが正しく返していても後段へ届かず、
  // 画面には「AIが埋められなかった」ようにしか見えない。
  // 実際に reading / summary / affiliation / gender の4つで起きた。
  // `EXTRACTED_TEXT_FIELDS` はスキーマとの照合テストが参照している。
  for (const key of EXTRACTED_TEXT_FIELDS) {
    copyNullableString(character, raw, key);
  }

  if ("addressTerms" in raw) {
    character.addressTerms = Array.isArray(raw.addressTerms)
      ? raw.addressTerms.flatMap((item) => {
          if (!isRecord(item)) return [];
          const targetName = cleanRequiredString(item.targetName);
          const term = cleanRequiredString(item.term);
          if (!targetName || !term) return [];
          return [
            {
              targetName,
              term,
              category: cleanNullableString(item.category),
              context: cleanNullableString(item.context),
              evidence: cleanNullableString(item.evidence),
            },
          ];
        })
      : [];
  }

  if ("relations" in raw) {
    character.relations = Array.isArray(raw.relations)
      ? raw.relations.flatMap((item) => {
          if (!isRecord(item)) return [];
          const relationName = cleanRequiredString(item.name);
          const relation = cleanRequiredString(item.relation);
          return relationName && relation
            ? [{ name: relationName, relation }]
            : [];
        })
      : [];
  }

  return character;
}

/**
 * 構造化出力でも前後に説明やコードフェンスが付くモデルがあるため、
 * 生のJSON、コードフェンス除去、最外の波括弧抽出の順で解析する。
 */
export function parseResult(text: string): CharacterExtractResult | null {
  const attempts = [
    text,
    text.replace(/^[\s\S]*?```(?:json)?\s*/i, "").replace(/```[\s\S]*$/, ""),
    extractBraces(text),
  ];

  for (const candidate of attempts) {
    if (!candidate) continue;
    try {
      const parsed: unknown = JSON.parse(candidate.trim());
      if (isRecord(parsed) && Array.isArray(parsed.characters)) {
        // キャッシュには正規化前の値を残し、検証ルール変更時に再評価できるようにする。
        return parsed as unknown as CharacterExtractResult;
      }
    } catch {
      // 次の候補を試す
    }
  }
  return null;
}

function candidateName(raw: unknown): string | null {
  if (!isRecord(raw) || typeof raw.name !== "string") return null;
  return raw.name.trim() || null;
}

function isValidName(name: string): boolean {
  return (
    name.length > 0 &&
    name.length <= MAX_NAME_LENGTH &&
    !PLACEHOLDER_NAME_PATTERN.test(name) &&
    !SENTENCE_PUNCTUATION.test(name) &&
    !WRAPPING_PUNCTUATION.test(name) &&
    !SENTENCE_LIKE_NAME_PATTERN.test(name)
  );
}

/**
 * その文字列を、この人物（`ownerName`）の別名として持ってよいか。
 *
 * **レコードの名前を受け取る。** 別名が正しいかどうかは、形だけでは
 * 決まらないものがある——「三門の母」は母親のレコードなら正しい別名だが、
 * 息子（三門太志）のレコードに付いていたら別人の呼び名である。
 */
function isValidAlias(alias: string, ownerName: string): boolean {
  return (
    isValidName(alias) &&
    // 自分の身内を指す呼び名は、本人の別名ではない（設計書6.5.9）
    !isOwnRelativeAlias(alias, ownerName) &&
    // 代名詞の判定は isValidName から分けた（除外の理由を分けるため）。
    // 別名の側でも同じように弾く——「僕」を別名に持つと、それだけで
    // 別レコードどうしが「同じ呼び名を持つ」ことになる（設計書6.5.9）
    !isPronounName(alias) &&
    // 説明的な名前も別名から落とす。「主人公」が別名に入ると、
    // それだけで別レコードどうしが「同じ呼び名を持つ」ことになる
    !isDescriptiveName(alias) &&
    !GENERIC_ROLES.has(alias) &&
    !isCollectiveName(alias)
  );
}

/**
 * 名前が代名詞そのものか（設計書6.5.9）。
 *
 * 空白を落とし、敬称を1つ外してから照合する。書かれたままの形でしか
 * 見ないと、「 僕 」のような形がすり抜ける。
 *
 * **家族関係語（「お母さん」「おばあさん」）は、ここでは弾かない。**
 * 作中でその呼び方しかされない登場人物がいる——この作品の実データでも
 * 「おばあさん」は関係25件を持つ主要人物で、弾くと資料からその人が消える。
 * 「母」「父」のような語だけの形は、これまでどおり GENERIC_ROLES が弾く。
 */
function isPronounName(name: string): boolean {
  const bare = name.replace(/[\s　]/gu, "");
  return PRONOUNS.has(bare) || PRONOUNS.has(stripHonorific(bare));
}

/**
 * 名前が「呼び名」ではなく「物語上の役割」か（設計書6.5.9）。
 *
 * 弾くのは役割語そのもの（「主人公」「語り手」「ヒロイン」）だけ。
 * **本文の誰もその語では呼んでいない**のに、モデルはレコードを作る
 * （gemma4:26b でも起きた。実機確認A-18）。プロンプトで禁じても返るので、
 * コードで弾く。
 *
 * **「密倉の母親」「三門の母」のような「〇〇の関係語」の形は弾かない**
 * （作者の裁定、2026-09-08「「〇〇の母」は必要です」）。名前を持たない
 * 人物の唯一の呼び名になりうる。実在のレコードと重なるときは
 * 「重複をまとめる」の候補に出るので、作者が画面で片づける。
 * 「おばあさん」「お母さん」のような関係語だけの形も同じ理由で残す
 * （`isPronounName` の注記）。「母親」「母」のように役職語でもある形は、
 * これまでどおり `GENERIC_ROLES` が `non_person` として弾く。
 *
 * **書かれたままの形と、敬称を1つ外した形の両方で見る。**
 * 「主人公」は `stripHonorific` が「公」を敬称とみなして「主人」に
 * してしまい、一覧に無い形になる。
 */
function isDescriptiveName(name: string): boolean {
  const bare = normalizeSpacingOnly(name);
  if (!bare) return false;
  return DESCRIPTIVE_ROLES.has(bare) || DESCRIPTIVE_ROLES.has(stripHonorific(bare));
}

/**
 * 名前を決められずに捨てたレコードを、**中身を添えて**記録する。
 *
 * 添えるのは `pronoun_name` と `descriptive_name` のときだけである
 * （`RejectedCharacterDetails` に理由を書いた）。
 */
function rejectedWithDetails(
  character: ExtractedCharacter,
  reason: "pronoun_name" | "descriptive_name"
): RejectedCharacterCandidate {
  const details = narratorDetails(character);
  return details
    ? { name: character.name, reason, details }
    : // 中身が無いときは項目ごと付けない。空の `details` が並ぶと、
      // 受け取る側（報告・MCP）で「中身がある」と読み違える
      { name: character.name, reason };
}

/**
 * 捨てたレコードから、作者が「誰のことか」を見当できる項目だけを取り出す。
 *
 * 性格や口調まで載せないのは、**報告に並べるため**である。誰のことか
 * 当たりが付けば足りるので、欄を増やすほど読まれなくなる。
 */
function narratorDetails(
  character: ExtractedCharacter
): RejectedCharacterDetails | undefined {
  const details: RejectedCharacterDetails = {};
  const fields: Array<
    [keyof RejectedCharacterDetails, string | null | undefined]
  > = [
    ["summary", character.summary],
    ["role", character.role],
    ["appearance", character.appearance],
    ["gender", character.gender],
  ];
  for (const [key, value] of fields) {
    // 「（本文からは読み取れない）」のような不在文は空欄と同じ扱いにする
    if (value && isMeaningfulValue(value)) details[key] = value.trim();
  }
  return Object.keys(details).length > 0 ? details : undefined;
}

/**
 * その別名は、**その人物自身の身内**を指しているか（設計書6.5.9）。
 *
 * 実データで、息子のレコードに母親の呼び名が別名として入った
 * （`三門太志 〔三門くん・三門の母・母さん・三門さん・太志くん〕`。
 * gemma4:26b で本編18話、2026-09-10）。マージのせいではなく、
 * **AIが本人の別名として返してくる**。放っておくと「三門の母」から
 * 引いたときに息子に当たる。
 *
 * 弾くのは「〇〇の△△」の形で、△△が家族関係語、かつ**〇〇がその人物
 * 自身の名前に含まれる**ときだけ。「密倉の母」（三門太志のレコード）は
 * 落とさない——〇〇が自分の名前に無いので、誰の別名なのかは形からは
 * 決められない。「母さん」のような関係語だけの別名も落とさない
 * （母親自身のレコードに付く正しい別名でもある）。
 */
function isOwnRelativeAlias(alias: string, ownerName: string): boolean {
  const owner = normalizeForCompare(ownerName);
  if (!owner) return false;
  // レコードの名前そのものが「〇〇の△△」のとき（「三門の母」という人物。
  // 作者の裁定で残している形）は見送る。同じ形の別名（「三門の母親」）は
  // 本人の言い換えでありうるのに、〇〇が必ず自分の名前に含まれてしまう
  if (splitRelativeName(ownerName) !== null) return false;

  const parts = splitRelativeName(alias);
  return parts !== null && owner.includes(parts.holder);
}

/**
 * 「〇〇の△△」を分ける。当てはまらなければ null。
 *
 * **区切りはひらがなの「の」だけ。** 「ノ」は「木ノ下」のように名前に使う。
 * 「の」が複数あるときは**最後の「の」で切る**——△△を最短に取ると
 * 「三門の家の母」は〇〇が「三門の家」になって名前と一致せず、落ちない。
 * 判断できないものは落とさない側へ倒す。
 */
function splitRelativeName(
  name: string
): { holder: string; kinship: string } | null {
  const bare = normalizeSpacingOnly(name);
  const at = bare.lastIndexOf("の");
  if (at <= 0 || at === bare.length - 1) return null;
  const kinship = bare.slice(at + 1);
  if (!KINSHIP.has(kinship)) return null;
  // 〇〇にも敬称が付く（「三門くんの母」）。名前と突き合わせる側なので、
  // 名前と同じ正規化を通してから返す
  const holder = normalizeForCompare(bare.slice(0, at));
  return holder ? { holder, kinship } : null;
}

function isCollectiveName(name: string): boolean {
  if (COLLECTIVE_SUFFIX_PATTERN.test(name)) return true;
  if (!name.endsWith("達") && !name.endsWith("ら")) return false;
  const singular = name.slice(0, -1);
  return GENERIC_ROLES.has(singular) || PRONOUNS.has(singular);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function cleanRequiredString(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const cleaned = value.trim();
  return cleaned || null;
}

function cleanNullableString(value: unknown): string | null {
  return cleanRequiredString(value);
}

function cleanStringArray(value: unknown): string[] {
  if (!Array.isArray(value)) return [];
  const strings = value
    .map(cleanRequiredString)
    .filter((item): item is string => item !== null);
  return [...new Set(strings)];
}

function copyNullableString<K extends keyof ExtractedCharacter>(
  target: ExtractedCharacter,
  source: Record<string, unknown>,
  key: K
): void {
  if (!(key in source)) return;
  target[key] = cleanNullableString(source[key]) as ExtractedCharacter[K];
}

function extractBraces(text: string): string | null {
  const start = text.indexOf("{");
  const end = text.lastIndexOf("}");
  if (start === -1 || end === -1 || end <= start) return null;
  return text.slice(start, end + 1);
}
