import type { Character } from "../models/character";
import { mergeChangeLists, mergeConflicts } from "../models/jsonValidation";
import {
  dedupeRelations,
  normalizeName,
  normalizeSpacing,
} from "./characterMerge";

/**
 * 同一人物として登録されてしまった2件を1件にまとめる。
 *
 * **作者が書いた内容は絶対に失わない。** 片方にしかない記述は残し、
 * 両方にある場合も捨てずに併記する。まとめる操作は作者の判断だが、
 * 「まとめたら作者メモが消えた」は取り返しがつかない。
 *
 * 取り下げる側のファイルは呼び出し側が回復用の場所へ退避する
 * （`CharacterStore.retire`）。消さないのは、別人をまとめてしまったときに
 * 元へ戻せるようにするため。
 */

export interface UnifyResult {
  /** まとめた結果。keep 側のIDを引き継ぐ */
  unified: Character;
  /** 取り下げる側のID */
  retiredId: string;
}

export function unifyCharacters(
  keep: Character,
  absorb: Character,
  /**
   * まとめる2人以外の、いま存在するレコード。
   *
   * **そこに載っている「名前」は別名にしない**（設計書6.5.9）。
   * 別人の名前が別名に残ると、次の「重複をまとめる」でその別人との組が
   * 候補に並び、まとめるたびに別人が引き寄せられる（実データで12件）。
   */
  others: readonly Character[] = []
): UnifyResult {
  if (keep.id === absorb.id) {
    throw new Error("同じ人物どうしはまとめられません。");
  }

  const blocked = new Set(
    others
      .filter(
        (character) => character.id !== keep.id && character.id !== absorb.id
      )
      .map((character) => normalizeSpacing(character.name))
  );
  const keepKey = normalizeSpacing(keep.name);
  const aliases: string[] = [];
  const seen = new Set<string>();
  for (const alias of [...keep.aliases, absorb.name, ...absorb.aliases]) {
    const key = normalizeSpacing(alias);
    // 「密倉文佳」と「密倉 文佳」を、別の呼び名として2つ残さない
    if (!key || key === keepKey || seen.has(key) || blocked.has(key)) continue;
    seen.add(key);
    aliases.push(alias);
  }

  return {
    unified: {
      ...keep,
      aliases,
      // 別人の記録（設計書6.5.8）は両方から引き継ぐ。吸収される側の分を
      // 落とすと、「アジャーノは別人」という作者の判断がまとめる操作1回で
      // 消え、次の抽出で別名が戻る。ただし**互いを指す記録は消す**——
      // まとめた後も残すと「自分の別名は別人だ」という矛盾になり、
      // その別名では二度と照合されなくなる
      distinctFrom: unifyDistinctFrom(keep, absorb),
      summary: keep.summary ?? absorb.summary,
      affiliation: keep.affiliation ?? absorb.affiliation,
      reading: keep.reading ?? absorb.reading,
      romaji: keep.romaji ?? absorb.romaji,
      icon: keep.icon ?? absorb.icon,
      iconSource: keep.icon ? keep.iconSource : absorb.iconSource,
      role: keep.role ?? absorb.role,
      personality: keep.personality ?? absorb.personality,
      appearance: keep.appearance ?? absorb.appearance,
      physical: keep.physical ?? absorb.physical,
      firstPerson: {
        default: keep.firstPerson.default ?? absorb.firstPerson.default,
        variants: [
          ...keep.firstPerson.variants,
          ...absorb.firstPerson.variants,
        ],
      },
      defaultSecondPerson:
        keep.defaultSecondPerson ?? absorb.defaultSecondPerson,
      // 呼称は「誰が誰をどう呼ぶか」なので、取り下げ側の名前で
      // 記録されていた分は、まとめた後の名前へ付け替える
      addressTerms: [
        ...keep.addressTerms,
        ...absorb.addressTerms.map((term) =>
          // 空白の有無だけが違う書き方も、同じ相手として付け替える
          normalizeSpacing(term.targetName) === normalizeSpacing(absorb.name)
            ? { ...term, targetName: keep.name }
            : term
        ),
      ],
      // 同じ相手との重複はここでもまとめる（設計書6.5.9）。
      // まとめる操作は2人ぶんの関係を足すので、重複がいちばん出やすい。
      // 名前の揺れ（「ばあさん」「おばあさん」）も1つに寄せる
      relations: dedupeRelations([...keep.relations, ...absorb.relations]),
      abilities: dedupeBy(
        [...keep.abilities, ...absorb.abilities],
        (ability) => ability.name
      ),
      appearedChapters: [
        ...new Set([...keep.appearedChapters, ...absorb.appearedChapters]),
      ].sort((a, b) => a - b),
      // 未登場どうしのときだけ未登場のまま
      status:
        keep.status === "登場済み" || absorb.status === "登場済み"
          ? "登場済み"
          : "未登場",
      // 公開範囲は狭いほうに合わせる。広げると意図せず外へ出る
      spoilerLevel: narrowerSpoiler(keep.spoilerLevel, absorb.spoilerLevel),
      // 作者が書いた文章は片方を捨てず両方残す
      authorNotes: joinAuthorText(keep.authorNotes, absorb.authorNotes),
      exportNote: joinAuthorText(keep.exportNote, absorb.exportNote),
      // まとめるのは作者の判断。以後の抽出で作り直させない
      autoGenerated: false,
      // 名前のある人物とモブをまとめたなら、モブ扱いをやめる
      isMob: keep.isMob && absorb.isMob,
      evidence: keep.evidence ?? absorb.evidence,
      // 同じ項目の食い違いは1つにまとめる。並べるだけだと、
      // 以後のマージが最初の1件しか見ないため取り残しになる
      conflicts: mergeConflicts(keep.conflicts, absorb.conflicts),
      // 作者が確定させた変化。片方にしか無いものも必ず残す
      changes: mergeChangeLists(keep.changes, absorb.changes),
      aiNotes: [...keep.aiNotes, ...absorb.aiNotes],
    },
    retiredId: absorb.id,
  };
}

const SPOILER_ORDER = ["public", "staff_only", "author_only"] as const;

function narrowerSpoiler(
  left: Character["spoilerLevel"],
  right: Character["spoilerLevel"]
): Character["spoilerLevel"] {
  return SPOILER_ORDER.indexOf(left) >= SPOILER_ORDER.indexOf(right)
    ? left
    : right;
}

/** 両方に文章があれば区切って併記する。片方を捨てない */
function joinAuthorText(keep: string, absorb: string): string {
  const left = keep.trim();
  const right = absorb.trim();
  if (!right) return left;
  if (!left) return right;
  if (left.includes(right)) return left;
  return `${left}\n\n${right}`;
}

function dedupeBy<T>(items: T[], key: (item: T) => string): T[] {
  const seen = new Set<string>();
  const result: T[] = [];
  for (const item of items) {
    const id = key(item);
    if (seen.has(id)) continue;
    seen.add(id);
    result.push(item);
  }
  return result;
}

/**
 * 別人の記録（distinctFrom）を、2人ぶん合わせる。
 *
 * - 互いを指す記録は消す（idか、敬称を落とした名前が相手の呼び名と一致するもの）
 * - 残りは重複なく合わせる（照合は characterMerge と同じ、敬称を落とした形）
 */
function unifyDistinctFrom(
  keep: Character,
  absorb: Character
): Character["distinctFrom"] {
  const counterpartIds = new Set([keep.id, absorb.id]);
  const counterpartNames = new Set(
    [keep.name, ...keep.aliases, absorb.name, ...absorb.aliases].map(
      normalizeName
    )
  );

  const seen = new Set<string>();
  const merged: Character["distinctFrom"] = [];
  for (const entry of [
    ...(keep.distinctFrom ?? []),
    ...(absorb.distinctFrom ?? []),
  ]) {
    if (entry.id !== null && counterpartIds.has(entry.id)) continue;
    const key = normalizeName(entry.name);
    if (counterpartNames.has(key)) continue;
    if (seen.has(key)) continue;
    seen.add(key);
    merged.push(entry);
  }
  return merged;
}
