import {
  emptyCharacter,
  nextCharacterId,
  type Character,
} from "../models/character";
import { normalizeName } from "./characterMerge";
import { fillReading } from "./reading";

/**
 * 1つにまとめられてしまった人物を、別人に分ける（設計書6.5.8）。
 *
 * `characterUnify.ts`（まとめる）の対である。作者の指摘：
 * 「アジャンとアジャーノが同一人物として認識されている作品があります」。
 *
 * ## 中身は移さない。名前だけで始める（作者の指定）
 *
 * 紹介・役割・性格・登場話・変化の記録は、**元の人物に残す。**
 * 実データでは第5話に「アジャン」と「アジャーノ」の両方が出るので、
 * どの記述がどちらのものかは**機械では決められない**。
 * 当てずっぽうで振り分けると、作者が書いた文章を別人へ移してしまう。
 *
 * 空の新しい記録は、次の抽出で本文から埋まる。チャンクの鍵は
 * `promptVersion|model|chunkHash` なので、同じAI・同じモデルなら
 * **AIは一度も呼ばれない**（`chunkCache.ts`）。
 *
 * ## 分けた事実を、両方のレコードへ残す
 *
 * 残さないと、次の抽出でまた1人へ戻る。抽出は毎回まっさらな目で本文を読み、
 * 「アジャン＝アジャーノ」と返してくるからである。塞ぐのは
 * `characterMerge.ts` 側（`distinctFrom` を見る4か所）。
 *
 * ## ここはファイルにも vscode にも触らない
 *
 * 保存するのは呼び出し側（`features/settingsPanel.ts`）。
 * 純粋な関数にしておくと、単体テストで固められる。
 */

export interface SeparationPlan {
  /** 別名を外し、別人の記録を足した元の人物 */
  original: Character;
  /** 新しくできる人物。**名前だけ** */
  created: Character;
  /** 元から外した別名（選んだものと、敬称違いで同じもの） */
  movedAliases: string[];
}

/**
 * 別名を1つ選んで、別人として切り出す。
 *
 * @param alias 別人として切り出す別名。`source.aliases` にあるもの
 * @param all 既にある人物すべて（IDの採番と、名前の重複を見るのに使う）
 */
export function planCharacterSeparation(
  source: Character,
  alias: string,
  all: readonly Character[]
): SeparationPlan {
  const wanted = alias.trim();
  if (!wanted) throw new Error("分ける呼び名を選んでください。");
  if (normalizeName(wanted) === normalizeName(source.name)) {
    throw new Error(
      `「${wanted}」は「${source.name}」自身の呼び名です。別の呼び名を選んでください。`
    );
  }
  if (!source.aliases.some((entry) => entry.trim() === wanted)) {
    throw new Error(`「${source.name}」の別名に「${wanted}」がありません。`);
  }
  const duplicate = all.find(
    (character) =>
      character.id !== source.id &&
      normalizeName(character.name) === normalizeName(wanted)
  );
  if (duplicate) {
    throw new Error(
      `「${duplicate.name}」が既にいます。分ける代わりに、そちらへまとめられないか確かめてください。`
    );
  }

  // 一緒に移すのは、**敬称を落とすと同じになるものだけ**。
  // 「アジャーノさん」は「アジャーノ」と同じ人だが、「アジャン様」は違う。
  // ここを曖昧一致（`isSuffixCallOf` のような後方一致）に広げると、
  // 関係のない呼び名まで持っていかれる。**推測で広げない**
  const key = normalizeName(wanted);
  const movedAliases = source.aliases.filter(
    (entry) => normalizeName(entry) === key
  );

  const created = emptyCharacter(nextCharacterId([...all]), wanted);
  // **自動生成のままにする。** `characterMerge.ts` は autoGenerated: false の
  // レコードへ登場話数しか足さない。false にすると「次の抽出で埋まる」が
  // 永久に成立せず、空の記録が残り続ける（まとめる側が false にするのは、
  // まとめた側は中身が揃っているからで、分けた側は逆）
  created.autoGenerated = true;
  // 公開範囲は元に合わせる。既定（public）へ落とすと、隠していた人物が
  // 分けた拍子に資料へ出る
  created.spoilerLevel = source.spoilerLevel;
  created.isMob = source.isMob;
  created.reading = fillReading(null, wanted);
  created.aliases = movedAliases.filter((entry) => entry.trim() !== wanted);
  created.distinctFrom = [{ name: source.name, id: source.id }];

  const original: Character = {
    ...source,
    aliases: source.aliases.filter((entry) => !movedAliases.includes(entry)),
    // 既にある記録は消さない。作者が何度か分けていることがある
    distinctFrom: [
      ...(source.distinctFrom ?? []).filter(
        (entry) => normalizeName(entry.name) !== key
      ),
      { name: created.name, id: created.id },
    ],
  };

  return { original, created, movedAliases };
}
