import {
  AddressTerm,
  Character,
  emptyCharacter,
  nextCharacterId,
} from "../models/character";
import { ExtractedCharacter } from "../prompts/characterExtract";
import { clampSummary } from "./summaryLimit";
import { fillReading } from "./reading";
import { normalizeGender } from "./gender";

/**
 * 抽出結果を既存の人物一覧へマージする。
 *
 * 設計書ではReduce段階もAIに任せる案だったが、実装ではコード側で行う。
 * 理由は3つ:
 *  1. 作者の加筆を確実に保護できる（AIの指示追従に依存しない）
 *  2. 同じ入力なら必ず同じ結果になる
 *  3. AI呼び出し回数が減り、処理時間とコストが下がる
 *
 * AIには「本文から情報を取り出す」ことだけをさせ、
 * 「既存データとどう統合するか」はコードが決める。
 */
export interface MergeResult {
  characters: Character[];
  added: string[];
  updated: string[];
  /** 実際に追加・更新された人物。不要なJSON再書き込みを避けるために使う */
  changedIds: string[];
  /** 既存と食い違い、作者の判断が必要になったもの */
  conflicts: Array<{ characterName: string; field: string; values: string[] }>;
  /** 同一人物かもしれない組。自動では統合せず、作者の判断に委ねる */
  mergeCandidates: MergeCandidate[];
}

/**
 * 同一人物の可能性がある組。
 *
 * 「ギルドマスター」と「ギルマス」のような省略形は敬称除去では吸収できない。
 * ただし自動で統合すると、別人を1人にまとめてしまったときに
 * 作者のデータを壊すことになる（取り消しも難しい）。
 * 統合し損ねるのは手間で済むが、誤統合は損害になるため、候補の提示に留める。
 */
export interface MergeCandidate {
  names: [string, string];
  /**
   * abbreviation: 省略形とみられる（「ギルマス」と「ギルドマスター」）
   * suffix: 一方が他方の言い方を含む（「近所のおばあさん」と「ばあさん」）
   * ambiguous: 統合先が複数あって決められなかった
   * same_name: 同じ呼称なのに別レコードになっている
   */
  reason: "abbreviation" | "suffix" | "ambiguous" | "same_name";
}

export function mergeExtractedCharacters(
  existing: Character[],
  extracted: Array<{ data: ExtractedCharacter; chapters: number[] }>
): MergeResult {
  // 作者が管理している元レコードを、入れ子の配列・オブジェクトを含めて保護する。
  const result: Character[] = existing.map((character) => structuredClone(character));
  const added: string[] = [];
  const updated: string[] = [];
  const changedIds = new Set<string>();
  const conflicts: MergeResult["conflicts"] = [];
  /** 統合先を決められず新規にした組。作者の判断へ回す */
  const ambiguousPairs: Array<[string, string]> = [];

  for (const item of extracted) {
    const ex = item.data;
    if (!ex.name || !ex.name.trim()) continue;

    const lookup = findCharacter(result, ex.name, ex.aliases ?? []);
    const match = lookup.match;

    if (!match) {
      const c = emptyCharacter(nextCharacterId(result), ex.name.trim());
      applyExtracted(c, ex, item.chapters, conflicts);
      result.push(c);
      added.push(c.name);
      changedIds.add(c.id);
      // 統合先が複数あって決められなかった場合、データは残しつつ
      // 「どれかと同じかもしれない」ことを作者へ伝える。
      // 黙って新規にすると重複が増えるだけで気づけない。
      for (const other of lookup.ambiguous) {
        ambiguousPairs.push([c.name, other.name]);
      }
      continue;
    }

    // 同名の相手が他にもいた場合、寄せ先へ統合したうえで
    // 「これらも同じかもしれない」と作者へ伝える。
    // 統合そのものは作者が決める（誤統合は取り返しがつかない）
    for (const other of lookup.ambiguous) {
      ambiguousPairs.push([match.name, other.name]);
    }

    // 作者が確定させた人物はAIで書き換えない。
    // 登場話数の追記だけ行う。
    if (!match.autoGenerated) {
      const before = match.appearedChapters.length;
      match.appearedChapters = mergeChapters(
        match.appearedChapters,
        item.chapters
      );
      if (match.appearedChapters.length !== before) {
        updated.push(match.name);
        changedIds.add(match.id);
      }
      continue;
    }

    const changed = applyExtracted(match, ex, item.chapters, conflicts);
    if (changed) {
      if (!updated.includes(match.name)) updated.push(match.name);
      changedIds.add(match.id);
    }
  }

  return {
    characters: result,
    added,
    updated,
    changedIds: [...changedIds],
    conflicts,
    mergeCandidates: [
      ...ambiguousPairs.map((names) => ({
        names,
        reason: "ambiguous" as const,
      })),
      ...findMergeCandidates(result),
    ],
  };
}

/**
 * 抽出結果を1人分のレコードへ反映する。
 * 既存の値を消さないことを原則とし、食い違いは conflicts に記録する。
 */
function applyExtracted(
  target: Character,
  ex: ExtractedCharacter,
  chapters: number[],
  conflicts: MergeResult["conflicts"]
): boolean {
  let changed = false;
  const validChapters = chapters.filter(Number.isFinite);

  // 別名は和集合。
  // 抽出時の名前が既存レコードと異なる場合（「玲司」で照合されたが
  // 登録名が「黒木 玲司」など）、その呼び名も別名として残す。
  const aliases = new Set(target.aliases);
  const incomingName = ex.name?.trim();
  if (incomingName && incomingName !== target.name && !aliases.has(incomingName)) {
    aliases.add(incomingName);
    changed = true;
  }
  for (const a of ex.aliases ?? []) {
    if (a && a !== target.name && !aliases.has(a)) {
      aliases.add(a);
      changed = true;
    }
  }
  target.aliases = [...aliases];

  if (ex.isMob === true && !target.isMob) {
    target.isMob = true;
    changed = true;
  }

  // 読みはカタカナならコード側で確実に作る。
  // 漢字を含む名前だけAIの推定（ex.reading）に委ねる
  changed =
    fillOrConflict(target, "reading", ex.reading, conflicts) || changed;
  const derived = fillReading(target.reading, target.name);
  if (derived !== target.reading) {
    target.reading = derived;
    changed = true;
  }

  // 紹介文は長さをコード側で確かめてから入れる。
  // プロンプトで字数を指示しても、モデルは平気で超えてくる
  changed =
    fillOrConflict(target, "summary", clampSummary(ex.summary), conflicts) ||
    changed;
  changed =
    fillOrConflict(target, "affiliation", ex.affiliation, conflicts) || changed;

  // 性別はAIが本文の言い方のまま返してくるので、ここで「男性」「女性」に揃える。
  // 揃えないと、同じ人物が話ごとに「男」「男性」と揺れて食い違い扱いになる
  changed =
    fillOrConflict(target, "gender", normalizeGender(ex.gender), conflicts) ||
    changed;

  // 単純なテキスト項目: 空なら埋める。既にあれば食い違いを記録し、上書きしない
  changed = fillOrConflict(target, "role", ex.role, conflicts) || changed;
  changed =
    fillOrConflict(target, "personality", ex.personality, conflicts) || changed;
  changed =
    fillOrConflict(target, "appearance", ex.appearance, conflicts) || changed;

  // 一人称
  if (ex.firstPerson) {
    if (!target.firstPerson.default) {
      target.firstPerson.default = ex.firstPerson;
      changed = true;
    } else if (target.firstPerson.default !== ex.firstPerson) {
      // 場面によって変わることがあるため、矛盾ではなく変化形として保持する
      const exists = target.firstPerson.variants.some(
        (v) => v.form === ex.firstPerson
      );
      if (!exists) {
        target.firstPerson.variants.push({
          form: ex.firstPerson,
          context: null,
          chapters: [...validChapters],
          evidence: ex.evidence ?? null,
        });
        changed = true;
      }
    }
  }

  if (ex.defaultSecondPerson && !target.defaultSecondPerson) {
    target.defaultSecondPerson = ex.defaultSecondPerson;
    changed = true;
  }

  // 呼称: 相手ごとにまとめ、異なる呼び方はすべて残す
  for (const at of ex.addressTerms ?? []) {
    if (!at.targetName || !at.term) continue;
    if (mergeAddressTerm(target, at, validChapters)) changed = true;
  }

  // 関係
  for (const rel of ex.relations ?? []) {
    if (!rel.name || !rel.relation) continue;
    const exists = target.relations.some(
      (r) => r.name === rel.name && r.relation === rel.relation
    );
    if (!exists) {
      target.relations.push({ name: rel.name, relation: rel.relation });
      changed = true;
    }
  }

  if (!target.evidence && ex.evidence) {
    target.evidence = ex.evidence;
    changed = true;
  }

  const before = target.appearedChapters.length;
  target.appearedChapters = mergeChapters(target.appearedChapters, validChapters);
  if (target.appearedChapters.length !== before) changed = true;

  return changed;
}

/**
 * 呼称をマージする。
 *
 * 同じ term は1件に統合するが、異なる term は統合しない。
 * 「澪」と「白瀬さん」を1つにまとめてはならない。呼び分けそのものが
 * 管理対象の情報であるため。
 */
function mergeAddressTerm(
  target: Character,
  incoming: NonNullable<ExtractedCharacter["addressTerms"]>[number],
  chapters: number[]
): boolean {
  let entry: AddressTerm | undefined = target.addressTerms.find(
    (a) => normalizeName(a.targetName) === normalizeName(incoming.targetName)
  );

  if (!entry) {
    entry = {
      targetName: incoming.targetName,
      targetId: null,
      forms: [],
      authorLocked: false,
    };
    target.addressTerms.push(entry);
  }

  // 作者がロックした呼称は触らない
  if (entry.authorLocked) return false;

  const chapter = chapters.length > 0 ? Math.min(...chapters) : null;
  const lastChapter = chapters.length > 0 ? Math.max(...chapters) : null;

  const existingForm = entry.forms.find((f) => f.term === incoming.term);
  if (existingForm) {
    let changed = false;
    if (
      chapter !== null &&
      (existingForm.firstChapter === null || chapter < existingForm.firstChapter)
    ) {
      existingForm.firstChapter = chapter;
      changed = true;
    }
    if (
      lastChapter !== null &&
      (existingForm.lastChapter === null ||
        lastChapter > existingForm.lastChapter)
    ) {
      existingForm.lastChapter = lastChapter;
      changed = true;
    }
    if (!existingForm.context && incoming.context) {
      existingForm.context = incoming.context;
      changed = true;
    }
    return changed;
  }

  entry.forms.push({
    term: incoming.term,
    category: incoming.category ?? null,
    context: incoming.context ?? null,
    firstChapter: chapter,
    lastChapter: lastChapter,
    status: "current",
    evidence: incoming.evidence ?? null,
  });
  return true;
}

/**
 * 空なら埋め、既存値と違えば conflicts に記録する。
 * 既存の記述は削除しない。設定側が正しいのか本文側が正しいのかは
 * AIには判断できないため、作者に委ねる。
 */
function fillOrConflict(
  target: Character,
  field:
    | "summary"
    | "affiliation"
    | "gender"
    | "reading"
    | "role"
    | "personality"
    | "appearance",
  incoming: string | null | undefined,
  conflicts: MergeResult["conflicts"]
): boolean {
  const value = incoming?.trim();
  if (!value) return false;

  const current = target[field];
  if (!current) {
    target[field] = value;
    return true;
  }
  if (current === value) return false;

  // 短い記述が長い記述に含まれる場合は、詳細な方を採用する
  if (value.includes(current)) {
    target[field] = value;
    return true;
  }
  if (current.includes(value)) return false;

  const already = target.conflicts.find((c) => c.field === field);
  if (already) {
    if (!already.values.includes(value)) {
      already.values.push(value);
      conflicts.push({
        characterName: target.name,
        field,
        values: already.values,
      });
      return true;
    }
    return false;
  }

  target.conflicts.push({
    field,
    values: [current, value],
    chapters: [...target.appearedChapters],
    note: null,
  });
  conflicts.push({
    characterName: target.name,
    field,
    values: [current, value],
  });
  return true;
}

/**
 * 統合先の探索結果。
 *
 * 「どれに統合すべきか決まらない」ことと「一致するものが無い」ことを
 * 区別する。前者で黙って新規レコードを作ると、既存2件に加えて3件目ができ、
 * 重複がかえって増えるため（実データで確認）。
 */
interface CharacterLookup {
  match?: Character;
  /** 複数一致して決められなかった相手。作者に提示する */
  ambiguous: Character[];
}

function findCharacter(
  list: Character[],
  name: string,
  aliases: string[]
): CharacterLookup {
  const incomingNames = [name, ...aliases];
  const keys = new Set(incomingNames.map(normalizeName));
  const exactMatches = list.filter((c) => {
    const candidates = [c.name, ...c.aliases].map(normalizeName);
    return candidates.some((candidate) => keys.has(candidate));
  });
  if (exactMatches.length === 1) return { match: exactMatches[0], ambiguous: [] };
  if (exactMatches.length > 1) {
    // **名前が一致した相手がいるのに新規を作ってはいけない。**
    // 既存2件に3件目が増え、その3件目の別名が次回さらに多くの
    // レコードと一致して、実行のたびに重複が増える。
    // 実データで「密倉 文佳」が3件、「お母さん」が4件に分裂した。
    //
    // どれか1件へ寄せたうえで、残りを統合候補として作者に見せる。
    const best = preferredMatch(exactMatches, name);
    return {
      match: best,
      ambiguous: exactMatches.filter((character) => character !== best),
    };
  }

  // 部分名は、姓名が空白・中黒で明示的に区切られている場合だけ使う。
  // 推測による部分一致は別人を壊すため、候補が一人に決まる場合に限る。
  const incomingParts = new Set(incomingNames.flatMap(splitNameParts));
  const partMatches = list.filter((character) =>
    [character.name, ...character.aliases].some((candidate) =>
      incomingParts.has(normalizeName(candidate)) ||
      splitNameParts(candidate).some((part) => keys.has(part))
    )
  );
  if (partMatches.length === 1) return { match: partMatches[0], ambiguous: [] };
  return { ambiguous: partMatches.length > 1 ? partMatches : [] };
}

/**
 * 同じ名前で一致した複数の中から、寄せ先を1件選ぶ。
 *
 * 1. 主たる名前がそのまま一致するもの（別名での一致より確かである）
 * 2. 作者が確定させたもの（作者の記述がある側を軸にする）
 * 3. それも無ければ先頭（＝IDが若い＝先にできたもの）
 *
 * どれを選んでも作者が最後に判断できるよう、選ばなかった相手は
 * 統合候補として提示する。
 */
function preferredMatch(candidates: Character[], name: string): Character {
  const key = normalizeName(name);
  return (
    candidates.find((character) => normalizeName(character.name) === key) ??
    candidates.find((character) => !character.autoGenerated) ??
    candidates[0]
  );
}

// 省略はカタカナ語で起きやすい。漢字を含む名前の部分一致は
// 別人（「田中」と「田中村」等）の可能性が高いため対象にしない。
const KATAKANA_ONLY = /^[ァ-ヶーｦ-ﾟ]+$/u;
/** これ以上に長さが開く組は、省略ではなく別語とみなす */
const MAX_LENGTH_RATIO = 2.5;

/**
 * 省略形とみられる組を洗い出す。統合はしない。
 *
 * 日本語の省略は元の語から文字を順に抜き出す形が多い
 * （ギルドマスター → ギルマス）ため、部分列であることを手掛かりにする。
 */
export function findMergeCandidates(characters: Character[]): MergeCandidate[] {
  const candidates: MergeCandidate[] = [];
  const appellations = buildAppellationIndex(characters);

  for (let i = 0; i < characters.length; i++) {
    for (let j = i + 1; j < characters.length; j++) {
      const a = characters[i];
      const b = characters[j];

      // 別レコードなのに呼称が重なっている＝ほぼ確実に同一人物。
      // 統合先が決まらず新規になった場合などに起きるので、最優先で伝える。
      const keys = new Set(
        (appellations.get(a.id) ?? []).map(normalizeName)
      );
      if (
        (appellations.get(b.id) ?? []).some((name) =>
          keys.has(normalizeName(name))
        )
      ) {
        candidates.push({ names: [a.name, b.name], reason: "same_name" });
        continue;
      }

      const pairs = appellationPairs(a, b);

      if (pairs.some(([left, right]) => isAbbreviationOf(left, right))) {
        candidates.push({ names: [a.name, b.name], reason: "abbreviation" });
        continue;
      }

      if (pairs.some(([left, right]) => isSuffixCallOf(left, right))) {
        candidates.push({ names: [a.name, b.name], reason: "suffix" });
      }
    }
  }
  return candidates;
}

/**
 * shorter が longer の後ろに含まれる呼び方か
 * （「ばあさん」と「近所のおばあさん」）。
 *
 * 日本語では、同じ人物を「近所のおばあさん」と説明的に書いたり、
 * 単に「ばあさん」と呼んだりする。AIは場面ごとに違う書き方を拾うため、
 * 別レコードになりやすい。実データで起きた（「いじめられっ子」）。
 *
 * `isAbbreviationOf` はカタカナ語の省略（ギルマス）専用なので、
 * ひらがな・漢字の呼び方は拾えない。
 *
 * **統合はしない。候補として出すだけ。** 別人の可能性は残るので、
 * 判断は作者に委ねる（`findMergeCandidates` の方針）。
 */
export function isSuffixCallOf(shorter: string, longer: string): boolean {
  // ここでは normalizeName を通さない。あれは敬称を落とすので
  // 「ばあさん」が「ばあ」になり、短すぎて判定できなくなる。
  // 呼び方そのものの重なりを見たいので、書かれたまま比べる
  const left = shorter.trim();
  const right = longer.trim();

  // 3字未満だと「先生」「さん」「たち」のような語で無関係な組が大量に並ぶ。
  // 候補が多すぎると作者が全部読まなくなり、機能そのものが死ぬ
  if (left.length < 3) return false;
  if (left.length >= right.length) return false;
  // 離れすぎた長さの組は、たまたま末尾が揃っただけのことが多い
  if (right.length / left.length > MAX_LENGTH_RATIO) return false;

  if (right.endsWith(left)) return true;

  // 「おばあさん」と「近所のばあさん」のように、
  // 丁寧の「お」の有無だけが違う場合も同じ呼び方とみなす
  const bare = stripPolitePrefix(left);
  return bare.length >= 3 && bare !== left && right.endsWith(bare);
}

/**
 * 頭に付く丁寧の「お」「御」を落とす。
 * 「おばあさん」と「ばあさん」は同じ言い方の丁寧・くだけた形にすぎない。
 */
function stripPolitePrefix(name: string): string {
  return name.replace(/^[お御]/, "");
}

/**
 * その人物を指す呼称を、全レコードを横断して集める。
 *
 * **呼称は「呼ぶ側」のレコードに入る。** 「マルキオがリンセップを『リン』と呼ぶ」
 * という情報は、リンセップではなくマルキオのレコードに記録される。
 * そのため1人分のレコードだけを見ても、その人物が何と呼ばれているかは分からない。
 *
 * これを見落としていたため、AIが関連を正しく記録していたにもかかわらず、
 * 「リン」と「リンセップ・アウクト」が別人のまま残っていた（実データで確認）。
 *
 * ただし「姫」「殿下」のような肩書きだけの呼称は、
 * 別人どうしでも一致してしまうため除く。
 */
export function buildAppellationIndex(
  characters: Character[]
): Map<string, string[]> {
  const index = new Map<string, string[]>();

  for (const character of characters) {
    const names = [character.name, ...character.aliases].filter((name) =>
      name.trim()
    );
    const ownKeys = new Set(names.map(normalizeName));
    const collected = new Set(names);

    // 誰のレコードに書かれていても、宛先がこの人物なら呼称として扱う
    for (const speaker of characters) {
      for (const term of speaker.addressTerms) {
        if (!ownKeys.has(normalizeName(term.targetName))) continue;
        for (const form of term.forms) {
          if (isTitleOnly(form.term)) continue;
          collected.add(form.term);
        }
      }
    }
    index.set(character.id, [...collected]);
  }

  return index;
}

/**
 * 肩書き・敬称だけの呼称か。
 * 「姫」「王女殿下」は別の王女とも一致してしまうので同一人物判定に使わない。
 */
function isTitleOnly(term: string): boolean {
  // normalizeName は敬称を落とすので「王女殿下」→「王女」になる
  const normalized = normalizeName(term);
  if (!normalized) return true;
  // 「姫」「殿下」のように敬称そのもの1語だけの呼び方
  if (HONORIFIC_SUFFIX_SOURCE.includes(normalized)) return true;
  return TITLE_WORDS.has(normalized);
}

/** 肩書きだけで人を特定できない語。別の王女とも一致してしまう */
const TITLE_WORDS = new Set([
  "王女", "王子", "王", "女王", "国王", "皇帝", "皇后", "王妃",
  "姫君", "師匠", "隊長", "副隊長", "団長", "会長",
  "社長", "部長", "課長", "店長", "旦那", "奥様", "お嬢様",
]);

/** 2人の呼称の総当たりを、短い方・長い方の順で返す */
function appellationPairs(a: Character, b: Character): Array<[string, string]> {
  const pairs: Array<[string, string]> = [];
  for (const left of [a.name, ...a.aliases]) {
    for (const right of [b.name, ...b.aliases]) {
      pairs.push(
        left.length <= right.length ? [left, right] : [right, left]
      );
    }
  }
  return pairs;
}

/** shorter が longer の省略形とみられるか */
export function isAbbreviationOf(shorter: string, longer: string): boolean {
  if (shorter.length < 2 || shorter.length >= longer.length) return false;
  if (!KATAKANA_ONLY.test(shorter) || !KATAKANA_ONLY.test(longer)) return false;
  if (longer.length / shorter.length > MAX_LENGTH_RATIO) return false;
  // 省略形は語頭を残すのが普通。頭が違うものは別語とみなす
  if (shorter[0] !== longer[0]) return false;
  return isSubsequence(shorter, longer);
}

function isSubsequence(shorter: string, longer: string): boolean {
  let index = 0;
  for (const char of longer) {
    if (char === shorter[index]) index++;
    if (index === shorter.length) return true;
  }
  return index === shorter.length;
}

function splitNameParts(name: string): string[] {
  if (!/[\s　・･]/.test(name)) return [];
  return name
    .split(/[\s　・･]+/)
    .map(normalizeName)
    .filter(Boolean);
}

// 同一人物判定でだけ使う。呼称の使い分け自体は addressTerms 側の
// 管理対象なので、name/aliases に保存する文字列はこの敬称を残したままにする
// 「先生」は敬称として名前に付く（「マイナ先生」＝「マイナ」）。
// 「先生」単独は GENERIC_ROLES 側で人物名から除外されるため、
// ここに入れても役職語だけのレコードを拾うことはない。
/**
 * 名前の後ろに付く敬称。同一人物判定でのみ使い、
 * name / aliases に保存する文字列からは取り除かない
 * （呼び分けそのものが addressTerms の管理対象であるため）。
 *
 * 「殿下」と「妃殿下」のように一方が他方の末尾になる組があるため、
 * 照合は長い敬称から行う（HONORIFIC_SUFFIXES を参照）。
 * 並び順に依存しないよう、定義はここでは自由に足してよい。
 */
const HONORIFIC_SUFFIX_SOURCE = [
  // 一般
  "さん",
  "くん",
  "君",
  "ちゃん",
  "ちゃま",
  "様",
  "さま",
  "殿",
  "氏",
  "女史",
  // 立場・職能
  "先輩",
  "先生",
  "師",
  "卿",
  "翁",
  // 王侯貴族・聖職
  "陛下",
  "妃殿下",
  "殿下",
  "閣下",
  "猊下",
  "聖下",
  "姫",
  "公",
];

/**
 * 長い敬称から順に照合する。
 *
 * 「エレナ妃殿下」は「殿下」でも末尾一致するため、
 * 短い方を先に試すと「エレナ妃」が残ってしまう。
 */
const HONORIFIC_SUFFIXES = [...HONORIFIC_SUFFIX_SOURCE].sort(
  (a, b) => b.length - a.length
);

/**
 * 表記ゆれを吸収する。全角空白・記号の違いで別人扱いしないため。
 * 敬称の有無も同様の理由で吸収する（「シル」と「シルさん」を別人扱いしない）。
 */
function normalizeName(s: string): string {
  const base = s
    .replace(/[\s　・･]/g, "")
    .replace(/[０-９]/g, (c) => String.fromCharCode(c.charCodeAt(0) - 0xfee0))
    .toLowerCase();

  for (const suffix of HONORIFIC_SUFFIXES) {
    if (base.endsWith(suffix) && base.length > suffix.length) {
      return base.slice(0, -suffix.length);
    }
  }
  return base;
}

function mergeChapters(existing: number[], incoming: number[]): number[] {
  const set = new Set(existing);
  for (const n of incoming) {
    if (Number.isFinite(n)) set.add(n);
  }
  return [...set].sort((a, b) => a - b);
}
