import {
  AddressTerm,
  Character,
  emptyCharacter,
  nextCharacterId,
} from "../models/character";
import { ExtractedCharacter } from "../prompts/characterExtract";

/**
 * 抽出結果を既存の人物一覧へマージする。
 *
 * 設計書ではReduce段階もAIに任せる案だったが、実装ではコード側で行う。
 * 理由は3つ:
 *  1. 作者の加筆を確実に保護できる（AIの指示追従に依存しない）
 *  2. 同じ入力なら必ず同じ結果になる
 *  3. AI呼び出し回数が減り、処理時間とコストが下がる
 *
 * AIには「本文から情報を取り出す」ことだけをさせ、
 * 「既存データとどう統合するか」はコードが決める。
 */
export interface MergeResult {
  characters: Character[];
  added: string[];
  updated: string[];
  /** 実際に追加・更新された人物。不要なJSON再書き込みを避けるために使う */
  changedIds: string[];
  /** 既存と食い違い、作者の判断が必要になったもの */
  conflicts: Array<{ characterName: string; field: string; values: string[] }>;
  /** 同一人物かもしれない組。自動では統合せず、作者の判断に委ねる */
  mergeCandidates: MergeCandidate[];
}

/**
 * 同一人物の可能性がある組。
 *
 * 「ギルドマスター」と「ギルマス」のような省略形は敬称除去では吸収できない。
 * ただし自動で統合すると、別人を1人にまとめてしまったときに
 * 作者のデータを壊すことになる（取り消しも難しい）。
 * 統合し損ねるのは手間で済むが、誤統合は損害になるため、候補の提示に留める。
 */
export interface MergeCandidate {
  names: [string, string];
  reason: "abbreviation";
}

export function mergeExtractedCharacters(
  existing: Character[],
  extracted: Array<{ data: ExtractedCharacter; chapters: number[] }>
): MergeResult {
  // 作者が管理している元レコードを、入れ子の配列・オブジェクトを含めて保護する。
  const result: Character[] = existing.map((character) => structuredClone(character));
  const added: string[] = [];
  const updated: string[] = [];
  const changedIds = new Set<string>();
  const conflicts: MergeResult["conflicts"] = [];

  for (const item of extracted) {
    const ex = item.data;
    if (!ex.name || !ex.name.trim()) continue;

    const match = findCharacter(result, ex.name, ex.aliases ?? []);

    if (!match) {
      const c = emptyCharacter(nextCharacterId(result), ex.name.trim());
      applyExtracted(c, ex, item.chapters, conflicts);
      result.push(c);
      added.push(c.name);
      changedIds.add(c.id);
      continue;
    }

    // 作者が確定させた人物はAIで書き換えない。
    // 登場話数の追記だけ行う。
    if (!match.autoGenerated) {
      const before = match.appearedChapters.length;
      match.appearedChapters = mergeChapters(
        match.appearedChapters,
        item.chapters
      );
      if (match.appearedChapters.length !== before) {
        updated.push(match.name);
        changedIds.add(match.id);
      }
      continue;
    }

    const changed = applyExtracted(match, ex, item.chapters, conflicts);
    if (changed) {
      if (!updated.includes(match.name)) updated.push(match.name);
      changedIds.add(match.id);
    }
  }

  return {
    characters: result,
    added,
    updated,
    changedIds: [...changedIds],
    conflicts,
    mergeCandidates: findMergeCandidates(result),
  };
}

/**
 * 抽出結果を1人分のレコードへ反映する。
 * 既存の値を消さないことを原則とし、食い違いは conflicts に記録する。
 */
function applyExtracted(
  target: Character,
  ex: ExtractedCharacter,
  chapters: number[],
  conflicts: MergeResult["conflicts"]
): boolean {
  let changed = false;
  const validChapters = chapters.filter(Number.isFinite);

  // 別名は和集合。
  // 抽出時の名前が既存レコードと異なる場合（「玲司」で照合されたが
  // 登録名が「黒木 玲司」など）、その呼び名も別名として残す。
  const aliases = new Set(target.aliases);
  const incomingName = ex.name?.trim();
  if (incomingName && incomingName !== target.name && !aliases.has(incomingName)) {
    aliases.add(incomingName);
    changed = true;
  }
  for (const a of ex.aliases ?? []) {
    if (a && a !== target.name && !aliases.has(a)) {
      aliases.add(a);
      changed = true;
    }
  }
  target.aliases = [...aliases];

  if (ex.isMob === true && !target.isMob) {
    target.isMob = true;
    changed = true;
  }

  // 単純なテキスト項目: 空なら埋める。既にあれば食い違いを記録し、上書きしない
  changed = fillOrConflict(target, "role", ex.role, conflicts) || changed;
  changed =
    fillOrConflict(target, "personality", ex.personality, conflicts) || changed;
  changed =
    fillOrConflict(target, "appearance", ex.appearance, conflicts) || changed;

  // 一人称
  if (ex.firstPerson) {
    if (!target.firstPerson.default) {
      target.firstPerson.default = ex.firstPerson;
      changed = true;
    } else if (target.firstPerson.default !== ex.firstPerson) {
      // 場面によって変わることがあるため、矛盾ではなく変化形として保持する
      const exists = target.firstPerson.variants.some(
        (v) => v.form === ex.firstPerson
      );
      if (!exists) {
        target.firstPerson.variants.push({
          form: ex.firstPerson,
          context: null,
          chapters: [...validChapters],
          evidence: ex.evidence ?? null,
        });
        changed = true;
      }
    }
  }

  if (ex.defaultSecondPerson && !target.defaultSecondPerson) {
    target.defaultSecondPerson = ex.defaultSecondPerson;
    changed = true;
  }

  // 呼称: 相手ごとにまとめ、異なる呼び方はすべて残す
  for (const at of ex.addressTerms ?? []) {
    if (!at.targetName || !at.term) continue;
    if (mergeAddressTerm(target, at, validChapters)) changed = true;
  }

  // 関係
  for (const rel of ex.relations ?? []) {
    if (!rel.name || !rel.relation) continue;
    const exists = target.relations.some(
      (r) => r.name === rel.name && r.relation === rel.relation
    );
    if (!exists) {
      target.relations.push({ name: rel.name, relation: rel.relation });
      changed = true;
    }
  }

  if (!target.evidence && ex.evidence) {
    target.evidence = ex.evidence;
    changed = true;
  }

  const before = target.appearedChapters.length;
  target.appearedChapters = mergeChapters(target.appearedChapters, validChapters);
  if (target.appearedChapters.length !== before) changed = true;

  return changed;
}

/**
 * 呼称をマージする。
 *
 * 同じ term は1件に統合するが、異なる term は統合しない。
 * 「澪」と「白瀬さん」を1つにまとめてはならない。呼び分けそのものが
 * 管理対象の情報であるため。
 */
function mergeAddressTerm(
  target: Character,
  incoming: NonNullable<ExtractedCharacter["addressTerms"]>[number],
  chapters: number[]
): boolean {
  let entry: AddressTerm | undefined = target.addressTerms.find(
    (a) => normalizeName(a.targetName) === normalizeName(incoming.targetName)
  );

  if (!entry) {
    entry = {
      targetName: incoming.targetName,
      targetId: null,
      forms: [],
      authorLocked: false,
    };
    target.addressTerms.push(entry);
  }

  // 作者がロックした呼称は触らない
  if (entry.authorLocked) return false;

  const chapter = chapters.length > 0 ? Math.min(...chapters) : null;
  const lastChapter = chapters.length > 0 ? Math.max(...chapters) : null;

  const existingForm = entry.forms.find((f) => f.term === incoming.term);
  if (existingForm) {
    let changed = false;
    if (
      chapter !== null &&
      (existingForm.firstChapter === null || chapter < existingForm.firstChapter)
    ) {
      existingForm.firstChapter = chapter;
      changed = true;
    }
    if (
      lastChapter !== null &&
      (existingForm.lastChapter === null ||
        lastChapter > existingForm.lastChapter)
    ) {
      existingForm.lastChapter = lastChapter;
      changed = true;
    }
    if (!existingForm.context && incoming.context) {
      existingForm.context = incoming.context;
      changed = true;
    }
    return changed;
  }

  entry.forms.push({
    term: incoming.term,
    category: incoming.category ?? null,
    context: incoming.context ?? null,
    firstChapter: chapter,
    lastChapter: lastChapter,
    status: "current",
    evidence: incoming.evidence ?? null,
  });
  return true;
}

/**
 * 空なら埋め、既存値と違えば conflicts に記録する。
 * 既存の記述は削除しない。設定側が正しいのか本文側が正しいのかは
 * AIには判断できないため、作者に委ねる。
 */
function fillOrConflict(
  target: Character,
  field: "role" | "personality" | "appearance",
  incoming: string | null | undefined,
  conflicts: MergeResult["conflicts"]
): boolean {
  const value = incoming?.trim();
  if (!value) return false;

  const current = target[field];
  if (!current) {
    target[field] = value;
    return true;
  }
  if (current === value) return false;

  // 短い記述が長い記述に含まれる場合は、詳細な方を採用する
  if (value.includes(current)) {
    target[field] = value;
    return true;
  }
  if (current.includes(value)) return false;

  const already = target.conflicts.find((c) => c.field === field);
  if (already) {
    if (!already.values.includes(value)) {
      already.values.push(value);
      conflicts.push({
        characterName: target.name,
        field,
        values: already.values,
      });
      return true;
    }
    return false;
  }

  target.conflicts.push({
    field,
    values: [current, value],
    chapters: [...target.appearedChapters],
    note: null,
  });
  conflicts.push({
    characterName: target.name,
    field,
    values: [current, value],
  });
  return true;
}

function findCharacter(
  list: Character[],
  name: string,
  aliases: string[]
): Character | undefined {
  const incomingNames = [name, ...aliases];
  const keys = new Set(incomingNames.map(normalizeName));
  const exactMatches = list.filter((c) => {
    const candidates = [c.name, ...c.aliases].map(normalizeName);
    return candidates.some((candidate) => keys.has(candidate));
  });
  if (exactMatches.length === 1) return exactMatches[0];
  if (exactMatches.length > 1) return undefined;

  // 部分名は、姓名が空白・中黒で明示的に区切られている場合だけ使う。
  // 推測による部分一致は別人を壊すため、候補が一人に決まる場合に限る。
  const incomingParts = new Set(incomingNames.flatMap(splitNameParts));
  const partMatches = list.filter((character) =>
    [character.name, ...character.aliases].some((candidate) =>
      incomingParts.has(normalizeName(candidate)) ||
      splitNameParts(candidate).some((part) => keys.has(part))
    )
  );
  return partMatches.length === 1 ? partMatches[0] : undefined;
}

// 省略はカタカナ語で起きやすい。漢字を含む名前の部分一致は
// 別人（「田中」と「田中村」等）の可能性が高いため対象にしない。
const KATAKANA_ONLY = /^[ァ-ヶーｦ-ﾟ]+$/u;
/** これ以上に長さが開く組は、省略ではなく別語とみなす */
const MAX_LENGTH_RATIO = 2.5;

/**
 * 省略形とみられる組を洗い出す。統合はしない。
 *
 * 日本語の省略は元の語から文字を順に抜き出す形が多い
 * （ギルドマスター → ギルマス）ため、部分列であることを手掛かりにする。
 */
export function findMergeCandidates(characters: Character[]): MergeCandidate[] {
  const candidates: MergeCandidate[] = [];

  for (let i = 0; i < characters.length; i++) {
    for (let j = i + 1; j < characters.length; j++) {
      const a = characters[i];
      const b = characters[j];

      // すでに別名として統合済みの組は候補にしない
      if (sharesAppellation(a, b)) continue;

      const pair = appellationPairs(a, b).find(([left, right]) =>
        isAbbreviationOf(left, right)
      );
      if (pair) {
        candidates.push({ names: [a.name, b.name], reason: "abbreviation" });
      }
    }
  }
  return candidates;
}

function sharesAppellation(a: Character, b: Character): boolean {
  const keys = new Set([a.name, ...a.aliases].map(normalizeName));
  return [b.name, ...b.aliases].some((name) => keys.has(normalizeName(name)));
}

/** 2人の呼称の総当たりを、短い方・長い方の順で返す */
function appellationPairs(a: Character, b: Character): Array<[string, string]> {
  const pairs: Array<[string, string]> = [];
  for (const left of [a.name, ...a.aliases]) {
    for (const right of [b.name, ...b.aliases]) {
      pairs.push(
        left.length <= right.length ? [left, right] : [right, left]
      );
    }
  }
  return pairs;
}

/** shorter が longer の省略形とみられるか */
export function isAbbreviationOf(shorter: string, longer: string): boolean {
  if (shorter.length < 2 || shorter.length >= longer.length) return false;
  if (!KATAKANA_ONLY.test(shorter) || !KATAKANA_ONLY.test(longer)) return false;
  if (longer.length / shorter.length > MAX_LENGTH_RATIO) return false;
  // 省略形は語頭を残すのが普通。頭が違うものは別語とみなす
  if (shorter[0] !== longer[0]) return false;
  return isSubsequence(shorter, longer);
}

function isSubsequence(shorter: string, longer: string): boolean {
  let index = 0;
  for (const char of longer) {
    if (char === shorter[index]) index++;
    if (index === shorter.length) return true;
  }
  return index === shorter.length;
}

function splitNameParts(name: string): string[] {
  if (!/[\s　・･]/.test(name)) return [];
  return name
    .split(/[\s　・･]+/)
    .map(normalizeName)
    .filter(Boolean);
}

// 同一人物判定でだけ使う。呼称の使い分け自体は addressTerms 側の
// 管理対象なので、name/aliases に保存する文字列はこの敬称を残したままにする
const HONORIFIC_SUFFIXES = ["さん", "くん", "君", "ちゃん", "様", "さま", "殿", "先輩", "氏"];

/**
 * 表記ゆれを吸収する。全角空白・記号の違いで別人扱いしないため。
 * 敬称の有無も同様の理由で吸収する（「シル」と「シルさん」を別人扱いしない）。
 */
function normalizeName(s: string): string {
  const base = s
    .replace(/[\s　・･]/g, "")
    .replace(/[０-９]/g, (c) => String.fromCharCode(c.charCodeAt(0) - 0xfee0))
    .toLowerCase();

  for (const suffix of HONORIFIC_SUFFIXES) {
    if (base.endsWith(suffix) && base.length > suffix.length) {
      return base.slice(0, -suffix.length);
    }
  }
  return base;
}

function mergeChapters(existing: number[], incoming: number[]): number[] {
  const set = new Set(existing);
  for (const n of incoming) {
    if (Number.isFinite(n)) set.add(n);
  }
  return [...set].sort((a, b) => a - b);
}
