import type { Character } from "../models/character";
import { mergeChangeLists, mergeConflicts } from "../models/jsonValidation";

/**
 * 同一人物として登録されてしまった2件を1件にまとめる。
 *
 * **作者が書いた内容は絶対に失わない。** 片方にしかない記述は残し、
 * 両方にある場合も捨てずに併記する。まとめる操作は作者の判断だが、
 * 「まとめたら作者メモが消えた」は取り返しがつかない。
 *
 * 取り下げる側のファイルは呼び出し側が回復用の場所へ退避する
 * （`CharacterStore.retire`）。消さないのは、別人をまとめてしまったときに
 * 元へ戻せるようにするため。
 */

export interface UnifyResult {
  /** まとめた結果。keep 側のIDを引き継ぐ */
  unified: Character;
  /** 取り下げる側のID */
  retiredId: string;
}

export function unifyCharacters(keep: Character, absorb: Character): UnifyResult {
  if (keep.id === absorb.id) {
    throw new Error("同じ人物どうしはまとめられません。");
  }

  const aliases = new Set([...keep.aliases, absorb.name, ...absorb.aliases]);
  aliases.delete(keep.name);

  return {
    unified: {
      ...keep,
      aliases: [...aliases].filter((alias) => alias.trim()),
      summary: keep.summary ?? absorb.summary,
      affiliation: keep.affiliation ?? absorb.affiliation,
      reading: keep.reading ?? absorb.reading,
      romaji: keep.romaji ?? absorb.romaji,
      icon: keep.icon ?? absorb.icon,
      iconSource: keep.icon ? keep.iconSource : absorb.iconSource,
      role: keep.role ?? absorb.role,
      personality: keep.personality ?? absorb.personality,
      appearance: keep.appearance ?? absorb.appearance,
      physical: keep.physical ?? absorb.physical,
      firstPerson: {
        default: keep.firstPerson.default ?? absorb.firstPerson.default,
        variants: [
          ...keep.firstPerson.variants,
          ...absorb.firstPerson.variants,
        ],
      },
      defaultSecondPerson:
        keep.defaultSecondPerson ?? absorb.defaultSecondPerson,
      // 呼称は「誰が誰をどう呼ぶか」なので、取り下げ側の名前で
      // 記録されていた分は、まとめた後の名前へ付け替える
      addressTerms: [
        ...keep.addressTerms,
        ...absorb.addressTerms.map((term) =>
          term.targetName === absorb.name
            ? { ...term, targetName: keep.name }
            : term
        ),
      ],
      relations: dedupeBy(
        [...keep.relations, ...absorb.relations],
        // 区切りにNULを使うのは、名前にも関係にも現れない文字だから。
        // ソースには生のNULを置かずエスケープで書く。生のまま置くと、
        // gitやgrepがこのファイルをバイナリとみなして差分を見せてくれない
        // （実際にそうなっていた）
        (relation) => `${relation.name}\u0000${relation.relation}`
      ),
      abilities: dedupeBy(
        [...keep.abilities, ...absorb.abilities],
        (ability) => ability.name
      ),
      appearedChapters: [
        ...new Set([...keep.appearedChapters, ...absorb.appearedChapters]),
      ].sort((a, b) => a - b),
      // 未登場どうしのときだけ未登場のまま
      status:
        keep.status === "登場済み" || absorb.status === "登場済み"
          ? "登場済み"
          : "未登場",
      // 公開範囲は狭いほうに合わせる。広げると意図せず外へ出る
      spoilerLevel: narrowerSpoiler(keep.spoilerLevel, absorb.spoilerLevel),
      // 作者が書いた文章は片方を捨てず両方残す
      authorNotes: joinAuthorText(keep.authorNotes, absorb.authorNotes),
      exportNote: joinAuthorText(keep.exportNote, absorb.exportNote),
      // まとめるのは作者の判断。以後の抽出で作り直させない
      autoGenerated: false,
      // 名前のある人物とモブをまとめたなら、モブ扱いをやめる
      isMob: keep.isMob && absorb.isMob,
      evidence: keep.evidence ?? absorb.evidence,
      // 同じ項目の食い違いは1つにまとめる。並べるだけだと、
      // 以後のマージが最初の1件しか見ないため取り残しになる
      conflicts: mergeConflicts(keep.conflicts, absorb.conflicts),
      // 作者が確定させた変化。片方にしか無いものも必ず残す
      changes: mergeChangeLists(keep.changes, absorb.changes),
      aiNotes: [...keep.aiNotes, ...absorb.aiNotes],
    },
    retiredId: absorb.id,
  };
}

const SPOILER_ORDER = ["public", "staff_only", "author_only"] as const;

function narrowerSpoiler(
  left: Character["spoilerLevel"],
  right: Character["spoilerLevel"]
): Character["spoilerLevel"] {
  return SPOILER_ORDER.indexOf(left) >= SPOILER_ORDER.indexOf(right)
    ? left
    : right;
}

/** 両方に文章があれば区切って併記する。片方を捨てない */
function joinAuthorText(keep: string, absorb: string): string {
  const left = keep.trim();
  const right = absorb.trim();
  if (!right) return left;
  if (!left) return right;
  if (left.includes(right)) return left;
  return `${left}\n\n${right}`;
}

function dedupeBy<T>(items: T[], key: (item: T) => string): T[] {
  const seen = new Set<string>();
  const result: T[] = [];
  for (const item of items) {
    const id = key(item);
    if (seen.has(id)) continue;
    seen.add(id);
    result.push(item);
  }
  return result;
}
