import {
  emptyCharacter,
  nextCharacterId,
  type Character,
} from "../models/character";
import { normalizeName } from "./characterMerge";
import { fillReading } from "./reading";

/**
 * 1つにまとめられてしまった人物を、別人に分ける（設計書6.5.8）。
 *
 * `characterUnify.ts`（まとめる）の対である。作者の指摘：
 * 「アジャンとアジャーノが同一人物として認識されている作品があります」。
 *
 * ## 中身は移さない。名前だけで始める（作者の指定）
 *
 * 紹介・役割・性格・登場話・変化の記録は、**元の人物に残す。**
 * 実データでは第5話に「アジャン」と「アジャーノ」の両方が出るので、
 * どの記述がどちらのものかは**機械では決められない**。
 * 当てずっぽうで振り分けると、作者が書いた文章を別人へ移してしまう。
 *
 * 空の新しい記録は、次の抽出で本文から埋まる。チャンクの鍵は
 * `promptVersion|providerId|model|chunkHash` なので、同じAI・同じモデル・
 * 同じ版なら **AIは一度も呼ばれない**（`chunkCache.ts`）。
 *
 * ## 分けた事実を、両方のレコードへ残す
 *
 * 残さないと、次の抽出でまた1人へ戻る。抽出は毎回まっさらな目で本文を読み、
 * 「アジャン＝アジャーノ」と返してくるからである。塞ぐのは
 * `characterMerge.ts` 側（`distinctFrom` を見る4か所）。
 *
 * ## ここはファイルにも vscode にも触らない
 *
 * 保存するのは呼び出し側（`features/settingsPanel.ts`）。
 * 純粋な関数にしておくと、単体テストで固められる。
 */

export interface SeparationPlan {
  /** 別名を外し、別人の記録を足した元の人物 */
  original: Character;
  /** 新しくできる人物。**名前だけ** */
  created: Character;
  /** 元から外した別名（選んだものと、敬称違いで同じもの） */
  movedAliases: string[];
}

/**
 * 別名を1つ選んで、別人として切り出す。
 *
 * @param alias 別人として切り出す別名。`source.aliases` にあるもの
 * @param all 既にある人物すべて（IDの採番と、名前の重複を見るのに使う）
 */
export function planCharacterSeparation(
  source: Character,
  alias: string,
  all: readonly Character[]
): SeparationPlan {
  const wanted = alias.trim();
  if (!wanted) throw new Error("分ける呼び名を選んでください。");
  if (normalizeName(wanted) === normalizeName(source.name)) {
    throw new Error(
      `「${wanted}」は「${source.name}」自身の呼び名です。別の呼び名を選んでください。`
    );
  }
  if (!source.aliases.some((entry) => entry.trim() === wanted)) {
    throw new Error(`「${source.name}」の別名に「${wanted}」がありません。`);
  }
  const duplicate = all.find(
    (character) =>
      character.id !== source.id &&
      normalizeName(character.name) === normalizeName(wanted)
  );
  if (duplicate) {
    throw new Error(
      `「${duplicate.name}」が既にいます。分ける代わりに、そちらへまとめられないか確かめてください。`
    );
  }

  // 一緒に移すのは、**敬称を落とすと同じになるものだけ**。
  // 「アジャーノさん」は「アジャーノ」と同じ人だが、「アジャン様」は違う。
  // ここを曖昧一致（`isSuffixCallOf` のような後方一致）に広げると、
  // 関係のない呼び名まで持っていかれる。**推測で広げない**
  const key = normalizeName(wanted);
  const movedAliases = source.aliases.filter(
    (entry) => normalizeName(entry) === key
  );

  const created = emptyCharacter(nextCharacterId([...all]), wanted);
  // **自動生成のままにする。** `characterMerge.ts` は autoGenerated: false の
  // レコードへ登場話数しか足さない。false にすると「次の抽出で埋まる」が
  // 永久に成立せず、空の記録が残り続ける（まとめる側が false にするのは、
  // まとめた側は中身が揃っているからで、分けた側は逆）
  created.autoGenerated = true;
  // 公開範囲は元に合わせる。既定（public）へ落とすと、隠していた人物が
  // 分けた拍子に資料へ出る
  created.spoilerLevel = source.spoilerLevel;
  created.isMob = source.isMob;
  created.reading = fillReading(null, wanted);
  created.aliases = movedAliases.filter((entry) => entry.trim() !== wanted);
  created.distinctFrom = [{ name: source.name, id: source.id }];

  const original: Character = {
    ...source,
    aliases: source.aliases.filter((entry) => !movedAliases.includes(entry)),
    // 既にある記録は消さない。作者が何度か分けていることがある
    distinctFrom: [
      ...(source.distinctFrom ?? []).filter(
        (entry) => normalizeName(entry.name) !== key
      ),
      { name: created.name, id: created.id },
    ],
  };

  return { original, created, movedAliases };
}

/* ------------------------------------------------------------------ *
 * 分けたあとの抽出でも中身が入らなかった記録に、取り下げを持ちかける
 * （作者の裁定、2026-10-03「取り下げを持ちかける」。設計書6.5.8）。
 *
 * 分けた呼び名が、実は元の人物への呼びかけだったとき（実機の「お嬢様」）、
 * 抽出はその呼び名を元の人物のものとして読み、`distinctFrom` が戻すのを
 * 止めるので、新しい記録は空のまま残り続ける。
 * ------------------------------------------------------------------ */

/** 一度持ちかけた記録。**IDと名前の組で覚える**（取り下げたあと番号が使い回されるため） */
export interface RetractionOffer {
  id: string;
  name: string;
}

/** 覚書（`.aiwriter/separation-retraction-offered.json`）を読む。壊れていれば空 */
export function parseRetractionOffers(raw: unknown): RetractionOffer[] {
  if (!raw || typeof raw !== "object") return [];
  const offered = (raw as { offered?: unknown }).offered;
  if (!Array.isArray(offered)) return [];
  return offered.filter(
    (entry): entry is RetractionOffer =>
      !!entry &&
      typeof entry === "object" &&
      typeof (entry as RetractionOffer).id === "string" &&
      typeof (entry as RetractionOffer).name === "string"
  ).map((entry) => ({ id: entry.id, name: entry.name }));
}

/**
 * 取り下げてはいけない理由。持ちかけてよければ undefined。
 *
 * **作者が書いた欄が1つでもあれば断る**（CLAUDE.md 規則2）。中身の空さとは
 * 別に見る——作者メモだけ書いて本文の中身が無い記録もありうるが、
 * それを消す話を機械から持ち出さない。押したあとにも、もう一度ここを通す
 * （持ちかけてから押すまでのあいだに、パネルで書かれることがある）。
 */
export function describeRetractionRefusal(record: Character): string | undefined {
  if (!record.autoGenerated) return "作者の手が入った記録です";
  if (record.authorNotes.trim()) return "作者メモが書かれています";
  if (record.exportNote.trim()) return "資料用の補足が書かれています";
  if (Object.values(record.customFields ?? {}).some((value) => value.trim())) {
    return "作者が足した項目に値があります";
  }
  if ((record.rejectedRelations ?? []).length > 0) return "退けた関係の記録があります";
  if ((record.rejectedValues ?? []).length > 0) return "落とした値の記録があります";
  if ((record.changes ?? []).length > 0) return "作中での変化の記録があります";
  if ((record.aiNotes ?? []).length > 0) return "承認した掘り下げメモがあります";
  return undefined;
}

function blank(value: string | null | undefined): boolean {
  return !value || !value.trim();
}

/**
 * 本文から入る欄が、すべて空か。
 *
 * 名前・読み仮名・別名・`distinctFrom`・公開範囲は、分けたときにこちらが
 * 入れたものなので数えない。**登場話が1つでも入っていれば中身ありとみなす**
 * （本文のどこかで、この人物として読まれたということなので）。
 */
function hasNoExtractedContent(record: Character): boolean {
  const physical = record.physical
    ? Object.values(record.physical).every((value) => blank(value))
    : true;
  return (
    blank(record.summary) &&
    blank(record.gender) &&
    blank(record.affiliation) &&
    blank(record.role) &&
    blank(record.personality) &&
    blank(record.speechStyle) &&
    blank(record.appearance) &&
    physical &&
    (record.personalityFacets ?? []).length === 0 &&
    (record.speechStyleFacets ?? []).length === 0 &&
    blank(record.firstPerson?.default) &&
    (record.firstPerson?.variants ?? []).length === 0 &&
    blank(record.defaultSecondPerson) &&
    record.addressTerms.length === 0 &&
    record.relations.length === 0 &&
    record.abilities.length === 0 &&
    record.appearedChapters.length === 0 &&
    blank(record.evidence) &&
    record.conflicts.length === 0
  );
}

/**
 * 取り下げを持ちかける記録を選ぶ。
 *
 * - 別人として分けた記録（`distinctFrom` がある）で、本文から入る欄が空
 * - **今回の抽出で更新案が出ていない**（出ていれば中身が見つかって承認待ちにある）
 * - 作者が書いた欄が無い（`describeRetractionRefusal`）
 * - **まだ一度も持ちかけていない**（断られた記録に毎回訊かない）
 *
 * 元の人物も `distinctFrom` を持つが、中身があるのでここには来ない。
 */
export function findEmptySeparatedCharacters(
  characters: readonly Character[],
  options: {
    /** 今回の抽出で更新案（承認待ち）に回った人物のID */
    updatedIds: ReadonlySet<string>;
    offered: readonly RetractionOffer[];
  }
): Character[] {
  return characters.filter(
    (record) =>
      (record.distinctFrom ?? []).length > 0 &&
      !options.updatedIds.has(record.id) &&
      !options.offered.some(
        (entry) => entry.id === record.id && entry.name === record.name
      ) &&
      describeRetractionRefusal(record) === undefined &&
      hasNoExtractedContent(record)
  );
}

/** 取り下げる前に見せる、何を消すかの説明 */
export function describeRetractionDetail(
  record: Character,
  fileName: string
): string {
  const from = (record.distinctFrom ?? []).map((entry) => `「${entry.name}」`).join("");
  return [
    `「${record.name}」は${from}から別の人物として分けた記録ですが、` +
      "分けたあとの抽出でも、本文から紹介・役割・登場話などが見つかりませんでした。" +
      `本文の「${record.name}」は、${from || "ほかの人物"}への呼びかけかもしれません。`,
    "",
    "取り下げるもの",
    `　ファイル：${fileName}`,
    `　名前：${record.name}` +
      (record.aliases.length > 0 ? `（別名：${record.aliases.join("、")}）` : ""),
    "　中身：空（紹介・役割・性格・登場話は入っていません）",
    "",
    "ファイルは消さず、回復用の場所（設定/characters/.novelai-recovery）へ移します。あとから戻せます。",
    `${from || "元の人物"}の「別人」の記録はそのまま残るので、次の抽出で「${record.name}」が元の人物の別名へ戻ることはありません。`,
  ].join("\n");
}
