import {
  AddressTerm,
  Character,
  emptyCharacter,
  nextCharacterId,
  type CharacterTextField,
} from "../models/character";
import { ExtractedCharacter } from "../prompts/characterExtract";
import { clampSummary } from "./summaryLimit";
import { fillReading } from "./reading";
import { normalizeGender } from "./gender";
import { isMeaningfulValue } from "./characterExtractionValidation";
import {
  hasChange,
  recordChangeChapters,
  recordObservation,
} from "../models/jsonValidation";
import {
  chaptersOfValue,
  foldCharacterConflicts,
  latestValueOfField,
  overlaps,
  recordValue,
  refineValue,
} from "./recordChanges";

/**
 * 抽出結果を既存の人物一覧へマージする。
 *
 * 設計書ではReduce段階もAIに任せる案だったが、実装ではコード側で行う。
 * 理由は3つ:
 *  1. 作者の加筆を確実に保護できる（AIの指示追従に依存しない）
 *  2. 同じ入力なら必ず同じ結果になる
 *  3. AI呼び出し回数が減り、処理時間とコストが下がる
 *
 * AIには「本文から情報を取り出す」ことだけをさせ、
 * 「既存データとどう統合するか」はコードが決める。
 */
export interface MergeResult {
  characters: Character[];
  added: string[];
  updated: string[];
  /** 実際に追加・更新された人物。不要なJSON再書き込みを避けるために使う */
  changedIds: string[];
  /** 既存と食い違い、作者の判断が必要になったもの */
  conflicts: Array<{ characterName: string; field: string; values: string[] }>;
  /**
   * 作中の変化として自動で畳んだもの。
   * **黙って書き換えたことにしないため**、件数を作者へ伝えるのに使う。
   */
  folded: Array<{ characterName: string; field: string }>;
  /** 同一人物かもしれない組。自動では統合せず、作者の判断に委ねる */
  mergeCandidates: MergeCandidate[];
}

/**
 * 同一人物の可能性がある組。
 *
 * 「ギルドマスター」と「ギルマス」のような省略形は敬称除去では吸収できない。
 * ただし自動で統合すると、別人を1人にまとめてしまったときに
 * 作者のデータを壊すことになる（取り消しも難しい）。
 * 統合し損ねるのは手間で済むが、誤統合は損害になるため、候補の提示に留める。
 */
export interface MergeCandidate {
  names: [string, string];
  /**
   * 組のレコードid。**名前だけでは組を特定できない。**
   * same_name の候補はまさに同名レコードの組であり（「お母さん」が4件）、
   * 名前で引き当てると同じ1件へ潰れて、まとめる操作が必ず失敗する
   */
  ids: [string, string];
  /**
   * abbreviation: 省略形とみられる（「ギルマス」と「ギルドマスター」）
   * suffix: 一方が他方の言い方を含む（「近所のおばあさん」と「ばあさん」）
   * name_part: 姓名を繋げた名前と、名だけの名前（「密倉文佳」と「文佳」）
   * ambiguous: 統合先が複数あって決められなかった
   * same_name: 同じ呼称なのに別レコードになっている
   */
  reason:
    | "abbreviation"
    | "suffix"
    | "name_part"
    | "ambiguous"
    | "same_name";
}

export function mergeExtractedCharacters(
  existing: Character[],
  extracted: Array<{ data: ExtractedCharacter; chapters: number[] }>
): MergeResult {
  // 作者が管理している元レコードを、入れ子の配列・オブジェクトを含めて保護する。
  const result: Character[] = existing.map((character) => structuredClone(character));
  const added: string[] = [];
  const updated: string[] = [];
  const changedIds = new Set<string>();
  const conflicts: MergeResult["conflicts"] = [];
  /** 統合先を決められず新規にした組。作者の判断へ回す */
  const ambiguousPairs: Array<{
    names: [string, string];
    ids: [string, string];
  }> = [];

  for (const item of extracted) {
    const ex = item.data;
    if (!ex.name || !ex.name.trim()) continue;

    const lookup = findCharacter(result, ex.name, ex.aliases ?? []);
    const match = lookup.match;

    if (!match) {
      const c = emptyCharacter(nextCharacterId(result), ex.name.trim());
      applyExtracted(c, ex, item.chapters, conflicts);
      result.push(c);
      added.push(c.name);
      changedIds.add(c.id);
      // 統合先が複数あって決められなかった場合、データは残しつつ
      // 「どれかと同じかもしれない」ことを作者へ伝える。
      // 黙って新規にすると重複が増えるだけで気づけない。
      for (const other of lookup.ambiguous) {
        if (isDeclaredDistinct(c, other)) continue;
        ambiguousPairs.push({ names: [c.name, other.name], ids: [c.id, other.id] });
      }
      continue;
    }

    // 同名の相手が他にもいた場合、寄せ先へ統合したうえで
    // 「これらも同じかもしれない」と作者へ伝える。
    // 統合そのものは作者が決める（誤統合は取り返しがつかない）
    // 作者が「別人だ」と決めた組は、ここでも作者へ回さない（設計書6.5.8）。
    // 回すと「同じかもしれません」と毎回聞かれ、分けた判断が尊重されない
    for (const other of lookup.ambiguous) {
      if (isDeclaredDistinct(match, other)) continue;
      ambiguousPairs.push({ names: [match.name, other.name], ids: [match.id, other.id] });
    }

    // 作者が確定させた人物はAIで書き換えない。
    // 登場話数の追記だけ行う。
    if (!match.autoGenerated) {
      const before = match.appearedChapters.length;
      match.appearedChapters = mergeChapters(
        match.appearedChapters,
        item.chapters
      );
      if (match.appearedChapters.length !== before) {
        updated.push(match.name);
        changedIds.add(match.id);
      }
      continue;
    }

    const changed = applyExtracted(match, ex, item.chapters, conflicts);
    if (changed) {
      if (!updated.includes(match.name)) updated.push(match.name);
      changedIds.add(match.id);
    }
  }

  // 話数の違う値は、作者に聞かずに作中の変化として畳む。
  // 聞いていた頃は、話ごとに違う言い方をされた要約がすべて食い違いとして
  // 積み上がり、資料が読めなくなっていた（実データで太志のsummaryが9段）。
  // **同じ話の中で矛盾しているものだけを作者へ回す**（`isFoldableConflict`）。
  //
  // 今回触れなかった人物にも掛ける。既に積み上がっている食い違いを
  // 畳むのが目的なので、対象を今回の更新分に絞ると古い分が残り続ける。
  const folded: MergeResult["folded"] = [];
  for (let index = 0; index < result.length; index++) {
    const character = result[index];
    // 作者が確定させたレコードは、こちらから書き換えない
    if (!character.autoGenerated) continue;
    const outcome = foldCharacterConflicts(character);
    if (outcome.folded.length === 0) continue;
    result[index] = outcome.character;
    changedIds.add(outcome.character.id);
    if (!updated.includes(outcome.character.name)) {
      updated.push(outcome.character.name);
    }
    for (const field of outcome.folded) {
      folded.push({ characterName: outcome.character.name, field });
    }
  }

  return {
    characters: result,
    added,
    updated,
    changedIds: [...changedIds],
    // 立てた直後に畳んだものは、作者の判断待ちではない。
    // 報告に残すと「見てください」と言われた先に何も無いことになる
    conflicts: conflicts.filter(
      (entry) =>
        !folded.some(
          (item) =>
            item.characterName === entry.characterName &&
            item.field === entry.field
        )
    ),
    folded,
    mergeCandidates: [
      ...ambiguousPairs.map((pair) => ({
        ...pair,
        reason: "ambiguous" as const,
      })),
      ...findMergeCandidates(result),
    ],
  };
}

/**
 * 抽出結果を1人分のレコードへ反映する。
 * 既存の値を消さないことを原則とし、食い違いは conflicts に記録する。
 */
function applyExtracted(
  target: Character,
  ex: ExtractedCharacter,
  chapters: number[],
  conflicts: MergeResult["conflicts"]
): boolean {
  let changed = false;
  const validChapters = chapters.filter(Number.isFinite);

  // 別名は和集合。
  // 抽出時の名前が既存レコードと異なる場合（「玲司」で照合されたが
  // 登録名が「黒木 玲司」など）、その呼び名も別名として残す。
  //
  // **作者が「別人だ」と決めた呼び名は足さない**（設計書6.5.8）。
  // 抽出は毎回まっさらな目で本文を読むので、分けた翌日にはまた
  // 「アジャン＝アジャーノ」と返してくる。ここで受け取ると別名が戻り、
  // 用語ハイライトもIME辞書も1人に戻る。
  const aliases = new Set(target.aliases);
  const incomingName = ex.name?.trim();
  const incoming = withoutDistinctNames(target, [
    ...(incomingName ? [incomingName] : []),
    ...(ex.aliases ?? []).filter((a): a is string => Boolean(a)),
  ]);
  for (const a of incoming) {
    if (a !== target.name && !aliases.has(a)) {
      aliases.add(a);
      changed = true;
    }
  }
  target.aliases = [...aliases];

  if (ex.isMob === true && !target.isMob) {
    target.isMob = true;
    changed = true;
  }

  // 読みはカタカナならコード側で確実に作る。
  // 漢字を含む名前だけAIの推定（ex.reading）に委ねる
  changed =
    fillOrConflict(target, "reading", ex.reading, validChapters, conflicts) || changed;
  const derived = fillReading(target.reading, target.name);
  if (derived !== target.reading) {
    target.reading = derived;
    changed = true;
  }

  // 紹介文は長さをコード側で確かめてから入れる。
  // プロンプトで字数を指示しても、モデルは平気で超えてくる
  changed =
    fillOrConflict(target, "summary", clampSummary(ex.summary), validChapters, conflicts) ||
    changed;
  changed =
    fillOrConflict(target, "affiliation", ex.affiliation, validChapters, conflicts) || changed;

  // 性別はAIが本文の言い方のまま返してくるので、ここで「男性」「女性」に揃える。
  // 揃えないと、同じ人物が話ごとに「男」「男性」と揺れて食い違い扱いになる
  changed =
    fillOrConflict(target, "gender", normalizeGender(ex.gender), validChapters, conflicts) ||
    changed;

  // 単純なテキスト項目: 空なら埋める。既にあれば食い違いを記録し、上書きしない
  changed = fillOrConflict(target, "role", ex.role, validChapters, conflicts) || changed;
  changed =
    fillOrConflict(target, "personality", ex.personality, validChapters, conflicts) || changed;
  changed =
    fillOrConflict(target, "appearance", ex.appearance, validChapters, conflicts) || changed;

  // 一人称
  if (ex.firstPerson) {
    if (!target.firstPerson.default) {
      target.firstPerson.default = ex.firstPerson;
      changed = true;
    } else if (target.firstPerson.default !== ex.firstPerson) {
      // 場面によって変わることがあるため、矛盾ではなく変化形として保持する
      const exists = target.firstPerson.variants.some(
        (v) => v.form === ex.firstPerson
      );
      if (!exists) {
        target.firstPerson.variants.push({
          form: ex.firstPerson,
          context: null,
          chapters: [...validChapters],
          evidence: ex.evidence ?? null,
        });
        changed = true;
      }
    }
  }

  if (ex.defaultSecondPerson && !target.defaultSecondPerson) {
    target.defaultSecondPerson = ex.defaultSecondPerson;
    changed = true;
  }

  // 呼称: 相手ごとにまとめ、異なる呼び方はすべて残す
  for (const at of ex.addressTerms ?? []) {
    if (!at.targetName || !at.term) continue;
    if (mergeAddressTerm(target, at, validChapters)) changed = true;
  }

  // 関係
  for (const rel of ex.relations ?? []) {
    if (!rel.name || !rel.relation) continue;
    const exists = target.relations.some(
      (r) => r.name === rel.name && r.relation === rel.relation
    );
    if (!exists) {
      target.relations.push({ name: rel.name, relation: rel.relation });
      changed = true;
    }
  }

  if (!target.evidence && ex.evidence) {
    target.evidence = ex.evidence;
    changed = true;
  }

  const before = target.appearedChapters.length;
  target.appearedChapters = mergeChapters(target.appearedChapters, validChapters);
  if (target.appearedChapters.length !== before) changed = true;

  return changed;
}

/**
 * 呼称をマージする。
 *
 * 同じ term は1件に統合するが、異なる term は統合しない。
 * 「澪」と「白瀬さん」を1つにまとめてはならない。呼び分けそのものが
 * 管理対象の情報であるため。
 */
function mergeAddressTerm(
  target: Character,
  incoming: NonNullable<ExtractedCharacter["addressTerms"]>[number],
  chapters: number[]
): boolean {
  let entry: AddressTerm | undefined = target.addressTerms.find(
    (a) => normalizeName(a.targetName) === normalizeName(incoming.targetName)
  );

  if (!entry) {
    entry = {
      targetName: incoming.targetName,
      targetId: null,
      forms: [],
      authorLocked: false,
    };
    target.addressTerms.push(entry);
  }

  // 作者がロックした呼称は触らない
  if (entry.authorLocked) return false;

  const chapter = chapters.length > 0 ? Math.min(...chapters) : null;
  const lastChapter = chapters.length > 0 ? Math.max(...chapters) : null;

  const existingForm = entry.forms.find((f) => f.term === incoming.term);
  if (existingForm) {
    let changed = false;
    if (
      chapter !== null &&
      (existingForm.firstChapter === null || chapter < existingForm.firstChapter)
    ) {
      existingForm.firstChapter = chapter;
      changed = true;
    }
    if (
      lastChapter !== null &&
      (existingForm.lastChapter === null ||
        lastChapter > existingForm.lastChapter)
    ) {
      existingForm.lastChapter = lastChapter;
      changed = true;
    }
    if (!existingForm.context && incoming.context) {
      existingForm.context = incoming.context;
      changed = true;
    }
    return changed;
  }

  entry.forms.push({
    term: incoming.term,
    category: incoming.category ?? null,
    context: incoming.context ?? null,
    firstChapter: chapter,
    lastChapter: lastChapter,
    status: "current",
    evidence: incoming.evidence ?? null,
  });
  return true;
}

/**
 * 空なら埋め、既存値と違えば「作中の変化」か「食い違い」に振り分ける。
 *
 * **振り分けの基準は話数である**（設計書6.18、2026-08-16）。
 *   - 第1話で「黒髪」、第7話で「銀髪」→ 作中で変わったと読む。両方を履歴に残し、
 *     レコードにはいちばん後ろの話の値を入れる
 *   - 同じ第7話で「黒髪」と「銀髪」→ 両方が同時に正しいことはない。
 *     AIの取り違えの可能性が高いので、これまでどおり作者の判断へ回す
 *
 * かつては違う値を必ず食い違いにしていたが、話ごとに違う言い方をされた要約が
 * すべて積み上がり、資料が読めなくなっていた（実データで太志のsummaryが9段）。
 *
 * **既存の値は消えない。** 変化の履歴に残り、資料には
 * 「A（第1話）→ B（第7話）」と両方が並ぶ。
 */
function fillOrConflict(
  target: Character,
  field: CharacterTextField,
  incoming: string | null | undefined,
  /** この値が出てきた話数。食い違いを『変化』として読めるようにする */
  chapters: number[],
  conflicts: MergeResult["conflicts"]
): boolean {
  const value = incoming?.trim();
  if (!value) return false;
  // 「（本文から読み取れる記述なし）」のような、値が無いことを述べた文言は
  // 空欄と同じ扱いにする。そのまま入れると設定資料へ載ってしまう
  if (!isMeaningfulValue(value)) return false;

  const current = target[field];
  if (!current) {
    target[field] = value;
    // **空欄を埋めるときにも話数を残す。** 残さないと、次に違う値が来たときに
    // 「作中で変わった」のか「同じ話で矛盾した」のかを見分けられない
    recordValue(target.changes, field, value, chapters);
    return true;
  }

  // 既に履歴にある値。話数を足し、いちばん後ろの話の値を今の値にする。
  // 作者が確定させた変化を食い違いへ戻さないのも、この経路である
  if (hasChange(target.changes, field, value)) {
    const noted = recordChangeChapters(target.changes, field, value, chapters);
    return adoptLatest(target, field) || noted;
  }

  if (current === value) {
    // 履歴に無い（この項目より前に作られたデータ）。ここで話数が分かるので残す
    const recorded = target.conflicts.find((c) => c.field === field);
    if (recorded) return recordObservation(recorded, value, chapters);
    return recordValue(target.changes, field, value, chapters);
  }

  // 短い記述が長い記述に含まれる場合は、詳細な方を採用する。
  // これは変化ではないので履歴を増やさず、同じ記録を書き換える
  if (value.includes(current)) {
    target[field] = value;
    refineValue(target.changes, field, current, value, chapters);
    return true;
  }
  if (current.includes(value)) return false;

  // ここから先は本当に違う値。話数が重ならなければ作中の変化として扱う。
  // **両方の話数が分かっているときだけ。** 片方でも分からないと前後を
  // 決められず、作者が手で書いた値をAIの読みで押し流しかねない
  const currentChapters = chaptersOfValue(target.changes, field, current);
  if (currentChapters?.length && chapters.length && !overlaps(currentChapters, chapters)) {
    recordValue(target.changes, field, value, chapters);
    adoptLatest(target, field);
    return true;
  }

  const already = target.conflicts.find((c) => c.field === field);
  if (already) {
    const isNewValue = !already.values.includes(value);
    if (isNewValue) already.values.push(value);
    // 同じ値が別の話にも出てきたら、話数だけを足す
    const noted = recordObservation(already, value, chapters);
    if (!isNewValue) return noted;
    conflicts.push({
      characterName: target.name,
      field,
      values: already.values,
    });
    return true;
  }

  target.conflicts.push({
    field,
    values: [current, value],
    chapters: [...target.appearedChapters],
    note: null,
    // 値ごとの話数を残す。並べれば「作中で変わった」のか
    // 「AIが取り違えた」のかを作者が読み分けられる。
    // 履歴に無い古いデータでは、先にあった値の話数が分からないので空にする
    observations: [
      { value: current, chapters: [...(currentChapters ?? [])] },
      { value, chapters: [...chapters] },
    ],
  });
  conflicts.push({
    characterName: target.name,
    field,
    values: [current, value],
  });
  return true;
}

/**
 * 履歴のうち、いちばん後ろの話に出てきた値をレコード本体へ入れる。
 *
 * 入れ直さないと、資料の「外見」が第1話の姿のまま止まる。
 * 話数の分かる値が1つも無ければ何もしない（順序を決められないため）。
 */
function adoptLatest(target: Character, field: CharacterTextField): boolean {
  const latest = latestValueOfField(target.changes, field);
  if (!latest || latest === target[field]) return false;
  target[field] = latest;
  return true;
}

/**
 * 作者が「別人だ」と決めた相手の呼び名（設計書6.5.8）。
 *
 * **敬称を落とした形で持つ。** 抽出は「アジャーノ」とも「アジャーノさん」とも
 * 返してくるので、書かれたままで比べると片方がすり抜ける。
 */
function distinctKeys(character: Character): Set<string> {
  return new Set(
    (character.distinctFrom ?? []).map((entry) => normalizeName(entry.name))
  );
}

/**
 * この2人は、作者が「別人だ」と決めた組か。
 *
 * **片側だけ見ればよい形にしない。** 分ける操作は両方へ記録を入れるが、
 * 作者が片方のJSONを手で直したときに、記録が片側だけになりうる。
 * どちらかが「別人だ」と言っていれば別人として扱う——
 * **作者の判断は、AIの読みより強い**（実装ルール2）。
 */
function isDeclaredDistinct(a: Character, b: Character): boolean {
  if (a.id === b.id) return false;
  const fromA = a.distinctFrom ?? [];
  const fromB = b.distinctFrom ?? [];
  return (
    fromA.some(
      (entry) =>
        entry.id === b.id ||
        [b.name, ...b.aliases].some(
          (name) => normalizeName(name) === normalizeName(entry.name)
        )
    ) ||
    fromB.some(
      (entry) =>
        entry.id === a.id ||
        [a.name, ...a.aliases].some(
          (name) => normalizeName(name) === normalizeName(entry.name)
        )
    )
  );
}

/**
 * 抽出結果の呼び名のうち、このレコードが「別人のもの」と決めたものを外す。
 *
 * 抽出はレコードを知らないので、**まだレコードになっていない呼び方**
 * （分けたばかりで本文からしか出てこない名前）も来る。名前で突き合わせる。
 */
function withoutDistinctNames(
  target: Character,
  names: readonly string[]
): string[] {
  const blocked = distinctKeys(target);
  return names.filter((name) => !blocked.has(normalizeName(name)));
}

/**
 * 統合先の探索結果。
 *
 * 「どれに統合すべきか決まらない」ことと「一致するものが無い」ことを
 * 区別する。前者で黙って新規レコードを作ると、既存2件に加えて3件目ができ、
 * 重複がかえって増えるため（実データで確認）。
 */
interface CharacterLookup {
  match?: Character;
  /** 複数一致して決められなかった相手。作者に提示する */
  ambiguous: Character[];
}

function findCharacter(
  list: Character[],
  name: string,
  aliases: string[]
): CharacterLookup {
  const incomingNames = [name, ...aliases];
  const keys = new Set(incomingNames.map(normalizeName));

  // 作者が「別人だ」と決めた呼び名では引き当てない（設計書6.5.8）。
  //
  // **ここを塞がないと、分ける操作は無意味になる。** 抽出は毎回まっさらな
  // 目で本文を読むので、「アジャン」と「アジャーノ」をまた1人として返す。
  // 名前で引き当てた先が「その名前は別人のものだ」と言っているなら、
  // そのレコードは候補から外す。
  const usable = list.filter((c) => !distinctKeys(c).has(normalizeName(name)));

  const exactMatches = usable.filter((c) => {
    // レコード側が別人だと決めた呼び名は、そのレコードの呼び名として使わない。
    // 作者が手でJSONを直したときなど、別名に残ったままのことがある
    const blocked = distinctKeys(c);
    const candidates = [c.name, ...c.aliases]
      .map(normalizeName)
      .filter((candidate) => !blocked.has(candidate));
    return candidates.some((candidate) => keys.has(candidate));
  });
  if (exactMatches.length === 1) return { match: exactMatches[0], ambiguous: [] };
  if (exactMatches.length > 1) {
    // 主たる名前がそのまま一致する相手だけを寄せ先の候補にする。
    const key = normalizeName(name);
    const samePrimaryName = exactMatches.filter(
      (character) => normalizeName(character.name) === key
    );

    if (samePrimaryName.length > 0) {
      // **同じ名前のレコードが既に複数あるのに、さらに新規を作ってはいけない。**
      // 3件目の別名が次回さらに多くのレコードと一致し、
      // 実行のたびに重複が増える。実データで「密倉 文佳」が3件、
      // 「お母さん」が4件に分裂した。
      //
      // 1件へ寄せたうえで、残りを統合候補として作者に見せる。
      const best =
        samePrimaryName.find((character) => !character.autoGenerated) ??
        samePrimaryName[0];
      return {
        match: best,
        ambiguous: exactMatches.filter((character) => character !== best),
      };
    }

    // 別名でしか一致しない場合は寄せ先を決めない。
    // 「黒木」と「白木」が同じ別名「玲司」を持つとき、どちらへ寄せても
    // 半分は誤りで、しかも既存レコードを汚す。
    // 新規として残せば作者が見て判断できる（誤統合は取り消しにくい）。
    return { ambiguous: exactMatches };
  }

  // 部分名は、姓名が空白・中黒で明示的に区切られている場合だけ使う。
  // 推測による部分一致は別人を壊すため、候補が一人に決まる場合に限る。
  //
  // **ただし、複数の人物が共有する部分（＝姓）では同一人物と判定しない。**
  // 実データで「ジェクティ・コンストラクタ」「ヴォイド・コンストラクタ」
  // 「イント・コンストラクタ」（母・父・息子）が、姓だけの「コンストラクタ」
  // という1件へまとめられた。姓だけのレコードが先にできると、家族が
  // 1人ずつ「候補が一人に決まる」判定を通ってしまい、次々に吸収される。
  const shared = sharedNameParts(list);
  const incomingParts = new Set(
    incomingNames.flatMap(splitNameParts).filter((part) => !shared.has(part))
  );
  const usableKeys = new Set([...keys].filter((key) => !shared.has(key)));

  const partMatches = usable.filter((character) =>
    [character.name, ...character.aliases].some((candidate) =>
      incomingParts.has(normalizeName(candidate)) ||
      splitNameParts(candidate).some((part) => usableKeys.has(part))
    )
  );
  if (partMatches.length === 1) return { match: partMatches[0], ambiguous: [] };
  return { ambiguous: partMatches.length > 1 ? partMatches : [] };
}

/**
 * 姓（家名）とみられる部分を集める。
 *
 * **姓は同一人物の証拠にならない。** 「イント・コンストラクタ」と
 * 「ストリナ・コンストラクタ」は別人であり、共有しているのは家名である。
 *
 * ## 語順で決めない
 *
 * 姓が先か名が先かは作品による（中黒区切りは「名・姓」、和名の空白区切りは
 * 「姓 名」）。**判定に語順を使わない。**
 *
 * ## 「何人が持っているか」ではなく「何と組んでいるか」で決める
 *
 * 人数で数えると、**同じ人物の重複レコードで名のほうも姓に見えてしまう。**
 * 実データでは「ヴォイド・コンストラクタ」が3件に分裂しており、
 * 人数で数えると「ヴォイド」まで姓と判定された。そうなると
 * 「ヴォイド」だけで呼ばれたときに本人へ寄せられなくなる。
 *
 * 組んだ相手の種類で数えれば、重複しても相手は同じなので増えない。
 * 実データ84人で、コンストラクタ4・フォートラン4・シーゲン3（いずれも家名）と、
 * ヴォイド1・ポインタ1（いずれも名）がきれいに分かれた。
 */
export function sharedNameParts(characters: readonly Character[]): Set<string> {
  // 部分 → 一緒に並んでいた別の部分の種類
  const partners = new Map<string, Set<string>>();

  for (const character of characters) {
    for (const full of [character.name, ...character.aliases]) {
      const parts = splitNameParts(full);
      for (const part of parts) {
        const set = partners.get(part) ?? new Set<string>();
        for (const other of parts) {
          if (other !== part) set.add(other);
        }
        partners.set(part, set);
      }
    }
  }

  const shared = new Set<string>();
  for (const [part, others] of partners) {
    // 2種類以上と組んでいれば家名とみなす。
    // 1種類だけなら、その相手との組でしか出てこない＝名とみなす
    if (others.size >= 2) shared.add(part);
  }
  return shared;
}

// 省略はカタカナ語で起きやすい。漢字を含む名前の部分一致は
// 別人（「田中」と「田中村」等）の可能性が高いため対象にしない。
const KATAKANA_ONLY = /^[ァ-ヶーｦ-ﾟ]+$/u;
/** これ以上に長さが開く組は、省略ではなく別語とみなす */
const MAX_LENGTH_RATIO = 2.5;

/**
 * 省略形とみられる組を洗い出す。統合はしない。
 *
 * 日本語の省略は元の語から文字を順に抜き出す形が多い
 * （ギルドマスター → ギルマス）ため、部分列であることを手掛かりにする。
 */
export function findMergeCandidates(characters: Character[]): MergeCandidate[] {
  const candidates: MergeCandidate[] = [];
  const appellations = buildAppellationIndex(characters);

  for (let i = 0; i < characters.length; i++) {
    for (let j = i + 1; j < characters.length; j++) {
      const a = characters[i];
      const b = characters[j];

      // 作者が「別人だ」と決めた組は、候補に出さない（設計書6.5.8）。
      // **出すと、操作メニューの「重複をまとめる」に永久に1件が残る。**
      // 分けたのに「重複しています」と言われ続けるのは、直っていないのと同じ
      if (isDeclaredDistinct(a, b)) continue;

      // 別レコードなのに呼称が重なっている＝ほぼ確実に同一人物。
      // 統合先が決まらず新規になった場合などに起きるので、最優先で伝える。
      const keys = new Set(
        (appellations.get(a.id) ?? []).map(normalizeName)
      );
      if (
        (appellations.get(b.id) ?? []).some((name) =>
          keys.has(normalizeName(name))
        )
      ) {
        candidates.push({ names: [a.name, b.name], ids: [a.id, b.id], reason: "same_name" });
        continue;
      }

      const pairs = appellationPairs(a, b);

      if (pairs.some(([left, right]) => isAbbreviationOf(left, right))) {
        candidates.push({ names: [a.name, b.name], ids: [a.id, b.id], reason: "abbreviation" });
        continue;
      }

      if (pairs.some(([left, right]) => isSuffixCallOf(left, right))) {
        candidates.push({ names: [a.name, b.name], ids: [a.id, b.id], reason: "suffix" });
        continue;
      }

      if (pairs.some(([left, right]) => isFamilyNameForm(left, right))) {
        candidates.push({ names: [a.name, b.name], ids: [a.id, b.id], reason: "name_part" });
      }
    }
  }
  return candidates;
}

/**
 * shorter が longer の後ろに含まれる呼び方か
 * （「ばあさん」と「近所のおばあさん」）。
 *
 * 日本語では、同じ人物を「近所のおばあさん」と説明的に書いたり、
 * 単に「ばあさん」と呼んだりする。AIは場面ごとに違う書き方を拾うため、
 * 別レコードになりやすい。実データで起きた（「いじめられっ子」）。
 *
 * `isAbbreviationOf` はカタカナ語の省略（ギルマス）専用なので、
 * ひらがな・漢字の呼び方は拾えない。
 *
 * **統合はしない。候補として出すだけ。** 別人の可能性は残るので、
 * 判断は作者に委ねる（`findMergeCandidates` の方針）。
 */
export function isSuffixCallOf(shorter: string, longer: string): boolean {
  // ここでは normalizeName を通さない。あれは敬称を落とすので
  // 「ばあさん」が「ばあ」になり、短すぎて判定できなくなる。
  // 呼び方そのものの重なりを見たいので、書かれたまま比べる
  const left = shorter.trim();
  const right = longer.trim();

  // 3字未満だと「先生」「さん」「たち」のような語で無関係な組が大量に並ぶ。
  // 候補が多すぎると作者が全部読まなくなり、機能そのものが死ぬ
  if (left.length < 3) return false;
  if (left.length >= right.length) return false;
  // 離れすぎた長さの組は、たまたま末尾が揃っただけのことが多い
  if (right.length / left.length > MAX_LENGTH_RATIO) return false;

  if (right.endsWith(left)) return true;

  // 「おばあさん」と「近所のばあさん」のように、
  // 丁寧の「お」の有無だけが違う場合も同じ呼び方とみなす
  const bare = stripPolitePrefix(left);
  return bare.length >= 3 && bare !== left && right.endsWith(bare);
}

/** 漢字を1文字でも含むか */
const HAS_KANJI = /[一-鿿㐀-䶿]/u;

/** 姓とみなせる長さ。「密倉」「三門」「春原」「長谷川」まで */
const MAX_FAMILY_NAME_LENGTH = 3;

/**
 * 姓名を繋げた名前と、名だけの名前か（「密倉文佳」と「文佳」）。
 *
 * **日本語の名前は空白で区切られないことが多い。** `splitNameParts` は
 * 空白・中黒がある場合しか分解しないので、「密倉文佳」からは何も取り出せず、
 * 後から「文佳」が出てきても別人として登録される（実データで起きた）。
 *
 * `isSuffixCallOf` は3字以上しか見ない。日本語の名は2字が多いので、
 * 「文佳」「月夜」「太志」はそこを通れない。3字の下限は
 * 「先生」「さん」のような語で候補が溢れるのを防ぐためだった。
 * そこでこちらは**漢字であること**を条件にして、2字から拾えるようにする。
 *
 * **統合はしない。候補として出すだけ。** 「太郎」と「金太郎」のように
 * 別人の可能性は残るので、判断は作者に委ねる（`findMergeCandidates` の方針）。
 */
export function isFamilyNameForm(shorter: string, longer: string): boolean {
  const left = shorter.trim();
  const right = longer.trim();

  // 1字だと「子」「郎」のような字で無関係な組が大量に並ぶ
  if (left.length < 2) return false;
  if (!right.endsWith(left)) return false;

  const family = right.slice(0, right.length - left.length);
  if (family.length < 1 || family.length > MAX_FAMILY_NAME_LENGTH) return false;

  // 姓と名の両方が漢字であること。カタカナ名の省略は isAbbreviationOf が見る。
  // ひらがなだけの語（「ちゃん」「さん」）を姓とみなさないためでもある
  return HAS_KANJI.test(left) && HAS_KANJI.test(family);
}

/**
 * 頭に付く丁寧の「お」「御」を落とす。
 * 「おばあさん」と「ばあさん」は同じ言い方の丁寧・くだけた形にすぎない。
 */
function stripPolitePrefix(name: string): string {
  return name.replace(/^[お御]/, "");
}

/**
 * その人物を指す呼称を、全レコードを横断して集める。
 *
 * **呼称は「呼ぶ側」のレコードに入る。** 「マルキオがリンセップを『リン』と呼ぶ」
 * という情報は、リンセップではなくマルキオのレコードに記録される。
 * そのため1人分のレコードだけを見ても、その人物が何と呼ばれているかは分からない。
 *
 * これを見落としていたため、AIが関連を正しく記録していたにもかかわらず、
 * 「リン」と「リンセップ・アウクト」が別人のまま残っていた（実データで確認）。
 *
 * ただし「姫」「殿下」のような肩書きだけの呼称は、
 * 別人どうしでも一致してしまうため除く。
 */
export function buildAppellationIndex(
  characters: Character[]
): Map<string, string[]> {
  const index = new Map<string, string[]>();

  for (const character of characters) {
    const names = [character.name, ...character.aliases].filter((name) =>
      name.trim()
    );
    const ownKeys = new Set(names.map(normalizeName));
    const collected = new Set(names);

    // 誰のレコードに書かれていても、宛先がこの人物なら呼称として扱う
    for (const speaker of characters) {
      for (const term of speaker.addressTerms) {
        if (!ownKeys.has(normalizeName(term.targetName))) continue;
        for (const form of term.forms) {
          if (isTitleOnly(form.term)) continue;
          collected.add(form.term);
        }
      }
    }
    index.set(character.id, [...collected]);
  }

  return index;
}

/**
 * 肩書き・敬称だけの呼称か。
 * 「姫」「王女殿下」は別の王女とも一致してしまうので同一人物判定に使わない。
 */
function isTitleOnly(term: string): boolean {
  // normalizeName は敬称を落とすので「王女殿下」→「王女」になる
  const normalized = normalizeName(term);
  if (!normalized) return true;
  // 「姫」「殿下」のように敬称そのもの1語だけの呼び方
  if (HONORIFIC_SUFFIX_SOURCE.includes(normalized)) return true;
  return TITLE_WORDS.has(normalized);
}

/** 肩書きだけで人を特定できない語。別の王女とも一致してしまう */
const TITLE_WORDS = new Set([
  "王女", "王子", "王", "女王", "国王", "皇帝", "皇后", "王妃",
  "姫君", "師匠", "隊長", "副隊長", "団長", "会長",
  "社長", "部長", "課長", "店長", "旦那", "奥様", "お嬢様",
]);

/** 2人の呼称の総当たりを、短い方・長い方の順で返す */
function appellationPairs(a: Character, b: Character): Array<[string, string]> {
  const pairs: Array<[string, string]> = [];
  for (const left of [a.name, ...a.aliases]) {
    for (const right of [b.name, ...b.aliases]) {
      pairs.push(
        left.length <= right.length ? [left, right] : [right, left]
      );
    }
  }
  return pairs;
}

/** shorter が longer の省略形とみられるか */
export function isAbbreviationOf(shorter: string, longer: string): boolean {
  if (shorter.length < 2 || shorter.length >= longer.length) return false;
  if (!KATAKANA_ONLY.test(shorter) || !KATAKANA_ONLY.test(longer)) return false;
  if (longer.length / shorter.length > MAX_LENGTH_RATIO) return false;
  // 省略形は語頭を残すのが普通。頭が違うものは別語とみなす
  if (shorter[0] !== longer[0]) return false;
  return isSubsequence(shorter, longer);
}

function isSubsequence(shorter: string, longer: string): boolean {
  let index = 0;
  for (const char of longer) {
    if (char === shorter[index]) index++;
    if (index === shorter.length) return true;
  }
  return index === shorter.length;
}

function splitNameParts(name: string): string[] {
  if (!/[\s　・･]/.test(name)) return [];
  return name
    .split(/[\s　・･]+/)
    .map(normalizeName)
    .filter(Boolean);
}

// 同一人物判定でだけ使う。呼称の使い分け自体は addressTerms 側の
// 管理対象なので、name/aliases に保存する文字列はこの敬称を残したままにする
// 「先生」は敬称として名前に付く（「マイナ先生」＝「マイナ」）。
// 「先生」単独は GENERIC_ROLES 側で人物名から除外されるため、
// ここに入れても役職語だけのレコードを拾うことはない。
/**
 * 名前の後ろに付く敬称。同一人物判定でのみ使い、
 * name / aliases に保存する文字列からは取り除かない
 * （呼び分けそのものが addressTerms の管理対象であるため）。
 *
 * 「殿下」と「妃殿下」のように一方が他方の末尾になる組があるため、
 * 照合は長い敬称から行う（HONORIFIC_SUFFIXES を参照）。
 * 並び順に依存しないよう、定義はここでは自由に足してよい。
 */
const HONORIFIC_SUFFIX_SOURCE = [
  // 一般
  "さん",
  "くん",
  "君",
  "ちゃん",
  "ちゃま",
  "様",
  "さま",
  "殿",
  "氏",
  "女史",
  // 立場・職能
  "先輩",
  "先生",
  "師",
  "卿",
  "翁",
  // 王侯貴族・聖職
  "陛下",
  "妃殿下",
  "殿下",
  "閣下",
  "猊下",
  "聖下",
  "姫",
  "公",
  // 爵位。「ヴォイド・コンストラクタ男爵」と「ヴォイド・コンストラクタ」を
  // 別人扱いしないため。**「夫人」付きも落とす**
  // （「ジェクティ・コンストラクタ男爵夫人」＝「ジェクティ・コンストラクタ」）
  "大公爵夫人",
  "公爵夫人",
  "侯爵夫人",
  "伯爵夫人",
  "子爵夫人",
  "男爵夫人",
  "大公爵",
  "公爵",
  "侯爵",
  "伯爵",
  "子爵",
  "男爵",
];

/**
 * 長い敬称から順に照合する。
 *
 * 「エレナ妃殿下」は「殿下」でも末尾一致するため、
 * 短い方を先に試すと「エレナ妃」が残ってしまう。
 */
const HONORIFIC_SUFFIXES = [...HONORIFIC_SUFFIX_SOURCE].sort(
  (a, b) => b.length - a.length
);

/**
 * 表記ゆれを吸収する。全角空白・記号の違いで別人扱いしないため。
 * 敬称の有無も同様の理由で吸収する（「シル」と「シルさん」を別人扱いしない）。
 */
export function normalizeName(s: string): string {
  const base = s
    .replace(/[\s　・･]/g, "")
    .replace(/[０-９]/g, (c) => String.fromCharCode(c.charCodeAt(0) - 0xfee0))
    .toLowerCase();

  for (const suffix of HONORIFIC_SUFFIXES) {
    if (base.endsWith(suffix) && base.length > suffix.length) {
      return base.slice(0, -suffix.length);
    }
  }
  return base;
}

function mergeChapters(existing: number[], incoming: number[]): number[] {
  const set = new Set(existing);
  for (const n of incoming) {
    // 話数は整数。`isFinite` だと 1.5 が通り、「第1.5話」と表示される。
    // 設定資料側（settingsMerge）と食い違っていたので揃えた
    if (Number.isSafeInteger(n)) set.add(n);
  }
  return [...set].sort((a, b) => a - b);
}
