import { nextCharacterId, type Character } from "../models/character";
import type { RecordConflict } from "../models/jsonValidation";
import {
  buildNewCharacterRecords,
  findCharactersByAppellation,
  type PendingCharacterProposal,
  type PlotCharacterEntry,
  type PlotCharacterPlan,
} from "./plotCharacterSync";

/**
 * 相談で決まったことを、人物の資料へ**直接**書く計画（作者の裁定 J14、
 * 2026-09-26。設計書6.6.3・6.72）。
 *
 * ## なぜ承認待ちとは別に持つのか
 *
 * プロット・紹介文・各話あらすじは相談パネルから直接書けるのに、人物だけは
 * 承認待ち（6.72）を経る形しか無かった。作者は相談で決めたことを、その場で
 * 資料へ入れたい。**ただし承認待ちの道は残す**——どちらにするかは、
 * 作者が押して選ぶ（呼び出し側が確認を出す）。
 *
 * ## 実装ルール2をここで守る
 *
 * - **書くのは紹介文と、食い違いの記録だけ。** 書き込むレコードは台帳の
 *   いまの人物から作り直し、案の側で変わった欄（`authorNotes`・`exportNote`
 *   ・呼称など）は拾わない
 * - **`autoGenerated: false` の人物は書かない。** 承認待ちへ回す
 *   （登場話数の追記だけが許されるが、相談には話数が無い）
 * - **既にある紹介文と食い違うなら上書きしない。** 食い違い（6.18）として
 *   `conflicts` に両方を残し、作者に選ばせる。相談で決めたことでも、
 *   資料に作者が書いた紹介文を黙って押し流さない
 * - 名前を直す案・承認待ちの案に重ねたもの・承認待ちに同じ名前の新規案が
 *   あるものは、**承認待ちへ回す**（直接書くと、承認したときに二重になる）
 *
 * VS Code API に依存しない（画面なしで確かめるため）。
 */

export interface DirectCharacterWritePlan<P extends PendingCharacterProposal> {
  /** 既存の人物の書き換え（紹介文を埋めた・食い違いを足した） */
  writes: Character[];
  /** 新しく作る人物（番号は採ってある） */
  creations: Character[];
  /** 承認待ちへ回すもの（`stageCharacterPlan` へそのまま渡せる形） */
  toPending: PlotCharacterPlan<P>;
  /** 紹介文を埋めた人物の名前 */
  filled: string[];
  /** 食い違いとして残した人物の名前 */
  conflicted: string[];
}

/** 食い違いに添える一言。どこから来た値かが分からないと、作者は選べない */
export const CHAT_CONFLICT_NOTE = "相談で決まった紹介文（資料と食い違うため上書きしていません）";

export function planDirectCharacterWrites<P extends PendingCharacterProposal>(
  plan: PlotCharacterPlan<P>,
  existing: readonly Character[],
  pendingCreations: readonly Character[]
): DirectCharacterWritePlan<P> {
  const byId = new Map(existing.map((character) => [character.id, character]));
  const writes: Character[] = [];
  const filled: string[] = [];
  const conflicted: string[] = [];
  const pendingUpdates: Character[] = [];

  for (const proposal of plan.updates) {
    const current = byId.get(proposal.id);
    // 台帳に居ない・作者が確定させた人物は、ここでは書かない
    if (!current || !current.autoGenerated) {
      pendingUpdates.push(proposal);
      continue;
    }
    const next = (proposal.summary ?? "").trim();
    const before = (current.summary ?? "").trim();
    if (!next || next === before) continue;

    // **台帳のいまの人物から作り直す**（案の側の欄は拾わない）
    const record = structuredClone(current);
    if (!before) {
      record.summary = next;
      filled.push(current.name);
    } else {
      if (!addSummaryConflict(record, before, next)) continue;
      conflicted.push(current.name);
    }
    writes.push(record);
  }

  // 承認待ちに同じ名前の新規案があれば、直接作らない（同じ人が2人になる）
  const directCreations: PlotCharacterEntry[] = [];
  const pendingCreationEntries: PlotCharacterEntry[] = [];
  for (const entry of plan.creations) {
    if (findCharactersByAppellation([...pendingCreations], entry.name).length > 0) {
      pendingCreationEntries.push(entry);
    } else {
      directCreations.push(entry);
    }
  }
  const known = [...existing];
  const creations = buildNewCharacterRecords(directCreations).map((record) => {
    const created: Character = { ...record, id: nextCharacterId(known) };
    known.push(created);
    return created;
  });

  return {
    writes,
    creations,
    toPending: {
      updates: pendingUpdates,
      creations: pendingCreationEntries,
      pendingOverlays: plan.pendingOverlays,
      renames: plan.renames,
      skipped: plan.skipped,
    },
    filled,
    conflicted,
  };
}

/**
 * 紹介文の食い違いを足す。足したら true（同じ値が既にあれば false）。
 *
 * 話数は持たない（相談には話数が無い）。6.18 の「話数の分かる値が1つしか
 * 無い」場合と同じく、前後を決められないので `conflicts` に残す。
 */
function addSummaryConflict(
  record: Character,
  current: string,
  proposed: string
): boolean {
  const found = record.conflicts.find(
    (conflict: RecordConflict) => conflict.field === "summary"
  );
  if (found) {
    if (found.values.includes(proposed)) return false;
    if (!found.values.includes(current)) found.values.push(current);
    found.values.push(proposed);
    if (!found.note) found.note = CHAT_CONFLICT_NOTE;
    return true;
  }
  record.conflicts.push({
    field: "summary",
    values: [current, proposed],
    chapters: [],
    note: CHAT_CONFLICT_NOTE,
  });
  return true;
}

/** 承認待ちへ回すものがあるか */
export function hasPendingPart<P extends PendingCharacterProposal>(
  plan: PlotCharacterPlan<P>
): boolean {
  return (
    plan.updates.length > 0 ||
    plan.creations.length > 0 ||
    plan.pendingOverlays.length > 0 ||
    plan.renames.length > 0
  );
}
