import type { Chunk } from "./chunker";
import type { Character } from "../models/character";
import type { Ability, AbilitySystem } from "../models/ability";
import type { Location } from "../models/location";
import type { Organization } from "../models/organization";
import type { WorldItem } from "../models/world";
import type { CharacterExtractResult } from "../prompts/characterExtract";
import {
  validateCharacterExtractResult,
  type AcceptedCharacterCandidate,
  type CharacterValidationResult,
  type RejectedCharacterCandidate,
} from "./characterExtractionValidation";
import { mergeExtractedCharacters, type MergeResult } from "./characterMerge";
import {
  SettingsExtractionCollector,
  type KnownSettingNames,
} from "./settingsExtractionCollect";
import {
  mergeExtractedAbilities,
  mergeExtractedLocations,
  mergeExtractedOrganizations,
  mergeExtractedWorldItems,
  organizationsFromAffiliations,
  type AbilityMergeResult,
  type LocationMergeResult,
  type OrganizationMergeResult,
  type WorldMergeResult,
} from "./settingsMerge";
import type { RejectedSettingCandidate } from "./settingsExtractionValidation";
import { buildKnownCharacterNames } from "./knownCharacterNames";

/**
 * 設定資料の抽出の「取り出したあと」を、**製品と同じ順で**行う（2026-10-02）。
 *
 * 製品の［設定資料を抽出］（`features/extractCharacters.ts`）は、
 *
 *   チャンクごとに 検算（人物）→ 集める（能力・場所・組織・世界観）
 *   → 全チャンクのあとに マージを1回ずつ → 新規は保存・既存への変更は承認待ち
 *
 * と進む。外部AI（MCP）が抽出を代わりに行ったとき、**同じ答えの列から
 * 同じ資料ができる**ように、この並びを1か所へ置いた。製品の側もここを
 * 呼ぶ（`ExtractionReplay`・`planCharacterSave`・`planSettingsMerge`）ので、
 * 写しにはならない——直したら両方が直る。
 *
 * **マージはAIでなくコードが行う**（CLAUDE.md 規則3）。ここが受け取るのは
 * AIの答え（`parseResult` を通したもの）だけで、既存レコードとの突き合わせは
 * 製品のマージ関数がする。
 *
 * VS Code APIに依存しない（MCP の束から届く。`mcpReach.test.ts`）。
 */

/** 抽出の前に台帳にあったもの。**全件**を渡す（上限で切らない） */
export interface ExtractionBaseline {
  characters: Character[];
  abilities: Ability[];
  locations: Location[];
  organizations: Organization[];
  world: WorldItem[];
}

/**
 * 集める側へ渡す、最初の総称。
 *
 * **製品と同じ決め方**——作者が確定させた総称（`autoGenerated: false`）なら
 * それを使い、AIが入れたものなら本文から読み直す。能力の検算と、指示文の
 * 写しを落とす判定（`dropInstructionEcho`）に効く。
 */
export function initialAbilityTermOf(
  system: AbilitySystem | undefined
): string | null {
  if (!system || system.autoGenerated) return null;
  return system.abilityTerm;
}

/**
 * チャンクごとの受け入れ。**製品の輪の1周ぶん**（キャッシュに当たったときも
 * AIが答えたときも同じ処理）。
 *
 * 育つもの（この回で受け入れた人物）と、育たないもの（台帳の名前）を
 * 分けて持つ——製品は「既存の名前」をループの前に1回だけ作る。チャンクごとに
 * 作り直すと、その回の抽出で増えた名前まで裏付けに混ざり、同じ資料でも
 * 実行のたびに結果が変わる（`features/extractCharacters.ts` の断り書き）。
 */
export class ExtractionReplay<
  C extends SettingsExtractionCollector = SettingsExtractionCollector,
> {
  /** 受け入れた人物（チャンク順）。マージへ渡す */
  readonly extracted: AcceptedCharacterCandidate[] = [];
  /** 検算で落とした人物 */
  readonly rejected: RejectedCharacterCandidate[] = [];
  private readonly existingCharacterNames: string[];
  private readonly authorEditedNames: string[];
  private readonly existingSettingNames: KnownSettingNames;

  constructor(
    private readonly baseline: ExtractionBaseline,
    /**
     * 能力・場所・組織・世界観を集める側。製品は保存まで持つ子クラス
     * （`SettingsExtractionAccumulator`）を渡し、MCP は集めるだけのものを渡す
     */
    readonly settings: C
  ) {
    this.existingCharacterNames = buildKnownCharacterNames(
      baseline.characters,
      []
    );
    // 作者が手で書いた人物の別名は、コードでも触らない（CLAUDE.md 規則2）
    this.authorEditedNames = baseline.characters
      .filter((character) => character.autoGenerated === false)
      .map((character) => character.name);
    // AIに「既知」として見せた名前。その名前で返ったものは、その話の本文に
    // 名前が無くても根拠なしにしない（2026-09-24 の裁定）
    this.existingSettingNames = {
      abilities: baseline.abilities.flatMap((item) => [item.name, ...item.aliases]),
      locations: baseline.locations.flatMap((item) => [item.name, ...item.aliases]),
      organizations: baseline.organizations.flatMap((item) => [
        item.name,
        ...item.aliases,
      ]),
    };
  }

  /** 1チャンクぶんの答えを受け入れる。返すのは人物の検算の結果（報告用） */
  accept(parsed: CharacterExtractResult, chunk: Chunk): CharacterValidationResult {
    const validated = validateCharacterExtractResult(parsed, chunk, {
      knownNames: this.existingCharacterNames,
      authorEditedNames: this.authorEditedNames,
      // AIに「既知の登場人物」として見せた顔ぶれ（既存＋この回の分）
      knownRecordNames: buildKnownCharacterNames(
        this.baseline.characters,
        this.extracted
      ),
    });
    this.extracted.push(...validated.accepted);
    this.rejected.push(...validated.rejected);
    // 同じ答えから能力・場所も取り出す（種別ごとにAIを呼ばない）
    this.settings.collect(parsed, chunk, this.existingSettingNames);
    return validated;
  }
}

/** 変更された人物だけを書き戻す */
export function selectChangedCharacters(
  characters: Character[],
  changedIds: string[]
): Character[] {
  const changed = new Set(changedIds);
  return characters.filter((character) => changed.has(character.id));
}

/** 人物のマージの結果と、書き方で分けたもの */
export interface CharacterSavePlan {
  merged: MergeResult;
  /** 台帳に無かった人物。**そのまま保存してよい**（承認は要らない） */
  created: Character[];
  /**
   * 台帳にいた人物への変更。**その場では書かず承認待ちへ回す**
   * ——作者が内容を見て承認したときにだけ反映する
   */
  updated: Character[];
}

/**
 * 人物を1回マージして、新規と既存への変更に分ける。受け入れた人物が
 * 1人もいなければ `undefined`（製品はマージそのものを行わない）。
 */
export function planCharacterSave(
  existing: Character[],
  extracted: AcceptedCharacterCandidate[]
): CharacterSavePlan | undefined {
  if (extracted.length === 0) return undefined;
  const merged = mergeExtractedCharacters(existing, extracted);
  const changed = selectChangedCharacters(merged.characters, merged.changedIds);
  const existingIds = new Set(existing.map((character) => character.id));
  return {
    merged,
    created: changed.filter((character) => !existingIds.has(character.id)),
    updated: changed.filter((character) => existingIds.has(character.id)),
  };
}

/** 集めたもの（`SettingsExtractionCollector.candidates()` の返り値） */
export type CollectedSettings = ReturnType<
  SettingsExtractionCollector["candidates"]
>;

/** 人物以外のマージの結果。製品の `persist` が件数を数えるのに使う */
export interface SettingsMergePlan {
  abilityMerge: AbilityMergeResult;
  locationMerge: LocationMergeResult;
  organizationMerge: OrganizationMergeResult;
  /** 人物の所属から作った組織（説明付きで抽出できた組織を足したあとに見る） */
  fromAffiliations: OrganizationMergeResult;
  worldMerge: WorldMergeResult;
  /** 変わったレコード（新規と既存への変更の両方） */
  changed: {
    abilities: Ability[];
    locations: Location[];
    organizations: Organization[];
    world: WorldItem[];
  };
}

/**
 * 能力・場所・組織・世界観を1回ずつマージする（`features/extractSettings.ts`
 * の `persist` から切り出した。2026-10-02）。
 *
 * **集めたものが無い種別は、既存を空として扱う。** 製品の `persist` は、
 * 集めたものが無い種別の台帳を読まない。その結果、組織を所属から作るときの
 * 「場所の一覧」も空になる——ここで台帳の場所を渡すと、同じ答えの列でも
 * 製品と違う組織ができる。挙動を変える話は別に決めることで、ここでは揃える。
 */
export function planSettingsMerge(
  collected: CollectedSettings,
  existing: Omit<ExtractionBaseline, "characters">
): SettingsMergePlan {
  const abilitiesBase = collected.abilities.length > 0 ? existing.abilities : [];
  const locationsBase = collected.locations.length > 0 ? existing.locations : [];
  const organizationsBase =
    collected.organizations.length > 0 || collected.affiliations.length > 0
      ? existing.organizations
      : [];
  const worldBase = collected.worldItems.length > 0 ? existing.world : [];

  const abilityMerge = mergeExtractedAbilities(abilitiesBase, [
    ...collected.abilities,
  ]);
  const locationMerge = mergeExtractedLocations(locationsBase, [
    ...collected.locations,
  ]);
  const organizationMerge = mergeExtractedOrganizations(organizationsBase, [
    ...collected.organizations,
  ]);
  // 所属から作る分は、抽出できた組織を足したあとに見る。
  // 先に見ると、AIが説明付きで返した組織を名前だけで作ってしまう
  const fromAffiliations = organizationsFromAffiliations(
    organizationMerge.organizations,
    [...collected.affiliations],
    // 地名を所属に書かれても組織を作らないよう、場所の一覧を渡す
    locationMerge.locations
  );
  const worldMerge = mergeExtractedWorldItems(worldBase, [
    ...collected.worldItems,
  ]);

  const changedOrganizationIds = new Set([
    ...organizationMerge.changedIds,
    ...fromAffiliations.changedIds,
  ]);
  return {
    abilityMerge,
    locationMerge,
    organizationMerge,
    fromAffiliations,
    worldMerge,
    changed: {
      abilities: abilityMerge.abilities.filter((ability) =>
        abilityMerge.changedIds.includes(ability.id)
      ),
      locations: locationMerge.locations.filter((location) =>
        locationMerge.changedIds.includes(location.id)
      ),
      organizations: fromAffiliations.organizations.filter((organization) =>
        changedOrganizationIds.has(organization.id)
      ),
      world: worldMerge.items.filter((item) =>
        worldMerge.changedIds.includes(item.id)
      ),
    },
  };
}

/** 1チャンクぶんの答え。**チャンク順に並べて渡す** */
export interface ReplayChunk {
  chunk: Chunk;
  parsed: CharacterExtractResult;
}

/** 新規と既存への変更に分けたもの */
export interface SplitRecords<T> {
  /** 台帳に無かったもの。そのまま保存してよい */
  created: T[];
  /** 台帳にあったものへの変更。承認待ちへ回す */
  updated: T[];
}

export interface ExtractionReplayResult {
  characters: SplitRecords<Character>;
  abilities: SplitRecords<Ability>;
  locations: SplitRecords<Location>;
  organizations: SplitRecords<Organization>;
  world: SplitRecords<WorldItem>;
  /** 人物のマージの結果（受け入れた人物が0人なら無い）。報告に件数を出す */
  characterMerge?: MergeResult;
  /** 人物以外のマージの結果。報告に件数を出す */
  settingsMerge: SettingsMergePlan;
  /** 検算で落とした人物 */
  rejectedCharacters: RejectedCharacterCandidate[];
  /** 検算で落とした能力・場所・組織・世界観・決まり */
  rejectedSettings: readonly RejectedSettingCandidate[];
  /** 読み取れた能力の総称と決まり（**保存はしない**。報告に出すだけ） */
  abilityTerm: string | null;
  abilityRules: string[];
}

/**
 * 答えの列を、製品と同じ順で通して、保存するものを決める（書かない）。
 *
 * 書き込みは呼んだ側の仕事である——製品は `CharacterStore`・`SettingsStore`、
 * MCP は Node の `fs` で書く。
 */
export function replayExtraction(input: {
  chunks: readonly ReplayChunk[];
  baseline: ExtractionBaseline;
  initialAbilityTerm: string | null;
}): ExtractionReplayResult {
  const replay = new ExtractionReplay(
    input.baseline,
    new SettingsExtractionCollector(input.initialAbilityTerm)
  );
  for (const item of input.chunks) replay.accept(item.parsed, item.chunk);

  const characterPlan = planCharacterSave(
    input.baseline.characters,
    replay.extracted
  );
  const collected = replay.settings.candidates();
  const settingsPlan = planSettingsMerge(collected, input.baseline);

  return {
    characters: {
      created: characterPlan?.created ?? [],
      updated: characterPlan?.updated ?? [],
    },
    abilities: splitByExisting(
      settingsPlan.changed.abilities,
      input.baseline.abilities
    ),
    locations: splitByExisting(
      settingsPlan.changed.locations,
      input.baseline.locations
    ),
    organizations: splitByExisting(
      settingsPlan.changed.organizations,
      input.baseline.organizations
    ),
    world: splitByExisting(settingsPlan.changed.world, input.baseline.world),
    characterMerge: characterPlan?.merged,
    settingsMerge: settingsPlan,
    rejectedCharacters: replay.rejected,
    rejectedSettings: collected.rejected,
    abilityTerm: collected.abilityTerm,
    abilityRules: collected.rules,
  };
}

function splitByExisting<T extends { id: string }>(
  changed: T[],
  existing: readonly T[]
): SplitRecords<T> {
  const ids = new Set(existing.map((record) => record.id));
  return {
    created: changed.filter((record) => !ids.has(record.id)),
    updated: changed.filter((record) => ids.has(record.id)),
  };
}
