import { WorkEntry } from "../models/types";
import { SettingsStore } from "./settingsStore";
import {
  emptyForeshadow,
  foreshadowFileName,
  nextForeshadowId,
  parseForeshadow,
  FORESHADOW_ID_PREFIX,
  type Foreshadow,
  type ForeshadowStatus,
} from "../models/foreshadow";

/**
 * 伏線の台帳（設計書6.35.1）。
 *
 * 保存先は設定フォルダーの `foreshadows/`。**1件1ファイル**にするのは
 * 人物・能力と同じ理由（別の環境で別々の伏線を足しただけでGitが競合する）。
 *
 * 中身は汎用の `SettingsStore` に載せる。この土台には
 * 「読み込み時のハッシュと照合してから書く」「未保存の変更があれば書かない」
 * 「壊れたJSONを修復しない」「消さずに回復先へ退避する」が揃っており、
 * 別に書き直すと、そのどれかを落とす。
 */
export function createForeshadowStore(
  work: WorkEntry
): SettingsStore<Foreshadow> {
  return new SettingsStore<Foreshadow>(work, {
    directoryName: "foreshadows",
    idPrefix: FORESHADOW_ID_PREFIX,
    parse: parseForeshadow,
    fileName: foreshadowFileName,
    // 設定資料は `name` だが、伏線は `label` を見出しにする
    displayName: (foreshadow) => foreshadow.label,
  });
}

/**
 * 作品ごとの順番待ち。
 *
 * **「読んで、採番して、書く」を重ねない。** 提案パネルで「登録」を
 * 続けて押すと、webview のメッセージ処理は並行に走るので、
 * 2件が同時に `loadAll` を通り、**同じIDが2つできる**（あとから書いた
 * ほうが、先に書いたファイルと同じ名前を取り合う）。
 *
 * 考え方は原稿エディタの `core/editQueue.ts` と同じ——当て終わるまで
 * 次を当てない。ただしあちらは「最後の1つに畳む」（画面の本文は全部が
 * 届くので途中は捨ててよい）が、**こちらは1件ずつ全部を保存する。**
 */
const saveQueues = new Map<string, Promise<unknown>>();

/**
 * その作品の台帳への書き込みを、前の1件が終わってから始める。
 *
 * **前の失敗で列を止めない。** 1件が保存できなかっただけで、以降の
 * 「登録」が永久に効かなくなるのは、いちばん困る形である。
 */
function enqueue<T>(work: WorkEntry, task: () => Promise<T>): Promise<T> {
  const key = work.id || work.folderPath;
  const previous = saveQueues.get(key) ?? Promise.resolve();
  const next = previous.then(task, task);
  saveQueues.set(
    key,
    next.catch(() => undefined)
  );
  return next;
}

/** 台帳へ1件足すときに、呼び出し側が決められるところ */
export interface ForeshadowDraft {
  label: string;
  note?: string;
  plantedChapter?: number | null;
  plantedQuote?: string;
  source: Foreshadow["source"];
  autoGenerated?: boolean;
}

/**
 * 台帳へ1件足す。
 *
 * **必ず読んでから書く。** IDの採番に既存の一覧が要るのに加えて、
 * `SettingsStore` の外部変更の照合は「読み込み時のハッシュ」を土台にする。
 * 読まずに書くと、その照合が働かない状態で保存することになる。
 *
 * **「読んで、採番して、書く」を作品ごとに1件ずつ行う**（`enqueue`）。
 * 並行に走らせると、2件が同時に `loadAll` を通って**同じIDが2つできる**。
 * 提案パネルで「登録」を続けて押すと、実際にそうなる。
 *
 * @returns 保存した伏線（採番されたIDと保存時刻が入っている）
 */
export function addForeshadow(
  work: WorkEntry,
  draft: ForeshadowDraft
): Promise<Foreshadow> {
  return enqueue(work, async () => {
    const store = createForeshadowStore(work);
    const loaded = await store.loadAll();

    // **読めないファイルがあっても止めない。** 1件壊れているだけで
    // 新しい伏線を足せなくなるより、採番を既読のぶんから続けるほうがよい
    // （IDが重なれば読み込みのときに重複として気づける）
    const now = new Date().toISOString();
    const record: Foreshadow = {
      ...emptyForeshadow(nextForeshadowId(loaded.records), draft.label),
      note: draft.note ?? "",
      plantedChapter: draft.plantedChapter ?? null,
      plantedQuote: draft.plantedQuote ?? "",
      source: draft.source,
      // 作者が手で入れたものは「AIが作った」ではない
      autoGenerated: draft.autoGenerated ?? false,
      createdAt: now,
      updatedAt: now,
    };

    await store.saveAll([record]);
    return record;
  });
}

/** 状態を変えるときに、呼び出し側が決められるところ */
export interface ForeshadowStatusChange {
  status: ForeshadowStatus;
  /** 回収した話数。読めなければ null（**推測で埋めない**） */
  resolvedChapter?: number | null;
  /** 回収箇所の逐語引用。本文と照合済みのものだけを渡す */
  resolvedQuote?: string;
}

/**
 * 既にある伏線の状態を書き換える。
 *
 * 読み込んだレコードを `SettingsStore` へ戻す形で保存する。`SettingsStore`
 * は**読み込み時のハッシュ照合**（外で書き換えられていれば止める）を行った
 * うえで、一時ファイル経由で正規の場所へ**置き換える**（`atomicWriteFile` の
 * 指定なしの経路）。**回復先への退避はしない**——退避→新規作成をしているのは
 * 人物（`CharacterStore.saveOrUpdate`）と本文（`writeTextFilePreservingFormat`）
 * だけである（CLAUDE.md 規則2）。**ここで `atomicWriteFile` を直に呼ばないこと**
 * （ハッシュ照合を通らない）。
 *
 * **必ず読んでから書く。** `SettingsStore` の外部変更の照合は
 * 「読み込み時のハッシュ」を土台にしており、読まずに書くとその照合が
 * 働かない状態で保存することになる（`addForeshadow` と同じ理由）。
 * まとめて何件も変えるときも、1件ずつこの口を通す。
 *
 * **作者メモ（`authorNotes`）と、張った側の記録には触らない。**
 * 変えるのは状態と、回収の話数・引用だけである。
 *
 * **足すほうと同じ列に並べる**（`enqueue`）。読み込みハッシュの照合を
 * 通す以上、こちらも「読んでから書く」なので、並行に走れば
 * 「外で書き換えられた」と誤って判定される。
 *
 * @returns 保存した伏線
 */
export function saveOrUpdateForeshadow(
  work: WorkEntry,
  id: string,
  change: ForeshadowStatusChange
): Promise<Foreshadow> {
  return enqueue(work, async () => {
    const store = createForeshadowStore(work);
    const loaded = await store.loadAll();
    const current = loaded.records.find((record) => record.id === id);
    if (!current) {
      // 読めなかったファイルの中にいる可能性がある。**作り直さない**
      throw new Error(
        `伏線「${id}」が見つかりません。伏線の一覧を開いて確かめてください。`
      );
    }

    const resolved = change.status === "resolved";
    const record: Foreshadow = {
      ...current,
      status: change.status,
      // **回収済みでないものに、回収の記録を残さない。** 一覧は状態を見て
      // 出し分けるので、食い違ったままだと「いつの回収か」が分からなくなる
      resolvedChapter: resolved ? (change.resolvedChapter ?? null) : null,
      resolvedQuote: resolved ? (change.resolvedQuote ?? "") : "",
      // createdAt は書き換えない（いつ気づいた伏線かが残る）。
      // updatedAt は保存時に `SettingsStore` が入れ直す
      updatedAt: current.updatedAt,
    };

    await store.saveAll([record]);
    return record;
  });
}
