/**
 * 拡張機能の外で直された設定資料を、AIに上書きさせないようにする。
 *
 * **決まったこと（2026-08-19、作者の判断）**
 *
 * - **編集部の書いた記述は、作者の記述と同じように守る**
 * - **AIの抽出が編集部の記述と食い違ったら、編集部を優先する**
 *
 * **守る仕組みは既にある。** マージは `autoGenerated` が `false` の
 * レコードをAIで書き換えない（登場話数の追記だけ行う）。この判定は
 * **誰が書いたかを見ていない**ので、編集部の記述も作者の記述と同じように
 * 守られる。決まったことの半分は、もともとそう動いている。
 *
 * **抜けているのはここである。** 編集部がAI生成のまま（`autoGenerated: true`）の
 * レコードを直した場合、印が付いていないので次の抽出で上書きされる。
 * 編集部はGitHub経由で直すので、拡張機能の「書き換え」画面を通らない。
 *
 * そこで、**外部で変わったレコードに「人が確定させた」印を付ける。**
 * 印さえ付けば、あとは既存の仕組みがそのまま効く。
 *
 * **黙って付けない。** 付けるのは作者が選んだときだけである。
 * 別のプラグインのAI（Copilot・Claude Code など）が書いた場合も同じ経路を
 * 通るので、機械が勝手に決めると「AIの書いたものをAIから守る」ことになる。
 *
 * VS Code APIに依存しない。
 */

/** 印を付けられるレコードの最小の形 */
export interface ProtectableRecord {
  name: string;
  autoGenerated: boolean;
}

export interface ProtectResult<T extends ProtectableRecord> {
  /** 印を付けたもの */
  protectedRecords: T[];
  /** もともと印が付いていたもの（触っていない） */
  alreadyProtected: T[];
}

/**
 * 印を付ける。
 *
 * **もともと `false` のものには触らない。** 触らないことが分かるように
 * 分けて返す。作者への報告で「10件のうち3件を守りました」と言えると、
 * 何が起きたのかが伝わる。
 */
export function protectRecords<T extends ProtectableRecord>(
  records: T[]
): ProtectResult<T> {
  const protectedRecords: T[] = [];
  const alreadyProtected: T[] = [];

  for (const record of records) {
    if (record.autoGenerated) {
      record.autoGenerated = false;
      protectedRecords.push(record);
    } else {
      alreadyProtected.push(record);
    }
  }
  return { protectedRecords, alreadyProtected };
}

/** 作者への報告文。何件を守り、何件はもともと守られていたか */
export function describeProtectResult<T extends ProtectableRecord>(
  result: ProtectResult<T>
): string {
  const { protectedRecords, alreadyProtected } = result;
  if (protectedRecords.length === 0 && alreadyProtected.length === 0) {
    return "守る対象がありませんでした。";
  }
  if (protectedRecords.length === 0) {
    return `${alreadyProtected.length}件は、もともとAIで上書きされない設定でした。`;
  }

  const names = protectedRecords
    .slice(0, 5)
    .map((record) => record.name)
    .join("、");
  const rest =
    protectedRecords.length > 5 ? ` ほか${protectedRecords.length - 5}件` : "";
  const head =
    `${protectedRecords.length}件を、今後AIで上書きしないようにしました` +
    `（${names}${rest}）。`;
  return alreadyProtected.length > 0
    ? `${head} ${alreadyProtected.length}件はもともとその設定でした。`
    : head;
}
