import { DEFAULT_SETTINGS_DIR } from "../models/types";
import { detectJsonFileFormat, formatJsonForFile } from "./jsonFileFormat";

/**
 * 設定資料のJSONが両方で書き換えられたとき、どちらを残すかを決める（設計書5.5.18）。
 *
 * 作者の指示（2026-09-10）：「設定資料ファイルは作者が書き換えた部分が
 * 変わっていなければ、時系列的に新しいほうに自動で合わせてください」。
 *
 * ## なぜ機械が決めてよいのか
 *
 * 5.5.4は「どちらが正しいかを機械が決めない」としていた。**安全側だが、
 * 行き止まりだった**——作者本人が「技術者しか解決できない難易度」と判断した。
 *
 * 決めてよい根拠は、**設定資料の大半がAIの抽出結果である**ことにある。
 * 抽出は同じ本文から何度でもやり直せるので、片側を残しても失われるのは
 * 「もう一度抽出すれば戻るもの」だけである。**失われては困るのは作者が
 * 手で書いた部分**（`authorNotes`・`exportNote`・呼称の固定など）なので、
 * **そこが両側で同じなら、新しいほうへ揃えてよい。**
 *
 * ## 決めないもの
 *
 * 作者が書いた部分が両側で違うときは決めない。ここを緩めると、作者が手で
 * 書いた値をもう一方の端末の読みが押し流す（CLAUDE.md「作者が書いたデータを
 * 上書きしない」）。**決めなかったものは、作者に1件ずつ選んでもらう。**
 *
 * ここは純粋関数だけを置く（vscodeにもgitにもファイルにも触らない）。
 * 版を取り出すのは `features/resolveDivergence.ts` の役目である。
 */

/**
 * 保存のたびに必ず変わる項目と、追記しかされない項目。
 *
 * **「作者が書いた部分」から外す。** 外さないと、`autoGenerated: false` の
 * レコードは保存時刻が違うだけで「作者が両方で書き換えた」ことになり、
 * すべてが作者への問いになる。登場話数（`appearedChapters`）は抽出が
 * 追記するだけの配列で、`autoGenerated: false` のレコードでもAIが触ってよい
 * 唯一の項目である（CLAUDE.md）。
 */
const VOLATILE_KEYS = ["updatedAt", "appearedChapters"] as const;

/**
 * 種別を問わず、作者が手で書く項目（models/character.ts ほか全種別が持つ）。
 *
 * 伏線の回収予定（`plannedResolveChapter`）は**作者だけが書く**（models/foreshadow.ts）。
 * AIが見つけた伏線（`source: "ai"`）でも、そこだけは作者の手である（2026-10-01）
 */
const AUTHOR_KEYS = [
  "authorNotes",
  "exportNote",
  "autoGenerated",
  "plannedResolveChapter",
] as const;

/** 人物だけが持つ、作者の判断の記録（設計書6.5.8・6.18。退けた関係は2026-09-23〜、落とした値は09-26〜） */
const CHARACTER_AUTHOR_KEYS = [
  "distinctFrom",
  "changes",
  "rejectedRelations",
  // 誤りとして落とした値（2026-09-26 深夜）。作者の操作でしか増えない
  "rejectedValues",
] as const;

/** 片側をそのまま残す決め方 */
export type SettingsSideDecision = { side: "ours" | "theirs"; reason: string };

export type SettingsConflictDecision =
  | SettingsSideDecision
  /**
   * 両側の変更を項目ごとに合わせた中身（2026-10-01 案3）。`text` は
   * この端末の側の改行の形で組んである。書き戻すのは呼び出し側
   */
  | { side: "merged"; text: string; reason: string }
  | { side: "conflict"; reason: string };

/**
 * 設定資料のJSONか（gitが返すリポジトリ相対パス）。
 *
 * **`設定/` の下にある `.json` だけを見る。** 置き場の名前は作品ごとに
 * 変えられるが（`settingsDir`）、gitのパスからは作品の設定を引けない。
 * 既定の名前に当たらないものは規則の対象にせず、作者へ回す——
 * **決められないものを決めたことにしないほうが安全である。**
 */
export function isSettingsJsonPath(filePath: string): boolean {
  // Windowsの区切り（\）を / に揃える。符号で書くのは、正規表現の中の
  // 円記号が読みにくいためである
  const normalized = filePath.replace(/[\u005C]/g, "/");
  if (!normalized.toLowerCase().endsWith(".json")) return false;

  const segments = normalized.split("/");
  // 拡張機能の作業場所は設定資料ではない（`externalChanges.ts` と同じ線引き）
  if (segments.includes(".aiwriter")) return false;
  if (segments.includes(".novelai-recovery")) return false;
  // AI向けのスキーマは生成物。書き換えても次の生成で消える
  if (segments.includes("_schema")) return false;

  return segments.includes(DEFAULT_SETTINGS_DIR);
}

/**
 * どちらを残すか決める。
 *
 * @param input `base` は共通の祖先（`git show :1:path`）。無いこともある
 *   （両方で新しく作られたレコードなど）。あるときは、両側が祖先から
 *   変えた項目を見比べて、重ならない変更を両方とも残す（案3、2026-10-01）
 *
 * ## 案3（作者の裁定、2026-10-01）
 *
 * > 設定資料については、デスクトップなどで作成したものを引き継いでいるものと
 * > 考えます。であれば、設定資料作成日が同じであれば何も出さず、衝突した時だけ
 * > 最新優先か聞く、作者が書き換えた項目は更新しないで良さそう
 *
 * - **作成の印**：`createdAt`（伏線・予定・AIメモが持つ）。両側にあって違えば
 *   別々に作った資料なので訊く。持たない資料（人物・場所など）は、
 *   **共通の祖先に同じファイルがあること**を引き継ぎの印にする
 * - **重ならない変更**：片側だけが変えた項目はその側を採る。訊かない
 * - **同じ項目が両側で違う値に変わった**：作者の項目なら訊く。AIの読みどうしなら、
 *   これまでの規則1と同じく新しいほうを採る（AIの読みは抽出し直せば戻る）
 * - **作者が確定させた側**（`autoGenerated: false`・作者が入れた伏線）の値は、
 *   確定していない側（AIの読み）の値で書き換えない。登場話数の追記だけは入れる
 */
export function decideSettingsConflict(input: {
  base?: string;
  ours: string;
  theirs: string;
}): SettingsConflictDecision {
  const ours = parseRecord(input.ours);
  const theirs = parseRecord(input.theirs);
  if (!ours || !theirs) {
    // **壊れたJSONを勝手に直さない**（CLAUDE.md）。読めないものは作者へ回す
    return {
      side: "conflict",
      reason: "JSONとして読めないため、どちらを残すか決められません",
    };
  }

  // 作成の印が違えば、**同じ名前の別の資料**である（案3、2026-10-01）。
  // 項目ごとに混ぜると、別々に作った2つの資料が1つに溶ける
  const oursMade = creationMark(ours);
  const theirsMade = creationMark(theirs);
  if (oursMade !== undefined && theirsMade !== undefined && oursMade !== theirsMade) {
    return {
      side: "conflict",
      reason: "作成日が違うため、別々に作った同じ名前の資料として扱います",
    };
  }

  const base = input.base === undefined ? undefined : parseRecord(input.base);

  // **共通の祖先がある＝同じ資料を引き継いでいる**（案3）。両側が祖先から
  // 何を変えたかを項目ごとに見て、重ならない変更は両方とも残す
  if (base) {
    const merged = mergeFields(base, ours, theirs);
    if (merged.kind === "conflict") {
      return {
        side: "conflict",
        reason: `作者が書いた部分が両方で違います（${merged.keys.join("・")}）`,
      };
    }
    if (sameValue(merged.value, ours)) {
      return {
        side: "ours",
        reason: "両方の変更を項目ごとに合わせると、この端末の側と同じになります",
      };
    }
    if (sameValue(merged.value, theirs)) {
      return {
        side: "theirs",
        reason: "両方の変更を項目ごとに合わせると、別の環境の側と同じになります",
      };
    }
    return {
      side: "merged",
      text: formatJsonForFile(
        merged.value,
        detectJsonFileFormat(new TextEncoder().encode(input.ours))
      ),
      reason: "変えた項目が重ならないので、両方の変更を合わせました",
    };
  }

  // ここから下は**共通の祖先が無い**（両方で別々に作った、または祖先の版が
  // 読めなかった）とき。何がどちらで変わったかを言えないので、作者が書いた
  // 部分を両側で突き合わせるだけにする（0.44.x からの規則）。
  // 旧「規則2（動いたのが片側だけなら動いたほうを残す）」は、祖先があるときの
  // 項目ごとの合わせ方（`mergeFields`）に含まれた
  const oursAuthor = authorParts(ours);
  const theirsAuthor = authorParts(theirs);

  // 規則1：作者が書いた部分が同じなら、時系列で新しいほうへ揃える
  if (sameValue(oursAuthor, theirsAuthor)) {
    return byUpdatedAt(ours, theirs);
  }

  // 規則3：作者が書いた部分が両側で違う。**機械は決めない**
  return {
    side: "conflict",
    reason: "作者が書いた部分が両方で違います",
  };
}

/**
 * 中身を見比べずに、**更新時刻の新しいほう**を採る。
 *
 * `decideSettingsConflict` は作者が書いた部分を突き合わせてから決めるので、
 * そこが両側で違うと「決めない」に落ちる。**それが正しい既定である**が、
 * 13作品ぶんの分岐が来ると1件ずつの見比べから抜けられない
 * （作者の実測、2026-09-11）。こちらは作者が画面で
 * 「全部、新しいほうを採る」と決めたときだけ通る道であり、
 * **決めるのは機械ではなく作者である。**
 *
 * 読めないJSONでもここでは止めない。押した作者の意図は「まとめて片づける」
 * なので、**書き換えずにこの端末の側を残す**——`decideSettingsConflict` が
 * 作者へ回すのとは、置かれている場面が違う。
 */
export function decideByUpdatedAt(
  ours: string,
  theirs: string
): SettingsSideDecision {
  const oursRecord = parseRecord(ours);
  const theirsRecord = parseRecord(theirs);
  if (!oursRecord || !theirsRecord) {
    return {
      side: "ours",
      reason: "JSONとして読めないため、この端末の側を残しました",
    };
  }
  return byUpdatedAt(oursRecord, theirsRecord);
}

/** 更新時刻の新しいほう。取れないときは、この端末の側を残す */
function byUpdatedAt(
  ours: Record<string, unknown>,
  theirs: Record<string, unknown>
): SettingsSideDecision {
  const oursAt = timeOf(ours.updatedAt);
  const theirsAt = timeOf(theirs.updatedAt);

  if (oursAt !== undefined && theirsAt !== undefined && oursAt !== theirsAt) {
    return oursAt > theirsAt
      ? {
          side: "ours",
          reason: "作者が書いた部分は同じで、この端末の側が新しいためです",
        }
      : {
          side: "theirs",
          reason: "作者が書いた部分は同じで、別の環境の側が新しいためです",
        };
  }

  // 時刻が無い・同じなら順序を決められない。**中身はどちらもAIの抽出結果**
  // なので、取り込んだ側で上書きするより、いま画面に出ているものを残す
  return {
    side: "ours",
    reason:
      "作者が書いた部分は同じで、更新時刻では新しいほうを決められないため、" +
      "この端末の側を残しました",
  };
}

/**
 * 作成の印（案3、2026-10-01）。`createdAt` が文字列で空でなければそれを使う。
 *
 * **人物・場所・組織などは `createdAt` を持たない。** そのときは undefined を返し、
 * 呼び出し側は「共通の祖先に同じファイルがあるか」で引き継ぎを判断する。
 */
function creationMark(record: Record<string, unknown>): string | undefined {
  const value = record.createdAt;
  return typeof value === "string" && value.trim() !== "" ? value : undefined;
}

/**
 * レコード全体が作者のものか。`authorParts` と同じ線引き。
 *
 * - `autoGenerated: false`（作者が確定させた）
 * - `source: "author"`（作者が入れた伏線）
 * - 1件1ファイルでない台帳（`id` を持たない。作者が直に書く場所）
 */
function isAuthorOwned(record: Record<string, unknown>): boolean {
  return (
    record.autoGenerated === false ||
    record.source === "author" ||
    typeof record.id !== "string"
  );
}

/** 名前で決まる、作者が手で書く項目 */
const AUTHOR_KEY_SET: ReadonlySet<string> = new Set<string>([
  ...AUTHOR_KEYS,
  ...CHARACTER_AUTHOR_KEYS,
]);

/** 項目ごとに合わせた結果 */
type FieldMerge =
  | { kind: "merged"; value: Record<string, unknown> }
  /** 作者の項目が両側で違う値に変わった。`keys` は項目名（作者への説明に使う） */
  | { kind: "conflict"; keys: string[] };

/**
 * 共通の祖先から、両側がそれぞれ何を変えたかを**項目ごとに**見て合わせる
 * （案3、2026-10-01）。**純粋関数。**
 *
 * gitは行で混ぜるので、JSONでは隣り合う行（`authorNotes` と `updatedAt` など）を
 * 両側で変えただけで衝突になる。保存のたびに `updatedAt` が変わるので、
 * **同じ資料を両方で開いて保存すれば、ほぼ必ず衝突していた。**
 * 項目の単位で見れば、本当にぶつかったものだけが残る。
 *
 * 1項目ずつの決め方：
 *
 * 1. 両側が同じ値 → その値
 * 2. 片側だけが祖先から変えた → 変えた側。**ただし**、相手が作者の確定した
 *    レコードで、こちらが確定していない（AIの読み）なら、確定した側の値を残す
 *    （作者の項目を名前で持つもの・呼称の固定は除く——それは作者の手である）
 * 3. 両側が違う値に変えた
 *    - 作者の項目（名前で決まるもの）→ 衝突
 *    - 片側だけが確定したレコード → 確定した側
 *    - 両側とも確定したレコード → 衝突
 *    - 呼称（`addressTerms`）→ 固定した呼称の違いで決める
 *    - AIの読みどうし → 更新時刻の新しいほう（これまでの規則1と同じ）
 *
 * 更新時刻は新しいほう、登場話数は両側の和（抽出が追記するだけの配列）にする。
 */
function mergeFields(
  base: Record<string, unknown>,
  ours: Record<string, unknown>,
  theirs: Record<string, unknown>
): FieldMerge {
  const ownedOurs = isAuthorOwned(ours);
  const ownedTheirs = isAuthorOwned(theirs);
  const newerIsTheirs = isTheirsNewer(ours, theirs);

  // 並びはこの端末の側に合わせる（差分を最小にする）。向こうにしか無い項目は後ろへ
  const keys = [
    ...Object.keys(ours),
    ...Object.keys(theirs).filter((key) => !(key in ours)),
    // 両側で消した項目は拾わない（祖先にしか無いものは、消えたままでよい）
  ];

  const value: Record<string, unknown> = {};
  const conflicts: string[] = [];

  for (const key of keys) {
    const o = ours[key];
    const t = theirs[key];
    const b = base[key];

    if (key === "updatedAt") {
      value[key] = newerIsTheirs ? t ?? o : o ?? t;
      continue;
    }
    if (key === "appearedChapters") {
      value[key] = unionChapters(b, o, t);
      continue;
    }

    const picked = pickField(key, { b, o, t }, {
      ownedOurs,
      ownedTheirs,
      newerIsTheirs,
    });
    if (picked.kind === "conflict") {
      conflicts.push(key);
      continue;
    }
    // 片側で項目ごと消したものは、消えたままにする
    if (picked.value !== undefined) value[key] = picked.value;
  }

  return conflicts.length > 0
    ? { kind: "conflict", keys: conflicts }
    : { kind: "merged", value };
}

/** 1項目の決め方（`mergeFields` の説明の 1〜3） */
function pickField(
  key: string,
  values: { b: unknown; o: unknown; t: unknown },
  sides: { ownedOurs: boolean; ownedTheirs: boolean; newerIsTheirs: boolean }
): { kind: "value"; value: unknown } | { kind: "conflict" } {
  const { b, o, t } = values;
  const { ownedOurs, ownedTheirs, newerIsTheirs } = sides;
  if (sameValue(o, t)) return { kind: "value", value: o };

  const oursMoved = !sameValue(b, o);
  const theirsMoved = !sameValue(b, t);
  const authorKey = AUTHOR_KEY_SET.has(key);
  const lockedMoved = (side: unknown) =>
    key === "addressTerms" &&
    !sameValue(lockedAddressTerms(b), lockedAddressTerms(side));

  if (oursMoved && !theirsMoved) {
    // こちらだけが変えた。ただし**こちらがAIの読みで、向こうが確定した
    // レコード**なら、向こう（作者の値）を残す。作者の項目と呼称の固定は
    // それ自体が作者の手なので、そのまま採る
    if (ownedTheirs && !ownedOurs && !authorKey && !lockedMoved(o)) {
      return { kind: "value", value: t };
    }
    return { kind: "value", value: o };
  }
  if (theirsMoved && !oursMoved) {
    if (ownedOurs && !ownedTheirs && !authorKey && !lockedMoved(t)) {
      return { kind: "value", value: o };
    }
    return { kind: "value", value: t };
  }

  // 両側が違う値に変えた
  if (authorKey) return { kind: "conflict" };
  if (ownedOurs !== ownedTheirs) {
    // 作者の手は片側だけ。**作者の値を残す**（相手はAIの読み）
    return { kind: "value", value: ownedOurs ? o : t };
  }
  if (ownedOurs && ownedTheirs) return { kind: "conflict" };

  if (key === "addressTerms") {
    const lockedBase = lockedAddressTerms(b);
    const lockedOurs = lockedAddressTerms(o);
    const lockedTheirs = lockedAddressTerms(t);
    if (!sameValue(lockedOurs, lockedTheirs)) {
      // 固定した呼称を変えたのが片側だけなら、その側を採る
      if (sameValue(lockedBase, lockedOurs)) return { kind: "value", value: t };
      if (sameValue(lockedBase, lockedTheirs)) return { kind: "value", value: o };
      return { kind: "conflict" };
    }
  }

  // AIの読みどうし。**抽出し直せば戻る**ので、新しいほうを採る（規則1と同じ）
  return { kind: "value", value: newerIsTheirs ? t : o };
}

/** 向こうの更新時刻のほうが新しいか。決められなければ false（この端末の側） */
function isTheirsNewer(
  ours: Record<string, unknown>,
  theirs: Record<string, unknown>
): boolean {
  const oursAt = timeOf(ours.updatedAt);
  const theirsAt = timeOf(theirs.updatedAt);
  return oursAt !== undefined && theirsAt !== undefined && theirsAt > oursAt;
}

/**
 * 登場話数を合わせる。**抽出が追記するだけの配列**なので、両側の和にする。
 * 片側だけが変えたならその側をそのまま使う（並びも含めて動かさない）。
 */
function unionChapters(b: unknown, o: unknown, t: unknown): unknown {
  if (sameValue(o, t)) return o;
  if (sameValue(b, o)) return t;
  if (sameValue(b, t)) return o;
  if (!Array.isArray(o) || !Array.isArray(t)) return o ?? t;
  const seen = new Set<string>();
  const out: unknown[] = [];
  for (const item of [...o, ...t]) {
    const key = stableText(item);
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(item);
  }
  // 話数だけなら小さい順に並べる（保存のときと同じ形）
  if (out.every((item) => typeof item === "number")) {
    (out as number[]).sort((left, right) => left - right);
  }
  return out;
}

/**
 * 「作者が書いた部分」を取り出す。
 *
 * ここが**この規則のすべて**である。広く取りすぎるとAIの抽出結果の違いまで
 * 作者への問いになり（前の設計がそうだった）、狭く取りすぎると作者の手が
 * 消える。**AIが触らないと約束している範囲**を、そのまま境界にする。
 */
function authorParts(record: Record<string, unknown>): unknown {
  // 作者が確定させたレコードは、登場話数の追記以外AIが触らない（CLAUDE.md）。
  // つまり**それ以外の違いは、すべて作者の手による**
  if (record.autoGenerated === false) return withoutVolatile(record);
  // 伏線は出どころを持つ。作者が入れたものは全体が作者のもの（設計書6.35.1）
  if (record.source === "author") return withoutVolatile(record);

  // 1件1ファイルのレコードでないもの（`custom_fields.json`・`keep_words.json`・
  // `ability_system.json` のような台帳）は、**作者が直に書く場所**である。
  // 形を決め打ちできないので、更新時刻を除いた全体を作者のものとみなす
  if (typeof record.id !== "string") return withoutVolatile(record);

  const parts: Record<string, unknown> = {};
  for (const key of AUTHOR_KEYS) parts[key] = record[key] ?? null;
  for (const key of CHARACTER_AUTHOR_KEYS) parts[key] = record[key] ?? null;
  // 作者が固定した呼称は変えない（CLAUDE.md）。固定していないものは
  // 抽出のたびに増えるので、ここでは見ない
  parts.lockedAddressTerms = lockedAddressTerms(record.addressTerms);
  return parts;
}

/** 保存のたびに変わる項目・追記されるだけの項目を落とす */
function withoutVolatile(record: Record<string, unknown>): unknown {
  const rest: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(record)) {
    if ((VOLATILE_KEYS as readonly string[]).includes(key)) continue;
    rest[key] = value;
  }
  return rest;
}

/** `authorLocked: true` の呼称だけを、順序に依存しない形で取り出す */
function lockedAddressTerms(value: unknown): unknown {
  if (!Array.isArray(value)) return null;
  const locked = value.filter(
    (entry): entry is Record<string, unknown> =>
      typeof entry === "object" &&
      entry !== null &&
      (entry as Record<string, unknown>).authorLocked === true
  );
  // 並び順は抽出のたびに変わりうる。**順序の違いを作者の手と読まない**
  return locked.map((entry) => stableText(entry)).sort();
}

function parseRecord(text: string): Record<string, unknown> | undefined {
  try {
    const value: unknown = JSON.parse(text);
    if (typeof value !== "object" || value === null || Array.isArray(value)) {
      return undefined;
    }
    return value as Record<string, unknown>;
  } catch {
    return undefined;
  }
}

/** 更新時刻を比べられる数にする。読めなければ undefined */
function timeOf(value: unknown): number | undefined {
  if (typeof value !== "string" || value.trim() === "") return undefined;
  const at = Date.parse(value);
  return Number.isNaN(at) ? undefined : at;
}

/** 中身が同じか。**項目の並び順の違いを、値の違いと読まない** */
function sameValue(left: unknown, right: unknown): boolean {
  return stableText(left) === stableText(right);
}

/** 項目名で並べ直したJSON。比較のためだけに使う */
function stableText(value: unknown): string {
  return JSON.stringify(value, (_key, inner: unknown) => {
    if (
      typeof inner !== "object" ||
      inner === null ||
      Array.isArray(inner)
    ) {
      return inner;
    }
    const sorted: Record<string, unknown> = {};
    for (const key of Object.keys(inner as Record<string, unknown>).sort()) {
      sorted[key] = (inner as Record<string, unknown>)[key];
    }
    return sorted;
  });
}
