import { SUMMARY_MAX_CHARS } from "./summaryLimit";

/**
 * 設定資料の構造を、他のツールやAIが読める形で書き出す。
 *
 * 作者は別のプラグインのAI（Copilot・Claude Code など）に
 * 設定資料の更新を頼むことがある。相手は `設定/` のJSONを直接読み書きできるが、
 * **構造を知らなければ推測で書き、こちらの検証で弾かれる。**
 *
 * そこで機械可読なJSON Schemaと、日本語の注意書きを置く。
 * 注意書きのほうが重要で、「作者メモは書き換えない」のような約束は
 * スキーマでは表せない。
 *
 * **型定義とずれないよう、テストで突き合わせている**
 * （`test/unit/settingsSchema.test.ts`）。モデルに項目を足して
 * ここを忘れると、テストが項目名を名指しで落とす。
 * 抽出側で同じ取りこぼしを2度やっているので、同じ形で守る。
 */

export const SCHEMA_DIR = "_schema";

export interface GeneratedSchemaFile {
  fileName: string;
  content: string;
}

/** 全レコードに共通する項目。1件ずつ書くと必ずどれかを書き忘れる */
function commonProperties(idPattern: string): Record<string, unknown> {
  return {
    schemaVersion: { type: "string" },
    id: {
      type: "string",
      pattern: idPattern,
      description: "ファイル名の先頭と一致させること。変更しないこと",
    },
    name: { type: "string", minLength: 1 },
    aliases: {
      type: "array",
      items: { type: "string" },
      description: "別の呼び方。本文に出てくる表記のまま",
    },
    reading: {
      type: ["string", "null"],
      description: "読み仮名。ひらがな。IME辞書の書き出しに使う",
    },
    summary: {
      type: ["string", "null"],
      maxLength: SUMMARY_MAX_CHARS,
      description: `一覧に出す短い紹介。${SUMMARY_MAX_CHARS}字以内`,
    },
    appearedChapters: {
      type: "array",
      items: { type: "integer", minimum: 0 },
      description: "登場する話数。本文から機械的に求まるので手で書かない",
    },
    status: { type: "string", enum: ["登場済み", "未登場"] },
    spoilerLevel: {
      type: "string",
      enum: ["public", "staff_only", "author_only"],
      description: "設定資料の書き出しで、どこまで出してよいか",
    },
    evidence: {
      type: ["string", "null"],
      description: "抽出の根拠。本文からの逐語引用",
    },
    authorNotes: {
      type: "string",
      description:
        "**作者のメモ。AIは絶対に書き換えないこと。** 消したら取り返しがつかない",
    },
    exportNote: {
      type: "string",
      description: "**作者が書く資料用の補足。AIは書き換えないこと**",
    },
    autoGenerated: {
      type: "boolean",
      description:
        "false は作者が確定させた記録。**false のレコードは登場話数以外を変更しないこと**",
    },
    conflicts: {
      type: "array",
      description: "設定と本文の食い違い。作者の判断待ちなので勝手に消さない",
      items: {
        type: "object",
        properties: {
          field: { type: "string" },
          values: { type: "array", items: { type: "string" } },
          chapters: { type: "array", items: { type: "integer" } },
          note: { type: ["string", "null"] },
        },
        required: ["field"],
      },
    },
    aiNotes: {
      type: "array",
      description: "AIとの相談で作者が承認したメモ。既存の項目とは別に持つ",
      items: {
        type: "object",
        properties: {
          id: { type: "string", pattern: "^note_\\d+$" },
          createdAt: { type: "string" },
          topic: { type: "string" },
          text: { type: "string" },
          model: { type: "string" },
          source: { type: "string", enum: ["deep_dive", "chat"] },
        },
        required: ["id", "text"],
      },
    },
    updatedAt: { type: "string" },
  };
}

function schemaOf(
  title: string,
  idPattern: string,
  extra: Record<string, unknown>
): Record<string, unknown> {
  return {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title,
    type: "object",
    properties: { ...commonProperties(idPattern), ...extra },
    required: ["id", "name"],
    // 知らない項目は書かせない。書いても読み込み時に落ちるだけで、
    // 書いた側は成功したと思い込む
    additionalProperties: false,
  };
}

export function characterSchema(): Record<string, unknown> {
  return schemaOf("登場人物", "^char_\\d+$", {
    gender: {
      type: ["string", "null"],
      description:
        "性別。男女は「男性」「女性」に統一する。それ以外は本文の記載に合わせる",
    },
    affiliation: {
      type: ["string", "null"],
      description:
        "所属する組織・部署。組織そのものの設定は organizations/ に置く",
    },
    role: { type: ["string", "null"], description: "肩書き・職業・立場" },
    personality: {
      type: ["string", "null"],
      description:
        "性格。**この項目だけは本文の言動からの推論を認める。** " +
        "ただし必ず「どう振る舞ったか」を添えること",
    },
    appearance: { type: ["string", "null"] },
    physical: { type: ["object", "null"] },
    firstPerson: {
      type: "object",
      description: "一人称。場面で変わる分は variants に入れる",
      properties: {
        default: { type: ["string", "null"] },
        variants: { type: "array" },
      },
    },
    defaultSecondPerson: { type: ["string", "null"] },
    addressTerms: {
      type: "array",
      description:
        "**この人物が他の人物をどう呼ぶか。** 呼ばれ方ではなく呼び方である。" +
        "authorLocked: true の項目は変更しないこと",
    },
    relations: { type: "array" },
    abilities: { type: "array", description: "この人物が持つ能力" },
    isMob: {
      type: "boolean",
      description:
        "集団名詞・汎用役職名か。true にすると一覧の末尾へ回り、" +
        "ハイライトとIME辞書から外れる",
    },
    romaji: { type: ["string", "null"] },
    icon: { type: ["string", "null"] },
    iconSource: { type: "string", enum: ["external", "generated", "none"] },
    customFields: {
      type: "object",
      description:
        "作者が定義した追加項目の値。キーは custom_fields.json の key に対応する。" +
        "定義に無いキーを勝手に足さないこと",
      additionalProperties: { type: "string" },
    },
  });
}

export function abilitySchema(): Record<string, unknown> {
  return schemaOf("能力", "^abil_\\d+$", {
    category: { type: ["string", "null"], description: "作品側の分類語" },
    description: { type: ["string", "null"] },
    cost: { type: ["string", "null"], description: "発動に必要な代償" },
    limitation: { type: ["string", "null"], description: "使えない条件" },
    userNames: {
      type: "array",
      items: { type: "string" },
      description: "使い手の人物名",
    },
    userIds: {
      type: "array",
      items: { type: "string", pattern: "^char_\\d+$" },
      description: "使い手の人物ID。名前から解決されるので手で書かなくてよい",
    },
  });
}

export function organizationSchema(): Record<string, unknown> {
  return schemaOf("組織", "^org_\\d+$", {
    parent: {
      type: ["string", "null"],
      description: "上位の組織（「生活保護課」に対する「冒険者ギルド」）",
    },
    category: {
      type: ["string", "null"],
      description: "種別（ギルド・王国・部署など）。作品側の言い方に従う",
    },
    description: { type: ["string", "null"] },
  });
}

export function locationSchema(): Record<string, unknown> {
  return schemaOf("場所", "^loc_\\d+$", {
    region: { type: ["string", "null"], description: "上位の地域" },
    description: { type: ["string", "null"] },
  });
}

/**
 * AIへ渡す注意書き。
 *
 * スキーマでは表せない約束をここに書く。
 * 守られなかった場合はこちらの検証で弾くが、
 * **弾かれてから直すより、先に伝えるほうが早い。**
 */
export function schemaReadme(workTitle: string): string {
  return `# 設定資料の書き方（AI・外部ツール向け）

「${workTitle}」の設定資料を読み書きするための約束です。
このフォルダーは小説AI執筆補助（VS Code拡張機能）が生成しています。

## どこに何があるか

| 置き場所 | 中身 | 1件あたり |
|---|---|---|
| \`設定/characters/\` | 登場人物 | 1人1ファイル |
| \`設定/abilities/\` | 能力 | 1件1ファイル |
| \`設定/organizations/\` | 組織 | 1件1ファイル |
| \`設定/locations/\` | 場所 | 1件1ファイル |
| \`設定/custom_fields.json\` | 作者が定義した人物の追加項目 | 1ファイル |

ファイル名は \`char_001_月島灯.json\` の形式です。**先頭のIDと中身の \`id\` を必ず一致させてください。**

\`*.md\`（characters.md など）は拡張機能が生成する読み物です。**編集しても次の生成で消えます。** 直すならJSONのほうを直してください。

## 絶対に守ること

1. **\`authorNotes\` と \`exportNote\` は書き換えない。** 作者が書いた文章です。消えると取り返しがつきません。
2. **\`autoGenerated: false\` のレコードは、\`appearedChapters\` 以外を変更しない。** 作者が確定させた記録です。
3. **\`addressTerms\` の \`authorLocked: true\` の項目は変更しない。**
4. **\`conflicts\` を勝手に消さない。** 作者の判断待ちとして残しているものです。
5. **既存の記述と食い違う情報を見つけても、上書きしない。** \`conflicts\` に足して作者に判断させてください。
6. **スキーマに無い項目を足さない。** 読み込み時に落ちます。

## 書き方

- \`summary\`（紹介）は**${SUMMARY_MAX_CHARS}字以内**。超えると切り詰められます。
- \`gender\`（性別）は男女なら「**男性**」「**女性**」に揃えます。それ以外は本文の記載に合わせます。
- \`personality\`（性格）は**本文の言動からの推論を認めます**。ただし必ず「どう振る舞ったか」を添えてください。
  - 良い例：「命令口調で指示を出し、部下の反論を最後まで聞かない」
  - 悪い例：「傲慢」
- **「記述なし」「不明」を値として書かないでください。** 空にするなら \`null\` にしてください。
- \`appearedChapters\`（登場話数）は本文から機械的に求まる値です。手で書かないでください。
- \`addressTerms\` は「**この人物が他の人物をどう呼ぶか**」です。呼ばれ方ではありません。
- 同じ相手への複数の呼び方は、まとめずにすべて残してください。

## 変更したあと

拡張機能はこのフォルダーを監視しています。**外部からの変更は「承認待ち」になり、作者が内容を確認してから取り込まれます。** すぐには反映されません。

JSONとして壊れている場合は取り込まれず、作者にエラーが出ます。勝手に修復されることはありません。

## スキーマ

- \`character.schema.json\`
- \`ability.schema.json\`
- \`organization.schema.json\`
- \`location.schema.json\`

これらは拡張機能が生成しています。**手で編集しても次の生成で上書きされます。**
`;
}

/** 書き出すファイル一式 */
export function buildSchemaFiles(workTitle: string): GeneratedSchemaFile[] {
  const json = (value: unknown) => `${JSON.stringify(value, null, 2)}\n`;
  return [
    { fileName: "README.md", content: schemaReadme(workTitle) },
    { fileName: "character.schema.json", content: json(characterSchema()) },
    { fileName: "ability.schema.json", content: json(abilitySchema()) },
    {
      fileName: "organization.schema.json",
      content: json(organizationSchema()),
    },
    { fileName: "location.schema.json", content: json(locationSchema()) },
  ];
}
