import {
  emptyAbility,
  nextAbilityId,
  normalizeAbilityName,
  type Ability,
} from "../models/ability";
import {
  emptyLocation,
  nextLocationId,
  normalizeLocationName,
  type Location,
} from "../models/location";
import {
  emptyOrganization,
  nextOrganizationId,
  normalizeOrganizationName,
  type Organization,
} from "../models/organization";
import type {
  ExtractedAbility,
  ExtractedLocation,
  ExtractedOrganization,
} from "../prompts/characterExtract";
import { clampSummary } from "./summaryLimit";
import { fillReading } from "./reading";

/**
 * 能力・場所の抽出結果を既存レコードへマージする。
 *
 * 人物と同じ方針で、統合はAIではなくコードが行い、
 * 作者が書いた値は上書きしない。食い違いは conflicts に残して
 * 作者の判断を待つ。
 */

/** 同一とみなせるか判断がつかない組。自動では統合しない */
export interface SettingMergeCandidate {
  names: [string, string];
  reason: "contains";
}

export interface AbilityMergeResult {
  abilities: Ability[];
  added: string[];
  updated: string[];
  changedIds: string[];
  conflicts: Array<{ name: string; field: string; values: string[] }>;
  mergeCandidates: SettingMergeCandidate[];
}

export interface LocationMergeResult {
  locations: Location[];
  added: string[];
  updated: string[];
  changedIds: string[];
  conflicts: Array<{ name: string; field: string; values: string[] }>;
}

export interface OrganizationMergeResult {
  organizations: Organization[];
  added: string[];
  updated: string[];
  changedIds: string[];
  conflicts: Array<{ name: string; field: string; values: string[] }>;
}

export function mergeExtractedAbilities(
  existing: Ability[],
  extracted: Array<{ data: ExtractedAbility; chapters: number[] }>
): AbilityMergeResult {
  // 作者が管理している元レコードを壊さないよう複製してから触る
  const result: Ability[] = existing.map((item) => structuredClone(item));
  const added: string[] = [];
  const updated: string[] = [];
  const changedIds = new Set<string>();
  const conflicts: AbilityMergeResult["conflicts"] = [];

  for (const item of extracted) {
    const incoming = item.data;
    const name = incoming.name?.trim();
    if (!name) continue;

    const match = findByAppellation(
      result,
      [name, ...(incoming.aliases ?? [])],
      normalizeAbilityName
    );

    if (!match) {
      const created = emptyAbility(nextAbilityId(result), name);
      applyAbility(created, incoming, item.chapters, conflicts);
      result.push(created);
      added.push(created.name);
      changedIds.add(created.id);
      continue;
    }

    // 作者が確定させたレコードはAIで書き換えない。話数の追記だけ行う
    if (!match.autoGenerated) {
      const before = match.appearedChapters.length;
      match.appearedChapters = mergeChapters(
        match.appearedChapters,
        item.chapters
      );
      if (match.appearedChapters.length !== before) {
        updated.push(match.name);
        changedIds.add(match.id);
      }
      continue;
    }

    if (applyAbility(match, incoming, item.chapters, conflicts)) {
      if (!updated.includes(match.name)) updated.push(match.name);
      changedIds.add(match.id);
    }
  }

  return {
    abilities: result,
    added,
    updated,
    changedIds: [...changedIds],
    conflicts,
    mergeCandidates: findAbilityMergeCandidates(result),
  };
}

export function mergeExtractedLocations(
  existing: Location[],
  extracted: Array<{ data: ExtractedLocation; chapters: number[] }>
): LocationMergeResult {
  const result: Location[] = existing.map((item) => structuredClone(item));
  const added: string[] = [];
  const updated: string[] = [];
  const changedIds = new Set<string>();
  const conflicts: LocationMergeResult["conflicts"] = [];

  for (const item of extracted) {
    const incoming = item.data;
    const name = incoming.name?.trim();
    if (!name) continue;

    const match = findByAppellation(
      result,
      [name, ...(incoming.aliases ?? [])],
      normalizeLocationName
    );

    if (!match) {
      const created = emptyLocation(nextLocationId(result), name);
      applyLocation(created, incoming, item.chapters, conflicts);
      result.push(created);
      added.push(created.name);
      changedIds.add(created.id);
      continue;
    }

    if (!match.autoGenerated) {
      const before = match.appearedChapters.length;
      match.appearedChapters = mergeChapters(
        match.appearedChapters,
        item.chapters
      );
      if (match.appearedChapters.length !== before) {
        updated.push(match.name);
        changedIds.add(match.id);
      }
      continue;
    }

    if (applyLocation(match, incoming, item.chapters, conflicts)) {
      if (!updated.includes(match.name)) updated.push(match.name);
      changedIds.add(match.id);
    }
  }

  return {
    locations: result,
    added,
    updated,
    changedIds: [...changedIds],
    conflicts,
  };
}

export function mergeExtractedOrganizations(
  existing: Organization[],
  extracted: Array<{ data: ExtractedOrganization; chapters: number[] }>
): OrganizationMergeResult {
  const result: Organization[] = existing.map((item) => structuredClone(item));
  const added: string[] = [];
  const updated: string[] = [];
  const changedIds = new Set<string>();
  const conflicts: OrganizationMergeResult["conflicts"] = [];

  for (const item of extracted) {
    const incoming = item.data;
    const name = incoming.name?.trim();
    if (!name) continue;

    const match = findByAppellation(
      result,
      [name, ...(incoming.aliases ?? [])],
      normalizeOrganizationName
    );

    if (!match) {
      const created = emptyOrganization(nextOrganizationId(result), name);
      applyOrganization(created, incoming, item.chapters, conflicts);
      result.push(created);
      added.push(created.name);
      changedIds.add(created.id);
      continue;
    }

    // 作者が確定させたレコードはAIで書き換えない。話数の追記だけ行う
    if (!match.autoGenerated) {
      const before = match.appearedChapters.length;
      match.appearedChapters = mergeChapters(
        match.appearedChapters,
        item.chapters
      );
      if (match.appearedChapters.length !== before) {
        updated.push(match.name);
        changedIds.add(match.id);
      }
      continue;
    }

    if (applyOrganization(match, incoming, item.chapters, conflicts)) {
      if (!updated.includes(match.name)) updated.push(match.name);
      changedIds.add(match.id);
    }
  }

  return {
    organizations: result,
    added,
    updated,
    changedIds: [...changedIds],
    conflicts,
  };
}

/**
 * 人物の所属から、まだ登録されていない組織を作る。
 *
 * AIは人物の affiliation には所属名を入れるのに、組織としては出さないことがある。
 * そのままだと、資料で所属ごとにまとめているのに組織一覧が空になる。
 * **名前だけを作り、説明は入れない。** 本文に根拠のない説明を足さないため。
 */
export function organizationsFromAffiliations(
  existing: Organization[],
  affiliations: string[]
): OrganizationMergeResult {
  const result: Organization[] = existing.map((item) => structuredClone(item));
  const added: string[] = [];
  const changedIds = new Set<string>();

  for (const raw of affiliations) {
    const name = raw.trim();
    if (!name) continue;
    if (findByAppellation(result, [name], normalizeOrganizationName)) continue;

    const created = emptyOrganization(nextOrganizationId(result), name);
    result.push(created);
    added.push(created.name);
    changedIds.add(created.id);
  }

  return {
    organizations: result,
    added,
    updated: [],
    changedIds: [...changedIds],
    conflicts: [],
  };
}

function applyOrganization(
  target: Organization,
  incoming: ExtractedOrganization,
  chapters: number[],
  conflicts: OrganizationMergeResult["conflicts"]
): boolean {
  let changed = false;

  changed = mergeAliases(target, incoming.name, incoming.aliases) || changed;
  changed = fillOrConflict(target, "reading", incoming.reading, conflicts) || changed;
  // カタカナならコード側で確実に作る。漢字だけAIの推定に委ねる
  const derivedReading = fillReading(target.reading, target.name);
  if (derivedReading !== target.reading) {
    target.reading = derivedReading;
    changed = true;
  }
  changed =
    fillOrConflict(target, "summary", clampSummary(incoming.summary), conflicts) ||
    changed;
  changed = fillOrConflict(target, "parent", incoming.parent, conflicts) || changed;
  changed =
    fillOrConflict(target, "category", incoming.category, conflicts) || changed;
  changed =
    fillOrConflict(target, "description", incoming.description, conflicts) || changed;

  if (!target.evidence && incoming.evidence) {
    target.evidence = incoming.evidence;
    changed = true;
  }

  const before = target.appearedChapters.length;
  target.appearedChapters = mergeChapters(target.appearedChapters, chapters);
  if (target.appearedChapters.length !== before) changed = true;

  return changed;
}

function applyAbility(
  target: Ability,
  incoming: ExtractedAbility,
  chapters: number[],
  conflicts: AbilityMergeResult["conflicts"]
): boolean {
  let changed = false;

  changed = mergeAliases(target, incoming.name, incoming.aliases) || changed;
  changed = fillOrConflict(target, "reading", incoming.reading, conflicts) || changed;
  // カタカナならコード側で確実に作る。漢字だけAIの推定に委ねる
  const derivedReading = fillReading(target.reading, target.name);
  if (derivedReading !== target.reading) {
    target.reading = derivedReading;
    changed = true;
  }
  // 紹介文の長さはコード側で確かめる。プロンプトの指示だけでは守られない
  changed =
    fillOrConflict(target, "summary", clampSummary(incoming.summary), conflicts) ||
    changed;
  changed = fillOrConflict(target, "category", incoming.category, conflicts) || changed;
  changed =
    fillOrConflict(target, "description", incoming.description, conflicts) || changed;
  changed = fillOrConflict(target, "cost", incoming.cost, conflicts) || changed;
  changed =
    fillOrConflict(target, "limitation", incoming.limitation, conflicts) || changed;

  for (const user of incoming.userNames ?? []) {
    const trimmed = user.trim();
    if (trimmed && !target.userNames.includes(trimmed)) {
      target.userNames.push(trimmed);
      changed = true;
    }
  }

  if (!target.evidence && incoming.evidence) {
    target.evidence = incoming.evidence;
    changed = true;
  }

  const before = target.appearedChapters.length;
  target.appearedChapters = mergeChapters(target.appearedChapters, chapters);
  if (target.appearedChapters.length !== before) changed = true;

  return changed;
}

function applyLocation(
  target: Location,
  incoming: ExtractedLocation,
  chapters: number[],
  conflicts: LocationMergeResult["conflicts"]
): boolean {
  let changed = false;

  changed = mergeAliases(target, incoming.name, incoming.aliases) || changed;
  changed = fillOrConflict(target, "reading", incoming.reading, conflicts) || changed;
  // カタカナならコード側で確実に作る。漢字だけAIの推定に委ねる
  const derivedReading = fillReading(target.reading, target.name);
  if (derivedReading !== target.reading) {
    target.reading = derivedReading;
    changed = true;
  }
  changed =
    fillOrConflict(target, "summary", clampSummary(incoming.summary), conflicts) ||
    changed;
  changed = fillOrConflict(target, "region", incoming.region, conflicts) || changed;
  changed =
    fillOrConflict(target, "description", incoming.description, conflicts) || changed;

  if (!target.evidence && incoming.evidence) {
    target.evidence = incoming.evidence;
    changed = true;
  }

  const before = target.appearedChapters.length;
  target.appearedChapters = mergeChapters(target.appearedChapters, chapters);
  if (target.appearedChapters.length !== before) changed = true;

  return changed;
}

/** 別名は和集合。照合に使われた別表記も残す */
function mergeAliases(
  target: { name: string; aliases: string[] },
  incomingName: string | undefined,
  incomingAliases: string[] | undefined
): boolean {
  let changed = false;
  const aliases = new Set(target.aliases);
  const name = incomingName?.trim();
  if (name && name !== target.name && !aliases.has(name)) {
    aliases.add(name);
    changed = true;
  }
  for (const alias of incomingAliases ?? []) {
    const trimmed = alias.trim();
    if (trimmed && trimmed !== target.name && !aliases.has(trimmed)) {
      aliases.add(trimmed);
      changed = true;
    }
  }
  target.aliases = [...aliases];
  return changed;
}

/**
 * 空なら埋め、既存値と違えば conflicts に記録する。
 * 設定側と本文側のどちらが正しいかはAIには判断できないため、
 * 既存の記述を消さずに作者へ委ねる。
 */
function fillOrConflict<T extends { name: string; conflicts: Array<{
  field: string;
  values: string[];
  chapters: number[];
  note: string | null;
}> }>(
  target: T,
  field: keyof T & string,
  incoming: string | null | undefined,
  conflicts: Array<{ name: string; field: string; values: string[] }>
): boolean {
  const value = incoming?.trim();
  if (!value) return false;

  const current = target[field] as unknown as string | null;
  if (!current) {
    (target as Record<string, unknown>)[field] = value;
    return true;
  }
  if (current === value) return false;
  // 短い記述が長い記述に含まれる場合は詳細な方を採る
  if (value.includes(current)) {
    (target as Record<string, unknown>)[field] = value;
    return true;
  }
  if (current.includes(value)) return false;

  const already = target.conflicts.find((entry) => entry.field === field);
  if (already) {
    if (!already.values.includes(value)) {
      already.values.push(value);
      conflicts.push({ name: target.name, field, values: already.values });
      return true;
    }
    return false;
  }

  target.conflicts.push({
    field,
    values: [current, value],
    chapters: [],
    note: null,
  });
  conflicts.push({ name: target.name, field, values: [current, value] });
  return true;
}

function findByAppellation<T extends { name: string; aliases: string[] }>(
  list: T[],
  appellations: string[],
  normalize: (value: string) => string
): T | undefined {
  const keys = new Set(appellations.map(normalize).filter(Boolean));
  return list.find((item) =>
    [item.name, ...item.aliases]
      .map(normalize)
      .some((candidate) => keys.has(candidate))
  );
}

/**
 * 一方が他方を完全に含む能力名を候補として挙げる。
 *
 * 「聖紋神術」と「聖紋神術の同時発動」のように、
 * 使い方が独立した能力として登録されることがある（実データで確認）。
 * ただし「炎槍」と「大炎槍」のように別能力のこともあるため、
 * 自動では統合せず作者に判断を委ねる。
 */
export function findAbilityMergeCandidates(
  abilities: Ability[]
): SettingMergeCandidate[] {
  const candidates: SettingMergeCandidate[] = [];

  for (let i = 0; i < abilities.length; i++) {
    for (let j = i + 1; j < abilities.length; j++) {
      const a = abilities[i];
      const b = abilities[j];
      if (sharesAppellation(a, b)) continue;

      const found = appellationPairs(a, b).some(([shorter, longer]) =>
        isContainedName(shorter, longer)
      );
      if (found) {
        candidates.push({ names: [a.name, b.name], reason: "contains" });
      }
    }
  }
  return candidates;
}

/** shorter が longer に完全に含まれるか。短すぎる語は誤検出の元なので除く */
export function isContainedName(shorter: string, longer: string): boolean {
  if (shorter.length < 3) return false;
  if (shorter.length >= longer.length) return false;
  return longer.includes(shorter);
}

function sharesAppellation(
  a: { name: string; aliases: string[] },
  b: { name: string; aliases: string[] }
): boolean {
  const keys = new Set(
    [a.name, ...a.aliases].map(normalizeAbilityName)
  );
  return [b.name, ...b.aliases]
    .map(normalizeAbilityName)
    .some((name) => keys.has(name));
}

/** 2件の呼称の総当たりを、短い方・長い方の順で返す */
function appellationPairs(
  a: { name: string; aliases: string[] },
  b: { name: string; aliases: string[] }
): Array<[string, string]> {
  const pairs: Array<[string, string]> = [];
  for (const left of [a.name, ...a.aliases]) {
    for (const right of [b.name, ...b.aliases]) {
      pairs.push(left.length <= right.length ? [left, right] : [right, left]);
    }
  }
  return pairs;
}

function mergeChapters(existing: number[], incoming: number[]): number[] {
  const set = new Set(existing);
  for (const chapter of incoming) {
    if (Number.isSafeInteger(chapter)) set.add(chapter);
  }
  return [...set].sort((a, b) => a - b);
}
