import type { ChapterSynopsis, ChapterSynopsisSet } from "../models/synopsis";
import { stripChapterLabel } from "./episodeLabel";

/**
 * 各話あらすじを読める形にする。
 *
 * **JSONのままでは作者が読めない。** あらすじは通して読むもの
 * （前の話から筋が繋がっているかを確かめる）なので、
 * 話数順に並べた1つの文書として書き出す。
 *
 * 設定資料集（`characters.md` 等）と同じく、これは生成物である。
 * 直したいときは設定資料パネルか JSON を直す。
 */

export interface SynopsisMarkdownOptions {
  workTitle: string;
  /**
   * 見出しの深さ。既定は1（`# 作品名 各話あらすじ`）。
   *
   * 作品紹介文と同じ文書へ差し込むときは2を渡す。紹介文の下に
   * `## 各話あらすじ` があり、その中に話が並ぶため、話の見出しは
   * 1段深くしないと目次の階層が壊れる。
   */
  headingLevel?: 1 | 2;
  /** 文書の見出し（`# 作品名 各話あらすじ`）を付けるか。既定は付ける */
  includeTitle?: boolean;
}

export function buildSynopsisListMarkdown(
  set: ChapterSynopsisSet,
  options: SynopsisMarkdownOptions
): string {
  const includeTitle = options.includeTitle ?? true;
  const episodeHeading = "#".repeat((options.headingLevel ?? 1) + 1);
  const lines: string[] = includeTitle
    ? [`# ${options.workTitle} 各話あらすじ`, ""]
    : [];

  if (set.episodes.length === 0) {
    lines.push("まだあらすじがありません。", "");
    return lines.join("\n");
  }

  const totalChars = set.episodes.reduce(
    (total, episode) => total + episode.synopsis.length,
    0
  );
  lines.push(
    `全 ${set.episodes.length} 話 / あらすじ合計 ${totalChars.toLocaleString()} 字`,
    ""
  );

  for (const episode of set.episodes) {
    lines.push(`${episodeHeading} ${headingFor(episode)}`, "");
    lines.push(episode.synopsis, "");

    // 作者が書いたものは、AIが作ったものと区別が付くようにする
    if (!episode.autoGenerated) {
      lines.push("- （作者が書き直したあらすじ）");
    }
    if (episode.authorNotes.trim()) {
      lines.push(`- **メモ**: ${episode.authorNotes.trim()}`);
    }
    if (!episode.autoGenerated || episode.authorNotes.trim()) {
      lines.push("");
    }
  }

  return lines.join("\n");
}

function headingFor(episode: ChapterSynopsis): string {
  const chapter =
    episode.chapter !== null ? `第${episode.chapter}話` : episode.fileName;
  // **題にも「第1話」が入っていることがある**（投稿サイトの題がそうなっている）。
  // そのまま並べると「第1話 第1話　気がついたら幽霊」になる
  // （2026-08-19、作者が実機で発見）
  const title = stripChapterLabel(episode.title, chapter);
  return title ? `${chapter} ${title}` : chapter;
}
