import {
  synopsisKey,
  type ChapterSynopsis,
  type ChapterSynopsisSet,
} from "../models/synopsis";
import { stripChapterLabel } from "./episodeLabel";

/**
 * 各話あらすじを読める形にする。
 *
 * **JSONのままでは作者が読めない。** あらすじは通して読むもの
 * （前の話から筋が繋がっているかを確かめる）なので、
 * 話数順に並べた1つの文書として書き出す。
 *
 * 設定資料集（`characters.md` 等）と同じく、これは生成物である。
 * 直したいときは設定資料パネルか JSON を直す。
 */

/**
 * 文書へ挟む章の印1つ（設計書6.66.4の3）。
 *
 * **どのあらすじの直前に置くか**を `startKey`（`synopsisKey` の形）で持つ。
 * 話数やファイル名をここで組み立て直すと、あらすじ側の話の見分け方
 * （リネームに強い形）とずれる。印を作るのは `core/synopsisChapters.ts`。
 */
export interface SynopsisChapterMark {
  /** 章の名前（台帳のまま。ここでは飾らない） */
  name: string;
  /** この章が始まる話。`synopsisKey(fileName, chapter)` の形 */
  startKey: string;
  /** 見出しに添える範囲（「第3話〜第5話・3話」）。空なら添えない */
  range: string;
}

export interface SynopsisMarkdownOptions {
  workTitle: string;
  /**
   * 見出しの深さ。既定は1（`# 作品名 各話あらすじ`）。
   *
   * 作品紹介文と同じ文書へ差し込むときは2を渡す。紹介文の下に
   * `## 各話あらすじ` があり、その中に話が並ぶため、話の見出しは
   * 1段深くしないと目次の階層が壊れる。
   */
  headingLevel?: 1 | 2;
  /** 文書の見出し（`# 作品名 各話あらすじ`）を付けるか。既定は付ける */
  includeTitle?: boolean;
  /**
   * 挟む章の印（設計書6.66.4の3）。**空なら章の見出しは1つも出ない**
   * ——章立ての台帳を持たない作品は、いままでどおりの文書になる。
   */
  chapters?: readonly SynopsisChapterMark[];
}

export function buildSynopsisListMarkdown(
  set: ChapterSynopsisSet,
  options: SynopsisMarkdownOptions
): string {
  const includeTitle = options.includeTitle ?? true;
  const marks = options.chapters ?? [];
  const baseLevel = options.headingLevel ?? 1;
  const chapterHeading = "#".repeat(baseLevel + 1);
  // **章があるときは、話を1段深くする。** 章と話が同じ深さだと、
  // 章の下に話が入っているように読めない（目次の階層も壊れる）
  const episodeHeading = "#".repeat(baseLevel + (marks.length > 0 ? 2 : 1));
  // 章の印は「その章が始まる話」を指す。同じ話を指す印が2つあることは
  // 無い（台帳が重複を許さない）ので、最初の1つだけを覚える
  const markByKey = new Map<string, SynopsisChapterMark>();
  for (const mark of marks) {
    if (!markByKey.has(mark.startKey)) markByKey.set(mark.startKey, mark);
  }
  const lines: string[] = includeTitle
    ? [`# ${options.workTitle} 各話あらすじ`, ""]
    : [];

  if (set.episodes.length === 0) {
    lines.push("まだあらすじがありません。", "");
    return lines.join("\n");
  }

  const totalChars = set.episodes.reduce(
    (total, episode) => total + episode.synopsis.length,
    0
  );
  lines.push(
    `全 ${set.episodes.length} 話 / あらすじ合計 ${totalChars.toLocaleString()} 字`,
    ""
  );

  for (const episode of set.episodes) {
    const mark = markByKey.get(synopsisKey(episode.fileName, episode.chapter));
    if (mark) {
      lines.push(`${chapterHeading} ${chapterHeadingFor(mark)}`, "");
    }
    lines.push(`${episodeHeading} ${headingFor(episode)}`, "");
    lines.push(episode.synopsis, "");

    // 作者が書いたものは、AIが作ったものと区別が付くようにする
    if (!episode.autoGenerated) {
      lines.push("- （作者が書き直したあらすじ）");
    }
    if (episode.authorNotes.trim()) {
      lines.push(`- **メモ**: ${episode.authorNotes.trim()}`);
    }
    if (!episode.autoGenerated || episode.authorNotes.trim()) {
      lines.push("");
    }
  }

  return lines.join("\n");
}

/** 章の見出し。範囲が読めない章は、名前だけを出す（数を捏造しない） */
function chapterHeadingFor(mark: SynopsisChapterMark): string {
  return mark.range ? `${mark.name}（${mark.range}）` : mark.name;
}

function headingFor(episode: ChapterSynopsis): string {
  const chapter =
    episode.chapter !== null ? `第${episode.chapter}話` : episode.fileName;
  // **題にも「第1話」が入っていることがある**（投稿サイトの題がそうなっている）。
  // そのまま並べると「第1話 第1話　気がついたら幽霊」になる
  // （2026-08-19、作者が実機で発見）
  const title = stripChapterLabel(episode.title, chapter);
  return title ? `${chapter} ${title}` : chapter;
}
