import type { ChapterSynopsis, ChapterSynopsisSet } from "../models/synopsis";

/**
 * 各話あらすじを読める形にする。
 *
 * **JSONのままでは作者が読めない。** あらすじは通して読むもの
 * （前の話から筋が繋がっているかを確かめる）なので、
 * 話数順に並べた1つの文書として書き出す。
 *
 * 設定資料集（`characters.md` 等）と同じく、これは生成物である。
 * 直したいときは設定資料パネルか JSON を直す。
 */

export interface SynopsisMarkdownOptions {
  workTitle: string;
}

export function buildSynopsisListMarkdown(
  set: ChapterSynopsisSet,
  options: SynopsisMarkdownOptions
): string {
  const lines: string[] = [`# ${options.workTitle} 各話あらすじ`, ""];

  if (set.episodes.length === 0) {
    lines.push("まだあらすじがありません。", "");
    return lines.join("\n");
  }

  const totalChars = set.episodes.reduce(
    (total, episode) => total + episode.synopsis.length,
    0
  );
  lines.push(
    `全 ${set.episodes.length} 話 / あらすじ合計 ${totalChars.toLocaleString()} 字`,
    ""
  );

  for (const episode of set.episodes) {
    lines.push(`## ${headingFor(episode)}`, "");
    lines.push(episode.synopsis, "");

    // 作者が書いたものは、AIが作ったものと区別が付くようにする
    if (!episode.autoGenerated) {
      lines.push("- （作者が書き直したあらすじ）");
    }
    if (episode.authorNotes.trim()) {
      lines.push(`- **メモ**: ${episode.authorNotes.trim()}`);
    }
    if (!episode.autoGenerated || episode.authorNotes.trim()) {
      lines.push("");
    }
  }

  return lines.join("\n");
}

function headingFor(episode: ChapterSynopsis): string {
  const chapter =
    episode.chapter !== null ? `第${episode.chapter}話` : episode.fileName;
  return episode.title ? `${chapter} ${episode.title}` : chapter;
}
