import { describe, expect, test } from "vitest";
import {
  ChunkCacheStore,
  type ChunkCacheIo,
} from "../../../src/core/chunkCacheStore";
import type { Chunk } from "../../../src/core/chunker";
import { promptVersionWithKnownCast } from "../../../src/core/knownCharacterNames";
import {
  buildExtractionCostNotice,
  buildKnownCharacterNamesForPrompt,
  characterExtractCacheKey,
} from "../../../src/features/extractCharacters";
import { emptyCharacter, type Character } from "../../../src/models/character";
import { CHARACTER_EXTRACT_VERSION } from "../../../src/prompts/characterExtract";

/**
 * 人物が増えたら人物抽出を読み直す（作者の裁定、2026-09-24 夜）。
 *
 * 人物抽出のプロンプトには「既に分かっている人物の名前」を渡しているのに、
 * 使い回しの鍵にはそれが入っていなかった。人物が増えても・名前を直しても、
 * 前の顔ぶれで読んだ古い答えがそのまま使われていた。
 *
 * **料金がかかる変化**なので、確認画面の件数と送る量（`pending` から数える）が
 * 同じ鍵で増えることまで確かめる。鍵の組み立て（core）と見積もり（features）に
 * またがるので cross に置く。
 */

function chunkOf(index: number, text: string): Chunk {
  return {
    filePath: `c:\\novels\\work\\本文\\00${index + 1}.txt`,
    text,
    hash: `hash-${index}`,
    chapterStart: index + 1,
    chapterEnd: index + 1,
    index: 0,
    startLine: 0,
  };
}

const CHUNKS = [
  chunkOf(0, "俺は局の裏で自転車の荷台に袋を縛りつけた。"),
  chunkOf(1, "千夏が水筒を差し出してきた。"),
  chunkOf(2, "蓬田さんの家の前では、縁側の雪がきれいに掃いてあった。"),
];

/** 手元の台（相沢春人・黒瀬千夏）。抽出が作った記録として置く */
function cast(): Character[] {
  const haruto = emptyCharacter("char_001", "相沢 春人");
  haruto.aliases = ["春人"];
  const chinatsu = emptyCharacter("char_002", "黒瀬 千夏");
  chinatsu.aliases = ["千夏"];
  return [haruto, chinatsu];
}

/** 読み書きをメモリで済ませるキャッシュ（ファイルは作らない） */
function memoryCache(): ChunkCacheStore {
  let stored: Uint8Array | undefined;
  const io: ChunkCacheIo = {
    async read() {
      return stored;
    },
    async write(_file, bytes) {
      stored = bytes;
    },
    log() {},
  };
  return new ChunkCacheStore("memory/chunks.json", io);
}

/** 前回の実行：その顔ぶれで全チャンクを読み終えた状態を作る */
async function cacheReadWith(characters: Character[]): Promise<ChunkCacheStore> {
  const cache = memoryCache();
  const key = characterExtractCacheKey("claude", "claude-model", characters);
  for (const chunk of CHUNKS) {
    await cache.set(chunk.hash, key, { characters: [] });
  }
  return cache;
}

/** 実行前の「未処理のチャンク」（確認画面の件数と見積もりはここから数える） */
function pendingWith(cache: ChunkCacheStore, characters: Character[]): Chunk[] {
  const key = characterExtractCacheKey("claude", "claude-model", characters);
  return CHUNKS.filter((chunk) => !cache.get(chunk.hash, key));
}

/** 確認画面に出る入力トークンの目安 */
function inputTokensOf(notice: string): number {
  const match = notice.match(/入力: 約 ([\d,]+) トークン/);
  expect(match, notice).not.toBeNull();
  return Number(match![1].replace(/,/g, ""));
}

describe("人物抽出の使い回しの鍵に、顔ぶれを入れる", () => {
  test("顔ぶれが同じなら、読み直さない", async () => {
    const cache = await cacheReadWith(cast());
    expect(pendingWith(cache, cast())).toEqual([]);
  });

  test("作者が手で足した人物がいれば、全部読み直す", async () => {
    const cache = await cacheReadWith(cast());
    const added = [...cast(), emptyCharacter("char_003", "蓬田 吾一")];
    added[2].autoGenerated = false;

    expect(pendingWith(cache, added)).toHaveLength(CHUNKS.length);
  });

  test("名前を直した人物がいれば、全部読み直す", async () => {
    const cache = await cacheReadWith(cast());
    const renamed = cast();
    renamed[0].name = "相沢 晴人";

    expect(pendingWith(cache, renamed)).toHaveLength(CHUNKS.length);
  });

  test("別名が増えただけなら読み直さない（抽出のたびに全部読み直さない）", async () => {
    const cache = await cacheReadWith(cast());
    const moreAliases = cast();
    moreAliases[1].aliases.push("黒瀬さん");

    expect(pendingWith(cache, moreAliases)).toEqual([]);
  });

  test("保存の順が入れ替わっただけなら読み直さない", async () => {
    const cache = await cacheReadWith(cast());
    expect(pendingWith(cache, [...cast()].reverse())).toEqual([]);
  });

  test("人物がまだいない作品の鍵は、これまでと同じ（処理済みを飛ばさない）", () => {
    expect(promptVersionWithKnownCast(CHARACTER_EXTRACT_VERSION, [])).toBe(
      CHARACTER_EXTRACT_VERSION
    );
    expect(characterExtractCacheKey("ollama", "m", []).promptVersion).toBe(
      CHARACTER_EXTRACT_VERSION
    );
  });

  test("読み直すぶんが、確認画面の送る量にそのまま載る", async () => {
    const cache = await cacheReadWith(cast());
    const before = pendingWith(cache, cast());
    const grown = [...cast(), emptyCharacter("char_003", "蓬田 吾一")];
    const after = pendingWith(cache, grown);

    // 抽出の処理と同じ組み方：未処理のチャンクと、プロンプトへ渡す既知の名前
    const noticeBefore = buildExtractionCostNotice(
      "claude",
      true,
      before,
      buildKnownCharacterNamesForPrompt(cast(), []),
      4096
    );
    const noticeAfter = buildExtractionCostNotice(
      "claude",
      true,
      after,
      buildKnownCharacterNamesForPrompt(grown, []),
      4096
    );

    expect(before).toEqual([]);
    expect(inputTokensOf(noticeBefore)).toBe(0);
    expect(after).toHaveLength(CHUNKS.length);
    // 3チャンクぶんの本文・指示・増えた人物の名前が、目安に入る
    const perChunk = CHUNKS.map((chunk) =>
      inputTokensOf(
        buildExtractionCostNotice(
          "claude",
          true,
          [chunk],
          buildKnownCharacterNamesForPrompt(grown, []),
          4096
        )
      )
    );
    expect(inputTokensOf(noticeAfter)).toBe(
      perChunk.reduce((sum, tokens) => sum + tokens, 0)
    );
    expect(inputTokensOf(noticeAfter)).toBeGreaterThan(0);
  });
});
