import { describe, expect, test } from "vitest";
import {
  emptyLocation,
  parseLocation,
  type Location,
} from "../../../src/models/location";
import { mergeExtractedLocations } from "../../../src/core/settingsMerge";
import { applyLocationEdits } from "../../../src/core/settingsEdit";
import { mergePendingSettingsRecord } from "../../../src/core/pendingSettingsMerge";
import { locationSchema } from "../../../src/core/settingsSchema";

/**
 * 略図で作者が置いた位置（`sketchPosition`。設計書6.93.10）を、抽出・マージ・
 * 編集・承認待ちの反映のどの道でも書き換えない（実装ルール2）。
 *
 * **モデル・スキーマ・マージにまたがる**ので cross に置く。1か所でも
 * 落とす道があれば、作者が並べた略図が次の抽出で崩れる。
 */

const placed: Location = {
  ...emptyLocation("loc_001", "港"),
  summary: "町の南の港。",
  appearedChapters: [1],
  sketchPosition: { x: 120, y: -40 },
};

describe("記録の形", () => {
  test("動かしていない場所は、欄ごと持たない", () => {
    expect(parseLocation({ id: "loc_001", name: "港" })).not.toHaveProperty("sketchPosition");
  });

  test("置いた位置は読み書きしても1字も変わらない", () => {
    const text = `${JSON.stringify({ ...placed, updatedAt: "2026-10-10T00:00:00.000Z" }, null, 2)}\n`;
    const reread = parseLocation(JSON.parse(text));
    expect(reread.sketchPosition).toEqual({ x: 120, y: -40 });
    expect(`${JSON.stringify(reread, null, 2)}\n`).toBe(text);
  });

  test("壊れた位置は直さずに止める", () => {
    for (const broken of [
      "120,-40",
      { x: "120", y: -40 },
      { x: 120 },
      { x: 120, y: -40, z: 0 },
      null,
    ]) {
      expect(
        () => parseLocation({ id: "loc_001", name: "港", sketchPosition: broken }),
        JSON.stringify(broken)
      ).toThrow(/sketchPosition/);
    }
  });

  test("手で書くJSONの検証（スキーマ）が、置いた位置を知らない項目として落とさない", () => {
    const schema = locationSchema() as {
      additionalProperties: boolean;
      properties: Record<string, { required?: string[] }>;
    };
    expect(schema.additionalProperties).toBe(false);
    expect(schema.properties.sketchPosition?.required).toEqual(["x", "y"]);
  });
});

describe("どの道でも書き換えない", () => {
  test("抽出のマージ（自動の記録）で、置いた位置が残る", () => {
    const result = mergeExtractedLocations(
      [structuredClone(placed)],
      [
        {
          data: {
            name: "港",
            description: "船が着く",
            evidence: "港に船が着いた",
            relations: [
              { target: "灯台", kind: "adjacent", evidence: "港は灯台に隣接している" },
            ],
          },
          chapters: [3],
        },
      ]
    );
    const port = result.locations.find((location) => location.id === "loc_001");
    expect(port?.description).toBe("船が着く");
    expect(port?.sketchPosition).toEqual({ x: 120, y: -40 });
  });

  test("抽出のマージ（確定した記録）でも、置いた位置が残る", () => {
    const result = mergeExtractedLocations(
      [{ ...structuredClone(placed), autoGenerated: false }],
      [{ data: { name: "港", evidence: "港に船が着いた" }, chapters: [5] }]
    );
    expect(result.locations[0].sketchPosition).toEqual({ x: 120, y: -40 });
  });

  test("新しく抽出した場所には位置を付けない（作者が置くまで無い）", () => {
    const result = mergeExtractedLocations(
      [structuredClone(placed)],
      [{ data: { name: "灯台", evidence: "灯台が見えた" }, chapters: [2] }]
    );
    const lighthouse = result.locations.find((location) => location.name === "灯台");
    expect(lighthouse).not.toHaveProperty("sketchPosition");
  });

  test("設定資料パネルでの書き換えで、置いた位置が残る", () => {
    const edited = applyLocationEdits(structuredClone(placed), { summary: "北の港。" });
    expect(edited.summary).toBe("北の港。");
    expect(edited.sketchPosition).toEqual({ x: 120, y: -40 });
  });

  test("承認待ちの反映は、案の位置で上書きせず、案から位置を足しもしない", () => {
    const proposal: Location = {
      ...structuredClone(placed),
      description: "船が着く",
      sketchPosition: { x: 0, y: 0 },
    };
    const merged = mergePendingSettingsRecord("location", structuredClone(placed), proposal);
    expect((merged as Location).description).toBe("船が着く");
    expect((merged as Location).sketchPosition).toEqual({ x: 120, y: -40 });

    const unplaced: Location = { ...emptyLocation("loc_002", "灯台") };
    for (const source of [undefined, "external"] as const) {
      const fromProposal = mergePendingSettingsRecord(
        "location",
        { ...unplaced, autoGenerated: source === "external" ? false : true },
        { ...unplaced, sketchPosition: { x: 5, y: 5 } },
        { source }
      );
      expect(fromProposal, String(source)).not.toHaveProperty("sketchPosition");
    }
  });
});
