import { describe, expect, test } from "vitest";
import {
  dedupeRelations,
  mergeExtractedCharacters,
} from "../../../src/core/characterMerge";
import {
  buildRelationGraph,
  filterRelationGraph,
  lastChapterOf,
} from "../../../src/core/relationGraph";
import { diffCharacter } from "../../../src/core/characterDiff";
import {
  describeRelationEditHint,
  editedRelations,
} from "../../../src/core/settingsEdit";
import { planCharacterSave } from "../../../src/core/externalExtractMerge";
import {
  emptyCharacter,
  parseCharacter,
  type Character,
} from "../../../src/models/character";

/**
 * 関係に話数を持たせる（作者の裁定、2026-10-02「関係にも話数を持たせる」）。
 *
 * 相関図の「第N話まで」（設計書6.38.2）は、人物と呼称は巻き戻せたが、
 * 関係の線だけは話数が無いので最終話の線が第1話の図にも引かれていた。
 * プロンプトは変えず、**抽出がどの話（チャンク）で関係を拾ったか**を
 * マージ（コード）が記録する。
 *
 * 1つのフォルダーに決まらない（models・core のマージ・図・差分・編集に
 * またがる）ので cross に置く。
 */

function person(id: string, name: string, extra: Partial<Character> = {}): Character {
  return { ...emptyCharacter(id, name), ...extra };
}

describe("マージ：関係を最初に拾った話を残す", () => {
  test("新しく拾った関係には、その話数が付く", () => {
    const result = mergeExtractedCharacters([], [
      {
        data: { name: "灯", relations: [{ name: "白鳥", relation: "婚約者" }] },
        chapters: [3],
      },
    ]);
    expect(result.characters[0].relations).toEqual([
      { name: "白鳥", relation: "婚約者", firstChapter: 3 },
    ]);
  });

  test("同じ関係を前の話でも拾ったら、早いほうの話になる", () => {
    const result = mergeExtractedCharacters([], [
      {
        data: { name: "灯", relations: [{ name: "白鳥", relation: "婚約者" }] },
        chapters: [5],
      },
      {
        data: { name: "灯", relations: [{ name: "白鳥", relation: "婚約者" }] },
        chapters: [2],
      },
    ]);
    expect(result.characters[0].relations).toEqual([
      { name: "白鳥", relation: "婚約者", firstChapter: 2 },
    ]);
  });

  test("まとめて送ったチャンク（複数話）は、いちばん前の話にする", () => {
    // どの話で出たかまでは分からない。前に倒せば、図で隠れすぎることはない
    const result = mergeExtractedCharacters([], [
      {
        data: { name: "灯", relations: [{ name: "白鳥", relation: "同僚" }] },
        chapters: [4, 5, 6],
      },
    ]);
    expect(result.characters[0].relations[0].firstChapter).toBe(4);
  });

  test("言い方が変わったら（婚約者→元婚約者）、両方を残し、それぞれの話数を持つ", () => {
    const result = mergeExtractedCharacters([], [
      {
        data: { name: "灯", relations: [{ name: "白鳥", relation: "婚約者" }] },
        chapters: [1],
      },
      {
        data: { name: "灯", relations: [{ name: "白鳥", relation: "元婚約者" }] },
        chapters: [8],
      },
    ]);
    expect(result.characters[0].relations).toEqual([
      { name: "白鳥", relation: "婚約者", firstChapter: 1 },
      { name: "白鳥", relation: "元婚約者", firstChapter: 8 },
    ]);
  });

  test("話数の無い古い関係（AIが積んだ人物）には、次の抽出で話数が付く", () => {
    const existing = person("char_001", "灯", {
      relations: [{ name: "白鳥", relation: "婚約者" }],
    });
    const result = mergeExtractedCharacters([existing], [
      {
        data: { name: "灯", relations: [{ name: "白鳥", relation: "婚約者" }] },
        chapters: [6],
      },
      {
        data: { name: "灯", relations: [{ name: "白鳥", relation: "婚約者" }] },
        chapters: [2],
      },
    ]);
    expect(result.characters[0].relations).toEqual([
      { name: "白鳥", relation: "婚約者", firstChapter: 2 },
    ]);
    expect(result.changedIds).toContain("char_001");
  });

  test("作者が確定させた人物（autoGenerated: false）の関係には話数を付けない", () => {
    const existing = person("char_001", "灯", {
      autoGenerated: false,
      relations: [{ name: "白鳥", relation: "婚約者" }],
    });
    const result = mergeExtractedCharacters([existing], [
      {
        data: { name: "灯", relations: [{ name: "白鳥", relation: "婚約者" }] },
        chapters: [2],
      },
    ]);
    expect(result.characters[0].relations).toEqual([
      { name: "白鳥", relation: "婚約者" },
    ]);
  });

  test("話数の分からない答え（話数が空）は、既にある話数を消さない", () => {
    const existing = person("char_001", "灯", {
      relations: [{ name: "白鳥", relation: "婚約者", firstChapter: 4 }],
    });
    const result = mergeExtractedCharacters([existing], [
      {
        data: { name: "灯", relations: [{ name: "白鳥", relation: "婚約者" }] },
        chapters: [],
      },
    ]);
    expect(result.characters[0].relations).toEqual([
      { name: "白鳥", relation: "婚約者", firstChapter: 4 },
    ]);
  });

  test("2人をまとめるとき、話数の無い側が混ざれば話数を付けない（隠さない側）", () => {
    expect(
      dedupeRelations([
        { name: "白鳥", relation: "同僚", firstChapter: 5 },
        { name: "白鳥", relation: "同僚" },
      ])
    ).toEqual([{ name: "白鳥", relation: "同僚" }]);
    expect(
      dedupeRelations([
        { name: "白鳥", relation: "同僚", firstChapter: 5 },
        { name: "白鳥", relation: "同僚", firstChapter: 3 },
      ])
    ).toEqual([{ name: "白鳥", relation: "同僚", firstChapter: 3 }]);
  });

  test("外部AIの道（planCharacterSave）でも話数が付く", () => {
    const plan = planCharacterSave([], [
      {
        data: { name: "灯", relations: [{ name: "白鳥", relation: "同僚" }] },
        chapters: [7],
      },
    ]);
    expect(plan?.created[0].relations).toEqual([
      { name: "白鳥", relation: "同僚", firstChapter: 7 },
    ]);
  });
});

describe("資料の読み込み", () => {
  test("話数の無い古い関係は、そのまま読める", () => {
    const character = parseCharacter({
      id: "char_001",
      name: "灯",
      relations: [{ name: "白鳥", relation: "同僚" }],
    });
    expect(character.relations).toEqual([{ name: "白鳥", relation: "同僚" }]);
  });

  test("話数の付いた関係を読める", () => {
    const character = parseCharacter({
      id: "char_001",
      name: "灯",
      relations: [{ name: "白鳥", relation: "同僚", firstChapter: 3 }],
    });
    expect(character.relations).toEqual([
      { name: "白鳥", relation: "同僚", firstChapter: 3 },
    ]);
  });

  test("話数が数でなければ読み込みエラーにする（黙って捨てない）", () => {
    expect(() =>
      parseCharacter({
        id: "char_001",
        name: "灯",
        relations: [{ name: "白鳥", relation: "同僚", firstChapter: "三" }],
      })
    ).toThrow();
  });
});

describe("相関図：関係の線も第N話に巻き戻す", () => {
  const characters = [
    person("char_001", "灯", {
      appearedChapters: [1, 2, 3, 8],
      relations: [
        { name: "白鳥", relation: "婚約者", firstChapter: 1 },
        { name: "白鳥", relation: "元婚約者", firstChapter: 8 },
        { name: "黒木", relation: "上司" },
      ],
    }),
    person("char_002", "白鳥", { appearedChapters: [1, 8] }),
    person("char_003", "黒木", { appearedChapters: [1] }),
  ];

  test("関係の言葉に話数が載る", () => {
    const graph = buildRelationGraph(characters);
    const labels = graph.edges.flatMap((edge) => edge.labels);
    expect(labels.find((label) => label.text === "元婚約者")?.firstChapter).toBe(8);
    expect(labels.find((label) => label.text === "上司")?.firstChapter).toBeNull();
  });

  test("第N話までの図では、その後に始まった関係を引かない", () => {
    const graph = buildRelationGraph(characters);
    const at3 = filterRelationGraph(graph, { upToChapter: 3 }).graph;
    const texts = at3.edges.flatMap((edge) => edge.labels.map((label) => label.text));
    expect(texts).toContain("婚約者");
    expect(texts).not.toContain("元婚約者");
    // 話数の無い関係は、両端が出ていれば今どおり引く
    expect(texts).toContain("上司");
  });

  test("関係が始まった話も、つまみの最終話に数える", () => {
    const graph = buildRelationGraph([
      person("char_001", "灯", {
        appearedChapters: [1],
        relations: [{ name: "白鳥", relation: "元婚約者", firstChapter: 12 }],
      }),
      person("char_002", "白鳥", { appearedChapters: [1] }),
    ]);
    expect(lastChapterOf(graph)).toBe(12);
  });
});

describe("承認の差分：話数だけ変わる更新も見える", () => {
  test("話数が付いただけの更新が「変更なし」で捨てられない", () => {
    const before = person("char_001", "灯", {
      relations: [{ name: "白鳥", relation: "婚約者" }],
    });
    const after = person("char_001", "灯", {
      relations: [{ name: "白鳥", relation: "婚約者", firstChapter: 2 }],
    });
    const diff = diffCharacter(before, after);
    expect(diff.changes.map((change) => change.label)).toContain("関係");
    const change = diff.changes.find((item) => item.label === "関係");
    expect(change?.after).toContain("第2話から");
    // ✕で落とす鍵は話数で変えない（言い方が同じなら同じ葉）
    expect(change?.entries?.every((entry) => entry.state === "kept")).toBe(true);
  });
});

describe("設定資料パネル：作者の編集", () => {
  test("触らなかった行の話数は、保存しても消えない", () => {
    const current = [
      { name: "白鳥", relation: "婚約者", firstChapter: 2 },
      { name: "黒木", relation: "上司", firstChapter: 1 },
    ];
    expect(editedRelations(current, "白鳥=婚約者\n黒木=恩師")).toEqual([
      { name: "白鳥", relation: "婚約者", firstChapter: 2 },
      // 作者が書き換えた行は作者の関係。話数は付けない
      { name: "黒木", relation: "恩師" },
    ]);
  });

  test("説明に、関係ごとの最初の話を出す", () => {
    const hint = describeRelationEditHint("灯", [], [
      { name: "白鳥", relation: "婚約者", firstChapter: 2 },
      { name: "黒木", relation: "上司" },
    ]);
    expect(hint).toContain("白鳥=婚約者（第2話から）");
    expect(hint).not.toContain("黒木=上司（");
  });

  test("話数の付いた関係が無ければ、説明は今までどおり", () => {
    expect(describeRelationEditHint("灯", [], [{ name: "黒木", relation: "上司" }])).toBe(
      describeRelationEditHint("灯", [])
    );
  });
});
