/**
 * 実機確認リストの 〔作者の手：見〕 のうち、原稿エディターと提案パネルの見た目を写真に撮る
 * （2026-10-09。作者が見た目の良し悪しを判断するための写真。判断そのものはしない）。
 *
 * `NOVELAI_LOOK=1` のときだけ動く（通常の E2E には入らない）。写真は `lookSupport.ts` の置き場へ。
 * 作品は使い捨ての見本だけ。AI は呼ばない。
 */
import { appendFile, mkdir, readFile } from "node:fs/promises";
import path from "node:path";
import type { Frame } from "playwright-core";
import { describe, expect, test } from "vitest";
import { emptyCharacter } from "../../../src/models/character";
import { footText, openEpisode } from "../support/manuscriptFrame";
import { OPEN_PROPOSALS_LAUNCH, OPEN_PROPOSALS_PRESS, proposalPanelFrame, writeSampleFinding } from "../support/sampleFinding";
import { defaultCharactersFolder, writeCharactersTo } from "../support/settingsFixture";
import { VERTICAL_LAUNCH, turnVertical } from "../support/verticalFace";
import { withVsCode, type E2ESession } from "../support/vscodeApp";
import { waitUntil } from "../support/wait";
import { clearNotifications, dismissWorkbenchHover } from "../support/workbenchDom";
import { coloredCharacterTerms, lookEnabled, shootPage } from "./lookSupport";

const NOVEL_EPISODE = "001_用語と記号.md";
const SNS_EPISODE = "2026-09-04_記事.md";

const NOVEL_LINES = [
  "　三門太志は言った。――そうか。それなら、仕方がない。",
  "　……いや、密倉文佳は黙っていた。――――長い沈黙だった。",
  "　「三門太志さん」と密倉文佳が呼んだ。……………………",
  "　窓の外では、雨が降っていた。三門太志は傘を持たずに出た。",
  "　密倉文佳は、その背中をずっと見ていた。――そして、笑った。",
  "　夜になっても、三門太志は帰らなかった。密倉文佳は灯りを消さなかった。",
];
const SNS_LINES = [
  "# 三門太志と密倉文佳の話",
  "",
  "三門太志は言った。――そうか。……いや、密倉文佳は黙っていた。",
  "",
  "密倉文佳は、その背中をずっと見ていた。三門太志は傘を持たずに出た。",
];

/** 起こす前に人物を置く（起きたあとに置くと「外で変更されました」の知らせが写真に写る） */
async function writeCharacters(workFolder: string): Promise<void> {
  await writeCharactersTo(
    defaultCharactersFolder(workFolder),
    ["三門太志", "密倉文佳"].map((name, index) => ({ ...emptyCharacter(`char_00${index + 1}`, name), autoGenerated: false }))
  );
}

async function waitColors(frame: Frame, label: string): Promise<void> {
  await waitUntil(async () => (await coloredCharacterTerms(frame)).length >= 2, `${label}：人物の色が付く`, 30_000);
  // 描き終わりと色の位置が落ち着くのを少し待つ
  await frame.page().waitForTimeout(800);
}

async function bigger(session: E2ESession, frame: Frame, times: number): Promise<void> {
  await dismissWorkbenchHover(session.page);
  for (let i = 0; i < times; i++) {
    await frame.evaluate(() => (document.getElementById("bigger") as HTMLElement).click());
    await session.page.waitForTimeout(150);
  }
  await session.page.waitForTimeout(800);
  console.log("[look] 大きくしたあとの下の欄:", await footText(frame, "counts"));
}

describe.skipIf(!lookEnabled)("見た目の写真：原稿エディター", () => {
  test("ダッシュ・三点リーダー・用語の色（横書き・縦書き、字の大きさ、note風）", async () => {
    await withVsCode(
      "見た目の写真：原稿",
      [
        // 縦書きで横に流れて、スクロールバーが出るだけの行数にする（6251）
        { name: NOVEL_EPISODE, text: [...NOVEL_LINES, ...NOVEL_LINES, ...NOVEL_LINES, ...NOVEL_LINES].join("\r\n") + "\r\n" },
        // 改行を揃える（違うと「改行コードが違います」の知らせが写真に写る）
        { name: SNS_EPISODE, text: SNS_LINES.join("\r\n") + "\r\n" },
      ],
      async (session) => {
        const { page } = session;
        await clearNotifications(page);

        // ── 横書き（組んで書く面） ──
        const frame = await openEpisode(page, NOVEL_EPISODE, "雨が降っていた");
        await waitColors(frame, "横書き");
        await shootPage(page, "6149-ダッシュ-横書き");
        await shootPage(page, "6236-三点リーダー-横書き");
        await shootPage(page, "6391-用語の色-横書き-標準");
        await bigger(session, frame, 4);
        await shootPage(page, "6391-用語の色-横書き-大きく");

        // ── note風（SNS記事） ──
        const note = await openEpisode(page, SNS_EPISODE, "見ていた。三門太志は");
        await waitColors(note, "note風");
        await shootPage(page, "5628-用語の色-note風-標準");
        await bigger(session, note, 4);
        await shootPage(page, "5628-用語の色-note風-大きく");

        // ── 縦書き ──
        const again = await openEpisode(page, NOVEL_EPISODE, "雨が降っていた");
        await again.page().waitForTimeout(300);
        const vertical = await turnVertical(session, "雨が降っていた");
        await waitColors(vertical, "縦書き");
        await shootPage(page, "6149-ダッシュ-縦書き");
        await shootPage(page, "6236-三点リーダー-縦書き");
        await shootPage(page, "6251-用語の色-縦書き-標準");
        await shootPage(page, "6391-用語の色-縦書き-標準");
        await bigger(session, vertical, 4);
        await shootPage(page, "6251-用語の色-縦書き-大きく");
        await shootPage(page, "6391-用語の色-縦書き-大きく");
        expect(await coloredCharacterTerms(vertical)).not.toHaveLength(0);
      },
      {
        ...VERTICAL_LAUNCH,
        windowSize: { width: 1280, height: 800 },
        prepareWork: ({ workFolder }) => writeCharacters(workFolder),
      }
    );
  });
});

describe.skipIf(!lookEnabled)("見た目の写真：提案パネル", () => {
  test("下段（提案パネル）を狭くしたときの分類タブ", async () => {
    const EPISODE = "001_駅.txt";
    const TEXT = [
      "　終電を逃した駅のホームに、雨の音だけが残っていた。",
      "　近づいてみると、男は以外にも若かった。",
      "　ホームの時計が、零時を指していた。",
      "　彼は彼は何も言わなかった。",
      "　翌朝、彼女は昨日と違う名前を名乗った。",
      "",
    ].join("\n");
    await withVsCode(
      "見た目の写真：提案パネル",
      [{ name: EPISODE, text: TEXT }],
      async (session) => {
        const { page } = session;
        // 分類の違う指摘を3つ置く（誤字脱字・推敲・矛盾）。置き場の1行1件の形は製品と同じ
        await writeSampleFinding(session.workFolder, {
          episode: EPISODE,
          text: TEXT,
          original: "男は以外にも若かった。",
          target: "以外",
          suggestion: "意外",
          message: "「思いのほか」の意味なら「意外」です",
        });
        const scratch = path.join(session.root, "scratch");
        await mkdir(scratch, { recursive: true });
        const extra: Array<{ original: string; target: string; suggestion: string; message: string; category: "proofread" | "contradiction"; label: string }> = [
          { original: "彼は彼は何も言わなかった。", target: "彼は彼は", suggestion: "彼は", message: "同じ語が重なっています", category: "proofread", label: "推敲" },
          { original: "翌朝、彼女は昨日と違う名前を名乗った。", target: "違う名前", suggestion: "", message: "前の話では同じ名前でした", category: "contradiction", label: "矛盾" },
        ];
        for (const [index, sample] of extra.entries()) {
          const dir = path.join(scratch, String(index));
          await mkdir(dir, { recursive: true });
          await writeSampleFinding(dir, { episode: EPISODE, text: TEXT, ...sample });
          const line = await readFile(path.join(dir, ".aiwriter", "findings.jsonl"), "utf8");
          await appendFile(path.join(session.workFolder, ".aiwriter", "findings.jsonl"), line, "utf8");
        }
        await openEpisode(page, EPISODE, "零時を指していた");
        await clearNotifications(page);
        await page.keyboard.press(OPEN_PROPOSALS_PRESS);
        let panel: Frame | undefined;
        await waitUntil(
          async () => {
            panel = await proposalPanelFrame(page);
            return panel !== undefined;
          },
          "提案パネルが開く",
          20_000
        );
        await page.waitForTimeout(1500);
        await shootPage(page, "4544-提案パネル-窓の幅そのまま");
        // 狭くする：窓の幅を絞って、提案パネルの列も細くする
        await session.app.evaluate(({ BrowserWindow }) => {
          for (const win of BrowserWindow.getAllWindows()) win.setContentSize(620, 800);
        });
        await page.waitForTimeout(1500);
        await shootPage(page, "4544-提案パネル-狭い");
      },
      { ...OPEN_PROPOSALS_LAUNCH, windowSize: { width: 1280, height: 800 } }
    );
  });
});
