/**
 * 実機確認リストの 〔作者の手：見た目〕 のうち、名前点検の「候補を出す」と、系統を選ぶ画面の文言の写真
 * （カタカナの名前の作品で、同じ系統で揃えて出すか。2026-10-09 の二段目。判断は作者がする）。
 *
 * **本物の AI は呼ばない。** 偽の Ollama が、決まった名前の候補を返す。**名前の出来は見えない**。
 * `NOVELAI_LOOK=1` のときだけ動く。作品は使い捨ての見本だけ。
 */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type { Frame, Page } from "playwright-core";
import { afterAll, beforeAll, describe, test } from "vitest";
import { emptyCharacter, type Character } from "../../../src/models/character";
import { fakeOllamaLaunch, passLocalAiGate, startFakeOllama, type FakeOllama } from "../support/fakeOllama";
import { runCommand } from "../support/quickInput";
import { defaultCharactersFolder, writeCharactersTo } from "../support/settingsFixture";
import { SIDEBAR_LAUNCH } from "../support/sidebar";
import { withVsCode } from "../support/vscodeApp";
import { waitUntil } from "../support/wait";
import { acceptQuickPick, clearNotifications, dialogText, pickQuickPickRow, pressDialogButton, quickPickRows, quickPickTitle } from "../support/workbenchDom";
import { lookEnabled, lookNote, shootPage } from "./lookSupport";
import { nameFakeRespond, openPlotMode } from "./nameLookSupport";

const PLOT = [
  "# カタカナの王国の物語",
  "",
  "## 世界観",
  "海に面した小さな王国。城下町と港がある。",
  "",
  "## 主要登場人物",
  "- 騎士：20歳の青年。王に仕える。",
  "- 参謀：年配の女性。王国の財政を預かる。",
  "",
  "## あらすじ",
  "騎士は参謀とともに、王国の港を守る。",
  "",
].join("\n");

const PEOPLE: Character[] = [
  { name: "ミレイユ", reading: "みれいゆ", gender: "女", role: "王女" },
  { name: "ボリス", reading: "ぼりす", gender: "男", role: "宰相" },
  { name: "アリシア", reading: "ありしあ", gender: "女", role: "侍女" },
].map((entry, index) => ({
  ...emptyCharacter(`char_00${index + 1}`, entry.name),
  reading: entry.reading,
  gender: entry.gender,
  role: entry.role,
  autoGenerated: false,
  appearedChapters: [1],
}));

let fake: FakeOllama;
beforeAll(async () => {
  fake = await startFakeOllama(nameFakeRespond);
});
afterAll(async () => {
  await fake.close();
});

async function nameCheckFrame(page: Page): Promise<Frame | undefined> {
  for (const frame of page.frames()) {
    const has = await frame.evaluate(() => document.querySelector("[data-suggest]") !== null && document.getElementById("people") !== null).catch(() => false);
    if (has) return frame;
  }
  return undefined;
}

describe.skipIf(!lookEnabled)("見た目の写真：名前点検の候補と系統の画面", () => {
  test("カタカナの名前の作品で、候補を出すを3回・4回押す", async () => {
    await withVsCode(
      "見た目の写真：名前点検の系統",
      [{ name: "第1話_はじまり.txt", text: "ミレイユはボリスに言った。アリシアは黙っていた。\n" }],
      async (session) => {
        const { page } = session;
        await clearNotifications(page);
        await runCommand(page, "名前点検");
        let panel: Frame | undefined;
        await waitUntil(
          async () => {
            if ((await quickPickTitle(page)) !== undefined && !panel) {
              const rows = await quickPickRows(page);
              if (rows.length > 0) await pickQuickPickRow(page, rows[0].label);
            }
            return (panel = await nameCheckFrame(page)) !== undefined;
          },
          "名前点検のパネルが開く",
          30_000
        );
        const frame = panel as Frame;
        await waitUntil(async () => (await frame.locator("[data-suggest]").count()) >= 3, "人物が並ぶ", 15_000);
        await page.waitForTimeout(800);

        const press = async (label: string, originRow: string, photoOnPick?: string): Promise<void> => {
          const requests = fake.requests.length;
          await frame.locator("[data-suggest]").nth(1).click();
          let photographed = false;
          await waitUntil(
            async () => {
              await passLocalAiGate(page);
              const title = (await quickPickTitle(page)) ?? "";
              if (title.includes("名前の系統")) {
                if (photoOnPick && !photographed) {
                  photographed = true;
                  await page.waitForTimeout(500);
                  const rows = await quickPickRows(page);
                  await lookNote(`[${label}] 系統を選ぶ画面の題：${title}／行：${rows.slice(0, 3).map((row) => `${row.label}〔${row.description}〕`).join(" / ")}`);
                  const detail = await page.locator(".quick-input-widget .quick-input-list .monaco-list-row").first().innerText();
                  await lookNote(`[${label}] 系統を選ぶ画面の先頭行：${detail.replace(/\s+/g, " ")}`);
                  await shootPage(page, photoOnPick);
                }
                await pickQuickPickRow(page, originRow);
              } else {
                const dialog = await dialogText(page);
                if (dialog) await pressDialogButton(page, "続ける").catch(() => pressDialogButton(page, "OK")).catch(() => undefined);
              }
              return fake.requests.length > requests && (await frame.locator(".origin-note").count()) > 0 && (await frame.locator("[data-suggest]").first().isEnabled());
            },
            `${label}：候補が出る`,
            60_000
          );
          await page.waitForTimeout(800);
        };

        await press("1回目", "指定なし");
        await lookNote(`[504] 1回目の系統の一文：${await frame.locator(".origin-note").first().innerText()}`);
        await shootPage(page, "504-名前点検-1回目の候補");

        await press("2回目", "指定なし", "504-名前点検-2回目の系統を選ぶ画面");
        await lookNote(`[504] 2回目の系統の一文：${await frame.locator(".origin-note").first().innerText()}`);
        await lookNote(`[504] 2回目に残った候補の系統：${(await frame.locator(".candidate .meta").allInnerTexts()).map((text) => text.replace(/\s+/g, " ")).join(" ／ ")}`);
        await shootPage(page, "504-名前点検-2回目の候補");

        // 3回目：系統を選ぶ画面を撮って、別の系統（フランス）を選ぶ
        await press("3回目", "フランス", "507-名前点検-3回目の系統を選ぶ画面");
        await lookNote(`[507] 3回目（フランスを選んだ）の系統の一文：${await frame.locator(".origin-note").first().innerText()}`);
        await shootPage(page, "507-名前点検-3回目フランスを選んだあと");

        // 4回目：指定なしに戻す（フランスで揃うか）
        await press("4回目", "指定なし", "507-名前点検-4回目の系統を選ぶ画面");
        await lookNote(`[507] 4回目（指定なし）の系統の一文：${await frame.locator(".origin-note").first().innerText()}`);
        await shootPage(page, "507-名前点検-4回目の候補");

        // プロットモードの名前の候補（508）。同じ作品で、役名だけの人物へ候補を出す
        const plot = await openPlotMode(session);
        await waitUntil(async () => (await plot.locator("[data-suggest-names]").count()) > 0, "［名前の候補を出す］が出る", 30_000);
        const requests = fake.requests.length;
        await plot.locator("[data-suggest-names]").click();
        await waitUntil(
          async () => {
            await passLocalAiGate(page);
            const title = (await quickPickTitle(page)) ?? "";
            if (title.includes("名前の候補を出す人物")) await acceptQuickPick(page);
            else if (title.includes("名前の系統")) {
              await page.waitForTimeout(300);
              await shootPage(page, "508-プロットモード-系統を選ぶ画面");
              await pickQuickPickRow(page, "指定なし");
            } else {
              const dialog = await dialogText(page);
              if (dialog) await pressDialogButton(page, "続ける").catch(() => pressDialogButton(page, "OK")).catch(() => undefined);
            }
            return fake.requests.length > requests && (await plot.locator(".name-person").count()) > 0;
          },
          "プロットモードの候補が並ぶ",
          60_000
        );
        await page.waitForTimeout(800);
        await lookNote(`[508] プロットモードの名前の欄の一文：${await plot.locator("#namesNote").innerText()}`);
        await plot.locator("#nameResults").scrollIntoViewIfNeeded();
        await page.waitForTimeout(400);
        await shootPage(page, "508-プロットモード-候補の欄");
      },
      fakeOllamaLaunch(fake, {
        ...SIDEBAR_LAUNCH,
        windowSize: { width: 1280, height: 900 },
        settings: {
          ...SIDEBAR_LAUNCH.settings,
          "workbench.editorAssociations": { "*.txt": "novelai.manuscriptEditorHorizontal", "*.md": "default" },
        },
        prepareWork: async ({ workFolder }) => {
          await writeCharactersTo(defaultCharactersFolder(workFolder), PEOPLE);
          await mkdir(path.join(workFolder, "設定"), { recursive: true });
          await writeFile(path.join(workFolder, "設定", "plot.md"), PLOT, "utf8");
        },
      })
    );
  });
});
