/**
 * 実機確認リストの 〔作者の手：見た目〕 のうち、プロットモードの「名前の候補を出す」まわりの写真
 * （2026-10-09 の二段目。作者が見た目の良し悪しを判断するための写真。判断そのものはしない）。
 *
 * **本物の AI は呼ばない。** 偽の Ollama が、決まった名前の候補を返す。見られるのは答えが返ったあとの
 * 配線と画面で、**名前の出来（良し悪し）は見えない**。作品は使い捨ての見本だけ。
 * `NOVELAI_LOOK=1` のときだけ動く。
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { afterAll, beforeAll, describe, test } from "vitest";
import { emptyCharacter, type Character } from "../../../src/models/character";
import type { Frame } from "playwright-core";
import { fakeOllamaLaunch, passLocalAiGate, startFakeOllama, type FakeOllama } from "../support/fakeOllama";
import { defaultCharactersFolder, writeCharactersTo } from "../support/settingsFixture";
import { SIDEBAR_LAUNCH } from "../support/sidebar";
import { withVsCode } from "../support/vscodeApp";
import { waitUntil } from "../support/wait";
import { clearNotifications, dialogText, pickQuickPickRow, pressDialogButton, pressWorkbenchKey, quickPickRows, quickPickTitle } from "../support/workbenchDom";
import { lookEnabled, lookNote, shootPage, shootPageKeepingToasts } from "./lookSupport";
import { nameFakeRespond, openPlotMode, openUpdates, panelText, rewritePlotAndSave, runNameSuggest } from "./nameLookSupport";

const PLOT = [
  "# 見本の物語",
  "",
  "## 世界観",
  "現代の小さな港町。",
  "",
  "## 主要登場人物",
  "- 主人公：17歳の高校生。港町で育ち、船に憧れている。",
  "- ヒロイン：春に転校してきた少女。海を怖がっている。",
  "- 班長：港の見回りをまとめる年配の男。",
  "",
  "## あらすじ",
  "主人公は転校生のヒロインと出会い、班長に港の仕事を教わる。",
  "",
].join("\n");

let fake: FakeOllama;
beforeAll(async () => {
  fake = await startFakeOllama((request) => {
    // 相談を資料へ反映（P-32）：作者の発言から決まったことを拾う
    if (request.user.includes("【相談の記録】")) {
      return JSON.stringify({
        decisions: [{ name: "相馬 誠", decided: "年齢は17歳", evidence: "相馬 誠の年齢は17歳にします" }],
      });
    }
    if (request.user.includes("名前の候補")) return nameFakeRespond(request);
    return "了解しました。年齢は17歳で進めましょう。";
  });
});
afterAll(async () => {
  await fake.close();
});

const EXISTING: Character = { ...emptyCharacter("char_002", "白瀬 灯"), reading: "しらせ あかり", autoGenerated: false, role: "友人", appearedChapters: [1] };
const LEDGER_ROLE: Character = { ...emptyCharacter("char_001", "主人公"), autoGenerated: true, appearedChapters: [1] };

function launchOptions(extraCharacters: readonly Character[]) {
  return fakeOllamaLaunch(fake, {
    ...SIDEBAR_LAUNCH,
    keybindings: [...SIDEBAR_LAUNCH.keybindings, { key: "ctrl+alt+shift+c", command: "novelai.openChat" }],
    windowSize: { width: 1280, height: 900 },
    settings: {
      ...SIDEBAR_LAUNCH.settings,
      // plot.md は素のテキストエディターで開く（作者の既定。6.4.8）
      "workbench.editorAssociations": { "*.txt": "novelai.manuscriptEditorHorizontal", "*.md": "default" },
    },
    prepareWork: async ({ workFolder }) => {
      await writeCharactersTo(defaultCharactersFolder(workFolder), [EXISTING, ...extraCharacters]);
      await mkdir(path.join(workFolder, "設定"), { recursive: true });
      await writeFile(path.join(workFolder, "設定", "plot.md"), PLOT, "utf8");
    },
  });
}

describe.skipIf(!lookEnabled)("見た目の写真：プロットモードの名前の候補", () => {
  test("候補の一覧・入れる・承認待ちの並び・見送り（資料に「主人公」がいる作品）", async () => {
    await withVsCode(
      "見た目の写真：プロットの名前の候補",
      [{ name: "第1話_はじまり.txt", text: "一話の本文。\n" }],
      async (session) => {
        const { page } = session;
        const plot = await openPlotMode(session);
        await waitUntil(async () => (await plot.locator("[data-suggest-names]").count()) > 0, "［名前の候補を出す］が出る", 30_000);
        await page.waitForTimeout(1200);
        await shootPage(page, "554-プロットモード-候補を出す前");
        await runNameSuggest(session, plot, {
          onTargetsPick: async () => {
            await page.waitForTimeout(500);
            await shootPage(page, "554-プロットモード-人物を選ぶ画面");
          },
        });
        await lookNote(`[554・563] プロットモードの名前の欄：${(await plot.locator("#nameResults").innerText()).replace(/\s+/g, " ").slice(0, 900)}`);
        await lookNote(`[554] 名前の欄の上の一文：${await plot.locator("#namesNote").innerText()}`);
        await plot.locator("#nameResults").scrollIntoViewIfNeeded();
        await page.waitForTimeout(500);
        await shootPage(page, "554-563-プロットモード-候補の一覧");
        // 落とした候補の畳みを開く
        const dropped = plot.locator(".name-person details summary").first();
        if ((await dropped.count()) > 0) await dropped.click();
        await page.waitForTimeout(400);
        await shootPage(page, "563-プロットモード-落とした候補を開いた");

        // 人物ごとに1つ選ぶ（主人公・ヒロインだけ。班長は選ばない）
        await plot.locator('input[name="name-1"]').nth(1).check();
        await plot.locator('input[name="name-2"]').nth(2).check();
        await page.waitForTimeout(300);
        await shootPage(page, "564-プロットモード-選んだところ");
        await plot.locator("[data-apply-names]").click();
        await page.waitForTimeout(2500);
        await shootPageKeepingToasts(page, "564-プロットモード-入れたあと-知らせつき");
        const plotText = (await readFile(path.join(session.workFolder, "設定", "plot.md"), "utf8")).replace(/\r\n/g, "\n");
        await lookNote(`[564] plot.md の主要登場人物（入れたあと）：${plotText.split("\n").filter((line) => line.startsWith("- ")).join(" ／ ")}`);

        // 設定資料更新分反映
        let updates = await openUpdates(session);
        await lookNote(`[564・545] 更新分反映（入れた直後）：${await panelText(updates)}`);
        await shootPage(page, "564-545-更新分反映-入れた直後");

        // 545：承認する前に plot.md のほかの行を書き換えて保存
        await rewritePlotAndSave(page, plotText.replace("主人公は転校生のヒロインと出会い", "主人公は転校生のヒロインと港で出会い"));
        await page.waitForTimeout(1500);
        await shootPageKeepingToasts(page, "566-545-別の行を保存した直後-知らせ");
        updates = await openUpdates(session);
        await lookNote(`[545・566] 更新分反映（別の行を保存したあと）：${await panelText(updates)}`);
        await shootPage(page, "545-566-更新分反映-別の行を保存したあと");
        await shootPage(page, "見出し-直したあと");

        // 546：「主人公（相馬 誠）」の行の説明を書き換えて保存
        const afterOther = (await readFile(path.join(session.workFolder, "設定", "plot.md"), "utf8")).replace(/\r\n/g, "\n");
        await rewritePlotAndSave(page, afterOther.replace("17歳の高校生。港町で育ち、船に憧れている。", "17歳の高校生。船乗りの家に生まれ、船に憧れている。"));
        await page.waitForTimeout(1500);
        updates = await openUpdates(session);
        await lookNote(`[546] 更新分反映（説明を書き換えたあと）：${await panelText(updates)}`);
        await shootPage(page, "546-更新分反映-説明を書き換えたあと");

        // 530：案を「見送る」→ plot.md のほかの行を書き換えて保存 → 並び直さない
        // 「主人公→相馬 誠」の案の［見送る］を探す（葛西 湊・班長の案とは別）
        const skipIndex = await updates.evaluate(() => {
          const buttons = Array.from(document.querySelectorAll("button")).filter((button) => (button.textContent ?? "").trim() === "見送る");
          return buttons.findIndex((button) => {
            let node: HTMLElement | null = button.parentElement;
            for (let depth = 0; depth < 5 && node; depth++) {
              const text = node.innerText;
              if (text.includes("相馬 誠") && !text.includes("葛西 湊") && !text.includes("班長")) return true;
              node = node.parentElement;
            }
            return false;
          });
        });
        await lookNote(`[530] 見送る対象の番号：${skipIndex}`);
        if (skipIndex >= 0) {
          await updates.locator("button", { hasText: "見送る" }).nth(skipIndex).click();
          await page.waitForTimeout(1500);
          await shootPage(page, "530-見送ったあと");
          const base = (await readFile(path.join(session.workFolder, "設定", "plot.md"), "utf8")).replace(/\r\n/g, "\n");
          await rewritePlotAndSave(page, base.replace("港の仕事を教わる", "港の仕事を一から教わる"));
          await page.waitForTimeout(1500);
          await shootPageKeepingToasts(page, "530-見送ったあとで別の行を保存-知らせ");
          updates = await openUpdates(session);
          await lookNote(`[530] 更新分反映（見送って別の行を保存したあと）：${await panelText(updates)}`);
          await shootPage(page, "530-見送ったあと-更新分反映");
        }
      },
      launchOptions([LEDGER_ROLE])
    );
  });

  test("候補を出したあとに plot.md が書き換わった・保存していない書きかけがあるときの［入れる］", async () => {
    await withVsCode(
      "見た目の写真：入れるを止める文言",
      [{ name: "第1話_はじまり.txt", text: "一話の本文。\n" }],
      async (session) => {
        const { page } = session;
        const plot = await openPlotMode(session);
        await waitUntil(async () => (await plot.locator("[data-suggest-names]").count()) > 0, "［名前の候補を出す］が出る", 30_000);
        await runNameSuggest(session, plot);
        await plot.locator('input[name="name-1"]').nth(1).check();
        // plot.md を別の字へ書き換えて保存する
        await rewritePlotAndSave(page, PLOT.replace("港町で育ち", "港町で生まれ育ち"));
        await clearNotifications(page);
        await plot.locator("[data-apply-names]").click();
        await page.waitForTimeout(1500);
        await lookNote(`[565] 書き換えたあと［入れる］：名前の欄の一文 ${await plot.locator("#namesNote").innerText()}`);
        await shootPageKeepingToasts(page, "565-書き換わったあと入れる");
        const afterStop = (await readFile(path.join(session.workFolder, "設定", "plot.md"), "utf8")).replace(/\r\n/g, "\n");
        await lookNote(`[565] 止めたあとの plot.md の主人公の行：${afterStop.split("\n").find((line) => line.startsWith("- 主人公")) ?? ""}`);
      },
      launchOptions([LEDGER_ROLE])
    );
  });

  test("保存していない書きかけがあるときの［入れる］", async () => {
    await withVsCode(
      "見た目の写真：保存していない書きかけで入れる",
      [{ name: "第1話_はじまり.txt", text: "一話の本文。\n" }],
      async (session) => {
        const { page } = session;
        const plot = await openPlotMode(session);
        await waitUntil(async () => (await plot.locator("[data-suggest-names]").count()) > 0, "［名前の候補を出す］が出る", 30_000);
        await runNameSuggest(session, plot);
        await plot.locator('input[name="name-1"]').nth(1).check();
        // plot.md を開いたまま1行足す（保存しない）
        const lines = page.locator(".monaco-editor .view-lines", { hasText: "主要登場人物" }).first();
        await lines.click();
        await page.keyboard.press("Control+End");
        await page.keyboard.insertText("書きかけの一行");
        await clearNotifications(page);
        await plot.locator("[data-apply-names]").click();
        await page.waitForTimeout(1500);
        const toasts = await page.locator(".notification-toast").allInnerTexts();
        await lookNote(`[565] 保存していない書きかけで［入れる］：知らせ ${toasts.map((text) => text.replace(/\s+/g, " ")).join(" ／ ")}`);
        await shootPageKeepingToasts(page, "565-保存していない書きかけで入れる");
      },
      launchOptions([LEDGER_ROLE])
    );
  });

  test("作者が確定させた「主人公」でも更新案として並び、承認したあと呼称の鍵が残る", async () => {
    const LOCKED: Character = {
      ...LEDGER_ROLE,
      autoGenerated: false,
      addressTerms: [
        {
          targetName: "白瀬 灯",
          targetId: "char_002",
          forms: [{ term: "灯さん", category: null, context: null, firstChapter: 1, lastChapter: null, status: "current", evidence: null }],
          authorLocked: true,
        },
      ],
    };
    await withVsCode(
      "見た目の写真：確定させた主人公",
      [{ name: "第1話_はじまり.txt", text: "一話の本文。\n" }],
      async (session) => {
        const { page } = session;
        const plot = await openPlotMode(session);
        await waitUntil(async () => (await plot.locator("[data-suggest-names]").count()) > 0, "［名前の候補を出す］が出る", 30_000);
        await runNameSuggest(session, plot);
        await plot.locator('input[name="name-1"]').nth(1).check();
        await plot.locator("[data-apply-names]").click();
        await page.waitForTimeout(2500);
        const updates = await openUpdates(session);
        await lookNote(`[556] 更新分反映：${await panelText(updates)}`);
        await shootPage(page, "556-確定させた主人公-更新分反映");
        const approve = updates.locator("button", { hasText: "反映する" }).first();
        await approve.click();
        await page.waitForTimeout(2500);
        await shootPageKeepingToasts(page, "556-承認したあと");
        const file = path.join(session.workFolder, "設定", "characters");
        const { readdir } = await import("node:fs/promises");
        const names = (await readdir(file, { withFileTypes: true })).filter((entry) => entry.isFile() && entry.name.endsWith(".json")).map((entry) => entry.name);
        const rows: string[] = [];
        for (const name of names) {
          const record = JSON.parse(await readFile(path.join(file, name), "utf8")) as Character;
          rows.push(`${name}: 名前=${record.name} 読み=${record.reading ?? "なし"} 役割=${record.role ?? "なし"} autoGenerated=${record.autoGenerated} 呼称の鍵=${JSON.stringify((record.addressTerms ?? []).map((term) => term.authorLocked))}`);
        }
        await lookNote(`[556] 承認したあとの人物ファイル：${rows.join(" ／ ")}`);
      },
      launchOptions([LOCKED])
    );
  });

  test("名前を直す案が承認待ちにあるうちに、相談で年齢を決めて「相談を資料へ反映」", async () => {
    await withVsCode(
      "見た目の写真：相談からの反映",
      [{ name: "第1話_はじまり.txt", text: "一話の本文。\n" }],
      async (session) => {
        const { page } = session;
        const plot = await openPlotMode(session);
        await waitUntil(async () => (await plot.locator("[data-suggest-names]").count()) > 0, "［名前の候補を出す］が出る", 30_000);
        await runNameSuggest(session, plot);
        await plot.locator('input[name="name-1"]').nth(1).check();
        await plot.locator("[data-apply-names]").click();
        await page.waitForTimeout(2500);
        const before = await openUpdates(session);
        await lookNote(`[531] 相談の前の更新分反映：${await panelText(before)}`);

        // 相談パネルで「相馬 誠の年齢は17歳にします」と決める
        await pressWorkbenchKey(page, "Control+Alt+Shift+KeyC");
        let chat: Frame | undefined;
        await waitUntil(
          async () => {
            for (const frame of page.frames()) {
              const ok = await frame.evaluate(() => document.getElementById("context-what") !== null && document.getElementById("to-main") !== null).catch(() => false);
              if (ok) chat = frame;
            }
            return chat !== undefined;
          },
          "横の相談パネルが開く",
          30_000
        );
        const frame = chat as Frame;
        await waitUntil(async () => ((await frame.evaluate(() => document.getElementById("context-what")?.textContent ?? "")) ?? "").length > 3, "相談の対象が決まる", 30_000);
        await frame.locator("#input").click();
        await page.keyboard.insertText("相馬 誠の年齢は17歳にします");
        await frame.locator("#send").click();
        await waitUntil(
          async () => {
            await passLocalAiGate(page);
            return (await frame.evaluate(() => document.getElementById("log")?.innerText ?? "")).includes("了解しました");
          },
          "相談の返事が出る",
          90_000
        );
        await waitUntil(async () => await frame.locator("#apply-settings").isEnabled(), "［相談を資料へ反映］が押せる", 30_000);
        await frame.locator("#apply-settings").click();
        // 料金の確認・直接書くか承認待ちかの選択を通す
        await waitUntil(
          async () => {
            await passLocalAiGate(page);
            const dialog = await dialogText(page);
            if (dialog) {
              await lookNote(`[531] 出た確認：${dialog.replace(/s+/g, " ").slice(0, 300)}`);
              await pressDialogButton(page, "承認待ちに積む").catch(() => pressDialogButton(page, "実行")).catch(() => pressDialogButton(page, "続ける")).catch(() => undefined);
            }
            const title = (await quickPickTitle(page)) ?? "";
            if (title !== "") {
              const rows = await quickPickRows(page);
              await lookNote(`[531] 選ぶ画面：${title}｜${rows.map((row) => row.label).join(" / ")}`);
              const pick = rows.find((row) => row.label.includes("承認待ち")) ?? rows.find((row) => row.label.includes("実行"));
              if (pick) await pickQuickPickRow(page, pick.label).catch(() => undefined);
            }
            const toasts = await page.locator(".notification-toast").allInnerTexts();
            return toasts.some((text) => text.includes("承認待ち") || text.includes("積み"));
          },
          "反映の結果の知らせが出る",
          90_000
        ).catch(async (error: unknown) => {
          await lookNote(`[531] 結果の知らせが出なかった：${String(error).slice(0, 80)}`);
        });
        await page.waitForTimeout(1500);
        await shootPageKeepingToasts(page, "531-相談を資料へ反映したあとの知らせ");
        const after = await openUpdates(session);
        await lookNote(`[531] 相談のあとの更新分反映：${await panelText(after)}`);
        await shootPage(page, "531-相談のあと-更新分反映");
      },
      launchOptions([LEDGER_ROLE])
    );
  });
});
