/**
 * 実機確認リストの 〔作者の手：見た目〕 のうち、設定資料パネルと提案パネル（承認待ちの更新案）の写真
 * （2026-10-09 の二段目。作者が見た目の良し悪しを判断するための写真。判断そのものはしない）。
 *
 * `NOVELAI_LOOK=1` のときだけ動く。作品は使い捨ての見本だけ。AI は呼ばない（人物・承認待ちの案は置き場へ見本を置く）。
 */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type { Frame } from "playwright-core";
import { describe, test } from "vitest";
import { emptyCharacter, type Character } from "../../../src/models/character";
import type { NarratorMoveItem } from "../../../src/core/narratorMoves";
import {
  PENDING_MOVES_DIR,
  buildPendingNarratorMovePayload,
  pendingNarratorMoveFileName,
} from "../../../src/core/pendingNarratorMoves";
import { runCommand } from "../support/quickInput";
import { proposalPanelFrame } from "../support/sampleFinding";
import { defaultCharactersFolder, settingsPanelFrame, writeCharactersTo } from "../support/settingsFixture";
import { withVsCode, type E2ESession } from "../support/vscodeApp";
import { waitUntil } from "../support/wait";
import { clearNotifications } from "../support/workbenchDom";
import { lookEnabled, lookNote, shootPage } from "./lookSupport";

const OPEN_SETTINGS_KEY = "ctrl+alt+shift+f1";
const OPEN_SETTINGS_PRESS = "Control+Alt+Shift+F1";
const EPISODES = [{ name: "001_はじまり.md", text: "白瀬灯は黙って歩いた。\n" }];

const LONG_VALUE =
  "黒髪を腰まで長く伸ばした少女で、いつも赤いリボンを結び、旅の途中で出会った老人から受け取った古い銀の懐中時計を首から下げている";

/** 食い違い（変化かもしれない）と口調の面のある人物 */
function shirase(): Character {
  return {
    ...emptyCharacter("char_001", "白瀬灯"),
    autoGenerated: true,
    role: "案内役",
    appearance: "銀髪の少女",
    appearedChapters: [1, 2, 3, 4, 5],
    speechStyle: "ぶっきらぼうな敬語",
    speechStyleFacets: [
      { value: "ぶっきらぼうな敬語", chapters: [1, 2, 3], evidence: "「そうですか。勝手にしてください」", },
      { value: "くだけた友達口調", chapters: [4, 5], evidence: "「それ、ちょっと貸して。いいでしょ？」" },
    ],
    conflicts: [
      {
        field: "appearance",
        values: ["銀髪の少女", "黒髪の少女", LONG_VALUE],
        chapters: [1, 3, 5],
        note: null,
        observations: [
          { value: "銀髪の少女", chapters: [1], evidence: "銀髪の少女が振り返った。" },
          { value: "黒髪の少女", chapters: [3], evidence: "黒髪の少女は黙っていた。" },
          { value: LONG_VALUE, chapters: [5], evidence: LONG_VALUE },
        ],
      },
    ],
  };
}

async function openPanel(session: E2ESession): Promise<Frame> {
  await session.page.keyboard.press(OPEN_SETTINGS_PRESS);
  let panel: Frame | undefined;
  await waitUntil(async () => (panel = await settingsPanelFrame(session)) !== undefined, "設定資料パネルが開く", 30_000);
  const frame = panel as Frame;
  await waitUntil(async () => (await frame.locator("#list .item").count()) >= 1, "人物が並ぶ", 15_000);
  await frame.locator("#list .item", { hasText: "白瀬灯" }).first().click();
  return frame;
}

describe.skipIf(!lookEnabled)("見た目の写真：設定資料パネル", () => {
  test("変化かもしれない行の値の札と、口調の欄・口調の面", async () => {
    for (const [label, size] of [
      ["広い窓", { width: 1280, height: 900 }],
      ["狭い窓", { width: 900, height: 800 }],
    ] as const) {
      await withVsCode(
        "見た目の写真：設定資料パネル",
        EPISODES,
        async (session) => {
          const { page } = session;
          const frame = await openPanel(session);
          await waitUntil(
            async () => (await frame.locator("#detail .readonly", { hasText: "変化かもしれない" }).count()) > 0,
            "「変化かもしれない」の行が出る",
            15_000
          );
          await clearNotifications(page);
          await frame.evaluate(() => {
            const row = Array.from(document.querySelectorAll("#detail .readonly")).find((node) => (node as HTMLElement).innerText.includes("変化かもしれない"));
            row?.scrollIntoView({ block: "center" });
          });
          await page.waitForTimeout(800);
          await shootPage(page, `408-設定資料パネル-${label}`);
          // 値の札の寸法（行からはみ出していないか）を数字でも残す
          const boxes = await frame.evaluate(() => {
            const row = Array.from(document.querySelectorAll("#detail .readonly")).find((node) => (node as HTMLElement).innerText.includes("変化かもしれない")) as HTMLElement | undefined;
            if (!row) return null;
            const rowBox = row.getBoundingClientRect();
            const buttons = Array.from(row.querySelectorAll("button")).map((button) => {
              const box = button.getBoundingClientRect();
              return { text: (button.textContent ?? "").trim(), left: Math.round(box.left), right: Math.round(box.right), title: button.title.length };
            });
            return { rowLeft: Math.round(rowBox.left), rowRight: Math.round(rowBox.right), scrollWidth: row.scrollWidth, clientWidth: row.clientWidth, buttons };
          });
          await lookNote(`[408] ${label}：札の寸法 ${JSON.stringify(boxes)}`);
          await frame.evaluate(() => {
            const row = Array.from(document.querySelectorAll("#detail .readonly")).find((node) => (node as HTMLElement).innerText.startsWith("口調の面"));
            row?.scrollIntoView({ block: "center" });
          });
          await page.waitForTimeout(400);
          await shootPage(page, `489-設定資料パネル-口調と口調の面-${label}`);
          const speech = await frame.evaluate(() =>
            Array.from(document.querySelectorAll("#detail .readonly, #detail .field, #detail label")).map((node) => (node as HTMLElement).innerText.replace(/\s+/g, " ").trim()).filter((text) => text.includes("口調"))
          );
          await lookNote(`[489] ${label}：口調に触れる行 ${JSON.stringify(speech)}`);
        },
        {
          windowSize: size,
          keybindings: [{ key: OPEN_SETTINGS_KEY, command: "novelai.openSettingsPanel" }],
          prepareWork: async ({ workFolder }) => {
            await writeCharactersTo(defaultCharactersFolder(workFolder), [shirase()]);
          },
        }
      );
    }
  });
});

describe.skipIf(!lookEnabled)("見た目の写真：提案パネル（承認待ちの更新案）", () => {
  test("落とした値を除いた出どころの一行", async () => {
    const current: Character = {
      ...emptyCharacter("char_001", "白瀬灯"),
      autoGenerated: true,
      role: "案内役",
      appearance: "黒髪の少女",
      appearedChapters: [1, 2, 3],
      rejectedValues: [{ field: "appearance", value: "銀髪", chapters: [1], rejectedAt: "2026-10-01T00:00:00.000Z" }],
    };
    const proposed: Character = { ...current, appearance: "銀髪", role: "物語の案内役", rejectedValues: current.rejectedValues };
    await withVsCode(
      "見た目の写真：落とした値の出どころ",
      EPISODES,
      async (session) => {
        const { page } = session;
        await clearNotifications(page);
        await runCommand(page, "設定資料更新分反映");
        let panel: Frame | undefined;
        await waitUntil(
          async () => {
            panel = await proposalPanelFrame(page);
            return panel !== undefined;
          },
          "提案パネルが開く",
          30_000
        );
        await page.waitForTimeout(2500);
        await clearNotifications(page);
        const rows = await (panel as Frame).evaluate(() => (document.body?.innerText ?? "").replace(/\s+/g, " ").slice(0, 600));
        await lookNote(`[352] 提案パネルの字：${rows}`);
        await shootPage(page, "352-提案パネル-落とした値の出どころ");
      },
      {
        windowSize: { width: 1280, height: 800 },
        prepareWork: async ({ workFolder }) => {
          await writeCharactersTo(defaultCharactersFolder(workFolder), [current]);
          const pending = path.join(workFolder, ".aiwriter", "pending-characters");
          await mkdir(pending, { recursive: true });
          await writeFile(
            path.join(pending, "char_001.json"),
            JSON.stringify({ source: "external", reason: "第1話の描写に合わせる", character: proposed }, null, 2),
            "utf8"
          );
        },
      }
    );
  });

  /*
    語り手の取り違えの移す案（設計書6.5.12、0.102.3）。名指しできない案の行に、
    移し先の選び口（「（選んでください）」・候補・外すだけ）が出て、選ぶまで
    「反映する」が押せないことを写す。承認待ちは製品と同じ関数で組む
  */
  test("移す案の行と移し先の選び口", async () => {
    const hero: Character = {
      ...emptyCharacter("char_007", "アジャーノ"),
      role: "冒険者",
      firstPerson: { default: "俺", variants: [] },
      changes: [
        { field: "role", value: "冒険者", chapters: [10], timepointId: null, note: null, evidence: null, source: "extracted" },
        { field: "role", value: "皇子", chapters: [12], timepointId: null, note: null, evidence: null, source: "extracted" },
      ],
      appearedChapters: [10],
    };
    const prince = emptyCharacter("char_016", "殿下");
    const item: NarratorMoveItem = {
      kind: "change",
      label: "役割",
      value: "皇子",
      chapters: [12],
      evidence: null,
      firstPersons: ["余"],
      destination: { kind: "choose", candidates: [{ id: prince.id, name: prince.name }] },
      change: hero.changes[1],
    };
    const payload = buildPendingNarratorMovePayload(hero, item, "2026-10-10T00:00:00.000Z");
    await withVsCode(
      "見た目の写真：移す案の行",
      EPISODES,
      async (session) => {
        const { page } = session;
        await clearNotifications(page);
        await runCommand(page, "設定資料更新分反映");
        let panel: Frame | undefined;
        await waitUntil(
          async () => {
            panel = await proposalPanelFrame(page);
            return panel !== undefined;
          },
          "提案パネルが開く",
          30_000
        );
        await page.waitForTimeout(2500);
        await clearNotifications(page);
        const state = await (panel as Frame).evaluate(() => ({
          text: (document.body?.innerText ?? "").replace(/\s+/g, " ").slice(0, 600),
          select: document.querySelector("select[data-move-for]") !== null,
          applyDisabled:
            (document.querySelector('button[data-action="apply"]') as HTMLButtonElement | null)?.disabled ?? null,
        }));
        await lookNote(
          `[353] 移す案の行：選び口=${state.select} 反映を押せない=${state.applyDisabled} 字：${state.text}`
        );
        await shootPage(page, "353-提案パネル-移す案の行");
      },
      {
        windowSize: { width: 1280, height: 800 },
        prepareWork: async ({ workFolder }) => {
          await writeCharactersTo(defaultCharactersFolder(workFolder), [hero, prince]);
          const pending = path.join(workFolder, ".aiwriter", PENDING_MOVES_DIR);
          await mkdir(pending, { recursive: true });
          await writeFile(
            path.join(pending, pendingNarratorMoveFileName(payload.sourceId, payload.key)),
            JSON.stringify(payload, null, 2),
            "utf8"
          );
        },
      }
    );
  });
});
