import {
  invalid,
  objectValue,
  optionalBoolean,
  optionalEnum,
  optionalNullableString,
  optionalNumberArray,
  optionalString,
  optionalStringArray,
  parseConflicts,
  requireNonEmptyString,
} from "./jsonValidation";
import { parseAiNotes, type AiNote } from "./aiNote";

/**
 * 能力（魔法・超能力・スキル）のデータモデル。
 *
 * ジャンルによって呼び名は変わるが（ファンタジーなら魔法、伝奇なら超能力、
 * 現代ものなら得意なスキル）、「誰が何をできるのか」を作品を通じて
 * 一貫させる必要がある点は共通するため、同じ構造で扱う。
 *
 * 能力の定義（効果・制約・代償）はここに、人物ごとの保有状況は
 * Character.abilities に置く。同じ能力を複数人が使う場合に定義が重複すると、
 * 設定変更のたびに全員分を直すことになり、食い違いの温床になるため。
 */

/** 習得の度合い。物語中で変化しうる */
export type AbilityMastery = "習得済み" | "習得中" | "未習得" | "喪失";

export const ABILITY_MASTERIES: readonly AbilityMastery[] = [
  "習得済み",
  "習得中",
  "未習得",
  "喪失",
];

/** ある人物が持つ能力。定義そのものではなく、その人物固有の事情を持つ */
export interface CharacterAbility {
  /** abilities.json の項目を指す。定義が未登録なら null */
  abilityId: string | null;
  /** 本文に出てきた表記 */
  name: string;
  mastery: AbilityMastery;
  /** その人物に固有の事情（「第12話で暴走」等） */
  note: string | null;
  firstChapter: number | null;
  appearedChapters: number[];
  evidence: string | null;
  /** AIが自動生成したか。false なら作者が確定させたもの */
  autoGenerated: boolean;
}

/** 能力の定義 */
export interface Ability {
  schemaVersion: string;
  id: string;
  name: string;
  /** 同一能力の別表記。登場人物の aliases と同じ扱い */
  aliases: string[];
  /** ルビ。設定資料エクスポートで必要になる */
  reading: string | null;
  /** 一覧で名前の下に出す短い紹介。上限は SUMMARY_MAX_CHARS */
  summary: string | null;
  /** 作品側の分類語をそのまま使う（「光属性魔法」等） */
  category: string | null;
  description: string | null;
  /** 発動に必要な代償 */
  cost: string | null;
  /** 使えない条件 */
  limitation: string | null;
  /** この能力を持つ人物のid */
  userIds: string[];
  /** 人物名。idが未解決でも資料として読めるように持つ */
  userNames: string[];
  appearedChapters: number[];
  status: "登場済み" | "未登場";
  spoilerLevel: "public" | "staff_only" | "author_only";
  evidence: string | null;
  /** 作者メモ。AI再生成でも絶対に上書きしない */
  authorNotes: string;
  /** 資料にのみ出力する補足 */
  exportNote: string;
  autoGenerated: boolean;
  /** 設定と本文の食い違い。作者の判断を待つ */
  conflicts: Array<{
    field: string;
    values: string[];
    chapters: number[];
    note: string | null;
  }>;
  /** AIの掘り下げメモ。作者が承認したものだけが入る */
  aiNotes: AiNote[];
  updatedAt: string;
}

/**
 * 能力体系そのものの設定。
 *
 * 総称を可変にするのは、現代ものを書いているのに
 * 「魔法一覧」と表示されるのを避けるため。
 */
export interface AbilitySystem {
  schemaVersion: string;
  /** 「魔法」「超能力」「スキル」「異能」など作品に合わせた総称 */
  abilityTerm: string;
  description: string | null;
  /** 体系全体に効く規則（「詠唱には最低3秒を要する」等） */
  rules: string[];
  authorNotes: string;
  autoGenerated: boolean;
  updatedAt: string;
}

export const ABILITY_SCHEMA_VERSION = "0.1";

/** 総称を推定できなかった場合に使う。作者が変更できる */
export const DEFAULT_ABILITY_TERM = "能力";

export function emptyAbility(id: string, name: string): Ability {
  return {
    schemaVersion: ABILITY_SCHEMA_VERSION,
    id,
    name,
    aliases: [],
    reading: null,
    summary: null,
    category: null,
    description: null,
    cost: null,
    limitation: null,
    userIds: [],
    userNames: [],
    appearedChapters: [],
    status: "登場済み",
    spoilerLevel: "public",
    evidence: null,
    authorNotes: "",
    exportNote: "",
    autoGenerated: true,
    conflicts: [],
    aiNotes: [],
    // 永続化境界で保存時刻を付ける。純粋な生成・マージ結果へ壁時計を混ぜない。
    updatedAt: "",
  };
}

export function emptyAbilitySystem(): AbilitySystem {
  return {
    schemaVersion: ABILITY_SCHEMA_VERSION,
    abilityTerm: DEFAULT_ABILITY_TERM,
    description: null,
    rules: [],
    authorNotes: "",
    autoGenerated: true,
    updatedAt: "",
  };
}

/** abil_001_灯火.json の形式にする */
export function abilityFileName(ability: Ability): string {
  const safeName = ability.name
    .replace(/[/\\:*?"<>|\s]/g, "")
    .slice(0, 30);
  return safeName ? `${ability.id}_${safeName}.json` : `${ability.id}.json`;
}

/** 新しいIDを採番する */
export function nextAbilityId(existing: Ability[]): string {
  let max = 0;
  for (const ability of existing) {
    const matched = ability.id.match(/^abil_(\d+)$/);
    if (!matched) continue;
    const value = parseInt(matched[1], 10);
    if (value > max) max = value;
  }
  return `abil_${String(max + 1).padStart(3, "0")}`;
}

/** 旧バージョンや手書きJSONでも落ちないよう欠損を補う */
export function normalizeAbility(raw: Partial<Ability>): Ability {
  const base = emptyAbility(raw.id ?? "abil_unknown", raw.name ?? "名称不明");
  return {
    ...base,
    ...raw,
    aliases: raw.aliases ?? [],
    userIds: raw.userIds ?? [],
    userNames: raw.userNames ?? [],
    appearedChapters: raw.appearedChapters ?? [],
    conflicts: raw.conflicts ?? [],
    aiNotes: raw.aiNotes ?? [],
    authorNotes: raw.authorNotes ?? "",
    exportNote: raw.exportNote ?? "",
  } as Ability;
}

/** 表記ゆれを吸収して同一能力を判定する */
export function normalizeAbilityName(name: string): string {
  return name
    .replace(/[\s　・･]/g, "")
    .replace(/[０-９]/g, (c) => String.fromCharCode(c.charCodeAt(0) - 0xfee0))
    .toLowerCase();
}

/** 作者が編集できるJSONを検証してから既定値を補う。 */
export function parseAbility(raw: unknown): Ability {
  const value = objectValue(raw, "ability");
  requireNonEmptyString(value.id, "id");
  if (!/^abil_\d+$/.test(value.id as string)) invalid("id");
  requireNonEmptyString(value.name, "name");

  optionalString(value.schemaVersion, "schemaVersion");
  optionalStringArray(value.aliases, "aliases");
  for (const key of [
    "reading",
    "summary",
    "category",
    "description",
    "cost",
    "limitation",
    "evidence",
  ]) {
    optionalNullableString(value[key], key);
  }
  optionalStringArray(value.userIds, "userIds");
  optionalStringArray(value.userNames, "userNames");
  optionalNumberArray(value.appearedChapters, "appearedChapters");
  optionalEnum(value.status, "status", ["登場済み", "未登場"]);
  optionalEnum(value.spoilerLevel, "spoilerLevel", [
    "public",
    "staff_only",
    "author_only",
  ]);
  optionalString(value.authorNotes, "authorNotes");
  optionalString(value.exportNote, "exportNote");
  optionalBoolean(value.autoGenerated, "autoGenerated");
  optionalString(value.updatedAt, "updatedAt");

  const conflicts = parseConflicts(value.conflicts);

  return normalizeAbility({
    ...value,
    id: value.id as string,
    name: value.name as string,
    conflicts,
    aiNotes: parseAiNotes(value.aiNotes),
  } as Partial<Ability>);
}

/** 能力体系の設定を検証する */
export function parseAbilitySystem(raw: unknown): AbilitySystem {
  const value = objectValue(raw, "abilitySystem");
  optionalString(value.schemaVersion, "schemaVersion");
  optionalString(value.abilityTerm, "abilityTerm");
  optionalNullableString(value.description, "description");
  optionalStringArray(value.rules, "rules");
  optionalString(value.authorNotes, "authorNotes");
  optionalBoolean(value.autoGenerated, "autoGenerated");
  optionalString(value.updatedAt, "updatedAt");

  const base = emptyAbilitySystem();
  return {
    ...base,
    ...value,
    abilityTerm:
      typeof value.abilityTerm === "string" && value.abilityTerm.trim()
        ? value.abilityTerm
        : base.abilityTerm,
    rules: (value.rules as string[] | undefined) ?? [],
    authorNotes: (value.authorNotes as string | undefined) ?? "",
  } as AbilitySystem;
}
