
/** 呼称の1形態 */
export interface AddressForm {
  term: string;
  category: string | null;
  context: string | null;
  firstChapter: number | null;
  lastChapter: number | null;
  status: "current" | "past";
  evidence: string | null;
}

/** ある人物が特定の相手を呼ぶ呼称 */
export interface AddressTerm {
  targetName: string;
  targetId: string | null;
  forms: AddressForm[];
  authorLocked: boolean;
}

export interface FirstPersonVariant {
  form: string;
  context: string | null;
  chapters: number[];
  evidence: string | null;
}

export interface CharacterPhysical {
  age: string | null;
  height: string | null;
  build: string | null;
  hair: string | null;
  eyes: string | null;
  skin: string | null;
  distinctive: string | null;
  clothing: string | null;
}

export interface Character {
  schemaVersion: string;
  id: string;
  name: string;
  aliases: string[];
  /** 読み仮名。設定資料エクスポートで必要になる */
  reading: string | null;
  romaji: string | null;
  icon: string | null;
  iconSource: "external" | "generated" | "none";
  role: string | null;
  personality: string | null;
  appearance: string | null;
  physical: CharacterPhysical | null;
  firstPerson: {
    default: string | null;
    variants: FirstPersonVariant[];
  };
  defaultSecondPerson: string | null;
  addressTerms: AddressTerm[];
  relations: Array<{ name: string; relation: string }>;
  appearedChapters: number[];
  status: "登場済み" | "未登場";
  /** 公開範囲。設定資料エクスポート時のフィルタに使う */
  spoilerLevel: "public" | "staff_only" | "author_only";
  /** 作者メモ。AI再生成でも絶対に上書きしない */
  authorNotes: string;
  /** 資料にのみ出力する補足 */
  exportNote: string;
  /** AIが自動生成したレコードか。false なら作者が作成・確定させたもの */
  autoGenerated: boolean;
  /**
   * 集団名詞・汎用役職名（「取調官たち」「冒険者」等）か。
   * ネームドキャラと区別して一覧から除外・折りたたむ用途に使う。
   * AIが true と判定した場合のみ立てる。作者が手動で戻すことも想定する。
   */
  isMob: boolean;
  /** 抽出根拠 */
  evidence: string | null;
  /** 設定と本文の食い違い。作者の判断を待つ */
  conflicts: Array<{
    field: string;
    values: string[];
    chapters: number[];
    note: string | null;
  }>;
  updatedAt: string;
}

export const CHARACTER_SCHEMA_VERSION = "0.1";

export function emptyCharacter(id: string, name: string): Character {
  return {
    schemaVersion: CHARACTER_SCHEMA_VERSION,
    id,
    name,
    aliases: [],
    reading: null,
    romaji: null,
    icon: null,
    iconSource: "none",
    role: null,
    personality: null,
    appearance: null,
    physical: null,
    firstPerson: { default: null, variants: [] },
    defaultSecondPerson: null,
    addressTerms: [],
    relations: [],
    appearedChapters: [],
    status: "登場済み",
    spoilerLevel: "public",
    authorNotes: "",
    exportNote: "",
    autoGenerated: true,
    isMob: false,
    evidence: null,
    conflicts: [],
    updatedAt: new Date().toISOString(),
  };
}

/** char_001_月島灯.json の形式にする */
export function characterFileName(c: Character): string {
  const safeName = c.name
    .replace(/[/\\:*?"<>|\s]/g, "")
    .slice(0, 30);
  return safeName ? `${c.id}_${safeName}.json` : `${c.id}.json`;
}

/** 旧バージョンや手書きJSONでも落ちないよう欠損を補う */
export function normalizeCharacter(raw: Partial<Character>): Character {
  const base = emptyCharacter(raw.id ?? "char_unknown", raw.name ?? "名称不明");
  return {
    ...base,
    ...raw,
    aliases: raw.aliases ?? [],
    firstPerson: raw.firstPerson ?? base.firstPerson,
    addressTerms: raw.addressTerms ?? [],
    relations: raw.relations ?? [],
    appearedChapters: raw.appearedChapters ?? [],
    conflicts: raw.conflicts ?? [],
    authorNotes: raw.authorNotes ?? "",
    exportNote: raw.exportNote ?? "",
  } as Character;
}

/** 新しいIDを採番する */
export function nextCharacterId(existing: Character[]): string {
  let max = 0;
  for (const c of existing) {
    const m = c.id.match(/^char_(\d+)$/);
    if (m) {
      const n = parseInt(m[1], 10);
      if (n > max) max = n;
    }
  }
  return `char_${String(max + 1).padStart(3, "0")}`;
}
