import {
  ABILITY_MASTERIES,
  type AbilityMastery,
  type CharacterAbility,
} from "./ability";

/** 呼称の1形態 */
export interface AddressForm {
  term: string;
  category: string | null;
  context: string | null;
  firstChapter: number | null;
  lastChapter: number | null;
  status: "current" | "past";
  evidence: string | null;
}

/** ある人物が特定の相手を呼ぶ呼称 */
export interface AddressTerm {
  targetName: string;
  targetId: string | null;
  forms: AddressForm[];
  authorLocked: boolean;
}

export interface FirstPersonVariant {
  form: string;
  context: string | null;
  chapters: number[];
  evidence: string | null;
}

export interface CharacterPhysical {
  age: string | null;
  height: string | null;
  build: string | null;
  hair: string | null;
  eyes: string | null;
  skin: string | null;
  distinctive: string | null;
  clothing: string | null;
}

export interface Character {
  schemaVersion: string;
  id: string;
  name: string;
  aliases: string[];
  /** 読み仮名。設定資料エクスポートで必要になる */
  reading: string | null;
  romaji: string | null;
  icon: string | null;
  iconSource: "external" | "generated" | "none";
  role: string | null;
  personality: string | null;
  appearance: string | null;
  physical: CharacterPhysical | null;
  firstPerson: {
    default: string | null;
    variants: FirstPersonVariant[];
  };
  defaultSecondPerson: string | null;
  addressTerms: AddressTerm[];
  relations: Array<{ name: string; relation: string }>;
  /**
   * この人物が持つ能力（魔法・超能力・スキル）。
   * 能力の定義そのものは abilities.json 側に置き、
   * ここには習得状況などその人物固有の事情だけを持つ。
   */
  abilities: CharacterAbility[];
  appearedChapters: number[];
  status: "登場済み" | "未登場";
  /** 公開範囲。設定資料エクスポート時のフィルタに使う */
  spoilerLevel: "public" | "staff_only" | "author_only";
  /** 作者メモ。AI再生成でも絶対に上書きしない */
  authorNotes: string;
  /** 資料にのみ出力する補足 */
  exportNote: string;
  /** AIが自動生成したレコードか。false なら作者が作成・確定させたもの */
  autoGenerated: boolean;
  /**
   * 集団名詞・汎用役職名（「取調官たち」「冒険者」等）か。
   * ネームドキャラと区別して一覧から除外・折りたたむ用途に使う。
   * AIが true と判定した場合のみ立てる。作者が手動で戻すことも想定する。
   */
  isMob: boolean;
  /** 抽出根拠 */
  evidence: string | null;
  /** 設定と本文の食い違い。作者の判断を待つ */
  conflicts: Array<{
    field: string;
    values: string[];
    chapters: number[];
    note: string | null;
  }>;
  updatedAt: string;
}

export const CHARACTER_SCHEMA_VERSION = "0.1";

export function emptyCharacter(id: string, name: string): Character {
  return {
    schemaVersion: CHARACTER_SCHEMA_VERSION,
    id,
    name,
    aliases: [],
    reading: null,
    romaji: null,
    icon: null,
    iconSource: "none",
    role: null,
    personality: null,
    appearance: null,
    physical: null,
    firstPerson: { default: null, variants: [] },
    defaultSecondPerson: null,
    addressTerms: [],
    relations: [],
    abilities: [],
    appearedChapters: [],
    status: "登場済み",
    spoilerLevel: "public",
    authorNotes: "",
    exportNote: "",
    autoGenerated: true,
    isMob: false,
    evidence: null,
    conflicts: [],
    // 永続化境界で保存時刻を付ける。純粋な生成・マージ結果へ壁時計を混ぜない。
    updatedAt: "",
  };
}

/** char_001_月島灯.json の形式にする */
export function characterFileName(c: Character): string {
  const safeName = c.name
    .replace(/[/\\:*?"<>|\s]/g, "")
    .slice(0, 30);
  return safeName ? `${c.id}_${safeName}.json` : `${c.id}.json`;
}

/** 旧バージョンや手書きJSONでも落ちないよう欠損を補う */
export function normalizeCharacter(raw: Partial<Character>): Character {
  const base = emptyCharacter(raw.id ?? "char_unknown", raw.name ?? "名称不明");
  return {
    ...base,
    ...raw,
    aliases: raw.aliases ?? [],
    firstPerson: raw.firstPerson ?? base.firstPerson,
    addressTerms: raw.addressTerms ?? [],
    relations: raw.relations ?? [],
    abilities: raw.abilities ?? [],
    appearedChapters: raw.appearedChapters ?? [],
    conflicts: raw.conflicts ?? [],
    authorNotes: raw.authorNotes ?? "",
    exportNote: raw.exportNote ?? "",
  } as Character;
}

/** 作者が編集できるJSONを検証してから既定値を補う。 */
export function parseCharacter(raw: unknown): Character {
  const value = objectValue(raw, "character");
  requireNonEmptyString(value.id, "id");
  if (!/^char_\d+$/.test(value.id as string)) invalid("id");
  requireNonEmptyString(value.name, "name");

  optionalString(value.schemaVersion, "schemaVersion");
  optionalStringArray(value.aliases, "aliases");
  for (const key of [
    "reading", "romaji", "icon", "role", "personality", "appearance",
    "defaultSecondPerson", "evidence",
  ]) {
    optionalNullableString(value[key], key);
  }
  optionalEnum(value.iconSource, "iconSource", ["external", "generated", "none"]);
  optionalEnum(value.status, "status", ["登場済み", "未登場"]);
  optionalEnum(value.spoilerLevel, "spoilerLevel", ["public", "staff_only", "author_only"]);
  optionalString(value.authorNotes, "authorNotes");
  optionalString(value.exportNote, "exportNote");
  optionalBoolean(value.autoGenerated, "autoGenerated");
  optionalBoolean(value.isMob, "isMob");
  optionalString(value.updatedAt, "updatedAt");
  optionalNumberArray(value.appearedChapters, "appearedChapters");

  let physical: CharacterPhysical | null | undefined;
  if (value.physical !== undefined) {
    if (value.physical === null) {
      physical = null;
    } else {
      const item = objectValue(value.physical, "physical");
      const fields = ["age", "height", "build", "hair", "eyes", "skin", "distinctive", "clothing"] as const;
      for (const field of fields) optionalNullableString(item[field], `physical.${field}`);
      physical = Object.fromEntries(fields.map((field) => [field, item[field] ?? null])) as unknown as CharacterPhysical;
    }
  }

  let firstPerson: Character["firstPerson"] | undefined;
  if (value.firstPerson !== undefined) {
    const item = objectValue(value.firstPerson, "firstPerson");
    optionalNullableString(item.default, "firstPerson.default");
    if (item.variants !== undefined && !Array.isArray(item.variants)) invalid("firstPerson.variants");
    firstPerson = {
      default: (item.default as string | null | undefined) ?? null,
      variants: (item.variants ?? []).map((entry, index) => {
        const variant = objectValue(entry, `firstPerson.variants[${index}]`);
        requireNonEmptyString(variant.form, `firstPerson.variants[${index}].form`);
        optionalNullableString(variant.context, `firstPerson.variants[${index}].context`);
        optionalNumberArray(variant.chapters, `firstPerson.variants[${index}].chapters`);
        optionalNullableString(variant.evidence, `firstPerson.variants[${index}].evidence`);
        return {
          form: variant.form as string,
          context: (variant.context as string | null | undefined) ?? null,
          chapters: (variant.chapters as number[] | undefined) ?? [],
          evidence: (variant.evidence as string | null | undefined) ?? null,
        };
      }),
    };
  }

  const addressTerms = optionalObjectArray(value.addressTerms, "addressTerms", (entry, path) => {
    requireNonEmptyString(entry.targetName, `${path}.targetName`);
    optionalNullableString(entry.targetId, `${path}.targetId`);
    optionalBoolean(entry.authorLocked, `${path}.authorLocked`);
    if (entry.forms !== undefined && !Array.isArray(entry.forms)) invalid(`${path}.forms`);
    return {
      targetName: entry.targetName as string,
      targetId: (entry.targetId as string | null | undefined) ?? null,
      forms: (entry.forms ?? []).map((rawForm, index) => {
        const form = objectValue(rawForm, `${path}.forms[${index}]`);
        requireNonEmptyString(form.term, `${path}.forms[${index}].term`);
        optionalNullableString(form.category, `${path}.forms[${index}].category`);
        optionalNullableString(form.context, `${path}.forms[${index}].context`);
        optionalNullableNumber(form.firstChapter, `${path}.forms[${index}].firstChapter`);
        optionalNullableNumber(form.lastChapter, `${path}.forms[${index}].lastChapter`);
        optionalEnum(form.status, `${path}.forms[${index}].status`, ["current", "past"]);
        optionalNullableString(form.evidence, `${path}.forms[${index}].evidence`);
        return {
          term: form.term as string,
          category: (form.category as string | null | undefined) ?? null,
          context: (form.context as string | null | undefined) ?? null,
          firstChapter: (form.firstChapter as number | null | undefined) ?? null,
          lastChapter: (form.lastChapter as number | null | undefined) ?? null,
          status: (form.status as AddressForm["status"] | undefined) ?? "current",
          evidence: (form.evidence as string | null | undefined) ?? null,
        };
      }),
      authorLocked: (entry.authorLocked as boolean | undefined) ?? false,
    };
  });

  const relations = optionalObjectArray(value.relations, "relations", (entry, path) => {
    requireNonEmptyString(entry.name, `${path}.name`);
    requireNonEmptyString(entry.relation, `${path}.relation`);
    return { name: entry.name as string, relation: entry.relation as string };
  });
  const abilities = optionalObjectArray(value.abilities, "abilities", (entry, path) => {
    requireNonEmptyString(entry.name, `${path}.name`);
    optionalNullableString(entry.abilityId, `${path}.abilityId`);
    optionalNullableString(entry.note, `${path}.note`);
    optionalNullableString(entry.evidence, `${path}.evidence`);
    optionalEnum(entry.mastery, `${path}.mastery`, [...ABILITY_MASTERIES]);
    optionalNumberArray(entry.appearedChapters, `${path}.appearedChapters`);
    if (
      entry.firstChapter !== undefined &&
      entry.firstChapter !== null &&
      !Number.isSafeInteger(entry.firstChapter)
    ) {
      invalid(`${path}.firstChapter`);
    }
    optionalBoolean(entry.autoGenerated, `${path}.autoGenerated`);
    return {
      abilityId: (entry.abilityId as string | null | undefined) ?? null,
      name: entry.name as string,
      mastery: (entry.mastery as AbilityMastery | undefined) ?? "習得済み",
      note: (entry.note as string | null | undefined) ?? null,
      firstChapter: (entry.firstChapter as number | null | undefined) ?? null,
      appearedChapters: (entry.appearedChapters as number[] | undefined) ?? [],
      evidence: (entry.evidence as string | null | undefined) ?? null,
      autoGenerated: (entry.autoGenerated as boolean | undefined) ?? true,
    };
  });
  const conflicts = optionalObjectArray(value.conflicts, "conflicts", (entry, path) => {
    requireNonEmptyString(entry.field, `${path}.field`);
    optionalStringArray(entry.values, `${path}.values`);
    optionalNumberArray(entry.chapters, `${path}.chapters`);
    optionalNullableString(entry.note, `${path}.note`);
    return {
      field: entry.field as string,
      values: (entry.values as string[] | undefined) ?? [],
      chapters: (entry.chapters as number[] | undefined) ?? [],
      note: (entry.note as string | null | undefined) ?? null,
    };
  });

  return normalizeCharacter({
    ...value,
    id: value.id as string,
    name: value.name as string,
    physical: physical ?? null,
    firstPerson,
    addressTerms,
    relations,
    abilities,
    conflicts,
  } as Partial<Character>);
}

function invalid(path: string): never {
  throw new Error(`${path} の形式が正しくありません。`);
}

function objectValue(value: unknown, path: string): Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) invalid(path);
  return value as Record<string, unknown>;
}

function requireNonEmptyString(value: unknown, path: string): void {
  if (typeof value !== "string" || value.trim().length === 0) invalid(path);
}

function optionalString(value: unknown, path: string): void {
  if (value !== undefined && typeof value !== "string") invalid(path);
}

function optionalNullableString(value: unknown, path: string): void {
  if (value !== undefined && value !== null && typeof value !== "string") invalid(path);
}

function optionalBoolean(value: unknown, path: string): void {
  if (value !== undefined && typeof value !== "boolean") invalid(path);
}

function optionalNullableNumber(value: unknown, path: string): void {
  if (value !== undefined && value !== null && (!Number.isInteger(value) || (value as number) < 0)) invalid(path);
}

function optionalStringArray(value: unknown, path: string): void {
  if (value !== undefined && (!Array.isArray(value) || value.some((item) => typeof item !== "string"))) invalid(path);
}

function optionalNumberArray(value: unknown, path: string): void {
  if (value !== undefined && (!Array.isArray(value) || value.some((item) => !Number.isInteger(item) || item < 0))) invalid(path);
}

function optionalEnum(value: unknown, path: string, allowed: readonly string[]): void {
  if (value !== undefined && (typeof value !== "string" || !allowed.includes(value))) invalid(path);
}

function optionalObjectArray<T>(
  value: unknown,
  path: string,
  parse: (entry: Record<string, unknown>, path: string) => T
): T[] | undefined {
  if (value === undefined) return undefined;
  if (!Array.isArray(value)) invalid(path);
  return value.map((entry, index) => parse(objectValue(entry, `${path}[${index}]`), `${path}[${index}]`));
}

/** 新しいIDを採番する */
export function nextCharacterId(existing: Character[]): string {
  let max = 0;
  for (const c of existing) {
    const m = c.id.match(/^char_(\d+)$/);
    if (m) {
      const n = parseInt(m[1], 10);
      if (n > max) max = n;
    }
  }
  return `char_${String(max + 1).padStart(3, "0")}`;
}
