import {
  invalid,
  objectValue,
  optionalBoolean,
  optionalString,
  requireNonEmptyString,
} from "./jsonValidation";

/**
 * 作者が足す項目の定義。
 *
 * 作品によって必要な項目は違う（誕生日、身長、好きな食べ物、家紋…）。
 * すべてを最初から用意することはできないので、作者が足せるようにする。
 *
 * 定義は作品ごとに持ち、**全人物に同じ項目が並ぶ**。人物ごとに違う項目にすると
 * 資料として見比べられなくなるため。値が入っていない人物では表示を省く。
 */

export interface CustomFieldDefinition {
  /** 保存に使うキー。作者には見せない */
  key: string;
  /** 画面と資料に出す見出し */
  label: string;
  /** AIに何を書くべきか伝える説明。空でもよい */
  hint: string;
  /** 長文になる項目か。入力欄の高さに使う */
  multiline: boolean;
}

/**
 * 項目を足せる資料の種類（作者の裁定、2026-09-23 問11 B）。
 *
 * 設定資料パネルの種類（`core/settingsSummary.ts` の `SettingsKind`）と
 * 同じ並び。**models は core を読めない**ので、ここにも持つ
 * （型が食い違えば `settingsPanel.ts` の受け渡しで型検査が落ちる）。
 */
export type CustomFieldKind =
  | "character"
  | "ability"
  | "organization"
  | "location"
  | "world";

/** 人物以外の種類。定義は `byKind` に置く */
export type OtherCustomFieldKind = Exclude<CustomFieldKind, "character">;

export const OTHER_CUSTOM_FIELD_KINDS: readonly OtherCustomFieldKind[] = [
  "ability",
  "organization",
  "location",
  "world",
];

export interface CustomFieldSet {
  schemaVersion: string;
  /**
   * **人物の**項目。名前は人物だけだったころのまま変えない——
   * 作者の手元の `custom_fields.json` はこの形で書かれており、
   * 置き場所を変えると足した項目がまるごと消えて見える。
   */
  fields: CustomFieldDefinition[];
  /**
   * 人物以外の項目（2026-09-23〜）。種類ごとに持つ。
   *
   * 書き出すときは**中身のある種類だけ**を書く（`customFieldSetToJson`）。
   * 人物だけの作品では、これまでと1文字も違わないファイルになる。
   */
  byKind: Partial<Record<OtherCustomFieldKind, CustomFieldDefinition[]>>;
}

export const CUSTOM_FIELD_SCHEMA_VERSION = "0.1";

/** 一度に扱える項目数の上限。増やしすぎると入力も資料も破綻する */
export const MAX_CUSTOM_FIELDS = 20;

/**
 * 標準の項目と衝突しないキーにする。
 * 衝突すると、追加項目の値が標準項目を隠してしまう。
 */
const RESERVED_KEYS = new Set([
  "id", "name", "aliases", "reading", "romaji", "icon", "iconSource",
  "summary", "affiliation", "role", "personality", "appearance", "physical",
  "firstPerson", "defaultSecondPerson", "addressTerms", "relations",
  "abilities", "appearedChapters", "status", "spoilerLevel", "gender",
  "authorNotes", "exportNote", "autoGenerated", "isMob", "evidence",
  "conflicts", "aiNotes", "updatedAt", "schemaVersion", "customFields",
  // 人物以外の資料の既定の項目（2026-09-23〜、種類ごとに項目を足せるようにした）
  "region", "parent", "category", "description", "cost", "limitation",
  "userIds", "userNames",
]);

export function emptyCustomFieldSet(): CustomFieldSet {
  return { schemaVersion: CUSTOM_FIELD_SCHEMA_VERSION, fields: [], byKind: {} };
}

/** その種類の項目の定義 */
export function fieldsFor(
  set: CustomFieldSet,
  kind: CustomFieldKind
): CustomFieldDefinition[] {
  if (kind === "character") return set.fields;
  return set.byKind[kind] ?? [];
}

/** その種類の定義だけを差し替えた集合を返す。ほかの種類には触らない */
export function withFieldsFor(
  set: CustomFieldSet,
  kind: CustomFieldKind,
  fields: CustomFieldDefinition[]
): CustomFieldSet {
  if (kind === "character") return { ...set, fields };
  const byKind = { ...set.byKind };
  if (fields.length > 0) {
    byKind[kind] = fields;
  } else {
    delete byKind[kind];
  }
  return { ...set, byKind };
}

/**
 * 保存する形。**中身の無い種類は書かない**——人物だけの作品では、
 * `byKind` を持たないこれまでの形のまま保たれる。
 */
export function customFieldSetToJson(set: CustomFieldSet): {
  schemaVersion: string;
  fields: CustomFieldDefinition[];
  byKind?: Partial<Record<OtherCustomFieldKind, CustomFieldDefinition[]>>;
} {
  const byKind: Partial<Record<OtherCustomFieldKind, CustomFieldDefinition[]>> =
    {};
  for (const kind of OTHER_CUSTOM_FIELD_KINDS) {
    const fields = set.byKind[kind];
    if (fields && fields.length > 0) byKind[kind] = fields;
  }
  return {
    schemaVersion: CUSTOM_FIELD_SCHEMA_VERSION,
    fields: set.fields,
    ...(Object.keys(byKind).length > 0 ? { byKind } : {}),
  };
}

/**
 * 見出しから保存キーを作る。
 *
 * 日本語の見出しをそのままキーにするとJSONが読みづらく、
 * 見出しを直したときにキーまで変わって値が失われる。
 * 連番のキーにして、見出しは別に持つ。
 */
export function nextCustomFieldKey(existing: CustomFieldDefinition[]): string {
  let max = 0;
  for (const field of existing) {
    const matched = field.key.match(/^field_(\d+)$/);
    if (!matched) continue;
    const value = parseInt(matched[1], 10);
    if (value > max) max = value;
  }
  return `field_${String(max + 1).padStart(3, "0")}`;
}

/** 追加できるか。できない場合は理由を返す */
export function validateNewField(
  existing: CustomFieldDefinition[],
  label: string
): string | undefined {
  const trimmed = label.trim();
  if (!trimmed) return "項目名を入力してください。";
  if (trimmed.length > 20) return "項目名は20字以内にしてください。";
  if (RESERVED_KEYS.has(trimmed)) {
    return `「${trimmed}」は既定の項目名と重なります。別の名前にしてください。`;
  }
  if (existing.some((field) => field.label === trimmed)) {
    return `「${trimmed}」はすでにあります。`;
  }
  if (existing.length >= MAX_CUSTOM_FIELDS) {
    return `項目は${MAX_CUSTOM_FIELDS}個までです。`;
  }
  return undefined;
}

/** 作者が編集できるJSONを検証する。壊れていれば例外を投げ、勝手に直さない */
export function parseCustomFieldSet(raw: unknown): CustomFieldSet {
  const value = objectValue(raw, "customFields");
  optionalString(value.schemaVersion, "schemaVersion");

  const fields = parseDefinitions(value.fields, "fields");

  const byKind: CustomFieldSet["byKind"] = {};
  if (value.byKind !== undefined) {
    const kinds = objectValue(value.byKind, "byKind");
    for (const [kind, entries] of Object.entries(kinds)) {
      // **知らない種類は捨てずに止める。** 綴りを誤った種類を黙って
      // 読み飛ばすと、作者が足した項目が消えたように見え、次の保存で本当に消える
      if (!(OTHER_CUSTOM_FIELD_KINDS as readonly string[]).includes(kind)) {
        invalid(`byKind（種類「${kind}」は分かりません）`);
      }
      const parsed = parseDefinitions(entries, `byKind.${kind}`);
      if (parsed.length > 0) byKind[kind as OtherCustomFieldKind] = parsed;
    }
  }

  return { schemaVersion: CUSTOM_FIELD_SCHEMA_VERSION, fields, byKind };
}

/**
 * 1つの種類の定義の並びを検証する。
 *
 * **キーの重複は種類の中だけで見る。** 値は種類ごとに別のレコードへ入るので、
 * 人物の `field_001` と場所の `field_001` はぶつからない。
 */
function parseDefinitions(
  raw: unknown,
  path: string
): CustomFieldDefinition[] {
  if (raw !== undefined && !Array.isArray(raw)) {
    invalid(path);
  }

  const fields = ((raw as unknown[] | undefined) ?? []).map((entry, index) => {
    const item = objectValue(entry, `${path}[${index}]`);
    requireNonEmptyString(item.key, `${path}[${index}].key`);
    requireNonEmptyString(item.label, `${path}[${index}].label`);
    optionalString(item.hint, `${path}[${index}].hint`);
    optionalBoolean(item.multiline, `${path}[${index}].multiline`);
    return {
      key: item.key as string,
      label: item.label as string,
      hint: (item.hint as string | undefined) ?? "",
      multiline: (item.multiline as boolean | undefined) ?? false,
    };
  });

  const keys = new Set<string>();
  for (const field of fields) {
    if (keys.has(field.key)) invalid(`${path}（キー「${field.key}」が重複）`);
    keys.add(field.key);
  }
  return fields;
}

/**
 * 人物レコードが持つ追加項目の値を検証する。
 * 値が空のものは持たない（未設定と区別する必要がないため）。
 */
export function parseCustomFieldValues(
  raw: unknown,
  path = "customFields"
): Record<string, string> {
  if (raw === undefined || raw === null) return {};
  const value = objectValue(raw, path);

  const result: Record<string, string> = {};
  for (const [key, entry] of Object.entries(value)) {
    if (entry === null || entry === undefined) continue;
    if (typeof entry !== "string") invalid(`${path}.${key}`);
    const text = entry.trim();
    if (text) result[key] = text;
  }
  return result;
}

/**
 * 人物以外のレコードが持つ追加項目の値（2026-09-23〜）。
 *
 * **値が1つも無ければ undefined を返す**——呼び出し側はキーごと持たない。
 * 人物と違い、これまでの場所・組織のファイルには `customFields` が無い。
 * 空の `{}` を持たせると、作者が何も足していない作品でも、保存のたびに
 * ファイルが1行ずつ書き換わって同期の差分に出る。
 */
export function parseOptionalCustomFieldValues(
  raw: unknown
): Record<string, string> | undefined {
  const values = parseCustomFieldValues(raw);
  return Object.keys(values).length > 0 ? values : undefined;
}

/**
 * 追加項目の値を、あるときだけ持たせる。
 *
 * 空になったらキーごと外す（上の `parseOptionalCustomFieldValues` と同じ理由）。
 */
export function withOptionalCustomFields<
  T extends { customFields?: Record<string, string> },
>(record: T, values: Record<string, string> | undefined): T {
  const copy = { ...record };
  if (values && Object.keys(values).length > 0) {
    copy.customFields = values;
  } else {
    delete copy.customFields;
  }
  return copy;
}
