import {
  invalid,
  objectValue,
  optionalBoolean,
  optionalEnum,
  optionalNullableNumber,
  optionalString,
  requireNonEmptyString,
} from "./jsonValidation";

/**
 * 伏線のデータモデル（設計書6.35.1）。
 *
 * **設定資料の6番目の種別にはしない。** 設定資料は「名前を持つもの」
 * （人物・能力・場所・組織・世界観）の記録だが、伏線は
 * 「張った箇所 → 回収した箇所」という対の形をしている。
 * 無理に同じ画面へ載せるより、軽い台帳から始めて使用感を見る。
 *
 * 1件1ファイルにするのは人物と同じ理由（Gitの競合を避ける）。
 */

/**
 * いまの扱い。
 *
 * `"intentional"` は**作者だけが選べる**。「回収していない」ことと
 * 「回収しないと決めた」ことを分けないと、意図して開けたままの伏線が
 * 未回収として一覧の先頭に居座り続ける。
 */
export type ForeshadowStatus = "open" | "resolved" | "intentional";

export const FORESHADOW_STATUSES: readonly ForeshadowStatus[] = [
  "open",
  "resolved",
  "intentional",
];

/**
 * どこから来た伏線か。
 *
 * `"contradiction"` は矛盾検知からの転送（設計書6.35.4）。
 * 矛盾として拾われたものが、実は意図した違和感だったという経路である。
 */
export type ForeshadowSource = "ai" | "contradiction" | "author";

export const FORESHADOW_SOURCES: readonly ForeshadowSource[] = [
  "ai",
  "contradiction",
  "author",
];

export interface Foreshadow {
  schemaVersion: string;
  id: string;
  /** 短い名。一覧の見出しになる */
  label: string;
  /** 何を示唆しているか */
  note: string;
  /** 張った話数。読み取れなければ null（話数不明） */
  plantedChapter: number | null;
  /** 張った箇所の逐語引用。本文と照合できる形で持つ */
  plantedQuote: string;
  status: ForeshadowStatus;
  /** 回収した話数。未回収なら null */
  resolvedChapter: number | null;
  resolvedQuote: string;
  /**
   * 回収予定の話（設計書6.35。作者の依頼、2026-09-23）。未定なら null。
   *
   * **作者だけが書く。** AIの検知・回収確認はここへ書かない（`authorNotes` と
   * 同じ扱い）。予定は作者の設計であって、本文から読み取れる事実ではない——
   * AIが「第8話で回収されそう」と書き込めば、作者の決めたことと区別が付かなくなる。
   * 書く口は `foreshadowStore.ts` の `setForeshadowPlannedResolve` だけで、
   * 状態を変える口（`saveOrUpdateForeshadow`）は読んだ値をそのまま保つ。
   */
  plannedResolveChapter: number | null;
  source: ForeshadowSource;
  autoGenerated: boolean;
  /** 作者メモ。AIは絶対に触らない */
  authorNotes: string;
  /** 台帳へ入った時刻。**更新で書き換えない**（いつ気づいた伏線かが残る） */
  createdAt: string;
  updatedAt: string;
}

/**
 * 台帳の版。0.2 で `plannedResolveChapter` を足した。
 *
 * **0.1 の台帳もそのまま読む**（欠けていれば null。`normalizeForeshadow`）。
 * 読んだだけで書き直すことはしない。
 */
export const FORESHADOW_SCHEMA_VERSION = "0.2";

/** IDの接頭辞。ファイル名との整合性検査にも使う */
export const FORESHADOW_ID_PREFIX = "foreshadow";

const ID_PATTERN = /^foreshadow_\d+$/;

export function emptyForeshadow(id: string, label: string): Foreshadow {
  return {
    schemaVersion: FORESHADOW_SCHEMA_VERSION,
    id,
    label,
    note: "",
    plantedChapter: null,
    plantedQuote: "",
    status: "open",
    resolvedChapter: null,
    resolvedQuote: "",
    plannedResolveChapter: null,
    source: "author",
    autoGenerated: false,
    authorNotes: "",
    // 時刻は永続化境界（ストア）で付ける。純粋な生成結果へ壁時計を混ぜない
    createdAt: "",
    updatedAt: "",
  };
}

/** foreshadow_001_銀の懐中時計.json の形式にする */
export function foreshadowFileName(foreshadow: Foreshadow): string {
  // 記号はファイル名に使えないものがあるので落とす（能力・場所と同じ処理）
  const safeLabel = foreshadow.label
    .replace(/[/\\:*?"<>|\s]/g, "")
    .slice(0, 30);
  return safeLabel
    ? `${foreshadow.id}_${safeLabel}.json`
    : `${foreshadow.id}.json`;
}

/** 新しいIDを採番する */
export function nextForeshadowId(existing: Foreshadow[]): string {
  let max = 0;
  for (const foreshadow of existing) {
    const matched = foreshadow.id.match(/^foreshadow_(\d+)$/);
    if (!matched) continue;
    const value = parseInt(matched[1], 10);
    if (value > max) max = value;
  }
  return `foreshadow_${String(max + 1).padStart(3, "0")}`;
}

/** 旧バージョンや手書きJSONでも落ちないよう欠損を補う */
export function normalizeForeshadow(raw: Partial<Foreshadow>): Foreshadow {
  const base = emptyForeshadow(
    raw.id ?? "foreshadow_unknown",
    raw.label ?? "名称不明"
  );
  return {
    ...base,
    ...raw,
    note: raw.note ?? "",
    plantedQuote: raw.plantedQuote ?? "",
    resolvedQuote: raw.resolvedQuote ?? "",
    plantedChapter: raw.plantedChapter ?? null,
    resolvedChapter: raw.resolvedChapter ?? null,
    plannedResolveChapter: raw.plannedResolveChapter ?? null,
    authorNotes: raw.authorNotes ?? "",
  } as Foreshadow;
}

/**
 * 作者が編集できるJSONを検証してから既定値を補う。
 *
 * **壊れていれば例外を投げて止める。** 勝手に修復して書き戻すと、
 * 作者が手で書いた内容が黙って消える。
 */
export function parseForeshadow(raw: unknown): Foreshadow {
  const value = objectValue(raw, "foreshadow");
  requireNonEmptyString(value.id, "id");
  if (!ID_PATTERN.test(value.id as string)) invalid("id");
  requireNonEmptyString(value.label, "label");

  optionalString(value.schemaVersion, "schemaVersion");
  for (const key of [
    "note",
    "plantedQuote",
    "resolvedQuote",
    "authorNotes",
    "createdAt",
    "updatedAt",
  ]) {
    optionalString(value[key], key);
  }
  optionalNullableNumber(value.plantedChapter, "plantedChapter");
  optionalNullableNumber(value.resolvedChapter, "resolvedChapter");
  optionalNullableNumber(value.plannedResolveChapter, "plannedResolveChapter");
  optionalEnum(value.status, "status", FORESHADOW_STATUSES);
  optionalEnum(value.source, "source", FORESHADOW_SOURCES);
  optionalBoolean(value.autoGenerated, "autoGenerated");

  return normalizeForeshadow({
    ...value,
    id: value.id as string,
    label: value.label as string,
  } as Partial<Foreshadow>);
}
