import {
  invalid,
  objectValue,
  optionalBoolean,
  optionalNullableString,
  optionalString,
  requireNonEmptyString,
} from "./jsonValidation";

/**
 * 各話のあらすじ。
 *
 * 作品紹介文（P-06）の材料であり、のちに矛盾検知・プロット逸脱検知でも
 * 「その話に何が起きたか」を知る手掛かりとして使う。
 *
 * **作者が書き直したあらすじは上書きしない。** ほかの設定資料と同じく
 * `autoGenerated: false` になったものは、AIの生成対象から外す。
 */

export interface ChapterSynopsis {
  /** 話数。合本の中の話も含めてここで並ぶ */
  chapter: number | null;
  /** どのファイルから作ったか。合本なら合本ファイルの名前 */
  fileName: string;
  /** そのときのサブタイトル。無ければ null */
  title: string | null;
  synopsis: string;
  /**
   * 生成に使った本文のハッシュ。
   * 本文が変わったかどうかを、これで判断して作り直す。
   */
  sourceHash: string;
  /** 生成に使ったモデルとプロンプトの版。作り直しの判断に使う */
  model: string | null;
  promptVersion: string | null;
  /** false は作者が書き直したもの。AIは触らない */
  autoGenerated: boolean;
  /** 作者のメモ。AIは絶対に書き換えない */
  authorNotes: string;
  updatedAt: string | null;
}

export interface ChapterSynopsisSet {
  schemaVersion: string;
  episodes: ChapterSynopsis[];
}

export const SYNOPSIS_SCHEMA_VERSION = "0.1";

export function emptySynopsisSet(): ChapterSynopsisSet {
  return { schemaVersion: SYNOPSIS_SCHEMA_VERSION, episodes: [] };
}

/**
 * 話を1つに定めるキー。
 *
 * **話数が読み取れる話は話数だけで決める。** ファイル名を混ぜないのは、
 * サブタイトルの提案でファイル名が変わる（`generateSynopses.ts`の
 * `proposeSubtitles`→`renameEpisodeFile`）ためで、ファイル名を含めると
 * リネーム後に「別の話」として扱われ、あらすじが二重に残る事故になる
 * （実機で発覚、2026-08-13。`第17話`が無題版・サブタイトル付き版の
 * 2つ表示されていた）。
 *
 * 話数が読み取れない話（「プロローグ」など）だけ、ファイル名で区別する。
 */
export function synopsisKey(fileName: string, chapter: number | null): string {
  return chapter !== null ? `#${chapter}` : `?#${fileName}`;
}

export function findSynopsis(
  set: ChapterSynopsisSet,
  fileName: string,
  chapter: number | null
): ChapterSynopsis | undefined {
  const key = synopsisKey(fileName, chapter);
  return set.episodes.find(
    (episode) => synopsisKey(episode.fileName, episode.chapter) === key
  );
}

/**
 * 生成結果を差し込む。
 *
 * **作者が書き直したものは差し替えない。** 話数・サブタイトルのような
 * 事実の更新だけを行う。
 */
export function upsertSynopsis(
  set: ChapterSynopsisSet,
  incoming: ChapterSynopsis
): { set: ChapterSynopsisSet; changed: boolean; skippedByAuthor: boolean } {
  const episodes = set.episodes.map((episode) => ({ ...episode }));
  const index = episodes.findIndex(
    (episode) =>
      synopsisKey(episode.fileName, episode.chapter) ===
      synopsisKey(incoming.fileName, incoming.chapter)
  );

  if (index < 0) {
    episodes.push(incoming);
    return { set: { ...set, episodes: sortEpisodes(episodes) }, changed: true, skippedByAuthor: false };
  }

  const current = episodes[index];
  if (!current.autoGenerated) {
    // 作者が書いたあらすじは残す。サブタイトルの変更だけ追随させる
    const title = incoming.title ?? current.title;
    const changed = title !== current.title;
    episodes[index] = { ...current, title };
    return {
      set: { ...set, episodes: sortEpisodes(episodes) },
      changed,
      skippedByAuthor: true,
    };
  }

  episodes[index] = { ...incoming, authorNotes: current.authorNotes };
  return { set: { ...set, episodes: sortEpisodes(episodes) }, changed: true, skippedByAuthor: false };
}

/**
 * 同じ話のエントリが複数あれば1つにまとめる。
 *
 * キーの定義を変える前（ファイル名込みだった時期）に保存された
 * `chapter_synopses.json` には、リネームのたびに増えた重複が
 * 残っている可能性がある。`SynopsisStore.load()` から呼び、
 * 読み込むたびに自動で片付ける。
 *
 * **作者が書き直したもの（`autoGenerated: false`）を最優先で残す。**
 * 次点は更新日時が新しいもの。負けた側にしか無いメモ（`authorNotes`）は
 * 引き継ぎ、作者のメモを失わないようにする。
 */
export function dedupeSynopsisEpisodes(
  episodes: ChapterSynopsis[]
): { episodes: ChapterSynopsis[]; removed: number } {
  const groups = new Map<string, ChapterSynopsis[]>();
  for (const episode of episodes) {
    const key = synopsisKey(episode.fileName, episode.chapter);
    const group = groups.get(key);
    if (group) {
      group.push(episode);
    } else {
      groups.set(key, [episode]);
    }
  }

  const deduped: ChapterSynopsis[] = [];
  let removed = 0;
  for (const group of groups.values()) {
    if (group.length === 1) {
      deduped.push(group[0]);
      continue;
    }
    deduped.push(mergeDuplicates(group));
    removed += group.length - 1;
  }

  return { episodes: deduped, removed };
}

function mergeDuplicates(group: ChapterSynopsis[]): ChapterSynopsis {
  // 更新日時が同点（未設定を含む）のときは、配列の後ろにあるほう
  // （＝リネーム後にあとから追加されたほう）を勝たせる。
  // `upsertSynopsis`は末尾へ`push`するため、後ろにあるほど新しい
  let winner = group[0];
  for (const candidate of group.slice(1)) {
    if (isBetterOrEqual(candidate, winner)) winner = candidate;
  }

  const losers = group.filter((candidate) => candidate !== winner);
  if (winner.authorNotes.trim()) return winner;

  const noteFromLoser = losers.find((loser) => loser.authorNotes.trim());
  return noteFromLoser
    ? { ...winner, authorNotes: noteFromLoser.authorNotes }
    : winner;
}

/** 作者が書いたものを最優先。次点は更新日時（同点なら後着優先） */
function isBetterOrEqual(
  candidate: ChapterSynopsis,
  current: ChapterSynopsis
): boolean {
  if (candidate.autoGenerated !== current.autoGenerated) {
    return !candidate.autoGenerated;
  }
  return updatedAtMs(candidate) >= updatedAtMs(current);
}

function updatedAtMs(episode: ChapterSynopsis): number {
  if (!episode.updatedAt) return 0;
  const parsed = Date.parse(episode.updatedAt);
  return Number.isNaN(parsed) ? 0 : parsed;
}

/** 話数の順に並べる。話数の無いものは末尾 */
function sortEpisodes(episodes: ChapterSynopsis[]): ChapterSynopsis[] {
  return [...episodes].sort((a, b) => {
    if (a.chapter === null && b.chapter === null) {
      return a.fileName.localeCompare(b.fileName, "ja");
    }
    if (a.chapter === null) return 1;
    if (b.chapter === null) return -1;
    return a.chapter - b.chapter;
  });
}

/** 作者が手で編集するJSONを検証する。壊れていたら保存を止める */
export function parseSynopsisSet(raw: unknown): ChapterSynopsisSet {
  const value = objectValue(raw, "chapter_synopses");
  requireNonEmptyString(value.schemaVersion, "schemaVersion");
  if (!Array.isArray(value.episodes)) invalid("episodes");

  const episodes = value.episodes.map((entry, index) => {
    const path = `episodes[${index}]`;
    const episode = objectValue(entry, path);
    requireNonEmptyString(episode.fileName, `${path}.fileName`);
    requireNonEmptyString(episode.synopsis, `${path}.synopsis`);
    optionalNullableString(episode.title, `${path}.title`);
    optionalString(episode.sourceHash, `${path}.sourceHash`);
    optionalNullableString(episode.model, `${path}.model`);
    optionalNullableString(episode.promptVersion, `${path}.promptVersion`);
    optionalBoolean(episode.autoGenerated, `${path}.autoGenerated`);
    optionalString(episode.authorNotes, `${path}.authorNotes`);
    optionalNullableString(episode.updatedAt, `${path}.updatedAt`);
    if (
      episode.chapter !== undefined &&
      episode.chapter !== null &&
      !Number.isSafeInteger(episode.chapter)
    ) {
      invalid(`${path}.chapter`);
    }

    return {
      chapter: (episode.chapter as number | null | undefined) ?? null,
      fileName: episode.fileName as string,
      title: (episode.title as string | null | undefined) ?? null,
      synopsis: episode.synopsis as string,
      sourceHash: (episode.sourceHash as string | undefined) ?? "",
      model: (episode.model as string | null | undefined) ?? null,
      promptVersion: (episode.promptVersion as string | null | undefined) ?? null,
      autoGenerated: (episode.autoGenerated as boolean | undefined) ?? true,
      authorNotes: (episode.authorNotes as string | undefined) ?? "",
      updatedAt: (episode.updatedAt as string | null | undefined) ?? null,
    };
  });

  return { schemaVersion: value.schemaVersion as string, episodes };
}
