import {
  invalid,
  objectValue,
  optionalBoolean,
  optionalEnum,
  optionalNullableString,
  optionalNumberArray,
  optionalString,
  optionalStringArray,
  parseConflicts,
  type RecordConflict,
  requireNonEmptyString,
} from "./jsonValidation";
import { parseAiNotes, type AiNote } from "./aiNote";

/**
 * 世界観の設定（P-03）。
 *
 * 「その世界がどうなっているか」を1件ずつ持つ。
 * 物語の出来事そのもの（誰が何をしたか）は入れない。
 *
 * **設計書のP-03は `world.md` に作者の加筆を `<!-- author -->` で
 * 混ぜる案だったが、採らない。** 作者が散文を書きながらコメント記法を
 * 維持するのは無理があり、再生成のたびに解析を誤れば作者の文章が消える。
 * 「作者が書いたデータを上書きしない」という約束を、
 * 解析の正確さに賭ける形になってしまう。
 *
 * 人物・能力・場所と同じく**JSONで持ち、`world.md` は純粋な生成物**にする。
 * 作者が書き足したいことは `authorNotes` / `exportNote` に入れる。
 * これらはAIが絶対に触らない。
 *
 * 1件1ファイルにするのも同じ理由（別環境で別々の項目を追記しただけで
 * Gitの競合が起きるのを避ける）。
 */

/** 世界観の分類。設計書P-03の category に対応する */
export const WORLD_CATEGORIES = [
  "genre",
  "era",
  "rule",
  "society",
  "culture",
  "geography",
  "term",
] as const;

export type WorldCategory = (typeof WORLD_CATEGORIES)[number];

/** 資料の見出しに使う。この順で並べる */
export const WORLD_CATEGORY_LABELS: Record<WorldCategory, string> = {
  genre: "ジャンル・作品の性格",
  era: "時代背景",
  rule: "世界の法則",
  society: "社会構造",
  culture: "文化・風習",
  geography: "地理",
  term: "固有の用語",
};

export interface WorldItem {
  schemaVersion: string;
  id: string;
  /**
   * 短い見出し。「詠唱の制約」のように、何についての項目かを示す。
   * ファイル名にも使うので、本文の丸写しではなく短くまとめる。
   */
  name: string;
  /** 表記ゆれ。同じ事柄を別の言い方で書いた場合に入る */
  aliases: string[];
  /**
   * 読み仮名（ひらがな）。**IME辞書のために持つ。**
   *
   * 「詠唱の制約」のような見出しに読みは要らない。そのため当初は
   * 項目ごと外していたが、分類 `term`（作品の造語）だけは
   * **本文で作者が打つ言葉**であり、IME辞書に入れないと毎回打ち直しになる。
   * 外していた間、**漢字の造語はどうやっても辞書に入らなかった。**
   *
   * 漢字の造語は機械的に読みを決められないので、ここが空だと辞書から落ちる。
   * 埋まる経路は3つ：カタカナならコード側（`fillReading`）、
   * 漢字ならAIの推定（P-16）か、作者が設定資料パネルで直接入力する。
   */
  reading: string | null;
  category: WorldCategory;
  /** 中身。これが本体 */
  description: string | null;
  appearedChapters: number[];
  spoilerLevel: "public" | "staff_only" | "author_only";
  evidence: string | null;
  /** 作者メモ。AI再生成でも絶対に上書きしない */
  authorNotes: string;
  /** 資料にのみ出力する補足 */
  exportNote: string;
  autoGenerated: boolean;
  /** 食い違い（作中での変化かもしれない）。値ごとの話数は observations に入る */
  conflicts: RecordConflict[];
  aiNotes: AiNote[];
  updatedAt: string;
}

export const WORLD_SCHEMA_VERSION = "0.1";

export function emptyWorldItem(
  id: string,
  name: string,
  category: WorldCategory = "term"
): WorldItem {
  return {
    schemaVersion: WORLD_SCHEMA_VERSION,
    id,
    name,
    aliases: [],
    reading: null,
    category,
    description: null,
    appearedChapters: [],
    spoilerLevel: "public",
    evidence: null,
    authorNotes: "",
    exportNote: "",
    autoGenerated: true,
    conflicts: [],
    aiNotes: [],
    // 永続化境界で保存時刻を付ける。純粋な生成・マージ結果へ壁時計を混ぜない。
    updatedAt: "",
  };
}

/** world_001_詠唱の制約.json の形式にする */
export function worldItemFileName(item: WorldItem): string {
  const safeName = item.name.replace(/[/\\:*?"<>|\s]/g, "").slice(0, 30);
  return safeName ? `${item.id}_${safeName}.json` : `${item.id}.json`;
}

export function nextWorldItemId(existing: WorldItem[]): string {
  let max = 0;
  for (const item of existing) {
    const matched = item.id.match(/^world_(\d+)$/);
    if (!matched) continue;
    const value = parseInt(matched[1], 10);
    if (value > max) max = value;
  }
  return `world_${String(max + 1).padStart(3, "0")}`;
}

/** 旧バージョンや手書きJSONでも落ちないよう欠損を補う */
export function normalizeWorldItem(raw: Partial<WorldItem>): WorldItem {
  const base = emptyWorldItem(raw.id ?? "world_unknown", raw.name ?? "名称不明");
  return {
    ...base,
    ...raw,
    aliases: raw.aliases ?? [],
    // 既存のJSONにはこの項目が無い。欠損を null で補うので移行処理は要らない
    reading: raw.reading ?? null,
    appearedChapters: raw.appearedChapters ?? [],
    conflicts: raw.conflicts ?? [],
    aiNotes: raw.aiNotes ?? [],
    authorNotes: raw.authorNotes ?? "",
    exportNote: raw.exportNote ?? "",
  } as WorldItem;
}

/** 表記ゆれを吸収して同一項目を判定する */
export function normalizeWorldItemName(name: string): string {
  return name
    .replace(/[\s　・･]/g, "")
    .replace(/[０-９]/g, (c) => String.fromCharCode(c.charCodeAt(0) - 0xfee0))
    .toLowerCase();
}

/** 作者が編集できるJSONを検証してから既定値を補う。 */
export function parseWorldItem(raw: unknown): WorldItem {
  const value = objectValue(raw, "world");
  requireNonEmptyString(value.id, "id");
  if (!/^world_\d+$/.test(value.id as string)) invalid("id");
  requireNonEmptyString(value.name, "name");

  optionalString(value.schemaVersion, "schemaVersion");
  optionalStringArray(value.aliases, "aliases");
  optionalEnum(value.category, "category", [...WORLD_CATEGORIES]);
  for (const key of ["description", "evidence", "reading"]) {
    optionalNullableString(value[key], key);
  }
  optionalNumberArray(value.appearedChapters, "appearedChapters");
  optionalEnum(value.spoilerLevel, "spoilerLevel", [
    "public",
    "staff_only",
    "author_only",
  ]);
  optionalString(value.authorNotes, "authorNotes");
  optionalString(value.exportNote, "exportNote");
  optionalBoolean(value.autoGenerated, "autoGenerated");
  optionalString(value.updatedAt, "updatedAt");

  const conflicts = parseConflicts(value.conflicts);

  return normalizeWorldItem({
    ...value,
    id: value.id as string,
    name: value.name as string,
    conflicts,
    aiNotes: parseAiNotes(value.aiNotes),
  } as Partial<WorldItem>);
}
