import { describe, expect, test } from "vitest";
import type { Chunk } from "../../src/core/chunker";
import {
  correctRelationDirection,
  isTruncatedAlias,
  validateCharacterExtractResult,
} from "../../src/core/characterExtractionValidation";
import {
  dedupeRelations,
  describeMergeCandidate,
  findMergeCandidates,
  mergeExtractedCharacters,
  normalizeSpacing,
} from "../../src/core/characterMerge";
import { unifyCharacters } from "../../src/core/characterUnify";
import {
  buildChronicle,
  type ChronicleEpisode,
} from "../../src/core/chronicle";
import { chronicleToMarkdown } from "../../src/core/chronicleMarkdown";
import { emptyCharacter, type Character } from "../../src/models/character";
import type { CharacterExtractResult } from "../../src/prompts/characterExtract";

/**
 * 設定資料の人物が分裂する不具合（実機確認A-18）の検算。
 *
 * **実データの値をそのまま使う。** 作った例だけで固めると、
 * 実際に壊れた形（別名に別人の名前・向きの逆さま・切れた呼び名）を
 * 素通りさせたことに気づけない。
 */

/** 本文。根拠の照合を通すため、名前と引用が実在するようにしてある */
const text = [
  "三門太志は密倉文佳の身体で目を覚ました。",
  "「太志くん」とお母さんが呼んだ。",
  "文佳ちゃんの母親さんは何も知らない。",
  "圭織は台所に立っていた。",
].join("\n");

const chunk: Chunk = {
  filePath: "001.txt",
  index: 0,
  text,
  startLine: 0,
  hash: "a18",
  chapterStart: 1,
  chapterEnd: 1,
};

function character(
  id: string,
  name: string,
  overrides: Partial<Character> = {}
): Character {
  return { ...emptyCharacter(id, name), ...overrides };
}

const WORK_ROOT = "C:/works/sample";

function episode(chapter: number, name: string): ChronicleEpisode {
  return {
    filePath: `${WORK_ROOT}/本文/${name}`,
    fileName: name,
    chapterStart: chapter,
    chapterEnd: chapter,
    subtitle: null,
    metaTitle: null,
    kind: "本編",
    date: null,
    dateSeq: null,
    counts: {
      gross: 100,
      net: 100,
      lines: 1,
      paragraphs: 1,
      manuscriptLines: 1,
    },
  };
}

describe("①体を共有している相手を別名に混ぜない", () => {
  test("憑依している相手の名前・別名を、自分の別名から落とす", () => {
    const result = validateCharacterExtractResult(
      {
        characters: [
          {
            name: "三門太志",
            aliases: ["太志", "文佳", "密倉文佳"],
            relations: [{ name: "文佳", relation: "憑依している" }],
            evidence: "三門太志は密倉文佳の身体で目を覚ました。",
          },
          {
            name: "文佳",
            aliases: ["密倉文佳", "お嬢様", "文佳ちゃん"],
            evidence: "三門太志は密倉文佳の身体で目を覚ました。",
          },
        ],
      } as unknown as CharacterExtractResult,
      chunk
    );

    const taishi = result.accepted.find((item) => item.data.name === "三門太志");
    // 「文佳」も、文佳のレコードが持つ「密倉文佳」も落ちる
    expect(taishi?.data.aliases).toEqual(["太志"]);
    // 落とした分は黙って消さず、件数と中身を返す
    expect(result.droppedSharedBodyAliases).toContainEqual({
      characterName: "三門太志",
      alias: "文佳",
      partner: "文佳",
    });
  });

  test("憑依された側の別名からも、憑依した相手の名前を落とす", () => {
    // 実データで汚染されたのはこちら側だった。
    // `char_006_文佳` の別名に別人の「太志」「三門太志」が入っていた
    const result = validateCharacterExtractResult(
      {
        characters: [
          {
            name: "三門太志",
            aliases: ["太志"],
            relations: [{ name: "文佳", relation: "憑依している" }],
            evidence: "三門太志は密倉文佳の身体で目を覚ました。",
          },
          {
            name: "文佳",
            aliases: ["密倉文佳", "太志", "三門太志", "文佳ちゃん"],
            evidence: "文佳ちゃんの母親さんは何も知らない。",
          },
        ],
      } as unknown as CharacterExtractResult,
      chunk
    );

    const fumika = result.accepted.find((item) => item.data.name === "文佳");
    expect(fumika?.data.aliases).toEqual(["密倉文佳", "文佳ちゃん"]);
  });

  test("普通の関係では別名を落とさない", () => {
    const result = validateCharacterExtractResult(
      {
        characters: [
          {
            name: "三門太志",
            aliases: ["太志"],
            relations: [{ name: "文佳", relation: "幼馴染" }],
            evidence: "三門太志は密倉文佳の身体で目を覚ました。",
          },
        ],
      } as unknown as CharacterExtractResult,
      chunk
    );

    expect(result.accepted[0].data.aliases).toEqual(["太志"]);
    expect(result.droppedSharedBodyAliases).toEqual([]);
  });

  test("既存レコードの名前と一致する別名は取り込まない", () => {
    // 別人の名前が別名に入ると、「重複をまとめる」に別人どうしの組が並ぶ
    const result = mergeExtractedCharacters(
      [
        character("char_001", "三門太志"),
        character("char_006", "文佳", { autoGenerated: true }),
      ],
      [{ data: { name: "文佳", aliases: ["三門太志", "フミカ"] }, chapters: [1] }]
    );

    const fumika = result.characters.find((item) => item.id === "char_006");
    expect(fumika?.aliases).toEqual(["フミカ"]);
  });
});

describe("②同じ相手との関係の重複をまとめる", () => {
  test("敬称と丁寧の「お」だけが違う相手を1人として数える", () => {
    // 実データでは「ばあさん」「おばあさん」だけで6件あった
    expect(
      dedupeRelations([
        { name: "ばあさん", relation: "祖母" },
        { name: "おばあさん", relation: "祖母" },
        { name: "ばあさま", relation: "祖母" },
      ])
      // 表示に使う名前は先に出てきた形を残す
    ).toEqual([{ name: "ばあさん", relation: "祖母" }]);
  });

  test("漢字とひらがなの違いまでは寄せない", () => {
    // 「お婆さん」と「ばあさん」は同じ人だが、字が違えば別の相手かもしれない。
    // ここで寄せると、別人の関係を1件に潰す危険のほうが大きい
    expect(
      dedupeRelations([
        { name: "ばあさん", relation: "祖母" },
        { name: "お婆さん", relation: "祖母" },
      ])
    ).toHaveLength(2);
  });

  test("関係の言い方が違えば両方残す", () => {
    // 「憑依している」と「同一人物（転生後）」は同時に成り立たないが、
    // まとめてしまうと矛盾に気づけなくなる
    expect(
      dedupeRelations([
        { name: "文佳", relation: "憑依している" },
        { name: "文佳", relation: "同一人物（転生後）" },
      ])
    ).toHaveLength(2);
  });

  test("マージのときに、既にある重複もまとめる", () => {
    const existing = character("char_001", "三門太志", {
      relations: [
        { name: "ばあさん", relation: "祖母" },
        { name: "おばあさん", relation: "祖母" },
      ],
    });

    const result = mergeExtractedCharacters(
      [existing],
      [
        {
          data: {
            name: "三門太志",
            relations: [{ name: "ばあさま", relation: "祖母" }],
          },
          chapters: [2],
        },
      ]
    );

    expect(result.characters[0].relations).toEqual([
      { name: "ばあさん", relation: "祖母" },
    ]);
  });

  test("作者が確定させたレコードの関係は書き換えない", () => {
    const existing = character("char_001", "三門太志", {
      autoGenerated: false,
      relations: [
        { name: "ばあさん", relation: "祖母" },
        { name: "おばあさん", relation: "祖母" },
      ],
    });

    const result = mergeExtractedCharacters(
      [existing],
      [
        {
          data: {
            name: "三門太志",
            relations: [{ name: "月夜", relation: "友人" }],
          },
          chapters: [2],
        },
      ]
    );

    expect(result.characters[0].relations).toHaveLength(2);
  });
});

describe("③関係の向きの検算", () => {
  test("相手が「お母さん」で関係が「息子」なら「母」へ直す", () => {
    // 実データの char_001_三門太志 にそのまま入っていた
    expect(correctRelationDirection("お母さん", "息子")).toBe("母");
  });

  test.each([
    ["三門の母", "娘", "母"],
    ["おじいさま", "孫", "祖父"],
    ["おばあさん", "孫", "祖母"],
    ["お兄ちゃん", "弟", "兄"],
    ["姉さん", "妹", "姉"],
  ])("相手「%s」に「%s」なら「%s」", (partner, relation, expected) => {
    expect(correctRelationDirection(partner, relation)).toBe(expected);
  });

  test.each([
    // 既に相手側から見た語なので触らない
    ["お母さん", "母"],
    ["おばあさん", "祖母"],
    // 親族語ではない関係は触らない
    ["お母さん", "雇い主"],
    // 相手の名前に親族語が無ければ判断できない
    ["春原月夜", "息子"],
    // 「ふじい」を「じい」と読まない。ひらがなの言い方は頭でしか見ない
    ["ふじいさん", "孫"],
  ])("相手「%s」に「%s」はそのまま", (partner, relation) => {
    const fixed = correctRelationDirection(partner, relation);
    expect(fixed === relation || fixed === null).toBe(true);
  });

  test("抽出結果の関係を直し、直した件数を返す", () => {
    const result = validateCharacterExtractResult(
      {
        characters: [
          {
            name: "三門太志",
            relations: [{ name: "お母さん", relation: "息子" }],
            evidence: "「太志くん」とお母さんが呼んだ。",
          },
        ],
      } as unknown as CharacterExtractResult,
      chunk
    );

    expect(result.accepted[0].data.relations).toEqual([
      { name: "お母さん", relation: "母" },
    ]);
    expect(result.correctedRelations).toEqual([
      {
        characterName: "三門太志",
        partner: "お母さん",
        from: "息子",
        to: "母",
      },
    ]);
  });
});

describe("④途中で切れた別名を弾く", () => {
  const known = new Set(["母親さん", "太志くん", "文佳ちゃん", "つかさ", "おじいさま"]);

  test.each(["母親さ", "太志く", "文佳ちゃ"])(
    "「ん」を足した形が実在する「%s」は弾く",
    (alias) => {
      expect(isTruncatedAlias(alias, known)).toBe(true);
    }
  );

  test.each(["つかさ", "おじいさま", "密倉さん", "文佳"])(
    "裏付けの無い「%s」は弾かない",
    (alias) => {
      expect(isTruncatedAlias(alias, known)).toBe(false);
    }
  );

  test("既存レコードの呼び名を裏付けにできる", () => {
    const result = validateCharacterExtractResult(
      {
        characters: [
          {
            name: "圭織",
            aliases: ["母親さ"],
            evidence: "圭織は台所に立っていた。",
          },
        ],
      } as unknown as CharacterExtractResult,
      chunk,
      { knownNames: ["圭織", "母親さん"] }
    );

    expect(result.accepted[0].data.aliases).toEqual([]);
    expect(result.droppedTruncatedAliases).toEqual([
      { characterName: "圭織", alias: "母親さ" },
    ]);
  });
});

describe("⑤重複の候補に根拠を出す", () => {
  /** 姓「三門」を4人が持つ、実データと同じ形 */
  function familyRecords(): Character[] {
    return [
      character("char_001", "三門太志", { aliases: ["太志", "三門"] }),
      character("char_002", "三門", {}),
      character("char_003", "三門の母", { aliases: ["三門"] }),
      character("char_007", "圭織", { aliases: ["三門さん"] }),
    ];
  }

  test("一致した呼び名を名指しで出す", () => {
    const candidates = findMergeCandidates(familyRecords());
    const pair = candidates.find(
      (candidate) =>
        candidate.ids[0] === "char_001" && candidate.ids[1] === "char_003"
    );

    expect(pair?.matchedName).toBe("三門");
    expect(describeMergeCandidate(pair!)).toBe(
      "「三門」が両方にあります（姓の共有かもしれません）"
    );
  });

  test("姓を共有しているだけの組は確信度を落とす", () => {
    const candidates = findMergeCandidates(familyRecords());
    const withKaori = candidates.find(
      (candidate) =>
        candidate.ids.includes("char_007") && candidate.reason === "same_name"
    );

    expect(withKaori?.confidence).toBe("weak");
    expect(withKaori?.weakNote).toBe("姓の共有かもしれません");
  });

  test("姓名と名だけの正しい重複は、確信度を落とさない", () => {
    // 「密倉文佳」と「文佳」は同じ人物の分裂で、いちばん直したい候補である
    const candidates = findMergeCandidates([
      character("char_005", "密倉文佳", { aliases: ["文佳"] }),
      character("char_006", "文佳", {}),
    ]);

    expect(candidates[0].reason).toBe("same_name");
    expect(candidates[0].confidence).toBe("strong");
    expect(describeMergeCandidate(candidates[0])).toBe(
      "「文佳」が両方にあります"
    );
  });

  test("別名に相手の名前が混ざっただけの組は確信度を落とす", () => {
    const candidates = findMergeCandidates([
      character("char_001", "三門太志", { aliases: ["太志"] }),
      character("char_006", "文佳", { aliases: ["三門太志"] }),
    ]);

    expect(candidates[0].confidence).toBe("weak");
    expect(describeMergeCandidate(candidates[0])).toBe(
      "「三門太志」が両方にあります（別名に相手の名前が混ざっただけかもしれません）"
    );
  });
});

describe("⑥読み仮名の違いは「変化」に入れない", () => {
  test("違う読みは conflicts へ回し、changes へ積まない", () => {
    // 実データでは reading:"たいし"（第1話）と "たし"（第2話）が並び、
    // 年表に「読み：たいし → たし」と出ていた
    const result = mergeExtractedCharacters(
      [character("char_001", "三門太志")],
      [
        { data: { name: "三門太志", reading: "たいし" }, chapters: [1] },
        { data: { name: "三門太志", reading: "たし" }, chapters: [2] },
      ]
    );

    const taishi = result.characters[0];
    expect(taishi.changes.filter((change) => change.field === "reading")).toEqual(
      []
    );
    expect(
      taishi.conflicts.find((conflict) => conflict.field === "reading")?.values
    ).toEqual(["たいし", "たし"]);
  });

  test("年表に「読み：◯◯ → ××」が出ない", () => {
    const merged = mergeExtractedCharacters(
      [character("char_001", "三門太志")],
      [
        { data: { name: "三門太志", reading: "たいし" }, chapters: [1] },
        { data: { name: "三門太志", reading: "たし" }, chapters: [2] },
      ]
    );

    const rows = buildChronicle(
      [episode(1, "第01話.txt"), episode(2, "第02話.txt")],
      merged.characters,
      null,
      [],
      null,
      { workRoot: WORK_ROOT }
    );
    const events = rows.flatMap((row) => row.events.map((event) => event.text));

    // 実データでは「読み：たいし → たし」という、起きていない変化が出ていた
    expect(events.some((text) => text.startsWith("読み："))).toBe(false);
  });

  test("外見の変化はこれまでどおり畳み、年表にも出す", () => {
    const result = mergeExtractedCharacters(
      [character("char_001", "三門太志")],
      [
        { data: { name: "三門太志", appearance: "黒髪" }, chapters: [1] },
        { data: { name: "三門太志", appearance: "銀髪" }, chapters: [2] },
      ]
    );

    expect(
      result.characters[0].changes.filter(
        (change) => change.field === "appearance"
      )
    ).toHaveLength(2);

    const rows = buildChronicle(
      [episode(1, "第01話.txt"), episode(2, "第02話.txt")],
      result.characters,
      null,
      [],
      null,
      { workRoot: WORK_ROOT }
    );
    const events = rows.flatMap((row) => row.events.map((event) => event.text));

    expect(events).toContain("外見：黒髪 → 銀髪");
  });
});

describe("⑦名前の空白の正規化", () => {
  test("空白だけを落とす。敬称は落とさない", () => {
    expect(normalizeSpacing("密倉 文佳")).toBe("密倉文佳");
    expect(normalizeSpacing("密倉　文佳")).toBe("密倉文佳");
    expect(normalizeSpacing("文佳ちゃん")).toBe("文佳ちゃん");
  });

  test("空白だけが違う呼び名を別名として増やさない", () => {
    const result = mergeExtractedCharacters(
      [character("char_005", "密倉文佳")],
      [{ data: { name: "密倉 文佳", aliases: ["密倉　文佳"] }, chapters: [1] }]
    );

    expect(result.characters).toHaveLength(1);
    expect(result.characters[0].aliases).toEqual([]);
  });

  test("まとめるとき、空白だけが違う名前を別名に残さない", () => {
    const { unified } = unifyCharacters(
      character("char_005", "密倉文佳"),
      character("char_006", "密倉 文佳", { aliases: ["文佳"] })
    );

    expect(unified.aliases).toEqual(["文佳"]);
  });

  test("まとめるとき、ほかのレコードの名前は別名にしない", () => {
    const others = [character("char_001", "三門太志")];
    const { unified } = unifyCharacters(
      character("char_005", "密倉文佳"),
      character("char_006", "文佳", { aliases: ["三門太志", "フミカ"] }),
      others
    );

    expect(unified.aliases).toEqual(["文佳", "フミカ"]);
  });
});

describe("⑧年表の空の見出し", () => {
  test("段に名前が無いときは「（時期なし）」と出す", () => {
    const markdown = chronicleToMarkdown([
      {
        label: "",
        line: null,
        kind: "canonical",
        rows: [
          {
            chapter: 1,
            chapterLabel: "第1話",
            title: null,
            filePath: "001.txt",
            synopsis: null,
            timepoint: null,
            line: null,
            appeared: [],
            events: [],
          },
        ],
      },
    ]);

    expect(markdown).not.toMatch(/^## $/m);
    expect(markdown).toContain("## （時期なし）");
  });
});

describe("⑨敬称違いを機械で寄せる（0.42.2）", () => {
  /**
   * 実機確認A-18の「新しい問題」。まっさらからの抽出で、AIは aliases を
   * ほぼ返さない（qwen3:8b・gemma4:e4b で実測）。スキーマの required も
   * 説明文もプロンプトの規則も効かなかったので、コードで結ぶ。
   */

  test("「文佳ちゃん」は「密倉文佳」へ寄り、別名に足される", () => {
    const result = mergeExtractedCharacters(
      [character("char_005", "密倉文佳", { aliases: ["文佳"] })],
      [{ data: { name: "文佳ちゃん" }, chapters: [3] }]
    );

    // レコードは増えない
    expect(result.characters).toHaveLength(1);
    expect(result.characters[0].aliases).toContain("文佳ちゃん");
    // 登場話数も本人へ付く
    expect(result.characters[0].appearedChapters).toContain(3);
  });

  test("寄せた分は黙らず、件数と中身を返す", () => {
    const result = mergeExtractedCharacters(
      [character("char_005", "密倉文佳", { aliases: ["文佳"] })],
      [{ data: { name: "文佳ちゃん" }, chapters: [3] }]
    );

    expect(result.honorificMerges).toEqual([
      { characterName: "密倉文佳", incomingName: "文佳ちゃん" },
    ]);
  });

  test("敬称の違いでないときは、寄せたことにしない", () => {
    const result = mergeExtractedCharacters(
      [character("char_005", "密倉文佳", { aliases: ["文佳"] })],
      [{ data: { name: "文佳" }, chapters: [3] }]
    );

    expect(result.honorificMerges).toEqual([]);
  });

  test("作者が別人と決めた呼び名なら寄らない", () => {
    const result = mergeExtractedCharacters(
      [
        character("char_005", "密倉文佳", {
          aliases: ["文佳"],
          distinctFrom: [
            { id: null, name: "文佳ちゃん" },
          ],
        }),
      ],
      [{ data: { name: "文佳ちゃん" }, chapters: [3] }]
    );

    // 作者の判断はAIの読みより強い。別レコードのまま残す
    expect(result.characters).toHaveLength(2);
    expect(result.characters[0].aliases).toEqual(["文佳"]);
    expect(result.honorificMerges).toEqual([]);
  });

  test("「密倉さん」は姓の一致どまり。候補に上げるが自動では寄せない", () => {
    const result = mergeExtractedCharacters(
      [character("char_005", "密倉文佳", { aliases: ["文佳"] })],
      [{ data: { name: "密倉さん" }, chapters: [4] }]
    );

    // 姓の一致は別人でもありうるので、寄せずにレコードは残す
    expect(result.characters).toHaveLength(2);
    expect(result.honorificMerges).toEqual([]);

    const candidate = result.mergeCandidates.find(
      (item) => item.reason === "honorific_family_name"
    );
    expect(candidate?.names).toEqual(["密倉さん", "密倉文佳"]);
    expect(candidate?.confidence).toBe("medium");
    expect(describeMergeCandidate(candidate!)).toBe(
      "敬称を外すと「密倉」＝「密倉文佳」の姓です"
    );
  });

  test("その姓を持つレコードが2件以上なら候補にしない（家族）", () => {
    const candidates = findMergeCandidates([
      character("char_010", "三門くん"),
      character("char_001", "三門太志"),
      character("char_003", "三門圭織"),
    ]);

    expect(
      candidates.filter((item) => item.reason === "honorific_family_name")
    ).toEqual([]);
  });

  test("作者が別人と決めた組は、姓の候補にも出さない", () => {
    const candidates = findMergeCandidates([
      character("char_010", "密倉さん", {
        distinctFrom: [{ id: "char_005", name: "密倉文佳" }],
      }),
      character("char_005", "密倉文佳"),
    ]);

    expect(candidates).toEqual([]);
  });

  test("呼びかけ語は敬称を外さないので、姓の候補にならない", () => {
    // 「おじいさま」を「おじい」まで削ると、「おじい◯◯」という
    // 本文に無い姓で人物を結びはじめる
    const candidates = findMergeCandidates([
      character("char_011", "おじいさま"),
      character("char_012", "おじい太郎"),
    ]);

    expect(
      candidates.filter((item) => item.reason === "honorific_family_name")
    ).toEqual([]);
  });
});
