import { describe, expect, test } from "vitest";
import { unifyCharacters } from "../../src/core/characterUnify";
import { emptyCharacter, type Character } from "../../src/models/character";

function character(id: string, name: string, overrides: Partial<Character> = {}) {
  return { ...emptyCharacter(id, name), ...overrides };
}

describe("同一人物をまとめる", () => {
  test("取り下げる側の名前を別名として残す", () => {
    const { unified, retiredId } = unifyCharacters(
      character("char_003", "リンセップ・アウクト"),
      character("char_001", "リン")
    );

    expect(unified.id).toBe("char_003");
    expect(unified.name).toBe("リンセップ・アウクト");
    expect(unified.aliases).toContain("リン");
    expect(retiredId).toBe("char_001");
  });

  test("作者が書いた文章は両方残す", () => {
    // 「まとめたら作者メモが消えた」は取り返しがつかない
    const { unified } = unifyCharacters(
      character("char_001", "リン", { authorNotes: "残す側のメモ" }),
      character("char_002", "リンセップ", { authorNotes: "消える側のメモ" })
    );

    expect(unified.authorNotes).toContain("残す側のメモ");
    expect(unified.authorNotes).toContain("消える側のメモ");
  });

  test("同じ文章を二重に書かない", () => {
    const { unified } = unifyCharacters(
      character("char_001", "リン", { authorNotes: "同じメモ" }),
      character("char_002", "リンセップ", { authorNotes: "同じメモ" })
    );

    expect(unified.authorNotes).toBe("同じメモ");
  });

  test("片方にしかない項目を拾う", () => {
    const { unified } = unifyCharacters(
      character("char_001", "リン", { role: null, appearance: "銀髪" }),
      character("char_002", "リンセップ", { role: "王女", appearance: null })
    );

    expect(unified.role).toBe("王女");
    expect(unified.appearance).toBe("銀髪");
  });

  test("残す側の項目を取り下げ側で上書きしない", () => {
    const { unified } = unifyCharacters(
      character("char_001", "リン", { role: "王女" }),
      character("char_002", "リンセップ", { role: "villager" })
    );

    expect(unified.role).toBe("王女");
  });

  test("登場話数と関係を合わせる", () => {
    const { unified } = unifyCharacters(
      character("char_001", "リン", {
        appearedChapters: [1, 3],
        relations: [{ name: "マル", relation: "幼馴染" }],
      }),
      character("char_002", "リンセップ", {
        appearedChapters: [3, 5],
        relations: [
          { name: "マル", relation: "幼馴染" },
          { name: "国王", relation: "父" },
        ],
      })
    );

    expect(unified.appearedChapters).toEqual([1, 3, 5]);
    expect(unified.relations).toEqual([
      { name: "マル", relation: "幼馴染" },
      { name: "国王", relation: "父" },
    ]);
  });

  test("呼称の宛先をまとめた後の名前へ付け替える", () => {
    const absorb = character("char_001", "リン", {
      addressTerms: [
        {
          targetName: "リン",
          targetId: null,
          authorLocked: false,
          forms: [
            {
              term: "リンちゃん",
              category: null,
              context: null,
              firstChapter: null,
              lastChapter: null,
              status: "current",
              evidence: null,
            },
          ],
        },
      ],
    });

    const { unified } = unifyCharacters(
      character("char_003", "リンセップ・アウクト"),
      absorb
    );

    // 付け替えないと、誰に向けた呼称なのか分からなくなる
    expect(unified.addressTerms[0].targetName).toBe("リンセップ・アウクト");
    expect(unified.addressTerms[0].forms[0].term).toBe("リンちゃん");
  });

  test("まとめた人物は以後の抽出で上書きされない", () => {
    const { unified } = unifyCharacters(
      character("char_001", "リン"),
      character("char_002", "リンセップ")
    );

    // 作者の判断で1件にしたものを、次の抽出で2件へ戻されては困る
    expect(unified.autoGenerated).toBe(false);
  });

  test("名前のある人物とモブをまとめたらモブ扱いをやめる", () => {
    const { unified } = unifyCharacters(
      character("char_001", "リン", { isMob: false }),
      character("char_002", "侍女", { isMob: true })
    );

    expect(unified.isMob).toBe(false);
  });

  test("公開範囲は狭いほうに合わせる", () => {
    // 広げると、意図せず外へ出る資料に載ってしまう
    const { unified } = unifyCharacters(
      character("char_001", "リン", { spoilerLevel: "public" }),
      character("char_002", "リンセップ", { spoilerLevel: "author_only" })
    );

    expect(unified.spoilerLevel).toBe("author_only");
  });

  test("掘り下げメモと食い違いは両方引き継ぐ", () => {
    const { unified } = unifyCharacters(
      character("char_001", "リン", {
        aiNotes: [
          {
            id: "note_001",
            createdAt: "",
            topic: "",
            text: "A",
            model: "m",
            source: "deep_dive",
          },
        ],
        conflicts: [{ field: "role", values: ["王女", "侍女"], chapters: [], note: null }],
      }),
      character("char_002", "リンセップ", {
        aiNotes: [
          {
            id: "note_001",
            createdAt: "",
            topic: "",
            text: "B",
            model: "m",
            source: "chat",
          },
        ],
      })
    );

    expect(unified.aiNotes).toHaveLength(2);
    expect(unified.conflicts).toHaveLength(1);
  });

  test("同じ人物どうしはまとめられない", () => {
    expect(() =>
      unifyCharacters(character("char_001", "リン"), character("char_001", "リン"))
    ).toThrow();
  });
});
