import { describe, expect, test } from "vitest";
import { planCharacterSeparation } from "../../src/core/characterSeparate";
import { emptyCharacter, type Character } from "../../src/models/character";

/**
 * 1つにまとめられた人物を、別人に分ける（設計書6.5.8）。
 *
 * 実データ（char_003 アジャン）を写して試す。
 */
function ajan(): Character {
  const character = emptyCharacter("char_003", "アジャン");
  character.aliases = ["アジャーノ", "アジャン様", "アジャーノさん"];
  character.summary = "村の長";
  character.role = "族長";
  character.personality = "温厚";
  character.appearedChapters = [1, 5, 6, 7, 8, 10, 15];
  character.changes = [
    {
      field: "role",
      value: "族長",
      chapter: 5,
      period: null,
      evidence: null,
      note: null,
    },
  ];
  character.authorNotes = "作者メモ";
  character.spoilerLevel = "staff_only";
  return character;
}

describe("別人に分ける", () => {
  test("選んだ別名が、新しい人物の名前になる", () => {
    const source = ajan();
    const plan = planCharacterSeparation(source, "アジャーノ", [source]);

    expect(plan.created.id).toBe("char_004");
    expect(plan.created.name).toBe("アジャーノ");
  });

  test("敬称違いの呼び方は一緒に移る", () => {
    const source = ajan();
    const plan = planCharacterSeparation(source, "アジャーノ", [source]);

    expect(plan.movedAliases).toEqual(["アジャーノ", "アジャーノさん"]);
    expect(plan.created.aliases).toEqual(["アジャーノさん"]);
  });

  test("関係のない別名は元に残る", () => {
    // 「アジャン様」は「アジャン」の呼び方であって、アジャーノではない
    const source = ajan();
    const plan = planCharacterSeparation(source, "アジャーノ", [source]);

    expect(plan.original.aliases).toEqual(["アジャン様"]);
  });

  test("中身は移さない。元にそのまま残る", () => {
    const source = ajan();
    const plan = planCharacterSeparation(source, "アジャーノ", [source]);

    expect(plan.original.summary).toBe("村の長");
    expect(plan.original.role).toBe("族長");
    expect(plan.original.personality).toBe("温厚");
    expect(plan.original.appearedChapters).toEqual([1, 5, 6, 7, 8, 10, 15]);
    expect(plan.original.changes).toHaveLength(1);
    expect(plan.original.authorNotes).toBe("作者メモ");

    expect(plan.created.summary).toBeNull();
    expect(plan.created.role).toBeNull();
    expect(plan.created.appearedChapters).toEqual([]);
    expect(plan.created.changes).toEqual([]);
    expect(plan.created.authorNotes).toBe("");
  });

  test("新しい人物は自動生成のまま（次の抽出で埋まるように）", () => {
    // false にすると、マージが登場話数しか足さなくなり、永久に空のままになる
    const source = ajan();
    const plan = planCharacterSeparation(source, "アジャーノ", [source]);

    expect(plan.created.autoGenerated).toBe(true);
  });

  test("公開範囲とモブ扱いは元から引き継ぐ", () => {
    // 既定（public）へ落とすと、隠していた人物が分けた拍子に資料へ出る
    const source = ajan();
    const plan = planCharacterSeparation(source, "アジャーノ", [source]);

    expect(plan.created.spoilerLevel).toBe("staff_only");
  });

  test("元の自動生成の印は、こちらでは変えない", () => {
    // 「AIに触らせない」は作者がその場で選ぶ（画面側の仕事）
    const source = ajan();
    const plan = planCharacterSeparation(source, "アジャーノ", [source]);

    expect(plan.original.autoGenerated).toBe(source.autoGenerated);
  });

  test("互いを別人として覚える", () => {
    const source = ajan();
    const plan = planCharacterSeparation(source, "アジャーノ", [source]);

    expect(plan.original.distinctFrom).toEqual([
      { name: "アジャーノ", id: "char_004" },
    ]);
    expect(plan.created.distinctFrom).toEqual([
      { name: "アジャン", id: "char_003" },
    ]);
  });

  test("読み仮名は機械で作る", () => {
    const source = ajan();
    const plan = planCharacterSeparation(source, "アジャーノ", [source]);

    expect(plan.created.reading).toBe("あじゃーの");
  });

  test("敬称を付けただけの呼び方は分けられない", () => {
    // 「アジャン様」は「アジャン」自身の呼び方であって、別人ではない。
    // ここを通すと、同じ人物が敬称の数だけ増えていく
    const source = ajan();
    expect(() =>
      planCharacterSeparation(source, "アジャン様", [source])
    ).toThrow(/自身の呼び名/);
  });

  test("2人目を分けても、1人目の記録が消えない", () => {
    const source = ajan();
    source.aliases = [...source.aliases, "ジャン"];
    const first = planCharacterSeparation(source, "アジャーノ", [source]);
    const second = planCharacterSeparation(first.original, "ジャン", [
      first.original,
      first.created,
    ]);

    expect(second.original.distinctFrom).toEqual([
      { name: "アジャーノ", id: "char_004" },
      { name: "ジャン", id: "char_005" },
    ]);
    expect(second.created.id).toBe("char_005");
  });

  test("別名に無い呼び方は分けられない", () => {
    const source = ajan();
    expect(() => planCharacterSeparation(source, "リナ", [source])).toThrow(
      /別名に/
    );
  });

  test("自分自身の名前は分けられない", () => {
    const source = ajan();
    expect(() => planCharacterSeparation(source, "アジャン", [source])).toThrow(
      /自身の呼び名/
    );
  });

  test("空の呼び名は分けられない", () => {
    const source = ajan();
    expect(() => planCharacterSeparation(source, "  ", [source])).toThrow();
  });

  test("同じ名前の人物が既にいるときは止める", () => {
    // 分けるのではなく、そちらへまとめるべき場面
    const source = ajan();
    const other = emptyCharacter("char_009", "アジャーノ");

    expect(() =>
      planCharacterSeparation(source, "アジャーノ", [source, other])
    ).toThrow(/既にいます/);
  });
});
