import { describe, expect, test } from "vitest";
import { unifyCharacters } from "../../src/core/characterUnify";
import { emptyCharacter, type Character } from "../../src/models/character";

function character(id: string, name: string, overrides: Partial<Character> = {}) {
  return { ...emptyCharacter(id, name), ...overrides };
}

describe("同一人物をまとめる", () => {
  test("取り下げる側の名前を別名として残す", () => {
    const { unified, retiredId } = unifyCharacters(
      character("char_003", "リンセップ・アウクト"),
      character("char_001", "リン")
    );

    expect(unified.id).toBe("char_003");
    expect(unified.name).toBe("リンセップ・アウクト");
    expect(unified.aliases).toContain("リン");
    expect(retiredId).toBe("char_001");
  });

  test("作者が書いた文章は両方残す", () => {
    // 「まとめたら作者メモが消えた」は取り返しがつかない
    const { unified } = unifyCharacters(
      character("char_001", "リン", { authorNotes: "残す側のメモ" }),
      character("char_002", "リンセップ", { authorNotes: "消える側のメモ" })
    );

    expect(unified.authorNotes).toContain("残す側のメモ");
    expect(unified.authorNotes).toContain("消える側のメモ");
  });

  test("同じ文章を二重に書かない", () => {
    const { unified } = unifyCharacters(
      character("char_001", "リン", { authorNotes: "同じメモ" }),
      character("char_002", "リンセップ", { authorNotes: "同じメモ" })
    );

    expect(unified.authorNotes).toBe("同じメモ");
  });

  test("片方にしかない項目を拾う", () => {
    const { unified } = unifyCharacters(
      character("char_001", "リン", { role: null, appearance: "銀髪" }),
      character("char_002", "リンセップ", { role: "王女", appearance: null })
    );

    expect(unified.role).toBe("王女");
    expect(unified.appearance).toBe("銀髪");
  });

  test("残す側の項目を取り下げ側で上書きしない", () => {
    const { unified } = unifyCharacters(
      character("char_001", "リン", { role: "王女" }),
      character("char_002", "リンセップ", { role: "villager" })
    );

    expect(unified.role).toBe("王女");
  });

  test("登場話数と関係を合わせる", () => {
    const { unified } = unifyCharacters(
      character("char_001", "リン", {
        appearedChapters: [1, 3],
        relations: [{ name: "マル", relation: "幼馴染" }],
      }),
      character("char_002", "リンセップ", {
        appearedChapters: [3, 5],
        relations: [
          { name: "マル", relation: "幼馴染" },
          { name: "国王", relation: "父" },
        ],
      })
    );

    expect(unified.appearedChapters).toEqual([1, 3, 5]);
    expect(unified.relations).toEqual([
      { name: "マル", relation: "幼馴染" },
      { name: "国王", relation: "父" },
    ]);
  });

  test("呼称の宛先をまとめた後の名前へ付け替える", () => {
    const absorb = character("char_001", "リン", {
      addressTerms: [
        {
          targetName: "リン",
          targetId: null,
          authorLocked: false,
          forms: [
            {
              term: "リンちゃん",
              category: null,
              context: null,
              firstChapter: null,
              lastChapter: null,
              status: "current",
              evidence: null,
            },
          ],
        },
      ],
    });

    const { unified } = unifyCharacters(
      character("char_003", "リンセップ・アウクト"),
      absorb
    );

    // 付け替えないと、誰に向けた呼称なのか分からなくなる
    expect(unified.addressTerms[0].targetName).toBe("リンセップ・アウクト");
    expect(unified.addressTerms[0].forms[0].term).toBe("リンちゃん");
  });

  test("まとめた人物は以後の抽出で上書きされない", () => {
    const { unified } = unifyCharacters(
      character("char_001", "リン"),
      character("char_002", "リンセップ")
    );

    // 作者の判断で1件にしたものを、次の抽出で2件へ戻されては困る
    expect(unified.autoGenerated).toBe(false);
  });

  test("名前のある人物とモブをまとめたらモブ扱いをやめる", () => {
    const { unified } = unifyCharacters(
      character("char_001", "リン", { isMob: false }),
      character("char_002", "侍女", { isMob: true })
    );

    expect(unified.isMob).toBe(false);
  });

  test("公開範囲は狭いほうに合わせる", () => {
    // 広げると、意図せず外へ出る資料に載ってしまう
    const { unified } = unifyCharacters(
      character("char_001", "リン", { spoilerLevel: "public" }),
      character("char_002", "リンセップ", { spoilerLevel: "author_only" })
    );

    expect(unified.spoilerLevel).toBe("author_only");
  });

  test("掘り下げメモと食い違いは両方引き継ぐ", () => {
    const { unified } = unifyCharacters(
      character("char_001", "リン", {
        aiNotes: [
          {
            id: "note_001",
            createdAt: "",
            topic: "",
            text: "A",
            model: "m",
            source: "deep_dive",
          },
        ],
        conflicts: [{ field: "role", values: ["王女", "侍女"], chapters: [], note: null }],
      }),
      character("char_002", "リンセップ", {
        aiNotes: [
          {
            id: "note_001",
            createdAt: "",
            topic: "",
            text: "B",
            model: "m",
            source: "chat",
          },
        ],
      })
    );

    expect(unified.aiNotes).toHaveLength(2);
    expect(unified.conflicts).toHaveLength(1);
  });

  test("同じ項目の食い違いは1つにまとめる", () => {
    // 両方に同じ項目の食い違いがあると、並べただけでは同じ見出しが2つ出る。
    // さらに、この先のマージは `field` で最初の1件しか見ないので、
    // 2件目は**表示されるのに二度と更新されない**取り残しになる
    const { unified } = unifyCharacters(
      character("char_001", "リン", {
        conflicts: [
          {
            field: "appearance",
            values: ["黒髪", "銀髪"],
            chapters: [],
            note: null,
            observations: [
              { value: "黒髪", chapters: [1] },
              { value: "銀髪", chapters: [7] },
            ],
          },
        ],
      }),
      character("char_002", "リンセップ", {
        conflicts: [
          {
            field: "appearance",
            values: ["銀髪", "赤髪"],
            chapters: [],
            note: null,
            observations: [
              { value: "銀髪", chapters: [9] },
              { value: "赤髪", chapters: [12] },
            ],
          },
        ],
      })
    );

    expect(unified.conflicts).toHaveLength(1);
    expect(unified.conflicts[0].values).toEqual(["黒髪", "銀髪", "赤髪"]);
    // 同じ値の話数は合わせる
    expect(unified.conflicts[0].observations).toEqual([
      { value: "黒髪", chapters: [1] },
      { value: "銀髪", chapters: [7, 9] },
      { value: "赤髪", chapters: [12] },
    ]);
  });

  test("同じ人物どうしはまとめられない", () => {
    expect(() =>
      unifyCharacters(character("char_001", "リン"), character("char_001", "リン"))
    ).toThrow();
  });
});

/**
 * まとめる操作と、別人の記録（distinctFrom、設計書6.5.8）の関係。
 *
 * まとめる側は distinctFrom を意識せずに書かれていた（0.22.7より前からある
 * 関数なので当然だが）、そのままだと2通りに壊れる。
 *
 * 1. **吸収される側の記録が黙って消える。** アジャンを別レコードへ吸収させると
 *    「アジャーノは別人」という判断が失われ、次の抽出で別名が戻る
 * 2. **相手を指す記録が残る。** 別人と決めた2人を（手で戻すなどして）まとめたとき、
 *    「自分の別名は別人だ」という自己矛盾したレコードができ、その別名では
 *    永久に照合されなくなる
 */
describe("まとめたとき、別人の記録を失わない", () => {
  test("吸収される側の別人の記録が、まとめた後も残る", () => {
    const keep = character("char_009", "アジャン様");
    const absorb = character("char_003", "アジャン", {
      distinctFrom: [{ name: "アジャーノ", id: "char_010" }],
    });

    const { unified } = unifyCharacters(keep, absorb);

    expect(unified.distinctFrom).toEqual([
      { name: "アジャーノ", id: "char_010" },
    ]);
  });

  test("両方の記録は重複なく合わさる", () => {
    const keep = character("char_001", "リン", {
      distinctFrom: [{ name: "アジャーノ", id: "char_010" }],
    });
    const absorb = character("char_002", "リンセップ", {
      distinctFrom: [
        { name: "アジャーノ", id: "char_010" },
        { name: "ソフィ", id: null },
      ],
    });

    const { unified } = unifyCharacters(keep, absorb);

    expect(unified.distinctFrom).toEqual([
      { name: "アジャーノ", id: "char_010" },
      { name: "ソフィ", id: null },
    ]);
  });

  test("互いを指す記録は、まとめたときに消す", () => {
    // 別人と決めた2人を、作者があらためて「同じだった」とまとめ直す場面。
    // 相手を指す記録を残すと「自分の別名は別人だ」という矛盾になり、
    // その別名では二度と照合されない
    const keep = character("char_003", "アジャン", {
      distinctFrom: [{ name: "アジャーノ", id: "char_010" }],
    });
    const absorb = character("char_010", "アジャーノ", {
      aliases: ["アジャーノさん"],
      distinctFrom: [{ name: "アジャン", id: "char_003" }],
    });

    const { unified } = unifyCharacters(keep, absorb);

    expect(unified.distinctFrom).toEqual([]);
    expect(unified.aliases).toContain("アジャーノ");
  });

  test("敬称違いで相手を指す記録も消す", () => {
    // 記録は敬称を落とした形で照合される（characterMerge と同じ規則）。
    // 名前の完全一致だけで消すと「アジャーノさん」を指す記録が残る
    const keep = character("char_003", "アジャン", {
      distinctFrom: [{ name: "アジャーノさん", id: null }],
    });
    const absorb = character("char_010", "アジャーノ");

    const { unified } = unifyCharacters(keep, absorb);

    expect(unified.distinctFrom).toEqual([]);
  });
});
