import { describe, expect, it } from "vitest";
import {
  buildChronicle,
  chronicleCharacters,
  filterChronicle,
  groupByTimepoint,
  sortByTimeline,
  UNASSIGNED_SECTION_LABEL,
  UNKNOWN_CHAPTER_LABEL,
  type ChronicleEpisode,
} from "../../src/core/chronicle";
import { emptyCharacter, type Character } from "../../src/models/character";
import { emptyForeshadow, type Foreshadow } from "../../src/models/foreshadow";
import {
  emptySynopsisSet,
  type ChapterSynopsisSet,
} from "../../src/models/synopsis";
import { emptyTimeline, type Timeline } from "../../src/models/timeline";

/**
 * 年表の組み立て（設計書6.39.1・6.39.2）。
 *
 * 材料はすべて既にある記録である。ここで確かめるのは
 * 「話ごとに正しく束ねられたか」と「時系列で段が分かれるか」だけで、
 * 見え方は画面の試験と実機に任せる。
 */

const WORK_ROOT = "C:/works/w1";

function episode(
  chapter: number | null,
  name: string,
  options: {
    title?: string | null;
    chars?: number;
    chapterEnd?: number | null;
  } = {}
): ChronicleEpisode {
  return {
    filePath: `${WORK_ROOT}/本文/${name}`,
    fileName: name,
    chapterStart: chapter,
    chapterEnd: options.chapterEnd ?? chapter,
    subtitle: options.title ?? null,
    metaTitle: null,
    kind: "本編",
    date: null,
    dateSeq: null,
    counts: {
      gross: options.chars ?? 100,
      net: options.chars ?? 100,
      lines: 1,
      paragraphs: 1,
      manuscriptLines: 1,
    },
  };
}

function character(
  id: string,
  name: string,
  patch: Partial<Character> = {}
): Character {
  return { ...emptyCharacter(id, name), ...patch };
}

function foreshadow(patch: Partial<Foreshadow>): Foreshadow {
  return { ...emptyForeshadow("foreshadow_001", "銀の時計"), ...patch };
}

function synopses(
  entries: Array<{ chapter: number; fileName: string; synopsis: string }>
): ChapterSynopsisSet {
  const set = emptySynopsisSet();
  return {
    ...set,
    episodes: entries.map((entry) => ({
      chapter: entry.chapter,
      fileName: entry.fileName,
      title: null,
      synopsis: entry.synopsis,
      sourceHash: "",
      model: null,
      promptVersion: null,
      autoGenerated: true,
      authorNotes: "",
      emotion: null,
      updatedAt: null,
    })),
  };
}

const EPISODES = [
  episode(1, "第01話.txt", { title: "はじまり" }),
  episode(2, "第02話.txt"),
  episode(3, "第03話.txt"),
];

function build(
  episodes: ChronicleEpisode[] = EPISODES,
  characters: Character[] = [],
  set: ChapterSynopsisSet | null = null,
  foreshadows: Foreshadow[] = [],
  timeline: Timeline | null = null
) {
  return buildChronicle(episodes, characters, set, foreshadows, timeline, {
    workRoot: WORK_ROOT,
  });
}

describe("年表の組み立て", () => {
  it("話数順に並び、話数・題・字数が載る", () => {
    const rows = build([
      episode(3, "第03話.txt"),
      episode(1, "第01話.txt", { title: "はじまり", chars: 1200 }),
    ]);

    expect(rows.map((row) => row.chapter)).toEqual([1, 3]);
    expect(rows[0].chapterLabel).toBe("第1話");
    expect(rows[0].title).toBe("はじまり");
    expect(rows[0].chars).toBe(1200);
  });

  it("話数の無いファイルは末尾に「話数なし」で載る", () => {
    // **推測で番号を振らない。** 番号を振ると、作者が付けていない順序を
    // 拡張機能が決めたことになる
    const rows = build([
      episode(null, "あとがき.txt"),
      episode(1, "第01話.txt"),
    ]);

    expect(rows.map((row) => row.fileName)).toEqual([
      "第01話.txt",
      "あとがき.txt",
    ]);
    expect(rows[1].chapterLabel).toBe(UNKNOWN_CHAPTER_LABEL);
  });

  it("あらすじが行に載る", () => {
    const rows = build(
      EPISODES,
      [],
      synopses([
        { chapter: 2, fileName: "第02話.txt", synopsis: "太志が港へ向かう。" },
      ])
    );

    expect(rows[1].synopsis).toBe("太志が港へ向かう。");
    expect(rows[0].synopsis).toBeNull();
  });

  it("登場人物が行に載る", () => {
    const rows = build(EPISODES, [
      character("char_001", "太志", { appearedChapters: [1, 3] }),
      character("char_002", "文佳", { appearedChapters: [3] }),
    ]);

    expect(rows[0].appeared.map((entry) => entry.name)).toEqual(["太志"]);
    expect(rows[1].appeared).toEqual([]);
    expect(rows[2].appeared.map((entry) => entry.name)).toEqual([
      "太志",
      "文佳",
    ]);
  });

  it("変化・能力・呼称・伏線が、それぞれの話に載る", () => {
    const rows = build(
      EPISODES,
      [
        character("char_001", "太志", {
          changes: [
            {
              field: "appearance",
              value: "黒髪",
              chapters: [1],
              timepointId: null,
              note: null,
              evidence: null,
              source: "author",
            },
            {
              field: "appearance",
              value: "銀髪",
              chapters: [2],
              timepointId: null,
              note: null,
              evidence: null,
              source: "author",
            },
          ],
          abilities: [
            {
              abilityId: null,
              name: "火球",
              mastery: "習得済み",
              note: null,
              firstChapter: 2,
              appearedChapters: [2],
              evidence: null,
              autoGenerated: true,
            },
          ],
          addressTerms: [
            {
              targetName: "サラ",
              targetId: null,
              authorLocked: false,
              forms: [
                {
                  term: "先生",
                  category: null,
                  context: null,
                  firstChapter: 2,
                  lastChapter: 3,
                  status: "past",
                  evidence: null,
                },
              ],
            },
          ],
        }),
      ],
      null,
      [
        foreshadow({
          plantedChapter: 1,
          status: "resolved",
          resolvedChapter: 3,
        }),
      ]
    );

    const texts = rows.map((row) => row.events.map((event) => event.text));
    expect(texts[0]).toEqual(["外見：黒髪", "伏線『銀の時計』を張る"]);
    expect(texts[1]).toEqual([
      "外見：黒髪 → 銀髪",
      "能力『火球』を習得",
      "サラを『先生』と呼び始める",
    ]);
    expect(texts[2]).toEqual([
      "サラを『先生』と呼ばなくなる",
      "伏線『銀の時計』を回収",
    ]);
  });

  it("changes の chapters が複数なら、いちばん早い話に載せる", () => {
    const rows = build(EPISODES, [
      character("char_001", "太志", {
        changes: [
          {
            field: "role",
            value: "隊長",
            chapters: [3, 2],
            timepointId: null,
            note: null,
            evidence: null,
            source: "author",
          },
        ],
      }),
    ]);

    expect(rows[1].events.map((event) => event.text)).toEqual(["役割：隊長"]);
    expect(rows[2].events).toEqual([]);
  });

  it("同じ話に変化が複数あっても、全部載る", () => {
    // 畳むと、その話で何が変わったのかが読めなくなる
    const rows = build(EPISODES, [
      character("char_001", "太志", {
        changes: [
          {
            field: "appearance",
            value: "銀髪",
            chapters: [2],
            timepointId: null,
            note: null,
            evidence: null,
            source: "author",
          },
          {
            field: "role",
            value: "隊長",
            chapters: [2],
            timepointId: null,
            note: null,
            evidence: null,
            source: "author",
          },
        ],
      }),
    ]);

    expect(rows[1].events.map((event) => event.text)).toEqual([
      "外見：銀髪",
      "役割：隊長",
    ]);
  });

  it("回収していない伏線は、回収の行を作らない", () => {
    // 「意図して開けたまま」に話数が残っていても、閉じたようには見せない
    const rows = build(EPISODES, [], null, [
      foreshadow({
        plantedChapter: 1,
        status: "intentional",
        resolvedChapter: 3,
      }),
    ]);

    expect(rows[2].events).toEqual([]);
  });

  it("話数の分からない変化は、次の変化の元の値として使うだけ", () => {
    // 「それ以前」は載せる先が無い。捨てると「→」の左が消える
    const rows = build(EPISODES, [
      character("char_001", "太志", {
        changes: [
          {
            field: "appearance",
            value: "黒髪",
            chapters: [],
            timepointId: null,
            note: null,
            evidence: null,
            source: "author",
          },
          {
            field: "appearance",
            value: "銀髪",
            chapters: [2],
            timepointId: null,
            note: null,
            evidence: null,
            source: "author",
          },
        ],
      }),
    ]);

    expect(rows[0].events).toEqual([]);
    expect(rows[1].events.map((event) => event.text)).toEqual([
      "外見：黒髪 → 銀髪",
    ]);
  });

  it("合本（1ファイルに複数話）は、範囲の中の出来事をすべて受ける", () => {
    const rows = build(
      [episode(1, "全話.txt", { chapterEnd: 20 })],
      [character("char_001", "太志", { appearedChapters: [3, 12] })]
    );

    expect(rows).toHaveLength(1);
    // 同じ人を2回並べない
    expect(rows[0].appeared).toEqual([{ id: "char_001", name: "太志" }]);
  });
});

describe("時期と系統", () => {
  function timelineWith(): Timeline {
    return {
      ...emptyTimeline(),
      lines: [
        {
          id: "ln_001",
          label: "本編",
          kind: "main",
          canonical: true,
          branchFrom: null,
          note: "",
        },
        {
          id: "ln_002",
          label: "IF・もし文佳が生きていたら",
          kind: "branch",
          canonical: false,
          branchFrom: "tp_002",
          note: "",
        },
      ],
      timepoints: [
        {
          id: "tp_001",
          lineId: "ln_001",
          label: "十年前・火事の夜",
          absolute: null,
          note: "",
        },
        {
          id: "tp_002",
          lineId: "ln_001",
          label: "本編開始",
          absolute: "四月",
          note: "",
        },
        {
          id: "tp_003",
          lineId: "ln_002",
          label: "もしもの春",
          absolute: null,
          note: "",
        },
      ],
      episodes: [
        { filePath: "本文/第01話.txt", timepointId: "tp_002", note: "" },
        { filePath: "本文/第03話.txt", timepointId: "tp_001", note: "回想" },
        { filePath: "本文/第04話.txt", timepointId: "tp_003", note: "" },
      ],
    };
  }

  const EPISODES4 = [...EPISODES, episode(4, "第04話.txt")];

  it("時期と系統が行に載る", () => {
    const rows = build(EPISODES4, [], null, [], timelineWith());

    expect(rows[0].timepoint?.label).toBe("本編開始");
    expect(rows[0].timepoint?.absolute).toBe("四月");
    expect(rows[0].line?.label).toBe("本編");
    // 対応づけの無い話は本編とみなす（設計書6.18）
    expect(rows[1].timepoint).toBeNull();
    expect(rows[1].line?.label).toBe("本編");
    expect(rows[3].line?.canonical).toBe(false);
  });

  it("時系列順では、時期の配列の順に並び直る", () => {
    const sections = sortByTimeline(
      build(EPISODES4, [], null, [], timelineWith()),
      timelineWith()
    );

    const main = sections[0];
    expect(main.label).toBe("本編");
    // tp_001（十年前）が配列の先頭なので、第3話が第1話より前へ来る
    expect(main.rows.map((row) => row.chapter)).toEqual([3, 1]);
  });

  it("canonical が false の系統は、別の段になる", () => {
    // IF編の話が本編の年表に混ざると、資料として使えない（6.39.5）
    const sections = sortByTimeline(
      build(EPISODES4, [], null, [], timelineWith()),
      timelineWith()
    );

    const alternate = sections.find((section) => section.kind === "alternate");
    expect(alternate?.label).toBe("IF・もし文佳が生きていたら");
    expect(alternate?.rows.map((row) => row.chapter)).toEqual([4]);
    expect(
      sections[0].rows.some((row) => row.chapter === 4),
      "IF編の話が本編の段に混ざっている"
    ).toBe(false);
  });

  it("時期の付いていない話は、別の段に集める", () => {
    // 黙って本編の末尾へ足すと、作者が決めていない順序を決めたことになる
    const sections = sortByTimeline(
      build(EPISODES4, [], null, [], timelineWith()),
      timelineWith()
    );

    const unassigned = sections[sections.length - 1];
    expect(unassigned.label).toBe(UNASSIGNED_SECTION_LABEL);
    expect(unassigned.rows.map((row) => row.chapter)).toEqual([2]);
  });

  it("時期を1つも決めていなければ、全部が「時期未設定」になる", () => {
    const sections = sortByTimeline(build(), emptyTimeline());

    expect(sections).toHaveLength(1);
    expect(sections[0].kind).toBe("unassigned");
    expect(sections[0].rows).toHaveLength(3);
  });

  it("同じ時期の話は、続きのまとまりになる", () => {
    const sections = sortByTimeline(
      build(EPISODES4, [], null, [], timelineWith()),
      timelineWith()
    );
    const groups = groupByTimepoint(sections[0].rows);

    expect(groups.map((group) => group.label)).toEqual([
      "十年前・火事の夜",
      "本編開始（四月）",
    ]);
  });
});

describe("絞り込み", () => {
  const CHARACTERS = [
    character("char_001", "太志", {
      appearedChapters: [1, 2],
      abilities: [
        {
          abilityId: null,
          name: "火球",
          mastery: "習得済み",
          note: null,
          firstChapter: 2,
          appearedChapters: [2],
          evidence: null,
          autoGenerated: true,
        },
      ],
    }),
    character("char_002", "文佳", { appearedChapters: [3] }),
  ];

  it("人物で絞ると、その人の登場と出来事だけが残る", () => {
    const rows = filterChronicle(build(EPISODES, CHARACTERS), {
      characterId: "char_001",
    });

    expect(rows.map((row) => row.chapter)).toEqual([1, 2]);
    expect(rows[1].appeared.map((entry) => entry.name)).toEqual(["太志"]);
    expect(rows[1].events.map((event) => event.text)).toEqual([
      "能力『火球』を習得",
    ]);
  });

  it("種類で絞ると、その出来事の無い話は落ちる", () => {
    const rows = filterChronicle(build(EPISODES, CHARACTERS), {
      kinds: ["ability"],
    });

    expect(rows.map((row) => row.chapter)).toEqual([2]);
  });

  it("伏線は人物に紐づかないので、人物で絞ると出ない", () => {
    const rows = filterChronicle(
      build(EPISODES, CHARACTERS, null, [foreshadow({ plantedChapter: 3 })]),
      { characterId: "char_001" }
    );

    expect(rows.some((row) => row.chapter === 3)).toBe(false);
  });

  it("絞り込みの選択肢は、年表に出てくる人物だけ", () => {
    // 資料の全員を並べると、選んだ先が必ず空になる人が混ざる
    const options = chronicleCharacters(
      build(EPISODES, [
        ...CHARACTERS,
        character("char_003", "まだ出ていない人"),
      ])
    );

    expect(options.map((entry) => entry.name)).toEqual(["太志", "文佳"]);
  });
});
