import { describe, expect, test } from "vitest";
import {
  buildEmotionCurveMarkdown,
  collectEmotionPoints,
} from "../../src/core/emotionCurve";
import {
  buildSynopsisMarkdown,
  parseSynopsisMarkdown,
} from "../../src/core/synopsisDoc";
import type { ChapterEmotion, ChapterSynopsis } from "../../src/models/synopsis";
import { parseSynopsisSet } from "../../src/models/synopsis";
import { validateSynopsisResult } from "../../src/core/synopsisValidation";

function emotion(overrides: Partial<ChapterEmotion> = {}): ChapterEmotion {
  return { intensity: 5, valence: 0, dominant: null, reason: "理由", ...overrides };
}

function episode(
  chapter: number,
  emo: ChapterEmotion | null = emotion()
): ChapterSynopsis {
  return {
    chapter,
    fileName: `${String(chapter).padStart(3, "0")}.txt`,
    title: null,
    synopsis: "あらすじ",
    sourceHash: "hash",
    model: "test",
    promptVersion: "2.0",
    autoGenerated: true,
    authorNotes: "",
    emotion: emo,
    updatedAt: null,
  };
}

describe("感情曲線の材料", () => {
  test("感情値のある話だけを話数順に取り出す", () => {
    const points = collectEmotionPoints([
      episode(1),
      episode(2, null),
      episode(3),
    ]);

    expect(points.map((point) => point.chapter)).toEqual([1, 3]);
    expect(points[0].label).toBe("第1話");
  });
});

describe("感情曲線の組み立て", () => {
  const episodes = [
    episode(1, emotion({ intensity: 2, valence: -1, dominant: "哀" })),
    episode(2, emotion({ intensity: 7, valence: -4, dominant: "怒" })),
    episode(3, emotion({ intensity: 9, valence: 3, dominant: "喜" })),
  ];

  test("SVGと文字のグラフを両方出す", () => {
    // SVGを剥がす場所（GitHub上での閲覧など）でも起伏が読めるようにする
    const markdown = buildEmotionCurveMarkdown(episodes);

    expect(markdown).toContain("<svg");
    expect(markdown).toContain("盛り上がり");
    expect(markdown).toMatch(/[▁▂▃▄▅▆▇█]/);
  });

  test("話ごとの内訳に理由を添える", () => {
    // 数値だけでは作者が確かめようがない
    const markdown = buildEmotionCurveMarkdown(episodes);

    expect(markdown).toContain("| 第2話 | 7 | -4 | 怒 |");
    expect(markdown).toContain("理由");
  });

  test("明暗は符号を付けて出す", () => {
    const markdown = buildEmotionCurveMarkdown(episodes);

    expect(markdown).toContain("| +3 |");
  });

  test("色ではなく線の種類で見分けられるようにする", () => {
    // 印刷やモノクロ表示でも2本を区別できる必要がある
    const markdown = buildEmotionCurveMarkdown(episodes);

    expect(markdown).toContain("stroke-dasharray");
  });

  test("テーマに依らない色を使う", () => {
    // 明るいテーマと暗いテーマの両方で読めるようにする
    const markdown = buildEmotionCurveMarkdown(episodes);

    expect(markdown).toContain("currentColor");
    expect(markdown).not.toMatch(/#[0-9a-f]{6}/i);
  });

  test("1話しか無ければ描かない（点1つでは曲線にならない）", () => {
    expect(buildEmotionCurveMarkdown([episode(1)])).toBe("");
  });

  test("感情値が1つも無ければ節ごと出さない", () => {
    expect(buildEmotionCurveMarkdown([episode(1, null), episode(2, null)])).toBe(
      ""
    );
  });

  test("1話＝1文字で、目盛りと本数が揃う", () => {
    // ずれると、どの山が何話なのか読み取れなくなる。
    // 見出しの幅は全角・半角が混ざるので、データ部分の文字数で確かめる
    const markdown = buildEmotionCurveMarkdown(episodes);
    const lines = markdown.split("\n");
    // 縦棒の並びだけを数える（行末には実際の幅を書いている）
    const barsOf = (line: string) => (line.match(/[▁▂▃▄▅▆▇█]/gu) ?? []).length;

    const intensity = lines.find((line) => line.startsWith("盛り上がり"))!;
    const valence = lines.find((line) => line.startsWith("明暗"))!;
    const axis = lines[lines.indexOf(valence) + 1];

    expect(barsOf(intensity)).toBe(episodes.length);
    expect(barsOf(valence)).toBe(episodes.length);
    expect([...axis.trim()].length).toBe(episodes.length);
  });

  test("引き伸ばした幅を明記する（0〜10の中での高さと誤解させない）", () => {
    const markdown = buildEmotionCurveMarkdown(episodes);

    expect(markdown).toContain("(2〜9)");
    expect(markdown).toContain("実際に出ている幅へ合わせて");
  });

  test("全話が同じ値なら、高低があるように見せない", () => {
    const flat = [
      episode(1, emotion({ intensity: 5, valence: 0 })),
      episode(2, emotion({ intensity: 5, valence: 0 })),
    ];
    const markdown = buildEmotionCurveMarkdown(flat);

    expect(markdown).toContain("（一定）");
    // 同じ縦棒が並ぶ（山があるように見えない）
    expect(markdown).toMatch(/盛り上がり (.)\1/u);
  });

  test("見出しの表示幅を揃える（等幅で縦に並ぶ）", () => {
    // 全角は2桁、半角は1桁として数える
    const width = (text: string) =>
      [...text].reduce(
        (sum, char) => sum + (/[　-鿿＀-￯]/.test(char) ? 2 : 1),
        0
      );
    const markdown = buildEmotionCurveMarkdown(episodes);
    const lines = markdown.split("\n");
    const prefixOf = (line: string) => width(line.match(/^\S*\s+/u)![0]);

    const intensity = lines.find((line) => line.startsWith("盛り上がり"))!;
    const valence = lines.find((line) => line.startsWith("明暗"))!;

    expect(prefixOf(intensity)).toBe(prefixOf(valence));
  });
});

describe("紹介文の文書への差し込み", () => {
  const episodes = [
    episode(1, emotion({ intensity: 2 })),
    episode(2, emotion({ intensity: 8 })),
  ];

  test("紹介文とあらすじの間に置く", () => {
    const markdown = buildSynopsisMarkdown(
      "作品",
      { catchphrase: null, blurb: "紹介文。" },
      "### 第1話\n\nあらすじ本文。",
      buildEmotionCurveMarkdown(episodes)
    );

    expect(markdown.indexOf("紹介文。")).toBeLessThan(
      markdown.indexOf("## 感情曲線")
    );
    expect(markdown.indexOf("## 感情曲線")).toBeLessThan(
      markdown.indexOf("## 各話あらすじ")
    );
  });

  test("読み戻しても紹介文に取り込まない（二重に積もらせない）", () => {
    const doc = { catchphrase: "コピー", blurb: "紹介文。" };
    const curve = buildEmotionCurveMarkdown(episodes);
    const first = buildSynopsisMarkdown("作品", doc, "### 第1話\n\n本文。", curve);

    expect(parseSynopsisMarkdown(first)).toEqual(doc);

    const second = buildSynopsisMarkdown(
      "作品",
      parseSynopsisMarkdown(first),
      "### 第1話\n\n本文。",
      curve
    );
    expect(second).toBe(first);
  });
});

describe("感情値の検証", () => {
  const base = { synopsis: "あらすじ", subtitles: [], confidence: "high" };

  test("範囲外は捨てずに丸める", () => {
    // 捨てるとその話だけ曲線が途切れ、かえって読み取りにくい
    const result = validateSynopsisResult({
      ...base,
      emotion: { intensity: 12, valence: -9, dominant: "喜", reason: "理由" },
    });

    expect(result.emotion?.intensity).toBe(10);
    expect(result.emotion?.valence).toBe(-5);
  });

  test("小数は整数に丸める", () => {
    const result = validateSynopsisResult({
      ...base,
      emotion: { intensity: 7.6, valence: 1.2, dominant: null, reason: "" },
    });

    expect(result.emotion?.intensity).toBe(8);
    expect(result.emotion?.valence).toBe(1);
  });

  test("数値が読めなければ点として打たない", () => {
    const result = validateSynopsisResult({
      ...base,
      emotion: { intensity: null, valence: 2, dominant: null, reason: "" },
    });

    expect(result.emotion).toBeNull();
  });

  test("知らない感情名は null にする", () => {
    const result = validateSynopsisResult({
      ...base,
      emotion: { intensity: 5, valence: 0, dominant: "驚", reason: "" },
    });

    expect(result.emotion?.dominant).toBeNull();
  });

  test("emotion が無くても壊れない（古い応答）", () => {
    expect(validateSynopsisResult(base).emotion).toBeNull();
  });
});

describe("保存したJSONの読み取り", () => {
  test("感情値を読み戻せる", () => {
    const set = parseSynopsisSet({
      schemaVersion: "0.1",
      episodes: [
        {
          fileName: "001.txt",
          synopsis: "あらすじ",
          emotion: { intensity: 8, valence: -3, dominant: "怒", reason: "対立" },
        },
      ],
    });

    expect(set.episodes[0].emotion).toEqual({
      intensity: 8,
      valence: -3,
      dominant: "怒",
      reason: "対立",
    });
  });

  test("感情値が壊れていても、あらすじは読める", () => {
    // ここで例外にすると、あらすじ全体が開けなくなる。
    // 感情値はグラフの飾りで、あらすじ本体より重くはない
    const set = parseSynopsisSet({
      schemaVersion: "0.1",
      episodes: [
        { fileName: "001.txt", synopsis: "あらすじ", emotion: "こわれた値" },
      ],
    });

    expect(set.episodes[0].synopsis).toBe("あらすじ");
    expect(set.episodes[0].emotion).toBeNull();
  });

  test("古い記録（感情値が無い）も読める", () => {
    const set = parseSynopsisSet({
      schemaVersion: "0.1",
      episodes: [{ fileName: "001.txt", synopsis: "あらすじ" }],
    });

    expect(set.episodes[0].emotion).toBeNull();
  });
});
