import { beforeEach, describe, expect, test, vi } from "vitest";
import { commands, window, workspace } from "./support/vscodeStub";
import type { AIRegistry } from "../../src/ai/registry";
import { splitIntoChunks, type Chunk } from "../../src/core/chunker";
import type { WorkEntry } from "../../src/models/types";
import {
  AIError,
  recoveryForAIError,
} from "../../src/ai/types";

const state = vi.hoisted(() => ({
  saveAll: vi.fn(),
  cacheSet: vi.fn(),
  cacheSave: vi.fn(),
  dirtyDocumentPaths: vi.fn(),
  generate: vi.fn(),
  cachedResults: new Map<string, unknown>(),
  mergeResult: undefined as unknown,
  providerId: "ollama" as "ollama" | "claude",
  configured: true,
  testConnection: vi.fn(),
  savedAbilities: [] as unknown[],
  savedLocations: [] as unknown[],
  savedOrganizations: [] as unknown[],
  savedWorldItems: [] as unknown[],
  /** 既定のチャンク列を上書きしたいテストだけが設定する */
  chunks: undefined as unknown[] | undefined,
  CharacterStoreError: class CharacterStoreError extends Error {
    readonly batchProgress:
      | {
          completedIds: string[];
          ambiguousIds: string[];
          remainingIds: string[];
        }
      | undefined;

    constructor(
      message: string,
      readonly kind:
        | "modified_externally"
        | "path_conflict"
        | "unsaved_changes"
        | "io_error",
      options?: {
        persistenceState?: "not_saved" | "ambiguous";
        recoveryPaths?: string[];
        batchProgress?: {
          completedIds: string[];
          ambiguousIds: string[];
          remainingIds: string[];
        };
      }
    ) {
      super(message);
      this.name = "CharacterStoreError";
      this.batchProgress = options?.batchProgress;
      this.persistenceState = options?.persistenceState ?? "not_saved";
      this.recoveryPaths = options?.recoveryPaths ?? [];
    }
    readonly persistenceState: "not_saved" | "ambiguous";
    readonly recoveryPaths: string[];
  },
}));

vi.mock("../../src/ai/registry", () => ({
  ensureConfigured: vi.fn(async () =>
    state.configured
      ? {
          provider: {
            id: state.providerId,
            generate: state.generate,
            testConnection: state.testConnection,
          },
          model: "test-model",
        }
      : undefined
  ),
}));

vi.mock("../../src/core/scanner", () => ({
  scanWork: vi.fn(async () => ({
    episodes: [
      {
        filePath: "001.txt",
        fileName: "001.txt",
        chapterStart: 1,
        chapterEnd: 1,
      },
    ],
  })),
}));

vi.mock("../../src/core/textFile", () => ({
  readTextFile: vi.fn(async () => ({
    text: "灯が歩いた。",
    hasConflictMarkers: false,
  })),
}));

const chunks: Chunk[] = [
  {
    filePath: "001.txt",
    index: 0,
    text: "灯が歩いた。",
    hash: "chunk-1",
    chapterStart: 1,
    chapterEnd: 1,
  },
  {
    filePath: "001.txt",
    index: 1,
    text: "澪が歩いた。",
    hash: "chunk-2",
    chapterStart: 1,
    chapterEnd: 1,
  },
];

/** 追加のチャンクを要するテスト（接続断の打ち切り等）だけが差し替える */
function chunkFixture(count: number): Chunk[] {
  return Array.from({ length: count }, (_, index) => ({
    filePath: "001.txt",
    index,
    text: `本文${index + 1}。`,
    hash: `chunk-${index + 1}`,
    chapterStart: 1,
    chapterEnd: 1,
  }));
}

vi.mock("../../src/core/chunker", () => ({
  decideChunkSize: vi.fn(() => 1000),
  splitIntoChunks: vi.fn(() => state.chunks ?? chunks),
}));

vi.mock("../../src/core/characterStore", () => ({
  CharacterStoreError: state.CharacterStoreError,
  CharacterStore: class {
    async loadAll() {
      return { characters: [], errors: [] };
    }
    async dirtyDocumentPaths() {
      return state.dirtyDocumentPaths();
    }
    async saveAll(characters: unknown[]) {
      return state.saveAll(characters);
    }
  },
}));

vi.mock("../../src/core/characterMerge", async (importOriginal) => {
  const actual = await importOriginal<
    typeof import("../../src/core/characterMerge")
  >();
  return {
    ...actual,
    mergeExtractedCharacters: (
      ...args: Parameters<typeof actual.mergeExtractedCharacters>
    ) =>
      state.mergeResult ?? actual.mergeExtractedCharacters(...args),
  };
});

// 能力・場所の保存はこのテストの対象外。人物フローに集中させる。
// 収集した件数だけ state に残し、必要なテストから参照する。
vi.mock("../../src/core/abilityStore", () => ({
  AbilitySystemStore: class {
    async load() {
      return {
        schemaVersion: "0.1",
        abilityTerm: "能力",
        description: null,
        rules: [],
        authorNotes: "",
        autoGenerated: true,
        updatedAt: "",
      };
    }
    async save() {}
  },
  createAbilityStore: () => ({
    async loadAll() {
      return { records: [], errors: [] };
    },
    async saveAll(records: unknown[]) {
      state.savedAbilities.push(...records);
    },
  }),
  createLocationStore: () => ({
    async loadAll() {
      return { records: [], errors: [] };
    },
    async saveAll(records: unknown[]) {
      state.savedLocations.push(...records);
    },
  }),
  createOrganizationStore: () => ({
    async loadAll() {
      return { records: [], errors: [] };
    },
    async saveAll(records: unknown[]) {
      state.savedOrganizations.push(...records);
    },
  }),
  createWorldStore: () => ({
    async loadAll() {
      return { records: [], errors: [] };
    },
    async saveAll(records: unknown[]) {
      state.savedWorldItems.push(...records);
    },
  }),
}));

vi.mock("../../src/core/chunkCache", () => ({
  ChunkCache: class {
    async load() {}
    get(hash: string) {
      return state.cachedResults.get(hash);
    }
    async set(hash: string, key: unknown, value: unknown) {
      state.cachedResults.set(hash, value);
      return state.cacheSet(hash, key, value);
    }
    async save() {
      return state.cacheSave();
    }
  },
}));

import {
  extractCharacters,
  saveDirtyDocumentsBeforeExtraction,
} from "../../src/features/extractCharacters";
import { CharacterStoreError } from "../../src/core/characterStore";
import { emptyCharacter } from "../../src/models/character";

const work: WorkEntry = {
  id: "work_test",
  title: "作品",
  folderPath: "C:\\novels\\work",
  registeredAt: "2026-08-06T00:00:00.000Z",
};

function testRegistry(): AIRegistry {
  return {
    resolveModelInfo: vi.fn(async () => ({ contextWindow: 8192 })),
  } as unknown as AIRegistry;
}

function successfulResult(name: string): {
  text: string;
  truncated: false;
  elapsedMs: number;
} {
  return {
    text: JSON.stringify({
      characters: [{ name, evidence: `${name}が歩いた。` }],
    }),
    truncated: false,
    elapsedMs: 1,
  };
}

describe("AI失敗後の復旧案内", () => {
  test.each([
    ["not_running", "AIを起動し、接続先設定を確認してください。"],
    ["model_not_found", "利用可能なモデルを選び直してください。"],
    [
      "timeout",
      "設定でタイムアウトの秒数を延ばすか、チャンクを小さくして、もう一度実行してください。",
    ],
    ["bad_response", "出力上限とモデル設定を確認してください。"],
    // 使っているのがGeminiでも「Claudeの…」と出て混乱させたため、
    // 案内文にサービス名を書かない
    ["authentication_failed", "APIキーを確認して再登録してください。"],
    ["permission_denied", "APIキーの利用権限または請求設定を確認してください。"],
    ["rate_limited", "しばらく待ってから、必要な場合に手動で再実行してください。"],
    ["aborted", "必要なら抽出をもう一度実行してください。"],
    ["unknown", "AI設定と拡張機能のログを確認してください。"],
  ] as const)("%s に具体的な復旧操作を1つ示す", (kind, expected) => {
    const error = new AIError("provider payload", kind, "secret detail");

    expect(recoveryForAIError(error)).toBe(expected);
  });
});

describe("人物抽出フロー", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    state.generate.mockReset();
    state.saveAll.mockReset().mockResolvedValue(undefined);
    state.cacheSet.mockReset();
    state.cacheSave.mockReset();
    state.dirtyDocumentPaths.mockReset().mockResolvedValue([]);
    state.cachedResults.clear();
    state.mergeResult = undefined;
    state.providerId = "ollama";
    state.configured = true;
    state.chunks = undefined;
    state.savedAbilities.length = 0;
    state.savedLocations.length = 0;
    state.savedOrganizations.length = 0;
    state.savedWorldItems.length = 0;
    // 既定では疎通できている状態にする。接続断は個別テストで再現する
    state.testConnection
      .mockReset()
      .mockResolvedValue({ ok: true, message: "接続しました", modelCount: 1 });
    workspace.getConfiguration = () => ({
      get: <T>(_key: string, defaultValue: T): T => defaultValue,
    });
    workspace.textDocuments = [];
  });

  test("保存に失敗した文書がある場合はunsafe continueを提示せず中止する", async () => {
    const save = vi.fn(async () => false);
    workspace.textDocuments = [{
      uri: { fsPath: "c:\\NOVELS\\WORK\\本文\\001.txt" },
      isDirty: true,
      getText: () => "未保存本文",
      save,
    }];
    const showWarningMessage = vi.fn(async () => "保存して実行");
    Object.assign(window, { showWarningMessage });

    await expect(saveDirtyDocumentsBeforeExtraction(work)).resolves.toBe(false);

    expect(save).toHaveBeenCalledOnce();
    expect(showWarningMessage.mock.calls[0]?.slice(1)).toEqual([
      "保存して実行",
      "中止",
    ]);
    expect(showWarningMessage.mock.calls.flat()).not.toContain("そのまま実行");
  });

  test("saveがtrueでもdirtyのままなら再検査で中止する", async () => {
    const document = {
      uri: { fsPath: "C:\\novels\\work\\設定\\characters\\char_001_灯.json" },
      isDirty: true,
      getText: () => "未保存設定",
      save: vi.fn(async () => true),
    };
    workspace.textDocuments = [document];
    Object.assign(window, {
      showWarningMessage: vi.fn(async () => "保存して実行"),
      showErrorMessage: vi.fn(async () => undefined),
    });

    await expect(saveDirtyDocumentsBeforeExtraction(work)).resolves.toBe(false);
  });

  test("モデル情報を取得できないまま既定値で分割せず中止する", async () => {
    const showWarningMessage = vi.fn(async () => "中止");
    Object.assign(window, {
      showInformationMessage: vi.fn(async () => "実行"),
      showWarningMessage,
      showErrorMessage: vi.fn(async () => undefined),
      withProgress: vi.fn(async (_options, task) =>
        task(
          { report: vi.fn() },
          { isCancellationRequested: false, onCancellationRequested: vi.fn() }
        )
      ),
    });
    // 疎通はできるがモデル情報だけ取れない（モデルが削除された等）
    const registry = {
      resolveModelInfo: vi.fn(async () => undefined),
    } as unknown as AIRegistry;

    await extractCharacters(work, registry);

    // 既定の8192で細かく刻んでキャッシュを無効化してしまうより、止める
    expect(state.generate).not.toHaveBeenCalled();
    expect(showWarningMessage.mock.calls.at(-1)?.[0]).toContain(
      "これまでの処理済みキャッシュが使えなくなります"
    );
  });

  test("接続断でモデル情報が取れない場合は疎通回復後に取り直す", async () => {
    Object.assign(window, {
      showInformationMessage: vi.fn(async () => "実行"),
      showWarningMessage: vi.fn(async () => "再試行"),
      showErrorMessage: vi.fn(async () => undefined),
      withProgress: vi.fn(async (_options, task) =>
        task(
          { report: vi.fn() },
          { isCancellationRequested: false, onCancellationRequested: vi.fn() }
        )
      ),
    });
    // 1回目はOllamaが落ちていて取得失敗、疎通回復後は本来の値が返る
    const resolveModelInfo = vi
      .fn()
      .mockResolvedValueOnce(undefined)
      .mockResolvedValue({ contextWindow: 131072 });
    state.testConnection
      .mockResolvedValueOnce({ ok: false, message: "Ollamaに接続できません" })
      .mockResolvedValue({ ok: true, message: "接続しました", modelCount: 1 });
    state.generate.mockResolvedValue(successfulResult("灯"));

    await extractCharacters(work, {
      resolveModelInfo,
    } as unknown as AIRegistry);

    // 取り直した本来のコンテキスト長で処理が進む
    expect(resolveModelInfo).toHaveBeenCalledTimes(2);
    expect(state.generate).toHaveBeenCalled();
  });

  test("AIへ接続できないときはAIを呼ばずに警告して中止する", async () => {
    const showWarningMessage = vi.fn(async () => "中止");
    const showInformationMessage = vi.fn(async () => "実行");
    Object.assign(window, {
      showInformationMessage,
      showWarningMessage,
      showErrorMessage: vi.fn(async () => undefined),
      withProgress: vi.fn(async (_options, task) =>
        task(
          { report: vi.fn() },
          { isCancellationRequested: false, onCancellationRequested: vi.fn() }
        )
      ),
    });
    state.testConnection.mockResolvedValue({
      ok: false,
      message:
        "Ollamaに接続できません（http://localhost:11434）。Ollamaが起動しているか確認してください。",
    });

    await extractCharacters(work, testRegistry());

    // 接続前に止まるので、AI呼び出しも保存も発生しない
    expect(state.generate).not.toHaveBeenCalled();
    expect(state.saveAll).not.toHaveBeenCalled();
    // 処理量の確認ダイアログまで到達しない
    expect(showInformationMessage).not.toHaveBeenCalled();

    const warning = showWarningMessage.mock.calls.at(-1);
    expect(warning?.[0]).toContain("AIに接続できないため");
    expect(warning?.[0]).toContain("Ollamaが起動しているか確認してください");
    // 既定の接続先はローカルなので、起動ボタンも提示される
    expect(warning?.slice(1)).toEqual([
      "Ollamaを起動",
      "再試行",
      "設定を開く",
      "中止",
    ]);
  });

  test("ローカルOllamaが落ちているときは起動ボタンを提示する", async () => {
    const showWarningMessage = vi.fn(async () => "中止");
    Object.assign(window, {
      showInformationMessage: vi.fn(async () => "実行"),
      showWarningMessage,
      showErrorMessage: vi.fn(async () => undefined),
      withProgress: vi.fn(async (_options, task) =>
        task(
          { report: vi.fn() },
          { isCancellationRequested: false, onCancellationRequested: vi.fn() }
        )
      ),
    });
    workspace.getConfiguration = () => ({
      get: <T>(key: string, defaultValue: T): T =>
        key === "ollama.endpoint"
          ? ("http://localhost:11434" as unknown as T)
          : defaultValue,
    });
    state.testConnection.mockResolvedValue({
      ok: false,
      message: "Ollamaに接続できません",
    });

    await extractCharacters(work, testRegistry());

    expect(showWarningMessage.mock.calls.at(-1)?.slice(1)).toEqual([
      "Ollamaを起動",
      "再試行",
      "設定を開く",
      "中止",
    ]);
  });

  test("別マシンのOllamaには起動ボタンを出さない", async () => {
    const showWarningMessage = vi.fn(async () => "中止");
    Object.assign(window, {
      showInformationMessage: vi.fn(async () => "実行"),
      showWarningMessage,
      showErrorMessage: vi.fn(async () => undefined),
      withProgress: vi.fn(async (_options, task) =>
        task(
          { report: vi.fn() },
          { isCancellationRequested: false, onCancellationRequested: vi.fn() }
        )
      ),
    });
    workspace.getConfiguration = () => ({
      get: <T>(key: string, defaultValue: T): T =>
        key === "ollama.endpoint"
          ? ("http://gpu-server:11434" as unknown as T)
          : defaultValue,
    });
    state.testConnection.mockResolvedValue({
      ok: false,
      message: "Ollamaに接続できません",
    });

    await extractCharacters(work, testRegistry());

    // 別マシンのプロセスは起動できないので提案しない
    expect(showWarningMessage.mock.calls.at(-1)?.slice(1)).toEqual([
      "再試行",
      "設定を開く",
      "中止",
    ]);
  });

  test("Claudeには起動ボタンを出さない", async () => {
    const showWarningMessage = vi.fn(async () => "中止");
    Object.assign(window, {
      showInformationMessage: vi.fn(async () => "実行"),
      showWarningMessage,
      showErrorMessage: vi.fn(async () => undefined),
      withProgress: vi.fn(async (_options, task) =>
        task(
          { report: vi.fn() },
          { isCancellationRequested: false, onCancellationRequested: vi.fn() }
        )
      ),
    });
    state.providerId = "claude";
    state.testConnection.mockResolvedValue({
      ok: false,
      message: "Claudeに接続できません。ネットワーク接続を確認してください。",
    });

    await extractCharacters(work, testRegistry());

    expect(showWarningMessage.mock.calls.at(-1)?.slice(1)).toEqual([
      "再試行",
      "設定を開く",
      "中止",
    ]);
  });

  test("接続失敗の警告で設定を開くとプロバイダの設定画面へ誘導する", async () => {
    const executeCommand = vi.fn(async () => undefined);
    Object.assign(commands, { executeCommand });
    Object.assign(window, {
      showInformationMessage: vi.fn(async () => "実行"),
      showWarningMessage: vi.fn(async () => "設定を開く"),
      showErrorMessage: vi.fn(async () => undefined),
      withProgress: vi.fn(async (_options, task) =>
        task(
          { report: vi.fn() },
          { isCancellationRequested: false, onCancellationRequested: vi.fn() }
        )
      ),
    });
    state.providerId = "claude";
    state.testConnection.mockResolvedValue({
      ok: false,
      message: "ClaudeのAPIキーが未設定です。",
    });

    await extractCharacters(work, testRegistry());

    expect(executeCommand).toHaveBeenCalledWith(
      "workbench.action.openSettings",
      "novelai.claude"
    );
    expect(state.generate).not.toHaveBeenCalled();
  });

  test("再試行を選ぶと接続を確認し直し、回復すれば処理を続行する", async () => {
    Object.assign(window, {
      showInformationMessage: vi.fn(async () => "実行"),
      showWarningMessage: vi.fn(async () => "再試行"),
      showErrorMessage: vi.fn(async () => undefined),
      withProgress: vi.fn(async (_options, task) =>
        task(
          { report: vi.fn() },
          { isCancellationRequested: false, onCancellationRequested: vi.fn() }
        )
      ),
    });
    state.testConnection
      .mockResolvedValueOnce({ ok: false, message: "Ollamaに接続できません" })
      .mockResolvedValue({ ok: true, message: "接続しました", modelCount: 1 });
    state.generate.mockResolvedValue(successfulResult("灯"));

    await extractCharacters(work, testRegistry());

    expect(state.testConnection).toHaveBeenCalledTimes(2);
    expect(state.generate).toHaveBeenCalled();
  });

  test("実行中に接続が連続で切れたら残りを試さず中断を伝える", async () => {
    state.chunks = chunkFixture(10);
    const showWarningMessage = vi.fn(async () => undefined);
    Object.assign(window, {
      showInformationMessage: vi.fn(async () => "実行"),
      showWarningMessage,
      showErrorMessage: vi.fn(async () => undefined),
      withProgress: vi.fn(async (_options, task) =>
        task(
          { report: vi.fn() },
          { isCancellationRequested: false, onCancellationRequested: vi.fn() }
        )
      ),
    });
    // 1件成功したあとにOllamaが落ちた状況
    state.generate
      .mockResolvedValueOnce(successfulResult("灯"))
      .mockRejectedValue(
        new AIError("Ollamaに接続できません", "not_running")
      );

    await extractCharacters(work, testRegistry());

    // 成功1回 + 連続失敗3回で打ち切る。10チャンク全部は試さない
    expect(state.generate).toHaveBeenCalledTimes(4);
    expect(showWarningMessage.mock.calls.at(-1)?.[0]).toContain(
      "AIへ接続できなくなったため、残りのチャンクを中断しました"
    );
  });

  test("接続失敗が連続しなければ打ち切らず最後まで処理する", async () => {
    state.chunks = chunkFixture(6);
    Object.assign(window, {
      showInformationMessage: vi.fn(async () => "実行"),
      showWarningMessage: vi.fn(async () => undefined),
      showErrorMessage: vi.fn(async () => undefined),
      withProgress: vi.fn(async (_options, task) =>
        task(
          { report: vi.fn() },
          { isCancellationRequested: false, onCancellationRequested: vi.fn() }
        )
      ),
    });
    // 一時的な揺らぎ（失敗と成功が交互）では中断しない
    state.generate
      .mockRejectedValueOnce(new AIError("timeout", "timeout"))
      .mockResolvedValueOnce(successfulResult("灯"))
      .mockRejectedValueOnce(new AIError("timeout", "timeout"))
      .mockResolvedValueOnce(successfulResult("澪"))
      .mockRejectedValueOnce(new AIError("timeout", "timeout"))
      .mockResolvedValueOnce(successfulResult("灯"));

    await extractCharacters(work, testRegistry());

    expect(state.generate).toHaveBeenCalledTimes(6);
  });

  test("キャッシュだけで完結する場合は接続を確認しない", async () => {
    Object.assign(window, {
      showInformationMessage: vi.fn(async () => undefined),
      showWarningMessage: vi.fn(async () => undefined),
      showErrorMessage: vi.fn(async () => undefined),
      withProgress: vi.fn(async (_options, task) =>
        task(
          { report: vi.fn() },
          { isCancellationRequested: false, onCancellationRequested: vi.fn() }
        )
      ),
    });
    state.cachedResults.set("chunk-1", {
      characters: [{ name: "灯", evidence: "灯が歩いた。" }],
    });
    state.cachedResults.set("chunk-2", {
      characters: [{ name: "澪", evidence: "澪が歩いた。" }],
    });

    await extractCharacters(work, testRegistry());

    // Ollamaが落ちていてもキャッシュからの再反映はできるべき
    expect(state.testConnection).not.toHaveBeenCalled();
    expect(state.generate).not.toHaveBeenCalled();
  });

  // 抽出のあと資料Markdownを作り直してよいかを、呼び出し側がこの戻り値で決める。
  // 中止したのに資料まで作り直すと、作者は何が起きたのか分からなくなる。
  test("保存まで進んだらtrueを返す", async () => {
    Object.assign(window, {
      showInformationMessage: vi.fn(async () => "実行"),
      showWarningMessage: vi.fn(async () => undefined),
      showErrorMessage: vi.fn(async () => undefined),
      withProgress: vi.fn(async (_options, task) =>
        task(
          { report: vi.fn() },
          { isCancellationRequested: false, onCancellationRequested: vi.fn() }
        )
      ),
    });
    state.generate.mockResolvedValue(successfulResult("灯"));

    await expect(extractCharacters(work, testRegistry())).resolves.toBe(true);
  });

  test("確認で中止したらfalseを返す", async () => {
    Object.assign(window, {
      showInformationMessage: vi.fn(async () => "中止"),
      showWarningMessage: vi.fn(async () => undefined),
      showErrorMessage: vi.fn(async () => undefined),
      withProgress: vi.fn(async (_options, task) =>
        task(
          { report: vi.fn() },
          { isCancellationRequested: false, onCancellationRequested: vi.fn() }
        )
      ),
    });

    await expect(extractCharacters(work, testRegistry())).resolves.toBe(false);
    expect(state.generate).not.toHaveBeenCalled();
  });

  test("1回のAI応答から人物・能力・場所をまとめて保存する", async () => {
    // 種別ごとにAIを呼ぶと同じ本文を3回読ませることになるため、
    // 1チャンク1回の応答を3種類に振り分ける。
    const showInformationMessage = vi.fn(async () => "実行");
    Object.assign(window, {
      showInformationMessage,
      showWarningMessage: vi.fn(async () => undefined),
      showErrorMessage: vi.fn(async () => undefined),
      withProgress: vi.fn(async (_options, task) =>
        task(
          { report: vi.fn() },
          { isCancellationRequested: false, onCancellationRequested: vi.fn() }
        )
      ),
    });
    // 能力名・場所名も本文に実在しなければ捏造として弾かれる。
    // 3種類とも根拠を満たす本文を用意する。
    const line = "灯が灯火を唱え、図書塔へ入った。";
    state.chunks = [
      {
        filePath: "001.txt",
        index: 0,
        text: line,
        hash: "chunk-1",
        chapterStart: 1,
        chapterEnd: 1,
      },
    ];
    state.generate.mockResolvedValue({
      text: JSON.stringify({
        characters: [{ name: "灯", evidence: line }],
        abilities: [{ name: "灯火", evidence: line }],
        locations: [{ name: "図書塔", evidence: line }],
        abilitySystem: { abilityTerm: "神術" },
      }),
      truncated: false,
      elapsedMs: 1,
    });

    await extractCharacters(work, testRegistry());

    expect(state.saveAll).toHaveBeenCalled();
    expect(state.savedAbilities).toHaveLength(1);
    expect(state.savedLocations).toHaveLength(1);
    // 総称は作品の呼称を使う（「能力」ではなく「神術」）
    expect(showInformationMessage.mock.calls.at(-1)?.[0]).toContain("神術");
  });

  test("能力・場所が無い作品では該当行を出さない", async () => {
    const showInformationMessage = vi.fn(async () => "実行");
    Object.assign(window, {
      showInformationMessage,
      showWarningMessage: vi.fn(async () => undefined),
      showErrorMessage: vi.fn(async () => undefined),
      withProgress: vi.fn(async (_options, task) =>
        task(
          { report: vi.fn() },
          { isCancellationRequested: false, onCancellationRequested: vi.fn() }
        )
      ),
    });
    state.generate.mockResolvedValue({
      text: JSON.stringify({
        characters: [{ name: "灯", evidence: "灯が歩いた。" }],
        abilities: [],
        locations: [],
        abilitySystem: { abilityTerm: null },
      }),
      truncated: false,
      elapsedMs: 1,
    });

    await extractCharacters(work, testRegistry());

    expect(state.savedAbilities).toHaveLength(0);
    expect(state.savedLocations).toHaveLength(0);
    // 「能力 0件」のような意味のない行を出さない
    const message = String(showInformationMessage.mock.calls.at(-1)?.[0] ?? "");
    expect(message).not.toContain("場所:");
    expect(message).not.toContain("能力:");
  });

  test("切り詰め応答を保存せず出力上限かチャンク縮小を案内する", async () => {
    const showWarningMessage = vi.fn(async () => undefined);
    Object.assign(window, {
      showInformationMessage: vi.fn(async () => "実行"),
      showWarningMessage,
      showErrorMessage: vi.fn(async () => undefined),
      withProgress: vi.fn(async (_options, task) =>
        task(
          { report: vi.fn() },
          { isCancellationRequested: false, onCancellationRequested: vi.fn() }
        )
      ),
    });
    state.generate.mockResolvedValue({
      text: JSON.stringify({ characters: [{ name: "灯" }] }),
      truncated: true,
      elapsedMs: 1,
    });

    await extractCharacters(work, testRegistry());

    expect(state.saveAll).not.toHaveBeenCalled();
    expect(showWarningMessage.mock.calls.at(-1)?.[0]).toContain(
      "出力上限を増やすかチャンクを小さくしてください"
    );
  });

  test("人物JSONに未保存変更がある場合はAI処理を開始しない", async () => {
    const showWarningMessage = vi.fn(async () => undefined);
    Object.assign(window, {
      showWarningMessage,
      showInformationMessage: vi.fn(async () => "実行"),
    });
    state.dirtyDocumentPaths.mockResolvedValue([
      "C:\\NOVELS\\WORK\\設定\\characters\\char_001_灯.json",
    ]);

    await extractCharacters(work, testRegistry());

    expect(state.generate).not.toHaveBeenCalled();
    expect(state.saveAll).not.toHaveBeenCalled();
    expect(showWarningMessage.mock.calls.at(-1)?.[0]).toContain(
      "未保存の人物設定"
    );
  });

  test("AI処理中に人物JSONがdirtyになった場合は保存直前に再検査して拒否する", async () => {
    const showWarningMessage = vi.fn(async () => undefined);
    Object.assign(window, {
      showInformationMessage: vi.fn(async () => "実行"),
      showWarningMessage,
      withProgress: vi.fn(async (_options, task) =>
        task(
          { report: vi.fn() },
          { isCancellationRequested: false, onCancellationRequested: vi.fn() }
        )
      ),
    });
    state.dirtyDocumentPaths
      .mockResolvedValueOnce([])
      .mockResolvedValueOnce(["C:\\novels\\work\\設定\\characters\\char_001_灯.json"]);
    state.generate
      .mockResolvedValueOnce(successfulResult("灯"))
      .mockResolvedValueOnce(successfulResult("澪"));

    await extractCharacters(work, testRegistry());

    expect(state.saveAll).not.toHaveBeenCalled();
    expect(showWarningMessage.mock.calls.at(-1)?.[0]).toContain(
      "保存直前に未保存の人物設定"
    );
  });

  test("キャッシュ保存失敗を警告して有効な人物結果の保存を続ける", async () => {
    const showWarningMessage = vi.fn(async () => undefined);
    Object.assign(window, {
      showInformationMessage: vi.fn(
        async (_message: string, ...actions: string[]) =>
          actions.includes("実行") ? "実行" : undefined
      ),
      showWarningMessage,
      withProgress: vi.fn(async (_options, task) =>
        task(
          { report: vi.fn() },
          { isCancellationRequested: false, onCancellationRequested: vi.fn() }
        )
      ),
    });
    state.generate
      .mockResolvedValueOnce(successfulResult("灯"))
      .mockResolvedValueOnce(successfulResult("澪"));
    state.cacheSave.mockRejectedValueOnce(
      new Error("cache path credential=secret-value")
    );

    await extractCharacters(work, testRegistry());

    expect(state.saveAll).toHaveBeenCalledOnce();
    const summary = showWarningMessage.mock.calls.at(-1)?.[0];
    expect(summary).toContain("キャッシュ保存警告 1件");
    expect(summary).toContain("保存済み 2名");
    expect(summary).not.toContain("secret-value");
  });

  test.each([
    [
      "timeout",
      "設定でタイムアウトの秒数を延ばすか、チャンクを小さくして、もう一度実行してください。",
    ],
    ["aborted", "必要なら抽出をもう一度実行してください。"],
  ] as const)("%s を失敗チャンクとして復旧案内する", async (kind, recovery) => {
    const showWarningMessage = vi.fn(async () => undefined);
    Object.assign(window, {
      showInformationMessage: vi.fn(async () => "実行"),
      showWarningMessage,
      showErrorMessage: vi.fn(async () => undefined),
      withProgress: vi.fn(async (_options, task) =>
        task(
          { report: vi.fn() },
          { isCancellationRequested: false, onCancellationRequested: vi.fn() }
        )
      ),
    });
    state.generate.mockRejectedValue(
      new AIError("provider payload", kind, "secret detail")
    );

    await extractCharacters(work, testRegistry());

    expect(state.saveAll).not.toHaveBeenCalled();
    expect(showWarningMessage.mock.calls.at(-1)?.[0]).toContain(recovery);
  });

  test.each([
    ["空応答", "", "AIの応答が空でした"],
    ["不正JSON", "not-json", "応答をJSONとして解析できませんでした"],
  ])("%s を保存せず安全な復旧案内を表示する", async (_label, text, expected) => {
    const showWarningMessage = vi.fn(async () => undefined);
    Object.assign(window, {
      showInformationMessage: vi.fn(async () => "実行"),
      showWarningMessage,
      showErrorMessage: vi.fn(async () => undefined),
      withProgress: vi.fn(async (_options, task) =>
        task(
          { report: vi.fn() },
          { isCancellationRequested: false, onCancellationRequested: vi.fn() }
        )
      ),
    });
    state.generate.mockResolvedValue({
      text,
      truncated: false,
      elapsedMs: 1,
    });

    await extractCharacters(work, testRegistry());

    expect(state.saveAll).not.toHaveBeenCalled();
    expect(showWarningMessage.mock.calls.at(-1)?.[0]).toContain(expected);
  });

  test("最終サマリーに新規・更新・除外・競合・失敗・保存競合未保存の全件数を示す", async () => {
    const showWarningMessage = vi.fn(async () => undefined);
    Object.assign(window, {
      showInformationMessage: vi.fn(async () => "実行"),
      showWarningMessage,
      showErrorMessage: vi.fn(async () => undefined),
      withProgress: vi.fn(async (_options, task) =>
        task(
          { report: vi.fn() },
          { isCancellationRequested: false, onCancellationRequested: vi.fn() }
        )
      ),
    });
    state.generate
      .mockResolvedValueOnce({
        text: JSON.stringify({
          characters: [
            { name: "灯", evidence: "灯が歩いた。" },
            { name: "先生", evidence: "灯が歩いた" },
          ],
        }),
        truncated: false,
        elapsedMs: 1,
      })
      .mockRejectedValueOnce(
        new AIError("provider payload", "timeout", "secret detail")
      );

    await extractCharacters(work, testRegistry());

    const summary = showWarningMessage.mock.calls.at(-1)?.[0];
    expect(summary).toContain("新規 1名");
    expect(summary).toContain("更新 0名");
    expect(summary).toContain("除外 1件");
    expect(summary).toContain("競合 0件");
    expect(summary).toContain("失敗 1チャンク");
    expect(summary).toContain("保存競合による未保存 0名");
  });

  test.each([
    ["modified_externally", "人物設定が読み込み後に変更されました"],
    ["path_conflict", "人物設定の保存先が競合しました"],
  ] as const)(
    "saveAll の %s では作者変更を保護し抽出結果を全件未保存と報告する",
    async (kind, classification) => {
      const showErrorMessage = vi.fn(async () => undefined);
      Object.assign(window, {
        showInformationMessage: vi.fn(async () => "実行"),
        showWarningMessage: vi.fn(async () => undefined),
        showErrorMessage,
        withProgress: vi.fn(async (_options, task) =>
          task(
            { report: vi.fn() },
            {
              isCancellationRequested: false,
              onCancellationRequested: vi.fn(),
            }
          )
        ),
      });
      state.generate
        .mockResolvedValueOnce(successfulResult("灯"))
        .mockResolvedValueOnce(successfulResult("澪"));
      state.saveAll.mockRejectedValueOnce(
        new CharacterStoreError("changed by author", kind)
      );

      await extractCharacters(work, testRegistry());

      const summary = showErrorMessage.mock.calls.at(-1)?.[0];
      expect(summary).toContain(
        "作者の変更を保護するため保存しませんでした"
      );
      expect(summary).toContain(classification);
      expect(summary).toContain("保存済み 0名");
      expect(summary).toContain("手動確認が必要 0名");
      expect(summary).toContain("新規 2名");
      expect(summary).toContain("更新 0名");
      expect(summary).toContain("除外 0件");
      expect(summary).toContain("競合 0件");
      expect(summary).toContain("失敗 0チャンク");
      expect(summary).toContain("保存競合による未保存 2名");
    }
  );

  test("後続保存競合では先に完了した件数だけを保存済みと報告する", async () => {
    const showErrorMessage = vi.fn(async () => undefined);
    Object.assign(window, {
      showInformationMessage: vi.fn(async () => "実行"),
      showWarningMessage: vi.fn(async () => undefined),
      showErrorMessage,
      withProgress: vi.fn(async (_options, task) =>
        task(
          { report: vi.fn() },
          { isCancellationRequested: false, onCancellationRequested: vi.fn() }
        )
      ),
    });
    state.generate
      .mockResolvedValueOnce(successfulResult("灯"))
      .mockResolvedValueOnce(successfulResult("澪"));
    state.saveAll.mockRejectedValueOnce(
      new CharacterStoreError("changed by author", "modified_externally", {
        batchProgress: {
          completedIds: ["char_001"],
          ambiguousIds: [],
          remainingIds: ["char_002"],
        },
      })
    );

    await extractCharacters(work, testRegistry());

    const summary = showErrorMessage.mock.calls.at(-1)?.[0];
    expect(summary).toContain("保存済み 1名");
    expect(summary).toContain("手動確認が必要 0名");
    expect(summary).toContain("保存競合による未保存 1名");
    expect(summary).not.toContain("保存済み 0名");
    expect(summary).not.toContain("保存競合による未保存 2名");
  });

  test("重複IDが含まれても未分類の未保存人数を水増ししない", async () => {
    const showErrorMessage = vi.fn(async () => undefined);
    Object.assign(window, {
      showInformationMessage: vi.fn(async () => "実行"),
      showWarningMessage: vi.fn(async () => undefined),
      showErrorMessage,
      withProgress: vi.fn(async (_options, task) =>
        task(
          { report: vi.fn() },
          { isCancellationRequested: false, onCancellationRequested: vi.fn() }
        )
      ),
    });
    const duplicate = emptyCharacter("char_001", "灯");
    state.mergeResult = {
      characters: [duplicate, structuredClone(duplicate)],
      added: ["灯"],
      updated: [],
      changedIds: ["char_001"],
      conflicts: [],
    };
    state.generate
      .mockResolvedValueOnce(successfulResult("灯"))
      .mockResolvedValueOnce(successfulResult("澪"));
    state.saveAll.mockRejectedValueOnce(
      new CharacterStoreError("legacy progress", "path_conflict", {
        batchProgress: {
          completedIds: [],
          ambiguousIds: [],
          remainingIds: [],
        },
      })
    );

    await extractCharacters(work, testRegistry());

    const summary = showErrorMessage.mock.calls.at(-1)?.[0];
    expect(summary).toContain("保存競合による未保存 1名");
    expect(summary).not.toContain("保存競合による未保存 2名");
  });

  test("配置後の退避失敗は保存済みとも未保存とも数えず手動照合を促す", async () => {
    const showErrorMessage = vi.fn(async () => undefined);
    Object.assign(window, {
      showInformationMessage: vi.fn(async () => "実行"),
      showWarningMessage: vi.fn(async () => undefined),
      showErrorMessage,
      withProgress: vi.fn(async (_options, task) =>
        task(
          { report: vi.fn() },
          { isCancellationRequested: false, onCancellationRequested: vi.fn() }
        )
      ),
    });
    state.generate
      .mockResolvedValueOnce(successfulResult("灯"))
      .mockResolvedValueOnce({
        text: JSON.stringify({ characters: [] }),
        truncated: false,
        elapsedMs: 1,
      });
    state.saveAll.mockRejectedValueOnce(
      new CharacterStoreError("manual recovery", "path_conflict", {
        batchProgress: {
          completedIds: [],
          ambiguousIds: ["char_001"],
          remainingIds: [],
        },
      })
    );

    await extractCharacters(work, testRegistry());

    const summary = showErrorMessage.mock.calls.at(-1)?.[0];
    expect(summary).toContain("保存済み 0名");
    expect(summary).toContain("手動確認が必要 1名");
    expect(summary).toContain("保存競合による未保存 0名");
    expect(summary).toContain("保存先と回復ファイルを手動で照合してください");
    expect(summary).not.toContain("保存済み 1名");
    expect(summary).not.toContain("保存競合による未保存 1名");
  });

  test("曖昧な保存失敗は型付きの保存先と回復パスだけを詳細表示する", async () => {
    const destination = "C:\\novels\\work\\設定\\characters\\char_001_灯.json";
    const recovery = "C:\\novels\\work\\設定\\characters\\.novelai-recovery\\safe.bak";
    let detailContent = "";
    Object.assign(workspace, {
      openTextDocument: vi.fn(async (options: { content: string }) => {
        detailContent = options.content;
        return { uri: { fsPath: "recovery-details" } };
      }),
    });
    Object.assign(window, {
      showInformationMessage: vi.fn(async () => "実行"),
      showWarningMessage: vi.fn(async () => undefined),
      showErrorMessage: vi.fn(
        async (_message: string, ...actions: string[]) =>
          actions.includes("回復パスを表示") ? "回復パスを表示" : undefined
      ),
      showTextDocument: vi.fn(async () => undefined),
      withProgress: vi.fn(async (_options, task) =>
        task(
          { report: vi.fn() },
          { isCancellationRequested: false, onCancellationRequested: vi.fn() }
        )
      ),
    });
    state.generate
      .mockResolvedValueOnce(successfulResult("灯"))
      .mockResolvedValueOnce(successfulResult("澪"));
    state.saveAll.mockRejectedValueOnce(
      new CharacterStoreError("raw prompt credential=secret-value", "path_conflict", {
        persistenceState: "ambiguous",
        recoveryPaths: [destination, recovery],
        batchProgress: {
          completedIds: [],
          ambiguousIds: ["char_001"],
          remainingIds: ["char_002"],
        },
      })
    );

    await extractCharacters(work, testRegistry());

    expect(detailContent).toContain(destination);
    expect(detailContent).toContain(recovery);
    expect(detailContent).not.toContain("secret-value");
    expect(detailContent).not.toContain("灯が歩いた");
  });

  test.each([
    [
      "permission_denied",
      "APIキーの利用権限または請求設定を確認してください。",
      "設定を開く",
    ],
    [
      "rate_limited",
      "しばらく待ってから、必要な場合に手動で再実行してください。",
      undefined,
    ],
  ] as const)("Claudeの%sを一般応答エラーへ潰さず即停止する", async (
    kind,
    recovery,
    expectedAction
  ) => {
    state.providerId = "claude";
    const showWarningMessage = vi.fn(async () => undefined);
    Object.assign(window, {
      showInformationMessage: vi.fn(async () => "実行"),
      showWarningMessage,
      withProgress: vi.fn(async (_options, task) =>
        task(
          { report: vi.fn() },
          { isCancellationRequested: false, onCancellationRequested: vi.fn() }
        )
      ),
    });
    state.generate.mockRejectedValue(
      new AIError("provider payload", kind, "credential=secret-value")
    );

    await extractCharacters(work, testRegistry());

    expect(state.generate).toHaveBeenCalledOnce();
    const call = showWarningMessage.mock.calls.at(-1);
    expect(call?.[0]).toContain(recovery);
    if (expectedAction) expect(call?.slice(1)).toContain(expectedAction);
    expect(call?.[0]).not.toContain("secret-value");
  });

  test("AI失敗後に保存競合しても無害化した失敗詳細を表示できる", async () => {
    let detailContent = "";
    const showErrorMessage = vi.fn(
      async (_message: string, ...actions: string[]) =>
        actions.includes("詳細を表示") ? "詳細を表示" : undefined
    );
    Object.assign(workspace, {
      openTextDocument: vi.fn(async (options: { content: string }) => {
        detailContent = options.content;
        return { uri: { fsPath: "failure-details" } };
      }),
    });
    Object.assign(window, {
      showInformationMessage: vi.fn(async () => "実行"),
      showWarningMessage: vi.fn(async () => undefined),
      showErrorMessage,
      showTextDocument: vi.fn(async () => undefined),
      withProgress: vi.fn(async (_options, task) =>
        task(
          { report: vi.fn() },
          { isCancellationRequested: false, onCancellationRequested: vi.fn() }
        )
      ),
    });
    state.generate
      .mockResolvedValueOnce(successfulResult("灯"))
      .mockRejectedValueOnce(
        new AIError("secret provider payload", "timeout", "raw prompt")
      );
    state.saveAll.mockRejectedValueOnce(
      new CharacterStoreError("changed by author", "modified_externally")
    );

    await extractCharacters(work, testRegistry());

    expect(showErrorMessage.mock.calls.at(-1)?.slice(1)).toContain(
      "詳細を表示"
    );
    expect(detailContent).toContain("第1話(2)");
    expect(detailContent).toContain(
      "チャンクを小さくして、もう一度実行してください。"
    );
    expect(detailContent).not.toContain("secret provider payload");
    expect(detailContent).not.toContain("raw prompt");
  });

  test("失敗詳細は章ラベルと無害化した案内だけを表示する", async () => {
    let detailContent = "";
    const showWarningMessage = vi.fn(
      async (_message: string, ...actions: string[]) =>
        actions.includes("詳細を表示") ? "詳細を表示" : undefined
    );
    Object.assign(workspace, {
      openTextDocument: vi.fn(async (options: { content: string }) => {
        detailContent = options.content;
        return { uri: { fsPath: "failure-details" } };
      }),
    });
    Object.assign(window, {
      showInformationMessage: vi.fn(
        async (_message: string, ...actions: string[]) =>
          actions.includes("実行") ? "実行" : undefined
      ),
      showWarningMessage,
      showErrorMessage: vi.fn(async () => undefined),
      showTextDocument: vi.fn(async () => undefined),
      withProgress: vi.fn(async (_options, task) =>
        task(
          { report: vi.fn() },
          { isCancellationRequested: false, onCancellationRequested: vi.fn() }
        )
      ),
    });
    state.generate
      .mockResolvedValueOnce(successfulResult("灯"))
      .mockRejectedValueOnce(
        new AIError(
          "sk-ant-secret provider payload 澪が歩いた。",
          "bad_response",
          "raw prompt"
        )
      );

    await extractCharacters(work, testRegistry());

    expect(showWarningMessage.mock.calls.at(-1)?.slice(1)).toContain(
      "詳細を表示"
    );
    expect(detailContent).toContain("第1話(2)");
    expect(detailContent).toContain(
      "出力上限とモデル設定を確認してください。"
    );
    expect(detailContent).not.toContain("sk-ant-secret");
    expect(detailContent).not.toContain("provider payload");
    expect(detailContent).not.toContain("澪が歩いた");
    expect(detailContent).not.toContain("raw prompt");
  });

  test.each(["ollama", "claude"] as const)(
    "AI接続失敗から選択中の %s 設定を開ける",
    async (providerId) => {
      state.providerId = providerId;
      const executeCommand = vi.fn(async () => undefined);
      const showWarningMessage = vi.fn(
        async (_message: string, ...actions: string[]) =>
          actions.includes("設定を開く") ? "設定を開く" : undefined
      );
      Object.assign(commands, { executeCommand });
      Object.assign(window, {
        showInformationMessage: vi.fn(async () => "実行"),
        showWarningMessage,
        showErrorMessage: vi.fn(async () => undefined),
        withProgress: vi.fn(async (_options, task) =>
          task(
            { report: vi.fn() },
            {
              isCancellationRequested: false,
              onCancellationRequested: vi.fn(),
            }
          )
        ),
      });
      state.generate.mockRejectedValue(
        new AIError("connection payload", "not_running")
      );

      await extractCharacters(work, testRegistry());

      expect(executeCommand).toHaveBeenCalledWith(
        "workbench.action.openSettings",
        `novelai.${providerId}`
      );
    }
  );

  test("セットアップのキャンセルは通知を増やさず何も保存しない", async () => {
    state.configured = false;
    const showInformationMessage = vi.fn(async () => undefined);
    const showWarningMessage = vi.fn(async () => undefined);
    const showErrorMessage = vi.fn(async () => undefined);
    Object.assign(window, {
      showInformationMessage,
      showWarningMessage,
      showErrorMessage,
    });

    await extractCharacters(work, testRegistry());

    expect(state.generate).not.toHaveBeenCalled();
    expect(state.saveAll).not.toHaveBeenCalled();
    expect(showInformationMessage).not.toHaveBeenCalled();
    expect(showWarningMessage).not.toHaveBeenCalled();
    expect(showErrorMessage).not.toHaveBeenCalled();
  });

  test("失敗チャンクを自動再試行せず別プロバイダへフォールバックしない", async () => {
    const showWarningMessage = vi.fn(async () => undefined);
    Object.assign(window, {
      showInformationMessage: vi.fn(async () => "実行"),
      showWarningMessage,
      showErrorMessage: vi.fn(async () => undefined),
      withProgress: vi.fn(async (_options, task) =>
        task(
          { report: vi.fn() },
          { isCancellationRequested: false, onCancellationRequested: vi.fn() }
        )
      ),
    });
    state.generate
      .mockRejectedValueOnce(new AIError("timed out", "timeout"))
      .mockResolvedValueOnce(successfulResult("澪"));

    await extractCharacters(work, testRegistry());

    expect(state.generate).toHaveBeenCalledTimes(2);
    expect(
      state.generate.mock.calls.filter(([params]) =>
        (params as { userPrompt: string }).userPrompt.includes("灯が歩いた。")
      )
    ).toHaveLength(1);
    expect(
      state.generate.mock.calls.filter(([params]) =>
        (params as { userPrompt: string }).userPrompt.includes("澪が歩いた。")
      )
    ).toHaveLength(1);
    expect(showWarningMessage.mock.calls.at(-1)?.[0]).toContain(
      "失敗 1チャンク"
    );
  });

  test("chunkChars が正なら自動計算より優先して分割へ渡す", async () => {
    workspace.getConfiguration = () => ({
      get: <T>(key: string, defaultValue: T): T =>
        (key === "chunkChars" ? 321 : defaultValue) as T,
    });
    Object.assign(window, {
      showInformationMessage: vi.fn(async () => "実行"),
      showWarningMessage: vi.fn(async () => undefined),
      showErrorMessage: vi.fn(async () => undefined),
      withProgress: vi.fn(async (_options, task) =>
        task(
          { report: vi.fn() },
          {
            isCancellationRequested: false,
            onCancellationRequested: vi.fn(),
          }
        )
      ),
    });
    state.generate.mockResolvedValue({
      text: JSON.stringify({ characters: [] }),
      truncated: false,
      elapsedMs: 1,
    });
    const registry = {
      resolveModelInfo: vi.fn(async () => ({ contextWindow: 8192 })),
    } as unknown as AIRegistry;

    await extractCharacters(work, registry);

    expect(splitIntoChunks).toHaveBeenCalledWith(
      "001.txt",
      "灯が歩いた。",
      1,
      1,
      { maxChars: 321 }
    );
  });

  test("1未満の chunkChars は自動計算へ戻す", async () => {
    workspace.getConfiguration = () => ({
      get: <T>(key: string, defaultValue: T): T =>
        (key === "chunkChars" ? 0.5 : defaultValue) as T,
    });
    Object.assign(window, {
      showInformationMessage: vi.fn(async () => "実行"),
      showWarningMessage: vi.fn(async () => undefined),
      showErrorMessage: vi.fn(async () => undefined),
      withProgress: vi.fn(async (_options, task) =>
        task(
          { report: vi.fn() },
          { isCancellationRequested: false, onCancellationRequested: vi.fn() }
        )
      ),
    });
    state.generate.mockResolvedValue({
      text: JSON.stringify({ characters: [] }),
      truncated: false,
      elapsedMs: 1,
    });
    const registry = {
      resolveModelInfo: vi.fn(async () => ({ contextWindow: 8192 })),
    } as unknown as AIRegistry;

    await extractCharacters(work, registry);

    expect(splitIntoChunks).toHaveBeenCalledWith(
      "001.txt",
      "灯が歩いた。",
      1,
      1,
      { maxChars: 1000 }
    );
  });

  test("途中でキャンセルした場合はキャッシュだけを保存し人物JSONを変更しない", async () => {
    let cancel: (() => void) | undefined;
    let cancelled = false;
    Object.assign(window, {
      showInformationMessage: vi.fn(async () => "実行"),
      showWarningMessage: vi.fn(async () => undefined),
      withProgress: vi.fn(async (_options, task) =>
        task(
          { report: vi.fn() },
          {
            get isCancellationRequested() {
              return cancelled;
            },
            onCancellationRequested(callback: () => void) {
              cancel = () => {
                cancelled = true;
                callback();
              };
            },
          }
        )
      ),
    });
    state.generate.mockImplementationOnce(async () => {
      cancel?.();
      return {
        text: JSON.stringify({ characters: [{ name: "灯" }] }),
        truncated: false,
        elapsedMs: 1,
      };
    });
    const registry = {
      resolveModelInfo: vi.fn(async () => ({ contextWindow: 8192 })),
    } as unknown as AIRegistry;

    await extractCharacters(work, registry);

    expect(state.cacheSave).toHaveBeenCalledOnce();
    expect(state.saveAll).not.toHaveBeenCalled();
  });

  test("全チャンクがキャッシュ済みでもAPIを呼ばず人物JSONへ再反映する", async () => {
    state.cachedResults.set("chunk-1", {
      characters: [{ name: "灯", evidence: "灯が歩いた。" }],
    });
    state.cachedResults.set("chunk-2", {
      characters: [{ name: "澪", evidence: "澪が歩いた。" }],
    });
    Object.assign(window, {
      showInformationMessage: vi.fn(async () => undefined),
      showWarningMessage: vi.fn(async () => undefined),
      withProgress: vi.fn(async (_options, task) =>
        task(
          { report: vi.fn() },
          { isCancellationRequested: false, onCancellationRequested: vi.fn() }
        )
      ),
    });
    const registry = {
      resolveModelInfo: vi.fn(async () => ({ contextWindow: 8192 })),
    } as unknown as AIRegistry;

    await extractCharacters(work, registry);

    expect(state.generate).not.toHaveBeenCalled();
    expect(state.saveAll).toHaveBeenCalledOnce();
    expect(
      state.saveAll.mock.calls[0][0].map((character: { name: string }) =>
        character.name
      )
    ).toEqual(["灯", "澪"]);
  });

  test("キャッシュの生出力も再検証して人物でない候補を除外する", async () => {
    state.cachedResults.set("chunk-1", {
      characters: [
        { name: "灯", evidence: "灯が歩いた。" },
        { name: "先生", evidence: "灯が歩いた" },
      ],
    });
    state.cachedResults.set("chunk-2", { characters: [] });
    const showInformationMessage = vi.fn(async () => undefined);
    Object.assign(window, {
      showInformationMessage,
      showWarningMessage: vi.fn(async () => undefined),
      withProgress: vi.fn(async (_options, task) =>
        task(
          { report: vi.fn() },
          { isCancellationRequested: false, onCancellationRequested: vi.fn() }
        )
      ),
    });
    const registry = {
      resolveModelInfo: vi.fn(async () => ({ contextWindow: 8192 })),
    } as unknown as AIRegistry;

    await extractCharacters(work, registry);

    expect(
      state.saveAll.mock.calls[0][0].map((character: { name: string }) =>
        character.name
      )
    ).toEqual(["灯"]);
    expect(showInformationMessage.mock.calls.at(-1)?.[0]).toContain(
      "AI出力から除外 1 件"
    );
  });

  test("検証前の解析結果をキャッシュして後の規則変更で再評価できるようにする", async () => {
    const rawResult = {
      characters: [
        { name: "灯", evidence: "灯が歩いた。" },
        { name: "先生", evidence: "灯が歩いた" },
      ],
    };
    state.generate
      .mockResolvedValueOnce({
        text: JSON.stringify(rawResult),
        truncated: false,
        elapsedMs: 1,
      })
      .mockResolvedValueOnce({
        text: JSON.stringify({ characters: [] }),
        truncated: false,
        elapsedMs: 1,
      });
    Object.assign(window, {
      showInformationMessage: vi.fn(
        async (_message: string, ...actions: string[]) =>
          actions.includes("実行") ? "実行" : undefined
      ),
      showWarningMessage: vi.fn(async () => undefined),
      withProgress: vi.fn(async (_options, task) =>
        task(
          { report: vi.fn() },
          { isCancellationRequested: false, onCancellationRequested: vi.fn() }
        )
      ),
    });
    const registry = {
      resolveModelInfo: vi.fn(async () => ({ contextWindow: 8192 })),
    } as unknown as AIRegistry;

    await extractCharacters(work, registry);

    expect(state.cachedResults.get("chunk-1")).toEqual(rawResult);
    expect(
      state.saveAll.mock.calls[0][0].map((character: { name: string }) =>
        character.name
      )
    ).toEqual(["灯"]);
  });

  test("Claudeの実行確認に保守的な入出力トークン量と課金注意を表示する", async () => {
    state.providerId = "claude";
    workspace.getConfiguration = () => ({
      get: <T>(key: string, defaultValue: T): T =>
        (key === "claude.maxOutputTokens" ? 4096 : defaultValue) as T,
    });
    const showInformationMessage = vi.fn(
      async (_message: string, ...actions: string[]) =>
        actions.includes("実行") ? "実行" : undefined
    );
    Object.assign(window, {
      showInformationMessage,
      showWarningMessage: vi.fn(async () => undefined),
      withProgress: vi.fn(async (_options, task) =>
        task(
          { report: vi.fn() },
          { isCancellationRequested: false, onCancellationRequested: vi.fn() }
        )
      ),
    });
    state.generate.mockResolvedValue({
      text: JSON.stringify({ characters: [] }),
      truncated: false,
      elapsedMs: 1,
    });
    const registry = {
      resolveModelInfo: vi.fn(async () => ({ contextWindow: 8192 })),
    } as unknown as AIRegistry;

    await extractCharacters(work, registry);

    const confirmation = showInformationMessage.mock.calls.find((call) =>
      call.slice(1).includes("実行")
    )?.[0];
    expect(confirmation).toMatch(/入力: 約 [\d,]+ トークン/);
    expect(confirmation).toContain(
      "出力: 最大 8,192 トークン（設定上限 4,096 × 2 回）"
    );
    expect(confirmation).toContain("Claude APIは実行すると利用量が加算されます");
    expect(confirmation).toContain("各社の現行料金");
  });

  test("Ollamaの実行確認は無料のローカル実行と示し課金を予告しない", async () => {
    const showInformationMessage = vi.fn(
      async (_message: string, ...actions: string[]) =>
        actions.includes("実行") ? "実行" : undefined
    );
    Object.assign(window, {
      showInformationMessage,
      showWarningMessage: vi.fn(async () => undefined),
      withProgress: vi.fn(async (_options, task) =>
        task(
          { report: vi.fn() },
          { isCancellationRequested: false, onCancellationRequested: vi.fn() }
        )
      ),
    });
    state.generate.mockResolvedValue({
      text: JSON.stringify({ characters: [] }),
      truncated: false,
      elapsedMs: 1,
    });
    const registry = {
      resolveModelInfo: vi.fn(async () => ({ contextWindow: 8192 })),
    } as unknown as AIRegistry;

    await extractCharacters(work, registry);

    const confirmation = showInformationMessage.mock.calls.find((call) =>
      call.slice(1).includes("実行")
    )?.[0];
    expect(confirmation).toContain("無料・ローカル実行（API課金なし）");
    expect(confirmation).not.toContain("課金が発生します");
    expect(confirmation).not.toContain("Anthropic");
  });
});
