import { describe, expect, test } from "vitest";
import {
  emptyOrganization,
  membersOf,
  nextOrganizationId,
  parseOrganization,
  type Organization,
} from "../../src/models/organization";
import {
  mergeExtractedOrganizations,
  organizationsFromAffiliations,
} from "../../src/core/settingsMerge";
import { validateExtractedOrganizations } from "../../src/core/settingsExtractionValidation";
import { buildOrganizationMarkdown } from "../../src/core/settingsMarkdown";
import { describeOrganization } from "../../src/core/settingsSummary";
import { buildOrganizationListItems } from "../../src/core/settingsList";
import { applyOrganizationEdits } from "../../src/core/settingsEdit";
import { emptyCharacter } from "../../src/models/character";
import { CHARACTER_EXTRACT_SCHEMA } from "../../src/prompts/characterExtract";
import type { Chunk } from "../../src/core/chunker";

/**
 * 組織は人物の `affiliation`（所属）に対応する設定。
 * 所属で人物をまとめているのに、組織そのものを書く場所が無かった。
 */

function chunk(text: string): Chunk {
  return {
    text,
    hash: "h",
    files: [{ filePath: "第1話.txt", episode: { numbers: [1] } }],
  } as unknown as Chunk;
}

function organization(
  name: string,
  extra: Partial<Organization> = {}
): Organization {
  return { ...emptyOrganization(`org_${name}`, name), ...extra };
}

describe("組織のID採番", () => {
  test("連番で振り、既存とぶつけない", () => {
    expect(nextOrganizationId([])).toBe("org_001");
    expect(nextOrganizationId([emptyOrganization("org_003", "ギルド")])).toBe(
      "org_004"
    );
  });
});

describe("組織のJSON検証", () => {
  test("欠けた項目は既定値で補う", () => {
    const parsed = parseOrganization({ id: "org_001", name: "冒険者ギルド" });
    expect(parsed.parent).toBeNull();
    expect(parsed.aliases).toEqual([]);
    expect(parsed.autoGenerated).toBe(true);
  });

  test("壊れていたら勝手に直さず止める", () => {
    // 作者が手で編集した可能性がある。黙って捨てると編集が消える
    expect(() => parseOrganization({ id: "loc_001", name: "ギルド" })).toThrow();
    expect(() => parseOrganization({ id: "org_001" })).toThrow();
    expect(() =>
      parseOrganization({ id: "org_001", name: "ギルド", parent: 3 })
    ).toThrow();
  });
});

describe("所属する人物を引く", () => {
  test("人物側の所属から集める。組織側には持たない", () => {
    // 両方に持つと、片方だけ直したときに食い違う
    const characters = [
      { ...emptyCharacter("char_001", "灯"), affiliation: "生活保護課" },
      { ...emptyCharacter("char_002", "澪"), affiliation: "窓口課" },
      { ...emptyCharacter("char_003", "エバン"), affiliation: null },
    ];

    expect(membersOf(organization("生活保護課"), characters)).toEqual(["灯"]);
  });

  test("別名で書かれた所属も同じ組織とみなす", () => {
    const characters = [
      { ...emptyCharacter("char_001", "灯"), affiliation: "ギルド" },
    ];
    const org = organization("冒険者ギルド", { aliases: ["ギルド"] });

    expect(membersOf(org, characters)).toEqual(["灯"]);
  });
});

describe("組織の抽出と検証", () => {
  test("本文に根拠のある組織だけを採る", () => {
    const result = validateExtractedOrganizations(
      [
        { name: "冒険者ギルド", evidence: "冒険者ギルドの扉" },
        { name: "闇の教団", evidence: "闇の教団が動いた" },
      ],
      chunk("冒険者ギルドの扉を開けた。")
    );

    expect(result.accepted.map((item) => item.data.name)).toEqual([
      "冒険者ギルド",
    ]);
    expect(result.rejected[0]).toEqual({
      name: "闇の教団",
      reason: "ungrounded",
    });
  });

  test("指示語だけの名前は採らない", () => {
    const result = validateExtractedOrganizations(
      [{ name: "その組織", evidence: "その組織は" }],
      chunk("その組織は動いた。")
    );

    expect(result.accepted).toHaveLength(0);
  });

  test("普通名詞の組織名は弾かない", () => {
    // 場所の「情景描写」判定を当てると、正しい組織まで落ちる
    const result = validateExtractedOrganizations(
      [{ name: "生活保護課", evidence: "生活保護課の窓口" }],
      chunk("生活保護課の窓口へ向かった。")
    );

    expect(result.accepted).toHaveLength(1);
  });

  test("スキーマで必須にして、モデルが黙って落とすのを防ぐ", () => {
    expect(CHARACTER_EXTRACT_SCHEMA.required).toEqual(
      expect.arrayContaining(["organizations"])
    );
    expect(
      CHARACTER_EXTRACT_SCHEMA.properties.organizations.items.required
    ).toEqual(expect.arrayContaining(["name", "summary", "evidence"]));
  });
});

describe("組織のマージ", () => {
  test("空欄は埋め、既にある値は上書きしない", () => {
    const merged = mergeExtractedOrganizations(
      [organization("冒険者ギルド", { description: "作者が書いた説明" })],
      [
        {
          data: {
            name: "冒険者ギルド",
            category: "ギルド",
            description: "AIが読み取った別の説明",
            evidence: "冒険者ギルド",
          },
          chapters: [1],
        },
      ]
    );

    const target = merged.organizations[0];
    expect(target.category).toBe("ギルド");
    expect(target.description).toBe("作者が書いた説明");
    expect(
      target.conflicts.some((conflict) => conflict.field === "description")
    ).toBe(true);
  });

  test("作者が確定させた組織は話数の追記だけにする", () => {
    const merged = mergeExtractedOrganizations(
      [organization("冒険者ギルド", { autoGenerated: false })],
      [
        {
          data: {
            name: "冒険者ギルド",
            category: "ギルド",
            evidence: "冒険者ギルド",
          },
          chapters: [3],
        },
      ]
    );

    expect(merged.organizations[0].category).toBeNull();
    expect(merged.organizations[0].appearedChapters).toEqual([3]);
  });
});

describe("人物の所属から組織を作る", () => {
  test("組織として抽出されなかった所属も登録する", () => {
    // AIは affiliation に所属名を入れておきながら、
    // organizations には出さないことがある
    const result = organizationsFromAffiliations([], ["生活保護課", "窓口課"]);

    expect(result.organizations.map((item) => item.name)).toEqual([
      "生活保護課",
      "窓口課",
    ]);
    // 本文に根拠のない説明は足さない
    expect(result.organizations[0].description).toBeNull();
  });

  test("すでにある組織は作り直さない", () => {
    const result = organizationsFromAffiliations(
      [organization("冒険者ギルド", { aliases: ["ギルド"] })],
      ["ギルド"]
    );

    expect(result.organizations).toHaveLength(1);
    expect(result.added).toEqual([]);
  });
});

describe("組織の表示", () => {
  const characters = [
    { ...emptyCharacter("char_001", "灯"), affiliation: "生活保護課" },
  ];

  test("設定資料集に所属する人物を出す", () => {
    const markdown = buildOrganizationMarkdown(
      [
        organization("生活保護課", {
          parent: "冒険者ギルド",
          category: "部署",
          description: "困窮した冒険者を支える。",
        }),
      ],
      characters,
      { workTitle: "作品" }
    );

    expect(markdown).toContain("## 冒険者ギルド");
    expect(markdown).toContain("### 生活保護課");
    expect(markdown).toContain("- **種別**: 部署");
    expect(markdown).toContain("- **所属する人物**: 灯");
  });

  test("上位組織が読み取れないものは末尾へまとめる", () => {
    const markdown = buildOrganizationMarkdown(
      [organization("冒険者ギルド")],
      [],
      { workTitle: "作品" }
    );

    expect(markdown).toContain("## 上位組織の記載なし");
  });

  test("1件も無ければその旨を書く", () => {
    expect(buildOrganizationMarkdown([], [], { workTitle: "作品" })).toContain(
      "まだ組織が登録されていません"
    );
  });

  test("AIへ渡す現在の設定にも所属する人物を含める", () => {
    const text = describeOrganization(organization("生活保護課"), ["灯"]);
    expect(text).toContain("所属する人物: 灯");
  });

  test("一覧に所属人数を出す", () => {
    // 名前だけの組織でも「誰がいるか」で見当が付く
    const items = buildOrganizationListItems(
      [organization("生活保護課")],
      characters
    );
    expect(items[0].sub).toContain("1人");
  });
});

describe("組織の書き換え", () => {
  test("作者が書き換えたら以後の抽出で上書きされないようにする", () => {
    const edited = applyOrganizationEdits(organization("ギルド"), {
      parent: "王国",
      category: "組合",
    });

    expect(edited.parent).toBe("王国");
    expect(edited.category).toBe("組合");
    expect(edited.autoGenerated).toBe(false);
  });

  test("AIの提案を反映しただけなら作者確定にしない", () => {
    const edited = applyOrganizationEdits(
      organization("ギルド"),
      { description: "冒険者を束ねる。" },
      { authorConfirmed: false }
    );

    expect(edited.autoGenerated).toBe(true);
  });
});
