import { beforeEach, describe, expect, test, vi } from "vitest";
import { readFileSync } from "node:fs";

/**
 * 伏線の検知の結果を、提案パネルへ出す道（設計書6.35.2・6.35.3）。
 *
 * **台帳へは何も自動で入らない。** 検知は候補を並べるだけで、作者が
 * 「登録」「回収済みにする」を押したものだけが保存される。
 *
 * ここで押さえるのは3つ。
 *   (a) 候補が「伏線の候補」「伏線の回収」として、押せる形で並ぶこと
 *   (b) 押すと**台帳の口**（`addForeshadow` / `saveOrUpdateForeshadow`）を通ること
 *   (c) 見送っても台帳を触らないこと
 * 保存そのもの（ファイルの書き方）は `foreshadowStore` の側の話である。
 */

const posted: Array<{ category: string; items: unknown[] }> = [];

vi.mock("vscode", () => {
  const noop = () => undefined;
  return {
    commands: { executeCommand: vi.fn() },
    window: {
      showWarningMessage: vi.fn(() => Promise.resolve(undefined)),
      showInformationMessage: vi.fn(() => Promise.resolve(undefined)),
      showErrorMessage: vi.fn(),
      createOutputChannel: () => ({
        appendLine: noop,
        show: noop,
        dispose: noop,
      }),
      createStatusBarItem: () => ({ show: noop, hide: noop, dispose: noop }),
      withProgress: vi.fn(),
    },
    workspace: {
      getConfiguration: () => ({ get: (_k: string, d?: unknown) => d }),
      fs: {
        readFile: vi.fn(() => Promise.resolve(new Uint8Array())),
        writeFile: vi.fn(() => Promise.resolve()),
        createDirectory: vi.fn(() => Promise.resolve()),
      },
      textDocuments: [],
    },
    Uri: { file: (p: string) => ({ fsPath: p }) },
    EventEmitter: class {
      event = () => ({ dispose: noop });
      fire = noop;
    },
    ProgressLocation: { Window: 10, Notification: 15 },
    StatusBarAlignment: { Left: 1, Right: 2 },
    ThemeIcon: class {},
    ThemeColor: class {},
    MarkdownString: class {},
    Range: class {},
    Position: class {},
    ViewColumn: { One: 1 },
  };
});

const addForeshadow = vi.fn(async () => ({}));
const saveOrUpdateForeshadow = vi.fn(async () => ({}));

// **台帳の口が呼ばれたかを見る。** ここを写して自前で書き込む実装にすると、
// IDの採番とハッシュ照合（既存ファイルを壊さない仕掛け）を落とす
vi.mock("../../src/core/foreshadowStore", () => ({
  addForeshadow: (...args: unknown[]) => addForeshadow(...(args as [])),
  saveOrUpdateForeshadow: (...args: unknown[]) =>
    saveOrUpdateForeshadow(...(args as [])),
  createForeshadowStore: vi.fn(),
}));

import {
  showForeshadowCandidates,
  showForeshadowResolutions,
  type ForeshadowResolutionProposal,
} from "../../src/features/checkForeshadows";
import { ProposalPanel } from "../../src/features/proposalPanel";
import type { WorkEntry } from "../../src/models/types";
import type { AcceptedForeshadowCandidate } from "../../src/core/foreshadowValidation";
import type { Foreshadow } from "../../src/models/foreshadow";

const work: WorkEntry = {
  id: "w1",
  title: "いじめられっ子",
  folderPath: "C:/小説/いじめられっ子",
  registeredAt: "2026-08-28T00:00:00.000Z",
};

const candidate: AcceptedForeshadowCandidate = {
  label: "銀の懐中時計",
  note: "まだ話せない事情があることを示している",
  quote: "銀の懐中時計を、彼はしまい込んだ",
  filePath: "C:/小説/いじめられっ子/本文/003_約束.txt",
  chapter: 3,
  chunkHash: "hash-003",
};

const foreshadow: Foreshadow = {
  schemaVersion: "0.1",
  id: "foreshadow_001",
  label: "銀の懐中時計",
  note: "まだ話せない事情がある",
  plantedChapter: 3,
  plantedQuote: "銀の懐中時計を、彼はしまい込んだ",
  status: "open",
  resolvedChapter: null,
  resolvedQuote: "",
  source: "ai",
  autoGenerated: true,
  authorNotes: "",
  createdAt: "2026-08-28T00:00:00.000Z",
  updatedAt: "2026-08-28T00:00:00.000Z",
};

const proposal: ForeshadowResolutionProposal = {
  foreshadow,
  resolution: {
    id: "foreshadow_001",
    quote: "彼は時計の蓋を開け、母の名を口にした",
    note: "時計が母の形見だと明かされた",
    filePath: "C:/小説/いじめられっ子/本文/007_湖畔の誓い.txt",
    chapter: 7,
    chunkHash: "hash-007",
  },
};

function fakeView() {
  return {
    webview: {
      options: {},
      html: "",
      cspSource: "vscode-webview:",
      onDidReceiveMessage: () => ({ dispose: () => undefined }),
      postMessage: (message: { category: string; items: unknown[] }) => {
        posted.push(message);
        return Promise.resolve(true);
      },
    },
    onDidDispose: () => ({ dispose: () => undefined }),
  };
}

function panelWithView(): ProposalPanel {
  const panel = new ProposalPanel();
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  panel.resolveWebviewView(fakeView() as any);
  return panel;
}

function latest() {
  return posted[posted.length - 1];
}

function shownItem(): {
  id: string;
  name: string;
  changes: string[];
  source: string;
  status: string;
  statusDetail?: string;
  applyLabel?: string;
} {
  return latest().items[0] as {
    id: string;
    name: string;
    changes: string[];
    source: string;
    status: string;
    statusDetail?: string;
    applyLabel?: string;
  };
}

/** 画面のボタンを押したのと同じ（webviewからのメッセージ） */
async function press(
  panel: ProposalPanel,
  type: "apply" | "dismiss",
  id: string
): Promise<void> {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  await (panel as any).handleMessage({ type, id });
}

beforeEach(() => {
  posted.length = 0;
  addForeshadow.mockClear();
  addForeshadow.mockImplementation(async () => ({}));
  saveOrUpdateForeshadow.mockClear();
  saveOrUpdateForeshadow.mockImplementation(async () => ({}));
});

describe("配置の候補（伏線の候補）", () => {
  test("押せる形で並ぶ", () => {
    const panel = panelWithView();

    showForeshadowCandidates(panel, work, [candidate]);

    expect(latest().category).toBe("伏線の候補");
    const item = shownItem();
    expect(item.name).toBe("銀の懐中時計");
    // 何を根拠にした候補かは、引用が示す。話数と示唆も並べる
    expect(item.changes.join("\n")).toContain("第3話で張られています");
    expect(item.changes.join("\n")).toContain(
      "引用：「銀の懐中時計を、彼はしまい込んだ」"
    );
    expect(item.changes.join("\n")).toContain("まだ話せない事情");
    expect(item.source).toBe("003_約束.txt");
    // 押した結果が何になるかで呼び名が変わる（「反映する」ではない）
    expect(item.applyLabel).toBe("登録");
    expect(item.status).toBe("pending");
  });

  test("話数が読めなければ、推測で埋めない", () => {
    const panel = panelWithView();

    showForeshadowCandidates(panel, work, [{ ...candidate, chapter: null }]);

    expect(shownItem().changes.join("\n")).toContain("話数不明で張られています");
  });

  test("「登録」を押すと、台帳の口へ渡る", () => {
    const panel = panelWithView();
    showForeshadowCandidates(panel, work, [candidate]);

    return press(panel, "apply", shownItem().id).then(() => {
      expect(addForeshadow).toHaveBeenCalledTimes(1);
      expect(addForeshadow.mock.calls[0][1]).toEqual({
        label: "銀の懐中時計",
        note: "まだ話せない事情があることを示している",
        plantedChapter: 3,
        plantedQuote: "銀の懐中時計を、彼はしまい込んだ",
        // 元はAIの読みなので、作者が確定させた記述とは区別する
        source: "ai",
        autoGenerated: true,
      });
      expect(shownItem().status).toBe("applied");
    });
  });

  test("保存に失敗したら、候補は残って理由が出る", async () => {
    addForeshadow.mockImplementation(async () => {
      throw new Error("書き込めませんでした。");
    });
    const panel = panelWithView();
    showForeshadowCandidates(panel, work, [candidate]);

    await press(panel, "apply", shownItem().id);

    const item = shownItem();
    expect(item.status).toBe("failed");
    expect(item.statusDetail).toContain("書き込めませんでした。");
  });

  test("見送っても、台帳は触らない", async () => {
    const panel = panelWithView();
    showForeshadowCandidates(panel, work, [candidate]);

    await press(panel, "dismiss", shownItem().id);

    expect(addForeshadow).not.toHaveBeenCalled();
    expect(shownItem().status).toBe("dismissed");
  });
});

describe("回収の候補（伏線の回収）", () => {
  test("張った箇所と回収の箇所を、並べて出す", () => {
    const panel = panelWithView();

    showForeshadowResolutions(panel, work, [proposal]);

    expect(latest().category).toBe("伏線の回収");
    const item = shownItem();
    expect(item.name).toBe("銀の懐中時計");
    expect(item.changes.join("\n")).toContain(
      "第3話で張った：「銀の懐中時計を、彼はしまい込んだ」"
    );
    expect(item.changes.join("\n")).toContain(
      "第7話で回収：「彼は時計の蓋を開け、母の名を口にした」"
    );
    expect(item.applyLabel).toBe("回収済みにする");
  });

  test("「回収済みにする」を押すと、台帳の口へ渡る", async () => {
    const panel = panelWithView();
    showForeshadowResolutions(panel, work, [proposal]);

    await press(panel, "apply", shownItem().id);

    expect(saveOrUpdateForeshadow).toHaveBeenCalledTimes(1);
    expect(saveOrUpdateForeshadow.mock.calls[0][1]).toBe("foreshadow_001");
    expect(saveOrUpdateForeshadow.mock.calls[0][2]).toEqual({
      status: "resolved",
      resolvedChapter: 7,
      resolvedQuote: "彼は時計の蓋を開け、母の名を口にした",
    });
    expect(shownItem().status).toBe("applied");
  });

  test("見送れば、未回収のまま残る", async () => {
    // **誤って回収済みの印が付くと、作者は安心して回収を忘れる**
    const panel = panelWithView();
    showForeshadowResolutions(panel, work, [proposal]);

    await press(panel, "dismiss", shownItem().id);

    expect(saveOrUpdateForeshadow).not.toHaveBeenCalled();
    expect(shownItem().status).toBe("dismissed");
  });
});

/** 画面側の道（WebViewを要するので、口が残っているかだけを見る） */
describe("画面のボタンの言葉", () => {
  const html = () => readFileSync("src/views/proposalPanelHtml.ts", "utf-8");

  test("押した結果に合わせた言葉を出す", () => {
    expect(html()).toContain("item.applyLabel");
  });

  test("渡されていなければ、これまでどおり「反映する」", () => {
    expect(html()).toContain("item.applyLabel || '反映する'");
  });
});
