import { describe, expect, test } from "vitest";
import { readdirSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

/**
 * **設定と台帳を書く経路の棚卸し**（CLAUDE.md「2. 作者が書いたデータを上書きしない」）。
 *
 * 本文の側は `manuscriptWriteAudit.test.ts` が見ている。こちらは**設定資料と
 * 各種台帳**——作者が手で直すことがあり、GitHub で持ち歩かれるものである。
 *
 * ## `atomicWriteFile` の書き方は2つある
 *
 * | 書き方 | 何が起きるか | 守り |
 * |---|---|---|
 * | `mode: "create"` | 既にあれば**失敗する** | 呼ぶ側が「退避 → 削除 → 作り直し」をする |
 * | 指定なし | **上書きする**（退避は無い） | 呼ぶ側のハッシュ照合、または作り直せること |
 *
 * **どちらも正しい。** 危ないのは、**指定なしを、守りの無いまま新しく足す**
 * ことである。そうすると、作者が外で直した設定が黙って消える——これは
 * 実機で実際に起きた壊れ方（A-18「設定資料の人物が分裂している」）の隣にある。
 *
 * そこで**指定なしで書く部品を名指しで並べ、理由を書く**。増えたらここが落ちる。
 * 落ちたときにすることは「一覧へ足す」ではなく、**まず守りがあるかを確かめる**
 * ことである。
 */

const CORE = resolve(__dirname, "../../src/core");

/**
 * 上書き（指定なし）で書いてよい部品と、その理由。
 *
 * **「作り直せる」か「呼ぶ側が照合する」のどちらかでなければ、ここへ足さない。**
 */
const OVERWRITE_ALLOWED: Record<string, string> = {
  // 呼ぶ側がハッシュ照合をする（読み込み時と同じ中身でなければ止める）
  "settingsStore.ts": "SettingsStore 自身が assertSaveAllowed を持つ",
  "bookStore.ts": "assertSaveAllowed を持つ（未保存の下書きだけ別に控える）",
  "chapterStore.ts": "assertSaveAllowed を持つ（未保存の編集も断る）",
  "postingStore.ts": "読み込み時の控えと突き合わせる",

  // 作り直せる（消えても作者の書いたものは失われない）
  "chunkCache.ts": "処理済みチャンクの控え。再実行で作り直せる",
  "vectorIndex.ts": "意味検索の索引。作り直せる",
  "extractedIndexStore.ts": "抽出済みの話の記録。再抽出で作り直せる",
  "writingStatsStore.ts": "端末ごとの執筆量。読むときに合算する（5.5.6）",
  "sessionStore.ts":
    "最終編集環境の記録（5.5.2）。端末ごとに分けてあり、次に開いたときに書き直される",
  "coverBake.ts": "焼いた表紙。素材から作り直せる",
  "pendingUpdates.ts": "承認待ち。まだ資料になっていない（5.5.18）",

  // 追記型の記録（1行1件。畳まない）
  "announcementHistory.ts":
    "告知文の履歴。作った文の控えで、作者が手で直す先ではない",
  "catchphraseHistory.ts":
    "キャッチコピーの履歴。同上（作り直しても失うものが無い）",
  "typoIssueHistory.ts":
    "誤字脱字の指摘の履歴。同じ指摘を二度出さないための控え",

  // 読み込み→併合→保存で、作者の書いたものを守る
  "abilityStore.ts":
    "能力体系だけは SettingsStore を通らない。" +
    "呼ぶのは抽出だけで、load → 併合 → save の間に AI を待たない。" +
    "併合は autoGenerated を見て総称を上書きせず、規則は和集合にする",
};

/** `atomicWriteFile` を使う `core` の部品を並べる */
function writersInCore(): string[] {
  return readdirSync(CORE)
    .filter((name) => name.endsWith(".ts") && name !== "atomicWrite.ts")
    .filter((name) =>
      readFileSync(resolve(CORE, name), "utf8").includes("atomicWriteFile(")
    );
}

/** 上書き（指定なし）で書いているか＝`mode: "create"` が1つも無いか */
function overwrites(name: string): boolean {
  return !readFileSync(resolve(CORE, name), "utf8").includes('mode: "create"');
}

describe("設定と台帳を書く経路", () => {
  test("**上書きで書く部品は、名指しの一覧どおり**", () => {
    const found = writersInCore().filter(overwrites).sort();
    expect(found).toEqual(Object.keys(OVERWRITE_ALLOWED).sort());
  });

  test("一覧に、もう使われていない名前が残っていない", () => {
    const writers = new Set(writersInCore());
    for (const name of Object.keys(OVERWRITE_ALLOWED)) {
      expect(writers.has(name), name).toBe(true);
    }
  });

  test("**理由を空にしない**（なぜ上書きしてよいのかが読めること）", () => {
    for (const [name, reason] of Object.entries(OVERWRITE_ALLOWED)) {
      expect(reason.length, name).toBeGreaterThan(10);
    }
  });

  test("ハッシュ照合を持つと書いた4つは、本当に持っている", () => {
    for (const name of [
      "settingsStore.ts",
      "bookStore.ts",
      "chapterStore.ts",
      "postingStore.ts",
    ]) {
      const source = readFileSync(resolve(CORE, name), "utf8");
      expect(source, name).toContain("hashBytes");
    }
  });

  test("**退避してから作り直す型は、退避を取ってから消している**", () => {
    // `mode: "create"` は既にあれば失敗する。だから呼ぶ側は
    // 「控えを取る → 消す → 作り直す」の順で通す。順を違えると、
    // 消したあとに書けなくて原稿も控えも無い状態になる
    const source = readFileSync(resolve(CORE, "plotFile.ts"), "utf8");
    const backup = source.indexOf("createManagedRecoveryPath(target)");
    const remove = source.indexOf("workspace.fs.delete(path.toUri(target)");
    expect(backup).toBeGreaterThan(0);
    expect(remove).toBeGreaterThan(backup);
  });
});
