import { describe, expect, test } from "vitest";
import {
  AUDIENCE_PROFILES,
  EXPORT_AUDIENCES,
  buildExportMarkdown,
  type ExportAudience,
  type SettingsExportData,
} from "../../src/core/settingsExportProfiles";
import { buildCharacterMarkdown } from "../../src/core/settingsMarkdown";
import { emptyCharacter, type Character } from "../../src/models/character";
import { emptyLocation, type Location } from "../../src/models/location";
import { emptyAbility, emptyAbilitySystem } from "../../src/models/ability";
import { emptyOrganization } from "../../src/models/organization";
import { emptyWorldItem } from "../../src/models/world";
import type { RecordChange } from "../../src/models/jsonValidation";

/**
 * 設定資料の提供先別エクスポート（設計書6.75）。
 *
 * **渡す相手によって、出してよい情報が違う。** イラストの発注書に
 * 結末の伏線や内面の掘り下げが混ざっていては困るし、レビュー依頼に
 * 経歴を全部付ける必要もない。
 *
 * ここで確かめるのは3つ。
 *
 * 1. **型ごとに、出る項目と出ない項目**——判断は項目の種類だけで行う
 *    （値の中身を見て決めない）ので、表のとおりに出ることが全てである
 * 2. **冒頭の明記**——渡された側が「これで全部」と誤解しないこと
 * 3. **第N話まで**——先の話で分かった値・後から出てくる人物が混ざらないこと
 */

const AT = new Date(2026, 8, 5, 14, 30, 0);

function change(field: string, value: string, chapters: number[]): RecordChange {
  return {
    field,
    value,
    chapters,
    timepointId: null,
    note: null,
    evidence: null,
    source: "extracted",
  };
}

/** 全項目を埋めた人物。**どの項目が落ちるか**を見るための材料 */
function fullCharacter(): Character {
  return {
    ...emptyCharacter("char_001", "月島灯"),
    reading: "つきしまあかり",
    aliases: ["灯ちゃん"],
    summary: "主人公。転生した女子高生。",
    gender: "女性",
    affiliation: "窓口課",
    role: "案内係",
    personality: "人見知りだが芯は強い",
    appearance: "小柄で猫っ毛",
    physical: {
      age: "17歳",
      height: "152cm",
      build: "細身",
      hair: "黒のショート",
      eyes: "琥珀色",
      skin: "色白",
      distinctive: "左目の下にほくろ",
      clothing: "紺のブレザーに赤いマフラー",
    },
    firstPerson: {
      default: "わたし",
      variants: [
        { form: "あたし", context: "親しい相手", chapters: [3], evidence: null },
      ],
    },
    defaultSecondPerson: "あなた",
    addressTerms: [
      {
        targetName: "白鳥",
        targetId: null,
        forms: [
          {
            term: "白鳥さん",
            category: null,
            context: null,
            firstChapter: 1,
            lastChapter: null,
            status: "current",
            evidence: null,
          },
        ],
        authorLocked: false,
      },
    ],
    relations: [{ name: "白鳥", relation: "同僚" }],
    abilities: [
      {
        abilityId: "abil_001",
        name: "霊視",
        mastery: "習得済み",
        note: null,
        firstChapter: 2,
        appearedChapters: [2],
        evidence: null,
        autoGenerated: true,
      },
    ],
    appearedChapters: [1, 2, 3],
    exportNote: "資料向けの補足",
    customFields: { theme: "再生" },
    conflicts: [
      {
        field: "appearance",
        values: ["黒髪", "銀髪"],
        chapters: [1, 7],
        note: null,
        observations: [
          { value: "黒髪", chapters: [1] },
          { value: "銀髪", chapters: [7] },
        ],
      },
    ],
    changes: [change("role", "案内係", [1])],
    aiNotes: [
      {
        id: "note_001",
        createdAt: "",
        topic: "内面",
        text: "母への負い目が行動の軸になっている。",
        model: "gemma",
        source: "deep_dive",
      },
    ],
  };
}

function fullLocation(): Location {
  return {
    ...emptyLocation("loc_001", "図書塔"),
    reading: "としょとう",
    aliases: ["塔"],
    summary: "物語の起点になる建物。",
    region: "王都",
    description: "石造りの八角形。屋根に銅の風見鶏。",
    appearedChapters: [1, 2],
    exportNote: "外観の資料あり",
  };
}

function baseData(): SettingsExportData {
  return {
    characters: [fullCharacter()],
    locations: [fullLocation()],
    abilities: [
      {
        ...emptyAbility("abil_001", "霊視"),
        summary: "死者の残滓が見える。",
        description: "触れた物の記憶を読む。",
        cost: "頭痛",
        userNames: ["月島灯"],
        appearedChapters: [2],
      },
    ],
    abilitySystem: emptyAbilitySystem(),
    organizations: [
      {
        ...emptyOrganization("org_001", "窓口課"),
        summary: "主人公の職場。",
        description: "市役所の一部署。",
        appearedChapters: [1],
      },
    ],
    world: [
      {
        ...emptyWorldItem("wld_001", "残滓"),
        description: "死者が遺す想いの断片。",
        appearedChapters: [1],
      },
    ],
    customFields: [
      { key: "theme", label: "主題", hint: "", multiline: false },
    ],
  };
}

const OPTIONS = { workTitle: "灯の塔", authorName: "野中ひさ", at: AT };

function build(
  audience: ExportAudience,
  chapter: number | null = null,
  data: SettingsExportData = baseData()
): string {
  return buildExportMarkdown(audience, data, { ...OPTIONS, chapter });
}

describe("提供先の型は3つ", () => {
  test("表は1か所にあり、3つの型が並ぶ", () => {
    expect(EXPORT_AUDIENCES).toEqual([
      "editorial",
      "illustration",
      "introduction",
    ]);
    for (const audience of EXPORT_AUDIENCES) {
      expect(AUDIENCE_PROFILES[audience].id).toBe(audience);
      // 選択画面に出す説明が空だと、どれを選べばよいか分からない
      expect(AUDIENCE_PROFILES[audience].description.length).toBeGreaterThan(0);
    }
  });
});

describe("編集部向け", () => {
  const markdown = build("editorial");

  test("既存の全部入りに出る項目は、すべて出る", () => {
    /*
      **「編集部向け＝いまの全部入りと同じ中身」**（設計書6.75）。
      別の組み立てで書いているので、項目が抜けても気づけない。
      既存の書き出しが作る「- **項目名**:」を全部拾って突き合わせる。
    */
    const data = baseData();
    const existing = buildCharacterMarkdown(data.characters as Character[], {
      workTitle: "灯の塔",
      customFields: data.customFields,
    });
    const labels = [...existing.matchAll(/- \*\*(.+?)\*\*:/g)].map((m) => m[1]);

    expect(labels.length).toBeGreaterThan(5);
    for (const label of labels) {
      expect(markdown, `編集部向けに「${label}」が無い`).toContain(
        `**${label}**`
      );
    }
  });

  test("紹介文・AIの掘り下げ・判断待ちの食い違いも出す", () => {
    expect(markdown).toContain("主人公。転生した女子高生。");
    expect(markdown).toContain("母への負い目");
    expect(markdown).toContain("変化かもしれない");
  });

  test("人物・場所・能力・組織・世界観の全部が入る", () => {
    for (const heading of ["## 登場人物", "## 場所", "## 組織", "## 世界観"]) {
      expect(markdown, heading).toContain(heading);
    }
    expect(markdown).toContain("死者の残滓が見える。");
  });
});

describe("イラスト・デザイン発注向け", () => {
  const markdown = build("illustration");

  test("外見に関わる項目は出る", () => {
    for (const value of [
      "つきしまあかり",
      "女性",
      "17歳",
      "小柄で猫っ毛",
      "紺のブレザーに赤いマフラー",
      "左目の下にほくろ",
      "白鳥（同僚）",
    ]) {
      expect(markdown, value).toContain(value);
    }
  });

  test("内面・経歴・AIメモ・判断待ちは出ない", () => {
    for (const value of [
      "人見知りだが芯は強い", // 性格
      "主人公。転生した女子高生。", // 紹介文
      "母への負い目", // AIの掘り下げ
      "資料向けの補足", // 自由記述の補足
      "再生", // 作者が足した項目
      "変化かもしれない",
      "**役割**",
    ]) {
      expect(markdown, value).not.toContain(value);
    }
  });

  test("場所は名前と外観の描写だけ", () => {
    expect(markdown).toContain("図書塔");
    expect(markdown).toContain("石造りの八角形");
    // 紹介文は物語の役割を書くところなので、発注書には要らない
    expect(markdown).not.toContain("物語の起点になる建物。");
  });

  test("能力・組織・世界観は種別ごと出さない", () => {
    expect(markdown).not.toContain("## 組織");
    expect(markdown).not.toContain("## 世界観");
    expect(markdown).not.toContain("死者の残滓が見える。");
  });
});

describe("あらすじ・設定の紹介向け", () => {
  const markdown = build("introduction");

  test("人物は名前・読み・紹介文だけ", () => {
    expect(markdown).toContain("月島灯");
    expect(markdown).toContain("つきしまあかり");
    expect(markdown).toContain("主人公。転生した女子高生。");
    for (const value of [
      "**役割**",
      "**性格**",
      "**外見**",
      "人見知りだが芯は強い",
      "小柄で猫っ毛",
    ]) {
      expect(markdown, value).not.toContain(value);
    }
  });

  test("世界観は出すが、場所・能力・組織は出さない", () => {
    expect(markdown).toContain("## 世界観");
    expect(markdown).toContain("死者が遺す想いの断片。");
    expect(markdown).not.toContain("## 場所");
    expect(markdown).not.toContain("## 組織");
  });

  test("公開範囲が public のものだけを出す", () => {
    const data = baseData();
    data.world = [
      { ...data.world[0], spoilerLevel: "staff_only", name: "終幕の鍵" },
    ];

    expect(
      buildExportMarkdown("introduction", data, { ...OPTIONS, chapter: null })
    ).not.toContain("終幕の鍵");
  });
});

describe("冒頭の明記", () => {
  const markdown = build("illustration", 12);

  test("作品名・作者名・作成日・提供先の型を書く", () => {
    expect(markdown).toContain("灯の塔");
    expect(markdown).toContain("野中ひさ");
    expect(markdown).toContain("2026-09-05");
    expect(markdown).toContain(AUDIENCE_PROFILES.illustration.label);
  });

  test("含めた項目と、含めなかった項目の両方を書く", () => {
    // 「これで全部」と誤解されると、足りない情報を訊いてもらえない
    expect(markdown).toContain("この資料に含めた項目");
    expect(markdown).toContain("この資料に含めなかった項目");
    expect(markdown).toContain("服装");
    expect(markdown).toContain("性格");
  });

  test("第N話までであることを書く", () => {
    expect(markdown).toContain("第12話まで");
  });

  test("全話ぶんのときは、絞っていないことを書く", () => {
    const all = build("illustration", null);

    expect(all).toContain("全話");
    expect(all).not.toContain("第12話まで");
  });

  test("作者名が分からなければ、その行を出さない", () => {
    const built = buildExportMarkdown("editorial", baseData(), {
      workTitle: "灯の塔",
      authorName: null,
      chapter: null,
      at: AT,
    });

    expect(built).not.toContain("**作者**");
  });
});

describe("第N話までに絞る", () => {
  test("あとの話で分かった値は出さない", () => {
    const data = baseData();
    data.characters = [
      {
        ...fullCharacter(),
        role: "課長",
        changes: [change("role", "新人", [1]), change("role", "課長", [7])],
      },
    ];

    const built = buildExportMarkdown("editorial", data, {
      ...OPTIONS,
      chapter: 3,
    });

    expect(built).toContain("新人");
    expect(built).not.toContain("課長");
  });

  test("あとから登場する人物は出さない", () => {
    const data = baseData();
    data.characters = [
      fullCharacter(),
      {
        ...emptyCharacter("char_002", "白鳥"),
        summary: "第9話で現れる協力者。",
        appearedChapters: [9, 10],
      },
    ];

    const built = buildExportMarkdown("editorial", data, {
      ...OPTIONS,
      chapter: 3,
    });

    expect(built).toContain("月島灯");
    expect(built).not.toContain("第9話で現れる協力者。");
  });

  test("登場話の一覧にも、先の話は出さない", () => {
    const data = baseData();
    data.characters = [{ ...fullCharacter(), appearedChapters: [1, 2, 3, 9] }];

    const built = buildExportMarkdown("editorial", data, {
      ...OPTIONS,
      chapter: 3,
    });

    expect(built).toContain("第1〜3話");
    expect(built).not.toContain("第1〜3、9話");
  });

  test("話数の分からない自由記述は、時点を絞ったときは出さない", () => {
    // 補足・AIの掘り下げ・判断待ちの食い違いは、いつ書かれたか分からない。
    // **先の話の情報が混ざっていないことを言えない**ので、出さない側へ倒す
    const built = build("editorial", 3);

    expect(built).not.toContain("資料向けの補足");
    expect(built).not.toContain("母への負い目");
    expect(built).not.toContain("変化かもしれない");
    // 落としたことは冒頭に書く（黙って減らさない）
    expect(built).toContain("補足");
  });

  test("全話ぶんなら、自由記述はそのまま出す", () => {
    const built = build("editorial", null);

    expect(built).toContain("資料向けの補足");
    expect(built).toContain("母への負い目");
  });
});

/**
 * ネタバレの漏れ（0.32.6のレビュー）。
 *
 * 提供先別の書き出しは「渡す相手によって出してよい情報が違う」ための機能
 * なので、**漏れは機能そのものの否定になる。** 見つかったのは6か所。
 *
 * 1. 未登場のレコードが「第N話まで」を素通りする
 * 2. 関係（相手の名前）が話数でも公開範囲でも絞られない
 * 3. 組織の「所属する人物」に、作者だけの印を付けた人物が出る
 * 4. 人物欄の能力名と、能力の「使い手」が絞られない
 * 5. 呼称の相手が絞られない
 * 6. 時点の記録を持たない項目が、断りなく最新の値で載る
 */
describe("未登場のレコードは、時点を絞ったら出さない", () => {
  /**
   * `hasAppearedBy` は登場話が空だと通す。**矛盾検知ではそれが正しい**
   * （記録が無いだけで設定を捨てると、突き合わせる材料が消える）が、
   * 書き出しでは逆に効く——第1話までの資料に、まだ書いていない人物の
   * 設定がそのまま載る。
   */
  test("登場話の記録が無い人物は、第N話までの資料に出ない", () => {
    const data = baseData();
    data.characters = [
      fullCharacter(),
      {
        ...emptyCharacter("char_009", "終幕の男"),
        summary: "最終話で正体が明かされる。",
        appearedChapters: [],
      },
    ];

    const built = buildExportMarkdown("editorial", data, {
      ...OPTIONS,
      chapter: 1,
    });

    expect(built).toContain("月島灯");
    expect(built).not.toContain("最終話で正体が明かされる。");
  });

  test("全話ぶんなら、これまでどおり出す", () => {
    const data = baseData();
    data.characters = [
      {
        ...emptyCharacter("char_009", "終幕の男"),
        summary: "最終話で正体が明かされる。",
        appearedChapters: [],
      },
    ];

    expect(
      buildExportMarkdown("editorial", data, { ...OPTIONS, chapter: null })
    ).toContain("最終話で正体が明かされる。");
  });

  test("「未登場（設定のみ）」の印が付いたものも出さない", () => {
    const data = baseData();
    data.characters = [
      {
        ...emptyCharacter("char_009", "終幕の男"),
        summary: "設定だけ作ってある。",
        status: "未登場",
        // 登場話に数字が入っていても、未登場の印が勝つ
        appearedChapters: [1],
      },
    ];

    expect(
      buildExportMarkdown("editorial", data, { ...OPTIONS, chapter: 5 })
    ).not.toContain("設定だけ作ってある。");
  });

  test("場所・能力・組織・世界観にも同じ守りが要る", () => {
    const data = baseData();
    data.locations = [
      { ...emptyLocation("loc_009", "封印の間"), description: "地下の広間。" },
    ];
    data.abilities = [
      { ...emptyAbility("abil_009", "終焉"), description: "世界を閉じる。" },
    ];
    data.organizations = [
      {
        ...emptyOrganization("org_009", "影の議会"),
        description: "黒幕の集まり。",
      },
    ];
    data.world = [
      { ...emptyWorldItem("wld_009", "門"), description: "最後に開く門。" },
    ];

    const built = buildExportMarkdown("editorial", data, {
      ...OPTIONS,
      chapter: 1,
    });

    for (const leaked of [
      "地下の広間。",
      "世界を閉じる。",
      "黒幕の集まり。",
      "最後に開く門。",
    ]) {
      expect(built, leaked).not.toContain(leaked);
    }
  });
});

describe("関係（相手の名前）を絞る", () => {
  /** 相手（白鳥）を資料に置いた状態を作る */
  function withPartner(overrides: Partial<Character> = {}): SettingsExportData {
    const data = baseData();
    data.characters = [
      { ...fullCharacter(), relations: [{ name: "白鳥", relation: "同僚" }] },
      {
        ...emptyCharacter("char_002", "白鳥"),
        summary: "本当は敵側の人物。",
        appearedChapters: [1],
        ...overrides,
      },
    ];
    return data;
  }

  test("作者だけの印が付いた相手との関係は、行ごと出さない", () => {
    const data = withPartner({ spoilerLevel: "author_only" });

    const built = buildExportMarkdown("editorial", data, {
      ...OPTIONS,
      chapter: null,
    });

    // 人物そのものが出ないだけでは足りない。**関係の行に名前が残る**
    expect(built).not.toContain("本当は敵側の人物。");
    expect(built).not.toContain("白鳥（同僚）");
  });

  test("あとから登場する相手との関係も出さない", () => {
    const data = withPartner({ appearedChapters: [9] });

    const built = buildExportMarkdown("editorial", data, {
      ...OPTIONS,
      chapter: 3,
    });

    expect(built).not.toContain("白鳥（同僚）");
  });

  test("その時点で出ている相手との関係は、これまでどおり出す", () => {
    const built = buildExportMarkdown("editorial", withPartner(), {
      ...OPTIONS,
      chapter: 3,
    });

    expect(built).toContain("白鳥（同僚）");
  });

  test("資料に居ない名前は、時点を絞ったときだけ落とす", () => {
    // 引き当てられない以上、その相手がいつ出るのかを言えない。
    // **確実に判定できないものは、出さない側へ倒す**（設計書6.75）
    const data = baseData();

    expect(
      buildExportMarkdown("editorial", data, { ...OPTIONS, chapter: 3 })
    ).not.toContain("白鳥（同僚）");
    // 全話ぶんなら、絞る理由が無いので従来どおり
    expect(
      buildExportMarkdown("editorial", data, { ...OPTIONS, chapter: null })
    ).toContain("白鳥（同僚）");
  });
});

describe("組織の「所属する人物」を絞る", () => {
  test("作者だけの印が付いた人物は並べない", () => {
    const data = baseData();
    data.characters = [
      { ...fullCharacter(), affiliation: "窓口課" },
      {
        ...emptyCharacter("char_002", "潜入者"),
        affiliation: "窓口課",
        appearedChapters: [1],
        spoilerLevel: "author_only",
      },
    ];

    const built = buildExportMarkdown("editorial", data, {
      ...OPTIONS,
      chapter: null,
    });

    expect(built).toContain("**所属する人物**");
    expect(built).not.toContain("潜入者");
  });

  test("その時点でまだ出ていない人物も並べない", () => {
    const data = baseData();
    data.characters = [
      { ...fullCharacter(), affiliation: "窓口課" },
      {
        ...emptyCharacter("char_002", "後任"),
        affiliation: "窓口課",
        appearedChapters: [],
      },
    ];

    const built = buildExportMarkdown("editorial", data, {
      ...OPTIONS,
      chapter: 3,
    });

    expect(built).not.toContain("後任");
  });
});

describe("能力を絞る", () => {
  test("人物欄の能力名も、公開範囲で絞る", () => {
    const data = baseData();
    data.abilities = [
      {
        ...emptyAbility("abil_001", "霊視"),
        appearedChapters: [2],
        spoilerLevel: "author_only",
      },
    ];

    const built = buildExportMarkdown("editorial", data, {
      ...OPTIONS,
      chapter: null,
    });

    // 能力の章に出ないだけでは足りない。**人物欄の「能力」に名前が残る**
    expect(built).not.toContain("**能力**: 霊視");
  });

  test("能力の「使い手」も、話数と公開範囲で絞る", () => {
    const data = baseData();
    data.characters = [
      fullCharacter(),
      { ...emptyCharacter("char_002", "影の使い手"), appearedChapters: [9] },
    ];
    data.abilities = [
      {
        ...emptyAbility("abil_001", "霊視"),
        appearedChapters: [2],
        userNames: ["月島灯", "影の使い手"],
      },
    ];

    const built = buildExportMarkdown("editorial", data, {
      ...OPTIONS,
      chapter: 3,
    });

    expect(built).toContain("**使い手**: 月島灯");
    expect(built).not.toContain("影の使い手");
  });
});

describe("呼称の相手を絞る", () => {
  test("作者だけの印が付いた相手への呼称は、行ごと出さない", () => {
    const data = baseData();
    data.characters = [
      fullCharacter(),
      {
        ...emptyCharacter("char_002", "白鳥"),
        appearedChapters: [1],
        spoilerLevel: "author_only",
      },
    ];

    const built = buildExportMarkdown("editorial", data, {
      ...OPTIONS,
      chapter: null,
    });

    expect(built).not.toContain("白鳥への呼称");
  });

  test("あとから登場する相手への呼称も出さない", () => {
    const data = baseData();
    data.characters = [
      fullCharacter(),
      { ...emptyCharacter("char_002", "白鳥"), appearedChapters: [9] },
    ];

    const built = buildExportMarkdown("editorial", data, {
      ...OPTIONS,
      chapter: 3,
    });

    expect(built).not.toContain("白鳥への呼称");
  });

  test("いつから使われたか分からない呼称は、時点を絞ったら出さない", () => {
    const data = baseData();
    const base = fullCharacter();
    data.characters = [
      {
        ...base,
        addressTerms: [
          {
            ...base.addressTerms[0],
            forms: [{ ...base.addressTerms[0].forms[0], firstChapter: null }],
          },
        ],
      },
      { ...emptyCharacter("char_002", "白鳥"), appearedChapters: [1] },
    ];

    expect(
      buildExportMarkdown("editorial", data, { ...OPTIONS, chapter: 3 })
    ).not.toContain("白鳥さん");
    // 全話ぶんなら、これまでどおり出す
    expect(
      buildExportMarkdown("editorial", data, { ...OPTIONS, chapter: null })
    ).toContain("白鳥さん");
  });
});

/**
 * 時点の記録を持たない項目（本体の裁定、0.32.6）。
 *
 * 年齢・容姿・服装・別名と作者が足した項目は、いつ変わったかの記録が無い。
 * **落とすと資料が用をなさない**（イラスト発注の中心項目である）ので、
 * 落とさずに、冒頭で正直に断る。
 */
describe("時点の記録を持たない項目を、冒頭で断る", () => {
  test("第N話までに絞ったときは、そう書く", () => {
    const built = build("illustration", 3);

    expect(built).toContain("時点の記録を持たない");
    for (const label of ["年齢", "容姿", "服装"]) {
      expect(built, label).toContain(label);
    }
    // 中身そのものは、これまでどおり載る（落とさない）
    expect(built).toContain("17歳");
    expect(built).toContain("紺のブレザーに赤いマフラー");
  });

  test("全話ぶんのときは、断り書きを出さない", () => {
    expect(build("illustration", null)).not.toContain("時点の記録を持たない");
  });

  test("その型が出さない項目は、断り書きにも並べない", () => {
    // 紹介向けは名前と紹介文だけなので、断るものが無い
    expect(build("introduction", 3)).not.toContain("時点の記録を持たない");
  });
});
