import { describe, expect, test } from "vitest";
import {
  decideSettingsConflict,
  isSettingsJsonPath,
} from "../../src/core/settingsConflictRule";

/**
 * 設定資料の衝突を、規則で決める（設計書5.5.18）。
 *
 * 作者の指示（2026-09-10）：「設定資料ファイルは作者が書き換えた部分が
 * 変わっていなければ、時系列的に新しいほうに自動で合わせてください」。
 *
 * **決めてよい線引きを、ここで固定する。** 広く取りすぎるとAIの抽出結果の
 * 違いまで作者への問いになり（0.44.0までがそうだった）、狭く取りすぎると
 * 作者が手で書いた値をもう一方の端末の読みが押し流す。
 */

/** 円記号。**文字列にそのまま置くと読みにくい**ので符号から作る */
const BS = String.fromCharCode(92);

/** 人物1件ぶんのJSON。既定はAIが作ったレコード */
function 人物(input: {
  summary?: string;
  authorNotes?: string;
  exportNote?: string;
  autoGenerated?: boolean;
  updatedAt?: string;
  appearedChapters?: number[];
  addressTerms?: unknown[];
  distinctFrom?: unknown[];
}): string {
  return JSON.stringify({
    schemaVersion: "0.1",
    id: "char_001",
    name: "太志",
    summary: input.summary ?? "紹介文",
    appearedChapters: input.appearedChapters ?? [1, 2],
    addressTerms: input.addressTerms ?? [],
    distinctFrom: input.distinctFrom ?? [],
    changes: [],
    authorNotes: input.authorNotes ?? "",
    exportNote: input.exportNote ?? "",
    autoGenerated: input.autoGenerated ?? true,
    updatedAt: input.updatedAt ?? "2026-09-01T00:00:00.000Z",
  });
}

describe("設定資料のJSONかの見分け", () => {
  test("設定フォルダーの下のJSONを見る", () => {
    expect(isSettingsJsonPath("短編/設定/characters/char_001_太志.json")).toBe(
      true
    );
    expect(isSettingsJsonPath("短編/設定/custom_fields.json")).toBe(true);
  });

  test("拡張機能の作業場所は対象にしない", () => {
    // 承認待ちは自動生成物として別に扱う（`mergePreview.ts`）
    expect(
      isSettingsJsonPath("短編/.aiwriter/pending-characters/char_001.json")
    ).toBe(false);
    expect(isSettingsJsonPath("短編/設定/_schema/character.json")).toBe(false);
  });

  test("本文は対象にしない", () => {
    expect(isSettingsJsonPath("短編/本文/第1話.txt")).toBe(false);
    // 設定フォルダーの外のJSONも見ない（作品ごとに置き場の名前は変えられる）
    expect(isSettingsJsonPath("短編/メモ/覚書.json")).toBe(false);
  });

  test("Windowsの区切りでも同じに見る", () => {
    expect(
      isSettingsJsonPath(`短編${BS}設定${BS}characters${BS}char_001.json`)
    ).toBe(true);
  });
});

describe("規則1：作者が書いた部分が同じなら、新しいほうへ", () => {
  test("別環境のほうが新しければ、別環境を採る", () => {
    const decision = decideSettingsConflict({
      ours: 人物({ summary: "こちらの読み", updatedAt: "2026-09-03T00:00:00.000Z" }),
      theirs: 人物({ summary: "むこうの読み", updatedAt: "2026-09-05T00:00:00.000Z" }),
    });

    expect(decision.side).toBe("theirs");
    expect(decision.reason).toContain("別の環境の側が新しい");
  });

  test("この端末のほうが新しければ、この端末を採る", () => {
    const decision = decideSettingsConflict({
      ours: 人物({ summary: "こちらの読み", updatedAt: "2026-09-07T00:00:00.000Z" }),
      theirs: 人物({ summary: "むこうの読み", updatedAt: "2026-09-05T00:00:00.000Z" }),
    });

    expect(decision.side).toBe("ours");
  });

  test("同じ時刻なら、順序を決められないのでこの端末を残す", () => {
    // **中身はどちらもAIの抽出結果**なので、いま画面に出ているものを残す
    const decision = decideSettingsConflict({
      ours: 人物({ summary: "こちらの読み" }),
      theirs: 人物({ summary: "むこうの読み" }),
    });

    expect(decision.side).toBe("ours");
    expect(decision.reason).toContain("更新時刻では新しいほうを決められない");
  });

  test("登場話数の違いは、作者の手とみなさない", () => {
    // 抽出が追記するだけの配列である（CLAUDE.md）
    const decision = decideSettingsConflict({
      ours: 人物({
        appearedChapters: [1, 2],
        updatedAt: "2026-09-03T00:00:00.000Z",
      }),
      theirs: 人物({
        appearedChapters: [1, 2, 3],
        updatedAt: "2026-09-05T00:00:00.000Z",
      }),
    });

    expect(decision.side).toBe("theirs");
  });
});

describe("規則2：共通の祖先から動いたのが片側だけなら、動いたほうを残す", () => {
  const 祖先 = 人物({ updatedAt: "2026-09-01T00:00:00.000Z" });

  test("この端末だけが作者メモを足したら、この端末を残す", () => {
    const decision = decideSettingsConflict({
      base: 祖先,
      ours: 人物({
        authorNotes: "この子は左利き",
        updatedAt: "2026-09-02T00:00:00.000Z",
      }),
      // 別環境は紹介文だけが変わった（AIの抽出）。**時刻は新しい**
      theirs: 人物({
        summary: "むこうの読み",
        updatedAt: "2026-09-09T00:00:00.000Z",
      }),
    });

    // **時刻では負けているが、作者の手が入っているほうを残す**
    expect(decision.side).toBe("ours");
    expect(decision.reason).toContain("この端末の側だけ");
  });

  test("別環境だけが作者メモを足したら、別環境を残す", () => {
    const decision = decideSettingsConflict({
      base: 祖先,
      ours: 人物({ summary: "こちらの読み", updatedAt: "2026-09-09T00:00:00.000Z" }),
      theirs: 人物({
        authorNotes: "編集部からの直し",
        updatedAt: "2026-09-02T00:00:00.000Z",
      }),
    });

    expect(decision.side).toBe("theirs");
    expect(decision.reason).toContain("別の環境の側だけ");
  });
});

describe("規則3：決めないもの", () => {
  test("両方で作者メモを変えたら、作者に選ばせる", () => {
    const decision = decideSettingsConflict({
      base: 人物({}),
      ours: 人物({ authorNotes: "こちらのメモ" }),
      theirs: 人物({ authorNotes: "むこうのメモ" }),
    });

    expect(decision.side).toBe("conflict");
    expect(decision.reason).toContain("作者が書いた部分が両方で違います");
  });

  test("作者が固定した呼称が違えば、決めない", () => {
    // `authorLocked: true` の呼称は変えない（CLAUDE.md）
    const locked = (term: string) => [
      {
        targetName: "美咲",
        targetId: null,
        forms: [{ term, category: null, context: null, firstChapter: 1, lastChapter: null, status: "current", evidence: null }],
        authorLocked: true,
      },
    ];
    const decision = decideSettingsConflict({
      ours: 人物({ addressTerms: locked("みさきさん") }),
      theirs: 人物({ addressTerms: locked("美咲") }),
    });

    expect(decision.side).toBe("conflict");
  });

  test("固定していない呼称の違いは、決めるのを妨げない", () => {
    // 抽出のたびに増える。**ここを作者の手に数えると、毎回問いになる**
    const free = (term: string) => [
      {
        targetName: "美咲",
        targetId: null,
        forms: [{ term, category: null, context: null, firstChapter: 1, lastChapter: null, status: "current", evidence: null }],
        authorLocked: false,
      },
    ];
    const decision = decideSettingsConflict({
      ours: 人物({ addressTerms: free("みさきさん"), updatedAt: "2026-09-03T00:00:00.000Z" }),
      theirs: 人物({ addressTerms: free("美咲"), updatedAt: "2026-09-05T00:00:00.000Z" }),
    });

    expect(decision.side).toBe("theirs");
  });

  test("壊れたJSONは決めない", () => {
    // **勝手に直さない**（CLAUDE.md）
    const decision = decideSettingsConflict({
      ours: "{ここが壊れている",
      theirs: 人物({}),
    });

    expect(decision.side).toBe("conflict");
    expect(decision.reason).toContain("JSONとして読めない");
  });
});

describe("作者が確定させたレコード（autoGenerated: false）", () => {
  test("紹介文が違えば、決めない", () => {
    // **登場話数の追記以外AIは触らない**約束なので、
    // 違っているならそれは作者の手である（CLAUDE.md）
    const decision = decideSettingsConflict({
      ours: 人物({
        autoGenerated: false,
        summary: "こちらで書いた紹介",
        updatedAt: "2026-09-03T00:00:00.000Z",
      }),
      theirs: 人物({
        autoGenerated: false,
        summary: "むこうで書いた紹介",
        updatedAt: "2026-09-05T00:00:00.000Z",
      }),
    });

    expect(decision.side).toBe("conflict");
  });

  test("中身が同じで更新時刻だけ違うなら、新しいほうへ", () => {
    // 保存し直しただけ。**これで問いを出すと、確定したレコードほど詰まる**
    const decision = decideSettingsConflict({
      ours: 人物({ autoGenerated: false, updatedAt: "2026-09-03T00:00:00.000Z" }),
      theirs: 人物({ autoGenerated: false, updatedAt: "2026-09-05T00:00:00.000Z" }),
    });

    expect(decision.side).toBe("theirs");
  });

  test("登場話数だけが違うなら、新しいほうへ", () => {
    const decision = decideSettingsConflict({
      ours: 人物({
        autoGenerated: false,
        appearedChapters: [1],
        updatedAt: "2026-09-05T00:00:00.000Z",
      }),
      theirs: 人物({
        autoGenerated: false,
        appearedChapters: [1, 2],
        updatedAt: "2026-09-03T00:00:00.000Z",
      }),
    });

    expect(decision.side).toBe("ours");
  });
});

describe("1件1ファイルではない台帳", () => {
  /** `custom_fields.json` のような、作者が直に書く台帳 */
  const 台帳 = (fields: string[], updatedAt: string) =>
    JSON.stringify({ schemaVersion: "0.1", fields, updatedAt });

  test("中身が違えば決めない（作者が直に書く場所である）", () => {
    const decision = decideSettingsConflict({
      ours: 台帳(["出身地"], "2026-09-03T00:00:00.000Z"),
      theirs: 台帳(["好きな食べ物"], "2026-09-05T00:00:00.000Z"),
    });

    expect(decision.side).toBe("conflict");
  });

  test("更新時刻だけが違えば、新しいほうへ", () => {
    const decision = decideSettingsConflict({
      ours: 台帳(["出身地"], "2026-09-03T00:00:00.000Z"),
      theirs: 台帳(["出身地"], "2026-09-05T00:00:00.000Z"),
    });

    expect(decision.side).toBe("theirs");
  });
});
