import { describe, expect, test } from "vitest";
import { buildSynopsisListMarkdown } from "../../src/core/synopsisMarkdown";
import type { ChapterSynopsis } from "../../src/models/synopsis";

function episode(overrides: Partial<ChapterSynopsis> = {}): ChapterSynopsis {
  return {
    chapter: 1,
    fileName: "001.txt",
    title: null,
    synopsis: "灯が幽霊になったことに気づく。",
    sourceHash: "hash",
    model: "test",
    promptVersion: "1.0",
    autoGenerated: true,
    authorNotes: "",
    updatedAt: null,
    ...overrides,
  };
}

const options = { workTitle: "いじめられっ子" };

describe("各話あらすじの読み物", () => {
  test("話数とサブタイトルを見出しにして並べる", () => {
    const md = buildSynopsisListMarkdown(
      {
        schemaVersion: "0.1",
        episodes: [
          episode({ chapter: 1, title: "気がついたら幽霊に" }),
          episode({ chapter: 2, synopsis: "ばあさんに拾われる。" }),
        ],
      },
      options
    );

    expect(md).toContain("# いじめられっ子 各話あらすじ");
    expect(md).toContain("## 第1話 気がついたら幽霊に");
    expect(md).toContain("## 第2話");
    expect(md).toContain("ばあさんに拾われる。");
  });

  test("作者が書き直したあらすじは、その旨が分かる", () => {
    // AIが作ったものと区別が付かないと、作り直してよいか判断できない
    const md = buildSynopsisListMarkdown(
      {
        schemaVersion: "0.1",
        episodes: [episode({ autoGenerated: false, authorNotes: "伏線" })],
      },
      options
    );

    expect(md).toContain("作者が書き直したあらすじ");
    expect(md).toContain("**メモ**: 伏線");
  });

  test("話数が無い話はファイル名を見出しにする", () => {
    const md = buildSynopsisListMarkdown(
      {
        schemaVersion: "0.1",
        episodes: [episode({ chapter: null, fileName: "about.txt" })],
      },
      options
    );

    expect(md).toContain("## about.txt");
  });

  test("何も無ければその旨を書く", () => {
    expect(
      buildSynopsisListMarkdown({ schemaVersion: "0.1", episodes: [] }, options)
    ).toContain("まだあらすじがありません");
  });
});
