import { describe, expect, test } from "vitest";
import { buildSynopsisListMarkdown } from "../../src/core/synopsisMarkdown";
import type { ChapterSynopsis } from "../../src/models/synopsis";

function episode(overrides: Partial<ChapterSynopsis> = {}): ChapterSynopsis {
  return {
    chapter: 1,
    fileName: "001.txt",
    title: null,
    synopsis: "灯が幽霊になったことに気づく。",
    sourceHash: "hash",
    model: "test",
    promptVersion: "1.0",
    autoGenerated: true,
    authorNotes: "",
    updatedAt: null,
    ...overrides,
  };
}

const options = { workTitle: "いじめられっ子" };

describe("各話あらすじの読み物", () => {
  test("話数とサブタイトルを見出しにして並べる", () => {
    const md = buildSynopsisListMarkdown(
      {
        schemaVersion: "0.1",
        episodes: [
          episode({ chapter: 1, title: "気がついたら幽霊に" }),
          episode({ chapter: 2, synopsis: "ばあさんに拾われる。" }),
        ],
      },
      options
    );

    expect(md).toContain("# いじめられっ子 各話あらすじ");
    expect(md).toContain("## 第1話 気がついたら幽霊に");
    expect(md).toContain("## 第2話");
    expect(md).toContain("ばあさんに拾われる。");
  });

  test("作者が書き直したあらすじは、その旨が分かる", () => {
    // AIが作ったものと区別が付かないと、作り直してよいか判断できない
    const md = buildSynopsisListMarkdown(
      {
        schemaVersion: "0.1",
        episodes: [episode({ autoGenerated: false, authorNotes: "伏線" })],
      },
      options
    );

    expect(md).toContain("作者が書き直したあらすじ");
    expect(md).toContain("**メモ**: 伏線");
  });

  test("話数が無い話はファイル名を見出しにする", () => {
    const md = buildSynopsisListMarkdown(
      {
        schemaVersion: "0.1",
        episodes: [episode({ chapter: null, fileName: "about.txt" })],
      },
      options
    );

    expect(md).toContain("## about.txt");
  });

  test("何も無ければその旨を書く", () => {
    expect(
      buildSynopsisListMarkdown({ schemaVersion: "0.1", episodes: [] }, options)
    ).toContain("まだあらすじがありません");
  });
});

/**
 * **見出しの二重**（2026-08-19、作者が実機で発見）。
 *
 * 投稿サイトの題は「第1話　気がついたら幽霊」のように**話数を含む**。
 * 見出し側にも「第1話」を出すので、そのまま並べると二重になる。
 *
 * 一覧（`workTree`）と文字数表（`episodeCharTable`）は `episodeTitle` を
 * 通していたが、**あらすじだけが漏れていた。**
 */
describe("見出しに話数を二重に出さない", () => {
  const build = (title: string | null) =>
    buildSynopsisListMarkdown(
      { schemaVersion: "0.1", episodes: [episode({ chapter: 1, title })] },
      options
    );

  test("題に「第1話」が入っていたら、片方を落とす", () => {
    const md = build("第1話　気がついたら幽霊");

    expect(md).toContain("## 第1話 気がついたら幽霊");
    expect(md).not.toContain("第1話 第1話");
  });

  test("区切りが記号でも落とす", () => {
    expect(build("第1話：気がついたら幽霊")).toContain(
      "## 第1話 気がついたら幽霊"
    );
  });

  test("題が話数だけなら、題を出さない", () => {
    // **同じ文字を右にもう一度出しても、伝わる情報が増えない**
    expect(build("第1話")).not.toContain("第1話 第1話");
  });

  test("話数を含まない題は、そのまま出す", () => {
    expect(build("気がついたら幽霊")).toContain("## 第1話 気がついたら幽霊");
  });

  test("題が無ければ、見出しは話数だけ", () => {
    expect(build(null)).toContain("## 第1話");
  });
});

/**
 * 章の見出しを挟む（設計書6.66.4の3）。
 *
 * 章立ての台帳がある作品では、各話あらすじの一覧に**章ごとの見出し**を
 * 挟む。挟む場所は「その章が始まる話の直前」で、最初の章より前の話は
 * 先頭にそのまま並ぶ。
 *
 * **台帳が無い作品は、いままでどおり**（章の見出しは1つも出ない）。
 */
describe("章の見出しを挟む", () => {
  const set = {
    schemaVersion: "0.1",
    episodes: [
      episode({ chapter: 1, fileName: "001.txt", synopsis: "序。" }),
      episode({ chapter: 2, fileName: "002.txt", synopsis: "旅立ち。" }),
      episode({ chapter: 3, fileName: "003.txt", synopsis: "出会い。" }),
    ],
  };

  test("章が始まる話の直前に見出しを挟む", () => {
    const md = buildSynopsisListMarkdown(set, {
      ...options,
      chapters: [
        { name: "第一章　出立", startKey: "#2", range: "第2話〜第3話・2話" },
      ],
    });

    expect(md).toContain("## 第一章　出立（第2話〜第3話・2話）");
    // 章の見出しは第2話の前。第1話（章なし）は見出しより上に残る
    expect(md.indexOf("序。")).toBeLessThan(md.indexOf("第一章　出立"));
    expect(md.indexOf("第一章　出立")).toBeLessThan(md.indexOf("旅立ち。"));
  });

  test("章があるときは、話の見出しを1段深くする", () => {
    // 章と話が同じ深さだと、章の下に話が入っているように読めない
    const md = buildSynopsisListMarkdown(set, {
      ...options,
      chapters: [{ name: "第一章", startKey: "#1", range: "" }],
    });

    expect(md).toContain("## 第一章");
    expect(md).toContain("### 第1話");
  });

  test("範囲が無ければ、章名だけを出す", () => {
    const md = buildSynopsisListMarkdown(set, {
      ...options,
      chapters: [{ name: "第一章", startKey: "#1", range: "" }],
    });

    expect(md).toContain("## 第一章\n");
    expect(md).not.toContain("第一章（");
  });

  test("台帳が無ければ、いままでどおり章の見出しは出ない", () => {
    const md = buildSynopsisListMarkdown(set, options);

    expect(md).not.toContain("### ");
    expect(md).toContain("## 第1話");
  });

  test("紹介文の文書へ差し込むときも、章が話より浅い", () => {
    // `## 各話あらすじ` の下に入るので、章は `###`、話は `####`
    const md = buildSynopsisListMarkdown(set, {
      ...options,
      headingLevel: 2,
      includeTitle: false,
      chapters: [{ name: "第一章", startKey: "#1", range: "第1話〜第3話・3話" }],
    });

    expect(md).toContain("### 第一章（第1話〜第3話・3話）");
    expect(md).toContain("#### 第1話");
  });
});
