import { describe, expect, test } from "vitest";
import {
  parseSynopsisResult,
  validateSynopsisResult,
} from "../../src/core/synopsisValidation";
import {
  emptySynopsisSet,
  findSynopsis,
  parseSynopsisSet,
  upsertSynopsis,
  type ChapterSynopsis,
} from "../../src/models/synopsis";
import { buildSynopsisPrompt } from "../../src/prompts/synopsis";

function episode(overrides: Partial<ChapterSynopsis> = {}): ChapterSynopsis {
  return {
    chapter: 1,
    fileName: "001.txt",
    title: null,
    synopsis: "灯が幽霊になったことに気づく。",
    sourceHash: "hash1",
    model: "test",
    promptVersion: "1.0",
    autoGenerated: true,
    authorNotes: "",
    updatedAt: null,
    ...overrides,
  };
}

describe("あらすじの応答を読む", () => {
  test("コードフェンス付きでも読める", () => {
    const result = parseSynopsisResult(
      '```json\n{"synopsis":"灯が転生する。","subtitles":[],"confidence":"high"}\n```'
    );

    expect(result?.synopsis).toBe("灯が転生する。");
  });

  test("形が違えば null を返す（壊れた値を保存しない）", () => {
    expect(parseSynopsisResult("こんにちは")).toBeNull();
    expect(parseSynopsisResult('{"subtitles":[]}')).toBeNull();
  });
});

describe("サブタイトル案の検証", () => {
  const build = (texts: string[]) => ({
    synopsis: "灯が転生する。",
    subtitles: texts.map((text) => ({ text, kind: "出来事型", reason: null })),
    confidence: "high",
  });

  test("15字を超える案は落とす（切り詰めない）", () => {
    // 途中で切れた言葉はサブタイトルにならない
    const result = validateSynopsisResult(
      build(["湖畔の誓い", "あまりにも長すぎて到底入りきらないサブタイトルの案"])
    );

    expect(result.subtitles.map((s) => s.text)).toEqual(["湖畔の誓い"]);
    expect(result.rejectedSubtitles[0].reason).toBe("too_long");
  });

  test("ファイル名に使えない文字を含む案は落とす", () => {
    // そのままファイル名になるので、通すと作者の原稿ファイルが壊れる
    const result = validateSynopsisResult(build(["再会/別離", "再会と別離"]));

    expect(result.subtitles.map((s) => s.text)).toEqual(["再会と別離"]);
    expect(result.rejectedSubtitles[0].reason).toBe("forbidden_char");
  });

  test("同じ案が重なったら1つにする", () => {
    const result = validateSynopsisResult(build(["湖畔の誓い", "湖畔の誓い"]));

    expect(result.subtitles).toHaveLength(1);
    expect(result.rejectedSubtitles[0].reason).toBe("duplicate");
  });

  test("あらすじは150字に収める", () => {
    const result = validateSynopsisResult({
      synopsis: "あ".repeat(300),
      subtitles: [],
      confidence: "high",
    });

    expect(result.synopsis.length).toBeLessThanOrEqual(150);
  });
});

describe("あらすじの保存", () => {
  test("同じ話は差し替え、話数の順に並べる", () => {
    const first = upsertSynopsis(emptySynopsisSet(), episode({ chapter: 3 }));
    const second = upsertSynopsis(first.set, episode({ chapter: 1 }));
    const third = upsertSynopsis(
      second.set,
      episode({ chapter: 3, synopsis: "書き直し" })
    );

    expect(third.set.episodes.map((e) => e.chapter)).toEqual([1, 3]);
    expect(findSynopsis(third.set, "001.txt", 3)?.synopsis).toBe("書き直し");
  });

  test("作者が書き直したあらすじは上書きしない", () => {
    const authored = upsertSynopsis(
      emptySynopsisSet(),
      episode({ synopsis: "作者が書いたあらすじ", autoGenerated: false })
    );

    const result = upsertSynopsis(
      authored.set,
      episode({ synopsis: "AIが作ったあらすじ" })
    );

    expect(result.set.episodes[0].synopsis).toBe("作者が書いたあらすじ");
    expect(result.skippedByAuthor).toBe(true);
  });

  test("作者のメモは生成で消えない", () => {
    const withNote = upsertSynopsis(
      emptySynopsisSet(),
      episode({ authorNotes: "この話は伏線" })
    );

    const result = upsertSynopsis(
      withNote.set,
      episode({ synopsis: "作り直し" })
    );

    expect(result.set.episodes[0].authorNotes).toBe("この話は伏線");
    expect(result.set.episodes[0].synopsis).toBe("作り直し");
  });

  test("合本のように同じファイル名で話数が違うものを区別する", () => {
    const first = upsertSynopsis(
      emptySynopsisSet(),
      episode({ fileName: "N2600GO.txt", chapter: 1 })
    );
    const second = upsertSynopsis(
      first.set,
      episode({ fileName: "N2600GO.txt", chapter: 2, synopsis: "2話" })
    );

    expect(second.set.episodes).toHaveLength(2);
  });
});

describe("あらすじJSONの検証", () => {
  test("壊れていたら例外にする（空として上書きしない）", () => {
    expect(() => parseSynopsisSet({ episodes: [] })).toThrow("schemaVersion");
    expect(() =>
      parseSynopsisSet({ schemaVersion: "0.1", episodes: [{ fileName: "a" }] })
    ).toThrow("synopsis");
  });

  test("欠けている任意項目は既定値で補う", () => {
    const set = parseSynopsisSet({
      schemaVersion: "0.1",
      episodes: [{ fileName: "001.txt", synopsis: "あらすじ" }],
    });

    expect(set.episodes[0]).toMatchObject({
      chapter: null,
      autoGenerated: true,
      authorNotes: "",
    });
  });
});

describe("あらすじのプロンプト", () => {
  test("サブタイトルが要らないときは空配列を求める", () => {
    const prompt = buildSynopsisPrompt({
      chapterLabel: "第7話",
      chapterText: "本文",
      previousSynopses: [],
      characterNames: [],
      needsSubtitle: false,
    });

    expect(prompt).toContain("subtitles は空配列");
    expect(prompt).not.toContain("3案提案してください");
  });

  test("前話のあらすじから出来事を持ち込ませない", () => {
    const prompt = buildSynopsisPrompt({
      chapterLabel: "第7話",
      chapterText: "本文",
      previousSynopses: ["第6話のあらすじ"],
      characterNames: ["灯"],
      needsSubtitle: true,
    });

    expect(prompt).toContain("ここから出来事を持ち込まないこと");
    expect(prompt).toContain("第6話のあらすじ");
  });
});
