import { afterEach, beforeEach, describe, expect, test, vi } from "vitest";
import { execFileSync } from "node:child_process";
import * as fs from "node:fs";
import * as os from "node:os";
import * as nodePath from "node:path";

/**
 * 1件ずつ見比べる入口（設計書5.5.18）。
 *
 * 作者の手元で13作品ぶんの分岐が起き、**「1件ずつ選ぶ」しか道が無い画面から
 * 抜けられなくなった**（2026-09-11）。作者の言葉：「全部最新を優先する
 * 選択肢をまず提示し、操作をシンプルにしてください」。
 *
 * ここでも vscode だけを差し替えて、**gitとファイルは本物を使う**。
 * 索引の版を取り出して書き戻すところは、作り物の返事では確かめられない。
 */

/** 画面に出た問いと、答えとして用意したボタン */
const answers: string[] = [];
const shown: string[] = [];
/** QuickPick で選ぶ項目の見出し（含まれていれば、それを選ぶ） */
const picks: string[] = [];

vi.mock("vscode", () => {
  const readFile = async (uri: { fsPath: string }) =>
    new Uint8Array(fs.readFileSync(uri.fsPath));
  return {
    window: {
      showInformationMessage: (message: string, ...rest: unknown[]) => {
        record(message, rest);
        return Promise.resolve(pickAnswer(rest));
      },
      showWarningMessage: (message: string, ...rest: unknown[]) => {
        record(message, rest);
        return Promise.resolve(pickAnswer(rest));
      },
      showErrorMessage: (message: string, ...rest: unknown[]) => {
        record(message, rest);
        return Promise.resolve(pickAnswer(rest));
      },
      showQuickPick: (items: unknown, options?: { title?: string }) => {
        shown.push(options?.title ?? "（見出しなし）");
        return Promise.resolve(pickItem(items));
      },
      showTextDocument: () => Promise.resolve(undefined),
      createOutputChannel: () => ({
        appendLine() {},
        show() {},
        dispose() {},
      }),
    },
    workspace: {
      fs: { readFile },
      getConfiguration: () => ({ get: () => undefined }),
      openTextDocument: () => Promise.resolve({}),
      textDocuments: [],
    },
    commands: {
      registerCommand: () => ({ dispose() {} }),
      executeCommand: () => Promise.resolve(undefined),
    },
    languages: { setTextDocumentLanguage: () => Promise.resolve(undefined) },
    Uri: {
      file: (value: string) => ({ fsPath: value, scheme: "file", path: value }),
      parse: (value: string) => ({ fsPath: value, scheme: "file", path: value }),
      from: (parts: { scheme: string; path: string }) => ({
        ...parts,
        fsPath: parts.path,
        toString: () => `${parts.scheme}:${parts.path}`,
      }),
    },
    Position: class {
      constructor(
        public line: number,
        public character: number
      ) {}
    },
    WorkspaceEdit: class {
      insert() {}
    },
    EventEmitter: class {
      event = () => ({ dispose() {} });
      fire() {}
      dispose() {}
    },
  };
});

function record(message: string, rest: unknown[]): void {
  const detail = rest.find(
    (item): item is { detail?: string } =>
      typeof item === "object" && item !== null && "detail" in item
  )?.detail;
  shown.push(detail ? `${message}\n${detail}` : message);
}

function pickAnswer(rest: unknown[]): string | undefined {
  const buttons = rest.filter((item) => typeof item === "string") as string[];
  return answers.find((answer) => buttons.includes(answer));
}

/** 用意した見出しに当たる項目を返す。当たらなければ「取りやめる」扱い */
function pickItem(items: unknown): unknown {
  if (!Array.isArray(items)) return undefined;
  for (const wanted of picks) {
    const found = items.find(
      (item) =>
        typeof item === "object" &&
        item !== null &&
        typeof (item as { label?: unknown }).label === "string" &&
        (item as { label: string }).label.includes(wanted)
    );
    if (found) return found;
  }
  return undefined;
}

const {
  ConflictContentProvider,
  describeWalkStart,
  describeWalkStartDetail,
  walkConflicts,
} = await import("../../src/features/resolveConflicts");

let root: string;

function git(cwd: string, ...args: string[]): string {
  return execFileSync("git", args, { cwd, encoding: "utf8" });
}

function write(dir: string, file: string, body: string): void {
  const full = nodePath.join(dir, file);
  fs.mkdirSync(nodePath.dirname(full), { recursive: true });
  fs.writeFileSync(full, body);
}

const 人物ファイル = "いじめられっ子/設定/characters/char_001.json";
const 原稿ファイル = "いじめられっ子/本文/第1話.txt";

function 人物(summary: string, updatedAt: string): string {
  return `${JSON.stringify(
    {
      schemaVersion: "0.1",
      id: "char_001",
      name: "太志",
      summary,
      appearedChapters: [1],
      authorNotes: "",
      exportNote: "",
      autoGenerated: true,
      updatedAt,
    },
    null,
    2
  )}\n`;
}

/**
 * 両方の側で同じ箇所を書き換えた状態を作り、**本物のマージを途中で止める**。
 * この状態でないと、索引の2番・3番の版を取り出せない。
 */
function setUpConflict(): void {
  root = fs.mkdtempSync(nodePath.join(os.tmpdir(), "novelai-walk-"));
  git(root, "init", "-q", "-b", "main");
  // 端末のgitの設定で結果が変わらないようにする
  git(root, "config", "core.autocrlf", "false");
  git(root, "config", "user.name", "作者");
  git(root, "config", "user.email", "author@example.com");

  write(root, 人物ファイル, 人物("もとの紹介", "2026-09-01T00:00:00.000Z"));
  write(root, 原稿ファイル, "もとの一行。\n");
  git(root, "add", "-A");
  git(root, "commit", "-qm", "土台");

  git(root, "checkout", "-q", "-b", "別環境");
  write(root, 人物ファイル, 人物("むこうの紹介", "2026-09-05T00:00:00.000Z"));
  write(root, 原稿ファイル, "むこうの一行。\n");
  git(root, "commit", "-qam", "別のPCで直した");

  git(root, "checkout", "-q", "main");
  write(root, 人物ファイル, 人物("こちらの紹介", "2026-09-03T00:00:00.000Z"));
  write(root, 原稿ファイル, "こちらの一行。\n");
  git(root, "commit", "-qam", "こちらで直した");

  // 衝突するので終了コードは 0 にならない。**止まった状態が欲しい**
  try {
    git(root, "merge", "--no-commit", "別環境");
  } catch {
    // CONFLICT で落ちるのが正しい
  }
}

function scope() {
  return { id: "w1", title: "いじめられっ子", folderPath: root };
}

function read(file: string): string {
  return fs.readFileSync(nodePath.join(root, file), "utf8");
}

beforeEach(() => {
  answers.length = 0;
  shown.length = 0;
  picks.length = 0;
});

afterEach(() => {
  vi.restoreAllMocks();
});

// 本物のgitを子プロセスで何度も起動するので、既定の5秒では足りない
describe("全部、新しいほうを採る", { timeout: 30_000 }, () => {
  beforeEach(() => {
    setUpConflict();
  });

  test("設定資料は一度に片づき、原稿だけ見比べに回る", async () => {
    answers.push("全部、新しいほうを採る");
    // 原稿は1件ずつ。ここでは「こちら」を選ぶ
    picks.push("こちらを採用");

    const result = await walkConflicts(scope(), [人物ファイル, 原稿ファイル], {
      provider: new ConflictContentProvider(),
    });

    expect(result.aborted).toBe(false);
    // **一括で寄せた分と、選んでもらった分は分けて返す**（2026-09-11）。
    // 混ぜると、済んだあとの知らせが一括の分まで
    // 「お選びいただきました」と言ってしまう
    expect(result.bulkResolved).toEqual([人物ファイル]);
    expect(result.resolved).toEqual([原稿ファイル]);
    // 設定資料は更新時刻の新しいほう（別環境）へ揃った
    expect(read(人物ファイル)).toContain("むこうの紹介");
    // **原稿は一括で寄せない。** 作者が選んだ側になる
    expect(read(原稿ファイル)).toBe("こちらの一行。\n");
    // 見比べの画面は原稿の1件だけ
    expect(shown.filter((text) => text.includes("をどう解決しますか"))).toHaveLength(
      1
    );
  });

  /**
   * 一括で寄せた分を `resolved` に混ぜない（2026-09-11）。
   *
   * 作者が13件を一括で片づけたのに、済んだあとの知らせが
   * 「本文など13件はお選びいただきました」と出ていた。数え分けは、
   * 文面を組む側（`describeFoldSuccess`）ではなく**ここで**する——
   * 混ぜて渡すと、受け取った側にはもう分けようがない。
   */
  test("一括で寄せたものは resolved に入らない", async () => {
    answers.push("全部、新しいほうを採る");
    picks.push("こちらを採用");

    const result = await walkConflicts(scope(), [人物ファイル, 原稿ファイル], {
      provider: new ConflictContentProvider(),
    });

    expect(result.resolved).not.toContain(人物ファイル);
    expect(result.bulkResolved).not.toContain(原稿ファイル);
    // どちらにも入らないファイルは無い（**確定した分は必ずどちらかで数える**）
    expect([...result.resolved, ...result.bulkResolved].sort()).toEqual(
      [人物ファイル, 原稿ファイル].sort()
    );
  });

  test("設定資料しか無ければ、見比べを1件も出さずに終わる", async () => {
    answers.push("全部、新しいほうを採る");

    const result = await walkConflicts(scope(), [人物ファイル], {
      provider: new ConflictContentProvider(),
    });

    expect(result.aborted).toBe(false);
    // 作者は1件も選んでいない。**`resolved` は空のままにする**
    expect(result.resolved).toEqual([]);
    expect(result.bulkResolved).toEqual([人物ファイル]);
    expect(shown.filter((text) => text.includes("をどう解決しますか"))).toEqual(
      []
    );
  });

  test("1件ずつ選ぶを選べば、設定資料も見比べに回る", async () => {
    // まとめて片づける道を足しても、**これまでの道は残す**
    answers.push("1件ずつ選ぶ");
    // 1件確定するごとに「次へ」を押す（ボタンであって QuickPick ではない）
    answers.push("次へ");
    picks.push("こちらを採用");

    const result = await walkConflicts(scope(), [人物ファイル, 原稿ファイル], {
      provider: new ConflictContentProvider(),
    });

    expect(result.resolved).toEqual([人物ファイル, 原稿ファイル]);
    // こちらは一括の道を通っていない。**全部が「選んだ」分になる**
    expect(result.bulkResolved).toEqual([]);
    expect(read(人物ファイル)).toContain("こちらの紹介");
  });

  test("どちらのボタンも押さなければ、取りやめる", async () => {
    const result = await walkConflicts(scope(), [人物ファイル, 原稿ファイル], {
      provider: new ConflictContentProvider(),
    });

    expect(result.aborted).toBe(true);
    expect(result.resolved).toEqual([]);
    expect(result.bulkResolved).toEqual([]);
  });
});

/**
 * 押す前に見せる中身。
 *
 * **ファイル名の羅列をやめた。** 13作品ぶんの分岐では、名前を8件並べても
 * 「どの作品がどれだけ残っているか」が分からない（2026-09-11）。
 */
describe("見比べを始める前に出す中身", () => {
  const いじめ設定 = "いじめられっ子/設定/characters/char_001.json";
  const いじめ原稿 = "いじめられっ子/本文/第1話.txt";
  const 短編設定 = "短編/設定/locations/loc_001.json";

  test("合計と内訳を先頭行に出す", () => {
    expect(describeWalkStart([いじめ設定, いじめ原稿, 短編設定])).toContain(
      "同じ箇所を両方で書き換えたものが 3件あります（設定資料 2件・原稿 1件）"
    );
  });

  test("作品ごとの件数になる", () => {
    const detail = describeWalkStartDetail([いじめ設定, いじめ原稿, 短編設定]);

    expect(detail).toContain("いじめられっ子：設定資料 1件／原稿 1件");
    expect(detail).toContain("短編：設定資料 1件／原稿 0件");
    // ファイル名は並べない
    expect(detail).not.toContain("char_001.json");
  });

  test("置き場の直下にあるものは、まとめて1つの束にする", () => {
    expect(describeWalkStartDetail(["README.md"])).toContain(
      "（置き場の直下）：設定資料 0件／原稿 1件"
    );
  });

  test("設定資料があれば、一括で片づく道を案内する", () => {
    const detail = describeWalkStartDetail([いじめ設定, いじめ原稿]);

    expect(detail).toContain("全部、新しいほうを採る");
    expect(detail).toContain("原稿だけ1件ずつ");
  });

  test("設定資料が0件なら、一括の案内を出さない", () => {
    // 押しても何も減らないボタンは出さないので、案内も出さない
    const detail = describeWalkStartDetail([いじめ原稿]);

    expect(detail).not.toContain("全部、新しいほうを採る");
    expect(detail).toContain("1件ずつ両方を並べます");
  });

  test("退避の枝から丸ごと戻せることを、必ず添える", () => {
    // **選んだあとで後悔しても戻れる**と分かれば、押す手がとまらない
    expect(describeWalkStartDetail([いじめ原稿])).toContain(
      "合わせる前の退避の枝から丸ごと戻せます"
    );
  });
});
