/**
 * 簡単ステップメニュー「4. 自己校正」の「伏線手動追加」を押すと、入力が始まる
 * （画面の自動テスト、設計書6.35・6.29。実機確認リスト F-29「押すと詳細メニューと同じ入力が
 * 始まるか」を 2026-10-09 に移した）。
 *
 * 何を見張るか：
 * - 左の列の簡単ステップメニューで「4. 自己校正」を開き、「伏線手動追加」の行を押すと、
 *   上に「伏線を手で追加（1/3）」の入力欄が出る
 * - **コマンドパレットから同じコマンド（伏線手動追加）を走らせても、同じ題の入力が出る**
 *   （ステップメニューは操作の実体を持たず、コマンドを指すだけ。同じ入力が始まることを並べて見る）
 * - 名前→内容→話数と答えると、作品の `設定/foreshadows/` に伏線が1件でき、
 *   作者が書いたもの（`autoGenerated: false`・`source: author`）として入る
 *
 * **AI は呼ばない。**
 */
import { readdir, readFile } from "node:fs/promises";
import path from "node:path";
import { expect, test } from "vitest";
import { answerInput, runCommand, waitForQuickInput, waitQuickInputClosed } from "./support/quickInput";
import { SIDEBAR_LAUNCH, scrollTreeUntilRow, showSidebar, treeRow } from "./support/sidebar";
import { E2E_WORK_TITLE, withVsCode } from "./support/vscodeApp";
import { waitUntil } from "./support/wait";
import { clearNotifications, pressWorkbenchKey } from "./support/workbenchDom";

const EPISODE = "001_はじまり.txt";
const ROW_NAME = "伏線手動追加";

async function foreshadowFiles(workFolder: string): Promise<string[]> {
  const folder = path.join(workFolder, "設定", "foreshadows");
  const names = await readdir(folder).catch(() => [] as string[]);
  return names.filter((name) => name.endsWith(".json"));
}

test("ステップメニュー「4. 自己校正」の「伏線手動追加」で入力が始まり、コマンドパレットと同じ題で、答えると伏線が1件できる", async () => {
  await withVsCode(
    "伏線手動追加の入口",
    [{ name: EPISODE, text: "　銀の懐中時計が、机の上で止まっていた。\n" }],
    async (session) => {
      const { page, workFolder } = session;
      await showSidebar(page, E2E_WORK_TITLE);

      /* ── ステップメニューの「4. 自己校正」を開き、「伏線手動追加」を押す ── */
      const step = treeRow(page, "4. 自己校正");
      await waitUntil(async () => (await step.count()) > 0, "簡単ステップメニューに「4. 自己校正」が出る");
      await step.scrollIntoViewIfNeeded();
      if ((await step.getAttribute("aria-expanded")) !== "true") await step.click();
      await waitUntil(async () => (await step.getAttribute("aria-expanded")) === "true", "「4. 自己校正」が開く");
      // 狭い窓では「4. 自己校正」の下のほうの行が描かれない（仮想化）ので、下へ送って出す
      const row = await scrollTreeUntilRow(page, "4. 自己校正", ROW_NAME);
      await row.click();
      await waitForQuickInput(page, "伏線を手で追加（1/3）", 20_000);
      await page.keyboard.press("Escape");
      await waitQuickInputClosed(page, "ステップメニューから始めた入力を Esc で止める");
      expect(await foreshadowFiles(workFolder), "Esc で止めたのに伏線ができました").toEqual([]);

      /* ── コマンドパレットから同じコマンドを走らせても、同じ題の入力が出る ── */
      await pressWorkbenchKey(page, "Escape");
      await runCommand(page, ROW_NAME);
      await waitForQuickInput(page, "伏線を手で追加（1/3）", 20_000);

      /* ── 名前→内容→話数と答える ── */
      await answerInput(page, "銀の懐中時計");
      await waitForQuickInput(page, "伏線を手で追加（2/3）");
      await answerInput(page, "止まった時計は、あの夜の約束を示している");
      await waitForQuickInput(page, "伏線を手で追加（3/3）");
      await answerInput(page, "1");
      await waitQuickInputClosed(page, "3つ目の答えで入力が閉じる");

      await waitUntil(async () => (await foreshadowFiles(workFolder)).length === 1, "設定/foreshadows/ に伏線が1件できる", 20_000);
      const [name] = await foreshadowFiles(workFolder);
      const saved = JSON.parse(await readFile(path.join(workFolder, "設定", "foreshadows", name), "utf8")) as Record<string, unknown>;
      expect(saved.label).toBe("銀の懐中時計");
      expect(saved.note).toBe("止まった時計は、あの夜の約束を示している");
      expect(saved.plantedChapter).toBe(1);
      expect(saved.source, "作者が足したものとして入っていません").toBe("author");
      expect(saved.autoGenerated, "作者が書いたものがAI生成扱いです").toBe(false);
      await clearNotifications(page);
    },
    SIDEBAR_LAUNCH
  );
});
