/**
 * 場所の略図（画面の自動テスト。設計書6.93.10・6.113。作者の裁定 2026-10-09 夜）。
 *
 * 見張ること：
 * 1. 略図が開いて、場所の点が並ぶ（手がかりの無い場所は棚に並ぶ）
 * 2. 点を引っ張ると、その場所の記録に `sketchPosition` が保存される。
 *    **関係（`relations`）も確定の印（`autoGenerated`）も変わらない**
 * 3. 略図を閉じて開き直しても、置いた位置に点がある（作者の印つき）
 * 4. 食い違いの赤い線を押すと、提案パネルの「矛盾」に場所の行が並ぶ
 *
 * 「抽出し直しても位置が消えない」は AI を呼ばないと起こせないので、ここでは見ない
 * （マージの単体テスト `cross/locationSketchPositionProtected.test.ts` が見張る）。
 *
 * 場所の記録は製品が読む形（`models/location.ts` の `emptyLocation` に中身を足したもの）で、
 * VS Code を起こす前に置く。**AI は呼ばない。**
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import type { Frame } from "playwright-core";
import { expect, test } from "vitest";
import { emptyLocation, type Location, type LocationRelation } from "../../src/models/location";
import { DEFAULT_SETTINGS_DIR } from "../../src/models/types";
import { withVsCode, type E2ESession } from "./support/vscodeApp";
import { activeTabNames, editorGroupTabs, pressWorkbenchKey } from "./support/workbenchDom";
import { holdsFor, waitUntil } from "./support/wait";

const OPEN_SKETCH_KEY = "ctrl+alt+shift+g";
const OPEN_SKETCH_PRESS = "Control+Alt+Shift+G";
const CLOSE_EDITOR_KEY = "ctrl+alt+shift+k";
const CLOSE_EDITOR_PRESS = "Control+Alt+Shift+K";

const KEYBINDINGS = [
  { key: OPEN_SKETCH_KEY, command: "novelai.openLocationSketch" },
  { key: CLOSE_EDITOR_KEY, command: "workbench.action.closeActiveEditor" },
];

function rel(
  kind: LocationRelation["kind"],
  target: string,
  value: string | null = null,
  extra: Partial<LocationRelation> = {}
): LocationRelation {
  return { kind, target, targetId: null, value, chapters: [], evidence: null, authorLocked: false, ...extra };
}

/** 港を真ん中に、北に学校、東に灯台。王城は手がかりが無い（棚） */
function harbor(): Location[] {
  return [
    { ...emptyLocation("loc_001", "港"), appearedChapters: [1] },
    {
      ...emptyLocation("loc_002", "学校"),
      appearedChapters: [1],
      relations: [rel("direction", "港", "北"), rel("distance", "港", "徒歩10分")],
    },
    {
      ...emptyLocation("loc_003", "灯台"),
      appearedChapters: [1],
      relations: [rel("direction", "港", "東"), rel("distance", "港", "徒歩20分")],
    },
    { ...emptyLocation("loc_004", "王城"), appearedChapters: [1] },
  ];
}

function locationsFolder(workFolder: string): string {
  return path.join(workFolder, DEFAULT_SETTINGS_DIR, "locations");
}

function fileOf(workFolder: string, location: Location): string {
  return path.join(locationsFolder(workFolder), `${location.id}_${location.name}.json`);
}

async function writeLocations(workFolder: string, locations: readonly Location[]): Promise<void> {
  await mkdir(locationsFolder(workFolder), { recursive: true });
  for (const location of locations) {
    await writeFile(fileOf(workFolder, location), `${JSON.stringify(location, null, 2)}\n`, "utf8");
  }
}

/** 保存は置き換えで書かれる。読めるまで少し待って読む */
async function readLocation(file: string): Promise<Location | undefined> {
  try {
    return JSON.parse(await readFile(file, "utf8")) as Location;
  } catch {
    return undefined;
  }
}

/** 略図の面（SVG の場所の点 `.s-point` を持つ） */
async function sketchFrame(session: E2ESession): Promise<Frame | undefined> {
  for (const frame of session.page.frames()) {
    const has = await frame.evaluate(() => document.querySelector(".s-point") !== null).catch(() => false);
    if (has) return frame;
  }
  return undefined;
}

async function openSketch(session: E2ESession, expectedPoints: number): Promise<Frame> {
  await pressWorkbenchKey(session.page, OPEN_SKETCH_PRESS);
  let found: Frame | undefined;
  await waitUntil(
    async () => {
      found = await sketchFrame(session);
      return found !== undefined && (await found.locator(".s-point").count()) === expectedPoints;
    },
    `場所の略図に点が${expectedPoints}つ並ぶ`,
    30_000
  );
  if (!found) throw new Error("場所の略図の面が見つかりません");
  return found;
}

/** 点の円の、図の上の中心（cx, cy） */
async function dotCenter(frame: Frame, id: string): Promise<{ x: number; y: number }> {
  return frame.evaluate((target) => {
    const dot = document.querySelector(`.s-point[data-id="${target}"] .s-dot`);
    if (!dot) throw new Error(`${target} の点がありません`);
    return { x: Number(dot.getAttribute("cx")), y: Number(dot.getAttribute("cy")) };
  }, id);
}

async function dragDot(session: E2ESession, frame: Frame, id: string, dx: number, dy: number): Promise<void> {
  const box = await frame.locator(`.s-point[data-id="${id}"] .s-dot`).boundingBox();
  if (!box) throw new Error(`${id} の点が画面にありません`);
  const x = box.x + box.width / 2;
  const y = box.y + box.height / 2;
  const { mouse } = session.page;
  await mouse.move(x, y);
  await mouse.down();
  await mouse.move(x + dx / 2, y + dy / 2, { steps: 5 });
  await mouse.move(x + dx, y + dy, { steps: 5 });
  await mouse.up();
}

test("略図が開いて点が並び、引っ張った位置が場所の資料に残り、開き直しても位置が残る（関係と確定の印は変わらない）", async () => {
  const locations = harbor();
  await withVsCode(
    "場所の略図",
    [{ name: "001_はじまり.txt", text: "港から学校が見えた。\n" }],
    async (session) => {
      const frame = await openSketch(session, 4);

      // 手がかりの無い王城は棚に、ほかの3つは図に
      const kinds = await frame.evaluate(() =>
        Array.from(document.querySelectorAll(".s-point")).map(
          (node) => `${node.getAttribute("data-id")}:${node.getAttribute("data-kind")}`
        )
      );
      expect(kinds.sort()).toEqual(["loc_001:point", "loc_002:point", "loc_003:point", "loc_004:shelf"]);
      // 決まった位置（方角と距離がそろう）は塗った点で、学校は港の北（上）
      const port = await dotCenter(frame, "loc_001");
      const school = await dotCenter(frame, "loc_002");
      expect(school.y).toBeLessThan(port.y);
      expect(await frame.locator(".s-line.s-dashed").count(), "決まった線が点線で描かれています").toBe(0);

      // 灯台を引っ張る
      const before = await dotCenter(frame, "loc_003");
      await dragDot(session, frame, "loc_003", 60, 50);
      const lighthouseFile = fileOf(session.workFolder, locations[2]);
      let saved: Location | undefined;
      await waitUntil(
        async () => (saved = await readLocation(lighthouseFile))?.sketchPosition !== undefined,
        "灯台の資料に置いた位置が書かれる",
        15_000
      );
      // 図の1単位が何画素かは窓と図の広さで変わる（字を縮めない作り。2026-10-10）ので、動いた向きだけを見る
      expect(saved!.sketchPosition!.x).toBeGreaterThan(before.x + 5);
      expect(saved!.sketchPosition!.y).toBeGreaterThan(before.y + 5);
      // 位置のほかは変えない
      expect(saved!.relations).toEqual(locations[2].relations);
      expect(saved!.autoGenerated).toBe(true);
      // ほかの場所のファイルには触らない
      const portSaved = await readLocation(fileOf(session.workFolder, locations[0]));
      expect(portSaved).not.toHaveProperty("sketchPosition");

      // 図にも作者の印が付く
      await waitUntil(
        async () => (await frame.locator('.s-point[data-id="loc_003"] .s-author-mark').count()) === 1,
        "灯台に作者が置いた印が付く",
        15_000
      );

      // 閉じて開き直しても、置いた所にある
      await pressWorkbenchKey(session.page, CLOSE_EDITOR_PRESS);
      await waitUntil(async () => (await sketchFrame(session)) === undefined, "略図が閉じる", 15_000);
      const reopened = await openSketch(session, 4);
      const after = await dotCenter(reopened, "loc_003");
      expect(after.x).toBeCloseTo(saved!.sketchPosition!.x, 1);
      expect(after.y).toBeCloseTo(saved!.sketchPosition!.y, 1);
      expect(await reopened.locator('.s-point[data-id="loc_003"] .s-author-mark').count()).toBe(1);
    },
    {
      keybindings: KEYBINDINGS,
      prepareWork: ({ workFolder }) => writeLocations(workFolder, locations),
    }
  );
});

test("棚の場所を図へ引っ張ると、その位置が残って棚から外れる", async () => {
  const locations = harbor();
  await withVsCode(
    "場所の略図の棚",
    [{ name: "001_はじまり.txt", text: "港から学校が見えた。\n" }],
    async (session) => {
      const frame = await openSketch(session, 4);
      await dragDot(session, frame, "loc_004", 0, -120);
      const castleFile = fileOf(session.workFolder, locations[3]);
      await waitUntil(
        async () => (await readLocation(castleFile))?.sketchPosition !== undefined,
        "王城の資料に置いた位置が書かれる",
        15_000
      );
      await waitUntil(
        async () =>
          (await frame.locator('.s-point[data-id="loc_004"]').getAttribute("data-kind")) === "point",
        "王城が棚から図へ移る",
        15_000
      );
    },
    {
      keybindings: KEYBINDINGS,
      prepareWork: ({ workFolder }) => writeLocations(workFolder, locations),
    }
  );
});

test("食い違いの赤い線を押すと、提案パネルの「矛盾」に場所の行が並ぶ", async () => {
  // 第3話「学校は港の北」と第7話「港は学校の北」が食い違う
  const locations: Location[] = [
    {
      ...emptyLocation("loc_001", "港"),
      relations: [rel("direction", "学校", "北", { chapters: [2], evidence: "港は学校の北に見えた" })],
    },
    {
      ...emptyLocation("loc_002", "学校"),
      relations: [
        rel("direction", "港", "北", { chapters: [1], evidence: "学校は港の北の高台にある" }),
        rel("distance", "港", "徒歩10分", { chapters: [1] }),
      ],
    },
  ];
  await withVsCode(
    "場所の略図の食い違い",
    [
      { name: "001_はじまり.txt", text: "学校は港の北の高台にある。\n" },
      { name: "002_つづき.txt", text: "港は学校の北に見えた。\n" },
    ],
    async (session) => {
      const frame = await openSketch(session, 2);
      expect(await frame.locator(".s-line.s-conflict").count()).toBe(1);
      expect(await frame.locator(".s-conflict-label").textContent()).toBe("食い違い：第1話／第2話");

      await frame.locator(".s-conflict-label").click({ force: true });

      // 提案パネルの「矛盾」に、場所の行が並ぶ
      let found = false;
      await waitUntil(
        async () => {
          for (const candidate of session.page.frames()) {
            const has = await candidate
              .evaluate(() =>
                Array.from(document.querySelectorAll(".issue .badge.cat")).some(
                  (badge) => badge.textContent === "場所"
                )
              )
              .catch(() => false);
            if (has) found = true;
          }
          return found;
        },
        "提案パネルに場所の行が並ぶ",
        30_000
      );

      // 本文の同じ所も開くが、**提案パネルを本文の後ろに隠さない**（作者の裁定 2026-10-10）
      const proposalsInFront = async () =>
        (await activeTabNames(session.page)).some((name) => name.startsWith("提案"));
      await waitUntil(
        async () =>
          (await proposalsInFront()) &&
          (await editorGroupTabs(session.page)).flat().includes("002_つづき.txt"),
        "本文が開き、提案パネルが前に出ている",
        30_000
      );
      await holdsFor(proposalsInFront, "提案パネルが前に出ている状態", 2_000);
    },
    {
      keybindings: KEYBINDINGS,
      prepareWork: ({ workFolder }) => writeLocations(workFolder, locations),
    }
  );
});

/** 王都・港町・港など、乗り物の混ざる広い作品（図を窓に合わせると大きく縮む） */
function wideWorld(): Location[] {
  return [
    { ...emptyLocation("loc_001", "王都") },
    { ...emptyLocation("loc_002", "大聖堂"), relations: [rel("within", "王都"), rel("direction", "市場", "北"), rel("distance", "市場", "徒歩10分")] },
    { ...emptyLocation("loc_003", "市場"), relations: [rel("within", "王都")] },
    { ...emptyLocation("loc_004", "港町"), relations: [rel("direction", "王都", "東"), rel("distance", "王都", "馬車で半日")] },
    { ...emptyLocation("loc_005", "港"), relations: [rel("within", "港町")] },
    { ...emptyLocation("loc_006", "学校"), relations: [rel("direction", "港", "北"), rel("distance", "港", "徒歩1時間")] },
    { ...emptyLocation("loc_007", "灯台"), relations: [rel("adjacent", "港")] },
    { ...emptyLocation("loc_008", "黒い森"), relations: [rel("direction", "王都", "北")] },
    { ...emptyLocation("loc_009", "北の村") },
    { ...emptyLocation("loc_010", "峠"), relations: [rel("direction", "北の村", "西"), rel("distance", "北の村", "徒歩3時間")] },
  ];
}

interface Rect {
  text: string;
  left: number;
  right: number;
  top: number;
  bottom: number;
}

async function rectsOf(frame: Frame, selector: string): Promise<Rect[]> {
  return frame.evaluate(
    (query) =>
      Array.from(document.querySelectorAll(query)).map((node) => {
        const rect = node.getBoundingClientRect();
        return { text: node.textContent ?? "", left: rect.left, right: rect.right, top: rect.top, bottom: rect.bottom };
      }),
    selector
  );
}

test("図を窓に合わせて縮めても、場所の名前と線の字は縮めず、名前どうしは重ならない（作者の裁定 2026-10-10）", async () => {
  const locations = wideWorld();
  await withVsCode(
    "場所の略図の字の大きさ",
    [{ name: "001_はじまり.txt", text: "王都の東に港町がある。\n" }],
    async (session) => {
      const frame = await openSketch(session, locations.length);
      // 字の高さ（画面の画素）。名前は15px・線の字は12px で描く
      const names = await rectsOf(frame, ".s-name");
      const labels = await rectsOf(frame, ".s-line-label");
      for (const name of names) {
        expect(name.bottom - name.top, `「${name.text}」の字が縮んでいます`).toBeGreaterThanOrEqual(14);
      }
      for (const label of labels) {
        expect(label.bottom - label.top, `「${label.text}」の字が縮んでいます`).toBeGreaterThanOrEqual(11);
      }
      // 名前どうしは重ならない
      const overlaps: string[] = [];
      names.forEach((a, index) => {
        for (const b of names.slice(index + 1)) {
          if (a.left < b.right && b.left < a.right && a.top < b.bottom && b.top < a.bottom) {
            overlaps.push(`${a.text}／${b.text}`);
          }
        }
      });
      expect(overlaps, "名前が重なっています").toEqual([]);
      // 全体を合わせたとき、端の名前が図の欄の外へ切れない
      const [canvas] = await rectsOf(frame, "svg#sketch");
      const clipped = names
        .filter((name) => name.left < canvas.left - 1 || name.right > canvas.right + 1 || name.top < canvas.top - 1 || name.bottom > canvas.bottom + 1)
        .map((name) => name.text);
      expect(clipped, "欄の外へ切れた名前").toEqual([]);
    },
    {
      keybindings: KEYBINDINGS,
      prepareWork: ({ workFolder }) => writeLocations(workFolder, locations),
    }
  );
});
