/**
 * 改行が CRLF の原稿でも LF の原稿でも、用語の色・右クリックの設定資料・ルビと傍点・
 * 下の欄の字数が正しく働く（画面の自動テスト、設計書6.113・6.34.5・6.25。実機確認
 * リスト F-27・F-28・F-32・F-35 を 2026-10-04 に移した）。
 *
 * 何を見張るか：
 * - **用語の色が正しい語に載る**（0.24.8 まで、CRLF の原稿では1行ごとに1字ずつ
 *   後ろへずれた）。見た目ではなく、色を付けた範囲（Custom Highlight API の
 *   `novelai-term-character`）が指す字が、人物の名前そのものかで測る
 * - **右クリックの「設定資料を見る」が、押した語の資料を出す**。本文から開いた
 *   設定資料パネルは一覧を畳んで出し、開いたままで別の語を右クリックしても
 *   その語へ切り替わる。作者が一覧を開いたあと、ふつうの道で開けば一覧が出ている
 * - **ルビ・傍点が振れる**（CRLF の原稿で「本文が変わった」と誤って断られていた）。
 *   振ったあとも改行は CRLF のまま。**見本の話は .md にする**——.txt では傍点の
 *   書き方がサイトごとに違うので、傍点は「.md で使えます」と断るのが正しい
 *   （ルビは .txt でも振れる）
 * - **下の欄に「作品／このファイル／この話で今日」が出て、保存すると今日の量が増える**
 */
import { readFile } from "node:fs/promises";
import path from "node:path";
import type { Frame } from "playwright-core";
import { expect, test } from "vitest";
import { emptyCharacter } from "../../src/models/character";
import { composeText, footText, openEpisode, placeCaretAfter, selectText } from "./support/manuscriptFrame";
import { answerInput, runCommand, waitForQuickInput } from "./support/quickInput";
import { charactersFolder, settingsPanelFrame, writeCharactersTo } from "./support/settingsFixture";
import { E2E_WORK_TITLE, withVsCode, type E2ESession } from "./support/vscodeApp";
import { waitUntil } from "./support/wait";
import { dismissWorkbenchHover, pickQuickPickRow, quickPickTitle, readTabState, tabIsDirty } from "./support/workbenchDom";

const CRLF_EPISODE = "001_改行CRLF.md";
const LF_EPISODE = "002_改行LF.md";
const NAMES = ["三門太志", "密倉文佳"];
/** 名前が3行目より下にも来る本文（CRLF ではずれが行ごとに積もるので、下の行ほど目立つ） */
const BODY_LINES = [
  "一行目の文。",
  "二行目に三門太志が来た。",
  "三行目の文。",
  "四行目に密倉文佳がいた。",
  "五行目の三門太志。",
];

/** 人物の資料を、製品が読む形で置く（`設定/characters/`） */
async function writeCharacters(session: E2ESession): Promise<void> {
  await writeCharactersTo(
    await charactersFolder(session),
    NAMES.map((name, index) => ({ ...emptyCharacter(`char_00${index + 1}`, name), autoGenerated: false }))
  );
}

/** 人物の色が載っている字（`novelai-term-character` の範囲が指す字）を、本文の順に */
async function coloredCharacterTerms(frame: Frame): Promise<string[]> {
  return frame.evaluate(() => {
    const registry = (globalThis as unknown as {
      CSS?: { highlights?: { get(name: string): Iterable<AbstractRange> | undefined } };
    }).CSS?.highlights;
    const highlight = registry?.get("novelai-term-character");
    if (!highlight) return [];
    const ranges = Array.from(highlight) as Range[];
    ranges.sort((a, b) => a.compareBoundaryPoints(Range.START_TO_START, b));
    return ranges.map((range) => range.toString());
  });
}

/** 組んで書く面の `nth` 番目（0から）の `word` を右クリックし、品書きの `item` を押す */
async function rightClickWord(frame: Frame, word: string, nth: number, item: string): Promise<void> {
  const position = await frame.evaluate(
    ({ text, index }) => {
      const compose = document.getElementById("compose");
      if (!compose) return undefined;
      const walker = document.createTreeWalker(compose, NodeFilter.SHOW_TEXT);
      let seen = 0;
      for (let node = walker.nextNode(); node; node = walker.nextNode()) {
        let at = (node.textContent ?? "").indexOf(text);
        while (at >= 0) {
          if (seen === index) {
            const range = document.createRange();
            range.setStart(node, at + 1);
            range.setEnd(node, at + 2);
            const rect = range.getBoundingClientRect();
            const box = compose.getBoundingClientRect();
            return { x: rect.left + rect.width / 2 - box.left, y: rect.top + rect.height / 2 - box.top };
          }
          seen += 1;
          at = (node.textContent ?? "").indexOf(text, at + 1);
        }
      }
      return undefined;
    },
    { text: word, index: nth }
  );
  if (!position) throw new Error(`組んで書く面に ${nth + 1} 番目の「${word}」が見つかりません`);
  await frame.locator("#compose").click({ button: "right", position });
  const entry = frame.locator("#menu .item", { hasText: item }).first();
  await waitUntil(async () => (await entry.count()) > 0 && (await entry.isVisible()), `右クリックの品書きに「${item}」が出る`);
  await entry.click();
}

async function panelState(frame: Frame): Promise<{ collapsed: boolean; detail: string }> {
  return frame.evaluate(() => ({
    collapsed: document.body.classList.contains("collapsed"),
    detail: document.getElementById("detail")?.innerText ?? "",
  }));
}

/**
 * 落ちたときに読む、列とタブと面の様子（2026-10-04、遅い機械で最後の段の
 * ［一覧を出す］／［傍点］を押すところが30秒で時間切れになった調べ）。
 * 押す相手の面が、別のタブの裏に回って見えていないのかを見分ける
 */
async function layoutState(session: E2ESession, frames: Record<string, Frame | undefined>): Promise<string> {
  const { page } = session;
  // タブの読み方は workbenchDom.ts の1か所に任せる（1.141.0 で名前の形が変わった）
  const groups = await readTabState(page)
    .then((state) =>
      state.map((group) => ({
        active: group.active,
        tabs: group.tabs.map((tab) => tab.name + (tab.active ? "［前］" : "")),
      }))
    )
    .catch(() => "（読めません）");
  const faces: string[] = [];
  for (const [name, frame] of Object.entries(frames)) {
    if (!frame) {
      faces.push(`${name}：無し`);
      continue;
    }
    const state = await frame
      .evaluate(() => {
        const look = (id: string) => {
          const element = document.getElementById(id) as HTMLElement | null;
          if (!element) return `${id}=無し`;
          const box = element.getBoundingClientRect();
          return `${id}=${Math.round(box.width)}x${Math.round(box.height)}${element.offsetParent ? "" : "(隠れ)"}`;
        };
        return `${document.visibilityState}／${window.innerWidth}x${window.innerHeight}／${look("reopen")}／${look("emph")}`;
      })
      .catch((error: unknown) => `読めません（${String(error).slice(0, 80)}）`);
    // どの iframe の中の面か（外側の iframe の name）。見えている面と取り違えていないかを見る
    const outer = frame.parentFrame()?.name() ?? "";
    faces.push(`${name}：${state}／iframe=${outer.slice(0, 8)}`);
  }
  // 本体の側の WebView の iframe（重なりの順・見えているか・場所）
  const iframes = await page
    .evaluate(() =>
      Array.from(document.querySelectorAll("iframe.webview")).map((element) => {
        const frameElement = element as HTMLIFrameElement;
        const box = frameElement.getBoundingClientRect();
        const style = getComputedStyle(frameElement.parentElement ?? frameElement);
        return `${frameElement.name.slice(0, 8)}@${Math.round(box.left)},${Math.round(box.top)} ${Math.round(box.width)}x${Math.round(box.height)} vis=${style.visibility}/${style.display}`;
      })
    )
    .catch(() => ["（読めません）"]);
  return `（列：${JSON.stringify(groups)}／面：${faces.join("／")}／本体の iframe：${JSON.stringify(iframes)}）`;
}

/** 原稿ファイルの生の中身（改行を揃えずに読む） */
async function rawFile(session: E2ESession, name: string): Promise<string> {
  return readFile(path.join(session.manuscriptFolder, name), "utf8");
}

/** ルビと傍点を振り、保存してファイルに入るまで待つ */
async function rubyAndEmphasis(session: E2ESession, frame: Frame, episode: string): Promise<void> {
  const { page } = session;
  await selectText(frame, "一行目");
  // 狭い窓では、本体の吹き出しが上の帯のボタンに重なって押せない（dismissWorkbenchHover）
  await dismissWorkbenchHover(page);
  await frame.locator("#ruby").click();
  await waitForQuickInput(page, "「一行目」の読み");
  await answerInput(page, "いちぎょうめ");
  await waitUntil(async () => (await frame.locator("#compose ruby").count()) > 0, `${episode}：画面にルビが組まれる`);

  await selectText(frame, "三行目");
  await dismissWorkbenchHover(page);
  await frame.locator("#emph").click();
  await waitUntil(async () => await tabIsDirty(page, episode), `${episode}：傍点で文書が変わる`);
  // 送り直しが画面へ届いてから保存する（manuscriptEditor.test.ts の傍点の件と同じ理由）
  await waitUntil(async () => (await frame.locator("#compose .emphasis").count()) > 0, `${episode}：画面に傍点が出る`);
  await page.keyboard.press("Control+KeyS");
  await waitUntil(async () => {
    const text = await rawFile(session, episode);
    return text.includes("{一行目|いちぎょうめ}") && text.includes("{{三行目}}");
  }, `${episode}：ルビと傍点がファイルに入る`).catch(async (error: unknown) => {
    throw new Error(`${String(error)}（ファイル：${JSON.stringify(await rawFile(session, episode))}／下の欄：${await footText(frame, "note")}）`);
  });
}

test("CRLF と LF の原稿で、人物の色が名前そのものに載り、右クリックの設定資料が押した語を一覧を畳んで出し、ルビ・傍点が振れて改行が保たれ、下の欄の今日の量が保存で増える", async () => {
  await withVsCode(
    "改行と用語・ルビ",
    [
      { name: CRLF_EPISODE, text: BODY_LINES.join("\r\n") + "\r\n" },
      { name: LF_EPISODE, text: BODY_LINES.join("\n") + "\n" },
    ],
    async (session) => {
      const { page } = session;
      await writeCharacters(session);

      /* ── CRLF の原稿 ── */
      const frame = await openEpisode(page, CRLF_EPISODE, "五行目の三門太志");
      const expectedTerms = ["三門太志", "密倉文佳", "三門太志"];
      await waitUntil(
        async () => (await coloredCharacterTerms(frame)).length === expectedTerms.length,
        "CRLF：人物の色が3か所に付く"
      ).catch(async (error: unknown) => {
        throw new Error(`${String(error)}（色の範囲：${JSON.stringify(await coloredCharacterTerms(frame))}）`);
      });
      expect(await coloredCharacterTerms(frame), "CRLF：色の範囲が名前からずれています").toEqual(expectedTerms);

      // 右クリックの「設定資料を見る」：押した語の資料が、一覧を畳んで出る
      await rightClickWord(frame, "密倉文佳", 0, "設定資料を見る");
      let settings: Frame | undefined;
      await waitUntil(async () => {
        settings = await settingsPanelFrame(session);
        return settings !== undefined && (await panelState(settings)).detail.includes("密倉文佳");
      }, "設定資料パネルに「密倉文佳」が出る", 30_000);
      if (!settings) throw new Error("設定資料パネルが見つかりません");
      const panel = settings;
      expect((await panelState(panel)).collapsed, "本文から開いた設定資料の一覧が畳まれていません").toBe(true);

      // 開いたままで、別の行の別の語を右クリック → その語へ切り替わる
      await rightClickWord(frame, "三門太志", 1, "設定資料を見る");
      await waitUntil(async () => {
        const state = await panelState(panel);
        return state.detail.includes("三門太志") && !state.detail.includes("密倉文佳");
      }, "開いたままの設定資料パネルが「三門太志」へ切り替わる").catch(async (error: unknown) => {
        throw new Error(`${String(error)}（詳細：${(await panelState(panel)).detail.slice(0, 120)}）`);
      });


      // 下の欄の字数（作品／このファイル／この話で今日）
      await waitUntil(async () => {
        const counts = await footText(frame, "counts");
        return counts.includes("作品 ") && counts.includes("このファイル ") && counts.includes("この話で今日 ");
      }, "下の欄に作品・このファイル・この話で今日の字数が出る").catch(async (error: unknown) => {
        throw new Error(`${String(error)}（下の欄：${await footText(frame, "counts")}）`);
      });
      const todayOf = (counts: string) => Number((/この話で今日 \+?(-?[\d,]+)字/.exec(counts)?.[1] ?? "NaN").replace(/,/g, ""));

      // ルビ・傍点（CRLF）。振ったあとも改行は CRLF のまま
      await rubyAndEmphasis(session, frame, CRLF_EPISODE);
      const crlf = await rawFile(session, CRLF_EPISODE);
      expect(crlf, "CRLF の原稿に LF だけの改行が混ざりました").not.toMatch(/[^\r]\n/);
      expect(crlf.split("\r\n").length).toBe(BODY_LINES.length + 1);

      /*
        保存すると「この話で今日」が増える。**作品の最初の保存は基準を置くだけで数えない**
        （設計書6.3.2。既にある本文を「今日書いた」ことにしないため）——上のルビ・傍点の
        保存がその1回目に当たる。作者の作品には前の日までの基準があるので、ここから先が
        作者の画面で起きることと同じ
      */
      const todayBefore = todayOf(await footText(frame, "counts"));
      await placeCaretAfter(frame, "五行目の");
      await page.keyboard.insertText("足した字");
      await waitUntil(async () => (await composeText(frame)).includes("五行目の足した字"), "打った字が画面に出る");
      await page.keyboard.press("Control+KeyS");
      await waitUntil(
        async () => (await rawFile(session, CRLF_EPISODE)).includes("五行目の足した字三門太志。"),
        "打った字がファイルに入る"
      );
      expect(await rawFile(session, CRLF_EPISODE), "打って保存したら LF だけの改行が混ざりました").not.toMatch(/[^\r]\n/);
      await waitUntil(
        async () => todayOf(await footText(frame, "counts")) >= todayBefore + 4,
        `保存すると「この話で今日」が4字以上増える（前：${todayBefore}）`
      ).catch(async (error: unknown) => {
        throw new Error(`${String(error)}（下の欄：${await footText(frame, "counts")}）`);
      });

      // 落ちたときの様子に添えるため、外で持つ（下の catch）
      let lfFrameSeen: Frame | undefined;
      try {
      /* ── LF の原稿（これまでどおり動くか） ── */
      const lfFrame = await openEpisode(page, LF_EPISODE, "五行目の三門太志");
      lfFrameSeen = lfFrame;
      await waitUntil(
        async () => (await coloredCharacterTerms(lfFrame)).length === expectedTerms.length,
        "LF：人物の色が3か所に付く"
      );
      expect(await coloredCharacterTerms(lfFrame), "LF：色の範囲が名前からずれています").toEqual(expectedTerms);
      await rubyAndEmphasis(session, lfFrame, LF_EPISODE);
      expect(await rawFile(session, LF_EPISODE), "LF の原稿に CRLF が混ざりました").not.toContain("\r");

      /* ── 設定資料パネルを、ふつうの道でも開く（最後に回す。開いたあとは焦点がパネルへ移る） ── */
      // 作者が［一覧を出す］で一覧を開いたあと、ふつうの道（設定資料集閲覧）で開くと一覧が出ている
      // 狭い窓では、タブの吹き出しがパネルの上に重なって押せない（dismissWorkbenchHover）
      await dismissWorkbenchHover(page);
      await panel.locator("#reopen").click();
      await waitUntil(async () => !(await panelState(panel)).collapsed, "［一覧を出す］で一覧が開く");
      await runCommand(page, "設定資料集閲覧");
      if ((await quickPickTitle(page)) !== undefined) await pickQuickPickRow(page, E2E_WORK_TITLE);
      await waitUntil(
        async () => (await panel.locator("#list .item", { hasText: "密倉文佳" }).count()) > 0,
        "ふつうの道で開いた設定資料パネルに人物の一覧が出る"
      );
      expect((await panelState(panel)).collapsed, "ふつうの道で開いたのに一覧が畳まれています").toBe(false);
      } catch (error) {
        if (error instanceof Error) {
          error.message += await layoutState(session, { CRLFの原稿: frame, LFの原稿: lfFrameSeen,設定資料パネル: panel });
        }
        throw error;
      }
    }
  );
});
