/**
 * 設定資料パネルで別名を「別の人物に分ける」と、開いたままの本文の用語の色分けが
 * その場で引き直される（画面の自動テスト、設計書6.5.8・6.113）。
 *
 * 実機確認リスト F-13 の「その場で本文の色分けが変わるか（VS Codeを開き直さないと変わらないなら
 * 直っていない）」を機械へ移したもの。色そのものは名前の持ち主が変わっても同じ緑なので、
 * **色が指す先（右クリックの「設定資料を見る」が出す人物）が変わるか**で測る：
 *
 * - 分ける前：別名「お嬢様」を右クリックすると、持ち主の「密倉文佳」の資料が出る
 * - 分けたあと（原稿エディターは開いたまま・開き直さない）：同じ「お嬢様」を右クリックすると、
 *   新しくできた「お嬢様」の資料が出る。色が付く範囲（`novelai-term-character`）は変わらず残る
 *
 * 分けたあとのファイル（元の人物から別名が外れ、新しい人物が名前だけでできる）も見る。
 * **AI は呼ばない。**
 */
import { readdir, readFile } from "node:fs/promises";
import path from "node:path";
import type { Frame } from "playwright-core";
import { expect, test } from "vitest";
import { emptyCharacter, type Character } from "../../src/models/character";
import { openEpisode } from "./support/manuscriptFrame";
import { defaultCharactersFolder, settingsPanelFrame, writeCharactersTo } from "./support/settingsFixture";
import { withVsCode, type E2ESession, type LaunchOptions } from "./support/vscodeApp";
import { waitUntil } from "./support/wait";
import { activateTab, dialogText, editorGroupTabs, pressDialogButton, tabNamesInclude } from "./support/workbenchDom";

const EPISODE = "001_お屋敷.md";
const TEXT = "密倉文佳は窓の外を見た。\nお嬢様は静かに笑った。\n";

const launchOptions: LaunchOptions = {
  prepareWork: async ({ workFolder }) => {
    await writeCharactersTo(defaultCharactersFolder(workFolder), [
      { ...emptyCharacter("char_001", "密倉文佳"), aliases: ["お嬢様"], autoGenerated: false },
    ]);
  },
};

async function coloredCharacterTerms(frame: Frame): Promise<string[]> {
  return frame.evaluate(() => {
    const registry = (globalThis as unknown as {
      CSS?: { highlights?: { get(name: string): Iterable<AbstractRange> | undefined } };
    }).CSS?.highlights;
    const highlight = registry?.get("novelai-term-character");
    if (!highlight) return [];
    const ranges = Array.from(highlight) as Range[];
    ranges.sort((a, b) => a.compareBoundaryPoints(Range.START_TO_START, b));
    return ranges.map((range) => range.toString());
  });
}

/** 組んで書く面の `word` を右クリックし、品書きの「設定資料を見る」を押す */
async function showSettingsOf(frame: Frame, word: string): Promise<void> {
  const position = await frame.evaluate((text) => {
    const compose = document.getElementById("compose");
    if (!compose) return undefined;
    const walker = document.createTreeWalker(compose, NodeFilter.SHOW_TEXT);
    for (let node = walker.nextNode(); node; node = walker.nextNode()) {
      const at = (node.textContent ?? "").indexOf(text);
      if (at >= 0) {
        const range = document.createRange();
        range.setStart(node, at + 1);
        range.setEnd(node, at + 2);
        const rect = range.getBoundingClientRect();
        const box = compose.getBoundingClientRect();
        return { x: rect.left + rect.width / 2 - box.left, y: rect.top + rect.height / 2 - box.top };
      }
    }
    return undefined;
  }, word);
  if (!position) throw new Error(`組んで書く面に「${word}」が見つかりません`);
  await frame.locator("#compose").click({ button: "right", position });
  const entry = frame.locator("#menu .item", { hasText: "設定資料を見る" }).first();
  await waitUntil(async () => (await entry.count()) > 0 && (await entry.isVisible()), "右クリックの品書きに「設定資料を見る」が出る");
  await entry.click();
}

/** 設定資料パネルが開いている人物の名前欄（詳細の入力欄の値） */
async function shownNames(panel: Frame): Promise<string[]> {
  return panel.evaluate(() =>
    Array.from(document.querySelectorAll<HTMLInputElement | HTMLTextAreaElement>("#detail input, #detail textarea")).map(
      (field) => field.value
    )
  );
}

async function charactersOnDisk(session: E2ESession): Promise<Character[]> {
  const folder = path.join(session.workFolder, "設定", "characters");
  const files = (await readdir(folder).catch(() => [])).filter((name) => name.endsWith(".json"));
  const result: Character[] = [];
  for (const file of files) {
    const raw = await readFile(path.join(folder, file), "utf8").catch(() => "");
    if (raw) result.push(JSON.parse(raw) as Character);
  }
  return result;
}

test("別名を別の人物に分けると、開いたままの本文の「お嬢様」の色が指す先が、開き直さずに新しい人物へ変わる", async () => {
  await withVsCode(
    "分けたあとの色分け",
    [{ name: EPISODE, text: TEXT }],
    async (session) => {
      const { page } = session;
      const frame = await openEpisode(page, EPISODE, "お嬢様は静かに笑った");

      // 色は別名にも付いている（分ける前）
      await waitUntil(async () => (await coloredCharacterTerms(frame)).includes("お嬢様"), "分ける前：「お嬢様」に人物の色が付く", 20_000);

      // 分ける前：「お嬢様」は密倉文佳の資料を出す
      await showSettingsOf(frame, "お嬢様");
      let panel: Frame | undefined;
      await waitUntil(async () => (panel = await settingsPanelFrame(session)) !== undefined, "設定資料パネルが開く", 30_000);
      const settings = panel as Frame;
      await waitUntil(async () => (await shownNames(settings)).includes("密倉文佳"), "分ける前：「お嬢様」の資料は持ち主の「密倉文佳」", 15_000);

      // 別の人物に分ける（確認の窓で「分ける」）
      // 同じ別名は「別名から選ぶ」（名前と入れ替える札）にも並ぶので、別人にする呼び名の行から押す
      await settings
        .locator("#detail .chips", { hasText: "別人にする呼び名" })
        .locator(".chip", { hasText: "お嬢様" })
        .first()
        .click();
      await waitUntil(async () => (await dialogText(page)) !== undefined, "分けるかの確認の窓が出る", 15_000);
      expect(await dialogText(page)).toContain("「お嬢様」を、別の人物として分けますか？");
      await pressDialogButton(page, "分ける");

      // ファイル：元の人物から別名が外れ、新しい人物ができる
      await waitUntil(async () => (await charactersOnDisk(session)).some((entry) => entry.name === "お嬢様"), "新しい人物「お嬢様」のファイルができる", 15_000);
      const people = await charactersOnDisk(session);
      expect(people.find((entry) => entry.name === "密倉文佳")?.aliases).toEqual([]);

      // 原稿エディターを開き直さずに、同じ語を右クリック：今度は新しい人物の資料
      const tabs = (await editorGroupTabs(page)).flat();
      expect(tabNamesInclude(tabs, EPISODE), `原稿のタブは開いたまま（タブ：${JSON.stringify(tabs)}）`).toBe(true);
      await activateTab(page, EPISODE);
      expect(await coloredCharacterTerms(frame), "分けたあとも「お嬢様」に色が付く").toContain("お嬢様");
      await showSettingsOf(frame, "お嬢様");
      await waitUntil(
        async () => {
          const names = await shownNames(settings);
          return names.includes("お嬢様") && !names.includes("密倉文佳");
        },
        "分けたあと：開き直さずに「お嬢様」の資料が新しい人物のものになる",
        15_000
      ).catch(async (error: unknown) => {
        throw new Error(`${String(error)}（いまの欄：${JSON.stringify(await shownNames(settings))}）`);
      });
    },
    launchOptions
  );
}, 180_000);
